### ISSUE TITLE
Roadmap chart is not up to date

### ISSUE THREAD

**Issue by garak** [symfony/symfony-docs#10105]
[Current roadmap chart](https://symfony.com/doc/current/contributing/community/releases.html) looks a bit out of date (for example, Symfony 4.2 is not shown, even if it's the current dev release).
I guess that it should be replaced with a newer image, with more new releases and maybe less old releases (it makes sense to still display 2.0?)
A possible further optimization could be using a dynamic image, like the one displayed on http://php.net/supported-versions.php

**Comment by javiereguiluz** [comment]
Closing this as fixed 😁  See https://twitter.com/symfony_en/status/1023963323300294656

@garak thanks a lot for reporting this issue and for suggesting us to get inspiration from PHP chart!
