### ISSUE TITLE
Add a link / explanation to how to access private services via the special container for testing console commands

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/symfony-docs#10132]
re: https://symfony.com/doc/current/console.html

I need to inject some private services into a console command, except the container from `$kernel->getContainer()` wouldn't allow me to do so. It led me onto a merry search to [this page](https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing) which shows how to access the 'special container' for testing. I think it'd be worth a mention in the command testing as accessing services is vital.

I would submit a pr but I couldn't figure out which rst to modify!

**Comment by javiereguiluz** [comment]
I'm closing this one as "fixed". Even if we didn't make the exact requested change ... we recently updated the documentation about [using the Symfony service container in tests](https://symfony.com/doc/current/testing.html#accessing-the-container) and we now show the three available alternatives. Cheers!
