### ISSUE TITLE
@Route and @Method in version 3.4

### ISSUE THREAD

**Issue by nzurita** [symfony/symfony-docs#10142]
Hello, working on a project with symfony 3.4 that uses `@Route` and `@Method` annotations I receive these warnings:

> User Deprecated: The "Sensio\Bundle\FrameworkExtraBundle\Configuration\Route" annotation is deprecated since version 5.2. Use "Symfony\Component\Routing\Annotation\Route" instead.
> User Deprecated: The "Sensio\Bundle\FrameworkExtraBundle\Configuration\Method" annotation is deprecated since version 5.2. Use "Symfony\Component\Routing\Annotation\Route" instead.

Changing those lines as the message states works ok for the `@Route` annotation, but not for the `@Method` one, which throws an exception "Annotation does not exist".

Searching the docs I find this page [@Route and @Method](https://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/annotations/routing.html) which omits version 3.4 in version selector (but shows 5.0). So, `@Method` annotation has dissapeared in this version? Is there another way to specify request method then?

Is this an omission in the docs or a bug (wrong deprecation message)?

Thank you

**Comment by xabbuh** [comment]
I think we shouldn't show the `@Route` annotation from SensioFrameworkExtraBundle anymore (see #10150).

**Comment by xabbuh** [comment]
It is still there, but it was deprecated in version 5.2 of the FrameworkExtraBundle. But using the `@Route` annotation from the Routing component you just make use of its `methods` option which is there to achieve the same.

**Comment by javiereguiluz** [comment]
I agree this is confusing. We're trying to fix it here: https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/585
