### ISSUE TITLE
authentication process, add image of the process, feature

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony-docs#10168]
Is it possible to add image of the authentication process, including firewall, acl, tokens, listeners (especially gurad listeners), guards, describing how everything works. 

Trying to implement custom 2fa authorization, and now I realise that is really hard to understand the whole process using the code.

**Comment by javiereguiluz** [comment]
You are right! We've added an image for the Guard authenticators (see https://symfony.com/doc/master/security/guard_authentication.html#the-guard-authenticator-methods). After #10423 was merged, we now promote Guards much more and we are deprecating or no longer explaining other older concepts. So let's close this for now as fixed thanks to this new Guard diagram. Thanks!
