### ISSUE TITLE
Code style: using short circuits for evaluations and assignments

### ISSUE THREAD

**Issue by denisvmedia** [symfony/symfony-docs#10189]
Personally, I'm not a fan of short circuits like:

```
$obj and $obj->funcCall();
```

But I can't find in the Symfony coding style recommendations if it's allowed or discouraged to use such constructions. is it covered by the docs?

**Comment by javiereguiluz** [comment]
I'm sorry we didn't reply here earlier. The code style document doesn't include recommendations for all possible cases, and this "short circuit notation" is one of those unrecommended things. We'll reconsider this in the future if more people ask about this. Thank you!
