### ISSUE TITLE
Add the twig.runtime tag in DIC list page

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony-docs#10192]
Hi everyone,

Should we add the `twig.runtime` tag in this page ? [http://symfony.com/doc/current/reference/dic_tags.html](http://symfony.com/doc/current/reference/dic_tags.html)  if yes, I can do a PR.

Thanks

**Comment by xabbuh** [comment]
I think that would make sense.

**Comment by javiereguiluz** [comment]
Fixed by #10196.
