### ISSUE TITLE
The FrameworkBundle config reference is incomplete

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#10197]
https://symfony.com/doc/current/reference/configuration/framework.html is missing the configuration for workflows at least. I haven't checked other config to identify other missing ones if any.

**Comment by javiereguiluz** [comment]
The `messenger` config is missing too. See #9963.

**Comment by LS05** [comment]
Hey @javiereguiluz can I work on this issue?
Do you have some suggestions about how to approach it?
