### ISSUE TITLE
[Security] Custom authentication provider imports removed exception

### ISSUE THREAD

**Issue by norkunas** [symfony/symfony-docs#10217]
While fixing another docs issue I've noticed that [this](https://symfony.com/doc/current/security/custom_authentication_provider.html#the-authentication-provider) example imports removed `Symfony\Component\Security\Core\Exception\NonceExpiredException` since v4.
How should we proceed fixing this?

**Comment by xabbuh** [comment]
A quick fix could be just to throw an instance of the generic `AuthenticationException` and add a comment above it that in a real world application it would make sense to throw a custom exception extending the generic one.
