### ISSUE TITLE
Templating: indicate that configuration is required for autowiring to load templating

### ISSUE THREAD

**Issue by LouWii** [symfony/symfony-docs#10211]
Hi there,

I lost a bit of time today when working with the Templating component https://symfony.com/doc/current/components/templating.html

I fortunately was able to find out that the component wasn't autowiring, and that configuration was needed in order for it to be autowired.
I know there's documentation about autowiring, but I didn't expect that I had to do something in particular for the Templating component to load properly.

I was wondering if a note about this could be added in the documentation page, or not. I'd be happy to try and do a PR.

What I did was just add
```
templating:
        engines:
            - twig
```
to my `framework.yaml` file. Autowiring then picked it up and loaded the component.

**Comment by xabbuh** [comment]
Hm, so the thing is that the component articles are meant for users who want to use the different component outside of the full-stack framework (i.e. commonly without the FrameworkBundle). For those users we cannot assume that they also use the DependencyInjection component and thus we cannot talk about autowiring at all.

Seeing that you were modifying your `framework.yaml` config file I wonder which problem did you try to solve. Do you really want to use the Templating component? Is Twig without the Templating component not better suited for you?

**Comment by LouWii** [comment]
Got it, that makes sense. That's why I asked, I wasn't sure if such information belongs to that documentation page or not.

We are overriding `FilesystemLoader` to add some logic when loading template files. It's a bit complex to explain but it only works when Templating is loaded in SF.

Well, I'll try to remember it for the next time :)
