### ISSUE TITLE
Range in Number Constraints is misleading

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#10229]
As the [Range](http://symfony.com/doc/3.4/reference/constraints/Range.html) constraint also work for **date** fields  the section headline [Number Constraints](http://symfony.com/doc/3.4/reference/constraints.html#number-constraints) is misleading. As I first thought that the Range will work only for numbers then.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. This is indeed confusing. What if we remove Range from "Number Constraints" and move it to "Comparison Constraints". After all, Range is just "Greater than" + "Less than".

**Comment by alexander-schranz** [comment]
@javiereguiluz sounds good for me created a PR

**Comment by javiereguiluz** [comment]
Fixed by #10249.
