### ISSUE TITLE
False link in subnavigation components -> contracts

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#10246]
When you are on https://symfony.com/doc/current/index.html.
The left sidebar Components -> Contracts links to https://symfony.com/doc/current/components/index.html but think should be https://symfony.com/components/Contracts?

Following the under links it should be https://symfony.com/doc/current/components/contracts.html but this does not exist.

**Comment by javiereguiluz** [comment]
@nicolas-grekas do you think we should create some docs for this component? Is this component something meant to be used independently in any PHP app like the other components?

If it's an internal thing better explained inside other components, we could remove it from here https://github.com/symfony/marketing/blob/1c41fd313be98f7801fb683f70e0c4e5d574d04a/components.yml#L50 to not display it in the components list. Thanks.

**Comment by nicolas-grekas** [comment]
> Is this component something meant to be used independently in any PHP app like the other components?

Of course!

**Comment by javiereguiluz** [comment]
Closing as fixed by this:

* The new Contracts docs: https://github.com/symfony/symfony-docs/pull/11430
* The updated link to those docs: https://github.com/symfony/marketing/pull/492

Thanks.
