### ISSUE TITLE
dudas con formulario

### ISSUE THREAD

**Issue by ronal08** [symfony/symfony-docs#10255]
tengo un crud por formulario sin embargo a la hora de editar y hacer la búsqueda por el id el me trae todos los valores que necesito pero al mostrarlo en mi vista me trae el tipo input como vació esto me obliga a que si una persona quiere editar tiene que obligatoriamente cargar una imagen nueva, como podría hacer para que mi input me traiga la información que tengo en mi base de datos.

**Comment by javiereguiluz** [comment]
@ronal08 we're sorry but we only accept comments written in English in this repository. Also, we don't use this repository to provide user support. You can get help on Symfony's Slack chat (https://symfony.com/support) You will even find a `#symfony-es` channel to ask for support in Spanish. Thanks!
