### ISSUE TITLE
Using a CDN: assets.base_urls or manifest.json ?

### ISSUE THREAD

**Issue by B-Galati** [symfony/symfony-docs#10251]
Hello,

I am bit confused.

The [CDN part of the doc](https://symfony.com/doc/current/frontend/encore/cdn.html) mentioned that it's possible to use a CDN by using `Encore.setPublicPath()` in webpack config. I think the doc is correct because it only relates to Webpack Encore.

But in the context of Symfony framework, one could also use `assets.base_urls` option (Which looks as good if not better from a developer point of view).

Perhaps the doc should mentioned what is the recommended way and why between the two?

Thank you for your help ;-)

I would be glad to open a PR if needed.

**Comment by B-Galati** [comment]
In fact, `assets.base_urls` cannot manage all cases like CSS images so it makes sense to use webpack encore for that.

But the doc would still need some clarification, no?

**Comment by javiereguiluz** [comment]
We're closing this old issue because sadly it didn't gain any traction and we didn't receive any other comments or requests about this. As always, this decision can be reconsidered in the future. Thanks for understanding!
