### ISSUE TITLE
[Translator] Document intl format

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony-docs#10264]
We should document how to use intl format. 

See related PR: https://github.com/symfony/symfony/pull/27399

Some description of the format here:
https://messageformat.github.io/messageformat/page-guide

**Comment by javiereguiluz** [comment]
Thanks for opening this issue Tobias. Hopefully you'll find sometime to document this new feature yourself ... because I'm afraid I don't understand it well enough to document it. Thanks!

**Comment by Nyholm** [comment]
Yes. That is the plan. But in case I forget or are too slow I thought it would be a good thing to write it down. 

I'll write on this issue when I begin with this feature. 
Anyone: feel free to start and we'll complete it together.

**Comment by nicolas-grekas** [comment]
A nice intl+icu fiddle we could link in the doc!
https://format-message.github.io/icu-message-format-for-translators/

**Comment by nicolas-grekas** [comment]
Should also tell about https://github.com/symfony/symfony/pull/28952

**Comment by javiereguiluz** [comment]
Fixed by the great #11523 PR.
