### ISSUE TITLE
Encore: Mention that public path of deployed location must match

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony-docs#10261]
file: https://github.com/symfony/symfony-docs/blob/3.4/frontend/encore/faq.rst

With assetic, it was not necessary to adapt any config when the public path has changed. (Adapting cookie_path in [framework](https://symfony.com/doc/current/reference/configuration/framework.html#cookie-path) is not really related. All could be solved with a parameter.) With encore this has changed. Adapting webpack.config.js and running ``encore production`` is necessary now.

I suppose to mention this at least in the faq in `2) Only Deploy the Built Assets`.

Showing a solution how to do this automatically would be even nicer. Maybe by reading a parameter/config/setting usable by encore and symfony config.

**Comment by SimonHeimberg** [comment]
maybe helpful: https://webpack.js.org/guides/public-path/ (did not yet try)

**Comment by javiereguiluz** [comment]
Closing because we didn't "fix" this issue on time. Symfony 3.4 is no longer supported and this was reported when Webpack Encore was very new. We haven't received any related reports since then and this didn't receive any comment from the community either. Thanks for understanding!
