### ISSUE TITLE
[FrameworkBundle] Deprecate Controller in favor of AbstractController

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#10282]
https://github.com/symfony/symfony/pull/28243

**Comment by jewome62** [comment]
Hello,

I think the work is done by : https://github.com/symfony/symfony-docs/commit/0775f0a6eb0778b9fa4a96d8da06ce2baaa70c97

**Comment by javiereguiluz** [comment]
@jewome62 you are right! Closing as fixed by #10172. Thanks!
