### ISSUE TITLE
Add enduser documentation/examples of methods for apply/test of unmerged/remote repo patches that can be easily referenced in devs' test requests

### ISSUE THREAD

**Issue by ghost** [symfony/symfony-docs#10304]
When asked in an issue to test an unmerged patch, e.g.,

	https://github.com/symfony/symfony/issues/28304#issuecomment-419257879

applying the remote commit as, for example,

```
git remote add patch-test https://github.com/nicolas-grekas/symfony
git fetch patch-test
git cherry-pick ccb6e1b5bfde8216f20b9b5026269c5fa59b39e2
composer update
```

works, generally elsewhere, but appears to be "the wrong way to apply the patch" in Symfony, e.g.,

	https://github.com/symfony/symfony/issues/28304#issuecomment-419321944

The docs should include a "right way" (or a selection of options) that devs/users can reference.

For example, at Slack, @nicolasgrekas comments

> there are many ways, not sure it's documented
> for sure its not trivial
> what I do is using the ./link utility at the root of symfony/symfony
> e.g.
```
git clone https://github.com/symfony/symfony
cd symfony
git fetch origin refs/pull/28123/head:pr-28123
git checkout pr-28123
./link $path_to_already_installed_project
```
> of course this supposes that pr-28123 uses the same base version as your project
> that's one way, there are others, and some might be better, dunno

Documentation should include a reference, providing explicit example of one, or more, appropriate methods for 'applying' -- *as requested* -- an unmerged, remote repo's patch

Then, a user can be pointed to the doc with a comment: "please test; do it this way"

What the 'right way' is, and in which cases of SF dev+test the usual cherry-pick is/isn't 'correct', I'm unclear;  as evidenced, my *failed* approach was to use it ... and, in the bug, there was never any successful test of the unmerged repo/commit.

**Comment by javiereguiluz** [comment]
I'm closing this one as "won't fix" because it's a bit out of the scope of Symfony Docs (the requested content is pure Git commands). What we can do is to rewrite the contribution docs to use the GitHub CLI (https://github.com/cli/cli) which simplifies everything a lot. Thanks!
