### ISSUE TITLE
[Website] Bugged code blocks in the docs

### ISSUE THREAD

**Issue by royklutman** [symfony/symfony-docs#10346]
The code blocks in the docs don't seem to work properly:

![image](https://user-images.githubusercontent.com/14876024/45586288-a97ef180-b8f4-11e8-90d3-1e5a5d6bafd0.png)

For example: https://symfony.com/doc/current/page_creation.html

**Comment by javiereguiluz** [comment]
@royklutman thanks for reporting! I'm really sorry for having introduced this issue. It's solved now. Thanks!
