### ISSUE TITLE
[Cache] Remove TaggableCacheInterface, alias cache.app.taggable to CacheInterface

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#10343]
https://github.com/symfony/symfony/pull/27398

**Comment by MarioBlazek** [comment]
@javiereguiluz this one can be closed, as it is already merged.

**Comment by javiereguiluz** [comment]
For reference purposes, can you please post the link to the Symfony Docs pull request that fixed it? Thanks!
