### ISSUE TITLE
Update reusable bundles testing doc from symfony/lts to flex

### ISSUE THREAD

**Issue by dbu** [symfony/symfony-docs#10361]
https://symfony.com/doc/current/bundles/best_practices.html is using symfony/lts examples. it should be updated to flex solution explained in the readme of the lts repository.

**Comment by javiereguiluz** [comment]
In addition to this, should we update this article (and others) to move from Travis CI to GitHub? Most of our readers already have a GitHub account, so we remove the friction of having to sign up for another service, etc.

@symfony/team-symfony-docs what do you think about this proposal?

**Comment by dbu** [comment]
not part of the core team but if you want my opinion: probably makes sense as symfony itself seems to have moved. i'd do some note that the best practice is to have "a continuous integration" and the examples use github actions, but using travis-ci or other services is perfectly fine too. just so we don't create the impression we think it is strictly better to use github actions over travis-ci...

**Comment by wouterj** [comment]
See https://github.com/symfony/symfony-docs/pull/14505

I agree with @dbu that it's probably better to not favor any tool. So I've decided to drop the config and instead document the intentions behind it.
