### ISSUE TITLE
Not setting the strict option of the Choice constraint to true is deprecated since Symfony 3.4 and will throw an exception in 4.0.

### ISSUE THREAD

**Issue by yohowie** [symfony/symfony-docs#10374]
The problem has been solved

**Comment by xabbuh** [comment]
@Carson-Yu Does it mean we should close this issue?

**Comment by lichtung** [comment]
Appending  "'strict'=>true" to the options of construct will works!
`new Choice(['choices' => [...], 'strict' => true])`

**Comment by javiereguiluz** [comment]
Let's close this as fixed because the deprecation notice about `strict` is already displayed in the `Choice` constraint: https://symfony.com/doc/3.4/reference/constraints/Choice.html#strict Thanks.
