### ISSUE TITLE
Composite Constraint not documented.

### ISSUE THREAD

**Issue by buffalobuffalobuffalobuffalobuffalo** [symfony/symfony-docs#10381]
There is a Composite Constraint

https://api.symfony.com/4.1/Symfony/Component/Validator/Constraints/Composite.html

but it completely lacks documentation. Does it allow for constructing logical alternative of other constraints? Like `@Composite({@LessThan(4), @GreaterThan(8)})`? Or is it designed for something entirely different?

**Comment by ro0NL** [comment]
The class is abstract... and a base for `@Optional` and `@Required`, explained here: https://symfony.com/doc/current/reference/constraints/Collection.html#required-and-optional-field-constraints

so yes, internal implementation detail to me :) but i'm not sure how it's implemented exactly, you might leverage it for your own "composites" i guess. AFAIK core only uses it for the `Collection` constraint.

**Comment by HeahDude** [comment]
We could actually include a note for all composite constraints: All, Valid and Collection.
Because they do have a different behavior regarding validation groups.

**Comment by OskarStark** [comment]
Not sure it’s worth having it in the documentation 🤔

**Comment by xabbuh** [comment]
We should maybe rather think about marking it internal in the code instead.

**Comment by javiereguiluz** [comment]
Closing for now in favor of the https://github.com/symfony/symfony/issues/34830, which might mark this as internal. Thanks.
