### ISSUE TITLE
[WebLink] The page you are looking for does not exist

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony-docs#10395]
WebLink's docs disappeared :(

https://symfony.com/doc/current/components/weblink/introduction.html

Also cannot see it in the list of components.

**Comment by hiddewie** [comment]
It seems available at https://symfony.com/components/WebLink

**Comment by vudaltsov** [comment]
@hiddewie , this is a different page. It's just a general info page. The documentation is missing.
@javiereguiluz , could you please, help?

**Comment by javiereguiluz** [comment]
Closing as fixed:

* Doc about using WebLink inside Symfony apps: https://symfony.com/doc/current/web_link.html
* Doc about using WebLink as a standalone component in any PHP app: https://symfony.com/doc/current/components/web_link.html
