### ISSUE TITLE
Constraints directory

### ISSUE THREAD

**Issue by Aliance** [symfony/symfony-docs#10428]
All of Symfony constraints located into `Validator\Constraint`:
https://github.com/symfony/symfony-docs/blame/95494c572dd98e2d9a94e373545a0c02588e2266/validation/custom_constraint.rst#L20

But current documentation put custom constraint inside `Validator\Constraints`:
https://github.com/symfony/symfony-docs/blame/95494c572dd98e2d9a94e373545a0c02588e2266/validation/custom_constraint.rst#L17

Maybe it should be specified in one manner?

**Comment by javiereguiluz** [comment]
@HeahDude @xabbuh do you agree with this proposal? Thanks!

**Comment by HeahDude** [comment]
Yes I agree we should use "Constraints" everywhere consistently.

**Comment by Aliance** [comment]
Constraint**s**? So we need to move all of them into sources? Looks like a BC, may be we should fix docs – use `Constraint`?

**Comment by xabbuh** [comment]
In projects I usually have only a `Validator` namespace. Why do we need the additional `Constraint`/`Constraints` subnamespace? Do you usually put any classes in the `Validator` namespace that are not related to constraints and their validators?

**Comment by Aliance** [comment]
You know, looks like I'm totally wrong here 😔 
Because the first link from my post goes to file itself, not directory:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraint.php

So, looks like there is no problem, yeap?

**Comment by HeahDude** [comment]
Indeed :).
