### ISSUE TITLE
SensioFrameworkExtraBundle "current" documentation points to 3.0

### ISSUE THREAD

**Issue by magnetik** [symfony/symfony-docs#10438]
For instance when you search for `symfony param converter` on google, you land on : https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html

I do not know why, but it's the `current` version that is linked, and it points to the 3.0 which is outdated, and not even maintained anymore. 

Can this URL change to be 5.0 ?

**Comment by javiereguiluz** [comment]
This has been fixed in the private symfony.com repo and will be deployed soon. After that, we'll need to wait a few hours until the doc is regenerated too. Thanks!
