### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-docs#10536]
I get "too many redirects" error following this link: https://symfony.com/doc/4.1/security/api_key_authentication.html

<img width="770" alt="screen shot 2018-10-23 at 10 42 56" src="https://user-images.githubusercontent.com/3317635/47344125-6b71ac00-d6b0-11e8-9476-70eeaddb4ec8.png">

**Comment by xabbuh** [comment]
see #10537
