### ISSUE TITLE
UserLocaleSubscriber example not working in documentation

### ISSUE THREAD

**Issue by Rmy5** [symfony/symfony-docs#10539]
In this documentation: https://symfony.com/doc/current/session/locale_sticky_session.html
The // src/EventSubscriber/UserLocaleSubscriber.php example seems to be missing the implementation of the getSubscribedEvents() method ?

Shouldn't it be be something like this ?:

` public static function getSubscribedEvents()
    {
        return array(
            SecurityEvents::INTERACTIVE_LOGIN => 'onInteractiveLogin',
        );
    }` 

Or maybe the service register is not pointing to the right namespace ?

`services:
    App\EventListener\UserLocaleListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin, priority: 15 }`

**Comment by xabbuh** [comment]
#10546 should fix this

**Comment by Rmy5** [comment]
Will #10546 also affect the symfony:4.1 ?

**Comment by xabbuh** [comment]
Yes, we regularly merge lower version branches up to all still supported versions. So the fix will land in 3.4, 4.1 and all future versions.

**Comment by Rmy5** [comment]
Great thanks !
