### ISSUE TITLE
[Form] Improve the doc about "recursive" rendering

### ISSUE THREAD

**Issue by vicb** [symfony/symfony-docs#1055]
Is it possible to make recursive calls in order to decorate the base template:

``` jinja
 {% block _text_id_widget %}
 <div id="container">
    {{ form_widget(form) }}
 </div>
{% endblock %}
```

The doc should give hints on when to call the flexible {% form_xxx %} vs when to call the speedy {% block() %}.

Refs:
symfony/symfony#1369
symfony/symfony#3195

**Comment by iltar** [comment]
This is more or less mentioned on this page: http://symfony.com/doc/current/form/form_customization.html#referencing-base-blocks-from-an-external-template

I think this issue can be closed.
