### ISSUE TITLE
[WebProfilerBundle] Removed application name

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#10565]
https://github.com/symfony/symfony/pull/28939

**Comment by TimoBakx** [comment]
I don't think any changes are needed.

Deprecations were:
> * The `Kernel::getRootDir()` and the `kernel.root_dir` parameter have been deprecated

No references to the method or parameter found in the 4.2 documentation.

> * The `KernelInterface::getName()` and the `kernel.name` parameter have been deprecated

A deprecation notice is already present: https://github.com/symfony/symfony-docs/blob/master/reference/configuration/kernel.rst#kernel-name

> * Deprecated the first and second constructor argument of `ConfigDataCollector`

No references to `ConfigDataCollector` found in the 4.2 documentation.

> * Deprecated `ConfigDataCollector::getApplicationName()`

No references to this method found in the 4.2 documentation.

> * Deprecated `ConfigDataCollector::getApplicationVersion()`

No references to this method found in the 4.2 documentation.

**Comment by xabbuh** [comment]
let's close here then
