### ISSUE TITLE
Xsd schema location not found

### ISSUE THREAD

**Issue by Landerstraeten** [symfony/symfony-docs#10589]
The schema location mentioned at
https://github.com/symfony/symfony-docs/blob/master/service_container.rst#L168 does not exist anymore.

**Comment by javiereguiluz** [comment]
@Landerstraeten thanks for reporting this issue. Do you refer to `http://symfony.com/schema/dic/services/services-1.0.xsd`? If that's the XSD, I can download it on my computer, so I'd need a bit more of details about the error. Thanks!

**Comment by Landerstraeten** [comment]
Strange! Yes I was referring to the xsd file.

We had an error in our [builds](https://travis-ci.org/phpro/grumphp/jobs/446662368) last Friday `(http://symfony.com/schema/dic/services/services-1.0.xsd): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found`

The problem is magically fixed.
Thanks!

**Comment by javiereguiluz** [comment]
Thanks for checking this. Let's close then as "fixed". It was probably a temporary issue.
