### ISSUE TITLE
Improve documentation of repository "magic finder" query methods

### ISSUE THREAD

**Issue by olberger** [symfony/symfony-docs#10665]
The findBy*() methods of the repositories are mentioned in certain examples, but are not really documented AFAICS.

The Doctrine docs aren't much clearer, either (quite late in https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-objects.html#by-simple-conditions):
"An EntityRepository also provides a mechanism for more concise calls through its use of __call."

Actually, the only thing that seems to clearly document it is in https://www.doctrine-project.org/api/orm/2.6/Doctrine/ORM/EntityRepository.html#method___call provided one know what are "magic method calls" ;-)

I guess this is highly used in practice, but deserves more clear documentation.

**Comment by olberger** [comment]
Btw, I just submitted https://github.com/doctrine/doctrine-website-build-prod/issues/2 hoping it'll get noticed.

**Comment by javiereguiluz** [comment]
Let's close this because it has been reported to Doctrine in https://github.com/doctrine/orm/issues/7481, so they may fix it in their docs. Thanks!
