### ISSUE TITLE
A new security.yaml file for testing HTTP Auth seems incompatible with the default architecture

### ISSUE THREAD

**Issue by obax** [symfony/symfony-docs#10721]
Version: Symfony 4.2

According to the documentation, I should be able to create a new firewal in security.yaml under `config/packages/test/`
https://symfony.com/doc/current/testing/http_authentication.html

Since I get `Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: You are not allowed to define new elements for path "security.firewalls". Please define all elements for this path in one config file.`; does it mean that I should migrate my existing `security.yaml` under `prod/dev` ?

**Comment by javiereguiluz** [comment]
@obax I think the docs is correct. Let me explain. The error message says that *"you are not allowed to define new elements"* ... but you can redefine/reconfigure the existing elements defined in the main `security.yaml` file.

This is what we do (applying what the docs say) in the Symfony Demo app:

1) the main security.yaml defines 2 firewalls: `dev` and `main` (https://github.com/symfony/demo/blob/39f0d9ce537a5614e901e0848b833e79dbb29227/config/packages/security.yaml#L16)
2) the devtestsecurity.yaml file redefines the `main` firewall: https://github.com/symfony/demo/blob/master/config/packages/test/security.yaml

Can you please double check if you are using the same firewall name in both files? Thanks!

**Comment by obax** [comment]
I stand corrected. I've glossed over the `# replace 'main' by the name of your own firewall`.
Thanks @javiereguiluz
