### ISSUE TITLE
Forms: Add example how to set the form theme

### ISSUE THREAD

**Issue by xosofox** [symfony/symfony-docs#10734]
It is quite hard in the documentation to find the part on "how to actually set/change the form theme".

It would be nice to have it on the form theming page, between "There are themes" and "how to customize" - at least as a reference/link

**Comment by javiereguiluz** [comment]
@xosofox thanks for reporting this problem. You are right. The docs about this were very confusing. A few weeks ago we revamped the main article about [Symfony Form Themes](https://symfony.com/doc/current/form/form_themes.html) from scratch, so this should be solved.

If you think something is wrong or missing in the new docs, please open a new issue. Thanks a lot!
