### ISSUE TITLE
[DOC] [DX] filter by component (category/living-on-the-edge)

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony-docs#10741]
| Q                | A
| ---------------- | -----
| Feature request? | yes (second part?)
| Symfony version  | 3.4, 4.*
| Related to | https://github.com/symfony/symfony/issues/27038 #SymfonyConHackday2018

Hi

After https://github.com/symfony/symfony/issues/27038 has been added to the doc (actualy blog part), and seeing it the SymfonyCon Lisbon summary conf 👍,
I would like to propose as well to add a filter by component (maybe in a select form input, as there are a lot of them)

That way, a developer can also filter on component to spot directly related blog posts.

If you consider this to much, just close that issue :)

Thank you,

**Comment by javiereguiluz** [comment]
@noniagriconomie we appreciate your improvement proposal, but as you said, this is "too much". It's difficult to associate some articles with components and some articles are related to lots of components. So, for now, we prefer to not implement this idea. Thanks!
