### ISSUE TITLE
Use of security.helper service when Checking for Roles inside a Voter

### ISSUE THREAD

**Issue by AndyGibsonProtectline** [symfony/symfony-docs#10773]
Hi!

This is not my speciality at all but I was surprised to read this on https://symfony.com/doc/4.1/security/voters.html:

> What if you want to call isGranted() from inside your voter - e.g. you want to see if the current user has ROLE_SUPER_ADMIN. That's possible by injecting the Security into your voter. You can use this to, for example, always allow access to a user with ROLE_SUPER_ADMIN:...

```
protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        // ...

        // ROLE_SUPER_ADMIN can do anything! The power!
        if ($this->security->isGranted('ROLE_SUPER_ADMIN')) {
            return true;
        }

        // ... all the normal voter logic
    }
```

Please shoot me down or ignore me but doesn't this lead to us bypasing the token which is passed into the voteOnAttribute method?

e.g. the 3.4 documentation recommends:

// ROLE_SUPER_ADMIN can do anything! The power!
        if ($this->decisionManager->decide($token, array('ROLE_SUPER_ADMIN'))) {
            return true;
        }

**Comment by weaverryan** [comment]
Hey @AndyGibsonProtectline!

Yes, this does bypass the `$token`, but that's fine 99% of the time. The `$token` is the current user's token. So, there's no point to passing a *different* token unless you want to test whether or not a different user (other than the current user) has access. I've never had a use-case for that.

Cheers!
