### ISSUE TITLE
Upgrade instructions for the new .env behavior are confusing

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#10775]
The upgrade instructions are mixing the 4.2+ and 3.3+ recipes, making people apply the 4.2 recipe in their 3.4 projects (see https://github.com/symfony/symfony/issues/29566).

The migration instructions should either link to the appropriate recipe for each version, or always link to the file in the 3.3 folder (applying the 3.3+ recipe in 4.2 will work fine, even though the file will be less clean due to the fallback implementation; the opposite breaks).

the link to the diff for files is also confusing, because they link to a diff which is still using `src/.bootstrap.php` while it was renamed in a later commit.

**Comment by weaverryan** [comment]
@stof I don't see many of the "mixing" that you see.

On the 4.1 version of the docs (https://symfony.com/doc/4.1/configuration/dot-env-changes.html) everything is linking to the 3.3 version of the recipes. And 4.2 (https://symfony.com/doc/current/configuration/dot-env-changes.html) is linking to the 4.2 recipes. There are a lot of links, so is there one I'm missing?

> the link to the diff for files is also confusing, because they link to a diff which is still using src/.bootstrap.php while it was renamed in a later commit.

That's correct - I'll fix that.
