### ISSUE TITLE
Add a note that Apache requires extra config for `mod_xsendfile`

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony-docs#10794]
https://symfony.com/doc/current/components/http_foundation.html#serving-files suggests that Symfony will automagically leverage the `mod_xsendfile` module to efficiently send files.

As https://github.com/symfony/symfony/issues/24897 correctly points out, this is not true: `BinaryFileResponse` will only make use of `mod_xsendfile` if a particular header is present, which is *not* the default case for Apache.

So, in fact, users might be sending out their files through PHP, even if they have `mod_xsendfile` installed. Probably they are not aware of this.

One way of fixing this is to enable the `mod_headers` Apache module and add the following to the Apache configuration:

```
<IfModule mod_xsendfile.c>
   # This is already present somewhere...
   XSendFile on
   XSendFilePath ...some path...

   # This needs to be added:
   <IfModule mod_headers.c>
      RequestHeader set X-Sendfile-Type X-Sendfile
   </IfModule>
</IfModule>
```

My suggestion is to add a warning/info box somewhere near https://symfony.com/doc/current/components/http_foundation.html#serving-files.

**Comment by PReimers** [comment]
If nobody is working on this I would add the suggested infobox.

**Comment by OskarStark** [comment]
We would appreciate a PR @PReimers 😊
