### ISSUE TITLE
DependencyInjection bind vs arguments?

### ISSUE THREAD

**Issue by wuestkamp** [symfony/symfony-docs#10805]
As can also be seen in this [discussion](https://stackoverflow.com/questions/49874327/symfony-manually-wiring-arguments-arguments-vs-bind), the difference between `bind` and `arguments` its not clearly described in the docs.

We have:
https://symfony.com/doc/current/service_container.html#manually-wiring-arguments
and
https://symfony.com/doc/current/service_container.html#binding-arguments-by-name-or-type

I think `bind` can be used more generally, giving the possibility by binding by type and not just by name like `arguments`. But why not use `bind` for everything?

Also, wins `arguments` over `bind`?

Thanks!
Kim

**Comment by ragboyjr** [comment]
@wuestkamp Bind is used as default bindings to be applied to the services defined later. Arguments are bind values per service definition. They essentially work the same do the same thing, bind is the default applied across the whole file, args are per service.

There's nothing that prevents binds an arguments from working together on an individual service either. You could define one arg for a service, and leave the rest to be autowired or binded from the defaults.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" for now. The current docs already explain that "bind" is for all services (defined in that file). It's true that we could explain this better ... hopefully we'll be able to reword all the docs about services "soon". Thanks.
