### ISSUE TITLE
PHPUnit require when using phpunit bridge

### ISSUE THREAD

**Issue by ghost** [symfony/symfony-docs#10820]
Hello!

Currently creating an app on symfony4 and writing tests on it. As in the manual, we should require symfony/phpunit-bridge and be happy. But if I require only phpunit-bridge, I won't be able to use features of phpunit, because it is not required with it. So, if I wanna use PHPUnit/Framework/TestCase (as it normally does, and as the documentation of Symfony requries too), it is imposible due to the lack of files. Also, It is hard to assign phpunit to phpstorm to use from the ui. 

So it might be usefull to add additional requirement in composer? 
Or is it just for me?

**Comment by xabbuh** [comment]
Running your tests afterwards with the `simple-phpunit` script will install PHPUnit. Afterwards, auto-completion should work as well. We may want to add a call of `vendor/bin/simple-phpunit` before explaining how to write tests. That should probably help with some confusion.

**Comment by Windstep** [comment]
Or just add phpunit as a dependency to this bridge, because it is the way, it has to work.

**Comment by HeahDude** [comment]
Also note that you can install PHPUnit dependencies to provide auto-completion withtou running your test with the following command:
```bash
./vendor/bin/simple-phpunit install
```
Or when using Flex:
```bash
./bin/phpunit install
```

**Comment by xabbuh** [comment]
Ops, I just noticed that I missed the `install` part in my previous comment. I just updated it.

**Comment by PReimers** [comment]
Hey 👋 

Is someone working on adding a note about installing PHPUnit by using the `install` command of the binary?

If not, I would like to try my luck on it. 😉

**Comment by romanhandke** [comment]
Is this really how it is supposed to be?

> vendor/bin/simple-phpunit install
Creating a "phpunit/phpunit" project at "./phpunit-7.5-0"
Installing phpunit/phpunit (7.5.20)
Plugins have been disabled.
>  - Installing phpunit/phpunit (7.5.20): Downloading (100%)
Created project in /home/user/code/test/vendor/bin/.phpunit/phpunit-7.5-0`

because installing phpunit to vendor/bin/.phpunit does not help with my autocompletion

**Comment by dbrumann** [comment]
> Is this really how it is supposed to be?
> [...]
> because installing phpunit to vendor/bin/.phpunit does not help with my autocompletion

It works fine on my machine™️ (Symfony 5.0.8, PHPUnit 9.0) with PhpStorm 2020.1.1 (Build #PS-201.7223.96, built on April 30, 2020). Have you tried invalidating the PhpStorm caches?

**Comment by javiereguiluz** [comment]
Closing this old issue because it looks like most people can't reproduce the issue (I can't either ... PHPUnit autocompletion works fine in PhpStorm and I0m using the PHPUnit bridge too). Thanks!
