### ISSUE TITLE
[Validator] Missing code example in the IdenticalTo constraint

### ISSUE THREAD

**Issue by xElysioN** [symfony/symfony-docs#10829]
Hi, 
In the `IdenticalTo` constraint, there is missing codes in YAML, XML and PHP for the firstname constraint in the Basic Usage, but ok for annotations.

CF : https://symfony.com/doc/3.4/reference/constraints/IdenticalTo.html#basic-usage

**Comment by javiereguiluz** [comment]
Fixed by #10830.
