### ISSUE TITLE
Bug in guard_authentication.rst: Picture missing

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#10838]
At https://symfony.com/doc/current/security/guard_authentication.html#the-guard-authenticator-methods the picture is missing:
> The picture below shows how Symfony calls Guard Authenticator methods:

**Comment by javiereguiluz** [comment]
Thanks for reporting ... but this is a duplicate of #10210. We're still trying to fix it. We have a change pending to be deployed that we hope it will be the definitive solution.
