### ISSUE TITLE
Minor error in authentication-guard-methods.svg

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#10844]
In `authentication-guard-methods.svg` on https://symfony.com/doc/current/security/guard_authentication.html#the-guard-authenticator-methods there is a minor error:

`supportsRememberMe` is not called in any case (as the picture suggests), but only if `remember_me` is configured for the firewall in `security.yaml`.

I'd suggest to add a note in parentheses, e.g.:
> (if `remember_me` is configured)

**Comment by xabbuh** [comment]
@ThomasLandauer Sounds reasonable to me. Would you like to work on a PR?
