### ISSUE TITLE
Not clear about how services are automatically load

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony-docs#10847]
Hello, I almost had a fight with a coworker because I was saying `autoconfigure: true` does not automatically register services. :smile: He finally told me "see, it's written in the doc !!".

This was obviously due to a misunderstanding of the documentation.

```
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
```

It does not actually automatically register services, but tag them as [...].

https://github.com/symfony/symfony-docs/blob/master/service_container.rst#creatingconfiguring-services-in-the-container

What do you think?

**Comment by javiereguiluz** [comment]
Thanks for this proposal. Symfony Docs follow the contents of the original Symfony Flex recipes very strictly ... so I've created https://github.com/symfony/recipes/issues/515 to report this and if it's accepted, then we'll make this change in docs. Thanks!

**Comment by OskarStark** [comment]
Can we say it is accepted? Only upvotes 👍🏻

**Comment by javiereguiluz** [comment]
Closing because the related recipe issue was closed too. Thanks.
