### ISSUE TITLE
[BUG] Create your own framework seems to have stopped working

### ISSUE THREAD

**Issue by wwwd3v** [symfony/symfony-docs#10859]
https://symfony.com/doc/current/create_framework/index.html

I started seeing empty page yesterday.

**Comment by javiereguiluz** [comment]
@wwwd3v thanks for reporting! Actually, the table of contents is there, but a CSS rule is making it `display: none`. We're going to merge/deploy a fix for this very soon, so I'm closing this as fixed. Sorry for this!

**Comment by wwwd3v** [comment]
Thanks :)
