### ISSUE TITLE
"Sticky Locale" not working?

### ISSUE THREAD

**Issue by beachespecially** [symfony/symfony-docs#10864]
Can anyone confirm that the workflow described [here](https://symfony.com/doc/current/session/locale_sticky_session.html) is still working?

I tried it with the [symfony demo application](https://github.com/symfony/demo), by adding a locale field to the User entity and the Locale- and UserLocaleSubscriber as shown in the article.
Now when I use the login in the demo application, the locale should be updated to the one saved in the user entity, but it stays the default locale.
After some debugging it looks like the session "_locale" never gets updated either.

Not sure if I have done something wrong or if there is a fault in the docs. If you have some pointers on where I could try to debug more, I'd be happy to do so.

**Comment by DavidGarciaCat** [comment]
Hey @beachespecially 

Here are the steps that I followed to reproduce your error:
* I've downloaded a copy of the demo project and installed the composer dependencies
* I've added the `LocaleSubscriber` as described on the docs page
* I've added just one line to the Blog's index page:

```
{{ dump(app.request.session.all) }}
```

When browsing the Demo project, then I can see that the Session now has the Locale stored there:

<img width="603" alt="screenshot 2019-01-16 at 15 04 13" src="https://user-images.githubusercontent.com/7809429/51257789-4daa9f00-19a0-11e9-8f53-d5be49414dd7.png">

Would you mind to provide more details? Are you changing a config parameter somewhere? Did you rename the `_locale` key? Any other clue to reproduce the error?

**Comment by DavidGarciaCat** [comment]
Adding a new `$locale` parameter in the `User` entity, updating the database schema and browsing again seems to work too, the session changes the locale when browsing other pages with a logged in user

![screenshot 2019-01-16 at 15 18 55](https://user-images.githubusercontent.com/7809429/51258504-0fae7a80-19a2-11e9-980c-91ce73c6061e.png)

**Comment by beachespecially** [comment]
Hi @DavidGarciaCat 
thank you for helping. 
I can confirm that the `_locale` Key gets stored in the session. But for me it does not change from the default locale, even when another locale is set in the `User` entity.

The steps I have taken are basically the same as you have (but obviously I have done something wrong):
- Download the demo project
- Add `LocaleSubscriber` and `UserLocaleSubscriber` as described on the doc page
- Add `$locale` (or in my case `$language`) to the `User` entity, add field for it in the Account settings form so I can change it.
- Log the session contents (I didn't know about the twig `{{ dump }}`, so already learnt something :) )

I see that in the dumped session, the `User` entity does not have the `language` parameter, so maybe that is where something went wrong for me.
![screenshot 2019-01-16 at 17 01 39](https://user-images.githubusercontent.com/28100936/51262028-c49c6380-19b1-11e9-8cd7-25d5e029ea3c.png)

I have pushed my current status here: [https://github.com/beachespecially/symfony-demo](https://github.com/beachespecially/symfony-demo)

**Comment by beachespecially** [comment]
It seems like that works correctly:
<img width="549" alt="screenshot 2019-01-16 at 23 05 35" src="https://user-images.githubusercontent.com/28100936/51303467-b98b1700-1a35-11e9-9da2-226bddcd4247.png">

**Comment by beachespecially** [comment]
Ok, another thing I tried which may help pinpoint the error:
- Open the demo application and go to "browse backend"
- Change the language via the language switcher in the top right to for example french
- Now log in with the admin user (which has the language on its entity set to for example to german)
- The language gets switched to english (default language, also browser language)

**Comment by javiereguiluz** [comment]
@beachespecially there's an edge case involving the login page and the locale. It's explained (and fixed) in https://github.com/symfony/demo/pull/949. So, I'm closing this in favor of the mentioned pull request. Thanks.

**Comment by beachespecially** [comment]
@javiereguiluz Thank you :)
