### ISSUE TITLE
Messenger: new PHP serializer for Symfony 4.3

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#10929]
See symfony/symfony#29958

The default serializer changed. Mostly this will be invisible to users, but anything that talks about how it's serialized, should not mention the Symfony serializer anymore. That IS still an option (and we could document perhaps how to set it to use the old serializer), but I think that will be an edge-case.

**Comment by javiereguiluz** [comment]
Closing in favor of the meta-issue that is tracking everything about Messenger: #11236.
