### ISSUE TITLE
Split Voter in "Creating the customer Voter"

### ISSUE THREAD

**Issue by kunicmarko20** [symfony/symfony-docs#10935]
https://symfony.com/doc/current/security/voters.html#creating-the-custom-voter

My opinion here would be that this should be 2 separate voters, one for the `view` and one for the `edit`.

I would like to create a PR for this if you think it is a good idea?

Or even a better idea would be to show just edit or view, and drop the other one.

**Comment by OskarStark** [comment]
I have mixed feelings about this, because it should show, that you can handle multiple in one voter.

Why would you like to change this? What would be the benefit for the user (docs reader)?

**Comment by kunicmarko20** [comment]
The logic is clearly separated for view and edit and as I said, my opinion is that there should be a separate class for each because that is how I would create it.
