### ISSUE TITLE
documentation for dotenv component refers the old .env.dist

### ISSUE THREAD

**Issue by PBrouwer** [symfony/symfony-docs#10940]
In the documentation of the dotenv component (https://symfony.com/doc/current/components/dotenv.html) it says:
`You should never store a .env file in your code repository as it might contain sensitive information; create a .env.dist file with sensible defaults instead.`
However since november 2018 changes (https://symfony.com/doc/current/configuration/dot-env-changes.html) the .env.dist file is no longer used and is replaced by the combination of .env in the repo and .env.local on your local environment.

The documentation should be updated to reflect these changes

**Comment by javiereguiluz** [comment]
Thanks for reporting this error! We're sorry it took us so long to fix it. It's been fixed as part of a total revamp of docs related to configuration in #11690.
