### ISSUE TITLE
Non found on https://symfony.com/inflector

### ISSUE THREAD

**Issue by mrself** [symfony/symfony-docs#10961]
I got to https://github.com/symfony/inflector and wanted to see docs. So I clicked to the link in the description and it turned out to be broken.

**Comment by javiereguiluz** [comment]
@mrself we've removed the wrong link. The real issue is that "inflector" is not a true Symfony component. I tried to add docs for it in https://github.com/symfony/symfony-docs/pull/6435 but I was told to not do that because this is not something created to be used as stand-alone component.

**Comment by mrself** [comment]
Thank you for clarification. I really thought that inflector is a Symfony component and was going to use it.
