### ISSUE TITLE
[Cache] How to configure a cache adapter

### ISSUE THREAD

**Issue by sylfabre** [symfony/symfony-docs#10989]
It is very easy to use default cache adapter like Redis or Filesystem.

But there is no explanation on how to set custom options for a given adapter.

For instance, Redis client supports a lot of options:
![image](https://user-images.githubusercontent.com/3177556/52629491-11dcf980-2eba-11e9-94f5-3683555a4a8a.png)

=> How may I use them?

**Comment by sylfabre** [comment]
@wouterj hi
Thank you for the doc update. But I still can't find how to configure the Redis cache adapter.
For instance, how to set the `retry_interval` for the `cache.app`?

**Comment by wouterj** [comment]
@Nyholm you mentioned this issue in your PR. Did we forgot to document how to configure options of adapters?

**Comment by Nyholm** [comment]
Sorry @sylfabre and @wouterj. I missed that. 

Have a look at #11364. That should fix this issue.
