### ISSUE TITLE
[Validator] Insufficient  documentation or bugs

### ISSUE THREAD

**Issue by crtl** [symfony/symfony-docs#10992]
I wanted to use the validator component but I am having some problems and many of them are related to insufficient docs.
Either im to dumb, the docs are incomplete, theres a bug or all of the three.

Given the following example:

```php
$constraints = new Assert\Collection([
    "type" => new Assert\Choice([
        "choices" => ["credentials", "google"],
        "groups" => ["type"]
    ]),
    "token" => new Assert\NotBlank([
        "groups" => ["google"]
    ])
]);

$data = ["type" => "credentials"]
$validator = Validation::createValidator();

$result = $validator->validate($data, $constraints, "type");
```

The Resulting messages are:

```
type = 'The value you selected is not a valid choice.'
token = 'The field is missing'
```

According to the documentation:
- [How to Apply only a Subset of all Your Validation Constraints (Validation Groups)](https://symfony.com/doc/current/validation/groups.html)
- [How to Validate Raw Values (Scalar Values and Arrays)](https://symfony.com/doc/current/validation/raw_values.html)
- [How to Sequentially Apply Validation Groups](https://symfony.com/doc/current/validation/sequence_provider.html)

Only the group `type` should be validated.
If I pass a sequence of `["type", "google"]` it validates the `type` group first and then validates `google` group, but shows all fields from `type` group as unexpected fields.

Aside of that, all examples are given for object validation.

> Usually you will be validating entire objects. But sometimes, you just want to validate a simple value[...]

Its the total opposite in my opinion, in most cases you will get input as an scalar, array or object and not a **Class**.

**Comment by HeahDude** [comment]
Hello @crtl, sorry for the late response.

In fact your example in not exactly the same but quite similar to the one of your first link.
What is missing is what's documented in the [`Collection` constraint] which considers all keys as required by default in all group, so your example is configured as if it was the following:
```php
$constraints = new Assert\Collection([
    "fields" => [
        "type" => new Assert\Required([
            "constraints" => [
                new Assert\Choice([
                    "choices" => ["credentials", "google"],
                    "groups" => ["type"]
                ]),
            ],
            "groups" => ["type", "google"],
        ]),
        "token" => new Assert\Required([
            "constraints" => [
                new Assert\NotBlank([
                    "groups" => ["google"],
                ],
            ],
            "groups" => ["credentials", "google"],
        ]),
    ],
    // the collection constraint must be traversed for each nested group
    "groups" => ["type, "google"],
    "allowMissingFields" => false,
]);
```
So each field is required in all group by default, you need to change this one line in your example to get the intended behavior:
```diff
-"token" => new Assert\NotBlank([
+"token" => new Assert\Optional(new Assert\NotBlank([
    "groups" => ["google"]
-])
+]))
```

@symfony/team-symfony-docs do you think we need a PR for this? Thanks!

**Comment by weaverryan** [comment]
I want really aware of this Required and Optional stuff. I DO think we should document this better :)

**Comment by HeahDude** [comment]
Thanks for the input @weaverryan, then I suggest to update this article `https://symfony.com/doc/current/validation/raw_values.html` to add a new section with groups, to tell about what I've explained in my comment above. WDYT?

**Comment by weaverryan** [comment]
That looks right. But we should also link to that (if we don’t already) from the CollectionType

**Comment by HeahDude** [comment]
I guess you're thinking about the `Collection` constraint, as I was thinking about it too :).

**Comment by HeahDude** [comment]
In fact it fitted more smoothly in the `Collection` constraint doc itself with a proper note from the article (the opposite of my first thought), I've opened #13492.
