### ISSUE TITLE
Custom form (Table theme) not working ?

### ISSUE THREAD

**Issue by zayders** [symfony/symfony-docs#11007]
I use form theme like it is explain in the documentation https://symfony.com/doc/current/form/form_themes.html with :

`{% form_theme form.methodes 'form_table_layout.html.twig' %}`

In order to have table and not "div".

My problem is :
For a normal form with "div", i use this code to modify and adapt a collection :
`{% block _Examplebundle_methodes_entry_widget %} `
Documentation "How to Customize a Collection Prototype" : https://symfony.com/doc/3.4/form/form_customization.html

It work for theme with "div" but with the theme 'form_table_layout.html.twig' it didn't work. I don't know how to custom block with the table theme.

here is a part of my code :

```
{% form_theme form.methodes 'form_table_layout.html.twig' %}

//////// Block to custom the collection/////////////
{% block _Examplebundle_methodes_entry_widget %}
 <tr>
    <td>
         {{ form_widget(form.methodeEssai) }}
         {{ form_errors(form.methodeEssai)}}
    </td>
    <td>
       {{ form_widget(form.ind, {'attr' : {'placeholder' : 'Index'}}) }}
       {{ form_errors(form.ind)}}
    </td>
    <td>a</td>
    <td>z</td>
    <td>e</td>
    <td>r</td>
    <td>t</td>
 </tr>          
{% endblock %}
//////// End Block custom /////////////

{% block body %}
{{ form_start(form) }}
....
<table id="eagle_laboratorybundle_pvp_methodes" class="row"
                data-prototype=" 
{{form_widget(form.methodes.vars.prototype)|e('html_attr') }}"
                data-index="{{ form.methodes|length }}">
<thead>
     <tr>
         <th>x</th>
         <th>y</th>
         <th>z</th>
         <th>a</th>
         <th>r</th>
         <th>e</th>
         <th>t</th>
     </tr>
 </thead>
 <tbody>
       {{ form_widget(form.methodes) }}
       {{ form_errors(form.methodes) }}
 </tbody> 
</table>


/// Some JS etc.../// 
```

So with the block _entry_widget i expected to custom rows of my table like it permit to custom div when i'm using original layout theme.

Someone know how to custom form rendering with table theme ?

**Comment by javiereguiluz** [comment]
@zayders I don't think your last example can work. As explained in this section -> https://symfony.com/doc/current/form/form_themes.html#creating-your-own-form-theme if you are defining the form theme inside the Twig template itself, you must use this:

```twig
{% form_theme form _self %}
```

instead of what you are using in your theme now:

```twig
{% form_theme form.methodes 'form_table_layout.html.twig' %}
```

Please, double check the mentioned article and see if this works following what the article says. If it doesn't, and we can confirm the error, we can reopen this issue later. Thanks!
