### ISSUE TITLE
[DX] Add a folded diff-result of what Maker Bundle did

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony-docs#11026]
Not everyone wants or can use the Maker Bundle (e.g. because of using non-default directory structure). Therefore having the documentation MakeBundle-only (e.g. https://symfony.com/doc/current/security.html) makes things harder. @javiereguiluz even mentioned this: _we plan to use MakerBundle even more in the docs_ in https://github.com/symfony/symfony-docs/issues/10876#issuecomment-455499607

I understand that it may be easier for new Symfony users and I don't want to open discussion about it here.

But what I suggest is to **add a folded section to each part of the documentation where the MakerBundle is used. This section will contain the code, the MakerBundle would generate with the options passed.** 

This will keep the life easy for the MakerBundle users but won't make it harder for the non-users.

What do you think?

**Comment by javiereguiluz** [comment]
We agree with this issue. The main problem was that in this article: https://symfony.com/doc/current/security/form_login_setup.html we said that the Maker command updated the security config file, but we didn't show the actual changes. We now show them and we'll do the same in the future if we use the MakerBundle in other parts of the docs. That's always been our intention: show the commands first to make you productive, but also show the changes to explain them.

If there are more specific issues in some articles, we can open new dedicated issues for them. Closing as fixed then. Thank you!

**Comment by mhujer** [comment]
@javiereguiluz Thank you! The _login form_ documentation looks super-useful with both Maker instructions and the actual code 👍 

I've created a separate issue https://github.com/symfony/symfony-docs/issues/11265 for the Security page.
