### ISSUE TITLE
Complete the documentation of the workflow options

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#11043]
In #11041 we listed the workflow config options to complete the config reference. Now someone who knows the Workflow component well must add the docs for those options.

Keep in mind that in `/workflow/*.rst` we have several articles explaining workflows and state machines, so we don't have to repeat everything in the config reference.

Thanks!

**Comment by noniagriconomie** [comment]
@javiereguiluz I give it a try on https://github.com/symfony/symfony-docs/pull/11492

**Comment by javiereguiluz** [comment]
Fixed by #11492.
