### ISSUE TITLE
Wrong link in symfony/var-exporter repository

### ISSUE THREAD

**Issue by xserrat** [symfony/symfony-docs#11076]
I've just found a wrong link to the `symfony/var-exporter` documentation on the initial description and also in the `Documentation` link:

https://github.com/symfony/var-exporter

**Comment by royklutman** [comment]
That is a dead link because the `VarExporter` component isn't yet documenten, see #10230.

I see this is your first issue in the docs, thanks and welcome!

**Comment by javiereguiluz** [comment]
Fixed by #11258, which was just merged. Thanks!
