### ISSUE TITLE
[phpunit-bridge] Correctly handling locale

### ISSUE THREAD

**Issue by melkamar** [symfony/symfony-docs#11087]
Some of our unit tests break when using `phpunit-bridge` due to this "feature":

> Forces the tests to use a consistent locale (C);

There is no further documentation about this. 

- Can the default locale be changed to something else than C?
- What is the proper way to write code that depends on the locale? Are we supposed to explicitly call `setlocale()` in every function that needs it so that granular unit tests pass?

**Comment by raymondschouten** [comment]
Same issue here... Forcing the locale to "C" makes `iconv` unable to transliterate accents and now completely removes accented characters as being "invalid".

**Comment by javiereguiluz** [comment]
@nicolas-grekas quick question: does this look like a bug on the code ... or is this expected and something to be documented? Thanks.

**Comment by nicolas-grekas** [comment]
Phpunit provides a setLocale method for locale-sensitive tests, see e.g. https://git.higidi.com/TYPO3/TYPO3.CMS/commit/8f997b6de9e227885859740895cfe261705801dd

That's unrelated to the bridge: tests should not be context-dependent

**Comment by raymondschouten** [comment]
@nicolas-grekas thanks, I was not aware of that method provided by PHPUnit!
