### ISSUE TITLE
Documentation for the CLI Webserver

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#11090]
There is this awesome new tool that we can download from https://symfony.com/download. It allows me to run a local webserver with multiple installed PHP versions.

I'd like to advertise this tools to my coworkers, but unfortunately all my knowledge about this tool comes from various SymfonyCon and SymfonyLive slide decks. It would be awesome if I could point them to some website that documents that tool. Unfortunately, I couldn't find one.

Should we add a documentation about the webserver provided by the Symfony CLI installer to this repository? I would volunteer to help, but I don't really know if this is the right place to do this. Also, the tool being closed-source doesn't really help me understanding it well enough to document it thoroughly.

**Comment by OskarStark** [comment]
Thank you and as you already mentioned on twitter, we can close this issue.

The new documentation was introduced in
