### ISSUE TITLE
Symfony download instructions don't work on MacOS

### ISSUE THREAD

**Issue by michaelperrin** [symfony/symfony-docs#11097]
I tried to create a Symfony project like a beginner would do. I followed these steps:

1. Go on symfony.com.
2. Click on Download (the page is https://symfony.com/download)
3. Copy and paste the following command that is given:

```
wget https://get.symfony.com/cli/installer -O - | bash 
```

4. Run it in a terminal on MacOS.

This gives `wget: command not found` (and it indeed doesn't exist on MacOS by default).

This is a severe issue as new comers won't go much further if the very first thing doesn't work.

**Comment by linaori** [comment]
Seems like an alternative that _should_ always be available, would be `curl -O`, but I can't confirm this as I don't have a mac.

**Comment by kiler129** [comment]
Yes, `curl` is available on the macOS by default. You also have `php` by default.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue! We're going to replace this:

```
wget https://get.symfony.com/cli/installer -O - | bash
```

by this:

```
curl https://get.symfony.com/cli/installer | bash
```

but only for Mac. Linux will keep using `wget`. Thanks.

**Comment by michaelperrin** [comment]
Looks good to me @javiereguiluz . Thanks :)
I think I will do this more often, to behave like "I don't know anything about Symfony, let's give it a try" and see how the experience is.

**Comment by javiereguiluz** [comment]
@michaelperrin and that's infinitely amazing 😍 and we'll be super grateful to you 🙏  Please, report anything you don't like or think it's confusing, no matter how "unimportant" it may look like.

**Comment by javiereguiluz** [comment]
Closing as fixed because the macOS download now uses `curl`. Thanks!
