### ISSUE TITLE
Document Monolog log formats

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony-docs#11144]
I've been asked to contribute to this here https://github.com/symfony/recipes/pull/552#discussion_r264709679 , I think it could be interesting to set this issue as an easy-pick.

The goal is to retrieve the log formats:
https://github.com/symfony/symfony/blob/18cd3420a44abbeacf96758daeb3ac7b8cf87f10/src/Symfony/Bridge/Monolog/Formatter/ConsoleFormatter.php#L50-L54

And add a small block in the ["Channel handlers"](https://github.com/symfony/symfony-docs/blob/master/logging/channels_handlers.rst) documentation file explaining the possible ones.

WDYT?

**Comment by wouterj** [comment]
I short of remember we once discussed this with @Seldaek  and decided it's no use to document all handlers and their settings: It's very likely to get outdated.

So I'm against documenting all monolog handlers, but we can add a short section about handlers that are provided by Symfony.

**Comment by Pierstoval** [comment]
I create the issue mostly because of the recipe that I linked that adds a message about text formatting in the console logs. IMO if such handler has at least an example in a recipe (which is official stuff), maybe it should be documented?

**Comment by javiereguiluz** [comment]
I agree with Wouter, this is the kind of documentation that is hard to maintain and keep it in sync with the code (hopefully the code includes PHPdoc annotations to describe its functionality and config options).

Moreover, even if Monolog is closely related to Symfony, it's a third-party project, so its doc is out of the scope of Symfony Docs. Sorry! ... and thanks for understanding!
