### ISSUE TITLE
upload_file.rst: Recommend view transformer instead of manually "transforming" the property?

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#11158]
On https://symfony.com/doc/current/controller/upload_file.html in the 4th code block it says:
```php
// updates the 'brochure' property to store the PDF file name
// instead of its contents
$product->setBrochure($fileName);
```
But the "second part" is not documented: If the file is already present, you also have to do this before creating the form: 
```php
$product->setBrochure(new File($product->getFileName()));
```
So the general question is: Wouldn't it be better to recommend a [Data Transformer](https://symfony.com/doc/current/form/data_transformers.html) instead of manually transforming back and forth in the controller?

This would (would it?) also solve this problem with EasyAdmin: https://github.com/EasyCorp/EasyAdminBundle/issues/2356

**Comment by xabbuh** [comment]
I thought about this chapter a couple of times as I don't think it's really straight-forward. My current idea would be to let the `setBrochure()` method only accept `\SplFileInfo` objects and also return only these in `getBrouchre()`. I think the whole chapter would be more concise then.

**Comment by javiereguiluz** [comment]
Hi! I'm closing this in favor of #8255, which is a meta-issue which stores all the things related to improving the "File Upload" article. Thanks!
