### ISSUE TITLE
Should we remove the GitHub repository reference in Components?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#11295]
In [this comment](https://github.com/symfony/symfony-docs/pull/11280#discussion_r271829361) Fabien wonders if we could get rid of that phrase in all component docs:

![components-repo-clone](https://user-images.githubusercontent.com/73419/55542254-ee1e7e80-56c6-11e9-97a3-b1f7b50bad4e.png)

**Comment by fabpot** [comment]
I think/hope most of Symfony users are Composer users as well.

**Comment by dbrumann** [comment]
I will create a PR removing this phrase throughout the current documentation. #EUFOSSA
