### ISSUE TITLE
Wrong env file assignment

### ISSUE THREAD

**Issue by vonalbert** [symfony/symfony-docs#11304]
In `setup/symfony_server.rst` in the "Docker integration" paragraph there's a typo:
the code should be

`DATABASE_URL=${MYSQL_URL}`  instead of `MYSQL_URL=${DATABASE_URL}`

because you're going to override your local DATABASE_URL value with the autogenerated MYSQL_URL variable provided by the symfony cli tool.

**Comment by dbrumann** [comment]
I will take a look at it
