### ISSUE TITLE
[Workflow] missing twig function "workflow_all_transitions"

### ISSUE THREAD

**Issue by cawolf** [symfony/symfony-docs#11376]
Hi everyone,

when copy-pasting an example of the documentation regarding blocked transitions in a fresh Symfony project, I found that a Twig function is not defined (neither in `4.2` nor `master`).

        {% for transition in workflow_all_transitions(article) %}

Learning from #11268, maybe you also want to add this function to the core? Or should there be another example utilizing the `$workflow->getDefinition()->getTransitions()` function?

Best regards,
cawolf

**Comment by HeahDude** [comment]
We'll have to adapt the docs for now.

@cawolf thank you for opening this issue. I'll try to work on it this week-end unless some one want to give it a try.

To discuss whether we should have use cases to have this function in core, please open an issue in [the core repository](https://github.com/symfony/symfony/issues), thanks!

**Comment by OskarStark** [comment]
I would propose „workflow_transitions_all“

**Comment by lyrixx** [comment]
Hello. This function did not exist in the core. It has been refused already. What is your use case ?

**Comment by cawolf** [comment]
Hi, at the time I opened this issue, the function was indeed not in the core, but it was documented. I used the example from the documentation to experiment with a workflow I was building, and stumbled upon errors when doing so.

Since the documentation changed in the last month and doesn't mention the function anymore, I'm happy to close this issue.
