### ISSUE TITLE
[Serializer] AnnotationReader usage is not registered

### ISSUE THREAD

**Issue by rufinus** [symfony/symfony-docs#11380]
As per @nicolas-grekas request,

If using the Serializer as component the annotation loader is not registred.

see https://github.com/symfony/symfony/issues/26083 for a disccusion about it.

Documentation - https://symfony.com/doc/current/components/serializer.html#deserializing-an-object

**Comment by xabbuh** [comment]
@rufinus Can you share such a simple application so we can check whether that's a misunderstanding or some missing pieces in the documentation?

**Comment by maxhelias** [comment]
@rufinus any feedback for this issue?
