### ISSUE TITLE
Add a copy code button

### ISSUE THREAD

**Issue by abdounikarim** [symfony/symfony-docs#11393]
Hello,

Can you add a copy code button to easily and rapidly copy the documentation code ?

Thanks

**Comment by javiereguiluz** [comment]
The main issue about this is that with the current doc build process, we don't have the original code, but only its highlighted version. Can we transform "highlighted -> original" automatically in all cases without any errors?

**Comment by wouterj** [comment]
@javiereguiluz this is quite easy with JS: ``codeBlock.querySelector('.code').textContent`` will give you the code without line numbers or highlights (where ``codeBlock`` is i.e. ``.literal-block`` or any other parent of ``.code`` and ``.linenos``)

**Comment by javiereguiluz** [comment]
Closing as fixed. See: https://symfony.com/blog/copy-code-from-symfony-com-examples

Thank you Wouter for your help and thank you @abdounikarim for your idea.
