### ISSUE TITLE
[Upload File]: Doctrine Listener vs. view transformer for File<=>String conversion

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#11390]
Is a Doctrine Listener preferred over a view transformer to switch between the `File` instance and the string? I'm wondering, since the error message recommends a view transformer:

> The form's view data is expected to be an instance of class Symfony\Component\HttpFoundation\File\File, but is a(n) string. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) string to an instance of Symfony\Component\HttpFoundation\File\File.

...whereas on https://symfony.com/doc/current/controller/upload_file.html a view transformer isn't even mentioned.

**Comment by javiereguiluz** [comment]
Closing as "fixed" because we recently updated the article about file uploading and we removed everything related to Doctrine listeners. Thanks.
