### ISSUE TITLE
Missing "see also" reference in redis component cache, to framework cache config

### ISSUE THREAD

**Issue by linaori** [symfony/symfony-docs#11432]
The page [components/cache/adapters/redis_adapter](https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html) is missing a reference back to the framework docs. It could very well be missing elsewhere, but this is the page where I found it.

My suggestion is to add something in form of "To configure this component in symfony, you can refer to the [cache pool configuration](https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle) in the framework bundle."

An example can be found on https://symfony.com/doc/current/components/console.html#creating-a-console-application

(from @javiereguiluz)
![image](https://user-images.githubusercontent.com/1754678/56133568-075be080-5f8d-11e9-8f37-ee65e5efc957.png)

**Comment by javiereguiluz** [comment]
Fixed by #11493.
