### ISSUE TITLE
Document the new "native" and "auto" encoder algorithms

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#11452]
see https://github.com/symfony/symfony/pull/31140 , `auto` should be the recommended value as of 4.3.

**Comment by chalasr** [comment]
`bcrypt` has been deprecated also https://github.com/symfony/symfony/pull/31170

**Comment by fmonts** [comment]
+1, here it still says "bcrypt or sodium are reccomended"
https://symfony.com/doc/current/security.html#c-encoding-passwords

Also I don't find anywhere how long the password field should be in the database, changing from bcypt to auto is incompatible with existing db structure, see https://stackoverflow.com/questions/56394016/max-length-for-user-password-field-with-algorithm-auto
