### ISSUE TITLE
3.4 docs mentions server:ca:install command, none present

### ISSUE THREAD

**Issue by tonykiselis** [symfony/symfony-docs#11464]
Just as it says. At this point I think it's simply a mistake in the docs. Although took me some hours to realize that it's not me doing the wrong thing.

**Comment by javiereguiluz** [comment]
That command is provided by the Local Symfony Server, which is explained in https://symfony.com/doc/3.4/setup/symfony_server.html  That article shows how to install the local server first and then shows some commands in practice, such as `server:ca:install`.

How did you run the `server:ca:install` command? Did you use the Symfony server ... or the Symfony console script (`php bin/console ...`)?

**Comment by javiereguiluz** [comment]
I'm closing because of the lack of feedback. Hopefully this was solved.
