### ISSUE TITLE
[UploadFile]: Recommend unmapped field for the file?

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#11481]
Wouldn't it be better to recommend an unmapped field (`'mapped'=>false`) for the file upload at https://symfony.com/doc/current/controller/upload_file.html ?

Advantages:

* Would mitigate the hassle with String<=>File conversion (see https://github.com/symfony/symfony-docs/issues/11390 )
* The main benefit of mapping is that on an "edit profile" form the form fields get prefilled with the current database values. But in this case, it doesn't make sense for the user to change the string (=file path) in the database, since the file wouldn't exist! So the real way to "edit" an uploaded file is to upload a new one (which should then overwrite the existing one in the controller).
* Would solve https://github.com/EasyCorp/EasyAdminBundle/issues/2356

**Comment by weaverryan** [comment]
We do this on our SymfonyCasts tutorial - I agree that it's much easier to work with.

**Comment by eiannone** [comment]
In this way you cannot define assert validation on the entity class. So what would be the preferred method for validation?

**Comment by weaverryan** [comment]
Exactly right - you would add to the form directly via the constraints option.
