### ISSUE TITLE
[Intl] Extra timezone utilities

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-docs#11499]
follow up of #11447 

added `Timezones::getCountryCode/forCountryCode` in https://github.com/symfony/symfony/pull/31262

added `Timezones::getRaw/GmtOffset` in https://github.com/symfony/symfony/pull/31295 and https://github.com/symfony/symfony/pull/31318

**Comment by rwitchell** [comment]
Hi @ro0NL  - if I've got the value `Asia/Kolkata`, how do I use this with the symfony `Timezones` class (which only has `Asia/Calcutta`)? (it's not clear in the docs)
