### ISSUE TITLE
Call a command from a controller example not working

### ISSUE THREAD

**Issue by Rmy5** [symfony/symfony-docs#11509]
In the [doc](https://symfony.com/doc/current/console/command_in_controller.html) there is an example on how to call a command from a controller.

When I inject `KernelInterface $kernel` in my controller method and try to use it like so:
`$application = new Application($kernel)` I get:

>Argument 1 passed to Symfony\Component\Console\Application::__construct() must be of the type string, object given
>

Not sure what string to pass to Application constructor.

**Comment by xabbuh** [comment]
It looks like you confused the `use` statement for the `Application` class. You need to use the one from the `Symfony\Bundle\FrameworkBundle\Console`. :)
