### ISSUE TITLE
Document the Mailer component

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#11531]
In 4.3 we added two closely related components: Mime and Mailer.

We have the full docs of Mime: https://symfony.com/doc/master/components/mime.html

But Mailer must be documented: https://symfony.com/doc/master/components/mailer.html

I tried to use this presentation from Fabien to document the Mailer, but I couldn't because I don't fully understand it: https://speakerdeck.com/fabpot/mailer?slide=35

**Comment by cvergne** [comment]
Hello,
Is there any way to help ? Is there already a draft ? :)

**Comment by harikt** [comment]
I have made an attempt. See https://github.com/symfony/symfony-docs/pull/11626 .

**Comment by bocharsky-bw** [comment]
More related changes in #11633
