### ISSUE TITLE
[Intl] Renamed Regions to Countries

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#11532]
I still think it's a big mistake 😢 but we'll need to update the current docs: https://github.com/symfony/symfony/pull/31350

**Comment by ro0NL** [comment]
Hi @javiereguiluz, thanks for taken care here :)

I understand your POV about regions vs. countries, but we need something to reason about.

Regions: world, (sub-continents), "countries/terroritories"
Countries: ISO 3166-1 alpha-2 (officially assigned)

For the docs it could be worth clarifying what we mean when we use "country".

The main reason for the PR was, it directly affects `CountryType/CountryValidator`. Discussing the naming should be done across the board IMHO.

Moreover, ICU itself uses "countries" as a term for all regions: https://github.com/unicode-org/icu/blob/master/icu4c/source/data/region/en.txt#L4 :man_shrugging: 

Moreover, after we excluded numeric codes (continents) and a **few** "non officially-assigned country codes" the list got ISO 3166-1 alpha-2 compliant, which to me proves ICU follows the same ISO standards.

**Comment by javiereguiluz** [comment]
I still think that the best solution is to use the ICO list of "Countries" + "Territories" and call that "Regions".

In the list of ISO "countries" you can find "jokes" like this: [Bouvet Island](https://en.wikipedia.org/wiki/Bouvet_Island). It's NOT a country and 0 people live there.

**Comment by ro0NL** [comment]
That could be worth considering, at least the current data set is OK now. Leaving us with a naming issue then.

Im fine with "country", so i'll leave this RFC proposal up to you. I think "country" is the most common/recognizable term in general, and conforms with upstream references let's say: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
