### ISSUE TITLE
ACL Documentation

### ISSUE THREAD

**Issue by samsamm777** [symfony/symfony-docs#1153]
The documentation for ACL's is very poor. I think there should be some more in depth documentation on how to apply permissions to classes and how to edit permissions via Forms. This is a common real world use for the ACL's.

**Comment by javiereguiluz** [comment]
@WouterJ @xabbuh this issue was opened more than three years ago. During this time, the ACL is not only not getting love, but we are actively working to remove it from the core of Symfony. Maybe it's time to close this issue as "won't fix" and acknowledge that ACL will never be documented.

**Comment by WouterJ** [comment]
@javiereguiluz it's going to be *extracted* to a separate bundle in the Symfony organization, afaik. This means it's still officially supported by Symfony and needs to be documented.

**Comment by javiereguiluz** [comment]
@WouterJ if that's what you think, let's keep this issue open then. But in my opinion, if the ACL got almost zero attention being in the core, when we finally extract it, it will get exactly zero attention or even less.

**Comment by javiereguiluz** [comment]
Closing it as "won't fix". The ACL component now has its own dedicated repository outside of the main Symfony repository (https://github.com/symfony/security-acl/). Besides, the component is semi-abandoned (see https://github.com/symfony/security-acl/issues/31).
