### ISSUE TITLE
broken link to image in How to Use Data Transformers

### ISSUE THREAD

**Issue by bzoks** [symfony/symfony-docs#11548]
Page "How to Use Data Transformers" has broken link to image in chapter "About Model and View Transformers".
Direct link to chapter:
https://symfony.com/doc/current/form/data_transformers.html#about-model-and-view-transformers
Broken link to image: https://symfony.com/doc/current/_images/data-transformer-types.png
Part with broken image url (formatted):
```html
<div class="figure">
<img 
   alt="../_images/data-transformer-types.png" 
   class="align-center" 
   src="../_images/data-transformer-types.png" />
</div>
```

**Comment by javiereguiluz** [comment]
@bzoks thanks for reporting this issue ... but looking at the chapter URL you shared ... it looks like the problem has been solved. I can see the image correctly, so we're closing this issue as "fixed". If the reported problem was different, please tell me and we'll reopen this. Thank you.
