### ISSUE TITLE
[Workflow] Support for getting a workflow from registry using a class instead of an instance

### ISSUE THREAD

**Issue by asimonf** [symfony/symfony-docs#11550]
This may be possible, but I didn't find it in the code. It would be awesome if something like this was possible:

```
    $workflow = $this->workflowRegistry->get(Object::class);
    $workflow->apply($object, 'to_next');
```

In my case, I would get the workflow from the class to be able to loop in a messenger handler on many objects and apply the transition.

**Comment by noniagriconomie** [comment]
Hi, looks like more a feature request on symfony/symfony rather than doc, or i do not understand

Do you have some code example to show?

**Comment by asimonf** [comment]
Indeed, it is a feature request. Is there another channel for these?
