### ISSUE TITLE
[Translator] Alternative method to add resources for a DB loader

### ISSUE THREAD

**Issue by linaori** [symfony/symfony-docs#11579]
According to the [translation dic tag documentation](https://symfony.com/doc/current/reference/dic_tags.html#translation-loader) you have to add empty files in order to have the translator pick up the loader for database translations. You can also add a compiler pass that fetches the translator and calls `addResource`, this would ensure the resource is loaded. Perhaps this is valuable to document?

```php
final class AddDbalTranslatorResourcesPass implements CompilerPassInterface
{
    /** {@inheritDoc} */
    public function process(ContainerBuilder $container) : void
    {
        $translatorDefinition = $container->getDefinition('translator.default');
        $locales              = ['nl', 'en', 'fr', 'de'];

        foreach ($locales as $locale) {
            $translatorDefinition->addMethodCall('addResource', [
                'dbal',
                new Reference(DbalLoader::class), // custom loader service id
                $locale,
                'message_domain',
            ]);
        }
    }
}
```
Perhaps this is a DX issue that should be fixed in the framework instead?

**Comment by javiereguiluz** [comment]
I don't know much about what you are talking here ... but from my ignorance, this -> *"you have to add empty files in order to have the translator pick up the loader for database translations"* looks like a Symfony hack/shortcoming and we should try to improve that in code before attempting to document it.

**Comment by linaori** [comment]
I'll open an issue in the symfony/symfony repository instead as I agree with you.
