### ISSUE TITLE
[Routing] The parameter "app.route_prefix" must be defined

### ISSUE THREAD

**Issue by mfrieling** [symfony/symfony-docs#11581]
I followed [How to Use Service Container Parameters in your Routes](routing/service_container_parameters.rst) to configure the `_locale` prefix for the Sonata Admin routes in my project and got the error message

>The parameter "app.route_prefix" must be defined.

After a second look on the documentation and my local changes I found out that the section "_You can also use a parameter to define your route path (or part of your path)_" uses the `%app.route_prefix%` parameter but never defines it. In the documentation the information should be added, where and how to define this parameter, especially that "__locale_" must be added as placeholder `{_locale}` and not as `_locale`:

YAML:
```yaml
# config/services.yaml
parameters:
  app.route_prefix: '{_locale}'
```
XML:
```xml
<!-- config/services.xml -->
        <?xml version="1.0" charset="UTF-8" ?>
        <container xmlns="http://symfony.com/schema/dic/services"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://symfony.com/schema/dic/services
                https://symfony.com/schema/dic/services/services-1.0.xsd">

            <parameters>
                <parameter key="app.route_prefix">{_locale}</parameter>
            </parameters>
        </container>
```
PHP:
```php
// config/services.php
        $container->setParameter('app.route_prefix', '{_locale}');
```

_I'm not editing the documentation on my own because I don't know the exact syntax for RST and and the Symfony rules for the documentation and at the moment have no time to read into it :-(_

**Comment by javiereguiluz** [comment]
@mfrieling thanks for reporting this issue. You are right and we're trying to improve this in #11587. However, we prefer to not use the `{_locale}` parameter as an example. The reason is that "routing + locale/i18n" has improved a lot in recent Symfony versions, so we don't want to mix those here. that's why we used a normal parameter. Thanks.

**Comment by mfrieling** [comment]
@javiereguiluz I understand your rationale to use a generic parameter. Mine to use `{_locale}` was to complete the existing example of https://symfony.com/doc/current/routing/service_container_parameters.html using it, because without the missing `app.route_prefix` parameter that example simply doesn't work. Therefore I suggest fixing that example accordingly as well to giving an example with a generic parameter as you've done in #11587.
