### ISSUE TITLE
[Validator] Email constraint strict option disappeared from docs

### ISSUE THREAD

**Issue by guilliamxavier** [symfony/symfony-docs#11608]
... between [4.0](https://symfony.com/doc/4.0/reference/constraints/Email.html) and [4.1](https://symfony.com/doc/4.1/reference/constraints/Email.html).
Even if deprecated (and superseded by the new mode option) in 4.1, [it still exists](https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Validator/Constraints/Email.php) (until 5.0 I guess).
Compare with e.g. the checkHost/checkMX options (marked as deprecated).
Cf https://github.com/symfony/symfony-docs/pull/8487#discussion_r283264129

**Comment by OskarStark** [comment]
But it didn’t disappear, it’s just moved unter the „mode“ option. Is this what you meant?

**Comment by guilliamxavier** [comment]
I meant that (when comparing with the 4.0 docs) the 4.1+ docs give the wrong impression that the `strict` option (bool) has been *replaced* by the `mode` option (string), i.e. that 4.0's `@Assert\Email(strict = true)` *does not work anymore* on 4.1+ (and *requires* to be changed to `@Assert\Email(mode = "strict")` immediately on upgrade), while it has only been deprecated (because superseded) but still exists and works.

In other words, I think that #8487 should not have *modified* the doc of the existing `strict` option to integrate it into the new `mode` option, but rather should have *copied* its description (and adapted it) for the `"strict"` value of the new `mode` option and just *annotated* the original option as "deprecated since 4.1" (like e.g. [the `checkHost` option in 4.2+](https://symfony.com/doc/4.2/reference/constraints/Email.html#checkhost)).

Does that make sense?

**Comment by OskarStark** [comment]
From your comment... it makes sense, not quite sure why we did it this way.
@javiereguiluz can you help here?

**Comment by xabbuh** [comment]
IIRC we tried not to document deprecated features. While that's good for most articles we should probably keep them in the reference but add a deprecation warning instead.

**Comment by guilliamxavier** [comment]
It guess that's not worth keeping this open any longer.
