### ISSUE TITLE
[Validator] Bic constraint iban* options do not exist in 4.2

### ISSUE THREAD

**Issue by guilliamxavier** [symfony/symfony-docs#11607]
... yet they appear in [the current 4.2 docs](https://symfony.com/doc/4.2/reference/constraints/Bic.html).
Cf https://github.com/symfony/symfony-docs/pull/10349#issuecomment-491723785

Refs #11111 (only done in the 4.3 branch)

**Comment by javiereguiluz** [comment]
Fixed by 11642.
