### ISSUE TITLE
Minor upgrade guide has incorrect information regarding version constraints

### ISSUE THREAD

**Issue by andyexeter** [symfony/symfony-docs#11627]
The minor upgrade guide at https://symfony.com/doc/current/setup/upgrade_minor.html#update-the-symfony-library-via-composer states:

> Your composer.json file should already be configured to allow your Symfony packages to be upgraded to minor versions.

But Symfony installs use `4.2.*` style constraints so this is incorrect and a `composer update` will only update patch releases, not minor versions. The documentation should be updated to reflect this.

After discussing with @nicolas-grekas on Slack, he asked me to open an issue.

**Comment by wouterj** [comment]
Fixed by @JoppeDC in #11627 . Thanks for reporting!
