### ISSUE TITLE
Add docs for: [Form] remove deprecated date types options handling

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11644]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#31777
| PR author(s) | @xabbuh

**Comment by xabbuh** [comment]
@javiereguiluz You already fixed this in #11621. 😄

**Comment by javiereguiluz** [comment]
I'm really sorry! There's so much activity that it's easy to forget about previous changes 😞
