### ISSUE TITLE
Add docs for: [FrameworkBundle][TwigBundle] Add missing deprecations ..

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11654]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#31821
| PR author(s) | @yceruto

**Comment by Tobion** [comment]
There isn't anything to update. Has been handled in #11231 and https://symfony.com/doc/current/templating/render_without_controller.html doesn't mention any php templates.

**Comment by ot7746592** [comment]
https://connect.symfony.com

**Comment by javiereguiluz** [comment]
Closing as "fixed" for the reasons given by Tobias.
