### ISSUE TITLE
[Messenger] Add clear Entity Manager middleware

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11657]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#31334
| PR author(s) | @Koc
|Merged in | 4.4

**Comment by Koc** [comment]
Depends on https://github.com/doctrine/DoctrineBundle/pull/980

**Comment by OskarStark** [comment]
The depending Doctrine PR is now merged
