### ISSUE TITLE
Add docs for: [Workflow] Add colors to workflow dumps

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#11675]
Feature PR: https://github.com/symfony/symfony/pull/29538

Now that #9476 has been fixed by superseded by #11209, and this last one is merged, we can document how to add colors.

For reference, see this nice example from @Korbeil :smiley: : https://twitter.com/Korbeil_/status/1135914174603714565

**Comment by GitLuca** [comment]
Hi, any news on this documentation? 
Symfony 4.3 is out but i cannot find any good documentation on how to change color to workflows. To be honest everything concerning workflows in Symfony is really fragmented and hard to find and understand. I tried to follow this example but without any luck https://symfony.com/blog/new-in-symfony-4-3-workflow-improvements

**Comment by javiereguiluz** [comment]
@GitLuca you are right. Sadly, there are so many components that the main Symfony Doc maintainers can't master all of them. We're mainly having problems with Workflow, Messenger and Serializer. We can't get enough contributors and reviewers.

**Comment by alexislefebvre** [comment]
@GitLuca you can find in the PR: https://github.com/symfony/symfony/pull/29538

**Comment by alexislefebvre** [comment]
See #11907
