### ISSUE TITLE
[Community Reviews] outdated advice to use Symfony Standard

### ISSUE THREAD

**Issue by boite** [symfony/symfony-docs#11692]
In the [Community Reviews doc](https://github.com/symfony/symfony-docs/blob/cc9d8ece0d582831be3e7edc9e2c14141d34a879/contributing/community/reviews.rst) we are advised to reproduce problems in the Symfony Standard edition, but the [README](https://github.com/symfony/symfony-standard/blob/3.4/README.md) for the Symfony Standard edition contains a warning which seems to indicate that this advice is outdated:-

> WARNING: This distribution does not support Symfony 4. See the Installing & Setting up the Symfony Framework page to find a replacement that fits you best.

Should the reviews doc updated to advise the reproduction of bugs/PRs using one of the skeletons?

**Comment by javiereguiluz** [comment]
@boite good catch! Thanks for reporting this error. We're trying to fix it in #11712.
