### ISSUE TITLE
Add docs for: [WebProfilerBundle] Select default theme based on user ..

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11720]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#31919
| PR author(s) | @javiereguiluz

**Comment by fabpot** [comment]
This new question of gh does not fit my workflow, sorry for the noise.

**Comment by javiereguiluz** [comment]
I'm not sure it's noise ... in theory, 100% of features should be documented, even if they are small.

Most issues related to tiny features will be closed, but it's worth it to double check if they require us to change something.
