### ISSUE TITLE
[Migration.rst] Add some suggestions to avoid direct access to global $kernel 

### ISSUE THREAD

**Issue by Phenix789** [symfony/symfony-docs#11742]
Current page : [migration.rst](https://github.com/symfony/symfony-docs/blob/master/migration.rst)

First thanks for this article, it's plenty of good advises to migrate application.

I would like to add a section to how to encapsulate the access to `global $kernel`.
In my opinion, it's a bad practice to access directly to the `global $kernel`

For example, in class context, you can define a `trait` to give you some shortcut :

```php
trait SymfonyLegacy
{
  private function getKernel(): Kernel
  {
    global $kernel;

    return $kernel;
  }

  protected function getContainer(): ContainerInterface
  {
    return $this->getKernel()->getContainer();
  }

  protected function get(string $service): object
  {
    return $this->getContainer()->get($service);
  }

  //...
}
```

And, in your existing class I think it's better to write something like this :

```php
class MyClass
{
  use SymfonyLegacy;

  public function myExistingFunction()
  {
    // To avoid
    global $kernel;

    $service = $kernel->getContainer()->get('my_service');

    // Better way
    $service = $this->get('my_service');

    // Best way
    $service = $this->getMyService();
  }

  private function getMyService() { return $this->get('my_service'); }
}
```

If you use the `global $kernel` directly, you will have some trouble in future when you will wanted to only run symfony project.
Instead, with a `trait` and maybe `interface` you will be able to easily inject services and/or modify the `trait`.

In addition, you can do the same in script context via some helper functions :

```php
function get_kernel(): Kernel
{
  global $kernel;

  return $kernel;
}

// ...
```

---

WDYT @wouterj @dbrumann ?

**Comment by Phenix789** [comment]
Thanks for you answer.

>  the visibility for the methods should be reduced to protected

You're absolutely right. It was an error from myself when I write the issue

> I would prefer not having the Trait, but instead have the "code smell" right there in the class using the $kernel to remind myself, that I have to clean this up at a later stage

I get your point, and I can agree with it even if I prefer the trait :wink: .

> replacing the current example with it is fine for me.

I not really wanted to replace your example by mine. I just wanted to add an additional tip.

**Comment by javiereguiluz** [comment]
Thank you both for the discussion. I think both of you are right and both proposals have merits. I don't any of the solutions is much better than the other so, as @dbrumann said, this seems to come down to personal taste.

So, considering that we have hundreds of pending issues to document 😭, let's close this as "won't change it". (We'll reopen in the future if people start complaining about this). Thanks!
