### ISSUE TITLE
Deprecated --env command option in docs

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony-docs#11787]
I find in this url : https://symfony.com/doc/current/configuration.html#selecting-the-active-environment

Maybe a mistake from a deprecated command option "--env". 
If we need remove this, i can PR for remove this mistake.

Gary

**Comment by javiereguiluz** [comment]
Do you mean that we mention the `--env` option in this block?

![image](https://user-images.githubusercontent.com/73419/59749556-83202500-927d-11e9-9b91-2eee8771b0dc.png)

If that's the case, we think this is correct. That article belongs to the Symfony 4.3 version, so we explain that the env of the commands was selected differently in 4.2, but it was deprecated.

In the Symfony 5 docs we'll remove that deprecation notice. You should see that in the "master" version of the docs, which correspond to Symfony 5.0: https://symfony.com/doc/master/configuration.html#selecting-the-active-environment
We're going to remove that deprecated doc soon. Thanks.

**Comment by TheGarious** [comment]
No problem, thanks :)

**Comment by Taluu** [comment]
@javiereguiluz actually, the deprecation was reverted in 4.2 (so it never made 4.2) : https://github.com/symfony/symfony/pull/29204
