### ISSUE TITLE
Symfony Distributions

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony-docs#11783]
As far as I understand it, Symfony Distributions are not for Symfony 4 as they are substituted by Symfony Flex.

Therefore a hint on the page https://symfony.com/distributions would be sensible.

**Comment by javiereguiluz** [comment]
@Mynyx thanks a lot for reporting this. We've just reworded that page to tell readers that "distributions" are no longer used since Symfony 4. The new contents will be displayed after the next deploy. Thanks.
