### ISSUE TITLE
How to connect to Twemproxy from Symfony/cache

### ISSUE THREAD

**Issue by lmathukumalli** [symfony/symfony-docs#11782]
We use Twemproxy to connect to Redis and Memcached.
Wondering if there is a way to connect to twemproxy using existing cache adapters in symfony/cache library.
If so, could you please provide some examples?
Thanks!

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
