### ISSUE TITLE
Offline Documentation The Cookbook

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony-docs#11797]
In the section "Offline Documentation" (at the bottom of the site https://symfony.com/doc/current/index.html), selecting "The Cookbook" leads to a "Document not found" error.

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because we removed all "offline docs" for the reasons explained here: https://github.com/symfony/symfony-docs/issues/1029#issuecomment-558181361
