### ISSUE TITLE
Composer Installation

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony-docs#11798]
The chapter "Installing & Setting up the Symfony Framework" (https://symfony.com/doc/current/setup.html) begins with "To create your new Symfony application, first make sure you're using PHP 7.1 or higher and have Composer installed. If you don't, start by installing Composer globally on your system." containing a link to https://symfony.com/doc/current/setup/composer.html.

There is the second paragraph "Since this article was first published, Composer installation has improved a lot. Therefore, the original contents of this article have been removed and you are encouraged to install Composer as explained in the official Composer documentation." with a link to https://getcomposer.org/download/.

But at this site only the local installation of composer is described and not the global installation.

**Comment by javiereguiluz** [comment]
Thanks for reporting this inconsistency. You are right. We're fixing it in #11806.

* We're going to remove the /setup/composer.html article because it was an outdate thing from the Symfony 2.0 era. It's no longer needed.
* We're going to link to Composer's download page directly.
* We're removing the mention to "global installation" in favor of just "installation".

**Comment by Mynyx** [comment]
When installing composer as described on Composer's download page, it will result in a composer.phar file.

How about adding a note like on the page "How to Install and Use the Symfony Components" (https://symfony.com/doc/current/components/using_components.html):
> Install Composer if you don't have it already present on your system. Depending on how you install, you may end up with a composer.phar file in your directory. In that case, no worries! Just run php composer.phar require symfony/finder.
