### ISSUE TITLE
Unclear navigation

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-docs#11841]
Hi,

At the Symfony website pages under "Quick Tour", "Create Framework", and perhaps other sections seem to suffer from an irrelevant left menu (or incomplete at least).

Visiting such pages directly from e.g. Google works counter-intuitive as it's not clear where on "symfony.com" we exactly are. They seem to be hidden "access points" referenced across the site?

- https://symfony.com/doc/master/quick_tour/the_big_picture.html
- https://symfony.com/doc/current/create_framework/index.html

It's a maze :)

**Comment by Mynyx** [comment]
This is also confusing when browsing the documentation for bundles or Symfony CMF.
