### ISSUE TITLE
Add docs for: [Lock] add an InvalidTtlException to be more accurate

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11848]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32180
| PR author(s) | @Simperfit

**Comment by javiereguiluz** [comment]
Closing as "won't fix". In the docs we mention that locsk lower than 1 are no valid for PDO locks:

```
.. note::

    This store does not support TTL lower than 1 second.
```

We don't mention the specific exception thrown in that case. I think this is OK because IDEs, logs and error messages clearly will tell you which exception is thrown.
