### ISSUE TITLE
[HttpFoundation][HttpKernel] Improving the request/response format auto…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11877]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32344
| PR author(s) | @yceruto
| Merged in    | pull/32344

**Comment by javiereguiluz** [comment]
I propose to close this as "won't fix" because this is an internal improvement about something that it's not explained in detail in the docs. I mean, we've always assumed that Symfony works the way it works after this PR.
