### ISSUE TITLE
[FrameworkBundle] Allow to use the BrowserKit assertions with Panther a…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11882]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32207
| PR author(s) | @dunglas
| Merged in    | pull/32207

**Comment by javiereguiluz** [comment]
Closing because we don't make any distinction in the docs about this. We only say the come from WebTestCase class.

**Comment by dunglas** [comment]
@javiereguiluz actually we'll have to remove the mention that it doesn't work with Panther when https://github.com/symfony/panther/pull/205 will be merged
