### ISSUE TITLE
Bundles link might be broken in symfony doc

### ISSUE THREAD

**Issue by gdc5** [symfony/symfony-docs#11880]
Hi.

The link on this page `https://symfony.com/doc/current/service_container/compiler_passes.html#working-with-compiler-passes-in-bundles` might be broken.

The *Bundles* link may be `https://symfony.com/doc/bundles/`.

Thanks.

**Comment by xabbuh** [comment]
Thanks for catching this @gdc5. 👍 We will fix it in #11884.

**Comment by gdc5** [comment]
@xabbuh  👍  Thanks for your time to pay attention and make a so quick fix.
