### ISSUE TITLE
[ServerBundle] Display all logs by default

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11916]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32423
| PR author(s) | @lyrixx
| Merged in    | 4.4

**Comment by lyrixx** [comment]
There is not reference to the server:log command in the documentation (only to symfony server:log, not bin/console server:log)

So I don't know what should be done here.

IMHO we can close this issue

**Comment by javiereguiluz** [comment]
Yes, we're promoting the Symfony local web server in the docs, so let's not explain this alternative. Thanks.
