### ISSUE TITLE
[Cache] Add argument $prefix to AdapterInterface::clear()

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11917]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32284
| PR author(s) | @nicolas-grekas
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because the related code PR says that:

> Since AdapterInterface is an "internal" interface (ie its purpose is to create compatible implementations - NOT to be type-hinted for), this is not really a user-facing change.
