### ISSUE TITLE
[Translation] deprecate passing a null locale

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11911]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32415
| PR author(s) | @Simperfit
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Closing because al the `new MessageCatalogue()` instances in the docs pass the locale as the first argument. There's no need to mention this internal detail because the deprecation message displayed by Symfony is crystal clear.
