### ISSUE TITLE
[MonologBridge] Monolog 2 compatibility

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11920]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#27905
| PR author(s) | @derrabus
| Merged in    | 5.0-dev

**Comment by derrabus** [comment]
I've peeked through some docs pages that mention Monolog, but I haven't found a piece that needs adjustments because of Monolog 2. I'd say, we're good here.

**Comment by xabbuh** [comment]
closing then, thanks for checking
