### ISSUE TITLE
Missing info on how to use RedisSessionHandler

### ISSUE THREAD

**Issue by gisostallenberg** [symfony/symfony-docs#11968]
Related issues only mention a broken link to the github repository. #10011 mentions a link to a how to. How about adding a page describing how to use RedisSessionHandler?

**Comment by javiereguiluz** [comment]
You are right! This info is missing. We're working on this on #12325, which is part of our ongoing efforts to improve all the docs related to databases (such as "sessions + databases"). I'm closing this one in favor of the mentioned pull request. Thanks.
