### ISSUE TITLE
Cache guide missing from navigation

### ISSUE THREAD

**Issue by codayblue** [symfony/symfony-docs#11970]
I found a cache document that I could not find in the navigation. The url structure matches the other guide pages so I assume it was meant to be in the guide popup (screen shot below). I pulled the repository and looked for a way to manage those links but it appears to not be something I can submit here. If I am mistaken I will happily submit a PR, I just need to know where the links are managed. Also if the link is not in the list on purpose please feel free to close this issue. 

Link that appears to be missing:
https://symfony.com/doc/current/cache.html

Screenshot:
![image](https://user-images.githubusercontent.com/7281660/61330910-8bfd0b80-a7d5-11e9-9b2c-24c9af6b5dc9.png)

**Comment by javiereguiluz** [comment]
@codayblue thanks for reporting this problem! "Cache" is going to be added to the list of guides very soon (after the next deploy). Thanks.
