### ISSUE TITLE
[Messenger] How to Create Your own Messenger Transport seems outdated

### ISSUE THREAD

**Issue by freiondrej** [symfony/symfony-docs#11972]
The code snippet 

```php
class YourTransport implements TransportInterface
{
    public function send(Envelope $envelope): Envelope
    {
        // ...
    }

    public function receive(callable $handler): void
    {
        // ...
    }

    public function stop(): void
    {
        // ...
    }
}
```

describes nonexistent methods receive() and stop(); the interface has methods get(), ack(), reject() and send() (as of symfony/messenger:4.3.2).

I want to confirm whether the docs page is outdated, if so, I can send a PR with the correct methods.

**Comment by freiondrej** [comment]
the link to the page: https://symfony.com/doc/current/messenger/custom-transport.html

**Comment by OskarStark** [comment]
Hi @freiondrej, thanks for reporting this issue. Can you please check my pull request here: https://github.com/symfony/symfony-docs/pull/12209

Thanks 🙏

**Comment by freiondrej** [comment]
Hi @OskarStark, thank you very much, that is exactly what I'd expect it to be.
