### ISSUE TITLE
[DI] Move non removing compiler passes to after removing passes

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11991]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32332
| PR author(s) | @alexpott
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Closing because I can't find in the docs any reference to the `CheckExceptionOnInvalidReferenceBehaviorPass` and `ResolveHotPathPass` passes that were modified in this change.
