### ISSUE TITLE
[Routing] Document ContainerLoader, ObjectLoader and routing.loader.service

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#12016]
We have an article called `routing/custom_route_loader.rst` but we don't mention these things. Should we do that?

See https://github.com/symfony/symfony/pull/32582

**Comment by fancyweb** [comment]
To be honest, I doubt anyone uses those classes / services except us 😀 Especially the `ObjectLoader` one. That's why I suggested to deprecate it in https://github.com/symfony/symfony/pull/32582.

**Comment by javiereguiluz** [comment]
OK, let's close this as "won't fix" then. Thank you.
