### ISSUE TITLE
Add docs for: [TwigBundle] Deprecating error templates for non-html f..

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony-docs#12015]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#31398
| PR author(s) | @yceruto

**Comment by OskarStark** [comment]
@Tobion please update gh-tool that the merged in branch is shown. Thanks 😊

**Comment by javiereguiluz** [comment]
Fixed by #12187.
