### ISSUE TITLE
[Mailer][DX][RFC] Rename mailer bridge transport classes

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12028]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32609
| PR author(s) | @Koc
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Closing as "fixed" because I can't find any reference to `Symfony\Component\Mailer\Bridge\*` and `Symfony\Component\Mailer\Transport\Http\*` classes in 4.4 branch docs.
