### ISSUE TITLE
No reference to the SubmitButtonTypeInterface

### ISSUE THREAD

**Issue by BenjaminBorlet** [symfony/symfony-docs#12027]
Hello,

First of all it's like my first real contribution to symfony :)

I struggled this afternoon to create a custom SubmitType, i finally found this [issue](https://github.com/symfony/symfony/issues/20528).

As you can read, this is not documented yet, even if this is pretty old, and maybe i could write a short cookbook example on this.

Hope I'm in the right place to ask that.
Thanks

**Comment by xabbuh** [comment]
Could you explain the use case you had that required it to create a custom `SubmitType`? I am just wondering because I have never seen a case where that was actually necessary and maybe we should find another solution and describe that instead.

**Comment by xontik** [comment]
(I started with wrong github account)
I use it because i have some sort of multiple validation,
My users can save an entity as draft, with not all fields matching finals constraints, thanks to validation groups.
I use custom SubmitType to render save as draft and publish button that do not trigger the same validation groups, but are the same in all my form, to not repeat myself is create SaveSubmitType and ValidateSubmitType
I also use FormEvent to hide the draft button when an entity is in "public state"

**Comment by javiereguiluz** [comment]
Can't this be solved by adding two normal SubmitType in the form? I don't understand the need to create a custom form type in this case.

**Comment by xontik** [comment]
it can ! But in each SubmitType i have to repeat some options. So, to  avoid repeating myself, i did that !


```
class SaveType extends AbstractType implements SubmitButtonTypeInterface
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'validation_groups' => ['Default', 'saving'],
            'attr' => ['class' => 'btn btn-danger']
        ]);
    }
}
```

```
class ValidateType extends AbstractType implements SubmitButtonTypeInterface
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'validation_groups' => ['Default', 'validating'],
            'attr' => ['class' => 'btn btn-danger']
        ]);
    }
}
```

and then I use them like that : 
```
class AdminType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder 
          ...
          ...
            ->add('save', SaveType::class)
            ->add('validate', ValidateType::class)
    }
}
```

**Comment by javiereguiluz** [comment]
I would have done this instead. Would that work for you?

```php
class AdminType extends AbstractType
{
    private $commentButtonOptions = [
        'attr' => ['class' => 'btn btn-danger'],
        'validation_groups' => ['Default', 'validating'],
    ];

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder 
            // ...
            ->add('save', SubmitType::class, $commonButtonOptions + [
                'label' => 'Save',
            ])
            ->add('validate', SubmitType::class, $commonButtonOptions + [
                'label' => 'Validate',
                '...' => '...',
            ])
        ;
    }
}
```

**Comment by xontik** [comment]
No because on some form I want to use only one of the two button.

**Comment by javiereguiluz** [comment]
@xontik you can solve that passing options to forms. Sadly there were no docs about that ... but we recently added that doc. See https://symfony.com/doc/current/forms.html#passing-options-to-forms

**Comment by xontik** [comment]
I did know that, and i didn't want to use this solution.

Anyway, I originally opened this issue to point out that something that migth be useful to some poeple was not in the doc :) I will not argue more about my specific case.

Thanks for your time

**Comment by xabbuh** [comment]
A custom form type extension might also be an option here. So you would add some kind of `button_type` option which allows to switch between a `save` and a `validate` button and all the other options would be set based on that option.

**Comment by javiereguiluz** [comment]
@xontik thanks for your patience!

After thinking about this, we've decided to close it because Symfony provides some built-in utilities to solve this, as shown in the above examples. However, if we receive more reports like this, we'll reconsider opening this. Thanks for understanding and thanks again for reporting this and for your patience!
