### ISSUE TITLE
--full option doesn't exist

### ISSUE THREAD

**Issue by cf-jvdijk** [symfony/symfony-docs#12103]
Hello,

I'm trying to setup a new installation with symfony 4, via this documentation: https://symfony.com/doc/current/setup.html

In there it says that this command should be run for a full installation:
`symfony new --full my_project`
But when I execute that on my local, it gives me a RuntimeException: `The "--full" option does not exist.`. I am not sure if I am doing something wrong, or if the documentation is not correct. Any help would be appreciated.

(It would also already help if the composer commands were displayed there as well, see https://symfony.com/download for example).

**Comment by xabbuh** [comment]
Did you download the `symfony` binary (see https://symfony.com/doc/current/setup/symfony_server.html) or could it be that  `symfony` points to the old Symfony installer?

**Comment by cf-jvdijk** [comment]
So I double checked, and the symfony installer was indeed pointing to the old version. Thanks!

**Comment by richard4339** [comment]
Perhaps a helpful addition to both the symfony_server page along with the setup page would be verbiage on how to tell which version of the Symfony command you have? I follow the Symfony blog and such, but didn't realize the installer had been replaced, and when I run symfony selfupdate it tells me it is up to date. It took me finding this issue to realize that this is probably my problem as well.
