### ISSUE TITLE
Add 5.0 to roadmap

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#12115]
Symfony 5.0 is actively being developed, which is why I thought it might be a good idea to add it to the roadmap chart. Right now, I can't find any trace of Symfony 5 on https://symfony.com/roadmap – Symfony 4.4 is the only dev version mentioned there.

![Bildschirmfoto 2019-08-07 um 17 40 37](https://user-images.githubusercontent.com/1506493/62636937-c2dcc200-b93a-11e9-942b-576b4ca8b6c8.png)

**Comment by javiereguiluz** [comment]
@derrabus nice idea! We've just made some changes to also show the `x.0` branch when the next branch is `x.4`. See https://symfony.com/roadmap

**Comment by derrabus** [comment]
Awesome, thank you. 😃
