### ISSUE TITLE
[HttpFoundation] deprecate HeaderBag::get() returning an array and add …

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12122]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32122
| PR author(s) | @Simperfit
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
I'm closing this as "no changes needed" because I can't find any docs referring to the behavior that it's now deprecated. All docs (components/http_foundation.rst, /controllers.rst and /create_framework/*.rst) rely on the default behavior that only returns the first of all possible headers.
