### ISSUE TITLE
Add --unpack option into composer require examples

### ISSUE THREAD

**Issue by Tetragramat** [symfony/symfony-docs#12130]
People unfamiliar with how packed packages work may find themselves in very uncomfortable situation when they find out that on `composer update` their project breaks apart due to wildcard requirements in packed packages.

By adding `--unpack` option into composer require examples people which copy paste code from docs will at least see in their `composer.json` that they have bunch of wildcard requirements that should be fixed instead of hiding them behind innocently looking packages.

**Comment by javiereguiluz** [comment]
@Tetragramat thanks for opening this issue. We've discussed about this in the Symfony Core Team and we prefer to keep installing the packs without the "unpack" option.

However, we realized that we didn't explain packs and the "unpack" option. So, we're doing that in #12354. Thanks!
