### ISSUE TITLE
StofDoctrineExtensions bundle seems to be not supported anymore

### ISSUE THREAD

**Issue by OlivierFromLille** [symfony/symfony-docs#12131]
Hello there.

It seems that StofDoctrineExtensions is not supported anymore: https://github.com/stof/StofDoctrineExtensionsBundle/issues/394

It should be great to not mention it in the following links for current sf version: https://symfony.com/doc/current/doctrine/common_extensions.html and https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html

I don't know which bundle can replace it. Maybe antishov's bundle: https://github.com/stof/StofDoctrineExtensionsBundle/issues/394#issuecomment-519241602

Thanks guys!

Olivier

**Comment by javiereguiluz** [comment]
@OlivierFromLille thanks for telling us about this. These days we're rewording Doctrine docs and we've also changing the Doctrine Extensions mention (see #12332). I've added a comment there to not forget about this until we figure out what to do. So, I'm closing this in favor of that pull request. Thanks.
