### ISSUE TITLE
[ErrorHandler] trigger deprecation in DebugClassLoader when child class misses a return type

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12161]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#30323
| PR author(s) | @fancyweb, @nicolas-grekas
| Merged in    | 4.4

**Comment by OskarStark** [comment]
@yceruto could you please have a look here and verify if there is sth to be documented? Thanks.

**Comment by nicolas-grekas** [comment]
@fancyweb maybe

**Comment by javiereguiluz** [comment]
I'v checked the code of the pull request and I don't see any way to enable or configure this, so it looks like a built-in feature of the debugging class loader which shows deprecation messages like *"Method "%s::%s()" will return "%s" as of its next major version. Doing the same in child class "%s" will be required when upgrading."*. I don't think we need to document this, so let's close it. Thanks.

**Comment by nicolas-grekas** [comment]
The deprecation notice is going to be removed from 4.4 and added back in 5.1.
Then, people will have to update their code, and all this is going to have to be documented.

**Comment by javiereguiluz** [comment]
A note about this ... do we have some numbers about the performance impact of adding these features to the DebugClassLoader? Could it be noticeable in non-trivial apps? Thanks.

**Comment by nicolas-grekas** [comment]
It doesn't add anything special on top of the existing checks in DebugClassLoader, so I don't expect any big differences. But no, we don't have numbers.
