### ISSUE TITLE
[Mailer] Remove the auth mode DSN option and support in the eSMTP trans…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12203]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33237
| PR author(s) | @fabpot
| Merged in    | 4.4

**Comment by OskarStark** [comment]
The only occurrences I can find in the 4.4 docs are related to Swiftmailer. But these should be kept I guess.

**Comment by fabpot** [comment]
Indeed, it was not yet documented.
