### ISSUE TITLE
Incorrect version and warning

### ISSUE THREAD

**Issue by gisostallenberg** [symfony/symfony-docs#12205]
When opening the 4.4 docs from 4.3 it actually opens 5 and displays a notice on not being maintained anymore. See
![image](https://user-images.githubusercontent.com/11526270/63324807-21d20c00-c329-11e9-92a7-51742ddc47e1.png)

Also for example https://symfony.com/doc/current/components/browser_kit.html and https://symfony.com/doc/master/components/browser_kit.html

**Comment by OskarStark** [comment]
You are right, 5.0 isn't mentioned here:
![Screenshot 2019-08-20 09 13 41](https://user-images.githubusercontent.com/995707/63325631-d6206200-c32a-11e9-8e9a-7bf829734153.png)

**Comment by wouterj** [comment]
This was a bug with the version checking system. It has been fixed
