### ISSUE TITLE
[Translation] deprecate support for null locales

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12219]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33272
| PR author(s) | @xabbuh
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
@xabbuh I've been looking in the docs and I can't find anything we should update ... except this in the `twig_reference.rst` article:

```twig
{{ message|transchoice(count, arguments = [], domain = null, locale = null) }}

[...]

``locale`` *(optional)*
    **type**: ``string`` **default**: ``null``
```

Should we update this or the default value here is still `null`? Thanks.

**Comment by xabbuh** [comment]
It's all fine here. We didn't deprecate the ability here as the whole `transchoice` part was already deprecated before.
