### ISSUE TITLE
cache.adapter.array is not available on Symfony 3.4

### ISSUE THREAD

**Issue by vroad** [symfony/symfony-docs#12222]
In [Cache \(Symfony 3\.4 Docs\)](https://symfony.com/doc/3.4/cache.html#configuring-cache-with-frameworkbundle), `cache.adapter.array` is listed as a valid service, but it doesn't actually work, because it's not exposed as a service.

https://github.com/symfony/framework-bundle/blob/v3.4.30/Resources/config/cache.xml
https://github.com/symfony/framework-bundle/blob/v4.3.3/Resources/config/cache.xml#L136-L143

Isn't this service introduced from Symfony 4.1? I can't find service definition in Symfony 4.0 and 3.4.

**Comment by javiereguiluz** [comment]
@vroad thanks for reporting this issue!
@nicolas-grekas do you remember if this is expected ... or if we missed adding the array adapter in 3.4? Thanks!

**Comment by nicolas-grekas** [comment]
That's been added later yes.
