### ISSUE TITLE
[HttpKernel] deprecate global dir to load resources from

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12220]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33258
| PR author(s) | @Tobion
| Merged in    | 4.4

**Comment by Tobion** [comment]
Closing as the deprecated global dir has not been documented anywhere. https://symfony.com/doc/current/bundles/override.html does not mention it either.

**Comment by Tobion** [comment]
I can't close :(
