### ISSUE TITLE
[ErrorHandler] make DebugClassLoader able to add return type declaratio…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12239]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33283
| PR author(s) | @nicolas-grekas
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
@nicolas-grekas could you please confirm that this is a feature intended for any developer and not an internal Symfony thing?

If this is a feature for everybody, can you confirm that adding for example the `SYMFONY_PATCH_TYPE_DECLARATIONS=force=1` env var will modify all the classes of my project to add PHP 7 types to clasS/method/function parameters?

Thanks!

**Comment by javiereguiluz** [comment]
Let's close as "won't fix" for now.
