### ISSUE TITLE
[Messenger] Document "own Receiver"

### ISSUE THREAD

**Issue by xfifix** [symfony/symfony-docs#12230]
it's possible someone explain "own receiver" with a case.
The doc just show  the class who implement ReceiverInterface and not how to use it...
thank a lot

**Comment by xfifix** [comment]
@Nyholm 🙏

**Comment by Nyholm** [comment]
Thank you for the ping. 

Sure, I can write up something. @xfifix could you help me review the PR and ask 1000 questions about things that are not clear and needs to be explained better?

**Comment by xfifix** [comment]
@Nyholm  I understand that you don't have the time.

**Comment by Nyholm** [comment]
Im saying that Im happy to do it. But I need help reviewing it and I asked if you could help me review it later?

**Comment by Nyholm** [comment]
@xfifix Could you please review: #12340

**Comment by xfifix** [comment]
@Nyholm Thank you for taking the time for this PR.
