### ISSUE TITLE
Missing security.form_login.logout reference in documentation

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony-docs#12243]
There's no doc about logout (which means users don't know it's possible to customize logout route! And other options ofc).

Or maybe I'm blind.

- https://symfony.com/doc/current/security/form_login.html
- https://symfony.com/doc/current/reference/configuration/security.html

For those asking about, it's available here: https://github.com/symfony/symfony/blob/545d38a037098f0f21b11b380912151488acfac7/src/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php#L206

**Comment by xabbuh** [comment]
I guess we may have made a mistake when rearranging security related docs. On https://symfony.com/doc/current/reference/configuration/security.html#firewalls there is a sentence reading "Options Related to Logout Configuration". I think this paragraph was meant to serve as a headline for the logout related option (`path` and `target` are missing though).

**Comment by abdounikarim** [comment]
Hey guys, 

I'm not sure but there's on the doc something about the logout here : 
https://symfony.com/doc/current/security.html#logging-out

Is it what you're searching ? 

Cheers 😉

**Comment by HeahDude** [comment]
Closing here as the logout section is indeed present in the main security article as stated by @abdounikarim. From 3.4 to master. Thanks!

**Comment by HeahDude** [comment]
But we could still document its options in the reference section... reopening.

**Comment by hacfi** [comment]
The configuration options https://symfony.com/doc/5.2/reference/configuration/security.html miss `target`, `handler` and `delete_cookie`. If I find some time I will create a PR. Do I create the PR against `master`?

**Comment by Nek-** [comment]
@hacfi always welcome

**Comment by javiereguiluz** [comment]
Closing in favor of #15908, a meta-issue that groups all pending security-related issues so we can easily check them.
