### ISSUE TITLE
Added new ErrorController + Preview and enabling there the error render…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12273]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33271
| PR author(s) | @yceruto
| Merged in    | 4.4

**Comment by yceruto** [comment]
Note: add a section about functional tests that mentions the before/after behavior around testing exceptions.

**Comment by javiereguiluz** [comment]
@yceruto I'm working on this and I'm having lots of problems trying to understand the changes needed in this page: https://symfony.com/doc/current/controller/error_pages.html

Before, things worked like this:

1. Customize the visible error pages of your site: use Twig template overriding.
2. View in `dev` how errors look in `prod`: use `/_error/{code}.{format}`
3. Run custom logic on exceptions: listen to kernel.exception event.
4. Do advanced stuff with the dev exceptions: use twig.exception_controller to override the default controller.

Now, how do we do those things?

1. I don't know. The "templates" are hardcoded in the error renderers.
2. It looks like the URL changed to `/{code}.{format}`. If this is right, isn't it confusing to not add some prefix like `/_error/` in the URL?
3. Same as before.
4. I don't know. Not possible anymore? The `framework.error_controller` value is not really used in the default `ErrorController`, right? (It's only used in the preview() action)

Thanks!

**Comment by yceruto** [comment]
> 1. Customize the visible error pages of your site: use Twig template overriding.

> 1. I don't know. The "templates" are hardcoded in the error renderers.

If TwigBundle is enabled, same as before, you can create the error pages in:
 * `templates/bundles/TwigBundle/Exception/error.html.twig`
 * or `templates/bundles/TwigBundle/Exception/error404.html.twig`

The difference is that now you can't create non-HTML error pages like `error.json.twig`, so you must define your own `JsonErrorRenderer` instead.

> 2. View in dev how errors look in prod: use /_error/{code}.{format}

> 2. It looks like the URL changed to /{code}.{format}. If this is right, isn't it confusing to not add some prefix like /_error/ in the URL?

As before, the path prefix is defined when we import the routing config, see recipe changes https://github.com/symfony/recipes/pull/645

> 3. Run custom logic on exceptions: listen to kernel.exception event.

> 3. Same as before. No changes in this feature.

No changes.

> 4. Do advanced stuff with the dev exceptions: use `twig.exception_controller` to override the default controller.

> 4. I don't know. Not possible anymore? The framework.error_controller value is not really used in the default ErrorController, right? (It's only used in the preview() action)

Yes, it's possible as before, the `framework.error_controller` config can be used if TwigBundle is not installed or if `twig.exception_controller` is set to `null` explicitly. The new one (framework.error_controller) has the same mean. By default the `ErrorController` is used for both actions: Rendering the error response and Preview the error response in non-debug mode.

**Comment by yceruto** [comment]
> 2. View in dev how errors look in prod: use /_error/{code}.{format}

> 2. It looks like the URL changed to /{code}.{format}. If this is right, isn't it confusing to not add some prefix like /_error/ in the URL?

As of now, the prefix has double undercore: `__error/`. That was needed to avoid conflic with the same config in `routes/dev/twig.yaml`

**Comment by dbrekelmans** [comment]
I ran into this while upgrading to symfony 5.0. Since the docs haven't been updated yet, it left me very confused until I found this issue. I shall try to open a PR this sunday to hopefully help others who run into the same issue :)

**Comment by yceruto** [comment]
Hello @dbrekelmans, my previous comment is outdated.  

I'm sorry, I don't have time to write/fix the documentation, but I can review any PR about it.

**Note:** There is no such a component `ErrorRenderer` nor the `JsonErrorRenderer` service. Now all these features are handled by the new `ErrorHandler` component. The customization of the Twig-based HTML error pages work as before by installing the `TwigBundle` and the `serializer` component (if installed/enabled) will be used for non-HTML error responses.

**Comment by dbrekelmans** [comment]
Hi @yceruto,

This was more work than I expected, but I managed to do most of it.
The only thing I'm struggling with is the `Overriding the Default ErrorController` paragraph in `controller/error_pages.rst`.

Would you mind if I open a PR with the changes I have so far?
Maybe someone else can jump in and finish the last section.

https://github.com/dbrekelmans/symfony-docs/compare/4.4...dbrekelmans:fix_12273

**Comment by yceruto** [comment]
Yes, please, submit the changes to this repo, so we can review it, thanks!
