### ISSUE TITLE
PDOSessionHandler supports URL-based DSNs but this is undocumented

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#12324]
The documentation at https://symfony.com/doc/current/doctrine/pdo_session_storage.html only shows a PDO DSN as configuration.
But In Symfony 3.4.5+ and 4.0.5+, PDOSessionHandler also supports URLs (that was merged as a bugfix, as DbalSessionHandler was deprecated in 3.4 but one of its use case was supporting URLs). The documentation should show it.

Refs https://github.com/symfony/symfony/issues/33589

**Comment by javiereguiluz** [comment]
I'm rewording the docs about sessions + database ... si I'll take care of this. Thank you.

**Comment by javiereguiluz** [comment]
Closing as fixed by #12325, which uses DSN by default in the config examples for consistency with the rest of docs.
