### ISSUE TITLE
Security Bundle doesn't actualize the role without LogOut/In

### ISSUE THREAD

**Issue by CorvinAlex** [symfony/symfony-docs#12331]
Hey I'm using the symfony security bundle with the role and I can't update my users until they disconnect and reconnect.
(I update an array of role inside them but it doesn't change the return of the is_granted function even if it might)
At the moment I handle the problem by disconnecting them if I see that their roles changed but I would like to just call a function which refresh their role.
Does anyone know something like that or how symfony security bundle set in to reset it :D 

Thanks

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
