### ISSUE TITLE
[FrameworkBundle] Cleanup

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12342]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33635
| PR author(s) | @yceruto
| Merged in    | 5.0-dev

**Comment by javiereguiluz** [comment]
Closing because in 4.3 we deprecated the article about PHP templates (https://symfony.com/doc/current/templating/PHP.html) and in 5.0-dev we've removed it (https://symfony.com/doc/master/templating/PHP.html).
