### ISSUE TITLE
certification symfony versions outdated on main page

### ISSUE THREAD

**Issue by greg606** [symfony/symfony-docs#12343]
https://symfony.com/doc/current/index.html#gsc.tab=0
<img width="330" alt="Screenshot 2019-09-19 12 06 49" src="https://user-images.githubusercontent.com/166559/65235223-7c9c8600-dad6-11e9-8755-37c39d5c5bd7.png">

**Comment by javiereguiluz** [comment]
@greg606 good catch! We've fixed this and will be updated publicly soon after the next deploy. Thanks!
