### ISSUE TITLE
In InteractiveSecurityHelper.php line 120

### ISSUE THREAD

**Issue by izitech89** [symfony/symfony-docs#12350]
php bin/console make:registration-form

` In InteractiveSecurityHelper.php line 120:                           
  [ErrorException]                   
  Notice: Undefined index: property                                
Exception trace:
  at /home/vagrant/code/proprios/vendor/symfony/maker-bundle/src/Security/InteractiveSecurityHelper.php:120
 Symfony\Bundle\MakerBundle\Security\InteractiveSecurityHelper->guessUserNameField() at /home/vagrant/code/proprios/vendor/symfony/maker-bundle/src/Maker/MakeRegistrationForm.php:108
 Symfony\Bundle\MakerBundle\Maker\MakeRegistrationForm->interact() at /home/vagrant/code/proprios/vendor/symfony/maker-bundle/src/Command/MakerCommand.php:99
 Symfony\Bundle\MakerBundle\Command\MakerCommand->interact() at /home/vagrant/code/proprios/vendor/symfony/console/Command/Command.php:240
 Symfony\Component\Console\Command\Command->run() at /home/vagrant/code/proprios/vendor/symfony/console/Application.php:933
 Symfony\Component\Console\Application->doRunCommand() at /home/vagrant/code/proprios/vendor/symfony/framework-bundle/Console/Application.php:87
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/vagrant/code/proprios/vendor/symfony/console/Application.php:272
 Symfony\Component\Console\Application->doRun() at /home/vagrant/code/proprios/vendor/symfony/framework-bundle/Console/Application.php:73
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/vagrant/code/proprios/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /home/vagrant/code/proprios/bin/console:42`

Solution : 

Line 120 : return $entityProvider['entity']['property'];
replace by 
Line 120 : return $entityProvider['entity']['class'];

**Comment by ymc-sise** [comment]
This seems to be a bug in the maker bundle. Could you please report it here and add a description how to reproduce it. https://github.com/symfony/maker-bundle/issues
