### ISSUE TITLE
[Security] Deprecate isGranted()/decide() on more than one attribute

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12363]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33584
| PR author(s) | @wouterj
| Merged in    | 4.4

**Comment by xabbuh** [comment]
looks like we do not mention this anywhere

**Comment by javiereguiluz** [comment]
Does this affect to `roles` in `access_control`? Because yesterday we merged some changes adding an example with multiple roles (see https://symfony.com/doc/current/security/access_control.html#matching-options)

**Comment by xabbuh** [comment]
indeed, we need to think about that example
