### ISSUE TITLE
[Security] add "anonymous: lazy" mode to firewalls

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#12390]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33676
| PR author(s) | @nicolas-grekas
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Fixed in #13155.

**Comment by wouterj** [comment]
I disagree with closing this as fixed, as the feature itself is not documented yet. Furthermore, I think we should also add the new `AbstractListener` with the `support()` method logic, in case someone implemented a custom authentication provider/listener.

**Comment by chalasr** [comment]
@javiereguiluz We have number of support issues about what `anonymous: lazy` means, I would expect the fix to give an explanation about it

**Comment by javiereguiluz** [comment]
You are right. I'm sorry I closed this one too quickly.

**Comment by HeahDude** [comment]
I've opened #13171, let me know if we need to be more exhaustive or other places it should be mentioned. Thanks
