### ISSUE TITLE
[Serializer] Deprecate the XmlEncoder::TYPE_CASE_ATTRIBUTES constant

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12401]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33789
| PR author(s) | @pierredup
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Closing because I can't find any occurrence of `TYPE_CASE_ATTRIBUTES` in the 4.4 branch of the docs, so we cannot deprecate it.
