### ISSUE TITLE
Question: How to start server without symfony binary?

### ISSUE THREAD

**Issue by stefanos82** [symfony/symfony-docs#12417]
I'm currently learning Symfony and in [Installing & Setting up the Symfony framework](https://symfony.com/doc/current/setup.html) we have the following example:

![image](https://user-images.githubusercontent.com/1777466/66202563-c11b4a80-e6ae-11e9-8a5b-345af5a97872.png)

But as you continue reading, there is not a single line that demonstrates how to start the server to test whether everything works as expected or not.

Do I have to manually install `web-server-bundle` to be able to run web server?

Isn't there any other default way that comes with the aforementioned example in screenshot?

Please advice.

Thank you.

**Comment by Taminoful** [comment]
Hey @stefanos82,

the Symfony CLI is the recommended way to use a webserver as development server.
If you have created your Symfony project with the `website-skeleton` template you can run the alternate development server with `php bin/console server:run` from a CLI in your project folder.
If you chose `skeleton` you'd need to require the web-server-bundle as dev dependency with `composer req web-server-bundle --dev` and then execute the command above.

**Comment by stefanos82** [comment]
Ah I see; I went with the plain `skeleton` version.

That's good to know.

Thank you @Taminoful :+1:
