### ISSUE TITLE
404 links in Normalizer docs

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony-docs#12437]
https://symfony.com/doc/current/serializer/normalizers.html

> Normalizers turn objects into arrays and vice versa. They implement NormalizerInterface for normalizing (object to array) and DenormalizerInterface for denormalizing (array to object).

Both interface links are currently broken, resulting in 404 errors.

**Comment by tony-tran** [comment]
Same for me, can you please provide a fix ? Or if you want I can the fix

**Comment by dkarlovi** [comment]
Please do if you have the time, I'm not really up to speed with the docs repo. Thanks.
