### ISSUE TITLE
Notifier Component

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12430]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33687
| PR author(s) | @fabpot
| Merged in    | 5.0-dev

**Comment by andreybolonin** [comment]
@nicolas-grekas no news where `Notifier Component` is documented?

**Comment by wouterj** [comment]
Documenting things, just as code features, is a community effort. Feel free to help contributing things to get them documented :smile: 

On slack, @TheGarious volunteered to work on this one today.
