### ISSUE TITLE
[Cache] document RedisTagAwareAdapter and FilesystemTagAwareAdapter

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12446]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33461
| PR author(s) | @andrerom
| Merged in    | 4.4

**Comment by andrerom** [comment]
Given experimental flag [has been removed](https://github.com/symfony/symfony/commit/191cb52902bdcf2843c34c7009505432d000c2a4#diff-410efc18de675a67676caaf96a22be12) we should cover both `FilesystemTagAwareAdapter` and `RedisTagAwareAdapter`.

Feature PR where both were introduced: https://github.com/symfony/symfony/pull/30370

@nicolas-grekas ok to rename issue?

---

Should cover these in at least `components/cache/cache_invalidation.rst`.
Anywhere else we should cover them?

**Comment by nicolas-grekas** [comment]
friendly ping @andrerom :)

**Comment by andrerom** [comment]
> Should cover this/these in at least components/cache/cache_invalidation.rst.
> Anywhere else we should cover it?

friendly reminder that question is mainly for you and doc team @nicolas-grekas ;)

**Comment by nicolas-grekas** [comment]
> Should cover this/these in at least components/cache/cache_invalidation.rst.

let's start with this page yes :)
