### ISSUE TITLE
"Routes with optional parameters at the end will not match on requests with a trailing slash" isn't true

### ISSUE THREAD

**Issue by Ahmed-Ayman** [symfony/symfony-docs#12444]
[here](https://symfony.com/doc/current/routing.html#optional-parameters)

a note is saying `Routes with optional parameters at the end will not match on requests with a trailing slash (i.e. /blog/ will not match, /blog will match).`

now I have created an optional `@Route("/blog/{page<\d+>}")` and tried /blog/ on chrome and it matched the route that I have already set to a default ` int $page = 0 `

**Comment by thbil** [comment]
Hi,
It seems you are correct !
According to https://github.com/symfony/symfony/pull/26283 this note is no longer relevant since v4.1.0-BETA1.
I'll edit the doc this afternoon (at least I'll try to do my first PR).

Cheers.
