### ISSUE TITLE
Error in variable name : Routings

### ISSUE THREAD

**Issue by Skraye** [symfony/symfony-docs#12455]
That's a very little thing, but i found a little error at:
[https://symfony.com/doc/current/routing.html#route-groups-and-prefixes](url)

In the annotation of the class, we put a requirement on "locale", but then above functions, "_locale" is used.

**Comment by wouterj** [comment]
Thanks for reporting this bug @Skraye! Another user submitted a fix that we merged a couple days ago: #12460 

If you find another bug in the future, please note that you can also submit the fix yourself by using the blue "edit this page" button at the top right of every page. This way, we can credit your for the report and fix!
