### ISSUE TITLE
Inconsistency in the convention doc

### ISSUE THREAD

**Issue by T1l3** [symfony/symfony-docs#12457]
Hi,

In https://github.com/symfony/symfony-docs/blob/3.4/contributing/code/conventions.rst

It says:

> When deprecating a whole class the trigger_error() call should be placed between the namespace and the use declarations, like in this example from ServiceRouterLoader:

And the example show the trigger_error after the use declarations:

```php
namespace Symfony\Component\Routing\Loader\DependencyInjection;

use Symfony\Component\Routing\Loader\ContainerLoader;

@trigger_error(sprintf('The "%s" class is deprecated since Symfony 4.4, use "%s" instead.', ServiceRouterLoader::class, ContainerLoader::class), E_USER_DEPRECATED);
```

What is the right way?

Btw what if I have some TriggerErrorUtils class and use it like that:

```php
@trigger_error(
    \FQCN\Utils\TriggerErrorUtils::getClassDeprecatedMessage(
        OldDummy::class,
        '1.0',
        '2.0',
        Dummy::class
    ),
    E_USER_DEPRECATED
);
```
With the trigger_error before the use declarations i'm forced to use the FQCN?

edited: TriggerErrorUtils use case

**Comment by javiereguiluz** [comment]
@T1l3 good catch!

@nicolas-grekas could you please tell us which is the recommended way? Thanks!

**Comment by nicolas-grekas** [comment]
We try to put it as high in the file as possible. Not all messages have a reference to a use statement. Please check the source code if you want further insights.

Note that the call must be on a single line (unlike in the description above.)

**Comment by javiereguiluz** [comment]
Let's close this because of what Nicolas said. Thanks @T1l3 for your proposal, even if this time it didn't make it.
