### ISSUE TITLE
[Mailer] Using Let's Encrypt certs to sign messages

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#12459]
In https://symfony.com/doc/4.4/mailer.html#signing-and-encrypting-messages we say that:

![image](https://user-images.githubusercontent.com/73419/66580772-3a1f1400-eb7f-11e9-8d4e-9265361628ed.png)

But according to this comment: https://symfony.com/blog/new-in-symfony-4-4-signing-and-encrypting-email-messages#comment-23489

> Email encryption and code signing require a different type of certificate that Let’s Encrypt does not issue.

Can someone check this? Thanks!

**Comment by patrick-mota** [comment]
Indeed isn't the same thing.
I think let's encrypt is only used to validate your domain name and encrypt SSL/TLS, so the transport side.
S/MIME is the message side so isn't related with securing the transmission channel but identifying that an email really belongs to the person using it and the message is secure (encrypted).

I think cacert gives these kind of certificates but they just verify the domain so I don't think it's really safe to use it.

As far as I know you have to pay to get a real good S/MIME certificate provider.

For local only you could probably use a certificate generate by yourself via certbot or something.
