### ISSUE TITLE
[Security] Redirecting after failure inaccurate?

### ISSUE THREAD

**Issue by DonCallisto** [symfony/symfony-docs#12524]
Looking at https://symfony.com/doc/current/security/form_login.html#redirecting-after-failure I've notice that using `path` to generate the route will return *also* the front controller in it.
This can cause the redirect to have a "double" front controller in it (tested in my project).
Shouldn't this changed to `url` in order to obtain an absoluto url along with schema, authority, and so on?
WDYT?

If that's really an issue I'm willing to open a PR to correct the docs, just le me know.

**Comment by javiereguiluz** [comment]
@DonCallisto have you tried the code shown on the docs and it gave you a different result? Because `failure_path` should not generate a double controller.

**Comment by DonCallisto** [comment]
I'm pretty sure that I used the example and then reported the issue.
I should try again and check if I've missed/misinterpreted something or if something strange happen in my code.
I'll try to return to you ASAP.

**Comment by javiereguiluz** [comment]
We're closing this because we haven't receive more reports like this. Maybe it was a temporary issue? As always, we can reopen this if we have a way to reproduce the error. Thanks!
