### ISSUE TITLE
[HttpClient] Document when exceptions are trigger on invalid response

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony-docs#12522]
This is a follow-up of https://github.com/symfony/symfony/issues/34046

Some HTTP requests (which? I would assume POST/PUT/PATCH/DELETE?) have their response status code validated. If the status code is not 2XX, then an exception is automatically thrown by the client in the `$client->request()` call.

@nicolas-grekas do you know which HTTP requests trigger validation?

**Comment by nicolas-grekas** [comment]
All of them: the verb is not considered when doing the check.

The logic is: if you didn't do anything with the response (ie you didn't call any of its methods but getInfo), the constructor will check the status code and throw on 3/4/5xx.

**Comment by stof** [comment]
also not that it is not the `$client->request()` throwing the exception, but the destructor of the response. Wrapping the `$client->request()` call in a try/catch will very likely *not* let you catch the exception.

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" because the current docs (https://symfony.com/doc/current/components/http_client.html#handling-exceptions) don't mention any exception of this behavior based on the HTTP verb, so I'm assuming that the docs are correct. Thanks!

**Comment by ThomasLandauer** [comment]
@nicolas-grekas What do you mean by "if you didn't do anything with the response"? When I do `$response->getHeaders()`, I'm getting an exception too.

I think this passage at https://symfony.com/doc/4.4/http_client.html#handling-exceptions is not very clear:

> When the HTTP status code of the response is in the 300-599 range (i.e. 3xx, 4xx or 5xx) your code is expected to handle it. If you don’t do that, the getHeaders() and getContent() methods throw an appropriate exception,

From what I see, I'm *always* getting an exception; except when I pass `false`, e.g. `$response->getHeaders(false)`. So what exactly do you mean by "your code is expected to handle it"? How am I supposed to handle it?

**Comment by nicolas-grekas** [comment]
This sentence is about the status code, not the headers.
Handling it means reading it by calling `getStatusCode()` (then doing whathever sensible with the return value)
