### ISSUE TITLE
[ExpressionLanguage][Lexer] Exponential format for number

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12537]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34028
| PR author(s) | @tigr1991
| Merged in    | 4.4

**Comment by wouterj** [comment]
This can be added to https://symfony.com/doc/current/components/expression_language/syntax.html#supported-literals

**Comment by MrYamous** [comment]
Hello, i'm working on it

**Comment by OskarStark** [comment]
Closed via #12711
