### ISSUE TITLE
[FrameworkBundle] Remove suffix convention when using env vars to overr…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12551]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34131
| PR author(s) | @nicolas-grekas
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Closing as "fixed" because we haven't documented the "secrets" feature yet, so we don't have to update the docs about it.
