### ISSUE TITLE
Re-allow to use "tagged" in service definitions

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12562]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34170
| PR author(s) | @dunglas
| Merged in    | 4.4

**Comment by wouterj** [comment]
I saw at least one deprecation notice in `service_container/tags.rst`  that needs to be removed.

**Comment by alexandrunastase** [comment]
I will start working on this.
