### ISSUE TITLE
[Lock][Cache] Allows URL DSN in PDO adapters

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12560]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34057
| PR author(s) | @jderusse
| Merged in    | 4.4

**Comment by jderusse** [comment]
Looks like this is already documented
- cache https://symfony.com/doc/current/components/cache/adapters/pdo_doctrine_dbal_adapter.html
- lock https://symfony.com/doc/current/components/lock.html#pdostore
