### ISSUE TITLE
Deploy notifications when docs are updated

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony-docs#12565]
I recently spoke to a few developers that do mentoring/training where they sometimes refer to different pages in the documentation. I do the same thing when I give workshops. 

We discussed that it may be a good idea to subscribe to notifications when the docs are updated. Im not sure how the current release process look like or what is possible with reasonable effort. Here are some ideas: 
- I could be an automated change log. 
- It could be that we tag a release before every update
- It could be a tweet from a new twitter account with the URLs that are updated. 

Feel free to close if you feel this is tonnes of work with too little win.

**Comment by OskarStark** [comment]
Or an option by guthib where you could watch all merged pull requests of a repo

**Comment by javiereguiluz** [comment]
Thanks Tobias for this proposal. We've been discussing about this during the #SymfonyHackday and we decided that, even if we'd love to have this, it's not easily doable at all and we need to focus our resources on other topics. I'm sorry but I hope one day we could do something like this. Thanks!
