### ISSUE TITLE
Broken link to Webpack Encore Component

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-docs#12585]
In the left sidebar when clicking on "Components" -> "Webpack Encore" - it leads to https://symfony.com/doc/current/components/frontend.html that shows 404. I suppose it should refer to https://symfony.com/doc/current/frontend.html instead

**Comment by javiereguiluz** [comment]
I'm sorry it took me so long to fix this. We're finally fixing it thanks to https://github.com/symfony/marketing/pull/509 and other changes we're making in symfony.com. That's why I'm closing this as fixed, although it will take up to some days to be truly fixed in production. Thanks!

**Comment by bocharsky-bw** [comment]
Thank you for taking care of it 👍
