### ISSUE TITLE
Potential flaw in Legacy Migration/Legacy Bridge example

### ISSUE THREAD

**Issue by dlancea** [symfony/symfony-docs#12592]
I'm trying to follow the [Migration documentation using a Legacy Bridge](https://symfony.com/doc/current/migration.html#front-controller-with-legacy-bridge) but I'm having an issue.

The code seems to imply that you are able to check the Response object's isNotFound function in the LegacyBridge class, however my code isn't getting to that point since an NotFoundHttpException exception is thrown at `$kernel->handle($request);` (line 36 in the example index.php) if the route isn't found.

There's a chance I'm missing something, but it doesn't seem like this example works. I'm testing this using a skeleton Symfony 4.3 install. Maybe this only works in a full Symfony install, or doesn't work in the current version?

**Comment by dbrumann** [comment]
I would expect the `kernel.exception` event to kick in and convert the exception into a response for you. Did you set up your project using `composer create-project symfony/skeleton`? I will have a look at it when I get the chance, but any additional info on custumizations you made would be helpful to narrow it down.

**Comment by dlancea** [comment]
Actually, this seems to have been caused by an old .htaccess file from the legacy application. After clearing out some legacy cruft the legacy bridge is now working. Sorry for the confusion.
