### ISSUE TITLE
Twig: Lazy loaded extensions example does not work in twig<1.35

### ISSUE THREAD

**Issue by mhujer** [symfony/symfony-docs#12597]
[Documentation](https://symfony.com/doc/current/templating/twig_extension.html#creating-lazy-loaded-twig-extensions) states:

> New in version 1.26: Support for lazy-loaded extensions was introduced in Twig 1.26.

However the interface `Twig\Extension\RuntimeExtensionInterface` which is included in the example is not available until Twig 1.35 (https://github.com/twigphp/Twig/commit/6f08f5745c2aa417b470d9ff5309d1737fc71265)

**Comment by javiereguiluz** [comment]
@mhujer great catch! Thanks a lot for reporting this bug. We're fixing it in #12766.
