### ISSUE TITLE
Deprecate things that prevent \Throwable from bubbling down

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12593]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33065
| PR author(s) | @fancyweb
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Closing because I can't find any occurrence of `renderException()` from `src/Symfony/Component/Console/Application.php` in 4.4 branch.
