### ISSUE TITLE
[Messenger] use events consistently in worker

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12594]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34217
| PR author(s) | @Tobion
| Merged in    | 4.4

**Comment by Tobion** [comment]
There is https://github.com/symfony/symfony-docs/pull/12586 already for this.

**Comment by wouterj** [comment]
Fixed by https://github.com/symfony/symfony-docs/pull/12586
