### ISSUE TITLE
[DI][FrameworkBundle] add EnvVarLoaderInterface - remove SecretEnvVarPr…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12608]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34295
| PR author(s) | @nicolas-grekas
| Merged in    | 4.4

**Comment by javiereguiluz** [comment]
Closing as fixed because in the docs about secrets we don't mention the `secret:` env var processor which was removed.
