### ISSUE TITLE
[Bundles] DoctrineFixturesBundle is missing ODM related information

### ISSUE THREAD

**Issue by tarlepp** [symfony/symfony-docs#12602]
See this issue https://github.com/doctrine/DoctrineMongoDBBundle/issues/600

**Comment by alcaeus** [comment]
I'm not sure if DoctrineFixturesBundle should contain any ODM related documentation: while the name suggests that it takes care of fixtures for more projects, it only handles fixtures for ORM. ODM fixture functionality is completely contained in DoctrineMongoDBBundle.

**Comment by tarlepp** [comment]
hmm, true but there isn't really documentation for ODM fixtures under `Bundles related to Doctrine project` https://symfony.com/doc/bundles/ so maybe we need to to change that part to cover ODM related stuff too?

**Comment by tarlepp** [comment]
> I'm not sure if DoctrineFixturesBundle should contain any ODM related documentation: while the name suggests that it takes care of fixtures for more projects, it only handles fixtures for ORM. ODM fixture functionality is completely contained in DoctrineMongoDBBundle.

And for that I think that it would be more clearer to users if that `DoctrineFixturesBundle` documentation says that this bundle is for Doctrine ORM and not for ODM.

**Comment by javiereguiluz** [comment]
> ODM fixture functionality is completely contained in DoctrineMongoDBBundle.

@alcaeus what do you think about doing the same with DoctrineBundle and ORM fixtures?

**Comment by alcaeus** [comment]
It's on my list of things - I wanted to start making some plans to treat ORM and ODM the same. The idea is to either move common functionality to DoctrineBridge and have an ORMFixturesBundle and ODMFixturesBundle (to avoid optional dependencies in the respective mapper bundles), or have a generic bundle and provide extra packages for mapper-specific glue code. It's on the table, but time is a severe constraint at the moment.

**Comment by javiereguiluz** [comment]
Closing in favor of https://github.com/doctrine/DoctrineFixturesBundle/pull/321

**Comment by LorensoD** [comment]
@tarlepp, did you find a way to get fixtures working using the DoctrineMongoDBBundle? Or is there any other way of writing fixtures for MongoDB which you could recommend?

**Comment by tarlepp** [comment]
> @tarlepp, did you find a way to get fixtures working using the DoctrineMongoDBBundle? Or is there any other way of writing fixtures for MongoDB which you could recommend?

Nope, that `doctrine/DoctrineFixturesBundle` is not for ODM, I'm not sure if there is separated package for ODM.

**Comment by alcaeus** [comment]
> > @tarlepp, did you find a way to get fixtures working using the DoctrineMongoDBBundle? Or is there any other way of writing fixtures for MongoDB which you could recommend?
> 
> Nope, that `doctrine/DoctrineFixturesBundle` is not for ODM, I'm not sure if there is separated package for ODM.

Nope, the functionality is built into the `doctrine/DoctrineMongoDBBundle`, but requires the user to require the `doctrine/data-fixtures` package. See the `doctrine:mongodb:fixtures:load` command for more details.
