### ISSUE TITLE
PHPUnit binary path is wrong

### ISSUE THREAD

**Issue by sebj54** [symfony/symfony-docs#12635]
I noticed that phpunit binary path is wrong in this section: https://symfony.com/doc/current/testing.html#the-phpunit-testing-framework

Path is mentioned as `./bin/phpunit` while it should be `./vendor/bin/simple-phpunit` like it is mentioned in this section: https://symfony.com/doc/current/components/phpunit_bridge.html#usage

**Comment by xabbuh** [comment]
That file should be created by Symfony Flex when the PHPUnit bridge is installed. Do you maybe have an application that does not use Flex?

**Comment by sebj54** [comment]
I think this is the case but as a newbie with Symfony it is unclear to me 😕

**Comment by javiereguiluz** [comment]
We've been discussing about this in the Symfony Docs team. We prefer to keep using `./bin/phpunit`, which is created when running `composer require phpunit` in a Symfony application that uses Flex (all new Symfony apps use that ... you must explicitly remove it if you don't want to use Flex). We've checked and all occurrences of ./bin/phpunit have some comment explaining this, so we prefer to keep it like this for now. Thanks!
