### ISSUE TITLE
[SecurityBundle] Outdated mention about services generated by in-memory user provider

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#12661]
Good first issue: https://symfony.com/doc/4.3/security/user_provider.html#injecting-a-user-provider-in-your-services mentions a `security.user.provider.in_memory.user` service which is not created anymore since https://github.com/symfony/symfony/pull/25837 (2.7).
It should be removed from the list. The Pull Request should be done against 3.4 branch.

**Comment by JoppeDC** [comment]
I couldn't help but notice that this issue seems to be only present in docs 4.2 and up. Not sure how/why to PR against 3.4?
