### ISSUE TITLE
Added context to exceptions thrown in apply method

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12685]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34457
| PR author(s) | @koenreiniers
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
I'm closing here because we don't document `TransitionException` explicitly and this is something easy to discover when you catch the exception and try to use the getter methods to get info from it.
