### ISSUE TITLE
New Symfony 5 Bundle Structure

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#12690]
At the SymfonyCon the [new bundle structure](https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#httpkernel) was also presented in the one year of symfony, but still the old one is shown in the docs: https://symfony.com/doc/current/bundles/best_practices.html#directory-structure. I know that there were some discussions about the new structure but I think as it was presented on the conference the new one is now best practice?

**Comment by yceruto** [comment]
Hi @alexander-schranz, as many bundles must be compatible with a range of Symfony versions, the new directory convention shouldn't be promoted as a best practice yet, but it will be in the future, I think as of Symfony 5.2 next year.

see open issue https://github.com/symfony/symfony-docs/issues/12156

**Comment by alexander-schranz** [comment]
@yceruto I think aslong as there will be no docs for the new structure also new bundles supporting only symonfy 5 will not use the new structure as I would also be afraid that until 5.2 this could frequently change and is not save to be used. Maybe it should be documented both, bundles Supporting only Symfony 5 and bundles which support Symfony 4.4 and lower should use the old one.

**Comment by maxhelias** [comment]
This issue or #12156 could be closed for duplicate

**Comment by xabbuh** [comment]
closing in favour of #12156
