### ISSUE TITLE
[Setup] add version constraint in cli setup commands

### ISSUE THREAD

**Issue by xosofox** [symfony/symfony-docs#12695]
Looking at https://symfony.com/doc/4.4/setup.html, we see

    > symfony new my_project_name

as the command to setup a new project

Of course, this will create a Symfony 5 project now

I think the docs for versions 4.4, 4.3, .... should include the version constraints for the setup commands.

I'd be glad to help - but I am not sure how to add this on the branch system...

**Comment by javiereguiluz** [comment]
@xosofox this is a bit tricky. In the past we decided that the installation would always show how to install the latest stable version (`5.0` at the moment). So, installing 5.0 when reading the Symfony Docs is not a mistake but something intended.

But you are right that we should tell the readers about the `--version` option. Yesterday we merged some changes to add more `--version` examples and to show the alternative when using Composer: https://symfony.com/doc/current/setup.html#symfony-lts-versions

So, we're closing this as "fixed" for now. Thanks.
