### ISSUE TITLE
Service Subscribers & Locators/Indexing the Collection of Services: Code example should include the "index_by" key

### ISSUE THREAD

**Issue by codegain** [symfony/symfony-docs#12704]
In https://github.com/symfony/symfony/issues/34637 I pointed out that `default_index_method` without `index_by` is useless and the indexing logic will not be triggered.

The code example below `If you prefer to use another method name, add a default_index_method attribute to the locator service defining the name of this custom method:` should include the `index_by` key with some value other than `null`.

**Comment by HeahDude** [comment]
Closing as fixed by #13099. Thanks
