### ISSUE TITLE
Documents how to create a custom templates engine

### ISSUE THREAD

**Issue by kylekatarnls** [symfony/symfony-docs#12713]
Hello,

I maintain a template engine adapter to use Pug templates in Symfony: https://github.com/pug-php/pug-symfony

Regarding the breaking changes and the previously big ranges of Symfony versions supported, I decided to drop Symfony < 5 and create a new major version for Symfony 5 from scratch.

But when looking for the new way to create custom template engines, I felt on:
https://symfony.com/doc/current/templating/PHP.html

I assume this is a documentation lack, right? You didn't just remove the template options with no alternatives?

What is the new way to say use XyzEngine renderer to render .xyz files when calling `->render('foobar.xyz', $variables)` from a controller?

Could you please document it?

**Comment by xabbuh** [comment]
There is no such way. Symfony now only supports Twig out of the box. If you want to use other templating engines, you need register services in your bundle that do the rendering and let the user use them.

**Comment by javiereguiluz** [comment]
@kylekatarnls I'm afraid that what @xabbuh said is true. Reading the README of your bundle, I see that before you could this `$this->render('contact/contact.pug', ['...'])`

This will no longer work and you'll need to use the services provided by the bundle explicitly. Something like this: `$this->get('templating.engine.pug')->render('contact/contact.pug', ['...'])`

I'm sorry!
