### ISSUE TITLE
Bad link for The Debug Component

### ISSUE THREAD

**Issue by steevanb** [symfony/symfony-docs#12715]
Hi,

I've just tried to search for `symfony/debug` in Google.
First answer is the Symfony official documentation, with this link: https://symfony.com/doc/current/components/debug.html (seems ok).

But when I click on it, I'm redirected to https://symfony.com/doc/current/https://github.com/symfony/debug.html (seems wrong :p)

I don't know if I can fix it by a PR or not ?

**Comment by jzawadzki** [comment]
Yeah - looks like `redirection_map` doesn't allow for absolute url https://github.com/symfony/symfony-docs/blob/master/_build/redirection_map#L477

**Comment by OskarStark** [comment]
@javiereguiluz can you please check this?

**Comment by javiereguiluz** [comment]
Good catch! We allowed redirections to `https://symfony.com/...` but not to GitHub. We've just fixed this and will be online soon after the next deploy. Thank you!

**Comment by steevanb** [comment]
Thanks for the fix!
