### ISSUE TITLE
[Security] Documentation for custom Authentication Provider not working for 5.0

### ISSUE THREAD

**Issue by GrosTon1** [symfony/symfony-docs#12727]
Hello.

The documentation for "[How to Create a custom Authentication Provider](https://symfony.com/doc/current/security/custom_authentication_provider.html)" is not up to date for SF 5.0. 
The [listener part](https://symfony.com/doc/current/security/custom_authentication_provider.html#the-listener) is not valid anymore, as ListenerInterface has been deleted and Listeners should be callables instead as mentioned in [UPGRADE-5.0](https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#security).

**Comment by HeahDude** [comment]
Closing if favor of #13069.
