### ISSUE TITLE
[Validator] Label regex in date validator

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12735]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34705
| PR author(s) | @kristofvc
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
I don't understand this change well. Should we document it?

**Comment by xabbuh** [comment]
I wouldn't document this. People having to extend the `DateValidator` class will have to read its code anyway and will easily discover what is necessary.
