### ISSUE TITLE
[Validator] mark the Composite constraint as internal

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12777]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34856
| PR author(s) | @xabbuh
| Merged in    | 5.1-dev

**Comment by OskarStark** [comment]
The only thing todo here is checking the documentation for it and remove it if it’s there.

**Comment by javiereguiluz** [comment]
Closing because I can't find any reference to it in docs. Thanks.
