### ISSUE TITLE
Debug component documentation link - circular reference

### ISSUE THREAD

**Issue by bradjones1** [symfony/symfony-docs#12775]
The documentation link at https://github.com/symfony/debug/blob/4.4/README.md links to https://symfony.com/doc/current/components/debug/index.html which redirects to https://symfony.com/doc/5.0/components/debug.html, which then redirects to https://symfony.com/doc/current/components/debug.html, which then redirects to https://github.com/symfony/debug.

The Symfony documentation is awesome so I'd love to find the Debug docs. :-)

Below is abbreviated `curl` output:

```bash
$ curl -L -I https://symfony.com/doc/current/components/debug/index.html
HTTP/2 301 
location: /doc/5.0/components/debug.html
server: cloudflare

HTTP/2 302 
location: /doc/current/components/debug.html
server: cloudflare

HTTP/2 301 
location: https://github.com/symfony/debug
server: cloudflare

HTTP/1.1 200 OK
Server: GitHub.com
Status: 200 OK
```

**Comment by bradjones1** [comment]
Sounds like maybe this is the same/similar to https://github.com/symfony/symfony-docs/issues/12715 but that was closed; am I just impatient or does this remain a problem after the "deploy"?

**Comment by javiereguiluz** [comment]
Good catch Brad! We're trying to fix this in https://github.com/symfony/symfony/pull/34912

**Comment by javiereguiluz** [comment]
Closing as fixed by https://github.com/symfony/symfony/pull/34912.
