### ISSUE TITLE
[HttpClient] HttpClient variable name when injected needs to be $client

### ISSUE THREAD

**Issue by NicolasDievart** [symfony/symfony-docs#12789]
I'm currently migrating a project of mine from a HTTPlug implementation to the HttpClient Component.

Thanks to the documentation of this component and the conference talk done by Nicolas Grekas at the Forum PHP 2019, the migration was really easy and painless.

However, I encontered a possible gap in the documentation and I would like to first talk about it before adding a contribution to it.

I have abstracted all my logic of external HTTP calls in a single service, where previously HTTPlug was used and I had just to inject the HttpClientInterface in my construct.

My configuration was accordingly to the documentation, no specific scoped client :
```
framework:
    http_client:
        max_host_connections: 10
        default_options:
            max_redirects: 5
            timeout: 10
```

However, I could not see any call made in the web profiler even if everything was working properly.

I discovered that you had to name specifically your variable : `$client` to have the the requests collected, whereas my IDE, via autocomplete, proposed me `$httpClient` (because of the interface HttpClientInterface) even if no scoped client is configured.

My diff at the end, to see all my outgoing requests, was just : 
```diff
- public function __construct(HttpClientInterface $httpClient)
+ public function __construct(HttpClientInterface $client)
```

I can not tell if it is just a missing information in the doc or maybe if there is no scoped client created, the default one could be named anything ?

Thank you all for the amazing work !
The migration was really easy and this component is really easy to use !

**Comment by OskarStark** [comment]
Hi @NicolasDievart 

Which versions do you use? http-client, framework.-bundle ?

**Comment by NicolasDievart** [comment]
Hi @OskarStark 

I probably did too much stuffs at the same time. I can not reproduce anymore (first try was on 4.4 (http client and framework bundle), currently i am on 5).

I may have found my first mystake, which is not using the dependency injection but directly the static method :
`HttpClient::create()` which create a NativeHttpClient, which does not collect requests.

Whereas, the dependecy injection gives me the correct Traceable client.

Wasn't clear to me first but now it is.

**Comment by OskarStark** [comment]
Ok, so we can close here?

**Comment by NicolasDievart** [comment]
Yes
