### ISSUE TITLE
[ErrorHandler] Symfony\Component\ErrorHandler\ExceptionHandler not exists.

### ISSUE THREAD

**Issue by subcores** [symfony/symfony-docs#12793]
The ExceptionHandler Class not exists in the symfony/error-handler package as discribed in [https://symfony.com/doc/4.4/components/error_handler.html#debugging-uncaught-php-exceptions](url)

**Comment by javiereguiluz** [comment]
@subcores thanks for reporting this!

@yceruto could you please confirm if the non-existent ExceptionHandler has been renamed to ErrorHandler? If this is true, could you please also confirm that, unlike the Debug component, the new ErrorHandler component uses just 1 class (ErrorHandler) for two different features (PHP errors and uncaught exceptions)? Thanks!

**Comment by yceruto** [comment]
> unlike the Debug component, the new ErrorHandler component uses just 1 class (ErrorHandler) for two different features (PHP errors and uncaught exceptions)? Thanks!

Yes.

https://symfony.com/doc/4.4/components/error_handler.html#debugging-uncaught-php-exceptions

The `ExceptionHandler` was removed in favor of `ErrorHandler::handleException()` + `HtmlErrorRenderer` classes. This is the replacement:
```php
ErrorHandler::register();
```
