### ISSUE TITLE
[ErrorHandler] Enabled the dark theme for exception pages

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12800]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34924
| PR author(s) | @javiereguiluz
| Merged in    | 5.1-dev

**Comment by stof** [comment]
does this need any doc ?

**Comment by javiereguiluz** [comment]
I agree. We don't need docs for this (at least for now). Thanks.
