### ISSUE TITLE
APP_ENV variable in .env

### ISSUE THREAD

**Issue by Ninos** [symfony/symfony-docs#12829]
Hey there,
what's the difference between `APP_ENV=dev` and `APP_ENV=prod`? I know in dev-mode the debug bar is loaded, but other code is still the same.

I'm wondering, because on prod-mode some js-functions are lagging (just on iPhone), on dev all is running fine.

Kindest regards

**Comment by javiereguiluz** [comment]
@Ninos all this is related to "configuration environments", which is explained here: https://symfony.com/doc/current/configuration.html#configuration-environments

We think the current docs are OK, but when reading them, please add a comment here if you find anything confusing and we'll reopen it. Thanks!
