### ISSUE TITLE
UniqueEntity using repositoryMethod with generated value 

### ISSUE THREAD

**Issue by Babar-sama** [symfony/symfony-docs#12832]
For instance, if you want to use repositoryMethod with a generated value (then nullable) you can't since within UniqueEntityValidator

```php
#Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php line 109
        // validation doesn't fail if one of the fields is null and if null values should be ignored
        if ($hasNullValue && $constraint->ignoreNull) {
            return;
        }
```
And it is only after it check the repositoryMethod.
In my case i need this value in my repositoryMethod

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
