### ISSUE TITLE
Service Container can't be set as public

### ISSUE THREAD

**Issue by diogotozzi** [symfony/symfony-docs#12852]
**Symfony version(s) affected**: 5.0.1
**PHP Version**: 7.4.0

**Description**  
According to the Service Container documentation about [public vs private](https://symfony.com/doc/current/service_container.html#public-versus-private-services) services, I cannot reproduce a public accessible service via `$container->get()`.

Even if I follow the [How to Create Service Aliases and Mark Services as Private](https://symfony.com/doc/current/service_container/alias_private.html), with an alias, the service still behaves as _private_.

**How to reproduce**  

The services configuration file:
```yaml
# config/services.yaml
services:
    # ...
    App\Service\MessageGenerator:
        public: true
```

The controller file:
```php
use App\Service\MessageGenerator;

// ...

public funciton new()
{
    $message = $this->container->get(MessageGenerator::class);
}
```

The error:

![Screen Shot 2019-12-16 at 4 01 51 PM](https://user-images.githubusercontent.com/529593/70935510-0baa3300-201f-11ea-8943-7b2d0cebdd5f.png)

**Comment by OskarStark** [comment]
Transfering the issue makes sense. @xabbuh can you please do this?

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed", because the mentioned article was updated in https://github.com/symfony/symfony-docs/pull/13486/files and we removed some confusing docs about injecting the entire container. Thanks.
