### ISSUE TITLE
[Mailer] Broken link 

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony-docs#12875]
On this page: https://symfony.com/doc/current/mailer.html#embedding-images

There is a paragraph: 

> If you want to display images inside your email, you must embed them instead of adding them as attachments. When using Twig to render the email contents, as explained later in this article, the images are embedded automatically. Otherwise, you need to embed them manually.

The "later in this article" is a link, but that link is broken. 

Im not sure where the link was intended to go.

**Comment by MrYamous** [comment]
I guess the right link would be this one : https://symfony.com/doc/current/mailer.html#id1

Maybe the problem is that two subtitles have the same name "Embedding images"

**Comment by Nyholm** [comment]
Oh, so there is a syntax error.. I'll try to submit a PR with a fix. 

Thank you @MrYamous
