### ISSUE TITLE
[Messenger] Log sender alias in SendMessageMiddleware

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12899]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35104
| PR author(s) | @ruudk
| Merged in    | 5.1-dev

**Comment by ruudk** [comment]
@fabpot I assume that this issue was automatically created for me to check if the docs need to be updated. I checked and there are no examples of the logging format written in the Messenger docs. So we can close this issue?
