### ISSUE TITLE
Symfony ve 5 AbstarctController : error Uncaught class not find

### ISSUE THREAD

**Issue by nathaliefell45** [symfony/symfony-docs#12891]
hello, 

I start to work with Symfony . I'm working whith the last version (5).
I try to work the route in controller file , and I have error when using  AbstractController dependencies.
you'll find the begin of controller , and error message during execution

thank you help !
Have a nice day

nathalie

#12891 

<?php
// src/Controller/AdvertController.php

namespace src\Controller;

use Symfony\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/advert")
 */
class AdvertController  extends AbstractController

( ! ) Fatal error: Uncaught Error: Class 'Symfony\FrameworkBundle\Controller\AbstractController' not found in C:\wamp64\www\mooc-symfony5\src\Controller\AdvertController.php on line 15

**Comment by Aerendir** [comment]
Hi @nathaliefell45 , this is not for support questions but only for issues related to Symfony's documentation.

Please, use Stackoverflow to get support.

**Comment by javiereguiluz** [comment]
As @Aerendir said, please use any of the resources available on https://symfony.com/support Thanks.
