### ISSUE TITLE
[HttpClient] Add LoggerAwareInterface to ScopingHttpClient and Traceabl…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12918]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35273
| PR author(s) | @pierredup
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
This is a nice but minor detail, so I think it's better to not mention it explicitly in the HttpClient docs (which are already super long). Thanks!
