### ISSUE TITLE
overwriting error controller should be updated for 4.4

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony-docs#12920]
The article about customizing error pages [1] still mentions `ExceptionController` as base for a new error controller. But this class is depreacated in 4.4 (and removed in 5). But changing the class to 
`Symfony\\Component\\HttpKernel\\Controller\\ErrorController` is not sufficient. The instructions for passing the debug flag do not match as well. 

But do we advised to extend ErrorController, or maybe to set a custom service as `error_renderer`? But I do not get at all how selecting `error_render` works.

related: #12273 

[1] https://symfony.com/doc/4.4/controller/error_pages.html#overriding-the-default-errorcontroller

**Comment by yceruto** [comment]
Hi @SimonHeimberg, you're right and we must remove the `ExceptionController` everywhere in this page. 

Let me know what you want to override exactly, so I can help you. It's likely that you don't need to override the `ErrorController` anymore, unless you have a different error system.

**Comment by SimonHeimberg** [comment]
@yceruto I do not need to change yet, I yust saw this while updateing to symfony 4

----

also related: #13071
