### ISSUE TITLE
Deprecate Yoda conditions on both sources and documentation.

### ISSUE THREAD

**Issue by DocFX** [symfony/symfony-docs#12965]
**Preamble:**

- _Simple community question (not asking for more unless concensus)._
- _This question is **not** about raising all the syntax trolls out there. :)_
- _This question is **only** about Documentation first, as Documentation show more custom sample code than internal Symfony code. But depending on results, question shall be raised on Symfony code repositories as well, for coherence purposes, let's not kick the anthill too fast._

Hi all!

Bumped into this today, while getting feedback on a Symfony Doc PR.

__First:_ sorry if this is not the appropriate place nor form, I usually only correct doc straight away and not create full-text conditions to creating PRs._

This topic was internally solved positively (_i.e._ removed) a few years ago, since PHP7, pretty much everywhere I touched code, home, work, etc. 
Also, being used to contributing / reading code from sources that are not Symfony as much as sources that are Symfony, it seems the latter (which matters right now) is one of the only that uses **Yoda conditions**. 
Most other projects don't, as far as I know. Don't enter a project quoting / namedropping contest, please, this is not the place for it, even though simple mentions would be useful.

**So, my question would be, in one straight sentence: could we consider dropping the Yoda conditions, as mentioned in: https://symfony.com/doc/current/contributing/code/standards.html, or do they still make sense in a full triple-equal syntax world?**

I won't add all arguments here, at a glance:
- https://knowthecode.io/yoda-conditions-yoda-not-yoda
- https://dev.to/greg0ire/why-using-yoda-conditions-you-should-probably-not
- PHP The Right Way doesn't use them: https://phptherightway.com/pages/The-Basics.html
- CodingMachine states it as controversial and avoidable: http://bestpractices.thecodingmachine.com/php/defensive_programming.html
- Long talk in CS-Fixer too: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2446

_Version suggestion: should only affect 5+, thanks to dependency on PHP 7.2.+ and strict + nullable typing, no real link between those two things, but surely can help, considering there should be no "==" left anywhere in the source code, especially when encouraged to use strict typing._

Thanks for the read! :)

**Comment by javiereguiluz** [comment]
@DocFX thanks for creating this proposal. My opinion is: it's true that the original reason for using Yoda conditions is not very relevant today ... but using Yoda conditions is OK ... and not using Yoda conditions is OK too.

Given that changing this would be "brutal" for code and docs ... the new syntax must be worth it (at least 10 times better than the current syntax). I don't think that's the case. So, all things considered, I wouldn't make this change. But let's wait for more opinions.

**Comment by DocFX** [comment]
As I said @javiereguiluz: that was my kick in the anthill. I know how boring this can be. 

Maybe we should update docs stating that mixing both is a middlegroudn that can be in peace? 
The official doc states so, and it was prolly right, despite the weird "applies to === and !==" thing, IMO.

This is actually far from a war to fight, merely a suggestion of maybe updating this so that we all accept both as OK, or unflag the Yoda conditions as "good practices" but instead as "safe practice".

**Comment by fabpot** [comment]
As @javiereguiluz already mentioned, that would be a huge amount of work for nothing. Yoda conditions are still valid and can still be somewhat useful. I don't think that === changes the status quo. In any case, that won't happen as one is not really better than the other. And we try to avoid changes with marginal value but with a huge amount of work.

Thank you for proposing.
