### ISSUE TITLE
"symfony new project" doesn't work in Windows 10

### ISSUE THREAD

**Issue by Nemecsek** [symfony/symfony-docs#12972]
PHP 7.4.1
Symfony 5.0.3
Symfony CLI v4.12.4
Windows 10 Pro

I am following the [online tutorial](https://symfony.com/doc/current/setup.html#creating-symfony-applications), _Creating Symfony Applications_

Both `symfony new my_project_name --full` and `symfony new my_project_name` print out the actions but don't create the project:

```
* Creating a new Symfony project with Composer
   (running C:\ProgramData\ComposerSetup\bin\composer.bat create-project symfony/skeleton C:\_git_files\pippo2)

* Setting up the project under Git version control
  (running git init C:\_git_files\pippo2)

 [OK] Your project is now ready in C:\_git_files\pippo2
```

Executing manually the corresponding commands (`composer create-project ...` and `git init ...`) the project is created.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. Sadly it's related to a temporary issue in the Symfony CLI application. Check this other issue for more information about when it will be fixed: https://github.com/symfony/cli/issues/195
