### ISSUE TITLE
Service container documentation (^4.2 and ^5.0) is wrong/misleading

### ISSUE THREAD

**Issue by debo** [symfony/symfony-docs#12978]
As per subject the documentation for symfony 5 but likely all the versions following 4.2 is rather misleading but let me elaborate.

Starting from [this](https://symfony.com/doc/current/service_container.html) section a user will, possibly, end up [here](https://symfony.com/doc/current/service_container/alias_private.html) where the documentation explains how services can be made public available and easily consumable via the service container itself.

Unfortunately this is not possible because, as I faced, but also as reported [here](https://github.com/symfony/symfony/issues/32633) and [here](https://github.com/symfony/symfony-docs/issues/10744) the `AbstractController` class doesn't provide access to the actual container anymore and the old base `Controller` class is completely deprecated and as such not available to developers.

This as you can understand made this specific part of the documentation not current and irrelevant and it also let me to hours and hours of headache to try to understand what I was doing wrong except there was nothing wrong.

I know I'm not offering a solution here bu I hope my report helps.

**Comment by HeahDude** [comment]
Thanks @debo for the report. I've opened #13057 in an attempt to fix this.

**Comment by debo** [comment]
@HeahDude no problem happy to help and also glad I wasn't talking nonsense; it could have been also a case of me having missed something in the docs.

Thanks for validating and confirming the issue.

**Comment by debo** [comment]
@HeahDude @OskarStark please see my follow up comment [here](https://github.com/symfony/symfony-docs/pull/12977#issuecomment-588544028)
