### ISSUE TITLE
[Secrets] Secret management

### ISSUE THREAD

**Issue by ghostika** [symfony/symfony-docs#12996]
I asked this already at the #12958 PR but reading the documentation now on the Symfony page I have to ask it again
Is the YAML implementation under the section [Referencing Secrets in Configuration Files](https://symfony.com/doc/current/configuration/secrets.html#referencing-secrets-in-configuration-files) correct without the `SECRET:`? 

If yes, then it would be good to explain this in the documentation, why the XML and PHP implementation requires the `secret` prefix for the secret env var.

**Comment by javiereguiluz** [comment]
@weaverryan do you know if this is a typo or a difference in the YAML syntax? Thanks!
