### ISSUE TITLE
[Messenger] Error in XML faremwork:transport documentation

### ISSUE THREAD

**Issue by Metallou-dev** [symfony/symfony-docs#13009]
**Version** 5.0.3

**Error**
`<option>` tag does not exist within `<framework:transport>` sequence
[Link to documentation](https://symfony.com/doc/current/messenger.html#prioritized-transports)

`<framework:option>` tag does not exist within `<framework:transport>` sequence
[Link to documentation](https://symfony.com/doc/current/messenger.html#doctrine-transport)

**Note**
XSD declares the following
```xml
<!-- /vendor/symfony/framework-bundle/Resources/config/schema/symfony-1.0.xsd -->

<xsd:element name="options" type="metadata" minOccurs="0" maxOccurs="unbounded" />

<xsd:complexType name="metadata">
  <xsd:sequence>
    <xsd:any minOccurs="0" processContents="lax"/>
  </xsd:sequence>
</xsd:complexType>
```

So the correct tag should be <framework:options> BUT it also fails (an issue will be submitted regarding this)

**Comment by xabbuh** [comment]
see #13278
