### ISSUE TITLE
[Messenger] missing XML and PHP configuration for failure_transport

### ISSUE THREAD

**Issue by Metallou-dev** [symfony/symfony-docs#13010]
**Version** Current

**Description**
Missing documentation for XML and PHP configuration regarding failure_transport
https://symfony.com/doc/current/messenger.html#saving-retrying-failed-messages

**Notes**
XSD does not specify any attribute to set failure_transport
`/vendor/symfony/framework-bundle/Resources/config/schema/symfony-1.0.xsd`

**Comment by xabbuh** [comment]
see #13277 and symfony/symfony#35897
