### ISSUE TITLE
[Dotenv] Add Dotenv::bootEnv() to check for .env.local.php before calli…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13012]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35308
| PR author(s) | @nicolas-grekas
| Merged in    | 5.1-dev

**Comment by wouterj** [comment]
Closing, as the dotenv component docs have been removed. I created https://github.com/symfony/symfony-docs/issues/13759 to keep track of removing the `config/bootstrap.php` file from the docs.
