### ISSUE TITLE
[Mailer] added tag/metadata support

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13017]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35050
| PR author(s) | @kbond
| Merged in    | 5.1-dev

**Comment by kbond** [comment]
Looking for some direction here. Should this be added to the [mailer component docs](https://symfony.com/doc/current/components/mailer.html), the [framework mailer docs](https://symfony.com/doc/current/mailer.html), or both?

**Comment by javiereguiluz** [comment]
In the framework mailer docs, please. We're going to remove the component docs soon to avoid this kind of confusion. Thanks!
