### ISSUE TITLE
[String] Made AbstractString::width() follow POSIX.1-2001

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13013]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35156
| PR author(s) | @fancyweb
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
Closing as "won't document" because this is an internal detail of the `width()` function, which is already documented here: https://symfony.com/doc/current/components/string.html#methods-related-to-length-and-white-spaces
