### ISSUE TITLE
Update bootstrap_4_layout.html.twig

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13047]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34278
| PR author(s) | @CoalaJoe
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
Closing as "no need to document". Rather than a feature, this looks like some constraint that was removed and now custom fields in Symfony Form theme works as explained in the Bootstrap docs.
