### ISSUE TITLE
[Contracts/Deprecation] Provide a generic function and convention to trigger deprecations

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13058]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35526
| PR author(s) | @nicolas-grekas
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
These other issues may need to be documented as part of this one: #13079 and #13080.

**Comment by wouterj** [comment]
Fixed by https://github.com/symfony/symfony-docs/pull/13379
