### ISSUE TITLE
Document how to install older versions

### ISSUE THREAD

**Issue by claytron5000** [symfony/symfony-docs#13052]
The documentation for installing a new Symfony application is the same for any version page, and will result in an installation of the most recent framework. 

Let's document how to install an older version of the framework.

Note: I haven't figured out how, otherwise I'd submit a PR. Perhaps I can figure it out.

**Comment by MrYamous** [comment]
I don't know if it's the best way to indicate this but in the documentation for Symfony 3.4 and below, there is an example for the installation of previous versions: https://symfony.com/doc/3.4/setup.html#creating-symfony-applications-with-composer.

**Comment by claytron5000** [comment]
I thought I made a PR yesterday for a similar fix, but that is pretty concise and to the point.

**Comment by javiereguiluz** [comment]
Closing as fixed because we changed this recently. For example, if you check 4.4 docs, you end up installing Symfony 4.4. See https://symfony.com/doc/4.4/setup.html
