### ISSUE TITLE
[Cache] add SodiumMarshaller

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#13070]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35019
| PR author(s) | @atailouloute
| Merged in    | 5.1-dev

**Comment by pableu** [comment]
I figured out how to use this and how to generate a key, and I think could document it.

Where would we add the documentation? Directly in https://symfony.com/doc/current/cache.html? Or can we create an "advanced topics" sub-page?

**Comment by wouterj** [comment]
Hi @pableu. Currently, we favor large one page docs over multiple small pages. So I would suggest a "How to encrypt cache data" or the like section somewhere at the bottom of the article you're referencing.

**Comment by Nyholm** [comment]
I agree. https://symfony.com/doc/current/cache.html 

:+1:
