### ISSUE TITLE
[HttpClient] Documentation Link is Incorrect

### ISSUE THREAD

**Issue by Raistlfiren** [symfony/symfony-docs#13117]
Page: https://symfony.com/components/HttpClient
![Screen Shot 2020-02-12 at 11 22 13 AM](https://user-images.githubusercontent.com/234712/74360324-7612f180-4d8a-11ea-8d30-0c8d400af0a6.png)

Minor nuance, but the link to "Documentation" is directed to https://symfony.com/doc/current/.html and should be redirected to https://symfony.com/doc/current/components/http_client.html

Thanks for Symfony! <3

**Comment by javiereguiluz** [comment]
Thanks for reporting this error! It's been fixed in the private repository of symfony.com and it will be available after the next deploy. That's why I'm closing this as fixed. Thanks!
