### ISSUE TITLE
configuration/env_var_processors.rst: explain clearer what resolve: does

### ISSUE THREAD

**Issue by SimonHeimberg** [symfony/symfony-docs#13205]
Out of documentation, I did not understand correctly what `%env(resolve:XXX)%` does.

My understanding now: in the value of the environment variable XXX, it replaces all parameters (like `%yy%`). It does NOT call other processors, so `x: %env(resolve:XXX)%/zzz` with `XXX=/aaa/%env(file:FILE_CONTAINING_PATH)%/bb/` does not work.

I do not understand the current explication:
`Replaces the string FOO by the value of a config parameter with the same name:`
Maybe `FOO` is replaced by the value of the parameter `foo`?

----

file: [configuration/env_var_processors.rst](https://github.com/symfony/symfony-docs/blob/8c2e52a/configuration/env_var_processors.rst)
doc verson: 5.0 (8c2e52a)
tested on: symfony 3.4.37

**Comment by javiereguiluz** [comment]
I'm closing this as fixed because the original explanation was changed in #13417.
