### ISSUE TITLE
DoctrineCacheBundle deprecated

### ISSUE THREAD

**Issue by hackzilla** [symfony/symfony-docs#13275]
I've started getting this message, and other similar messages, in my Symfony v3 app.

```
Using the "memcached" type for cache "metadata_cache_driver" is deprecated since DoctrineBundle 1.12 and will be dropped in 2.0. Please use the "service" or "pool" types exclusively.
```

After digging, I have found out that DoctrineCacheBundle has been deprecated.
```
This bundle is deprecated; it will not be updated for Symfony 5. If you want to use doctrine/cache in Symfony, please configure the services manually. When using Symfony, we no longer recommend configuring doctrine/cache through this bundle. Instead, you should use symfony/cache for your cache needs. However, the deprecation does not extend to doctrine/cache, you'll be able to use those classes as you did so far.
```
https://github.com/doctrine/DoctrineCacheBundle

However, the page on Symfony about Doctrine Configuration, still talks about the old way.
https://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers

**Comment by javiereguiluz** [comment]
@nicolas-grekas as you know everything about Symfony + Cache ... could you please help us here? What should we change in the docs? Thanks!

**Comment by nicolas-grekas** [comment]
Yes our doc should be updated. Maybe recipes could help, but @weaverryan knows this well also :)
