### ISSUE TITLE
[HttpClient] Add portable HTTP/2 implementation based on Amp's HTTP cli…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13293]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35115
| PR author(s) | @nicolas-grekas
| Merged in    | 5.1-dev

**Comment by wouterj** [comment]
@nicolas-grekas can you maybe share a small example on how to use this feature in a Symfony 5.1 application? That way, someone can start documenting this feature It's a huge PR, so I'm sorry if it's already shown somewhere and I just missed it.

**Comment by nicolas-grekas** [comment]
Since https://github.com/symfony/symfony/pull/35924, installing the amphp/http-client is all that is needed, see also https://github.com/symfony/symfony/pull/36137

**Comment by nicolas-grekas** [comment]
The doc page should be updated when it tells that curl is required to leverage true async + http2: there's another option now.
