### ISSUE TITLE
Assets component - remove not needed parameter

### ISSUE THREAD

**Issue by mohammed-elattar** [symfony/symfony-docs#13295]
the code snippet after **Custom Version Strategies** header at line 12 , there is a parameter in the function signature without being used and I think there is no need to it all . 
it's existing in the code base at this file
components/asset.rst line 187

**Comment by javiereguiluz** [comment]
Thanks for reporting this. You are right that the parameter is not used ... but it's part of an interface, as explained in #13296. Closing because of that. Thanks.
