### ISSUE TITLE
Render twig template in specific locale

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#13291]
I'm searching for best practices how to render a specific twig template in a specific locale. Since the new `TranslatorInterface` has no `getLocale` or `setLocale` I'm not sure what the recommend way now is. Before I was doing the following:

```php
$currentLocale = $this->translator->getLocale();
$this->translator->setLocale($adminUser->getLocale());
$content = $this->twig->render('my.html.twig');
$this->translator->setLocale($currentLocale);
```

**Comment by yceruto** [comment]
You could use the `locale` argument of the `trans` filter directly:
```twig
{{ 'key'|trans(locale=user.locale) }}
```
or the tag:
```twig
{% trans into user.locale %}
    key
{% endtrans %}
```

**Comment by alexander-schranz** [comment]
@yceruto I'm aware that there is a parameter but thats really annoying to set this on every call. And somebody forgot it on one place and then its translated to the false language.
  
If there is currently really no other way it would maybe good to introduce something like  `trans_default_locale` similar to `trans_default_domain`.

**Comment by yceruto** [comment]
Yes, I like the idea to add a new `trans_default_locale` tag to solve it. 
You should submit this proposal to the Symfony instead :) Thanks.

**Comment by alexander-schranz** [comment]
@yceruto created #35925

**Comment by javiereguiluz** [comment]
Closing this in favor of the discussion in the code repository. Thanks!
