### ISSUE TITLE
[Cache] Merge conflict in docs

### ISSUE THREAD

**Issue by dannyvw** [symfony/symfony-docs#13336]
https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle

**Comment by xabbuh** [comment]
Has this already been resolved? I don't see any issue there.

**Comment by dannyvw** [comment]
@xabbuh See section Creating Custom (Namespaced) Pools and then below the code blocks.

**Comment by javiereguiluz** [comment]
My bad! I'm sorry. It's been fixed in https://github.com/symfony/symfony-docs/commit/14cad705c22b99c0ea065be9b5185baf10f57211. Thanks!
