### ISSUE TITLE
[Performance] Wrong file name for opcache preload

### ISSUE THREAD

**Issue by florentdestremau** [symfony/symfony-docs#13330]
On page https://symfony.com/doc/master/performance.html

I noticed when trying to apply the `opcache.preload` setting that the file announced in the docs wasn't the actual name of the file in my project. (4.4.5)

```
; php.ini
opcache.preload=/path/to/project/var/cache/prod/App_KernelProdContainer.preload.php
```
Should actually be

```
; php.ini
opcache.preload=/path/to/project/var/cache/prod/srcApp_KernelProdContainer.preload.php
```
(notice the `srcApp_KernelProdContainer`).

As @Pierstoval pointed me, this is because in SF <5 the name of the app is included in the file (src). I can make a docs PR to point this out. 
Should it be on master with a notice or on 4.4 docs ?

**Comment by OskarStark** [comment]
friendly ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
that's correct

**Comment by florentdestremau** [comment]
I'm sorry I really can't get a clear answer as to if I should:

1. Create a PR into 4.4 with a corrected file name
2. Create a PR into master with a "info" panel explaining that in SF < 5, the filename will be prefixed with the app name "src".

**Comment by dbrumann** [comment]
I would prefer 1.

**Comment by florentdestremau** [comment]
PR ready :)
