### ISSUE TITLE
[VarDumper] Outdated and broken documentation for the var dumper server

### ISSUE THREAD

**Issue by Sobak** [symfony/symfony-docs#13342]
Hi,

the current version of the documentation still mentions the `server:dump` command to run the var dumper server, even though the server bundle and its commands are removed as of Symfony 5.0. Additionally it tells to set the dump destination in `debug.yaml` configuration while which is no longer supported.

It was actually this response https://stackoverflow.com/questions/51940485/symfony-dump-server-listening-but-not-hearing-when-i-dump/51950035 that saved the day for me. I couldn't figure it out in the code myself.

Would be great if the documentation could receive an update on that, perhaps there's better way to achieve it than placing a code like this in `index.php` which is what I did for temporary debug purposes.

**Comment by xabbuh** [comment]
The `server:dump` command is not shipped with the WebServerBundle, but is registered by the DebugBundle: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/DebugBundle/Resources/config/services.xml#L94

Do you have that bundle installed?

**Comment by wouterj** [comment]
Hi! I'm going to close this issue, as it didn't get any feedback and as far as we know, the current documentation is still valid (as explained by @xabbuh). Please let me know if you still think something is wrong. Thanks!

**Comment by Sobak** [comment]
@wouterj Hi, I was doing some basic tests with the suggested bundle but failed. I guess that that fall into the documentation problem anymore, though. I should have closed that myself, sorry. Thanks for keeping the issues log clean! I miss that in so many projects
