### ISSUE TITLE
[Validator] Add AtLeastOne constraint and validator

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13355]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35744
| PR author(s) | @przemyslaw-bogusz
| Merged in    | 5.1-dev

**Comment by przemyslaw-bogusz** [comment]
I will do this week.

**Comment by wouterj** [comment]
Fixed by https://github.com/symfony/symfony-docs/pull/13409
