### ISSUE TITLE
[PropertyAccess][DX] Added an `UninitializedPropertyException`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13370]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36117
| PR author(s) | @HeahDude
| Merged in    | 5.1-dev

**Comment by xabbuh** [comment]
I don't think this needs to be documented. When working with the PropertyAccess component you usually do not care about the concrete exception instance being thrown.
