### ISSUE TITLE
[Testing] assertSelectorTextContains example is wrong

### ISSUE THREAD

**Issue by arneee** [symfony/symfony-docs#13385]
Hi,

affected page: https://symfony.com/doc/current/testing.html

**Affected part of the page**
---------------------------------------
`$this->assertSelectorTextContains('html h1.title', 'Hello World')`

> This assertion will internally call $crawler->filter('html h1.title'), which allows you to use CSS selectors to filter any HTML element in the page and check for its existence, attributes, text, etc.
> 
> The assertSelectorTextContains method is not a native PHPUnit assertion and is available thanks to the WebTestCase class.

> Using native PHPUnit methods, the same assertion would look like this:

```
$this->assertGreaterThan(
    0,
    $crawler->filter('html h1.title:contains("Hello World")')->count()
);
```
---------------------------------------

This is wrong. assertSelectorTextContains() will check if the FIRST matching element contains the given text. The native phpunit example will check if there any more than 0 matching elements with that text.

For example, this test might fail since "Stuttgart" is not in the FIRST paragraph:
`$this->assertSelectorTextContains('p','Stuttgart');`

But the native phpunit test will succeed:
```
$this->assertGreaterThan(
        0,
        $crawler->filter('p:contains("Stuttgart")')->count()
);
```

**Comment by wouterj** [comment]
Hi @arneee!

Thanks for your detailed error description. You're completely correct that the docs are indeed wrong... But I'm convinced it's more the code being wrong than the docs. I would expect the assertion to check every matching element (like `...:contains(...)` does). So I've submitted a code fix instead: https://github.com/symfony/symfony/pull/36158

For now, I'm closing this issue. If the PR gets rejected, I'll reopen as we'll have to fix the docs :)

**Comment by arneee** [comment]
Hi @wouterj!

Thank you **very much** for not only looking at this issue, bit even making a PR to make the actual assertion better.
