### ISSUE TITLE
[Mailer] Document how to work with headers

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony-docs#13399]
Currently there is no documentation how to set headers on an email. 

We should mention MetadataHeader and TagHeader and also plain old text headers.

**Comment by Seldaek** [comment]
BTW if someone is looking for an example of a header, mentioning this in the docs might be a nice helpful thing anyway:

```
        $email->getHeaders()->addTextHeader('X-Auto-Response-Suppress', 'OOF, DR, RN, NRN, AutoReply');
```

This header tells most auto-repliers / holiday mode things that it's an automated email which does not require an auto-reply. It reduces quite a bit the amount of nonsensical email traffic you get back.
