### ISSUE TITLE
[Mailer][Mailgun] Support more headers

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13397]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36148
| PR author(s) | @Nyholm
| Merged in    | 5.1-dev

**Comment by Nyholm** [comment]
I think this issue should be closed. 

There is currently only a brief mention of headers here: https://symfony.com/doc/current/mailer.html#multiple-email-transports

PR symfony/symfony#36148 introduced a way to set header *any* valid mailgun header. 

I've opend https://github.com/symfony/symfony-docs/issues/13399 to document headers.
