### ISSUE TITLE
[Form] Allowing plural message on extra data validation failure

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13411]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#34984
| PR author(s) | @popnikos
| Merged in    | 5.1-dev

**Comment by jpjoao** [comment]
Where should this be documented? I failed to find where this is currently being documented. If it can be pointed out to me I could update the documentation.

**Comment by wouterj** [comment]
@jpjoao I think `reference/forms/types/options/extra_fields_message.rst.inc` is the best place to document this. We can keep it real simple (e.g. add one sentence indicating that this allows pluralized messages + maybe a link to https://symfony.com/doc/current/translation/message_format.html#pluralization )
