### ISSUE TITLE
[Workflow] documentation is incomplete

### ISSUE THREAD

**Issue by acantepie** [symfony/symfony-docs#13453]
Yaml config describe on master documentation : https://symfony.com/doc/master/workflow.html is inconsistent.
I have to read FrameworkExtension.php to know how use single_state marking or custom support_strategy class for exemple.

Please update the documentation,

**Comment by dbrumann** [comment]
Do you have a specific question? Maybe you can create an example based on your use case for the docs?

**Comment by wouterj** [comment]
Did you also see https://symfony.com/doc/current/reference/configuration/framework.html#workflows ?

If something is missing there, and you figured it out, are you up to create a PR to add it to the documentation? :)

**Comment by javiereguiluz** [comment]
@acantepie thanks for opening this issue. However, I'm afraid it's too generic. It's better to open new issues explaining in detail what's wrong: which option configs are missing, or which example is wrong, or which exact feature is not documented, etc. We'll be glad to help if you create those issues. Thanks for understanding!
