### ISSUE TITLE
[HttpKernel] Deprecate single-colon notation for controllers

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#13466]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36257
| PR author(s) | @chalasr
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
I can't find any occurrence of the deprecated notation in the docs (this is the main relevant article: https://symfony.com/doc/current/controller/service.html). So, I'm closing this as "fixed".
