### ISSUE TITLE
[DependencyInjection] Deprecate ContainerInterface aliases

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#13469]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35879
| PR author(s) | @fancyweb
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
I've browsed the docs and I found 3 occurrences of the deprecated aliases:

1) This example in the main DI article: https://github.com/symfony/symfony-docs/blob/master/service_container.rst#public-versus-private-services

2) This example in the "service subscribers and locators" article: https://github.com/symfony/symfony-docs/blob/master/service_container/service_subscribers_locators.rst#defining-a-service-subscriber

3) This example in "service decoration": https://github.com/symfony/symfony-docs/blob/master/service_container/service_decoration.rst#control-the-behavior-when-the-decorated-service-does-not-exist

I guess we don't need to do anything for 3) ... but I'm not sure what to do with 1) and 2), so we'll need help. Thanks!

**Comment by nicolas-grekas** [comment]
3) is fine yes, unrelated. 2) is not using the main container but a dedicated locator (that's the whole point of service subscribers), nothing to do either.
1) need to be rewritten yes, a sentence like "This is mostly useful when you want to fetch services lazily:" is misleading nowadays, service subscribers provide the same benefit without the drawback.

**Comment by etshy** [comment]
Sorry for necroing this issue but I'm upgrading a fiw projects fro 5.4 to 6.4 and I have a different opinion about 2.

I know we don't have the full container in a locator, but why not recommending using `ServiceProviderInterface`, the direct interface of `ServiceLocator`, which extends `ContainerInterface` ?

It would be less confusing about the deprecation of `ContainerInterface` usage but stil seeing it on some part of the doc, even if unrelated.

**Comment by javiereguiluz** [comment]
@etshy please, create a new issue in this repository mentioning this so we can discuss about it. Otherwise, your comment will be lost because we don't track comments on closed/merged issues/PRs. Thanks!
