### ISSUE TITLE
[DI] remove restriction and allow mixing "parent" and instanceof-condit…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13527]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36390
| PR author(s) | @nicolas-grekas
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
I haven't found any paragraph mentioning these (now removed) constraints explicitly ... but I'd like to ask @nicolas-grekas if these two paragraphs would be affected by this change. I'll update them if needed. Thanks!

```rst
All attributes on the parent service are shared with the child **except** for
``shared``, ``abstract`` and ``tags``. These are *not* inherited from the parent.

[...]

.. note::

    If you have a ``_defaults`` section in your file, all child services are required
    to explicitly override those values to avoid ambiguity. You will see a clear
    error message about this.
```

**Comment by nicolas-grekas** [comment]
The first one should be kept, and the note can be removed.

**Comment by javiereguiluz** [comment]
Thanks for the quick reply! Changes done in #13546.
