### ISSUE TITLE
[RedisMessengerBridge] Add a delete_after_ack option

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13559]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36464
| PR author(s) | @Seldaek
| Merged in    | 5.1-dev

**Comment by Seldaek** [comment]
Related to https://github.com/symfony/symfony-docs/pull/11869 slightly - at least IMO it could be tackled together. There needs to be a big fat warning that the redis transport with the default configuration is gonna leak memory. You need to configure either `delete_after_ack` (if you use a single group) or `stream_max_entries` (if you can estimate how many max entries is sane in your case). Failing to do this will mean all messages remain forever in redis, which is not going to end well ever IMO.
