### ISSUE TITLE
[Form][Best practices] Inconsistent recommendation for buttons

### ISSUE THREAD

**Issue by Zanguu** [symfony/symfony-docs#13563]
Recently back in Symfony development since a 2 major versions hiatus, I've read the [Best Practices section](https://symfony.com/doc/current/best_practices.html#add-form-buttons-in-templates) where I've  stumbled on this paragraph:
> Instead of adding buttons in form classes or the controllers, it's recommended to add buttons in the templates. 

So, I've started doing that until a couple days where I needed a form with multiple submit buttons and detect which one submitted the form.
`$form->getClickedButton()` giving me only `null` value, I've started looking if there was a How to that documents this and I found it: [How to Submit a Form with Multiple Buttons](https://symfony.com/doc/current/form/multiple_buttons.html).
On that page the form is created with 2 SubmitType and only when doing it you get something out of `$form->getClickedButton()`.

Every other SO thread or tutorial on the subject creates the buttons with the formBuilder.

Is there a way to detect which button submitted a form without creating them in a form object?
If yes, shouldn't that page mention it as it's more in line with the Best Practices?
If no, can we work on adding it or mention it on the Best Practices paragraph that some functionalities might not work when creating buttons in the template?

**Comment by xabbuh** [comment]
> If no, can we work on adding it or mention it on the Best Practices paragraph that some functionalities might not work when creating buttons in the template?

You indeed need to add the button to the form if you want to test in your controller if it was clicked. Adding a short note and linking to the multiple submit buttons article seems like a good idea to me.
