### ISSUE TITLE
[DI] allow loading and dumping tags with an attribute named "name"

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13613]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36586
| PR author(s) | @nicolas-grekas
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
I don't think we need to document this (and I don't know where(how we could do that). As stated in the original code PR, this is "a minor feature added for consistency".

**Comment by stof** [comment]
This actually needs to be documented somewhere in https://symfony.com/doc/current/service_container/tags.html#adding-additional-attributes-on-tags to show how to do the XML configuration for such case (especially given that some core tags rely on the `name` attribute)

**Comment by javiereguiluz** [comment]
Closed as fixed in #18802.
