### ISSUE TITLE
[Security/Core] Add CustomUserMessageAccountStatusException

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13632]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36656
| PR author(s) | @VincentLanglet
| Merged in    | 5.1-dev

**Comment by wouterj** [comment]
The best place to document this would be in https://symfony.com/doc/current/security/user_checkers.html . In the example the - not existing - `AccountDeletedException` line can be replaced with this new class. The _"If one or more conditions are not met, an exception should be thrown which extends the `AccountStatusException`:"_ sentence above the example can then be tweaked to also mention this new exception.
