### ISSUE TITLE
Log deprecations on a dedicated Monolog channel

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13631]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36621
| PR author(s) | @l-vo
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
Closing, because this feature, although nice, is a minor detail ... and everything is auto-configured by the Flex recipe, so users will easily spot the new config, the new log file, etc.
