### ISSUE TITLE
[Form] deprecate `NumberToLocalizedStringTransformer::ROUND_*` constants

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13646]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36711
| PR author(s) | @nicolas-grekas
| Merged in    | 5.1-dev

**Comment by wouterj** [comment]
For reference, the affected piece of documentation is: `reference/forms/types/options/rounding_mode.rst.inc`.
