### ISSUE TITLE
[FrameworkBundle] use the router context by default for assets

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13641]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36681
| PR author(s) | @nicolas-grekas
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
Closing as fixed because we mention this in the updated docs: https://github.com/symfony/symfony-docs/pull/13657/files#diff-3b3b9409bff44f4b31ba1f933dbf0001R2129
