### ISSUE TITLE
[Bundles] DoctrineFixturesBundle misses the example of how to work with fixtures programmatically.

### ISSUE THREAD

**Issue by yyaremenko** [symfony/symfony-docs#13679]
I can't find an official documentation which would give me an example of how to work with fixtures programmatically - how to load only specific entities (fixtures), how to purge after tests, etc. I have to collect info from pieces here and there, e.g.

https://stackoverflow.com/questions/17091772/how-can-i-load-fixtures-from-functional-test-in-symfony-2

http://www.inanzzz.com/index.php/post/vx0y/using-doctrine-data-fixtures-and-testing-dynamic-responses-with-phpunit-in-symfony-applications

https://blog.theodo.com/2019/04/fixtures-right-gestures/

Just compare with the beautiful Laravel documentation https://laravel.com/docs/7.x/database-testing#using-factories

**Comment by javiereguiluz** [comment]
@yyaremenko here are the docs you are looking for:

How to load only specific entities: https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html#fixture-groups-only-executing-some-fixtures

Resetting the database after each test: https://symfony.com/doc/current/testing/database.html#resetting-the-database-automatically-before-each-test

About the doc you posted from other framework, we also have an article about database + testing: https://symfony.com/doc/current/testing/database.html

**Comment by yyaremenko** [comment]
@javiereguiluz thank you for the response; I would still argue about the documentation

> How to load only specific entities: https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html#fixture-groups-only-executing-some-fixtures

1. This documentation only describes console interaction (loading fixtures by executing a command), but gives no info on how to do a loading programmatically (inside a test)

2. Using groups is not the best solution here. I'll explain my point.
Imagine you have 10 tests each needing a specific set of fixtures: the database is huge, has a lot of tables, and you don't need to seed entire database for this exact test. You have to create 10 groups distributed among fixtures. It's rather difficult to control which fixture belongs to which group. Now, imagine you have 100 tests each needing a specific set of fixtures. 500 tests. And more. The number of tests is a real world example, not some imaginary stuff. Much better approach would allow each test to define the list of fixtures it needs.

As, for example, described in the link I posted above (have a look at getFistures() method)
http://www.inanzzz.com/index.php/post/vx0y/using-doctrine-data-fixtures-and-testing-dynamic-responses-with-phpunit-in-symfony-applications

> About the doc you posted from other framework, we also have an article about database + testing: https://symfony.com/doc/current/testing/database.html

Yep, I've looked through this documentation, thank you. Just missed the database auto-resetting thing. Still, this documentation does not explain how to work with fixtures **programmatically**. 

The problem sounds as follows: create a particular set of fixtures, load them during a test execution, get their references and use those references in test. Currently available documentation does not help. All those blog articles out there in Internet (hopefully) do, but you have to collect the information from pieces. And it's not like those blog post describe fancy things, they rather compensate the missing official documentation.

**Comment by javiereguiluz** [comment]
@yyaremenko about the problem of too many fixtures ... Doctrine proposes a solution based on dependencies: https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html#loading-the-fixture-files-in-order

Regarding the programmatic loading of fixtures, I think they are not supported by default Symfony/Doctrine ... but I'm going to ask about this.

**Comment by yyaremenko** [comment]
@javiereguiluz yes, I've read about the loading order, thank you; the problem I describe is not about the order of fixtures loading, the problem is about defining a **limited** set of fixtures for each test (this problem currently could be resolved by groups, but groups is not the good solution)

thank you for the prompt reply.

**Comment by javiereguiluz** [comment]
I've asked about this in the Symfony Slack ... and we came to the conclusion that we already have something better than programmatically loading fixtures.

It's explained here: https://symfony.com/doc/current/testing/database.html#resetting-the-database-automatically-before-each-test. The idea is to load ALL fixtures once ... and use them in all tests. After each tests, the database is reset, so any change you made in a test doesn't affect to others. This is much easier to manage and the resulting tests are much faster because fixtures are only loaded once for the entire test suite.

If you absolutely want to load fixtures programmatically, you can use https://github.com/liip/LiipTestFixturesBundle. but we're not planning to mention it in the docs because we want to promote the other way, which is simpler and much faster.

Thanks for your understanding!
