### ISSUE TITLE
[Templating] Update code sample to twig engine

### ISSUE THREAD

**Issue by Deamon** [symfony/symfony-docs#13703]
Hi,
while struggling with the templating compenent in standalone mode, 
I found that [phpengine is not supported as for sf 5.0](https://symfony.com/doc/current/templating/PHP.html).

But the all [templating page](https://symfony.com/doc/current/components/templating.html) describe how to use the component in standalone using phpengine.

and also there is a link at the bottom of the page forwarding to php templating.

I could update the page if I manage to make it work on my side but its not the case at the moment.

cheers.

**Comment by wouterj** [comment]
The `PhpEngine` is still supported when using the component standalone. Only the integration with the Symfony full-stack framework has been removed. The `TwigEngine` has been removed from Symfony 5 (it didn't make sense anymore - as the framework no longer uses the Templating component).

We're working on removing all component docs, in favor of better framework usage docs + better component README's. See this - currently open - PR to remove the Templating component docs: https://github.com/symfony/symfony-docs/pull/13706 So I'm closing this issue, thanks for understanding!

**Comment by Deamon** [comment]
Sure, thanks for your answer!
