### ISSUE TITLE
backslashes in access_control

### ISSUE THREAD

**Issue by nuryagdym** [symfony/symfony-docs#13745]
Hi,
Why do we need backslashes in access_control? which is described in the [documentation](https://symfony.com/doc/current/security/access_control.html#matching-options)

access_control:
       ` - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.example\.test }`
I tried defining host name without backlashes and it still works...

**Comment by xabbuh** [comment]
If I am not mistaken, the value configured with `host` is a regular expression and the dot has a special meaning there (e.g. without the backslash the example above would also match `adminxexample.test`).

**Comment by nuryagdym** [comment]
It did not match in my case, I teste
