### ISSUE TITLE
[Session] Encrypted session documentation

### ISSUE THREAD

**Issue by lugosium** [symfony/symfony-docs#13755]
Hello,

I am trying to use the new symfony 5.1 feature about encrypted session, but i don't understand how to use it.

In https://symfony.com/blog/new-in-symfony-5-1-httpfoundation-improvements#encrypted-session-data it looks like we should add in our `config/services.yaml` this:

```
Symfony\Component\Cache\Marshaller\SodiumMarshaller:
    decorates: 'session.marshaller'
    arguments:
        - ['%env(file:resolve:SODIUM_DECRYPTION_FILE)%']
        - '@.inner'
```

But i am facing this error:

`Environment variable not found: "SODIUM_DECRYPTION_FILE".`

I certainly don't understand this feature and looking for information about how to use it correctly.

Thank you very much.

**Comment by javiereguiluz** [comment]
@lugosium I'm sorry you're having some issues with this feature. However, there's already a pending issue about this in #13245, so I'm closing this issue in favor of the older one (but I linked to your issue to not forget about this). Thanks!

**Comment by lugosium** [comment]
Thank you for your help @javiereguiluz. I will check the other issue.
