### ISSUE TITLE
Document alternative Requirements Checker usage, perhaps add it as best practice

### ISSUE THREAD

**Issue by Amunak** [symfony/symfony-docs#13758]
This is a follow-up on a Slack discussion.

I think that the [deployment docs](https://symfony.com/doc/current/deployment.html#a-check-requirements) should mention that the Requirement Checker can be used without the Symfony "binary", which is something most people probably don't want to deal with in production.

I would suggest to at least mention that there is an option to `require symfony/requirements-checker`, then adding `"vendor/bin/requirements-checker": "php-script",` as one of the first of `auto-scripts` in `composer.json`. (Note: there is a recipe that adds it there automatically, but in a different way that does not run it under the same PHP executable, being useless on setups with multiple PHP versions).

Even better, there is no reason I can think of why people *shouldn't* be doing this - the requirements checker can catch a lot of common mistakes (like forgetting to set up date.timezone) and it runs extremely fast. Which is why I suggest that it should also be added as a best practice.

**Comment by javiereguiluz** [comment]
I think you are right. We're trying to fix this in #14809. Thanks!
