### ISSUE TITLE
Upgrade Kernel from 5.0 to 5.1

### ISSUE THREAD

**Issue by Cartman34** [symfony/symfony-docs#13753]
Hello,

I got several hours of trouble upgrading Kernel because the upgrade & kernel usage is not documented.
Kernel class changed a lot between 5.0 & 5.1.

About my Kernel 5.0, this is a Kernel generated for new  Symfony 5.0 project using composer create project command. I am using my own extension included in this Kernel to allow my own configuration file.
[Kernel_5.0.php.txt](https://github.com/symfony/symfony-docs/files/4729377/Kernel_5.0.php.txt)

About my Kernel 5.1, this a Kernel generated for another brand new I imported and edited to include my own extension. My extension class was also moved to another namespace.
[Kernel_5.1.php.txt](https://github.com/symfony/symfony-docs/files/4729376/Kernel_5.1.php.txt)

As you can see, bote files are really differents.

I advise all people upgrading the kernel to use the new one and to include their changes after.

**Comment by maxhelias** [comment]
The kernel is in a recipe, see the note to update your recipe : https://symfony.com/doc/current/setup/upgrade_minor.html#updating-recipes

**Comment by Cartman34** [comment]
Okay, so now, I understand more about recipes. But Is there any documentation about using Kernel ?

**Comment by maxhelias** [comment]
Like that ?
https://symfony.com/doc/current/reference/configuration/kernel.html or https://symfony.com/doc/current/configuration/front_controllers_and_kernel.html#the-kernel-class

**Comment by Cartman34** [comment]
Recipes does not contain information about upgrade, this is only replacing the existing files with new version.
These documentations about Kernel are incomplete, there is nothing about build container in Kernel.

**Comment by maxhelias** [comment]
About upgrading, the following command (`compose recipes symfony/framework-bundle`) as guide information for migration would be enough or not ?
The link "recipes history" displays the modifications made since the version installed on the project

![Capture d’écran 2020-06-08 à 09 50 55](https://user-images.githubusercontent.com/12966574/84005858-15797700-a96e-11ea-961f-04c1340aff14.png)

If so, a little promotion in side of Flex about this command could correct this problem.

**Comment by javiereguiluz** [comment]
I'm closing this one in favor of:

* #13778 pull request which updates the docs to the latest recipe contents
* https://github.com/symfony/flex/issues/629 issue which is discussing ways to improve this situation for future updates.

Thanks!

**Comment by qharnay** [comment]
"If I may": updating recipes (and their related documentation) can only be relevant to bare symfony applications users. 
What if an application makes uses of symfony ( ie : migrating a huge legacy app to tend to be a symfony app) and do not rely on recipes ?
