### ISSUE TITLE
Provides a way to override cache and log folders from the ENV

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13787]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37114
| PR author(s) | @Plopix
| Merged in    | 5.2-dev

**Comment by Plopix** [comment]
I can help here if someone points where you would like to add this quick documentation.

**Comment by javiereguiluz** [comment]
@Plopix thanks! I think the best place would be in `configuration/override_dir_structure.rst` showing this as another option to override both cache and log dirs.

**Comment by javiereguiluz** [comment]
Fixed in #13819.
