### ISSUE TITLE
[Console] Add support for true colors

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13795]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36802
| PR author(s) | @fabpot
| Merged in    | 5.2-dev

**Comment by wouterj** [comment]
This applies to https://symfony.com/doc/current/console/coloring.html

In there, we're saying "Available foreground and background colors are: black, red, green, yellow, blue, magenta, cyan and white.". This should be updated to say something like "any hex color is supported, besides that these named colors are supported:". And then also say something about "if the terminal doesn't support true colors, the nearest named color is used".
