### ISSUE TITLE
Use PHP instead of XML as the prefered service/route configuration in c…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13798]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36778
| PR author(s) | @fabpot
| Merged in    | 5.2-dev

**Comment by stof** [comment]
I don't think the fact that the core uses PHP rather than XML has any impact on the doc.

**Comment by xabbuh** [comment]
I don't think we need to change anything here. The website already remembers the format that people choose to read code examples. Changing the order of code blocks will cause too much trouble when merging branches IMO.
