### ISSUE TITLE
[Frontend] Stop mentioning Assetic as an alternative?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#13813]
Follow-up of #13801

The [documentation](https://symfony.com/doc/4.4/frontend/encore/versus-assetic.html ) suggest to keep using [`symfony/assetic-bundle`](https://packagist.org/packages/symfony/assetic-bundle) but this bundle doesn't work with Symfony 4.

Message from @javiereguiluz:

> However, we may instead update this to stop mentioning Assetic as an alternative. This text was originally written when "everybody" used Assetic and there was some opposition to moving to JS-based solutions. But now the situation is the opposite: most people use and are happy with JS-based solutions. @weaverryan would you agree removing/rewording this to stop mentioning Assetic as an alternative? Thanks!

This page exist and is identical for Symfony 3.4, 4.4, and 5.0+. Should it be kept as is for 3.4 and updated only for Symfony 4.4 onwards?

**Comment by wouterj** [comment]
If Symfony no longer maintains the alternative, I would say it's fine to stop mentioning the alternative in the official docs. It doesn't make sense to give people a choice when there is no choice 😄 

So I'm 👍 for removing the article for 4.4+

**Comment by xabbuh** [comment]
I agree with Wouter.

**Comment by javiereguiluz** [comment]
OK, let's do that in #13823.
