### ISSUE TITLE
MicroKernelTrait error

### ISSUE THREAD

**Issue by Surfoo** [symfony/symfony-docs#13865]
Hello,

I followed the first example _A Single-File Symfony Application_, just here: https://symfony.com/doc/current/configuration/micro_kernel_trait.html

And it doesn't work, here the log from Symfony CLI: 

```
[Web Server/PHP ] Jun 19 00:05:02 |DEBUG| PHP    127.0.0.1:50258 Accepted path="/usr/bin/php" php="7.4.6"
[Web Server/PHP ] Jun 19 00:05:02 |ERROR| PHP    Uncaught PHP Exception TypeError: "Argument 1 passed to Kernel::configureRoutes() must be an instance of Symfony\Bundle\FrameworkBundle\Routing\Loader\Configurator\RoutingConfigurator, instance of Symfony\Component\Routing\RouteCollectionBuilder given, called in [***]/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php on line 171" at [***]/index.php line 33 
[Web Server/PHP ] Jun 19 00:05:02 |DEBUG| PHP     
[Web Server/PHP ] Jun 19 00:05:02 |DEBUG| PHP    127.0.0.1:50258 Closing 
[Web Server/PHP ] Jun 19 00:05:02 |ERROR| SERVER GET  (500) /random/10 ip="::1"
```

Can you confirm this bug by reproducing it?

**Comment by javiereguiluz** [comment]
The error says: "you must pass a RoutingConfigurator object, but you passed RouteCollectionBuilder".

But the page you linked to only uses "RoutingConfigurator". We changed this in the page very recently, maybe you were using a previous page version?

**Comment by Surfoo** [comment]
No cache issue, I opened the page for the first time yesterday.

The last commit on the rst file is about 3 months ago : https://github.com/symfony/symfony-docs/blob/5.1/configuration/micro_kernel_trait.rst not very recent :thinking:

**Comment by javiereguiluz** [comment]
You are right. This was fixed in #13394 a few months ago.

I was confused by this other PR #13852 from four days ago, which was related to the "RoutingConfigurator" vs "RouteCollectionBuilder" mismatch.

-----

In any case, in the page you linked: https://github.com/symfony/symfony-docs/blob/5.1/configuration/micro_kernel_trait.rst you can see this code:

```php
protected function configureRoutes(RoutingConfigurator $routes)
```

So, Symfony Docs are using `RoutingConfigurator` but the error you showed says "hey, you must use RoutingConfigurator but you are using RouteCollectionBuilder". That's why I don't fully understand the problem.

**Comment by Surfoo** [comment]
Here the bug from the browser : 
![microkernel](https://user-images.githubusercontent.com/553659/85128246-2e690e80-b231-11ea-849a-c29372518468.png)

The issue is in MicroKernelTrait.php, right ?

**Comment by javiereguiluz** [comment]
Yes, your code looks right. I still can't understand why this error happens, so I'll ask to the @symfony/team-symfony-docs to see if they can spot the error. Thanks!

**Comment by xabbuh** [comment]
Does it help if you rename the method to `configureRouting()`?

**Comment by Surfoo** [comment]
No, this method doesn't exist anyway in `MicroKernelTrait`.

```
"Kernel" uses "Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait", but does not implement the required method "protected function configureRoutes(RoutingConfigurator $routes): void".
```

**Comment by xabbuh** [comment]
And if you change the `use` statement to `use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;`?

**Comment by Surfoo** [comment]
OK, it almost works now.

I have a 404:
![404](https://user-images.githubusercontent.com/553659/85141901-d1c51e00-b247-11ea-84a9-3ffc5fc9eb5f.png)

**Comment by Surfoo** [comment]
I still have the 404, I think something is wrong in the code here: https://symfony.com/doc/current/configuration/micro_kernel_trait.html

Can you try on your side please?

**Comment by wouterj** [comment]
Please note that this is not an official support channel. Obviously, there is something wrong in the docs so this doc issue is still valid. However, if you need direct help with issues you're facing, you can get quicker help in one of the support channels: https://symfony.com/support (e.g. Slack or StackOverflow).

Please also note that it has been weekend and this project is almost fully run by volunteers. Things can take a bit longer than paid services :)

**Comment by Surfoo** [comment]
You are right, I have been rude in my previous message (deleted now), sorry.

I'll ask on slack or SO, thank you!
