### ISSUE TITLE
[Security] Let security factories add firewall listeners

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13872]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37336
| PR author(s) | @scheb
| Merged in    | 5.2-dev

**Comment by wouterj** [comment]
I'm not so sure about this one.

With the new system, the only people needing to create authentication factories are the devs creating bundles. We do not yet have an article describing how to use the authentication factories for bundle authors. So let's close this one, we'll see the changelog/code if we ever add such document.
