### ISSUE TITLE
[Notifier] Return SentMessage from the Notifier message handler

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13894]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37403
| PR author(s) | @fabpot
| Merged in    | 5.2-dev

**Comment by phpfour** [comment]
I'd like to work on this during the [SymfonyWorld Hackday](https://sfhackday.com/)!

**Comment by Nyholm** [comment]
Awesome #SymfonyHackday

**Comment by JohJohan** [comment]
I don't think changes are needed the [MessageHandler](https://github.com/fabpot/symfony/blob/master/src/Symfony/Component/Notifier/Messenger/MessageHandler.php) isn't documented and no interface is updated so its not required to return a `SentMessage`. That is why i think no documentation is needed

**Comment by xabbuh** [comment]
Let's close here then. Thanks for investigating @JohJohan.
