### ISSUE TITLE
Why is the string concatenation code style in code examples not according to PSR-2?

### ISSUE THREAD

**Issue by dsentker** [symfony/symfony-docs#13902]
In all code examples, no spaces are used between the period that connects two strings. [According to PSR-2](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#strings-and-concatenation), the space is required. Without the space, the code is harder to read IMHO.

Here is an example from "[Using command arguments](https://symfony.com/doc/3.4/console/input.html#using-command-arguments)":
```php
$names = $input->getArgument('names');
if (count($names) > 0) {
    $text .= ' '.implode(', ', $names);
}
```
Is there anything against putting a space between the periods?

**Comment by wouterj** [comment]
We're using the Symfony code style in the documentation: https://symfony.com/doc/current/contributing/code/standards.html#structure

> Add a single space around binary operators (`==`, `&&`, `…`), with the exception of the concatenation (`.`) operator;

**Comment by dsentker** [comment]
OK, I always thought that the Symfony CS was compatible with PSR.
