### ISSUE TITLE
[HttpClient] always yield a LastChunk in AsyncResponse on destruction

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13936]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37482
| PR author(s) | @nicolas-grekas
| Merged in    | 5.2-dev

**Comment by javiereguiluz** [comment]
I'd say this is "an internal thing" that shouldn't be documented explicitly.

**Comment by nicolas-grekas** [comment]
It's not internal but it's advanced for sure, and ppl that care will figure out (or it will "just work" for them.)
