### ISSUE TITLE
use Jetbrains Mono as code fonts

### ISSUE THREAD

**Issue by erlangp** [symfony/symfony-docs#13939]
https://www.jetbrains.com/lp/mono/
https://github.com/JetBrains/JetBrainsMono
:)

**Comment by javiereguiluz** [comment]
@erlangp thanks for your proposal. We'll consider it when we redesign the site. Meanwhile, you can use browser extensions like [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) to change the styles of symfony.com and any other site.
