### ISSUE TITLE
[HttpKernel][WebProfilerBundle] Add session profiling

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13931]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36364
| PR author(s) | @mtarld
| Merged in    | 5.2-dev

**Comment by javiereguiluz** [comment]
Closing because in the docs we don't explain this kind of details. In any case, developers will easily discover this new nice feature when using the profiler in their apps. Thanks!
