### ISSUE TITLE
[ErrorHandler] Allow override of the default non-debug template

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13942]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37492
| PR author(s) | @PhilETaylor
| Merged in    | 5.2-dev

**Comment by javiereguiluz** [comment]
Closing because this is only for standalone component usage ... and the related code contribution already added a mention to this in the component README.

**Comment by PhilETaylor** [comment]
Thanks for your time anyway :)
