### ISSUE TITLE
Link to easy admin documentation

### ISSUE THREAD

**Issue by JakeFr** [symfony/symfony-docs#13941]
Hello
(not sure if it's the good repo)

The link to the documentation of EasyAdminBundle in https://symfony.com/doc/bundles/ shows docs for version 2 (even if the select box says it's v3)

I think it's a routing issue
Links for **1.x**, **2.x** and **master** are fine
Alias **current** is for **2.x** and should be **3.x**/**master**

**Comment by javiereguiluz** [comment]
Thanks for reporting this. I think I've found the problem and fixed it locally. I created a pull request in the private repository of smyfony.com, so this will be fixed online after merging and deploying. Thanks!
