### ISSUE TITLE
[Form] Improve invalid messages for form types

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#13954]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#30931
| PR author(s) | @hiddewie
| Merged in    | 5.2-dev

**Comment by wouterj** [comment]
@xabbuh do you think there is something to do here? Nothing changes until you configure the option, and the deprecation notice already explains the option name. A possible solution is to add a little note about this for the updated form types, but I'm not sure if it's really needed.

**Comment by wouterj** [comment]
Oh, we also need to update the relevant form types to document their new `invalid_message` default value.

**Comment by xabbuh** [comment]
I think documenting the new default value when you opt-in for it is the only relevant change needed here.
