### ISSUE TITLE
[PhpUnitBridge] Polyfill new phpunit 9.1 assertions

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13975]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37567
| PR author(s) | @phpfour
| Merged in    | 5.2-dev

**Comment by wouterj** [comment]
Closing this issue as we don't document the full list of backwards compatible methods by the PhpunitBridge: https://symfony.com/doc/current/components/phpunit_bridge#polyfills-for-the-unavailable-methods
