### ISSUE TITLE
[HttpFoundation] Added File::getContent()

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13974]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37479
| PR author(s) | @lyrixx
| Merged in    | 5.2-dev

**Comment by javiereguiluz** [comment]
Closing because we don't need or use this feature in the docs. We explain how to upload files and safely move and rename them, but that's all. Developers needing this feature will discover it easily via their IDEs.
