### ISSUE TITLE
DotEnv on/off switches, booleans

### ISSUE THREAD

**Issue by szepeviktor** [symfony/symfony-docs#13982]
How should one add an on/off switch to `.env`?

```ini
SWITCH=on
SWITCH=off
SWITCH=true
SWITCH=false
SWITCH=1
SWITCH=0
SWITCH=enabled
SWITCH=disabled
...
```

Please include it in the documentation.
Thank you.

**Comment by noniagriconomie** [comment]
I personaly use 1 and 0 and after you can use the
https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors features

**Comment by szepeviktor** [comment]
Thank you.

![kép](https://user-images.githubusercontent.com/952007/88112390-124de980-cbb0-11ea-9b5f-0b7d49431ba7.png)
