### ISSUE TITLE
[Console] Add signal event

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14016]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#33729
| PR author(s) | @marie
| Merged in    | 5.2-dev

**Comment by javiereguiluz** [comment]
When documenting, keep in mind these changes that were merged later: https://github.com/symfony/symfony/pull/37827

**Comment by lyrixx** [comment]
And https://github.com/symfony/symfony/pull/38845

**Comment by javiereguiluz** [comment]
Fixed by #15717 and #15741.
