### ISSUE TITLE
[Notifier] Make Freemobile config more flexible

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14030]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37747
| PR author(s) | @fabpot
| Merged in    | 5.2-dev

**Comment by javiereguiluz** [comment]
Closing because we don't document these internal details. But the code in https://github.com/symfony/symfony/pull/37747/files could have added a comment about this in the argument description to improve its discoverability.
