### ISSUE TITLE
[Notifier] added telegram options

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14044]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36496
| PR author(s) | @krasilnikovm
| Merged in    | 5.2-dev

**Comment by wouterj** [comment]
This can be done in a similar way as Slack options are documented: https://symfony.com/doc/current/notifier/chatters.html#adding-interactions-to-a-slack-message

**Comment by javiereguiluz** [comment]
Closing as fixed by #14503.
