### ISSUE TITLE
[Workflow] Choose which Workflow events should be dispatched

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14062]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37815
| PR author(s) | @stewartmalik, @lyrixx
| Merged in    | 5.2-dev

**Comment by lyrixx** [comment]
@stewartmalik Since you are the first author of the issue and (code) PR, would you mind submitting a PR for the doc? 🙏🏼 Thanks

**Comment by lyrixx** [comment]
The doc PR has been merged, we can merge this issue

**Comment by OskarStark** [comment]
You mean "close"? Yes 😄  

Thank you!
