### ISSUE TITLE
Improve link script with rollback when using symlink

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14113]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37915
| PR author(s) | @noniagriconomie
| Merged in    | 5.2-dev

**Comment by ogizanagi** [comment]
This one should probably go to 3.4, as https://github.com/symfony/symfony/pull/37952

**Comment by noniagriconomie** [comment]
@ogizanagi the doc PR is created, should i rebase it also?

**Comment by ogizanagi** [comment]
@noniagriconomie : Sure, let's go :)
