### ISSUE TITLE
[Semaphore] Added the component

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14139]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35780
| PR author(s) | @lyrixx
| Merged in    | 5.2-dev

**Comment by lyrixx** [comment]
Hello,

I created a very simple PR for the composant. It's only about the basics. 

If someone wants to finish it (in another PR) It would be very cool ! 

TODO:

* [x] Installation
* [x] Basic usage
* [ ] Expiring Locks (refreshing)
* [ ] Store
  * [ ] Redis

**Comment by javiereguiluz** [comment]
The first docs have been merged in #14144, so this is now closed. We'll keep adding improvements to these docs in the future.
