### ISSUE TITLE
Rename messenger/message-recorder.rst

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14148]
The `messenger/message-recorder.rst` file name is confusing as it is not related to what it explains. That's probably due to the fact that this feature started as a recorder (https://github.com/symfony/symfony/pull/27844), but it was later merged with a different name (https://github.com/symfony/symfony/pull/28849).

I think we should rename this file according to the new naming.

/cc @Nyholm

**Comment by Nyholm** [comment]
You are correct. It should be changed.

I was just about to start making a PR but @xabbuh was quicker =)
