### ISSUE TITLE
[PHPUnitBridge] deprecations not disabled anymore when disabled=0

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14157]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#38017
| PR author(s) | @l-vo
| Merged in    | 5.2-dev

**Comment by l-vo** [comment]
@fabpot no need to add documentation for this one because the change allows to match to what is currently written in the [doc](https://symfony.com/doc/5.1/components/phpunit_bridge.html#disabling-the-deprecation-helper) :)
