### ISSUE TITLE
Legacy docs have black text on black background

### ISSUE THREAD

**Issue by afilina** [symfony/symfony-docs#14178]
Example: https://symfony.com/legacy/doc/getting-started/1_4/en/04-Project-Setup

<img width="715" alt="Screen Shot 2020-09-04 at 4 43 23 PM" src="https://user-images.githubusercontent.com/199835/92283491-fedfaf00-eecd-11ea-9f35-dbad5bc7024f.png">

**Comment by javiereguiluz** [comment]
Thanks for reporting this error! We've merged some changes to fix it, so it will be displayed correctly soon after code is deployed and caches expire.
