### ISSUE TITLE
HttpClient is missing in list of components

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#14194]
at https://symfony.com/doc/4.4/components/index.html

**Comment by wouterj** [comment]
That is expected. We're removing all component docs in favor of better framework usage and better README's. You can find the combined framework and component docs for the HttpClient component here: https://symfony.com/doc/current/http_client.html

**Comment by ThomasLandauer** [comment]
@wouterj OK, so https://symfony.com/doc/4.4/components/index.html is in fact something like a TODO list of components where this transition isn't finished yet? So this will probably take some time?! => Then I'd suggest to either add a (large) note explaining this, or remove the page completely. Why? It's always annoying if something *appears* to be a full list, when in fact is isn't.

**Comment by wouterj** [comment]
I agree. See #14196
