### ISSUE TITLE
SMS Channel overview gone

### ISSUE THREAD

**Issue by jschaedl** [symfony/symfony-docs#14207]
I just realized that the sms channel overview in the notifier documentation is gone.

https://symfony.com/doc/current/notifier.html
![Screenshot 2020-09-10 at 14 37 28](https://user-images.githubusercontent.com/1880467/92729964-6d5fb980-f373-11ea-9ea7-396f8d87aa74.png)

vs. 

https://symfony.com/doc/master/notifier.html
![Screenshot 2020-09-10 at 14 37 18](https://user-images.githubusercontent.com/1880467/92729984-76508b00-f373-11ea-806d-f29967f52727.png)

Looks like a formatting issue, because I can still see it in the code but its gone in the rendered page: https://github.com/symfony/symfony-docs/blob/master/notifier.rst

**Comment by xabbuh** [comment]
Do we still need to do anything here?

**Comment by jschaedl** [comment]
Was fixed in https://github.com/symfony/symfony-docs/pull/14211
