### ISSUE TITLE
[PropertyInfo] fix array types with keys (array<string, string>)

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14205]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37559
| PR author(s) | @digilist
| Merged in    | 5.2-dev

**Comment by javiereguiluz** [comment]
This is a nice feature ... but in the PropertyInfo doc we don't show the full details about what do you get when inspecting the types of properties. We only explain the general ideas about getting that information. So, we can close this issue.
