### ISSUE TITLE
[Messenger] Don't prevent dispatch out of another bus

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14214]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#37976
| PR author(s) | @ogizanagi
| Merged in    | 5.2-dev

**Comment by Nyholm** [comment]
This is not a feature that should be documented. 

Here is the related page: https://symfony.com/doc/current/messenger/dispatch_after_current_bus.html

I vote for closing this issue.

**Comment by ogizanagi** [comment]
I agree. I don't think there is anything particular to notice the developper about.

**Comment by javiereguiluz** [comment]
Closing then. Thanks for checking it.
