### ISSUE TITLE
Need create a documentation for rate-limiter component

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony-docs#14258]
I see a link from rate-limiter component Readme file : https://symfony.com/rate-limiter

Anyone create this documentation or i can create this ?

**Comment by wouterj** [comment]
It's an open issue: https://github.com/symfony/symfony-docs/issues/14248 (the feature just got merged).

Standalone usage is already documented in the README: https://github.com/symfony/rate-limiter/#getting-started The missing documentation should focus on framework usage. It's on my list to pick up after feature freeze (I'm doing it a bit easy on creating new PRs the next 2 weeks), but feel free to pick it up as well.

The page you're liking to is something internal in symfony.com's repository I think, @javiereguiluz can you help us out here? :)

**Comment by TheGarious** [comment]
I can create a begin documentation with take reference the README: https://github.com/symfony/rate-limiter/#getting-started. 

And create a WIP Pull request for finish this ? 

@wouterj  and @javiereguiluz  it's right for you ?

**Comment by TheGarious** [comment]
I create a pull request with some information from Readme Rate limiter git.

https://github.com/symfony/symfony-docs/pull/14266
