### ISSUE TITLE
[String] allow passing null to string functions

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14276]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#38269
| PR author(s) | @kbond
| Merged in    | 5.2-dev

**Comment by wouterj** [comment]
Closing, I don't think there is anything to document here. This is a feature that will probably be only used implicitly (e.g. in nullable fields), rather than explicitly (I think people will/should use `s('')` to construct empty strings, rather than `s(null)`).
