### ISSUE TITLE
[Security] Support class inheritance in UserProvider::supportsClass by default

### ISSUE THREAD

**Issue by CharlyPoppins** [symfony/symfony-docs#14292]
Issue :
https://github.com/symfony/maker-bundle/pull/532

MR :
https://github.com/symfony/maker-bundle/pull/532/commits/fa83c95dd585143e435ac848df8e2b4dfa270dd8

Doc MR :
https://github.com/symfony/symfony-docs/pull/14293

**Comment by wouterj** [comment]
Closing as fixed by #14304
