### ISSUE TITLE
[Validator] Add support for UUIDv6 in Uuid constraint

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14300]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#38332
| PR author(s) | @nicolas-grekas
| Merged in    | 5.2-dev

**Comment by JohJohan** [comment]
I updated the docs https://github.com/symfony/symfony-docs/pull/14334

**Comment by javiereguiluz** [comment]
Fixed by #14334.
