### ISSUE TITLE
[Monolog] Autowire Logger Channels

### ISSUE THREAD

**Issue by reiterth** [symfony/symfony-docs#14316]
As described here
https://symfony.com/doc/current/logging/channels_handlers.html#how-to-autowire-logger-channels
this only works if the channel is predefined in 

_config/packages/*/monolog.yaml_

```
monolog:
    channels: ['autowirechannelname']

```

**Comment by Matts** [comment]
How about this:

Starting from `MonologBundle`_ 3.5 you can autowire different Monolog channels
by type-hinting your service arguments with the following syntax:
``Psr\Log\LoggerInterface $<channel>Logger``. The ``<channel>`` must have been
predefined in your monolog configuration.

An example to inject the service related to the ``app`` logger channel use this:
