### ISSUE TITLE
[Messenger] Add DelayStamp::delayFor() and DelayStamp::delayUntil()

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14373]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#38484
| PR author(s) | @Nyholm
| Merged in    | 5.x

**Comment by Nyholm** [comment]
I think this should be closed. 

We had no mention of the `DelayStamp` in the docs. 
I added https://github.com/symfony/symfony-docs/pull/14374 to show that the `DelayStamp` exists but Im not sure we need to show the new factory methods with examples.
