### ISSUE TITLE
Document how to change .env location

### ISSUE THREAD

**Issue by omsi668** [symfony/symfony-docs#14383]
Hello,

I lost a lot of time trying to change the location of the .env file Symfony is using. I ended up finding it by luck when researching through my project.

In the end you just have to change the hardcoded path in the application entry point (index.php and console). 

But I think it is a good idea to document that as it is a not-so-rare issue and usually you don't want/go to your entry point created by symfony to modify things.

Thank you

**Comment by JohJohan** [comment]
Why would you want to change the location of the `.env` file?

**Comment by omsi668** [comment]
Well that's not relevant for the issue but in this case we where doing a monorepo with subfolders and wanted to have a common .env.

Why would you want to limit that?

**Comment by javiereguiluz** [comment]
After thinking about this ... I'm going to close as "won't fix for now".

Changing the location of this file is a very rare edge-case according to what I see in the Symfony community. If we receive more requests/questions about this, we'll reconsider this decision. Thanks for understanding 🙏
