### ISSUE TITLE
The 'default' domain for translation files

### ISSUE THREAD

**Issue by 34rc1n** [symfony/symfony-docs#14390]
I have spent a lot of time wondering why my new translation files are not being recognized.
The issue was that they were namend "en.yaml" "en.php" etc. (no domain defined)

The manual does not state that domain part is required. 

> domain: An **optional** way to organize messages into groups. Unless parts of the application are explicitly separated from each other, it is **recommended** to only use default messages domain;

Please give some information about that here.. https://symfony.com/doc/current/translation.html#translation-resource-locations

**Comment by Matts** [comment]
Will look at this. Maybe instead of optional, we should say:

domain: Domains are a way to organize messages into groups. Unless parts of the application are explicitly separated from each other, it is recommended to only use default `messages` domain; (e.g. `messages.en.yaml`)

**Comment by 34rc1n** [comment]
You could write in addition.
"If no domains will be explicitly defined Symfony will look for "messages" domain (e.g. messages.en.yaml)"

**Comment by Matts** [comment]
changed 👍
