### ISSUE TITLE
[Online Symfony 5 book] Paragraph 1.9 in nl/it/ro-translations contains typo in different hyperlinks

### ISSUE THREAD

**Issue by vmeijer** [symfony/symfony-docs#14441]
Hello all, I have been looking for an 'edit' button or an other possibility to create a pull request for the pages behind the online Symfony 5 book (https://symfony.com/book), but I couldn't find them so I'm taking the liberty to propose a little improvement through this repository's issue tracker. (If it is possible to make a pull request for the online book, please do point me in the right direction :female_detective: )

Paragraph 1.9 has a 'hyperlink typo' somewhere in the Dutch, Italian, and Romanian language (I checked all languages after discovering it in the Dutch translation). I realise this is a relative minor issue, but I love to try and help where I can, so at least I wanted to show what I saw in order to make it easier for the correct people to edit it :smile: 

In the following screenshots I show the same paragraph but with green rectangles, so that it is easier to see what I mean.

The English version at https://symfony.com/doc/current/the-fast-track/en/1-tools.html looks like this:
![symfony-book-paragraph-1-9](https://user-images.githubusercontent.com/11903368/96375000-9a736900-1176-11eb-962f-ef3ca78e305d.png)
.
.
The Dutch version at https://symfony.com/doc/current/the-fast-track/nl/1-tools.html has a typo in the link to `SymfonyConnect` somewhere, making the last part of the sentence cursive and the link unclickable (although the full url is visible and can be copied):
![symfony-book-nl](https://user-images.githubusercontent.com/11903368/96375224-effc4580-1177-11eb-8f95-f6d1c8eb52be.png)
.
.
The Italian version at https://symfony.com/doc/current/the-fast-track/it/1-tools.html has an underscore before and after the third link:
![symfony-book-it](https://user-images.githubusercontent.com/11903368/96375266-2d60d300-1178-11eb-8b5d-9c4cb2e04a1c.png)
.
.
The Romanian version at https://symfony.com/doc/current/the-fast-track/ro/1-tools.html has a typo in the link to `Symfony CLI`, making the link unclickable (although the full url is visible and can be copied, just like the Dutch example above):
![symfony-book-ro](https://user-images.githubusercontent.com/11903368/96375354-d9a2b980-1178-11eb-9301-387a40bf4c1c.png)

**Comment by wouterj** [comment]
@fabpot can you please have a look at these? (maybe it's good to also activate DOCtor-RST on de book repositories :wink: )

**Comment by wouterj** [comment]
Oh and thanks a lot for finding the little bugs across many languages @vmeijer!

**Comment by OskarStark** [comment]
I could help Setup DOCtor-RST. Is the repo publicly available?

**Comment by fabpot** [comment]
There is no repo as the translations are managed by Sphinx directly, so there is no RST files for them. I will see how I can incorporate DOCtor-RST somehow to do the validation (I do have some validation already in the translation tool, but it is not sufficient apparently).

**Comment by javiereguiluz** [comment]
@vmeijer thanks a lot for reporting these issues. However, we can't fix them in this repository, so let's close this issue and let Fabien fix this in the tool used for translations. Thanks!

**Comment by vmeijer** [comment]
You're welcome, thanks for the answer! :+1:
