### ISSUE TITLE
Missing explanation of the possible priority values

### ISSUE THREAD

**Issue by naliferov** [symfony/symfony-docs#14466]
For example https://symfony.com/doc/current/service_container/tags.html#tagged-services-with-priority
There we can see example of setting priority. But no description possible values of priority and how this value processing, and how it affects order of tagged elements.

But instead of previous article here this description presents.
https://symfony.com/doc/current/reference/dic_tags.html

Also many components has lack of different examples and use cases.

**Comment by wouterj** [comment]
Thanks @x8core. Please continue this conversation in a respectful matter. It's free time spend here for all of us, so let's not blame each other when things could be done better.

---

Thanks for the examples @javiereguiluz, I agree we should add that here as well. @x8core are you open to create a PR fixing this?
