### ISSUE TITLE
How to contribute translations

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#14481]
We have a detailed page on how to contribute to the project:

https://symfony.com/doc/3.4/contributing/index.html

However, I think this page is missing a section on how to contribute translations, specificly:

* Where to look for translation files (Form, Security, Validator)
* How to determine which translations are missing.
* How to add them to a translation file.
* We always translate on the oldest LTS branch (currently ~~3.4~~ 4.4)

**Comment by javiereguiluz** [comment]
I'm divided about this. The feature (translate Symfony validation strings) is super niche ... and the dashboard created by @Nyholm already contains the instructions needed to create the PR. I'd say that's enough for now and we shouldn't add anything in the docs.

@symfony/team-symfony-docs do you agree?

**Comment by fabpot** [comment]
I think having short docs about translations would be nice (just mu 2cts of course), and the dashboard could just be a link to the docs (having all docs centralized is nicer I think).

**Comment by Nyholm** [comment]
I created the dashboard. It is just a script (github actions) that uploads the html files on S3. Im happy to move the repository and/or the website under the symfony organisation. 

(If someone thinks that is a better idea)
