### ISSUE TITLE
BrowserKit Component overview page: Errors in list of projects

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#14491]
How/where is https://symfony.com/components/BrowserKit maintained?

There are some errors in the projects list:
* Codeception is missing
* Mentioning "Symfony" is ridiculous ;-)
* Goutte isn't developed anymore (I think)
* These appear twice:
  * Symfony CMF
  * Contao

**Comment by javiereguiluz** [comment]
Hi Thomas,

First, thanks for reporting these errors.

1) The duplicated "CMF" and "Contao" entries is managed by the private source symfony.com, so we've fixed it there and it will be available "soon" after some merge/deploy/cache-busting.
2) I know it's an edge-case, but the Symfony framework is made with Symfony components ... so we prefer to keep it mentioned as one of the "projects using Symfony components".
3) About Codeception, I can't see BrowserKit being required by the main composer.json file of the project (https://github.com/Codeception/Codeception/blob/4.0/composer.json). This is the file we look into, according to https://github.com/symfony/marketing/blob/7fa5b05aeb19c6d0589dd94b13ee6a9ad193e7f5/projects/codeception.yml#L3-L4
4) About Goutte, maybe the project is "feature finished", but it's still being developed. See the activity at https://github.com/FriendsOfPHP/Goutte/commits/master

Given all this, I think we can close this one as "fixed" ... although the symfony.com fix is not visible yet on the production website. Thanks!
