### ISSUE TITLE
Creating applications with multiple kernels is no longer recommended by Symfony. Consider creating multiple small applications instead.

### ISSUE THREAD

**Issue by nivpenso** [symfony/symfony-docs#14592]
Hi,

We are now looking to break our monolith into many apps that live in a mono-repo.

We searched over the internet to see what are the best practices and suggestions for this topic in the context of the Symfony framework. It looks like most article focus on the "Virtual Kernel approach" as discussed [in this StackOverflow thread](https://stackoverflow.com/questions/45925697/more-than-one-application-per-project-repository-with-symfony-4) and also [in this Symfony documentation page](https://symfony.com/doc/current/configuration/multiple_kernels.html)

The approach does look suitable for my needs, but, there is a red note on the Symfony documentation page that says:

![image](https://user-images.githubusercontent.com/1158646/99901252-e22d6900-2cbd-11eb-914c-79dce6504794.png)

_"Creating applications with multiple kernels is no longer recommended by Symfony. Consider creating multiple small applications instead."_

There is not any explanation of why the multiple kernel approach is no longer recommended and either there is no link to achieve the same for with the "Small applications" approach. 

Is there any updated documentation on this topic?

**Comment by javiereguiluz** [comment]
Hi Niv. I'm afraid there's not a better doc about this in Symfony Docs. We probably won't add new docs about this either, because that'd look like a tutorial, and that's out of the scope of Symfony Docs.

I'm sorry for not having a better response.

**Comment by javiereguiluz** [comment]
Closing this old issue for the reasons given above. Sorry!

**Comment by redaLaanait** [comment]
IMO, It would be nice to explain why **the multiple kernel approach is no longer recommended**.

Otherwise, do I have to open a duplicate in the main repo?

**Comment by wouterj** [comment]
There is no benefit (performance or otherwise) and it increases the complexity a lot.
