### ISSUE TITLE
Broken link on symfony.com

### ISSUE THREAD

**Issue by maoschanz** [symfony/symfony-docs#14600]
on this page https://symfony.com/4, this link:

![Capture d’écran de 2020-11-23 16-02-01](https://user-images.githubusercontent.com/19996113/99977935-95bd5880-2da5-11eb-86c6-592c311aa7cf.png)

... leads here https://github.com/symfony/symfony/blob/5.x/UPGRADE-4.0.md, which is a 404

a correct link would be https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.0.md for example

**Comment by javiereguiluz** [comment]
Very good catch! This has been fixed in the private symfony.com repository and it'll be available soon after the next deploy. Thanks Romain!
