### ISSUE TITLE
[PHP8] Annotations vs PHP8 attributes compatibility for routing

### ISSUE THREAD

**Issue by BarthDELUY** [symfony/symfony-docs#14619]
Hi,

I'm setting routes that matches specific HTTP methods.

In the current doc, page https://symfony.com/doc/current/routing.html#matching-http-methods, the example shows how to use annotations to match a specific HTTP Method : 

> `/**
     * @Route("/api/posts/{id}", methods={"GET","HEAD"})
     */`

The method is specified inside braces.

In PHP8 attributes, using braces generates a Syntax Error; the method name has to be specified between square brackets : 

> `#[Route('/contact', name: 'contact', methods: ["GET"])]`

Is it planned to add a "PHP8 Attributes" tab in the doc examples ?

**Comment by wouterj** [comment]
Hi!

PHP8 attributes are only supported from Symfony 5.2 (which will be released next week). You're looking at the "current" version of the docs (5.1). If you switch to the 5.2 version, you'll see the PHP 8 attribute tab: https://symfony.com/doc/5.2/routing.html#matching-http-methods

Therefor, I'm going to close this issue (but feel free to continue commenting if something is unclear for you)
