### ISSUE TITLE
Wrong status for 3.4 LTS version

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony-docs#14616]
I think the release page is currently displaying the wrong status for Symfony 3.4
https://symfony.com/releases & https://symfony.com/releases/3.4

Displayed in yellow for `Security fixes only` but it should be on `Maintained` status until the end of this month.
Next version 3.4.47 will be a bug fixes release https://github.com/symfony/symfony/commits/3.4 and will probably be released soon with Symfony 5.2

**Comment by javiereguiluz** [comment]
Thanks for reporting this. Although you were technically correct when you reported this issue originally, in practice 3.4 version was really finished before the official end date of "the last day of November 2020". In any case, today is the last day of November 2020, so the information is now finally correct and we can close this as "fixed". Thanks!
