### ISSUE TITLE
[DoctrineBridge] uuid_binary type no longer exists.

### ISSUE THREAD

**Issue by AndrolGenhald** [symfony/symfony-docs#14641]
Per https://symfony.com/blog/new-in-symfony-5-2-doctrine-types-for-uuid-and-ulid Symfony 5.2 added `uuid` and `uuid_binary` types, but it looks like `uuid_binary` got removed [here](https://github.com/symfony/symfony/commit/bdfc20520e7055fd5172aa5dcaf2eb27becc0470), and I think it might be selecting binary or character columns depending on database type?

It doesn't look like that blog post is part of this documentation repo, but it should probably still be changed. This repo still references `uuid_binary` [here](https://github.com/symfony/symfony-docs/blob/5127924953e7fad3bf2976a2a83c0067ff8dde11/components/uid.rst).

**Comment by javiereguiluz** [comment]
Fixed in #14707.
