### ISSUE TITLE
[Notifier] Check for maximum number of buttons in slack action block

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14652]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39300
| PR author(s) | @malteschlueter
| Merged in    | 5.3-dev

**Comment by javiereguiluz** [comment]
This is a nice improvement, but there's no need to document it. If developers exceed the limit, they'll see a self-explanatory error message. Thanks!
