### ISSUE TITLE
Where is the legacy Symfony 1.0 reference docs?

### ISSUE THREAD

**Issue by justo-rivera** [symfony/symfony-docs#14666]
Where can we find the legacy Symfony 1.0 reference documents?

Thanks

**Comment by justo-rivera** [comment]
Not this one: https://symfony.com/legacy/doc/reference

The real complete technical reference.

**Comment by xabbuh** [comment]
I don't know which complete technical reference you refer to, but as far as I know there is not more than what you can find on https://symfony.com/legacy/doc.

**Comment by justo-rivera** [comment]
Something like this:
https://reactjs.org/docs/react-api.html

**Comment by justo-rivera** [comment]
> Something like this:
> https://nodejs.org/api/

no wonder symfony is being left behind..

**Comment by wouterj** [comment]
Symfony 1.0 has reached end of life [many many years ago](https://symfony.com/blog/the-end-of-symfony-1). There is no 1.0 online reference doc anymore. Thank you for understanding.

**Comment by justo-rivera** [comment]
Hey @wouterj I am aware of the version i'm "using". I am actually porting it to react + kubernetes.
Such a shame that in the end, no matter if we are talking about 1.0 or 5.1.2 (https://symfony.com/doc/current/reference/)
We developers have to fork the whole source code and dive into it just to Understand how it works.
In short, https://symfony.com/doc/current/reference < https://reactjs.org/docs/react-api.html <<< https://nodejs.org/api/

Hope my feedback is useful to you
