### ISSUE TITLE
[BrowserKit] Allowing body content from GET with a content-type

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#14679]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#38622
| PR author(s) | @thiagomp
| Merged in    | 5.3-dev

**Comment by javiereguiluz** [comment]
I'm closing this without adding any comments for it. We don't mention this as a shortcoming anywhere, so there's no need to explicitly say that this is now possible. Even in the original code PR it was debated whether this is a bug fix or a new feature, and it certainly looks like a bug fix to me. Cheers!
