### ISSUE TITLE
[Profiler] Never enable the profiler in production

### ISSUE THREAD

**Issue by jelen07** [symfony/symfony-docs#14691]
👋 Hi, in profiler documentation, [there is a part](https://github.com/symfony/symfony-docs/blame/eab61bb79767157e6167b381bb8a07b4703c4271/profiler.rst#L5) which says:
>  **Never** enable the profiler in production environments as it will lead to major security vulnerabilities in your project.

And I agree. But in some cases, some members of the development team could profile the application directly on the production/stage when the profiler will be enabled only for specific users.
Is there any security issue having profiler as a non-dev dependency (require section in composer) and disabled for "public" users?
The specific user - who will see the profiler on will be superadmin, accessing from the specific network (IP) and with another extra auth. token?
This topic can be extensive and problematic depending on the project scope. But develop extra profiling tools will be definitely expensive. This is how a non-developer person can profile an application and save developers time.

Of course, processes must be set up so that these situations do not have to happen. But the reality is sometimes different.

Final question - Can the sentence be understood as it is up to the developers how to deal with this in some edge cases?

Kind Regards
Vojtěch

**Comment by javiereguiluz** [comment]
You understood it perfectly: _"never use it in production ... unless you are a very experienced and professional developer who knows how to restrict access to this highly-sensitive information"_. So, if you know how to do that, then you can enable the profiler as you explained.

In any case, we prefer to not change the current wording. We prefer to be over-cautious and only recommend the most safe practice. Advanced developers will understand the message as you did anyways. Thanks!

**Comment by noniagriconomie** [comment]
A recent article was published about this exact usage
https://www.bleepingcomputer.com/news/security/cbs-lastfm-fixes-admin-password-leakage-via-symfony-profiler/
be careful enabling this on produuction :s

**Comment by wouterj** [comment]
Yeah, the main target for our docs (Especially with sensitive things like here) are unexperienced people new to Symfony. All docs recommendations should be read as such. If you know all potential leaks/issues and you know how to work around it, then feel free to completely ignore a recommendation in the docs.

Btw, just to add to all info in this issue: please also be aware of the fact that collecting profiling information makes your environment quite slow and more memory intensive. I would always recommend to invest in more verbose logging and log handling (e.g. ElasticStack or Sentry) than enabling profiling in production.
