### ISSUE TITLE
Assignment in if comparison

### ISSUE THREAD

**Issue by ceochronos** [symfony/symfony-docs#14703]
I was running my project through PHPStan and I came upon this error.

```
 ------ ------------------------------------------------------------------ 
  Line   src/Security/LoginFormAuthenticator.php                           
 ------ ------------------------------------------------------------------ 
  97     Only booleans are allowed in an if condition, string|null given.  
 ------ ------------------------------------------------------------------ 
```

I must admit I copied the code from this doc [form_login_setup.rst](https://github.com/symfony/symfony-docs/blob/5.2/security/form_login_setup.rst#L288)

The code is 

```php
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        if ($targetPath = $this->getTargetPath($request->getSession(), $providerKey)) {
            return new RedirectResponse($targetPath);
        }

        return new RedirectResponse($this->urlGenerator->generate('admin_dashboard'));
    }
```

According to PHPStan an assignment in an if comparison is bad practice. The code should be this way:

```php
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        $targetPath = $this->getTargetPath($request->getSession(), $providerKey);
        if (isset($targetPath)) {
            return new RedirectResponse($targetPath);
        }

        return new RedirectResponse($this->urlGenerator->generate('admin_dashboard'));
    }
```

**Comment by wouterj** [comment]
Hi! I think you misunderstood PHPstan's error. It's not about assignment, it's about type (boolean vs `string|null`). While `null` is falsey, PHPstan strictly wants pure booleans. So you would need to change it to `null !== $targetPath = $this->getTargetPath($request->getSession(), $providerKey)` (or `null !== $targetPath` in your 2nd example, `isset()` is wrong, as it'll always be true as the variable is set one line above it).

In the docs, we follow Symfony's code style conventions. Assignment in if statements (and falsey comparisons for `null`) are quite common in the Symfony code. Also, there are lots of different static analysers and lots of different strictness levels in each of them. It's probably impossible to have code that passes all code.

If you edit the page and change it to `$targetPath = ...; if ($targetPath) {`, I'm happy to merge that change (as it's more readable). However, I'm going to close this issue as-is as the original issue is not going to be fixed here I'm afraid.
