### ISSUE TITLE
[FrameworkBundle] Allow env variables in `json_manifest_path`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14701]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39484
| PR author(s) | @jderusse
| Merged in    | 5.3-dev

**Comment by jderusse** [comment]
not sure, allowing an env variable worth a doc

**Comment by javiereguiluz** [comment]
I agree. If someone needs to use that, they will try to use it straight way. They won't read the docs to see if they are allowed to do that (they'd only read the docs if this didn't work). So, let's close it.
