### ISSUE TITLE
[Serializer] Migrate ArrayDenormalizer to DenormalizerAwareInterface

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14767]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39577
| PR author(s) | @derrabus
| Merged in    | 5.3-dev

**Comment by derrabus** [comment]
The examples in the docs rely on the `Serializer` class to inject itself properly into `ArrayDenormalizer`. This should work as before. I think we can close this ticket.
