### ISSUE TITLE
XML and PHP config not supported by Kernel by default

### ISSUE THREAD

**Issue by WouterCypers** [symfony/symfony-docs#14793]
I stumbled upon this on upgrading the Flex recipe for `symfony/framwork-bundle`. The [docs about Configuring Symfony](https://symfony.com/doc/current/configuration.html) makes it seem like XML and PHP config are supported by default: 
> Symfony lets you choose between YAML, XML and PHP and throughout the Symfony documentation, all configuration examples will be shown in these three formats.

XML and PHP config are not loaded inside the Kernel by default anymore since [this commit](https://github.com/symfony/recipes/commit/5d24d659fc54e2ed564ae93f2f09a2fefe0c850f#diff-95ff278bd0d72a95552f916cfc646898fba8351e801e3860c662d0d745369656) in `symfony/recipes`. It is also not mentioned inside [Configuring in the Kernel](https://symfony.com/doc/current/reference/configuration/kernel.html).

It might be useful to add some lines to the docs because this might be confusing to beginners.

**Comment by javiereguiluz** [comment]
We added a comment about this in the Routing chapter. See https://symfony.com/doc/current/routing.html#creating-routes-in-yaml-xml-or-php-files

But we'll need to add more messages like this ... or revert the code change and support all formats out of the box.

**Comment by WouterCypers** [comment]
Personally, I feel like reverting the changes would save many developers a headache, but I don't really know or understand the reasons behind the simplification so I cannot make an educated argument :)

I'd be happy to try and write some documentation if that is the way to go!
