### ISSUE TITLE
Flex uses unpacking by default

### ISSUE THREAD

**Issue by andrew-demb** [symfony/symfony-docs#14814]
Since https://github.com/symfony/flex/pull/656 unpacking is enabled by default.
To use previous behavior user need explicitly use "--no-unpack".

Reference in doc: https://symfony.com/doc/4.4/setup.html#installing-packages (cannot provide persistent link to line in https://github.com/symfony/symfony-docs/blob/4.4/setup.rst)

**Comment by xabbuh** [comment]
@andrew-demb Thanks for noticing. Would you like to send a PR to change this?

**Comment by andrew-demb** [comment]
No, I can't choose an appropriate alternative description due to lack of language knowledge :(

**Comment by wouterj** [comment]
I would change the whole paragraph to something like:

> You won't see the `symfony/debug-pack` dependency in your `composer.json`, as Flex automatically unpacks the pack. This means that it only adds the real packages as dependencies (e.g. you will see the new `symfony/var-dumper` in `require-dev`). While it is not recommended, you can use the `composer require --no-unpack ...` option to disable unpacking.

Please create a PR - this way we can give credits to you :) We're all non-native english speakers as well, so together we can make something readable :wink:
