### ISSUE TITLE
[Blog]: False warning about unsupported Symfony version on Symfony 5.2 blogposts

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#14813]
Looks like all blogposts about new features in Symfony 5.2 have this yellow warning box:

> Warning: this post is about an unsupported Symfony version. Some of this information may be out of date. Read the most recent Symfony Docs.

Examples:
* https://symfony.com/blog/new-in-symfony-5-2-php-8-attributes
* https://symfony.com/blog/new-in-symfony-5-2-notifier-improvements
* https://symfony.com/blog/new-in-symfony-5-2-semaphore-component
* https://symfony.com/blog/new-in-symfony-5-2-login-links

**Comment by javiereguiluz** [comment]
Yes, sadly we are aware about this. We're working on it in the private symfony.com repo, so I'm closing this. Thanks!
