### ISSUE TITLE
Mention autowiring in an AbstractAuthenticator?

### ISSUE THREAD

**Issue by PaulCombal** [symfony/symfony-docs#14833]
Basically the title.
[On this page](https://symfony.com/doc/current/security/experimental_authenticators.html#security-passports), we can find the following code:

```php
$passport = new Passport(
    new UserBadge($email, function ($userIdentifier) {
        return $this->userRepository->findOneBy(['email' => $userIdentifier]);
    }),
    $credentials
);
```

I had to guess that `$this->userrepository` was obtained by using autowiring, but the page makes no mention of autowiring at all.  Is that by design?
Thank you!

**Comment by xabbuh** [comment]
Can you check if #14849 makes things a bit more clear for you?

**Comment by PaulCombal** [comment]
Thank you, that's exactly what I would have loved to see!
