### ISSUE TITLE
[FrameworkBundle] Add renderForm() helper setting the appropriate HTTP …

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14844]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39843
| PR author(s) | @dunglas
| Merged in    | 5.3-dev

**Comment by chalasr** [comment]
Follow up PR https://github.com/symfony/symfony/pull/40799 needs to be taken into account.

**Comment by lyrixx** [comment]
This can be closed in favor of https://github.com/symfony/symfony-docs/pull/15217
