### ISSUE TITLE
Does DeauthenticatedEvent really performs cleanup tasks when a logout has been triggered?

### ISSUE THREAD

**Issue by udaypt** [symfony/symfony-docs#14846]
Probably I have opened the issue at wrong place here https://github.com/symfony/symfony/issues/39835#issue-786061319

I think this last statement of this documentation is not correct (as per the discussion on the above raised issue thread):
`it can help you doing some clean-up task when a logout has been triggered.`
https://symfony.com/doc/4.4/components/security/authentication.html#security-events

**Comment by YaFou** [comment]
@udaypt, I have proposed a fix here #14852. Can you have a look?

**Comment by OskarStark** [comment]
I merged #14852, feel free to reopen if that does not help, thanks
