### ISSUE TITLE
301 redirection for https://symfony.com/uid is missing

### ISSUE THREAD

**Issue by yoannrenard** [symfony/symfony-docs#14866]
Not sure if it really is relevant or if there is a better place to mention this. 
When I clicked on the UID repository website I got a 404 error page instead of being nicely redirected to https://symfony.com/components/Uid with a 301 redirection as it usually works with the other components.

**Comment by javiereguiluz** [comment]
Yoann thanks for telling us about this. We've just fixed it but we'll need to wait for merge/deploy before seeing it in production. Cheers!
