### ISSUE TITLE
[Semaphore] remove "experimental" status

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#14897]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40028
| PR author(s) | @jderusse
| Merged in    | 5.3-dev

**Comment by javiereguiluz** [comment]
Fixed in https://github.com/symfony/symfony-docs/commit/9d03c8f616eb9b9b473a51c7e8c0647e616a440f

**Comment by jderusse** [comment]
Thanks for taking care of this :heart:
