### ISSUE TITLE
[HttpKernel] Show full URI when route not found

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14931]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39893
| PR author(s) | @ruudk
| Merged in    | 5.3-dev

**Comment by ruudk** [comment]
I searched the docs for `No route found` or `Method Not Allowed` but no matches. So nothing to do here.

**Comment by javiereguiluz** [comment]
@ruudk thanks for checking. Let's close then.
