### ISSUE TITLE
[Routing] don't decode nor double-encode already encoded slashes when g…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#14932]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39732
| PR author(s) | @nicolas-grekas
| Merged in    | 5.3-dev

**Comment by javiereguiluz** [comment]
I'm closing because, even it's nice, this looks more like a bug fix of an edge case. This is not the same as "allowing slashes in route parameters" which was already possible and explained in the routing docs. Thanks.
