### ISSUE TITLE
the doc about configuring  trusted proxies in Symfony 5.2+ is wrong

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#14961]
the doc at https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies shows example using negated values and examples using class constants of `Request` in the semantic config of FrameworkBundle.
This was indeed supported in the initial implementation of the feature, but it was removed before the 5.2.0 release when deprecating the `HEADER_X_FORWARDED_ALL` constant in the component, to keep only the additive way.

**Comment by javiereguiluz** [comment]
I don't know how to update that ... so please, someone submit a PR or tell me the exact changes to do. Thanks!

**Comment by xabbuh** [comment]
see #14964
