### ISSUE TITLE
[Routing] Construct Route annotations using named arguments

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15030]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40266
| PR author(s) | @derrabus
| Merged in    | 5.3-dev

**Comment by derrabus** [comment]
There should be nothing to do here. In the documentation, the `Route` class is used as annotation and attribute. The way to do that has not changed. My PR change the way the constructor has to be called and I haven't found an old-style constructor call in the docs.
