### ISSUE TITLE
[HttpKernel] Handle multi-attribute controller arguments

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#15037]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40307
| PR author(s) | @chalasr
| Merged in    | 5.3-dev

**Comment by javiereguiluz** [comment]
Closing because we don't show `ArgumentInterface` in the docs and, even if we show `ArgumentMetadata`, we don't show the `ArgumentMetadata::getAttribute()` method, so there's nothing to update. Thanks.
