### ISSUE TITLE
[DomCrawler] The doc about adding content in a crawler shows unsupported usages

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#15046]
The doc at https://symfony.com/doc/current/components/dom_crawler.html#adding-the-content shows passing content inside the Crawler constructor and then calling `add*` methods on it. That's not a supported usage of the component.
You cannot mix multiple sources of content in the same Crawler instance. So a supported usage is to use either of the ways to add content, but not multiple ones like in this snippet.

See https://github.com/symfony/symfony/issues/34950 for the original report.

**Comment by javiereguiluz** [comment]
Closing as fixed by #15212.
