### ISSUE TITLE
[Translation] Missing XLIFF documentation on HTML elements

### ISSUE THREAD

**Issue by fayon-safti** [symfony/symfony-docs#15047]
Does Symfony support the `<g>, <x> (v1.2) | <pc>, <mrk>(v2.0)` elements in XLIFF files? If so, how does it work? I tried to use this functionality but it just deleted the <g> elements from the final translation. 

If it is supported, I would be happy to create a PR for documenting it, but I would like to know how it works first 😄
However if this is not supported, what is the recommended alternative for using semantic markup in translations?

Sources: 
XLIFF 1.2 : https://docs.oasis-open.org/xliff/v1.2/xliff-profile-html/xliff-profile-html-1.2-cd02.html
XLIFF 2.0 : http://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html

**Comment by javiereguiluz** [comment]
I'm not sure I fully understand the feature you are describing ... do you mean using any HTML tag inside translation messages in XLIFF files ... or do you mean some special HTML elements defined by XLIFF?

**Comment by javiereguiluz** [comment]
I've reviewed the links you shared ... and I'm afraid we don't support any of those features at all 😞 

If you need to include HTML tags inside translation contents in XLIFF files, please wrap them with `<![CDATA[ ... ]>` and those tags will be preserved. Thanks!
