### ISSUE TITLE
[FrameworkBundle] Add support for doctrine/annotations:1.13 || 2.0

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#15056]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40338
| PR author(s) | @Nyholm
| Merged in    | 5.3-dev

**Comment by Nyholm** [comment]
Im not sure there is anything to document. 

The PR will internally just use PSR-6 cache. We may want to add a note that a custom cache service is deprecated.

**Comment by wouterj** [comment]
I agree with @Nyholm here. Things that are deprecated already document themselves good enough (using PHPdoc and notices), and the changes are all internal.
