### ISSUE TITLE
[FrameworkBundle][Translation] Extract translation IDs from all of src

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15061]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40229
| PR author(s) | @natewiebe13
| Merged in    | 5.3-dev

**Comment by natewiebe13** [comment]
Note: This is what needs to be updated: https://github.com/symfony/symfony-docs/blob/5.x/translation.rst#extracting-translation-contents-and-updating-catalogs-automatically
