### ISSUE TITLE
[Security] Decouple passwords from UserInterface

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15065]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40267
| PR author(s) | @chalasr
| Merged in    | 5.3-dev

**Comment by javiereguiluz** [comment]
I've been looking in the current docs and I don't know where could we add this. We don't even have a single place where we explain the `UserInterface`. Docs related to Security need a total revamp 😢

**Comment by javiereguiluz** [comment]
Closing in favor of #15908, a meta-issue that groups all pending security-related issues so we can easily check them.
