### ISSUE TITLE
[example code] Include path/filename in examples

### ISSUE THREAD

**Issue by excitedbox** [symfony/symfony-docs#15075]
As a newbie going through the Documentation over the last 2 weeks, one of the great features of the documentation that helped me get started was that code examples listed the filename that the code sample belonged in. Many of the examples do not include this though (EasyAdmin bundle) which makes it hard to tell where to put these codes.

Another suggestion would be to add a way to show the code which has been omitted by the //... in an example. In some cases it would help identify if this step is now talking about a new file or if some parts have been removed. (Maybe this could be done with a hover or expanded view so the guide doesn't get too cluttered)

[Crud Menu Item](https://symfony.com/doc/current/bundles/EasyAdminBundle/dashboards.html#crud-menu-item) 
This section for instance shows the beginning of the file down to configuring the menu but does not show which file is being worked on besides "use App\Entity\Category;" and it does not show the "Dashboard::new()" call which causes some confusion since before that the guide mainly shows working on the main dashboard controller.

I think more emphasis on which controllers and namespaces need to be imported, in addition to what file is being worked on, when would clear up this confusion. In some cases more emphasis on which part of a setting or statement is used as the "connection between systems" may also be needed since symfony offers so many options. Especially when commented code is being parsed (or is it?).

I encountered 1 problem where the Dashboard guide says to create 3 controllers but as a newbie I had not yet made any entities or knew to create those which lead to some problems. In addition to my migration metadata now being out of sync and the command to sync it does not work (error: The metadata storage is not up to date). I may have made a manual change somewhere I shouldn't have who knows.

Anyway just some suggestions, hopefully knowing where I get stuck will help. Top-notch work so far. I keep using Symfony as the example of how Open Source documentation should be done since I have found it. I think so far it has been much easier to work with than many less complicated systems.

**Comment by David-Maran** [comment]
For the documentation of EasyAdminBunddle, go to the doc of this bunddle for installation and use. It is located here just for the example of you adapting the code to what you want. for the rest, it's php.

**Comment by javiereguiluz** [comment]
@excitedbox thanks for reporting it and sorry about this issue ... but @David-Baron is right ... this should be fixed in https://github.com/EasyCorp/EasyAdminBundle instead of in this repository. That's why we're closing this. Thanks!
