### ISSUE TITLE
[WebProfilerBundle] Disable CSP if dumper was used

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15092]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40441
| PR author(s) | @monojp
| Merged in    | 5.3-dev

**Comment by herndlm** [comment]
Couldn't find docs that might need adaption and I think this does not need to be added. What do you think?

**Comment by fabpot** [comment]
Thanks for having a look, I agree with you that there is no need to document anything here.
