### ISSUE TITLE
[bundles][best practice] adding entities inside a reusable bundle (when not using annotations)

### ISSUE THREAD

**Issue by Aazhar** [symfony/symfony-docs#15100]
Hello

I would like to have more details about putting entities inside reusable bundles, it is mentioned that it is ok to do so when not using annotations without further comments, could you help me understand a bit this subject, here is the commit : https://github.com/symfony/symfony-docs/commit/87647084dd393df798c9fbd1a414b20ef948f0bd

Best regards

**Comment by johnnypea** [comment]
Have you found what is the meaning of this recommendation? Thanks.

**Comment by alcaeus** [comment]
The motivation behind this is to separate the entity logic from the doctrine-specific logic expressed through entity mappings. Using XML (or YAML while it's still there) allows developers to override these configuration files using standard bundle practices without having to extend the bundle's entity class. This is not possible through annotations (or attributes once ORM 2.9 lands).

**Comment by wouterj** [comment]
On top of @alcaeus' reason, I believe we also recommend not to use annotations at all in third party bundles as it requires depending on `doctrine/annotations` (at the very least). It's often a good idea to reduce the dependencies of shared bundles as much as possible.

**Comment by javiereguiluz** [comment]
We're trying to improve this in #15849. Thanks.

**Comment by tacman** [comment]
@alcaeus do you have any bundles that implement this best practices for an entity?  Also, while the recommendation is for XML, YAML is much easier to read, will creating an entity within a bundle work using YAML?
