### ISSUE TITLE
[Validator] Inline literals for constraint option names?

### ISSUE THREAD

**Issue by henry2778** [symfony/symfony-docs#15134]
Hello. I noticed that the option names in constraint option lists sometimes go with backticks (which is the 'inline literal' thing) and sometimes without. The question is what is the correct way to describe them? I would like to fix it and to ask for the opinions first. It is hard to notice the difference on when you read the docs on the site, but still.  WDYT? Thanks! :)

![image](https://user-images.githubusercontent.com/13105599/111920554-50c9da00-8a98-11eb-8b92-394d19087e37.png)

**Comment by xabbuh** [comment]
In the form type options reference we always use literals. I think we should do the same here.
