### ISSUE TITLE
[Security] Better explain the Remember Me functionality

### ISSUE THREAD

**Issue by whitezo** [symfony/symfony-docs#15133]
Hi,
Working my way through the Symfony 5.2 security documentation and installation process I've found an issue that took me a couple of hours to figure out.

https://symfony.com/doc/current/security/remember_me.html

The remember me functionality described above should mention that for this to work the `LoginFormAuthenticator` (created via `make`) should add a `RememberMeBadge` to the `Passport` in the `authenticate` function.

I've only figured this out after looking at the logs, finding the message saying that remember me was skipped and then searching the source for that message, and what was causing it.

**Comment by javiereguiluz** [comment]
Closing in favor of #15908, a meta-issue that groups all pending security-related issues so we can easily check them.
