### ISSUE TITLE
Some minor design issues with sponsors

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony-docs#15196]
The image is visible though the drop down.

<img width="318" alt="Screenshot 2021-04-07 at 08 32 19" src="https://user-images.githubusercontent.com/1275206/113821044-d679a500-977b-11eb-94dc-07069f3403f9.png">
<img width="297" alt="Screenshot 2021-04-07 at 08 32 15" src="https://user-images.githubusercontent.com/1275206/113821045-d7123b80-977b-11eb-92d4-6e6c246812b7.png">

**Comment by javiereguiluz** [comment]
Thanks for reporting this problem. There were some issues related to these logos in dark mode and we've fixed them. The fix will be visible in production after the merge+deploy.

**Comment by Nyholm** [comment]
Cool cool. 

Thank you very much.
