### ISSUE TITLE
[Console] Deprecate Helper::strlen() for width() and length()

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15213]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40695
| PR author(s) | @Nyholm
| Merged in    | 5.3-dev

**Comment by Nyholm** [comment]
There is no mention of `Helper::strlen()` in the docs. Im not sure this feature is important enough to add to the docs. 

I suggest closing this issue.

**Comment by javiereguiluz** [comment]
Let's close for the reasons given by Tobias. Thanks!
