### ISSUE TITLE
Add docs about framework->http_cache

### ISSUE THREAD

**Issue by alex-bacart** [symfony/symfony-docs#15245]
The Fast Track book mentions a parameter `http_cache` https://symfony.com/doc/current/the-fast-track/en/21-cache.html#activating-the-symfony-http-cache-kernel

But it’s not listed in a Framework Configuration Reference https://symfony.com/doc/current/reference/configuration/framework.html

**Comment by javiereguiluz** [comment]
You are right ... but this will be documented when completing #13881 ... so, we're closing this as a duplicate of it. Thanks!
