### ISSUE TITLE
[Messenger] Ability to distinguish retry and delay actions

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony-docs#15327]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36864
| PR author(s) | @theravel
| Merged in    | 5.3-dev

**Comment by theravel** [comment]
@Nyholm I guess there is nothing to update in documentation. Or what do you think?

**Comment by Nyholm** [comment]
Oh, no. That is right. Because me as an end user will not care. I will just enjoy that it works as expected.
