### ISSUE TITLE
[Translation] Added Crowdin Translation Provider

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15323]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40947
| PR author(s) | @andrii-bodnar
| Merged in    | 5.3-dev

**Comment by welcoMattic** [comment]
It's done in https://github.com/symfony/symfony-docs/pull/15310

**Comment by javiereguiluz** [comment]
Yes, let's close this as fixed! Thanks Mathieu!
