### ISSUE TITLE
Undocumented DI tags

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-docs#15337]
https://symfony.com/doc/5.3/reference/dic_tags.html

at least i found some Messenger related ones in the framework's extension class

**Comment by javiereguiluz** [comment]
Thanks fore reporting this issue.

Do you know if there's some place in Symfony code where these tags are listed? Something like a class with public constants with the tag names?

I know we have `bin/console debug:container --tags` but that shows tags of third-party packages too (we don't want that) and it also misses the tags of all components/bridges/bundles not installed in the app you run the command (we don't want that either).

**Comment by ro0NL** [comment]
https://github.com/symfony/symfony/search?q=findTaggedServiceIds :D when 6.0 is the default branch results should be better, due https://github.com/symfony/symfony/pull/40468

AFAIK it's manual labor

**Comment by ro0NL** [comment]
> AFAIK it's manual labor

closing as such.
