### ISSUE TITLE
[Security] Deprecate the old authentication mechanisms

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15355]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41247
| PR author(s) | @chalasr
| Merged in    | 5.3-dev

**Comment by crtl** [comment]
Docs still link to old guard authenticators too. [Security > Authenticating Your Users > Guard Authenticators](https://symfony.com/doc/current/security.html#guard-authenticators).
Only to then read the note to use the new authentication system instead:
> A new authenticator-based system was introduced in Symfony 5.1, which will eventually replace Guards in Symfony 6.0.

**Comment by javiereguiluz** [comment]
In #15503 we're rewriting the entire docs about Security to use the new authentication system. In #15529 we're adding some additional deprecation notices in Guard authentication docs.
