### ISSUE TITLE
[Security] [RememberMe] Add support for parallel requests doing remembe…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15357]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41175
| PR author(s) | @Seldaek
| Merged in    | 5.3-dev

**Comment by Seldaek** [comment]
To document here would be the new `security -> firewalls -> x -> remember_me -> token_verifier` service id that can be optionally passed to use a custom TokenVerifierInterface service with the remember me functionality, by default though the CacheTokenVerifier should be autoconfigured and work sufficiently for most use cases.

**Comment by javiereguiluz** [comment]
Ping @wouterj to ask if the use case explained by Jordi is common enough to document it in Symfony Docs or we consider it too advanced and therefore we left it undocumented. Thanks!

**Comment by javiereguiluz** [comment]
Closing in favor of #15908, a meta-issue that groups all pending security-related issues so we can easily check them.
