### ISSUE TITLE
[DomCrawler] Add doc about using html5 parser

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/symfony-docs#15356]
There was https://symfony.com/blog/new-in-symfony-4-3-better-html5-parser-for-domcrawler

But nothing was added to https://symfony.com/doc/current/components/dom_crawler.html

Not sure I'll find time to create a PR soon so I create an issue for it, in case of.

**Comment by javiereguiluz** [comment]
Hi Vincent! We documented this in the page that you linked. It's (briefly) mentioned here:

![image](https://user-images.githubusercontent.com/73419/118791507-0f3a8d00-b897-11eb-88b0-2159f473e3fa.png)

**Comment by VincentLanglet** [comment]
Sorry, didn't see it !
