### ISSUE TITLE
[FrameworkBundle] Add autowiring alias for `HttpCache\StoreInterface`

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#15368]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41203
| PR author(s) | @nicolas-grekas
| Merged in    | 5.4

**Comment by javiereguiluz** [comment]
We don't show or explain `HttpCache\StoreInterface` in the docs, so we don't need to document this addition either. Thanks!
