### ISSUE TITLE
UuidV4Generator class not found

### ISSUE THREAD

**Issue by babeuloula** [symfony/symfony-docs#15396]
Hello,

On the documentation for [UID component](https://symfony.com/doc/current/components/uid.html) you use `Symfony\Bridge\Doctrine\IdGenerator\UuidV4Generator` instead of `UuidGenerator`.

**Comment by OskarStark** [comment]
The `*Generator` classes were removed, as this component is experimental, this is not considered a BC break.

However, please head over to the updated current docs: https://symfony.com/doc/current/components/uid.html

You now need to do the following:
```php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;
// ...

class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     */
    private $id;

    public function __construct()
    {
        $this->id = Uuid::v4();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    // ...
}


```

Please close this issue afterwards, thanks

**Comment by javiereguiluz** [comment]
@babeuloula you are right ... sorry for the confusion! There was a problem with the "doc building" process and the 5.3 docs weren't updated with the latest changes. If you visit the same page again: https://symfony.com/doc/current/components/uid.html you'll see that we no longer include that old generator class and we show a code similar to what @OskarStark showed. So, let's close as fixed. Thanks!
