### ISSUE TITLE
Routing with constant

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony-docs#15418]
Now that Symfony is using the Attributes in the controllers, we could indicate as a good practice to indicate all the routes in a separate file.

For instance:

```diff
<?php
// src/Controller/BlogController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
-    #[Route('/blog', name: 'blog_list')]
+    #[Route('/blog', name: \App\ValueObject\Routing\RouteName::BLOG_LIST)]
    public function list()
    {
        // ...
    }
}
```

```php
<?php
// src/ValueObject/Routing/RouteName.php

namespace App\ValueObject\Routing;

final class RouteName
{
    /**
     * @var string
     */
    public const BLOG_LIST = 'blog_list';
}
```

**Comment by javiereguiluz** [comment]
@seb-jean thanks for this proposal! However, I'm not sure this is a wide-spread best-practice.

Also, this would make templates a bit verbose:

```twig
{# before #}
<a href="{{ path('blog_list') }}"> ... </a>

{# after #}
<a href="{{ path(constant('\App\ValueObject\Routing\RouteName::BLOG_LIST')) }}"> ... </a>
```

I'll keep this open to hear other opinions before making a decision. Thanks!

**Comment by OskarStark** [comment]
I would not add this complexity to the docs, also note routing is a very basic one and it should be less complex as possible.

So I vote against merging this PR, sorry

**Comment by javiereguiluz** [comment]
I'm closing this one because it have two -1 votes from the Docs Team. In any case, thanks a lot for sharing this proposal with us and please, keep sharing new ideas to improve things. Cheers!

**Comment by seb-jean** [comment]
Thanks for the answers :smiley:
