### ISSUE TITLE
[Validator] Add support for `ConstraintViolationList::createFromMessage…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15474]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41154
| PR author(s) | @lyrixx
| Merged in    | 5.4

**Comment by javiereguiluz** [comment]
I'm closing this one because in Symfony Docs there isn't a single occurrence of `ConstraintViolationList` creation. We only mention that some Symfony methods return objects like that, but we never create one in any code examples.
