### ISSUE TITLE
[Cache] Remove DoctrineProvider

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#15484]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41976
| PR author(s) | @derrabus
| Merged in    | 6.0

**Comment by derrabus** [comment]
Same as #15483, I guess.

**Comment by chalasr** [comment]
I dunno https://github.com/symfony/symfony-docs/issues/15480 :) The docs team will tell us

**Comment by javiereguiluz** [comment]
Yes, let's close this one as part of #15483. Thanks!
