### ISSUE TITLE
[PasswordHasher][Security] Remove legacy password encoders

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15480]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41960
| PR author(s) | @chalasr
| Merged in    | 6.0

**Comment by javiereguiluz** [comment]
Closing because we already updated the docs to not use any of the deprecated *Encoder features and docs only show *Hasher equivalents, so there's no more changes to do. Thanks.
