### ISSUE TITLE
[Security] Deprecate "always authenticate" and "exception on no token"

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15497]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41965
| PR author(s) | @wouterj
| Merged in    | 5.4

**Comment by kappa1389** [comment]
If token is not provided in request and no access control is defined for called route then firewall gets bypassed, but the expected behavior is to get an authentication exception with code of 401
I face this problem with new symfony security integrated with lexik
Any ideas?
