### ISSUE TITLE
[Cache] Implement psr/cache 3

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#15492]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41290
| PR author(s) | @derrabus
| Merged in    | 6.0

**Comment by javiereguiluz** [comment]
I've looked for occurrences of `Symfony\Contracts\Cache\...` classes in Symfony Docs but we don't have examples where we would have to update code to add return types. So, let's close it. Thanks.
