### ISSUE TITLE
DataTransformer class, function's names inversion

### ISSUE THREAD

**Issue by barbuslex** [symfony/symfony-docs#15494]
Hi,

In documentation here: [https://symfony.com/doc/current/form/data_transformers.html#creating-the-transformer](url)

The function's names and comments are inverted.

transform() convert **a string to an object**.
reverseTransform() **convert an object to string**.

Sincerely

**Comment by xabbuh** [comment]
I am sorry, but I do not really understand what you mean. What makes you think the code should be inverted?

**Comment by javiereguiluz** [comment]
Thanks for suggesting an improvement to the docs. However, I've just checked the code and I agree with Christian. The current comments match the behavior of each method, so let's close this as "won't fix". Thanks!
