### ISSUE TITLE
Improving documentation for translator interface implementations

### ISSUE THREAD

**Issue by elfring** [symfony/symfony-docs#15493]
[The following code example](https://github.com/symfony/symfony-docs/blob/bd6cfa1aafda2cae1e9f76c7bf1350b1d9ca6ec6/translation.rst#basic-translation "Basic translation") is provided.

```php
use Symfony\Contracts\Translation\TranslatorInterface;

public function index(TranslatorInterface $translator)
{
    $translated = $translator->trans('Symfony is great');

    // ...
}
```

I am looking for information sources which explain better where concrete objects would be created for the mentioned translator interface.
:thinking: How do you think about to point any known interface implementations out together with the usual software dependencies?

**Comment by xabbuh** [comment]
I think that's too much detail for the documentation. If you are interested in all the implementation of that interface, using your IDE is a better fit than maintaining a potentially soon out-of-date list of classes in the documentation.

If you want to wire the translator outside of the Symfony framework when using the Translator component standalone, you can take a look at the FrameworkBundle code to see how the services are wired there.

**Comment by elfring** [comment]
>I think that's too much detail for the documentation.

I am trying to present an other view.


>If you want to wire the translator outside of the Symfony framework when using the Translator component standalone, …

I would like to achieve a bit more guidance for constructing an object which should be passed for the shown function parameter.
:thinking: How will the clarification evolve for this use case?

**Comment by elfring** [comment]
Would other contributors like to help any more with the understanding of the required object constructions according to translator interfaces?
