### ISSUE TITLE
[FrameworkBundle] annotations config reference outated

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony-docs#15505]
https://symfony.com/doc/current/reference/configuration/framework.html#annotations is outdated since https://github.com/symfony/symfony/pull/40338.
Using a service id is deprecated. And the possible values and default value is outdated since https://github.com/symfony/symfony/commit/f950a2bcde60dfe528f3621812888617ab6a522e

**Comment by javiereguiluz** [comment]
Closing as hopefully fixed by #15520 and #15521.
