### ISSUE TITLE
[Security] Deprecate `TokenInterface::isAuthenticated()`

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#15513]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#42050
| PR author(s) | @chalasr
| Merged in    | 5.4

**Comment by javiereguiluz** [comment]
Closing because there isn't a single mention to TokenInterface's `isAuthenticated()` method in the entire 5.4 docs (and  we're also revamping security docs in #15503, so we'll take care of this if needed). Thanks!

**Comment by chalasr** [comment]
Thanks for checking, Javier.
