### ISSUE TITLE
current/security/form_login_setup uses deprecated classes

### ISSUE THREAD

**Issue by fmonts** [symfony/symfony-docs#15543]
Symfony 5.3 deprecated the old authenticator system in favor of a new one, which is not well documented anywhere, and no migration guide was provided. 

I think this is quite confusing for the users who are trying to upgrade their applications to SF5.3.

The "How to Build a Login Form" docs have not been updated and are still using old deprecated classes, for example in:

> class LoginFormAuthenticator extends AbstractFormLoginAuthenticator implements PasswordAuthenticatedInterface

https://github.com/symfony/symfony-docs/blob/5.3/security/form_login_setup.rst
https://symfony.com/doc/5.3/security/form_login_setup.html

**Comment by javiereguiluz** [comment]
Francesco, you are right!

These days, our friend @wouterj is rewriting the entire docs about Symfony Security. See #15503. The article about "form login setup" is part of that rewrite, so I'm closing this issue in favor of the Pull Request. It'd be great if you could review that work-in-progress pull request and share your comments if you don't like something of the new docs. Thanks!
