### ISSUE TITLE
[Frontend/Encore] WebpackDevServer 4.0.0-rc.0 renamed the "firewall" option into "allowedHosts"

### ISSUE THREAD

**Issue by emmanuelballery** [symfony/symfony-docs#15542]
When installing `@symfony/webpack-encore` you'll get a front requirement for `webpack-dev-server@^4.0.0-beta.0`. The new `4.0.0-rc.0` release renamed the `firewall` option into `allowedHosts` (and changed the way it's configured)

[See WebpackDevServer Changelog](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#bug-fixes).

[This documentation](https://github.com/symfony/symfony-docs/blob/5.4/frontend/encore/dev-server.rst#cors-issues) is not valid as of `webpack-dev-server@^4.0.0-beta.0`.

```js
Encore
    .configureDevServerOptions(options => {
        options.allowedHosts = 'all';
    });
```

**Comment by javiereguiluz** [comment]
Emmanuel, thanks for reporting this error!

In #15544 we're trying to fix this, but instead of `options.allowedHosts = 'all'`, we're using `options.disableHostCheck = true`. Does that look correct to you? Thanks!

**Comment by emmanuelballery** [comment]
I'm no expert in Webpack but it seems that `disableHostCheck` and `allowedHosts` were removed in [4.0.0-beta.0](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#400-beta0-2020-11-27) in favor of `firewall` then `firewall` was renamed back to `allowedHosts` in [4.0.0-rc.0](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#bug-fixes) ;

All in `^4` version ... a bit of a nightmare.

**Comment by emmanuelballery** [comment]
Also if you take a look at the [PR](https://github.com/webpack/webpack-dev-server/commit/81e4e557a07381980083efdeb99eb26265b38aae) regarding this change, they seem to move to the `options.allowedHosts = 'all';` setting ;

![image](https://user-images.githubusercontent.com/1687685/126354752-5d9f260d-9258-427b-8ff8-0509b2a8f5af.png)

**Comment by javiereguiluz** [comment]
Thanks for checking. This is truly confusing 😓
