### ISSUE TITLE
[Security] Deprecate remaining `LogoutHandlerInterface` implementations

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15569]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#42326
| PR author(s) | @chalasr
| Merged in    | 5.4

**Comment by javiereguiluz** [comment]
Closing because I can't find any occurrences of `CookieClearingLogoutHandler`, `SessionLogoutHandler`, `CsrfTokenClearingLogoutHandler` or `LogoutHandlerInterface`.
