### ISSUE TITLE
Wrong option name in AMQP Transport documentation

### ISSUE THREAD

**Issue by br2c** [symfony/symfony-docs#15566]
There is an option `login`, but it is named `user` in AMQP Transport documentation. See the list of options at https://symfony.com/doc/current/messenger.html#amqp-transport

**Comment by javiereguiluz** [comment]
Thanks for reporting this! I don't know this well so, could you please share a link to some official AMQP resource/doc where we can verify this? Thanks a lot!

**Comment by br2c** [comment]
The AMQP transport uses the AMQP PHP extension to send messages to RabbitMQ queues. `AmqpConnection` from the extension takes `login` option as a username to RabbitMQ server (see constructor of https://github.com/php-amqp/php-amqp/blob/master/stubs/AMQPConnection.php). There is no option `user`.

If I use DSN to configure connection to RabbitMQ, everything works as expected, because the DSN is parsed and the username part of the DSN is used to set `login` option. See line 197 at https://github.com/symfony/amqp-messenger/blob/5.3/Transport/Connection.php. But if I use options way to configure connection to RabbitMQ, I need to pass `login` option, not `user`, as stated in the documentation.

I also noticed a comment on line 131 at https://github.com/symfony/amqp-messenger/blob/5.3/Transport/Connection.php. Maybe the author of this class intended to support both options, aka create an alias `user` for `login` option.

**Comment by javiereguiluz** [comment]
Thanks a lot for providing all these details!

I've looked into the `Connection.php` class that you linked to and it contains this:

```php
if (isset($parsedUrl['user'])) {
    $amqpOptions['login'] = $parsedUrl['user'];
}
```

So, `user` indeed looks like an alias of `login`.

What do you think we should do with the docs? Document both `user` and `login` and say that `login` is preferred? Thanks.

**Comment by br2c** [comment]
`$parsedUrl['user']` is set only when DSN is used to configure connection to RabbitMQ server. If I use no DSN, when `$parsedUrl = [];` (see line 177 at https://github.com/symfony/amqp-messenger/blob/5.3/Transport/Connection.php)
