### ISSUE TITLE
[Security] Missing PHP example of configuration

### ISSUE THREAD

**Issue by tarlepp** [symfony/symfony-docs#15574]
Just noticed that - https://symfony.com/doc/current/security/user_provider.html#chain-user-provider - is missing PHP example of that configuration.

**Comment by javiereguiluz** [comment]
Please note that we're rewriting the Security docs from scratch. The `user_provider` article is gone becuase it's merged on the main `security.rst`. However, in the pending PR, the problem still persists: https://github.com/symfony/symfony-docs/pull/15503/files#diff-304f3325eead17806aec3b66cd4fa6065f83ecca5df0c567c8e1522638a95b02R538

**Comment by tarlepp** [comment]
Oh I didn't know that there is rewriting in process.

**Comment by javiereguiluz** [comment]
Closing in favor of #15908, a meta-issue that groups all pending security-related issues so we can easily check them.

**Comment by javiereguiluz** [comment]
Fixed in #18925.
