### ISSUE TITLE
[Webpack Encore] always show examples with npm

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony-docs#15575]
Is there any reason to favor `yarn` over `npm`command lines in webpack encore documentation?

[Some examples](https://symfony.com/doc/current/frontend/encore/simple-example.html#requiring-javascript-modules) in the documentation are only available with yarn command and [the installation example with npm](https://symfony.com/doc/current/frontend/encore/installation.html) is in the section "for non Symfony applications" so people may think that installing yarn is required when using Symfony.

I dont know if the documentation website supports it for command lines, but I think it could be nice to have all examples in both npm & yarn using the same tab feature we can see on some other pages (to switch between annotations, YAML, XML, ...)

![image](https://user-images.githubusercontent.com/915273/127808197-e9676133-d645-4948-a24f-4c4ea6b41c6f.png)

And maybe display npm by default, because this is the tool required to install. Yarn is optional.

**Comment by javiereguiluz** [comment]
We did that because, after evaluating both tools, we decided that Yarn worked much better (and faster) than npm. But yes, we should display both commands always. So, someone with enough experience in "npm" needs to help us submitting a Pull Request with the needed changes. If there are lots of changes, it's OK to do separate PRs. Also, PRs should be created against 4.4 branch. Thanks!

**Comment by havijs** [comment]
Hi I'm new :D but I'd like to help. Is this format OK?

    $ yarn command

    # if you prefer npm, run:
    $ npm relative command

**Comment by Seb33300** [comment]
I think it's better if we can use tabs but I don't know if this is possible with console code

**Comment by havijs** [comment]
> I think it's better if we can use tabs but I don't know if this is possible with console code

What about something like this?

    .. configuration-block::

        .. code-block:: terminal+yarn
            # yarn command
        .. code-block:: terminal+npm
            # npm command

There is a list of supported formats [here](https://symfony.com/doc/current/contributing/documentation/format.html#configuration-blocks) which I don't know where these markup formats are defined.

**Comment by OskarStark** [comment]
just use terminal for both code blocks
