### ISSUE TITLE
[Validator] Remove internal from `ConstraintViolationAssertion`

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-docs#15573]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#42337
| PR author(s) | @jordisala1991
| Merged in    | 5.4

**Comment by W0rma** [comment]
As far as I can see, `ConstraintViolationAssertion` is currently not mentioned in the docs.

Is this issue about adding a documentation on how to unit test validation constraints similar to the documentation in den form component (https://symfony.com/doc/current/form/unit_testing.html)?

**Comment by javiereguiluz** [comment]
That's correct; `ConstraintViolationAssertion` is not documented, so let's close this. Thanks!
