### ISSUE TITLE
[Lock] Add documentation for `InMemoryStore`

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony-docs#15604]
Hi everyone 👋🏻 

Recently, I've faced some bugs when it comes to `Lock` and during tests, I discovered the `InMemoryStore` (which has been introduced in `5.2`) but didn't found any documentation related to it? 

Could it be a good idea to add some informations about it? 

Thanks again for the feedback and have a great day 🙂

**Comment by javiereguiluz** [comment]
Closing as fixed in #17097.
