### ISSUE TITLE
$request->query->get() can't return array anymore

### ISSUE THREAD

**Issue by ThomasTr** [symfony/symfony-docs#15613]
According to the documentation here:
https://symfony.com/doc/current/components/http_foundation.html#accessing-request-data

```
// the query string is '?foo[bar]=baz'

$request->query->get('foo');
// returns ['bar' => 'baz']
```

$request->query->get() can return arrays, but since pull request [34363](https://github.com/symfony/symfony/pull/34363) arrays are no more supported.

I would like to replace the line 
```
$request->query->get('foo');
````
with
```
$request->query->all()['foo'];
```
to hint how arrays can be accessed.
If it's ok, i can prepare a pull request.

**Comment by javiereguiluz** [comment]
Thomas, thanks for reporting this problem! We've prepared in #15847 a PR to fix it. Please, review if the proposed changes look OK to you. Thanks!

**Comment by ThomasTr** [comment]
Hi Javier, thanks, looks totally fine to me.
