### ISSUE TITLE
Is it worth adding attribute code block examples to doctrine documentation section?

### ISSUE THREAD

**Issue by zspine** [symfony/symfony-docs#15623]
https://symfony.com/doc/current/doctrine.html
https://symfony.com/doc/current/doctrine/associations.html
and many more....

**Comment by OskarStark** [comment]
@symfony/team-symfony-docs  I think that makes sense until PHP 8 is widely adopted

**Comment by zspine** [comment]
@OskarStark I think you are right, ```make:entity``` does not support attributes yet so adding attribute examples may confuse the readers.

**Comment by xabbuh** [comment]
Having code blocks for both annotations and attributes while showing annotations by default sounds reasonable to me.

**Comment by wouterj** [comment]
I agree with @xabbuh. We shouldn't drop the annotation examples, but showing the attributes first will be great. See also how we do this for Symfony's attributes (e.g. https://symfony.com/doc/current/routing ).

**Comment by javiereguiluz** [comment]
It seems that most of us agree, so let's do that:

* Add attribute examples for all current annotation examples
* But DON'T remove annotation examples yet
* And keep annotations as the default format for now

Thanks!
