### ISSUE TITLE
Broken links to a number of bundle documentation sections

### ISSUE THREAD

**Issue by mbabker** [symfony/symfony-docs#15725]
With the launch of the new bundles section, it looks as though some bundles aren't included in the new build and are being redirected to 404s.

Affected bundles (with docs links from Google) include:

- DoctrineBundle (https://symfony.com/doc/current/bundles/DoctrineBundle/index.html)
- DoctrineMongoDBBundle (https://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html)
- FOSRestBundle (https://symfony.com/doc/current/bundles/FOSRestBundle/index.html)

**Comment by wouterj** [comment]
Thank you for the report. We've now implemented the correct redirections for these bundle docs.
