### ISSUE TITLE
Possible Good First Issues

### ISSUE THREAD

**Issue by Asdf0717** [symfony/symfony-docs#15745]
Hello, we are a group of researchers developing machine learning techniques to locate issues suitable for newcomers, and our model considers the following issues as likely "good first issues"

#15728 #15732 #15733 #15735 #15736 

May we recommend you to label them as "good first issue" so newcomers know where to choose? 

Thank you!

**Comment by javiereguiluz** [comment]
Thanks for trying to help ... but sadly this idea didn't gain any traction, so let's close it.
