### ISSUE TITLE
[Ldap] Fixing the behaviour of getting LDAP Attributes

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15750]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41527
| PR author(s) | @mr-sven
| Merged in    | 5.4

**Comment by javiereguiluz** [comment]
I propose to close without adding anything to the docs. The related PR looks like a bug more than a feature. Also, in the current docs we don't say that `memberOf` or other similar attributes don't work, so we don't have to update the docs either.
