### ISSUE TITLE
Broken link to FOSJsRoutingBundle

### ISSUE THREAD

**Issue by jmsche** [symfony/symfony-docs#15752]
Hi,

After the bundles docs redesign, it seems the link to FOSJsRoutingBundle docs is broken: https://symfony.com/doc/master/bundles/FOSJsRoutingBundle/index.html

It's currently [still displayed on the bundle README](https://github.com/FriendsOfSymfony/FOSJsRoutingBundle#documentation) but I created a PR on the bundle repository to fix that.

**Comment by wouterj** [comment]
@fabpot can you please add FOSJsRoutingBundle to the bundle redirection script? (the docs now live in https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/tree/master/Resources/doc )

**Comment by javiereguiluz** [comment]
Thanks for reporting this error. We've fixed this and once the fix is deployed in production, we'll redirect the old doc pages to the given GitHub URL.
