### ISSUE TITLE
Clarify B/C Promise for parameter names on Attributes

### ISSUE THREAD

**Issue by mbabker** [symfony/symfony-docs#15757]
Presently, parameter names are not covered under the B/C promise.  However, it is common practice to use named arguments with attributes, and this is even used in examples for the [routing](https://symfony.com/doc/current/routing.html#creating-routes-as-attributes-or-annotations) and [validation](https://symfony.com/doc/current/reference/constraints/Url.html#message) docs.

Given that the majority of Symfony's attributes are built on top of pre-existing annotations classes that implicitly use named arguments (as they internally use associative array structures) and that changing these names would be a potential B/C break, could I ask that consideration be given to making the argument names for Attribute constructors a part of the B/C promise?

**Comment by nicolas-grekas** [comment]
To me, constructor arguments on attributes should be documented as being covered by the BC promise.

Up for a PR?

**Comment by mbabker** [comment]
See https://github.com/symfony/symfony-docs/pull/15770
