### ISSUE TITLE
You forgot to document how to use a bundle

### ISSUE THREAD

**Issue by ghost** [symfony/symfony-docs#15771]
The https://symfony.com/doc/current/bundles.html doc feels almost as a joke, since it tells how to register a bundle and create a bundle, but not how to use it. I want to use a bundle (JMSSerializerBundle) inside of a controller route. How do I do it?

**Comment by javiereguiluz** [comment]
Each bundle publishes its own dedicated docs explaining all its features.

In your case, you need to look for JMSSerializerBundle docs, which are published here --> http://jmsyst.com/bundles/JMSSerializerBundle

Cheers!
