### ISSUE TITLE
Selection of user interface settings for form data submission

### ISSUE THREAD

**Issue by elfring** [symfony/symfony-docs#15783]
Some information is available in [the software documentation according to the rendering of forms](https://symfony.com/doc/current/forms.html#rendering-forms "Rendering forms with Symfony").
I would expect that such forms need settings for the selection of an user interface element according to the submission of input data. I would look for the specification of submit buttons.

I got the impression that it is not explicitly described so far if an appropriate submit button would be provided by default.
Can corresponding details be clarified better? :thinking:

**Comment by xabbuh** [comment]
Feel free to send a PR with a suggestion.

**Comment by elfring** [comment]
Who does really know how the support for submit buttons should look like by default at the moment?

**Comment by xabbuh** [comment]
closing here as it seems that nobody is interested to work on this
