### ISSUE TITLE
[Runtime] Github symfony/runtime repo "about" links to 404

### ISSUE THREAD

**Issue by wiese** [symfony/symfony-docs#15801]
The github [repository symfony/runtime](https://github.com/symfony/runtime)'s "about" section links to symfony.com/runtime – a URL which gives a 404 for me.

This is probably not right. Maybe it meant to link to the component documentation at https://symfony.com/doc/current/components/runtime.html ?

**Comment by wouterj** [comment]
Hi! Thanks for creating this issue.

The URL seems correct, it's the same format as used by other components. @javiereguiluz is there some misconfiguration for this redirection?

**Comment by wiese** [comment]
Tried this again and it works satisfactorily now.

```
$ curl --head https://symfony.com/runtime
HTTP/2 301 
date: Thu, 16 Sep 2021 13:36:16 GMT
...
location: /components/Runtime
```

Thanks to whoever fixed it.
