### ISSUE TITLE
Weblink: Broken link on the documentation home page

### ISSUE THREAD

**Issue by akiletour** [symfony/symfony-docs#15814]
Hello !

On the symfony.com documentation home page (https://symfony.com/doc/current/index.html), the link to the Weblink page is broken.

https://symfony.com/doc/current/weblink.html

I'm not sure, but I think the correct link should be https://symfony.com/doc/current/web_link.html

<img width="719" alt="Capture d’écran 2021-09-14 à 11 37 52" src="https://user-images.githubusercontent.com/1524422/133234276-8263ca67-dca2-4d4b-b1dd-aa11d33d9a67.png">

**Comment by javiereguiluz** [comment]
Thanks for reporting this error. We've finally fixed it but we need to wait a bit more to be deployed on production. Cheers.
