### ISSUE TITLE
[Form] ChoiceType.choice_loader doesn't accept callable

### ISSUE THREAD

**Issue by benjaminmal** [symfony/symfony-docs#15826]
Maybe I am wrong but the documentation about [ChoiceType#choice-loader](https://symfony.com/doc/current/reference/forms/types/choice.html#choice-loader) says that you can pass a callable to the `choice_loader` option but [ChoiceType::configureOptions()](https://github.com/symfony/symfony/blob/4da88985bc96831ec2f4a167db6b1f3579cad23b/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L405) set `choice_loader` default values to `['null', ChoiceLoaderInterface::class, ChoiceLoader::class]`. It leads to this kind of exception:

> An exception has been thrown during the rendering of a template ("An error has occurred resolving the options of the form "Symfony\Component\Form\Extension\Core\Type\ChoiceType": The option "choice_loader" with value Closure is expected to be of type "null" or "Symfony\Component\Form\ChoiceList\Loader\ChoiceLoaderInterface" or "Symfony\Component\Form\ChoiceList\Factory\Cache\ChoiceLoader", but is of type "Closure"."

You can see it in the example: `'choice_loader' => function (Options $options) {}`

So I think there is an error here :)

**Comment by gnito-org** [comment]
The [documentation](https://symfony.com/doc/current/reference/forms/types/choice.html#choice-loader) says you must code it as follows:

```
'choice_loader' => new CallbackChoiceLoader(function() {}
```
and not like this:
```
'choice_loader' => function (Options $options) {}
```
The closure is a parameter of CallbackChoiceLoader().

Does that resolve your issue?

**Comment by benjaminmal** [comment]
Can you check just below? In the ConstantsType example :)

Here a copy/paste:
```php 
use App\Form\ChoiceList\CustomChoiceLoader;
use App\StaticClass;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConstantsType extends AbstractType
{
    public static function getExtendedTypes(): iterable
    {
        return [ChoiceType::class];
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // the example below will create a CallbackChoiceLoader from the callable
            'choice_loader' => ChoiceList::lazy($this, function() {
                return StaticClass::getConstants();
            }),

            // you can pass your own loader as well, depending on other options
            'some_key' => null,
            'choice_loader' => function (Options $options) { // <-------------------------------- Here
                return ChoiceList::loader(
                    // pass the instance of the type or type extension which is
                    // currently configuring the choice list as first argument
                    $this,
                    // pass the other option to the loader
                    new CustomChoiceLoader($options['some_key']),
                    // ensure the type stores a loader per key
                    // by using the special third argument "$vary"
                    // an array containing anything that "changes" the loader
                    [$options['some_key']]
                );
            },
        ]);
    }
}
```

**Comment by xabbuh** [comment]
@benjaminmal Would you like to send a pull request fixing the code example in the docs?

**Comment by benjaminmal** [comment]
@xabbuh With pleasure but I don't know how to retrieve the `Options` object and use `$options['some_key']` while creating `CustomChoiceLoader`. Do you ?

Or perhaps it's better to remove mention of `Options` here and add a random argument in `$vary` and in the `CustomChoiceLoader` constructor (replacing `$option['some_key']`). WDYT ?

**Comment by xabbuh** [comment]
While re-reading the issue I think I may have understood something wrong. Are you sure that the code example does not work? I mean did you end up with an error or something like that?

The reason I am asking is that the OptionsResolver component allows to pass a callable to any option if you need to read other options' values to calculate the actual value of another option (here the final value of the `choice_loader` option is not a callable but the object returned by `ChoiceList::loader()`).

**Comment by benjaminmal** [comment]
> The reason I am asking is that the OptionsResolver component allows to pass a callable to any option if you need to read other options' values to calculate the actual value of another option (here the final value of the `choice_loader` option is not a callable but the object returned by `ChoiceList::loader()`).

Oh I didn't know that. I guess it is correct then. I tested it within `buildForm()` which lead to the exception in the first comment. 

Sorry for this false-positive and thanks for your work !
