### ISSUE TITLE
[Validator] Add error's uid to `Count` and `Length` constraints with "e…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15834]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43098
| PR author(s) | @VladGapanovich
| Merged in    | 5.4

**Comment by javiereguiluz** [comment]
Closing because we already document the `exactMessage` in Count and Length, so this PR is just an "internal change" which doesn't need to be documented.
