### ISSUE TITLE
[Mailer] Invalid code snippet for creating-sending-messages part

### ISSUE THREAD

**Issue by Fxdpt** [symfony/symfony-docs#15855]
Hello,

I'm implementing the Mailer Component and following the documentation for Symfony 5.3

The following code snippet in https://symfony.com/doc/current/mailer.html#creating-sending-messages

```
        $email = (new Email())
            ->from('hello@example.com')
            ->to('you@example.com')
            //->cc('cc@example.com')
            //->bcc('bcc@example.com')
            //->replyTo('fabien@example.com')
            //->priority(Email::PRIORITY_HIGH)
            ->subject('Time for Symfony Mailer!')
            ->text('Sending emails is fun again!')
            ->html('<p>See Twig integration for better HTML integration!</p>');

        $mailer->send($email);
```

Seems invalid as the `send` method of MailerInterface expects an Instance of `Symfony\Component\Mime\RawMessage` as 1st argument and not `Symfony\Component\Mime\Email` as the documentation mentions it.

**Comment by gnito-org** [comment]
`Symfony\Component\Mime\Email` extends `Symfony\Component\Mime\Message`, which extends `Symfony\Component\Mime\RawMessage`

**Comment by xabbuh** [comment]
I am closing here as the code seems to be correct as explained by @gnito-org.
