### ISSUE TITLE
Broken link to WebLink in overview

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony-docs#15859]
Hi,

on the overview page https://symfony.com/doc/current/index.html the link to WebLink is wrong:

![Capture 2021-09-27_11-17-18](https://user-images.githubusercontent.com/1032411/134880598-d2193eb3-b63c-4c89-b432-44277c0e1b33.png)

The correct link would be `web_link.html` (like in https://symfony.com/doc/current/web_link.html)

Not sure if the link can be changed in this repository (if yes, I can send a PR).

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. We fixed it very recently: see #15814.

There must be some caching issue somewhere. I'll take a look or redeploy the site. Thanks!
