### ISSUE TITLE
[Flex] Serverless private repositories documentation

### ISSUE THREAD

**Issue by gnito-org** [symfony/symfony-docs#15865]
Is anyone working on documentation for using private recipe repositories in the new serveless Flex?

I've just set it up for myself, so I could just document the steps and make a doc PR.

**Comment by xabbuh** [comment]
@gnito-org PR welcome :)

**Comment by gnito-org** [comment]
PR https://github.com/symfony/symfony-docs/pull/15888

**Comment by rogamoore** [comment]
@gnito-org Your docs have been very helpful. Based on your PR I also got it working on Gitlab (self hosted). I would be happy to contribute the relevant steps to the docs. Just ping me, if you are interested.

**Comment by gnito-org** [comment]
@rogamoore Please feel free to add your contribution. Thank you for the feedback.

**Comment by gnito-org** [comment]
@xabbuh The [PR](https://github.com/symfony/symfony-docs/pull/15888) has been sitting in the same state for more than a month. Is anything else required before it can be merged?
