### ISSUE TITLE
[HttpKernel] Add support for configuring log level, and status code by …

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15874]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#42244
| PR author(s) | @lyrixx
| Merged in    | 5.4

**Comment by JohJohan** [comment]
@lyrixx you where planning to pick it up https://github.com/symfony/symfony/pull/42244#issuecomment-930201929? Otherwise i would like to do it if you mention where it should be placed

**Comment by lyrixx** [comment]
I wanted to do it, but if you have time to do it, it would be awesome 😍

However I Don't know where it should be placed

**Comment by JohJohan** [comment]
Yea i checked just now and i also dont know where the best place is to document it. Maybe here https://symfony.com/doc/current/reference/configuration/framework.html?

**Comment by lyrixx** [comment]
It's a good start 👍🏼

**Comment by JohJohan** [comment]
I made a pull request see https://github.com/symfony/symfony-docs/pull/15916
