### ISSUE TITLE
API token used as user identifier in custom authenticator example

### ISSUE THREAD

**Issue by ihmels** [symfony/symfony-docs#15886]
In the example for a custom authenticator, the API key is passed to the `UserBadge` as the user identifier. However, it cannot be assumed that the API key is the same as the user identifier. Doesn't the user identifier have to be determined from the API token and then passed to the `UserBadge`?

https://github.com/symfony/symfony-docs/blob/15084a836fd70e199a6e2a4f1f5de11e40d6e636/security/authenticator_manager.rst#L318-L328

**Comment by javiereguiluz** [comment]
Closing in favor of #15908, a meta-issue that groups all pending security-related issues so we can easily check them.

**Comment by javiereguiluz** [comment]
Fixed in #18928.
