### ISSUE TITLE
Issue with webpack configuration in a VM

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony-docs#15887]
The [following guide](https://symfony.com/doc/current/frontend/encore/virtual-machine.html#allow-external-access) does not work anymore with the latest version of wepback

We have the [same issue](https://github.com/jolicode/docker-starter/issues/157) with our docker starter and I'm not able to fix it

TL;DR: **webpack should bind 0.0.0.0 and expose a custom host**

I'm able to:

* use a custom host (like http://app.vm:8080) and bind `127.0.0.1`
* **OR** bind `0.0.0.0` and expose host `0.0.0.0`

If someone have the solution, it would be super nice!

**Comment by lyrixx** [comment]
Note: I think it's related to https://github.com/webpack/webpack-dev-server/pull/3309
IIRC, I already tried `webSocketURL` option but I did not work (the HTTP resource in the entrypoints.json was 0.0.0.0; may be there is something to fix in encore?)

**Comment by lyrixx** [comment]
I managed to fix it, see https://github.com/jolicode/docker-starter/pull/161

**Comment by javiereguiluz** [comment]
Any expert in Webpack, etc. willing to create a PR to fix the docs about this? Thanks 🙏

**Comment by javiereguiluz** [comment]
Closing as fixed by #16196.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because:

* We haven't received more reports about this
* People can check the fix linked by Grégoire and adapt it to their needs
* Webpack Encore is going to be less and less important now that we have AssetMapper

Thanks

**Comment by lyrixx** [comment]
> * Webpack Encore is going to be less and less important now that we have AssetMapper

Not sure about that :) 

But ok to close this.
