### ISSUE TITLE
[MonologBridge] Deprecate the Swiftmailer handler

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#15896]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43328
| PR author(s) | @fabpot
| Merged in    | 5.4

**Comment by javiereguiluz** [comment]
Closing because we already moved https://symfony.com/doc/current/logging/monolog_email.html from SwiftMailer to Symfony Mailer a while ago.
