### ISSUE TITLE
[Intl] Language code 2B/2T

### ISSUE THREAD

**Issue by SpiGAndromeda** [symfony/symfony-docs#15897]
According to [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-2) there are two sets of 3-letter language codes: 2B and 2T. 

They only differ in a couple of entries. The documentation is missing information which of these sets is used (and I couldn't figure it out in the code either).

**Comment by javiereguiluz** [comment]
Maybe @ro0NL, who knows a lot about this Intl/ICU data, can help us here. Thanks!

**Comment by ro0NL** [comment]
@SpiGAndromeda  AFAIK there are only 2T entries in symfony/intl.

**Comment by ro0NL** [comment]
@javiereguiluz  see also https://github.com/symfony/symfony/blob/61ecf9bf6a934c5df680008daa7b6642742f8bf2/src/Symfony/Component/Intl/Data/Generator/LanguageDataGenerator.php#L188-L202

we only check "overlong", thus skiping "bibliographic" (legacy)

https://github.com/unicode-org/icu/blob/bbd72fb93e03eb3d059a8ac48af8eb25dd866ae2/icu4c/source/data/misc/metadata.txt#L383-L386

i assume all 3-long language codes in https://github.com/unicode-org/icu/blob/b9311e2f547251807c3982e6cb003feec3ba5c83/icu4c/source/data/lang/en.txt#L43 are 2T, unless we find a false positive :)

**Comment by ro0NL** [comment]
one edge case im aware of is [`ase`](https://en.wikipedia.org/wiki/American_Sign_Language) - https://github.com/unicode-org/icu/blob/b9311e2f547251807c3982e6cb003feec3ba5c83/icu4c/source/data/lang/en.txt#L79

which qualifies [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639:a)

**Comment by javiereguiluz** [comment]
Roland, thanks for the detailed info. So, can we say in the docs that we use `2T` ?

**Comment by ro0NL** [comment]
IMO yes

**Comment by SpiGAndromeda** [comment]
@ro0NL I made two Pull Requests to specify the language codes (unfortunatly the Language Constraint was intruduced in 5.1 and not 4.4)

Closed the PR for 5.1 and created one for 5.4

**Comment by ro0NL** [comment]
@SpiGAndromeda very nice, this means any false positive is considered a bug now. Eg. `ase`, we can exclude them in symfony/symfony if you find this relevant :)

**Comment by javiereguiluz** [comment]
Fixed by #15915 and #15913. Thanks!

**Comment by SpiGAndromeda** [comment]
@ro0NL I think we should do this. I will create the necessary PRs, so this can be merged into 5.4, 4.4 and 6.0 before the 5.4/6.0 release.
