### ISSUE TITLE
[MonologBridge] Deprecates ResetLoggersWorkerSubscriber

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#15895]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43322
| PR author(s) | @lyrixx
| Merged in    | 5.4

**Comment by lyrixx** [comment]
It looks like the feature has not been documented. 
https://symfony.com/search?q=ResetLoggersWorkerSubscriber
(and google does not know either the page)

So I guess we can close this issue

**Comment by javiereguiluz** [comment]
That's right. We had this pending to document since #15231. So, let's close this one.
