### ISSUE TITLE
Symfony 6 - php 8

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony-docs#15944]
Hello,

I don't know if it's necessary now but i see lot of page without example use function or method with php 8. 

I think it's a best time to add for each example a new tab for php 8. 

I hope my issue is clear.

**Comment by javiereguiluz** [comment]
Gary, I'm afraid I don't understand your request. In many (all?) places we've added for example PHP 8 attributes to the examples (in addition to the existing annotations). See for example: https://symfony.com/doc/current/routing.html

Please, share a specific example of the change you would like to see in the docs. Thanks.

**Comment by TheGarious** [comment]
For example this page https://symfony.com/doc/6.0/profiler.html

We don't have example with php 8. 

Maybe create a PR with example it's better.

What do you think ?

**Comment by javiereguiluz** [comment]
I still don't understand what are you asking for 😢   so yes, please, create a simple PR with a minimal example of your proposal. Thanks!

**Comment by TheGarious** [comment]
For example : 
``` php
$tokens = $profiler->find('', '', 10, '', '', '');
```

```php
$tokens = $profiler->find(
 ip: '',
 url: '',
 limit: 10,
 method: '',
 start: '',
 end: ''
);
```

What do you think ?

**Comment by javiereguiluz** [comment]
Now I understand the proposal 😊 

I see how this can be super useful in some cases ... but I wouldn't make this change in general because Symfony doesn't guarantee BC of arguments, so this would impose a tremendous maintenance burden on us.

But that's just my opinion. Let's ask to @symfony/team-symfony-docs

**Comment by TheGarious** [comment]
Ok, i need to propose each time an example, sorry for my explication is bad.

**Comment by xabbuh** [comment]
I agree with Javier. Documenting something for which we do not guarantee BC would be a bad sign from my POV.

**Comment by TheGarious** [comment]
Ok, i understand and i think is a bad idea finally :).

Thanks @xabbuh  and @javiereguiluz
