### ISSUE TITLE
Error in a method

### ISSUE THREAD

**Issue by toto33331** [symfony/symfony-docs#15958]
In **Security** chapiter (https://symfony.com/doc/current/security.html) **Registering the User: Hashing Passwords** section, the doc says to use `$passwordHasher->hash();` wich doesn't exist. The method is `$passwordHasher->hashPassword();`

**Comment by JeroenMoonen** [comment]
https://github.com/symfony/symfony-docs/pull/15954

**Comment by javiereguiluz** [comment]
Closing as fixed by #15954. Thanks.
