### ISSUE TITLE
I'm finding the new doc styling more difficult to read

### ISSUE THREAD

**Issue by boite** [symfony/symfony-docs#15978]
The new Symfony doc styling makes the background colour of the code/config samples the same as the body of text. This isn't so bad when reading a doc sequentially from start for finish, but it's really bad when trying to focus on a section of the doc.

As a veteran Symfony user, I often need to refer to the docs.  Usually it's for something "advanced" that one does rarely enough to forget the details.  The new Symfony doc styling makes it much harder to scan the document to find specific information within it.  This is particularly true when looking for specific example code/config sections.

Additionally, the pages do not behave well if you zoom out to get a better view of the page (i.e. hit Ctrl & minus in firefox).

**Comment by Trismegiste** [comment]
I generally like the new design, particularly the new layout, but I have to agree on that : 

> This is particularly true when looking for specific example code/config sections.

Something like this should be better to highlight code sections : 
![image](https://user-images.githubusercontent.com/1260026/138303172-dba23fe9-95a4-4d49-a338-925ce35c0764.png)

**Comment by javiereguiluz** [comment]
Please note that the Docs Team is discussing about this internally. I can't promise anything, but you can rest assured that we're listening to your complaints. Thanks!

**Comment by javiereguiluz** [comment]
We've added some subtle background on code blocks and made other design tweaks. Check out https://symfony.com/doc Closing as fixed then. Thanks.

**Comment by Trismegiste** [comment]
Love it, thank you
