### ISSUE TITLE
Duplicated entry on reference doc "ChoiceType Field (select drop-downs, radio buttons & checkboxes)"

### ISSUE THREAD

**Issue by Trismegiste** [symfony/symfony-docs#15976]
Somehow, the option 'empty_data' is duplicated on https://symfony.com/doc/current/reference/forms/types/choice.html#empty-data

HTH

![image](https://user-images.githubusercontent.com/1260026/138282376-f6dcaa95-2cd6-42d9-bc86-af74e7902467.png)

**Comment by Trismegiste** [comment]
By the way, I've also noted that many links are broken (see picture below)

For example, in the first list, links are like « /doc/current/reference/forms/types/choice.html#empty-data »
In the table, links are « /doc/current/**reference/forms/types/reference/forms/types**/choice.html#empty-data »

« reference/forms/types » is duplicated.

Hope this helps

![bug](https://user-images.githubusercontent.com/1260026/138418118-0f17f321-0a19-4ea3-942b-6318497779c5.png)
:

**Comment by PhilETaylor** [comment]
same issue on https://symfony.com/doc/current/reference/forms/types/entity.html#empty-data

**Comment by javiereguiluz** [comment]
This has been fixed in #16120 ... but it will take some time (up to some hours) until we can see it in production (because we need to wait for the automatic doc rebuild). Thanks!

**Comment by PhilETaylor** [comment]
Thank you.

**Comment by Trismegiste** [comment]
Excellent, thanks to you, @javiereguiluz
