### ISSUE TITLE
Code blocks with "diff" language get no syntax highlighting

### ISSUE THREAD

**Issue by hvt** [symfony/symfony-docs#15984]
Looking at the new docs, I found that code blocks with `diff` as a language, were not syntax highlighted. See https://symfony.com/doc/current/security.html#form-login for example (the third code block showing the `LoginController` diff).

**Comment by javiereguiluz** [comment]
You are right. This was reported before (see https://github.com/symfony/symfony-docs/pull/15963#issuecomment-947907264) and we're working on a fix. Thank you!
