### ISSUE TITLE
[Form] Constraint options links return a 404

### ISSUE THREAD

**Issue by SVillette** [symfony/symfony-docs#15985]
As you can see in the screenshot below, summary links return to `reference/constraints/<constraint>.html#<option>` (in green) but links in table redirect to  `reference/constraints/reference/constraints/<constraint>.html#<option>` (red) so it return a 404.

![Screenshot_20211022_091503](https://user-images.githubusercontent.com/17042730/138413695-10b1ed45-fdd4-4bbf-90d1-55000ffc78ca.png)

**Comment by javiereguiluz** [comment]
Yes, you are right! We're discussing internally in the Symfony Docs Team about the best possible solution to fix this duplication. That's why I'm closing this one as "we are aware and we'll fix it soon". Thanks!
