### ISSUE TITLE
form type constraints Page Not Found

### ISSUE THREAD

**Issue by habibun** [symfony/symfony-docs#15998]
On this page = https://symfony.com/doc/current/reference/forms/types/form.html
when I click constraints redirect =(https://symfony.com/doc/current/reference/forms/types/reference/forms/types/form.html#constraints) 
and showing Page Not Found.

screenshot = https://www.awesomescreenshot.com/image/15554316?key=c840dc6976df0a77a35c6daa09754076

**Comment by javiereguiluz** [comment]
@habibun thanks for reporting this. Sadly we're aware of this bug (it's related to this: https://symfony.com/blog/redesigning-the-symfony-docs-website) but we haven't fixed it yet. We'll ry to do it soon.

**Comment by javiereguiluz** [comment]
This was finally fixed thanks to #16053 If you visit https://symfony.com/doc/current/reference/forms/types/form.html again, all links should work. Thanks!
