### ISSUE TITLE
Wrong line numbers in some article

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#16003]
In this article: https://symfony.com/doc/current/migration.html

At the following section: https://symfony.com/doc/current/migration.html#front-controller-with-legacy-bridge

The text below the first code example refers to some lines (line 15, lines 38-47) which doesn't match the previous example. Which would be the right lines to refer to? Thanks!

**Comment by wouterj** [comment]
They must be +3, so Line 18 and Line 41-50

**Comment by javiereguiluz** [comment]
It's an easy fix then (done in #16007). Thanks!
