### ISSUE TITLE
Customize Voter's "access denied"

### ISSUE THREAD

**Issue by Milana7** [symfony/symfony-docs#16011]
Hello,
I wanna know if there a way to customize the red page "Access Denied" provided by a Voter?
I want to redirect to another page which explained why the access is denied in a friendly way, it is possible?

**Comment by javiereguiluz** [comment]
You can create an event listener or subscriber, then listen to `KernelEvents::EXCEPTION` event and inside your subscriber/listener check if the exception is of type `Symfony\Component\Security\Core\Exception\AccessDeniedException` and then redirect to some page.

See https://symfony.com/doc/current/event_dispatcher.html

-----

As an alternative approach, you can try this too: https://symfony.com/doc/current/controller/error_pages.html

-----

Also, Symfony may add soon a feature to allow voters give a reason why they denied permission. See https://github.com/symfony/symfony/pull/43147

-----

For other support questions, please use https://github.com/symfony/symfony/discussions or the `#support` channel at https://symfony.com/support

**Comment by Milana7** [comment]
Thank you for your answer.
It is possible to do it easier? (I am new in Symfony)

**Comment by Milana7** [comment]
> You can create an event listener or subscriber, then listen to `KernelEvents::EXCEPTION` event and inside your subscriber/listener check if the exception is of type `Symfony\Component\Security\Core\Exception\AccessDeniedException` and then redirect to some page.
> 
> See https://symfony.com/doc/current/event_dispatcher.html
> 
> As an alternative approach, you can try this too: https://symfony.com/doc/current/controller/error_pages.html
> 
> Also, Symfony may add soon a feature to allow voters give a reason why they denied permission. See [symfony/symfony#43147](https://github.com/symfony/symfony/pull/43147)
> 
> For other support questions, please use https://github.com/symfony/symfony/discussions or the `#support` channel at https://symfony.com/support

Thank you for your answer.
It is possible to do it easier? (I am new in Symfony)
