### ISSUE TITLE
Documentations links to wrong code versions

### ISSUE THREAD

**Issue by jdreesen** [symfony/symfony-docs#16014]
No matter which version of the docs I read (e.g. [6.0](https://symfony.com/doc/6.0/components/http_foundation.html#accessing-request-data), [4.2](https://symfony.com/doc/4.2/components/http_foundation.html#accessing-request-data), [3.4](https://symfony.com/doc/3.4/components/http_foundation.html#accessing-request-data)), all of them link to `4.4` version of the code.

![grafik](https://user-images.githubusercontent.com/424602/139081284-9968fe07-160d-4036-ba3e-21418eea3d56.png)

e.g. `all()` links to https://api.symfony.com/4.4/Symfony/Component/HttpFoundation/ParameterBag.html#method_all in all versions of the docs.

**Comment by javiereguiluz** [comment]
Jacob, thanks a lot for reporting this bug! We've fixed it in the private repository of symfony.com source and it'll be on production soon after the fix merge and deploy. So, let's close this one as fixed. Thank you!
