### ISSUE TITLE
[Filesystem] Add third argument `$lockFile` to `Filesystem::appendToFil…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16028]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43796
| PR author(s) | @fwolfsjaeger
| Merged in    | 5.4

**Comment by fwolfsjaeger** [comment]
Should I create an issue in advance next time?

**Comment by nicolas-grekas** [comment]
A PR please :)

**Comment by javiereguiluz** [comment]
Fixed by #16078.
