### ISSUE TITLE
[RateLimiter] Add support for long intervals (months and years)

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16033]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43060
| PR author(s) | @alexandre-daubois
| Merged in    | 5.4

**Comment by javiereguiluz** [comment]
I propose to close this as "won't fix". This is probably a very uncommon case and in the current docs we don't mention that you can only use seconds, minutes and days. Ping @wouterj in case you want to review this decision. Thanks!
