### ISSUE TITLE
Add option to use old design

### ISSUE THREAD

**Issue by fedorenko22116** [symfony/symfony-docs#16051]
Hello, symfony community. I just found out new changes to symfony.com, now it has completely new design and what I am trying to say that it is terrible. Look at this
![image](https://user-images.githubusercontent.com/22433371/139707544-d1ae0150-d35d-49f6-8164-e25e504fbd14.png)
Okay, it's only top of the whole site, lets scroll down and see what we have now
![image](https://user-images.githubusercontent.com/22433371/139708014-a2e34c2b-13cf-4116-a56b-17368ee4720f.png)
Instead of really usefull navigation menu we have 40% of AD + blank space. Why there is someone on Earth decided to put this new design on production? In previous version I was able to understand where am I right now during the reading, now I can see only this AD. And I am not against of AD, this is a business, but at least you could left navigation menu...
Add possibility to switch to the old-style design please!

**Comment by wouterj** [comment]
I'm sorry, but I'm going to close this issue directly.

If you feel like your issue description here is the way to provide helpful feedback to people investing tons of hours of work into this, then I guess you would consider this direct close normal as well.

You may not like some things that changed. I think everyone of us experiences some kind of "resistance to change". But try it out for some time and, if you have things that can be better, share them in a constructive and friendly matter. Thank you.

**Comment by fedorenko22116** [comment]
I agree, it was a little bit to much. Main reason I wrote this issue is lack of navigation menu. So i am kindly sorry for been so rude. I would  happy if you return back it someday.
Thanks in advance.

**Comment by javiereguiluz** [comment]
In any case, it's true that we need to improve the navigation of doc pages. Sadly, it's harder than it looks because Symfony Docs has so many contents. We hope to do it sooner than later. Cheers!

**Comment by fedorenko22116** [comment]
Thanks you. Now it really looks and feels awesome
