### ISSUE TITLE
Bug: Broken link "Read Symfony 5.3.10 Docs" in Symfony Web Toolbar

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#16057]
The line https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/config.html.twig#L84 is creating a link "Read Symfony 5.3.10 Docs" which leads to https://symfony.com/doc/5.3.10/index.html

But this page does not exist :-(

If you tell me where this link is supposed to lead to, I can create a PR for the bundle.

**Comment by noniagriconomie** [comment]
same for v4.4.33, I think we should use only major.minor, cf the version toggle on the top of the doc page

also perhaps it is when the doc pages were redesigned, there was an auto redirect removed from server side?
4.4.X to 4.4, 5.3.Y to 5.3?

**Comment by javiereguiluz** [comment]
This is a bug in the website ... the server should redirect to the appropriate `X.Y` version. Let me check why it doesn't work.

**Comment by javiereguiluz** [comment]
We've just deployed a fix for this bug. Thanks!
