### ISSUE TITLE
[Security] Make the abstract Voter class implement CacheableVoterInterf…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16065]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43898
| PR author(s) | @javiereguiluz
| Merged in    | 5.4

**Comment by zairigimad** [comment]
@javiereguiluz this issue is already documented in https://github.com/symfony/symfony-docs/blob/bf1e1c73e32a90b62bb2a81e2be33d494d554bf5/security/voters.rst , is this issue can be closed?

**Comment by javiereguiluz** [comment]
Imad, you are right! Thanks for checking this.
