### ISSUE TITLE
Problem with anchors

### ISSUE THREAD

**Issue by tony-tran** [symfony/symfony-docs#16096]
Hi,

Some anchor links redirect to a 404 page.

For example in https://symfony.com/doc/4.4/reference/constraints/Image.html, there are anchors : 

- `mimeTypes` redirect to https://symfony.com/doc/4.4/reference/constraints/reference/constraints/Image.html#mimetypes 
- `mimeTypesMessage` redirect to https://symfony.com/doc/4.4/reference/constraints/reference/constraints/Image.html#mimetypesmessage 

There are two times `/reference/constraints` in URL.

I didn't check all constraint pages, but the same issue is on file constraint page.

I can create a PR if we have an idea of the origin of problem.

**Comment by wouterj** [comment]
You are correct. This is a bug in the rst parser that we've recently fixed (ref https://github.com/doctrine/rst-parser/pull/166 ). I expect the symfony.com build process to upgrade to the new version within the next couple days, so I'm going to close this issue. Thank you for reporting so clearly what was wrong! :)

**Comment by javiereguiluz** [comment]
@tony-tran thanks for reporting this error!

@wouterj I'm sorry I didn't fix this earlier ... I've just created a PR to update the RST Parser dependency on symfony.com and Symfony Docs will be fixed after the next doc build. Thanks!
