### ISSUE TITLE
DEFAULT_PLACEHOLDER is not taken into account 

### ISSUE THREAD

**Issue by youssefsaoubou** [symfony/symfony-docs#16093]
DEFAULT_PLACEHOLDER that helps include a part of text in documentation is not taken into account witch result in duplicate menu item and documentation. like here empty_data is duplicated in the menu https://symfony.com/doc/current/reference/forms/types/text.html#empty-data and the content includes placeholder instead of the replaced value.

![image](https://user-images.githubusercontent.com/5830452/141257865-ffab0295-cd91-4e6f-827a-a3b901e401ba.png)

**Comment by xabbuh** [comment]
see #16081, I am going to close here as we already have an open issue for this
