### ISSUE TITLE
Inconsistent dir layout for bundles between pages

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16109]
If I'm not wrong, this page: https://symfony.com/doc/current/bundles/best_practices.html
describe a different diresctory layout than this one: https://symfony.com/doc/current/bundles.html

**Comment by javiereguiluz** [comment]
Nicolas, you are right! Thanks for reporting. However, checking old issues I found #15881, which reports the same problem. So, we're closing this in favor of the other one. Cheers!
