### ISSUE TITLE
Is Node and Yarn needed to install Encore?

### ISSUE THREAD

**Issue by PhoneixS** [symfony/symfony-docs#16119]
In the [guide Install Encore](https://symfony.com/doc/current/frontend/encore/installation.html) apperars the next text:

> First, make sure you `install Node.js`_ and also the `Yarn package manager`_.
> The following instructions depend on whether you are installing Encore in a
> Symfony application or not.

With `and also` it appears to me that you need to install both but I think that you can install Encore with only npm.

Is it correct that you could install it with only npm or do you need to install both?

If you only need one, I think the documentation should be changed to reflect that. Else, I think it should be explained as new users (as me) could be confused by the fact that said `and` but then in the examples said `if you use X do Y`.

**Comment by javiereguiluz** [comment]
You are right. We're improving this in #16123. Thanks!
