### ISSUE TITLE
Use only Symfony binary commands in the Symfony documents

### ISSUE THREAD

**Issue by BahmanMehrdad** [symfony/symfony-docs#16140]
I think it is better to replace all `php bin/console ...` commands in the Symfony documents with `symfony console ...` command.
There are some problems such as [this issue](https://github.com/symfony/symfony/issues/44189) in `php bin/console ...` command, and the advantages of using the Symfony binary is include the automatic execution of `git init` command, using the Symfony local web server for development, and etc.
What is your opinion?

**Comment by javiereguiluz** [comment]
For those using Symfony CLI this would be a bit better ... but for those not using it (which I'd say are still the most Symfony developers) it would be very confusing. You would read the docs, run the suggested commands and nothing would ever work.

So, it's better to keep the current long commands (`php bin/console ...`) which should work for everybody. And for those savvy readers using Symfony CLI, they know there's a shorter/cooler way of executing all commands.

I hope you understand our reasoning for closing this. Thanks!

**Comment by BahmanMehrdad** [comment]
@javiereguiluz I said this mostly because in some documents `php bin/console ...` command is used and in others `symfony console ...` command. This may be a contradiction for beginners and it is better to include one of theme in the whole documents. The Symfony book is also written based on `symfony console ...` command.
Of course, what you said is true and your experience is definitely more ;)
