### ISSUE TITLE
RememberMeBadge in remember Me Functionality 

### ISSUE THREAD

**Issue by avieville** [symfony/symfony-docs#16149]
Hello,

I followed the documentation to set up the remember me functionality and the remember me cookie is not created during authentication if in addition I do not add 'new RememberMeBadge ()' in the authenticate function of the AppCustomAuthenticator .

[](https://symfony.com/doc/current/security/remember_me.html#forcing-the-user-to-re-authenticate-before-accessing-certain-resources)

```php
public function authenticate(Request $request): PassportInterface
{
    $email = $request->request->get('email', '');

    $request->getSession()->set(Security::LAST_USERNAME, $email);

    return new Passport(
        new UserBadge($email),
        new PasswordCredentials($request->request->get('password', '')),
        [
            new CsrfTokenBadge('authenticate', $request->request->get('_csrf_token')),
            new RememberMeBadge()
        ]
    );
}
```
thank you for your feedback and your actions

**Comment by BahmanMehrdad** [comment]
Ask your questions in `Symfony Discussions`
https://github.com/symfony/symfony/discussions

**Comment by OskarStark** [comment]
Is this a question or do you mean some detail is missing in the docs?

**Comment by avieville** [comment]
it is not indicated in the documentation that it is necessary to add the 'new RememberMeBadge ()'

https://symfony.com/doc/current/security/remember_me.html

**Comment by BahmanMehrdad** [comment]
What you say happens when you want to have a custom authentication mechanism.
When you use `form_login` in `security.yaml` configuration file, no need to use `RememberMeBadge` and you just have to use `remember_me` in the firewall
See this link:
https://symfony.com/doc/current/security/custom_authenticator.html#passport-badges

**Comment by avieville** [comment]
@BahmanMD Thank you for this information. I am using a custom authenticator.
I think it would be interesting to add a note for this particular case in the remember me documentation.

**Comment by gnito-org** [comment]
I included a documentation section as suggested in https://github.com/symfony/symfony-docs/pull/16161.
