### ISSUE TITLE
[Website] Introduce top level sections menu in fixed left sidebar to improve global documentation navigability

### ISSUE THREAD

**Issue by tigitz** [symfony/symfony-docs#16171]
As a follow-up of https://github.com/symfony/symfony-docs/issues/16169 that deals with "in page" navigability, docs got a new top level content hierarchy thanks to the redesign (https://symfony.com/doc/current/index.html) that I feel could be reused in a left sidebar to help global documentation navigability. Icons could be even kept in the menu labels.

Many popular project documentations are using this type of navigation, so aside from the actual benefits of helping global navigation, it would feel more intuitive for new developers to be introduced to symfony and explore the documentation.

Live examples:
- https://getbootstrap.com/docs/5.1/getting-started/introduction/
- https://tailwindcss.com/docs
- https://v3.vuejs.org/guide/introduction.html
- https://laravel.com/docs/8.x/installation

Implementation wise, sections defined in the new docs content hierarchy don't cover all the doc pages. I suggest in these cases that all the main section headers would be closed (given they're implemented as a collapsible block like [bootstrap is doing](https://getbootstrap.com/docs/5.1/getting-started/introduction/))

**Comment by tigitz** [comment]
@javiereguiluz I just discovered the recent improvements made on the doc site implementing the main idea of what I've described here. I thought it was ignored since there was no follow-up here but I'm glad it was considered after all.

Is there a way a follow-up could have been done here ? Asking because I think it can be demotivating for issue authors to suggest improvements when there's no feedbacks, not even when someone's suggestion is actually considered and implemented.

**Comment by javiereguiluz** [comment]
Philippe, I'm sorry for not having replied here. The only reason for this is that I get more inputs that I can possibly handle. Sometimes I miss some issues and PRs. This shouldn't have happened with website-related issues in this repository because I regularly check the `website` label here.

So, I apologize for not having handled this issue properly and I hope that you understand that it was only because of a human error. We're looking forward to receive more ideas and proposals from you in the future. Thanks!

**Comment by tigitz** [comment]
@javiereguiluz Sorry you felt the need to be so apologetic, it's totally understandable, you're basically carrying the whole documentation side on your shoulders. 

My only wish was to bring awareness and maybe an improvement could be figured it out. Like a public roadmap of the upcoming documentation site improvements for example, or opening positions to triage and maintain this repo. 

Anyways, thanks for everything you're doing. The Symfony community owes you a lot.
