### ISSUE TITLE
Lock component docs has multiple non-unique permalinks

### ISSUE THREAD

**Issue by jperovic** [symfony/symfony-docs#16170]
When I navigate [The Lock Component](https://symfony.com/doc/current/components/lock.html), within the index, I see:

Available Stores
- FlockStore
- MemcachedStore
- MongoDbStore
- PdoStore
- PostgreSqlStore
- RedisStore
- SemaphoreStore
- etc.

Reliability
- Remote Stores
- Expiring Stores
- FlockStore
- MemcachedStore
- MongoDbStore
- etc.

The problem here is that Permalinks are automatically generated based on a title. For example, FlockStore generates `#flockstore`. This is not unique across the page and clicking on `Reliability > FlockStore` navigates me to `Available Stores > FlockStore`.

I understand this is rather a minor inconvenience, so if you decide not to address it, I am fine :)

I tried playing with markdown, but I don't see a way to force some permalink value...

**Comment by javiereguiluz** [comment]
Jovan, you are right. Sadly this is a known bug of the website/RST-parser. However, we're already tracking the issue in #16067, so we're closing this issue as a duplicate. Thanks!
