### ISSUE TITLE
Broken link on the varnish cache page

### ISSUE THREAD

**Issue by jdreesen** [symfony/symfony-docs#16180]
In `symfony-docs/http_cache/varnish.rst` there's a dead link which points to https://varnish-cache.org/trac/wiki/VCLExampleRemovingSomeCookies but now gets redirected to the Varnish home page.

**Comment by xabbuh** [comment]
Do you have an idea where we could link to instead?

**Comment by jdreesen** [comment]
Not right now, otherwise I would have created a PR ;)

Maybe I'll find something in the next days, as I'm a bit into the varnish topic at the moment.

**Comment by jdreesen** [comment]
There doesn't seem to be a general page about cookies in the varnish docs.

There's for example this outdated one https://varnish-cache.org/docs/3.0/tutorial/cookies.html or this one from varnish plus https://www.varnish-software.com/wiki/content/tutorials/varnish/sample_vclTemplate.html#cookie-manipulation

Since v6.4 the `cookie` vmod is included, so there's this one in newer docs versions: https://varnish-cache.org/docs/7.0/reference/vmod_cookie.html

**Comment by javiereguiluz** [comment]
@jdreesen I liked your last comment suggestion about the new docs, so I created #17007 to update the link. Thanks.

**Comment by javiereguiluz** [comment]
Fixed in #17007.
