### ISSUE TITLE
Add indicator which component is standalone

### ISSUE THREAD

**Issue by erlangparasu** [symfony/symfony-docs#16193]
https://symfony.com/components

Please add indicator which component is **standalone** and which is need symfony **framework**.
Something like 2 column checklist: "Framework" column and "Standalone" column

**Comment by erlangparasu** [comment]
For me, if the docs is contains: `use Symfony\Config\FrameworkConfig;`
for example in: https://symfony.com/doc/current/http_client.html,
i assume that is not a standalone component.

Then i assume these components are standalone:
https://symfony.com/doc/current/components/asset.html
https://symfony.com/doc/current/components/browser_kit.html
https://symfony.com/doc/current/components/cache.html
https://symfony.com/doc/current/components/console.html
https://symfony.com/doc/current/components/contracts.html
https://symfony.com/doc/current/components/css_selector.html
https://symfony.com/doc/current/components/dependency_injection.html
https://symfony.com/doc/current/components/dom_crawler.html
https://symfony.com/doc/current/components/event_dispatcher.html
https://symfony.com/doc/current/components/expression_language.html
https://symfony.com/doc/current/components/filesystem.html
https://symfony.com/doc/current/components/finder.html
https://symfony.com/doc/current/components/form.html
https://symfony.com/doc/current/components/http_foundation.html
https://symfony.com/doc/current/components/http_kernel.html
https://symfony.com/doc/current/components/string.html
https://symfony.com/doc/current/components/intl.html
https://symfony.com/doc/current/components/ldap.html
https://symfony.com/doc/current/components/lock.html
https://symfony.com/doc/current/components/mime.html
https://symfony.com/doc/current/components/options_resolver.html
https://symfony.com/doc/current/components/process.html
https://symfony.com/doc/current/components/property_access.html
https://symfony.com/doc/current/components/property_info.html
https://symfony.com/doc/current/components/string.html
https://symfony.com/doc/current/components/uid.html
https://symfony.com/doc/current/components/var_dumper.html
https://symfony.com/doc/current/components/var_exporter.html
https://symfony.com/doc/current/components/workflow.html
https://symfony.com/doc/current/components/yaml.html

**Comment by mbabker** [comment]
All of the components can be used standalone.  They all also have a configuration in the context of a "full-stack" Symfony application through the FrameworkBundle, any place showing configuration examples assumes this context.

> for example in: https://symfony.com/doc/current/http_client.html, i assume that is not a standalone component.

This is really a bad example for "this is not a standalone component", it has examples for both configuring and use within a Symfony application context as well as for standalone use.

**Comment by erlangparasu** [comment]
@mbabker Thanks for guiding me, I just realized that there is a detail tab for standalone use for http_client component.
How about https://symfony.com/doc/current/components/messenger.html ?

**Comment by javiereguiluz** [comment]
@erlangparasu as @mbabker said, all components are standalone and can be used without using the entire Symfony framework. Some components are trivial to use them stand-alone (e.g. Yaml) and others require some manual work to set things up (e.g. Form).

Please note that we've decided to focus Symfony Docs on using components inside an entire Symfony app. That's why we've removed some stand-alone instructions and we'll remove more in the future. We've added some of those stand-alone instructions/examples in the READMEs of each component repository (see for example: https://github.com/symfony/translation)

That's why we're closing issue as "won't fix". Sorry!
