### ISSUE TITLE
Trouble with render of Symfony Documentation offline

### ISSUE THREAD

**Issue by Krazitchek** [symfony/symfony-docs#16208]
Following mentioned process to build documentation locally i got the output folder with all html files but when opening index.html, or other, left menu and search field are missing. Also, some pages haven't stylesheet. Please, see screenshots as attachments. Previous documentation (docker image) was all OK. 

I'm on Debian 11.1 and PHP 8.1.0, using command **php build.php** to build the documentation, and Firefox 94.0.2 for reading.

Maybe i'm the only one needing offline documentation but i realy have no choice because of no internet connection on developpers computers at work for security reasons, that's how it is !

Here is what i see when viewing compiled documentation.

![Screenshot 2021-12-07 at 07-21-42 Screenshot](https://user-images.githubusercontent.com/11500208/144977621-887cbfd4-bd79-429a-891e-d235cd751f3f.png)

--------------------------------------------------------------------------------------------

![Screenshot 2021-12-07 at 07-22-13 Screenshot](https://user-images.githubusercontent.com/11500208/144977625-e1f6dbee-46a7-4609-afb1-07f21d03be0d.png)

Thanks.

**Comment by almaz-free** [comment]
Yes, php builder not work propertly for me too.
Previously, there was a working Sphinx builder, but they drop it.
Today we do not have a working local offline documentation builder.

**Comment by wouterj** [comment]
Hi!

Yes, the new docs builder indeed seems to have some issues when running locally. More precisely: it's somehow messing up the path to the stylesheets on sub pages (probably some relative paths?).

Unfortunately, building the docs locally is not on our priority list, so I'm going to close this issue. Fortunately however, the new docs builder is written in PHP and available online: https://github.com/symfony-tools/docs-builder/ Feel free to have a look if you can fix the bug :)

**Comment by Krazitchek** [comment]
... answer and way of doing things very disturbing !

**Comment by javiereguiluz** [comment]
@Krazitchek sorry if answer looked disturbing.

What Wouter tried to say is that, although we acknowledge this is a bug, we don't have any resources to fix it anytime soon. Given that almost every Symfony developer uses the online docs and that we ourselves don't use the offline docs except for checking in the RST parsing worked, we consider this a very low priority task to fix. Sorry!

Also, the mention of the open source repository where this project is hosted was more an invitation in case you have time and want to dig into this. But please, don't understand it as a disrespectful answer.

Thanks!
