### ISSUE TITLE
Missing part on testing documentation ?

### ISSUE THREAD

**Issue by partulaj** [symfony/symfony-docs#16213]
Hello,

I just notice two ``:local: :depth: 1`` on the testing documentation page and it's look like there was a intention to had a list or something after but it was forgotten.

**Comment by jdreesen** [comment]
I just noticed this, too. Actually, there's three of them, and they exist in the testing docs only, as it seems.

See #16418 for a PR that removes them.

**Comment by jdreesen** [comment]
It's an upcoming feature, see: https://github.com/symfony/symfony-docs/pull/16418#issuecomment-1018783997

**Comment by partulaj** [comment]
Okay, thank you for the info
