### ISSUE TITLE
How to create a command inline (without creating a Command class)

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony-docs#16214]
For people looking for a micro-framework for cli, the Console component provides a fluent interface to declare commands. I don't find it in the doc.

Example:
```php
$app->register('hello')
    ->addArgument('name', InputArgument::OPTIONAL, '', 'World!')
    ->setCode(function (InputInterface $input, OutputInterface $output): int {
        $output->writeln('Hello, ' . $input->getArgument('name'));
        
        return Command::SUCCESS;
    });
```

This should be pointed in this section of the doc. Maybe with a dedicated page.
https://symfony.com/doc/current/components/console.html#creating-a-console-application

Existing frameworks are good at presenting this feature, but are almost unmaintained ([Silly](https://github.com/mnapoli/silly), [Cylex](https://github.com/Cilex/Cilex)).

(Triggered by https://github.com/brefphp/bref/pull/1117)

**Comment by 94noni** [comment]
@GromNaN can we add it here you think? https://symfony.com/doc/current/components/console/single_command_tool.html
