### ISSUE TITLE
Bundles structure conventions differs

### ISSUE THREAD

**Issue by BafS** [symfony/symfony-docs#16219]
There is 2 pages mentioning the structure bundles should have but the structure is not the same.

- https://symfony.com/doc/current/bundles/best_practices.html#directory-structure
- https://symfony.com/doc/current/bundles.html#bundle-directory-structure

It would be great to have some clarifications about what/when to use, it's not clear to me which one I should use on my app and/or an open source bundle.

**Comment by javiereguiluz** [comment]
@BafS you are right. Thanks for reporting. However, we must close because it's a duplicate of #15881 and #16109.

**Comment by BafS** [comment]
Thank you! Sorry for having open a duplicate 👍

**Comment by javiereguiluz** [comment]
No worries! There are so many open issues that it's hard to find duplicates. Cheers!
