### ISSUE TITLE
"Symfony\Component\BrowserKit\AbstractBrowser" not found when creating client in class extending WebTestCase

### ISSUE THREAD

**Issue by sukhoy94** [symfony/symfony-docs#16210]
Hello, I have such simple code.
```
<?php

declare(strict_types=1);


namespace App\Tests\Security;


use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * @group active 
 */
class SampleTest extends WebTestCase
{
    private KernelBrowser $client;
    
    public function setUp(): void
    {
        $this->client = static::createClient();
    }
    
    public function testSampleTest(): void
    {
        $this->client->request('GET', '/');
    }
}
```

Anyway I'm getting Error: Class "Symfony\Component\BrowserKit\AbstractBrowser" not found

I'm following this instruction https://symfony.com/doc/current/testing.html#write-your-first-application-test.

Any suggestion why I have that error ?

**Comment by sukhoy94** [comment]
Solved by running `composer require symfony/browser-kit`. Can this be adding to documentation ?

**Comment by xabbuh** [comment]
At the beginning of the chapter we have this:

```
composer require --dev phpunit/phpunit symfony/test-pack
```

Did that not install the BrowserKit component for you?

**Comment by sukhoy94** [comment]
@xabbuh ohh okay, didn't saw that.
