### ISSUE TITLE
[Lock] Documentation about PostgreSqlStore and DoctrineDbalPostgreSqlStore is not updated in 6.0

### ISSUE THREAD

**Issue by metaer** [symfony/symfony-docs#16215]
This example is not actual:

```php
$databaseConnectionOrDSN = 'postgresql://myuser:mypassword@localhost:5634/lock';
$store = new PostgreSqlStore($databaseConnectionOrDSN);
```

Correct way is to use `DoctrineDbalPostgreSqlStore` with a string like this `'postgresql://myuser:mypassword@localhost:5634/lock'`

https://symfony.com/doc/current/components/lock.html#postgresqlstore
https://github.com/symfony/symfony/issues/44535#issuecomment-990097084

**Comment by stof** [comment]
note that this applies to 5.4+ rather than 6.0+ (5.4 has a BC layer of course, but the doc should show the non-deprecated way)

**Comment by GromNaN** [comment]
I do it. `PdoStore`/`DoctrineDbalStore` are concerned too.

**Comment by GromNaN** [comment]
Please review: #16217
