### ISSUE TITLE
[Framework] Read env var SYMFONY_IDE by default for framework.ide

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony-docs#16232]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#44575
| PR author(s) | @GromNaN
| Merged in    | 6.1

**Comment by 94noni** [comment]
can be closed ;)

**Comment by javiereguiluz** [comment]
Yes, closed as fixed by #16315. Thanks Antoine!
