### ISSUE TITLE
[Translation] Translatable parameters

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16299]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#44672
| PR author(s) | @sylfabre
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @sylfabre! Thanks for this feature :)
Do you have time to write a small `.. tip::` about this in https://symfony.com/doc/current/translation.html#translatable-objects ?

**Comment by alamirault** [comment]
We can close issue. PR has been merged

**Comment by sylfabre** [comment]
Thank you @alamirault 🙏
