### ISSUE TITLE
Duplicate links in the "Learn more" section of the console component

### ISSUE THREAD

**Issue by shaedrich** [symfony/symfony-docs#16298]
Link: https://symfony.com/doc/current/components/console.html#learn-more

1. There's a duplicate entry (`/components/console/helpers/index`, "The Console Helpers") but it looks like it was added on purpose
2. The link to "The Console Helpers" is somewhat redundant since all the links listed there are also part of the "Learn more" section

<table>
<thead>
<tr>
<th>Code</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr>
<td>

    .. toctree::
        :maxdepth: 1
        :glob:
    
        /console
        /components/console/*
        /components/console/helpers/index
        /console/*
</td>
<td>

# Learn more
*  Console Commands
*  Changing the Default Command
*  Understanding how Console Arguments and Options Are Handled
*  Using Events
*  Cursor Helper
*  Debug Formatter Helper
*  Formatter Helper
*  **The Console Helpers**
*  Process Helper
*  Progress Bar
*  Question Helper
*  Table
*  Using the Logger
*  Building a single Command Application
*  Using Console Commands, Shortcuts and Built-in Commands
*  **The Console Helpers**
*  How to Call Other Commands
*  How to Color and Style the Console Output
*  How to Call a Command from a Controller
*  How to Define Commands as Services
*  How to Hide Console Commands
*  Console Input (Arguments & Options)
*  How to Make Commands Lazily Loaded
*  Prevent Running the Same Console Command Multiple Times
*  How to Style a Console Command
*  Verbosity Levels
</td>
</tr>
</tbody>
</table>

**Comment by javiereguiluz** [comment]
Fixed in #16302. Thanks!

**Comment by shaedrich** [comment]
You're welcome!
