### ISSUE TITLE
Redis Sentinel : add password field for DSN to documentation

### ISSUE THREAD

**Issue by aricci95** [symfony/symfony-docs#16310]
Hi,

It took me 2 days of hard research to figure out how to add the password for the Redis Sentinel DSN, please add this information.

Correct Sentinel DSN with a password should look like this : 
'redis:REDIS_PASSWORD@?host[REDIS_HOST1:REDIS_PORT1]&host[REDIS_HOST2:REDIS_PORT2]&redis_sentinel=SENTINEL_NAME&dbindex=DB_INDEX_NUMBER'

Regards,

Antoine.

**Comment by ToshY** [comment]
I will make a PR for this, as this caused me so much pain when trying to figure it out (in this [discussion](https://github.com/symfony/symfony/discussions/47361)).
