### ISSUE TITLE
Workflow dump images don't match with configuration from workflow docs

### ISSUE THREAD

**Issue by andrew-demb** [symfony/symfony-docs#16324]
Dumped images workflow (https://symfony.com/doc/current/workflow/dumping-workflows.html) differs from configuration in previous docs page about workflow component usage (https://symfony.com/doc/current/workflow.html#creating-a-workflow).

Example difference between PlantUML images:
from docs website ![image_diagram_from_docs](https://user-images.githubusercontent.com/12499813/147335279-4fef9274-22d0-4b71-81f5-0c13d13a51c0.png)

generated from config ![image_diagram_from_config](https://user-images.githubusercontent.com/12499813/147335247-6543319e-512c-4fc2-9f19-703382b3b9d0.png)

Should we sync base workflow configuration and regenerate images to allow matching them by developer with configuration from docs?
Or provide a new workflow config used for generating image in https://symfony.com/doc/current/workflow/dumping-workflows.html ?

**Comment by 94noni** [comment]
Indeed, sometimes there are images/screenshots versioned generated with documentation code that has evolved and not the images/screenshots
I do not know if there is a core process to spot/update them (cc @OskarStark @javiereguiluz)

**Comment by 94noni** [comment]
@andrew-demb I think yes, we should regenerate new images based on changes on the workflow config
do you have the tools locally to do so?

**Comment by andrew-demb** [comment]
@94noni  Yes, I do.

There are generated images from docs config (https://symfony.com/doc/current/workflow.html#creating-a-workflow):

----
1) graphviz dot 
![dot_graph](https://user-images.githubusercontent.com/12499813/182706585-32d19ac6-e8f4-4bf5-819e-795d3c292ebc.png)
----
2) plantuml
![plantuml_graph](https://user-images.githubusercontent.com/12499813/182706667-e9f16207-85a2-4b5f-8a16-fff97401dbab.png)

----
3) mermaid
![mermaid_graph](https://user-images.githubusercontent.com/12499813/182706701-96ba2698-7dfd-4bf1-873f-6e87762ff0f4.png)

**Comment by 94noni** [comment]
May you open a doc PR with those? Could be very valuable to match code and dump images :)

**Comment by andrew-demb** [comment]
@94noni PR landed
