### ISSUE TITLE
A link to AbstractController ends up with invalid certificate

### ISSUE THREAD

**Issue by ProteanCode** [symfony/symfony-docs#16325]
Here: https://symfony.com/doc/current/controller.html
is the link to AbstactController:
https://api.symfony.com/6.0/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.html

it throws privacy error once I open this up

**Comment by OskarStark** [comment]
Thank you, this is a known issue.

We will shutdown api.symfony.com soon am link to Github

**Comment by xabbuh** [comment]
see #16322 for more information
