### ISSUE TITLE
Broken links on the security page (security is written twice)

### ISSUE THREAD

**Issue by CedCannes** [symfony/symfony-docs#16330]
On the page that talks about [security](https://symfony.com/doc/current/security), links to security related pages are broken.
They have the path "security" twice instead of once.
for example : 
[https://symfony.com/doc/current/security/security.html#form-login](https://symfony.com/doc/current/security/security.html#form-login)

[https://symfony.com/doc/current/security/security/passwords.html](https://symfony.com/doc/current/security/security/passwords.html)

It seems that the link to edit the page is broken.

[https://github.com/symfony/symfony-docs/edit/6.0//security/.rst](https://github.com/symfony/symfony-docs/edit/6.0//security/.rst)

**Comment by gnito-org** [comment]
I wonder if something like an extension in your browser is messing with the links you see.

None of the links you mentioned are broken for me at https://symfony.com/doc/current/security.html.

When I do a view source of that page, a search for ``/security/security/`` and ``/security/security.`` finds nothing.

**Comment by javiereguiluz** [comment]
I'm closing this as fixed because I can no longer reproduce it.

Our amazing Docs Team members @wouterj and @weaverryan contributed recently a fix about "references and relative links" in the RST parser that we use to build docs (see https://github.com/doctrine/rst-parser/pull/166) so the issue was probably fixed there.

**Comment by wouterj** [comment]
All credits to @weaverryan for fixing it, I just wrote a failing test :)

However, I recently discovered there is still a broken case: all TOC lists at the bottom of the main guides are broken, e.g. https://symfony.com/doc/current/security/#learn-more
