### ISSUE TITLE
Add `exclude` to `TaggedIterator` and `TaggedLocator`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16339]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#44774
| PR author(s) | @ruudk
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @ruudk. This looks like a useful addition! Are you willing to add a small section describing this new option in https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services ? Thanks!

**Comment by wouterj** [comment]
For reference: Support for `exclude` was also added to Yaml and XML (https://github.com/symfony/symfony-docs/issues/17366).

**Comment by alexandre-daubois** [comment]
I'm on it :+1:

**Comment by rvanlaak** [comment]
I was looking for the documentation on [the great exclusion feature](https://github.com/symfony/symfony/pull/44774), and in the process found the `excludeSelf` argument on the `TaggedIterator`. But, could not find any documentation on it: https://symfony.com/doc/current/service_container/tags.html#reference-tagged-services

Did I miss out on the introduction of `excludeSelf`, or do we possibly still have a TODO somewhere to document that parameter as well?

**Comment by ruudk** [comment]
I found this: https://github.com/symfony/symfony-docs/issues/17656

**Comment by OskarStark** [comment]
@alexandre-daubois do you want to have a look?

**Comment by alexandre-daubois** [comment]
I'll do asap! In order to "finalize" the PR that closed the issue 🙂
