### ISSUE TITLE
[Website] Do not copy $ in terminal bloc example

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/symfony-docs#16413]
Hi,

This is a website issue, perhaps it already has been discussed so feel free to close

Is it possible to only display the `$` sign but not make it copyable when selecting the line?

Ex:

<img width="836" alt="Capture d’écran 2022-01-19 à 09 59 03" src="https://user-images.githubusercontent.com/13205768/150097734-e49c44e8-79aa-48a6-9e0b-1dd2c2f53748.png">

I just want to copy:

`symfony new my_project_directory --webapp`

not

`$ symfony new my_project_directory --webapp`

Thank you!

**Comment by javiereguiluz** [comment]
The current behavior should be exactly what you are asking. I've tried to select the entire text here https://symfony.com/doc/current/setup.html#creating-symfony-applications and I couldn't select the `$` prompts.

If this doesn't work for you, which browser/OS are you using? Thanks!

**Comment by noniagriconomie** [comment]
@javiereguiluz thanks for the reply :)

I am browsing using Safari Version 15.0 (16612.1.29.41.4, 16612) on macOS 11.6

**Comment by javiereguiluz** [comment]
I can confirm in https://caniuse.com/user-select-none that Safari needs the `-webkit-` prefixed property name. We've just fixed this but it will be online after the merge/deploy/cache-expiration. Closing as fixed then. Thanks!

**Comment by 94noni** [comment]
@javiereguiluz it is working well now, thx very much
