### ISSUE TITLE
how can i solve this error

### ISSUE THREAD

**Issue by wnunezc** [symfony/symfony-docs#16435]
how can i solve this error:

![image](https://user-images.githubusercontent.com/1207306/150644036-1aa29c57-edbf-4886-bec1-15ede687302e.png)

https://github.com/symfony/symfony-docs/runs/4907550473?check_suite_focus=true

https://github.com/symfony/symfony-docs/pull/16434/files

**Comment by javiereguiluz** [comment]
@arcanisgk won't worry bout this error. It's unrelated to your contribution, so it doesn't matter. Cheers!
