### ISSUE TITLE
Problem with executing php build.php command

### ISSUE THREAD

**Issue by karaka200** [symfony/symfony-docs#16449]
For build documentation locally, after executing `php build.php` command, the following error is displayed:

```
In FileIncluder.php line 47:

  Include ".. include:: /components/require_autoload.rst.inc" does not exist or is not readable.
```

**Comment by almaz-free** [comment]
same error on windows 10 with php-8.1.2-Win32-vs16-x64.zip
(on linux no error)
In file FileIncluder.php on line 44 variable $path conatin:
"C:\projects\symfony-docs-6.0/components/components/require_autoload.rst.inc"
but real path is
"C:\projects\symfony-docs-6.0\components\require_autoload.rst.inc"

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. I've moved it to https://github.com/symfony-tools/docs-builder/issues/144 because that's the tool that we use to build docs so, if there's a bug, it's in that repository. Thanks!
