### ISSUE TITLE
Remove spaces in Symfony CLI YUM setup instructions

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony-docs#16441]
_(sorry if this is the wrong repo for this issue)_

Currently, the [instructions](https://symfony.com/download) say to do this
```
echo '[symfony-cli]
 name=Symfony CLI
 baseurl=https://repo.symfony.com/yum/
 enabled=1
 gpgcheck=0' | sudo tee /etc/yum.repos.d/symfony-cli.repo
 ```
 
 This produces a file like this:
 
```ini
[symfony-cli]
 name=Symfony CLI
 baseurl=https://repo.symfony.com/yum/
 enabled=1
 gpgcheck=0
```

This does not work (at least with DNF, which deprecated the old YUM), like this

```
Warning: failed loading '/etc/yum.repos.d/symfony-cli.repo', skipping.
Last metadata expiration check: 3:14:41 ago on ponedjeljak, 24. siječnja 2022. 10:44:11 CET.
No match for argument: symfony-cli
Error: Unable to find a match: symfony-cli
```

and it doesn't work until the spaces are removed.

**Comment by wouterj** [comment]
cc @fabpot @javiereguiluz (afaik, the `/download` page text is not public)

**Comment by javiereguiluz** [comment]
We've just deployed a fix to remove the leading white space from the multi-line command that starts with `echo '[symfony-cli]`. I hope everything is fine now. Thanks for reporting this issue!
