### ISSUE TITLE
[Serializer] Add context builders

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#16470]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43973
| PR author(s) | @mtarld
| Merged in    | 6.1

**Comment by nicolas-grekas** [comment]
Friendly ping @mtarld, this really needs doc.

**Comment by mtarld** [comment]
Yes, I'll try to do it ASAP

**Comment by javiereguiluz** [comment]
Closing as fixed by #16591.
