### ISSUE TITLE
Use always a version instead of current in the url of documentation

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#16480]
If somebody copy a symfony docs link into there own documentation or issue. It sometimes happen that that url is maybe not longer available under a new symfony version. Or even is total different to the documentation which the user wanted to linked as the behaviour changed.

So I'm thinking it would be better to always have the version of Symfony in the `url` and not use `/current/` for active version.

So instead of https://symfony.com/doc/current/forms.html I would always go with https://symfony.com/doc/6.0/forms.html. The `current` could still exist as a redirect to the current version but in the browser it would be better have always the number in it so when it is copied it is linking to the version which the link was copied from.

**Comment by javiereguiluz** [comment]
The Symfony Docs Team has a different opinion about this. Including `current` instead of the exact version number allows us to have invariant URLs that always point to the best and most updated docs. This is very important for Google SEO too, because we have a ton of backlinks to the same URLs and those links never get old.

About _"maybe the URL is no longer available"_, we set up URL redirections when we move contents, so please tell us the exact URLs that disappeared because we'll look into them to fix them. Thanks!

Lastly, the good thing about the current URLs is that you can already do what you asked. If you prefer to point to an exact Symfony version, include that in the URL. E.g. `symfony.com/doc/6.0/...`  Then, until 6.1 is release, `6.0` will be redirected to `current` automatically. When 6.1 is released, `6.0` won't be redirected anywhere, so your URL will always work.

I hope you understand why we need to do this. Thanks!

**Comment by alexander-schranz** [comment]
Thank you for your time and detailed answer.

I understand your points and decisions. Still think that Google would be clever enough about handling versions of documentations correctly and backlings would still work via redirect.

It is sometimes just really missleading if a project was created with Symfony 3.4 and was documented using `current` links to the symfony documentation you are reading then the new stuff which don't work in that project.

> we set up URL redirections when we move contents

Oh I see, seems like I did got it false in my mind and you did a lot of improvements here. A big 👍 here for all the effort the symfony docs team did put into this, works really better as sometime ago. I think there is sometimes just not possible to link to the new section like https://symfony.com/doc/current/security/password_migration.html#upgrade-the-password-when-using-a-custom-user-provider links to https://symfony.com/doc/current/security/passwords.html#security-password-migration
instead of https://symfony.com/doc/current/security/passwords.html#upgrade-the-password-when-using-a-custom-user-provider. But I think this is the technical limitation of redirects and anchor links. This is what sometimes confuse about the current urls.

I think the best on my side would be go with a linting task to avoid the current urls. Because it feels for me personally better to be linked to the version which the documentation was created then being linked to a newer version which maybe works differently. Also if somebody needs the newer version symfony docs already shows a nice message on the top if you are on a outdated version. 

Thx again for the quick and detailed response!

**Comment by wouterj** [comment]
> Still think that Google would be clever enough about handling versions of documentations correctly and backlings would still work via redirect.

Unfortunately, Google isn't good with versioned documents. Javier did lots of work on this last year, but Google often favors the old 2.x versions of the docs over the shiny new ones. It's impossible to tell Google: "hey, there is this newer version that you should rank much higher, but still please index the 2.x docs in case someone searches for this specific version". This is why e.g. Read the docs just doesn't let Google index outdated versions of a document.

> But I think this is the technical limitation of redirects and anchor links.

Indeed, the part after `#` isn't even sent to the server so we can't do anything about this (even if we wanted). In general, you might end up in slightly the wrong place, but you should always end up in a real article about that topic and not a 404 page.

**Comment by alexander-schranz** [comment]
@wouterj would be interested providing some information also with version over schema.org json+ld would help here to let google understand the documentation better:

 - https://schema.org/Chapter (a docs page could be seen as chapter I think)
 - https://schema.org/version (a chapter as it is creative work can have a version number)
