### ISSUE TITLE
URGENT: ERR_TOO_MANY_REDIRECTS at https://symfony.com/doc/current/doctrine.html

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#16487]
https://symfony.com/doc/current/doctrine.html

**Comment by javiereguiluz** [comment]
Thanks for reporting. Sadly this is a known problem that we don't know exactly how to solve yet. See https://github.com/symfony/symfony-docs/issues?q=is%3Aissue+ERR_TOO_MANY_REDIRECTS+is%3Aclosed
