### ISSUE TITLE
[ErrorHandler] trigger deprecations for `@final` properties

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16491]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45360
| PR author(s) | @nicolas-grekas, @fancyweb
| Merged in    | 6.1

**Comment by wouterj** [comment]
Closing, the deprecation notice seems to be clear enough. If anything, we shall document this change in a "new in Symfony 6.1" blogs maybe.
