### ISSUE TITLE
[Validator] Deprecate `Constraint::$errorNames` in favor of `Constraint…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16490]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45371
| PR author(s) | @nicolas-grekas
| Merged in    | 6.1

**Comment by javiereguiluz** [comment]
Closing because we don't mention the `$errorNames` property in the docs, so we don't need to fix this. Thanks.
