### ISSUE TITLE
Page redirects to itself

### ISSUE THREAD

**Issue by php4fan** [symfony/symfony-docs#16505]
This page:
https://symfony.com/doc/current/configuration.html
redirects to https://symfony.com/doc/6.0/configuration.html
which in turn seems to redirect to itself, causing "too many redirects" error in the browser.

It is linked from here:
https://symfony.com/doc/current/index.html

![image](https://user-images.githubusercontent.com/13969584/153762221-aace2c61-a754-46dd-9124-fab148fe43ec.png)

**Comment by Asad240** [comment]
![download (3)](https://user-images.githubusercontent.com/99563867/155228624-9921312f-8e95-4fd8-bc46-87aac24fe0d2.png)

**Comment by xabbuh** [comment]
Has this been resolved in the meantime? At least for me there is no redirection (any more).

**Comment by php4fan** [comment]
> Has this been resolved in the meantime?

Yes, it seems so.
