### ISSUE TITLE
bug(yaml): DUMP_BASE64_BINARY_DATA not available

### ISSUE THREAD

**Issue by Guikingone** [symfony/symfony-docs#16508]
Hi 👋🏻 

Small question about the `3.4` version of the documentation related to the `YAML` component, it seems that the doc highlight the fact that since `3.2` (the doc only display the information since `3.4`: https://symfony.com/doc/3.4/components/yaml.html#parsing-and-dumping-of-binary-data) , we can dump / parse binaries data thanks to `Yaml::DUMP_BASE64_BINARY_DATA` const.

Problem is, after checking the source code, it seems that this const does not exist: https://github.com/symfony/symfony/blob/3.2/src/Symfony/Component/Yaml/Yaml.php.

Am I missing something or is there a missing link / const / code block? 

Thanks 🙂

**Comment by xabbuh** [comment]
That's a mistake in the documentation. The documented flag has never been released (see symfony/symfony#18294). I have opened #16526 to fix this.
