### ISSUE TITLE
Can't close the stupid search box

### ISSUE THREAD

**Issue by php4fan** [symfony/symfony-docs#16504]
Steps to reproduce:
----

1. Go to any docs page, e.g. https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
2. Enter something in the search input box on the top left, e.g. the string "services.prod.yaml" (I'm not sure why, this returns a single search result which is the very page we navigated to at step 1, despite the fact that it does not contain the searched-for string, but that's good for our example).
3. Let's consider only the following cases: (A) none of the results is of your interest or your curiosity has vanished and you just want to cancel searching and go on reading, or (B) you click on one of the search results which points right to the very page you are already reading (possibly a specific anchor in it), so you say "Oh great, what I'm looking for is right here, let's just keep reading".

Expected behavior
-----
I should be able to close the search results popup and keep reading.
I usually expect ALL of the following actions to always close any popup:
- clicking on an "X" close button if there is any (there's none here)
- click outside of the box
- hitting the Esc key

Observed result
----
NONE of the above closes the popup with the search results.
The ONLY way to make the popup go away is to delete all input from the search box, which is neither intuitive nor common nor easy to discover. Normally I will first hit the Esc key repeatedly, then start clicking outside nervously, and then start screaming in rage before I figure out I need to delete the search query.

**Comment by javiereguiluz** [comment]
The search box has been updated. You can now close it with (1) `Esc`, (2) clicking anywhere on the page; (3) clicking on the `x` at the right of the input search.
