### ISSUE TITLE
What is the alternative of setEncoder? 

### ISSUE THREAD

**Issue by darkcavalry** [symfony/symfony-docs#16509]
Hello,

I have completely examined the mailer document and source codes, but I could not find where to use the Symfony\Component\Mime\Encoder\Base64Encoder() part.

in old version we can do like;

```
$encoder = \Swift_DependencyContainer::getInstance()->lookup('mime.base64contentencoder');
$message->setEncoder($encoder);
```

but I cant use this one;

`$encoder = new Base64Encoder();`

Where can I put that $encoder variable in message?

Regards.

**Comment by javiereguiluz** [comment]
We're sorry you didn't get any response. Please try it in:

(1) Symfony Discussions: https://github.com/symfony/symfony/discussions
(2) Symfony Slack: https://symfony.com/slack and select the `#support` channel

If after getting some support there's something wrong or missing in the docs, please create a new issue with the details and we'll try to fix it. Thanks.
