### ISSUE TITLE
Psr7ServerRequestResolver is missing

### ISSUE THREAD

**Issue by gnumoksha** [symfony/symfony-docs#16514]
[docs](https://symfony.com/doc/current/controller/argument_value_resolver.html) says the `Psr7ServerRequestResolver` can be found by installing the SensioFrameworkExtraBundle, but the class does not exist.

related to https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/767

**Comment by derrabus** [comment]
Thank you for your report. The page should mention the PSR HTTP Message Bridge instead and link to https://symfony.com/doc/current/components/psr7.html.
