### ISSUE TITLE
Translation support in Twig Bridge

### ISSUE THREAD

**Issue by withinboredom** [symfony/symfony-docs#16536]
Hi, some of us using poedit to parse twig files for translations and are having trouble identifying how plurals work. Is there any chance someone could help us out over in https://github.com/vslavik/poedit/issues/736?

**Comment by xabbuh** [comment]
closing here as I don't see how this is related to the Symfony documentation

**Comment by vslavik** [comment]
Well, the Symfony documentation is insufficient. Literally the *entire* extent of its description of the non-MessageFormat plurals format is [this](https://symfony.com/doc/5.4/translation.html#message-format):

> The message variable must include all the different versions of this message based on the value of the count parameter. For example:
>  `{0}%name% has no apples|{1}%name% has one apple|]1,Inf[ %name% has %count% apples`

I.e. *one* ambiguous example.

For example, what about languages that have a different form for n=2 or 3 or 4? What about languages that have a different form for n=x modulo 10? That's, for example, Czech:

n=1: 1 jablko
n=2,3,4: %count% jablka
n=5,6,7,8,9,10,11,...,20: %count% jablek
n=21: %count% jablko (i.e. same as with n=1)
n=22: %count% jablka (i.e. same as with n=2)

That one limited English-centric example is nowhere near sufficient to understand how to properly handle plurals (which vanilla Twig had no trouble with).

**Comment by wouterj** [comment]
I would not recommend using non-ICU MessageFormat in new applications. If you're working on an older application, you can use an older version of the documentation: https://symfony.com/doc/3.4/translation.html#pluralization
