### ISSUE TITLE
[HttpKernel] Add the UidValueResolver argument value resolver

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16542]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#44665
| PR author(s) | @fancyweb
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @fancyweb! Do you have time to add this new resolver to https://symfony.com/doc/6.1/controller/argument_value_resolver.html ?

**Comment by javiereguiluz** [comment]
Fixed in #17068.
