### ISSUE TITLE
 [Translation] Add the possibilty to export xliff translation with the …

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16547]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45421
| PR author(s) | @DanielBadura
| Merged in    | 6.1

**Comment by javiereguiluz** [comment]
Looking at code PR I'm no entirely sure how does it affect to docs. Anyone can help me here? Thanks!

**Comment by mdoutreluingne** [comment]
This PR does not affect the documentation. It says it supports a new suffix (.xliff) for XLIFF translation files to facilitate the use of external services.

Looking more closely at the documentation, I noticed that we don't mention the different possible suffixes for YAML (.yml) and XLIFF (.xliff, the new suffix of this PR). Is there a reason?

I think it would be interesting to add them, [here](https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations) (in the part "Symfony provides many loaders:"), to facilitate the user, without the need to enter the command: `php bin/console translation:extract --force fr --format=` to see all formats supported by Symfony.

What do you think?

**Comment by javiereguiluz** [comment]
@mdoutreluingne thanks a lot for the insights! I've created #16693 to do the change that you proposed and other minor improvements. Cheers!

**Comment by javiereguiluz** [comment]
Closing as fixed by #16693.
