### ISSUE TITLE
Vertical right scrollbar is not synchronized with documentation content

### ISSUE THREAD

**Issue by fabienlem** [symfony/symfony-docs#16567]
Hello,

I noticed the scrollbar is not usable to browse the documentation. (Chrome windows and debian). It's not convenient.

![docs](https://user-images.githubusercontent.com/19775001/156783479-20bd79e4-a5ce-47ab-8b49-d8740e99155b.png)

Thank you.

**Comment by javiereguiluz** [comment]
Fabien, thanks for reporting this error. We've just deployed some fixes, so it will be hopefully fixed by now. Cheers!

**Comment by fabienlem** [comment]
Indeed it works again. Thank you for your reply.
