### ISSUE TITLE
[Validator] Deprecate constraint "ExpressionLanguageSyntax", use "Expre…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16566]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45623
| PR author(s) | @mpiot
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @mplot. Thanks for working on this Symfony feature. With the 6.1 release coming closer, are you willing to update the docs for this change?

I think it boils down to almost copy-pasting https://symfony.com/doc/current/reference/constraints/ExpressionLanguageSyntax.html and adding a `.. deprecation:: 6.1` box in the old constraint? (similar to what I did in https://github.com/symfony/symfony-docs/pull/16784 )

**Comment by mpiot** [comment]
@wouterj I've try a way:
 - Add a link to the new ExpressionSyntax (copy/paste the old one)
 - Add (deprecated) after the ExpressionLanguageSyntax (to not miss the old one)
 - Add a message on the old ExpressionLanguageSyntax page
 
 The other way is to delete the old, but it seems more difficult to retrieve the previous have informations about the change.

**Comment by javiereguiluz** [comment]
Closing as fixed in #16786.
