### ISSUE TITLE
[Routing] Avoid double encoded slashes in query parameters

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16578]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45658
| PR author(s) | @usu
| Merged in    | 6.1

**Comment by javiereguiluz** [comment]
Closing because this looks more like a bug fix. The PR changes are the expected behavior anyway and we don't document anything about the previous behavior. Thanks!
