### ISSUE TITLE
[PropertyInfo] Add PHP 8.0 promoted properties @param mutation support …

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16571]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45062
| PR author(s) | @raphaelvoisin
| Merged in    | 6.1

**Comment by wouterj** [comment]
Nice feature (I was actually wondering if `@param` worked), but I think we don't need to document this (it "just works").
