### ISSUE TITLE
[Messenger] add TransportMessageIdStamp to RedisSender

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16570]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#44522
| PR author(s) | @GaryPEGEOT
| Merged in    | 6.1

**Comment by wouterj** [comment]
I'm not fully up to speed with Messenger internals, but I feel like there is no need to explicitly document this feature. If I'm correct, please open a pull request with your proposal :)
