### ISSUE TITLE
Need print friendly CSS pour Symfony doc

### ISSUE THREAD

**Issue by diam** [symfony/symfony-docs#16588]
Bonjour,

I often need to read (i.e. learn) Symfony documentation offline. For that, I regularly "print" some sections or chapters (e.g. Security, ...) in a pdf file to read them on my phone. Other times, I print these pdf on real paper to read it on public transportation.

But the Symfony website is not really designed for this use case and many secondary parts of the page (header, footer, and especially left and right border) make the generated PDF very bad (and the html too).

Is it possible to add a CSS with a "print" icon to make a "print friendy" view of the Symfony documentation?

I guess the same technique used by the "Symfony: The Fast Track" book could be used for the official documentation?

Sincerely,
-- Maurice

**Comment by javiereguiluz** [comment]
We've just deployed some changes to add a printer-friendly CSS, so you can now print doc pages and all their contents will be visible. Cheers!

**Comment by diam** [comment]
Thank you very much!
-- Maurice
