### ISSUE TITLE
[BrowserKit] Add `toArray` to `Response`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16580]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45515
| PR author(s) | @HypeMC
| Merged in    | 6.1

**Comment by javiereguiluz** [comment]
I've looked into this and I don't know where to add this new method. The most appropriate article would be `components/browser_kit.rst` but I don't know exactly where. Thanks.
