### ISSUE TITLE
 Documentation about the &dev and *dev syntax in configuration files

### ISSUE THREAD

**Issue by alexandre-le-borgne** [symfony/symfony-docs#16583]
![image](https://user-images.githubusercontent.com/10196942/157408828-d6d640dd-6c93-42ea-8e20-b4cda03a72bf.png)

Hello, could you tell me where is the documentation about the &dev and *dev syntax?

I'm using symfony 5.4

I have already searched in :
https://symfony.com/blog/new-in-symfony-5-3-configure-multiple-environments-in-a-single-file
https://symfony.com/doc/5.4/configuration.html#configuration-parameters
https://symfony.com/doc/5.4/components/yaml/yaml_format.html
https://www.online-fortune-telling.com/
and others

**Comment by apfelbox** [comment]
That's a feature from YAML itself, not symfony: https://yaml.org/spec/1.2.2/#692-node-anchors

If you search for "yaml anchors", there you will find a lot of blog articles talking about it.

**Comment by alexandre-le-borgne** [comment]
Thanks
I think an example/reference would not be too much in at least
https://symfony.com/doc/5.4/components/yaml/yaml_format.html
and others documentation as a way to factorize its configuration (best practice)
