### ISSUE TITLE
[HttpClient][WebProfilerBundle] Add button to copy a request as a cURL …

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16581]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43931
| PR author(s) | @Deuchnord
| Merged in    | 6.1

**Comment by javiereguiluz** [comment]
This is a very nice feature ... but we don't need to document it explicitly because users can discover it when using Symfony Profiler.
