### ISSUE TITLE
Better document `EnumType` with `multiple`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#16594]
@derrabus Am I right that connecting an `EnumType` form field with `multiple` to an entity is not straightforward?
Since you can't define an *array of enums* in the entity, the field looks something like this:
```php
#[ORM\Column(type: Types::SIMPLE_ARRAY)]
private array $features = [];
```
But in order to hydrate the array items as enum (not as string), you need a DataTransformer on the form field, right?

What do you think about adding a full example at https://symfony.com/doc/current/reference/forms/types/enum.html#multiple ?

Due to the DataTransformer, the validation rule you suggested at https://github.com/symfony/symfony/pull/43047#issuecomment-922509862 isn't working, so I'm guessing the only way to get validation on the entity is:
```php
#[Assert\Choice(callback: [Features::class, 'values'], multiple: true)]
```
... with this in the enum:
```php
public static function values(): array
{
    return array_column(self::cases(), 'value');
}
```

**Comment by derrabus** [comment]
Have you seen doctrine/orm#9497?

**Comment by ThomasLandauer** [comment]
No, I haven't, thanks! So I'm closing this.
