### ISSUE TITLE
Cloudflare Email Protection block correct displaying doctrine URL on symfony.com

### ISSUE THREAD

**Issue by andp97** [symfony/symfony-docs#16601]
Hi,

In this page https://symfony.com/doc/current/doctrine.html the [Cloudflare Email Protection](https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-) avoid the right display of Doctrine database URL.

<img width="787" alt="Schermata 2022-03-14 alle 17 49 53" src="https://user-images.githubusercontent.com/17993831/158221008-5c03f11a-32be-4854-ac0b-282ff49af627.png">

If I click on `[email protected]` I'm redirect to this page: https://symfony.com/cdn-cgi/l/email-protection

<img width="1014" alt="Schermata 2022-03-14 alle 17 51 20" src="https://user-images.githubusercontent.com/17993831/158221276-c54722d2-db99-4a4e-ba61-551f4fd18902.png">

Cloudflare tarce:
```
fl=470f17
h=symfony.com
ip=x.x.x.x
ts=1647276702.688
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
colo=FRA
http=http/2
loc=IT
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
```

**Comment by javiereguiluz** [comment]
We've just disabled email obfuscation on symfony.com, so this should be fixed now ... or it will soon. Cheers!
