### ISSUE TITLE
[Security] wrong anchor

### ISSUE THREAD

**Issue by connorhu** [symfony/symfony-docs#16602]
Hi,

In security.rst there is a wrong anchor at the link:

```# https://symfony.com/doc/current/security.html#c-hashing-passwords```

https://github.com/symfony/symfony-docs/blame/5.4/security.rst#L31

I guess the right link is:
https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords

**Comment by mdoutreluingne** [comment]
Thanks for you issue, I will open a PR for fix wrong anchor.
