### ISSUE TITLE
Inconsistency in how to run tests

### ISSUE THREAD

**Issue by pbowyer** [symfony/symfony-docs#16603]
The [testing documentation](https://symfony.com/doc/current/testing.html) consistently uses `php ./vendor/bin/phpunit` to invoke tests.

When I install `symfony/test-pack` it outputs:
```
$ composer require --dev symfony/test-pack
Using version ^1.0 for symfony/test-pack
./composer.json has been updated
[...]
 symfony/phpunit-bridge  instructions:

  * Write test cases in the tests/ folder
  * Use MakerBundle's make:test command as a shortcut!
  * Run the tests with php bin/phpunit
```

`Run the tests with` is inconsistent with the documented way. I make no judgement about which is right, but the two should match.

Happy to create a PR once I know which one to change.

**Comment by xabbuh** [comment]
Thanks for reporting. This will be fixed by #16626.
