### ISSUE TITLE
Coding standard "arguments on the same line"

### ISSUE THREAD

**Issue by leofeyer** [symfony/symfony-docs#16607]
I am referring to this:

https://github.com/symfony/symfony-docs/blob/dc9a534b9e426ad4bc5928d3453525973ff0604a/contributing/code/standards.rst#L182-L183

Now that we have constructor property promotion in PHP 8, do you still feel like this rule makes sense? Especially constructors can become quite long, e.g.:

```php
class Request
{
    public function __construct(public array $query = [], public array $request = [], public array $attributes = [], public array $cookies = [], public array $files = [], public array $server = [], protected string|object|false|null $content = null)
    {
        $this->initialize($query, $request, $attributes, $cookies, $files, $server, $content);
    }
}
```

Compared to:

```php
class Request
{
    public function __construct(
        public array $query = [],
        public array $request = [],
        public array $attributes = [],
        public array $cookies = [],
        public array $files = [],
        public array $server = [],
        protected string|object|false|null $content = null
    ) {
        $this->initialize($query, $request, $attributes, $cookies, $files, $server, $content);
    }
}
```

I realize that you are not promoting constructor property promotion yet (as explained in #16087) and I also realize that nobody has to adopt the Symfony coding style if they don‘t agree with it. However, removing that rule does not mean that anyone (including Symfony) has to change their code, so I figured we could at least discuss it.

What do you think?

**Comment by nicolas-grekas** [comment]
to me: property promotion = multiline (with trailing comma), single line otherwise (no trailling comma)

**Comment by xabbuh** [comment]
I agree with Nicolas

**Comment by wouterj** [comment]
I agree with Nicolas as well (although I'm not a fan of trailing comma in param lists).

I don't think removing the rule, while it is true and the easiest, is the best solution here. Symfony is a bit different to many other projects in that we fully respect the pixels at the right side of your screen, and thus we don't maintain a maximum line length. Let's be explicit about that (to avoid people, after reading the CS, to still contribute wrapped parameter lists).

Would you be able to create a PR to add the property promotion exception to this rule?
