### ISSUE TITLE
Add generics to ArgumentMetadata::getAttributes

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16615]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45094
| PR author(s) | @Seldaek
| Merged in    | 6.1

**Comment by Seldaek** [comment]
This stuff is not present at all in the docs right now that I could find, https://symfony.com/doc/current/controller/argument_value_resolver.html does not have any example fetching attributes.

Maybe it'd be better to update the example of the UserValueResolver by something else using an attribute, as that one is anyway built-in already it is a bit redundant.

**Comment by wouterj** [comment]
I don't think this specific feature needs docs (you'll find it when you need it).

I do agree with the example being a bit unfortunate. If you have a nice use-case (and time :wink:) we can update it.
