### ISSUE TITLE
FRONT-END > Vue.js  : redirect loop (v6.0)

### ISSUE THREAD

**Issue by PauchardThomas** [symfony/symfony-docs#16637]
Page [https://symfony.com/doc/6.0/frontend/encore/vuejs.html](https://symfony.com/doc/6.0/frontend/encore/vuejs.html) can not be reached for version **6.0**, as it redirects to itself.

**Comment by javiereguiluz** [comment]
Thanks for reporting. Sadly this is a known and random error that we haven't found yet how to solve it. See https://github.com/symfony/symfony-docs/issues?q=is%3Aissue+too+many+redirect+is%3Aclosed Cheers!
