### ISSUE TITLE
"Installing & Setting up the Symfony Framework" creates redirect loop for v6.1

### ISSUE THREAD

**Issue by wiese** [symfony/symfony-docs#16635]
The page ["Installing & Setting up the Symfony Framework"](https://symfony.com/doc/6.1/setup.html) can not be reached for version 6.1, as it redirects to itself. Browsers will eventually give up and show a message (to the effect of "The Page Isn’t Redirecting Properly").
 
The same link works for e.g. 6.0. Both are available alongside each other in the version dropdown in the navigation.

```
curl --head https://symfony.com/doc/6.1/setup.html
HTTP/2 301 
date: Tue, 22 Mar 2022 16:18:59 GMT
content-type: text/html; charset=UTF-8
…
location: /doc/6.1/setup.html
```

**Comment by wiese** [comment]
Recent #16637 sounds similar, but both seem to be working now. I'll leave this open a bit longer just in case this happens to be a coincidence.

**Comment by wiese** [comment]
Seems to be working reliably now. No need to keep this open any longer. Thanks to who ever fixed this!

**Comment by javiereguiluz** [comment]
@wiese thanks for reporting this. Sadly it's a known random error that we haven't fixed yet because we don't know the exact cause. You could see similar errors ... and they are fixed automatically a few minutes later without us doing anything to fix it.

**Comment by wiese** [comment]
@javiereguiluz Thanks for the insight. Maybe we could produce a generic, well-tagged ticket to track this issue (I could not find in case it already exists). This would act as a reminder, people can see that it is a known issue (not reporting it again), may add observations there, and save you some work triaging new reports every now and again.

**Comment by javiereguiluz** [comment]
See https://github.com/symfony/symfony-docs/issues?q=is%3Aissue+too+many+redirects+is%3Aclosed+

**Comment by wiese** [comment]
@javiereguiluz No doubt about it. The idea was more along the lines of having an _unclosed_ ticket to track the "random error that we haven't fixed yet because we don't know the exact cause"… Basically putting your knowledge in writing in a dedicated ticket. Maybe along the lines of "[Website] Documentation pages randomly redirecting to themself (too many redirects)", with a description and maybe a list of links to former (specific) tickets. ~~How does that sound?~~ I took the liberty to create #16649.
