### ISSUE TITLE
[Website] Documentation pages randomly redirecting to themself (too many redirects)

### ISSUE THREAD

**Issue by wiese** [symfony/symfony-docs#16649]
Sometimes documentation pages can not be reached as they redirect to themself. Browsers will eventually give up and show a message (to the effect of "The Page Isn’t Redirecting Properly").

As @javiereguiluz [put it](https://github.com/symfony/symfony-docs/issues/16635#issuecomment-1077665657), "it's a known random error that we haven't fixed yet because we don't know the exact cause. You could see similar errors ... and they are fixed automatically a few minutes later without us doing anything to fix it."

This is has repeatedly been reported in tickets for individual occurrences (e.g. in #16031, #16384, #16487, #16505, #16635, #16637) which then were closed because the specific problem went away – while they all seem to be sharing an unresolved root cause.

Theories so far:
* "cache pollution issue" https://github.com/symfony/symfony-docs/issues/16031#issuecomment-999400354

**Comment by wiese** [comment]
Created this to track the problem, so that people can see that it is a known issue (don't have to report it again), may add observations, and save some work triaging new reports every now and again. Feel free to change/add to.

**Comment by javiereguiluz** [comment]
I'm closing this issues because I think the situation is back to normal and we no longer get those errors. I haven't seen them myself for some time ... and I don't see user reports about this on Slack or GitHub anymore either. Thanks!
