### ISSUE TITLE
[Notifier] Use Importance level to set flash message type

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16654]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45047
| PR author(s) | @benr77, @fabpot
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @benr77. 6.1 is coming closer, and with it your great feature will soon see his first stable release :partying_face: 

Do you have time (and do you want) to write a little section about this feature in the documentation? I don't fully understand the feature (no experience with Notifier), but maybe somewhere in "Creating & Sending Notifications" or "Customize Notifications" in https://symfony.com/doc/current/notifier.html ? Thanks!

**Comment by benr77** [comment]
Yes, I will submit a docs PR no problem - hopefully can do this today.
