### ISSUE TITLE
[HttpKernel] Simplifying Bundle/Extension config definition

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16669]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43701
| PR author(s) | @yceruto
| Merged in    | 6.1

**Comment by Nyholm** [comment]
It is really important that we document this feature. I've heard many people complain that there is too little documentation on how to create bundles. 

Let me know if you (anyone) needs help.

**Comment by yceruto** [comment]
I will start writing it as soon as possible.

**Comment by wouterj** [comment]
Very friendly ping @yceruto :)

I realize we don't really properly document bundle extensions/config in the docs at the moment. If you are in doubt what to document or where, feel free to reply/contact us.

**Comment by yceruto** [comment]
Thanks for pinging me @wouterj! I've already started documenting it, but unfortunately, I haven't found time to finish it. I will do my best to finish it before the final 6.1 release.

**Comment by alamirault** [comment]
With this great merged PR https://github.com/symfony/symfony-docs/pull/16801, I think we can close this issue ?
