### ISSUE TITLE
[HttpFoundation] Allow dynamic session "ttl" when using a remote storage

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16668]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45873
| PR author(s) | @nicolas-grekas
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi again @nicolas-grekas :). Do you think this feature needs documentation? I cannot fully follow the code PR and it seems to be quite an advanced edge case? If you think it needs docs, can you please submit a small PR?

**Comment by javiereguiluz** [comment]
Closing as fixed in #16880. Thanks.
