### ISSUE TITLE
[DependencyInjection] Add argument type `closure` to help passing closu…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16667]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45878
| PR author(s) | @nicolas-grekas
| Merged in    | 6.1

**Comment by wouterj** [comment]
@nicolas-grekas do you have time to write a few words about closure argument type in the service container documentation before the 6.1 release? :)

I think either a subsection on https://symfony.com/doc/current/service_container.html or a new sub article are the best locations (given the current structure of service container).

**Comment by alexandre-daubois** [comment]
I'm on it 🙂
