### ISSUE TITLE
[PhpUnitBridge] Add option `ignoreFile` to configure a file that lists …

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16670]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45226
| PR author(s) | @mondrake
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @mondrake, thanks for the code feature! Are you willing to write a very small doc section about this new feature? I think it would best fit under the "Configuration" section on https://symfony.com/doc/current/components/phpunit_bridge.html

**Comment by mondrake** [comment]
I tried in #16768, please review - my first doc PR
