### ISSUE TITLE
[Serializer] Add serializer profiler

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16675]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45656
| PR author(s) | @mtarld
| Merged in    | 6.1

**Comment by javiereguiluz** [comment]
This is a fantastic feature ... but in the docs we don't explain Symfony Profiler panels in detail (users can easily browse them and understand the given information) so, let's close this. Thanks!
