### ISSUE TITLE
[Validator] Allow creating constraints with required arguments

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16674]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45072
| PR author(s) | @norkunas
| Merged in    | 6.1

**Comment by wouterj** [comment]
@norkunas thanks for this feature! Looking at the code PR, it seems like this is very useful for required options. Do you have time to write a small bit of documentation about this in https://symfony.com/doc/current/validation/custom_constraint.html#creating-the-constraint-class ?

**Comment by norkunas** [comment]
@wouterj np, will do :)
