### ISSUE TITLE
Update confusing example using ->method(...)

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony-docs#16685]
It was common to write code examples using `method(...)` to omit the details of the arguments.

https://github.com/symfony/symfony-docs/blob/250afd32ae9d605f5170dd492d15ff2df497de17/messenger.rst#L2040-L2041

This notation is becoming confusing since [first-class callable syntax was introduced in PHP 8.1](https://stitcher.io/blog/new-in-php-81#first-class-callable-syntax-rfc). 

I think we should find a new notation for such examples : I propose `->method(/* ... */)`

```php
             $messenger->transport('async_priority_normal')->dsn(/* ... */); 
             $messenger->transport('image_transport')->dsn(/* ... */); 
```

**Comment by javiereguiluz** [comment]
That's a good point!

If the argument can only be a string, I'd prefer to use `'...'` but I like the `/* ... */` for other cases.

Ping @symfony/team-symfony-docs. Thanks!

**Comment by xabbuh** [comment]
I agree with Javier.

**Comment by GromNaN** [comment]
@javiereguiluz proposition is nice. What should be the target version for a PR?

**Comment by OskarStark** [comment]
> What should be the target version for a PR?

I think we should start on 4.4 fix all occurrences, unmerge and do the round trip again for the upper branches

**Comment by xabbuh** [comment]
I agree with Oskar

**Comment by alamirault** [comment]
@javiereguiluz  PR was merged, we can close this issue :smile:
