### ISSUE TITLE
`Subscribe to Symfony Roadmap notifications` page not found

### ISSUE THREAD

**Issue by chen-gloria** [symfony/symfony-docs#16687]
When I tried to click [this](https://symfony.com/account/notifications) link in [the Release Process page](https://symfony.com/doc/current/contributing/community/releases.html) in Symfony doc, it gave me the page not found. I'm wondering if this is not updated:

![Screen Shot 2022-04-05 at 8 16 06 am](https://user-images.githubusercontent.com/38202941/161641004-07b49a48-ac0b-48f9-b429-f9cb1dc2fc34.png)

**Comment by javiereguiluz** [comment]
@chen-gloria thanks for reporting this error! We've just deployed some fixes for it. Cheers!
