### ISSUE TITLE
[Messenger] Worker state and reset_on_message

### ISSUE THREAD

**Issue by volendavidov** [symfony/symfony-docs#16688]
The documentation states that `That's why Symfony automatically resets the service container between two messages.`. However it does not explain that the service must implement `Symfony\Contracts\Service\ResetInterface` or `Symfony\Component\Cache\ResettableInterface` in order to reset the service leading to the impression that a new instance of the service will be provided automagically. Shouldn't this be elaborated in the documentation?

**Comment by javiereguiluz** [comment]
Yes, we should mention this. Would you be willing to create a pull request to improve this? Thanks!
