### ISSUE TITLE
[Set up]: Fixing file permission

### ISSUE THREAD

**Issue by tuan-lm97** [symfony/symfony-docs#16708]
At "Setting up or Fixing File Permissions" we got this:

https://symfony.com/doc/current/setup/file_permissions.html#1-using-acl-on-a-system-that-supports-setfacl-linux-bsd

> HTTPDUSER=$(ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1)
>\# if this doesn't work, try adding `-n` option

But where to add `-n` option ?
`grep`, `head` and `cut` all have `-n` option.

A few more word would be very clear for the user who is reading this doc

**Comment by sargath** [comment]
I think that it should aim at `setfacl` command option. 

https://man7.org/linux/man-pages/man1/setfacl.1.html  check -n `no-mask`

**Comment by javiereguiluz** [comment]
Thanks for your help @sargath. We're trying to fix this in #17004.

**Comment by javiereguiluz** [comment]
Fixed in #17004.
