### ISSUE TITLE
[HttpFoundation] Send `Content-Length` when calling `Response::send()` …

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16703]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45092
| PR author(s) | @nicolas-grekas
| Merged in    | 6.1

**Comment by wouterj** [comment]
Looking at the code PR, this is a feature that "just works". So I guess there is nothing to document here.

Please correct me if I'm wrong.
