### ISSUE TITLE
[Routing] Add Requirement, a collection of universal regular-expression…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16718]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45528
| PR author(s) | @fancyweb
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @fancyweb :) Do you have time to add some docs about this wonderful helper class in https://symfony.com/doc/6.1/routing.html#parameters-validation ?

**Comment by nicwortel** [comment]
With the merging of #16926, I think this issue can now be closed.

**Comment by javiereguiluz** [comment]
Yes, thank you!
