### ISSUE TITLE
[Routing] Allow using services in the route condition

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony-docs#16714]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#44405
| PR author(s) | @renanbr
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @renanbr. This looks like a pretty big feature! Are you willing to (and do you have time) to write a bit of documentation about the feature?

I think the best would be to add the `service()` function to the list in https://symfony.com/doc/6.1/routing.html#matching-expressions
And then add a small section paragraph basically saying "you'll have to add the `#[AsRoutingConditionService]` attribute or `...` tag to your service if you want to use it in the condition".
