### ISSUE TITLE
[Notifier] smsapi - send messages in test mode

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16729]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46047
| PR author(s) | @Patryk Kozłowski
| Merged in    | 6.1

**Comment by OskarStark** [comment]
@nicolas-grekas this is weird, why is the author not the same? 🤔

**Comment by OskarStark** [comment]
friendly ping @n3crone

**Comment by javiereguiluz** [comment]
Fixed in #17002.
