### ISSUE TITLE
[Validator] multiple id attribute with callback value

### ISSUE THREAD

**Issue by connorhu** [symfony/symfony-docs#16721]
On the page Callback Constraint there are two id attributes has "callback" value. First one is the headerlink, second one is the option callback. This is bug because you can not navigate to the element:
https://symfony.com/doc/current/reference/constraints/Callback.html#callback

![Screenshot 2022-04-16 at 14 28 46](https://user-images.githubusercontent.com/1845575/163675156-92c9aa73-31d1-46fa-adda-6fe597b44a06.png)

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. Sadly, it's a known issue in the docs-builder tool (https://github.com/symfony-tools/docs-builder) that we use to build the docs. In any case, let's close this as a duplicate of #16417.
