### ISSUE TITLE
[FrameworkBundle] Add support for route attributes in kernel controller…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16734]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46115
| PR author(s) | @dunglas
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @dunglas. Do you have any time to add this cool functionality to https://symfony.com/doc/current/configuration/micro_kernel_trait.html ? (e.g. by adding a "php-attributes" tab to the first code example and a versionadded saying it is new)
