### ISSUE TITLE
Document constraint about php internals before php8 and lazy services.

### ISSUE THREAD

**Issue by chrishalbert** [symfony/symfony-docs#16740]
I ran into this as I'm sure others have when trying to lazy load a php internal like PDO with default parameters.

While it was interesting to learn why this didn't work and traverse the codebases, a small note in the short lazy services docs could have saved me a little time. Thanks for your work!

PR: https://github.com/symfony/symfony-docs/pull/16739

**Comment by chrishalbert** [comment]
Is there any reason this isn't getting merged? Thanks

**Comment by javiereguiluz** [comment]
Closing as fixed in #16739. Chris, thanks for your contribution to improve Symfony Docs.
