### ISSUE TITLE
[Routing] Remove variadic constructor signature

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16758]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46157
| PR author(s) | @wouterj
| Merged in    | 6.1

**Comment by javiereguiluz** [comment]
This change was done in https://github.com/symfony/symfony-docs/commit/05c68eb5aca38adf605f287954b15528a180d1e2 while merging #16726.
