### ISSUE TITLE
[Console] Table vertical rendering

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony-docs#16795]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41676
| PR author(s) | @yoannrenard
| Merged in    | 6.1

**Comment by wouterj** [comment]
Hi @yoannrenard. Thanks for this feature :)

With the 6.1 stable release coming very soon, do you have any time (and do you want) to write a small section about vertical tables in https://symfony.com/doc/current/components/console/helpers/table.html ?

**Comment by yoannrenard** [comment]
Hi @wouterj 
I'll do it with pleasure

**Comment by javiereguiluz** [comment]
Fixed in #16817.
