### ISSUE TITLE
Resettable services called on repeatable boot kernel, not on terminate event

### ISSUE THREAD

**Issue by andrew-demb** [symfony/symfony-docs#16806]
https://symfony.com/doc/5.4/reference/dic_tags.html#kernel-reset

> During the kernel.terminate event, Symfony looks for any service tagged with the kernel.reset tag to reinitialize their state. This is done by calling to the method whose name is configured in the method argument of the tag.

If you will check the codebase about `services_resetter` (main service with all known services tagged as `kernel.reset`) callers - you will find, that it is called only on kernel 2+ booting (if we talking about HTTP context)
https://github.com/symfony/symfony/blob/9cb6274a5bcfddea10f84369acfe7f480a9c7d1f/src/Symfony/Component/HttpKernel/Kernel.php#L113-L125

Should the documentation be updated about the moment, when `reset` method will be called?

**Comment by vudaltsov** [comment]
Agree, documentation is really misleading at the moment. @javiereguiluz , may I attract your attention to this issue?

**Comment by xabbuh** [comment]
Are you up for a PR that rewords the current description?
