### ISSUE TITLE
[Forms] EntityType with multiple=true returns ArrayCollection but is documented to return array

### ISSUE THREAD

**Issue by Xesau** [symfony/symfony-docs#16805]
In the documentation (https://symfony.com/doc/current/reference/forms/types/entity.html#multiple) it states that when `multiple` is enabled, the field should return an array. However, if you look at the tests (https://github.com/symfony/symfony/blob/6.1/src/Symfony/Bridge/Doctrine/Tests/Form/Type/EntityTypeTest.php) you see that it expects an ArrayCollection.

**Comment by javiereguiluz** [comment]
Fixed in #16849.
