### ISSUE TITLE
[VarExporter] Add Hydrator::hydrate() and preserve PHP referenc…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16827]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46452
| PR author(s) | @nicolas-grekas
| Merged in    | 6.2

**Comment by wouterj** [comment]
Hi Nicolas! Can you please update the [Instantiating PHP classes](https://symfony.com/doc/current/components/var_exporter#instantiating-php-classes) section of the VarExporter documentation to show this new feature and also explain when to use Hydrator and when to use Instantiator?
