### ISSUE TITLE
[TwigBridge] Add form_label_content and form_help_content block to form…

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#16836]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45985
| PR author(s) | @alexander-schranz
| Merged in    | 6.2

**Comment by javiereguiluz** [comment]
I propose to close this without adding any docs because we don't list the available Twig blocks in form themes. We don't do that even in `form/form_themes.rst`.

Folks needing this will look into the Twig blocks available in the Symfony built-in themes and they'll find them. Thanks!
