### ISSUE TITLE
[Serializer][WebProfilerBundle] Collect & show caller source code

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16847]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46569
| PR author(s) | @ogizanagi
| Merged in    | 6.2

**Comment by javiereguiluz** [comment]
This is a super nice feature ... but there's no need to document it because people will easily discover it when using the Serializer profiler panel. Thanks!
