### ISSUE TITLE
PHPUnit Bridge SetUpTearDownTrait got removed in 6.0

### ISSUE THREAD

**Issue by mvhirsch** [symfony/symfony-docs#16857]
The [mentioned Trait](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Bridge/PhpUnit/SetUpTearDownTrait.php) got removed in 6.0 (https://github.com/symfony/symfony/pull/41302). I suggest the whole paragraph can be removed in 6.0 and higher, too?

See: https://symfony.com/doc/6.0/components/phpunit_bridge.html#removing-the-void-return-type

**Comment by javiereguiluz** [comment]
Michael, thanks for your issue report, which contained all the needed information and references. It was perfect!

I propose to fix this in two ways: in #16860 we're adding the deprecation notice in 5.4 branch ... and when merging this into upper branches, we'll remove the paragraph entirely, as you proposed. Thanks!

**Comment by mvhirsch** [comment]
That's the reason why I love the symfony community: efficient, friendly, ... please stay like this @javiereguiluz !
