### ISSUE TITLE
[Serializer] Deprecate autowiring aliases pointing to concrete normaliz…

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony-docs#16886]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46663
| PR author(s) | @chalasr
| Merged in    | 6.2

**Comment by ogizanagi** [comment]
https://github.com/symfony/symfony-docs/pull/16826 might be enough to fix this (but there is the alternative to change the typehint and explicitly inject the proper object normalizer service id)

**Comment by wouterj** [comment]
I think there is nothing specifically to document about this change in 6.2. Let's continue this in #16826 (which is 4.4+).
