### ISSUE TITLE
remove "isSubmitted()" from Form documentation

### ISSUE THREAD

**Issue by arderyp** [symfony/symfony-docs#16892]
if `isValid()` indeed is the same as `isSubmitted() && isValid()`, as [this issue](https://github.com/symfony/symfony/issues/13706) suggests, then the documentation should not show `isSubmitted() && isValid()` as it's both redundant and confusing.

Example documentation: https://symfony.com/doc/current/forms.html

**Comment by wouterj** [comment]
Hi!

That issue is from 6 years ago. Meanwhile, `isValid()` is no longer contains `isSubmitted()` since Symfony 3.2: https://github.com/symfony/symfony/pull/17644

**Comment by arderyp** [comment]
@wouterj thanks for the quick response.  So, just to clarify, are you saying `isValid()` no longer covers `isSubmitted()` and now it is indeed required/recommended to check both `isSubmitted() && isValid()`?  If so, I think there should be a simple shorthand `$form->isSubmittedAndValid()`, in which case I will open a separate Symfony issue for that.

**Comment by arderyp** [comment]
@wouterj is my comment above correct?

**Comment by xabbuh** [comment]
IIRC that has been discussed in the past. You may want to search the issues in the code repository.

**Comment by arderyp** [comment]
Searching is what lead me the the apparently outdated statements in the issue that I referenced in opening this issue.
