### ISSUE TITLE
[Doctrine] the reverse-engineering features are deprecated

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#16903]
https://symfony.com/doc/current/doctrine/reverse_engineering.html is documenting how to reverse-engineer entities from an existing database. However, this feature of doctrine/orm is deprecated and won't be improved anymore. This should at least be warned on the page, and maybe symfony.com should remove that page entirely.

**Comment by javiereguiluz** [comment]
Do you know the Doctrine version that deprecated this? Or any other official resource from Doctrine confirming that it's deprecated? Thanks! (I can't see that it's deprecated in the Doctrine docs).

**Comment by wouterj** [comment]
Yes: https://github.com/doctrine/DoctrineBundle/pull/1082

Imho, we should just remove the page entirely

**Comment by javiereguiluz** [comment]
Closing as fixed in #16924.
