### ISSUE TITLE
Introduce FlashBagAwareSessionInterface

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16934]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46491
| PR author(s) | @VincentLanglet
| Merged in    | 6.2

**Comment by VincentLanglet** [comment]
Hi @fabpot, does this new Interface really need doc ?

**Comment by fabpot** [comment]
As there are so many questions about this, maybe yes? I don't know.

**Comment by javiereguiluz** [comment]
Closed in #16936.
