### ISSUE TITLE
[Serializer] Provide context information from attribute for promoted pr…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16932]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46680
| PR author(s) | @DanielBadura
| Merged in    | 6.2

**Comment by wouterj** [comment]
If I'm correct, the PR referenced in this issue has made it possible to use the `#[Context]` attribute on (promoted) properties. I would say this is not something that we have to explicitly document (other than in the CHANGELOG in the code repository?).

Btw, we're completely lacking the docs for this attribute (ref #14988 ). If you're wanting to write a bit of documentation about it, you're definitely welcome to do so :)
