### ISSUE TITLE
[Form] Provide string keys when iterating on a form

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16933]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46813
| PR author(s) | @VincentLanglet
| Merged in    | 6.2

**Comment by VincentLanglet** [comment]
Hi @fabpot, what's needed in the doc ? I kinda consider my PR as a bugfix, it was just considered safer to do it on 6.2 since it's changing an internal class.

**Comment by HeahDude** [comment]
A bot opened this issue on merge, I guess we can close here.
