### ISSUE TITLE
Add deprecation when the session is not FlashBagAware

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16937]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46831
| PR author(s) | @VincentLanglet
| Merged in    | 6.2

**Comment by VincentLanglet** [comment]
Hi @xabbuh, is a PR needed for this ?

**Comment by xabbuh** [comment]
This looks too specific to me. If someone is able to customise the session class, they will probably also be able to solve the deprecation.
