### ISSUE TITLE
Error Can't get a way to read the property  in class 

### ISSUE THREAD

**Issue by stoullec** [symfony/symfony-docs#16938]
Hello,

The docs is good but I have an error when I use:

'entry_options' => $options,

in TaskType.

for documentation:
https://symfony.com/doc/5.4/form/form_collections.html

Kind Regards.

**Comment by TheGarious** [comment]
Hello,

Concerning your error can you share your output error ? 

You use $options from parameters of function buildForm ? 
```
public function buildForm(FormBuilderInterface $builder, array $options)
```

Regarding the documentation it's not mentioned to use it directly into entry_option.
Look this link for more information concerning $options : https://symfony.com/doc/5.4/form/create_custom_field_type.html#adding-configuration-options-for-the-form-type

**Comment by stoullec** [comment]
Ok thank you so much it works,

the solutions is 'entry_options' => [ "myOption" => $options['myOption'] ]

**Comment by TheGarious** [comment]
You can close this issue :D
