### ISSUE TITLE
[Security] Add a method in the security helper to ease programmatic login

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#16940]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#41274
| PR author(s) | @johnkrovitch, @chalasr
| Merged in    | 6.2

**Comment by javiereguiluz** [comment]
Closing as a duplicate of #17016.

**Comment by xabbuh** [comment]
reopening here as #17016 is about logging users out

**Comment by wouterj** [comment]
Hi @johnkrovitch! Thanks for contributing this feature (I'm happy it's finally merged).

Do you have time (and are you willing) to write a short section about this new helper to login users? I think this is best as a new subsection at the end [Authenticating Users](https://symfony.com/doc/current/security.html#authenticating-users).

**Comment by johnkrovitch** [comment]
Hi @wouterj , 

yes, I try to do that this evening.

**Comment by johnkrovitch** [comment]
The documentation has been added in #17284
