### ISSUE TITLE
custom form type named SearchType adds additional field

### ISSUE THREAD

**Issue by DavidBadura** [symfony/symfony-docs#16953]
### Symfony version(s) affected

6.1.2

### Description

I created a new symfony project few hours ago and came across something very strange. If you create a custom form type called `SearchType` then for some reason another input field is added. As soon as you rename the class, the field is gone again.

This should definitely not happen and some symfony magic adds this field if the name is "SearchType". Regardless of the namespace. This shouldn't be happening in my opinion and is super confusing.

### How to reproduce

Form Type:

```php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('zipCode', TextType::class)
            ->add('range', ChoiceType::class, [
                'choices' => [
                    '10km' => 10,
                    '20km' => 20,
                    '50km' => 50
                ]
            ])
        ;
    }
}
```

Controller: 

```php
    #[Route('/')]
    public function __invoke(Request $request): Response
    {
        $form = $this->formFactory->create(SearchType::class);
        $form->handleRequest($request);

        // ...

        return new Response(
            $this->twig->render('index.html.twig', [
                'form' => $form->createView()
            ])
        );
    }
```

Template:

```twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form(form) }}
{% endblock %}
```

Since I've only just started the project and there's nothing business-relevant in it, I pushed the status to a public github repository: https://github.com/DavidBadura/symfony-search-type-bug

### Additional Context

<img width="656" alt="Bildschirmfoto 2022-07-07 um 14 10 57" src="https://user-images.githubusercontent.com/470138/177770071-3fc58d1a-9923-4baa-a1a7-ace88e13a7a7.png">

**Comment by HeahDude** [comment]
It seems expected to me.

You should implement `getBlockPrefix()` in your `SearchType` (and in all custom type to avoid such conflict with something like `app_search_form`. Or just rename your type to `SearchFormType` that should do the trick.

**Comment by DavidBadura** [comment]
I've been working with Symfony since 2.0 prerelease and have never had this problem or conflict until now :D

I've now looked into the documentation: https://symfony.com/doc/current/form/create_custom_field_type.html

That doesn't mention this problem or anything. There `ShippingType ` is used without additional `Form` in the name. Also, there is no mention that `getBlockPrefix` should be implemented to prevent this from happening.

I don't know if it is the best DX if this behavior exists or if there is not a safe way not to walk into it. such as a convention of suffixing your own types with FormType. I figured it out quickly because I know Symfony, but it might be frustrating for others.

I'm fine with it being expected. But we should make sure somehow that people don't run in there. What do you think about? The `SearchType` name for a custom form is certainly not infrequently used.

**Comment by stof** [comment]
Well, the conflict only happens when the automatically generated block prefix does not conflict with another form type that has a custom rendering.
To never face this issue, we would have to generate the block prefix based on the FQCN instead of the short name, but that would make very long block names in Twig.

**Comment by teradrive65k** [comment]
Just to add more information about this topic, the search field is added in the form template form_div_layout:

```
#form_div_layout.html.twig
{%- block search_widget -%}
    {%- set type = type|default('search') -%}
    {{ block('form_widget_simple') }}
{%- endblock search_widget -%}
```

So we can also create our own theme and just override this block like this for exemple:
```
{% extends 'base.html.twig' %}
{% form_theme form _self %}

{%- block search_widget -%}
{%- endblock search_widget -%}
{% block body %}
    {{form(form)}}
{% endblock %}
```

**Comment by HeahDude** [comment]
I would open an issue in the docs. IMO there is nothing we can fix in core, as the solution proposed by Christophe:

>To never face this issue, we would have to generate the block prefix based on the FQCN instead of the short name, but that would make very long block names in Twig.

would be a huge BC break anyway and a nightmare to handle a BC layer.

**Comment by xabbuh** [comment]
I have moved the issue to the docs repo as this is there place where we need to handle this somehow.

**Comment by javiereguiluz** [comment]
I was going to try to fix this, but I realized that we already display a `caution` message about this:

<img width="989" alt="block_form_type" src="https://github.com/symfony/symfony-docs/assets/73419/70696eef-a8ec-4053-836b-2900fae0b38d">

So, let's close this as fixed.
