### ISSUE TITLE
Hide sensitive information with `SensitiveParameter` attribute

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16964]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46183
| PR author(s) | @GromNaN
| Merged in    | 6.2

**Comment by alexandre-daubois** [comment]
I think this could be added as a `.. note:` somewhere in the Security documentation just to inform developers of this from PHP 8.2. But I can't exactly decide where to add this, in the Security documentation?

**Comment by javiereguiluz** [comment]
Fixed in #16997.
