### ISSUE TITLE
[VarExporter] Add trait to help implement lazy loading ghost objects

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16970]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46751
| PR author(s) | @nicolas-grekas
| Merged in    | 6.2

**Comment by wouterj** [comment]
Hi Nicolas. I'm afraid this and https://github.com/symfony/symfony-docs/issues/17249 are way beyond the knowledge that we documentors have about Symfony code.
Are you willing to write up a nice section (maybe new article in the var exporter component?) about the proxy features provided by Symfony 6.2? :pray:
