### ISSUE TITLE
[DependencyInjection] Use lazy-loading ghost object proxies out of the …

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#16976]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46752
| PR author(s) | @nicolas-grekas
| Merged in    | 6.2

**Comment by javiereguiluz** [comment]
Does this have any impact for developers? E.g. do they have to change anything in their apps? Can they remove some previously needed dependencies? etc. Thanks!

**Comment by nicolas-grekas** [comment]
Yes: they don't need proxy-manager-bridge anymore so we need to check where we tell about it and remove those mentions. It should just work out of the box now, and in the cases where it doesn't, it will throw an actionable error message.

**Comment by javiereguiluz** [comment]
Fixed in #16995.
