### ISSUE TITLE
[FrameworkBundle] Add "Usages" to debug:container output

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16989]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#38903
| PR author(s) | @Bert ter Heide, @bertterheide
| Merged in    | 6.2

**Comment by javiereguiluz** [comment]
This is a nice feature, but we don't need to update the docs because we don't display the output of the `debug:container` command in docs. We only display how to use it and its options. Thanks.
