### ISSUE TITLE
[Safari] Symfony Hub banner overlaying search

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony-docs#16991]
Docs seem slightly broken on Safari:
<img width="1992" alt="Screenshot 2022-07-17 at 16 22 06" src="https://user-images.githubusercontent.com/24696606/179402788-82964161-978d-460b-82aa-2860f8a6cda8.png">
As you can see the Hub banner is overlaying the search for me.

Does anyone have the same issue with Safari (15.5)?

**Comment by OskarStark** [comment]
<img width="1512" alt="CleanShot 2022-07-22 at 11 01 03@2x" src="https://user-images.githubusercontent.com/995707/180404253-1134a67b-047c-490c-b5e9-b0475c765ff2.png">

No

**Comment by KDederichs** [comment]
Hmm, ok looks like adguard might be messing with that.
Question is if that's an issue for here, or for them.

**Comment by javiereguiluz** [comment]
Let's close this old issue because it looks like we can no longer reproduce this issue. Thanks.
