### ISSUE TITLE
[DoctrineBridge] Add an Entity Argument Resolver

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17018]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43854
| PR author(s) | @jderusse, @nicolas-grekas
| Merged in    | 6.2

**Comment by wouterj** [comment]
I think we should replace all mentions of param converter with this new resolver:

* https://symfony.com/doc/current/doctrine.html#automatically-fetching-objects-paramconverter
* https://symfony.com/doc/current/best_practices.html#use-paramconverters-if-they-are-convenient (same practices still apply I think)

@jderusse do you have time to update these docs? :)

**Comment by jderusse** [comment]
Actually, using the feature would be muchn more simple with the wiring provided in doctrine bundle which not yet tagged (https://github.com/doctrine/DoctrineBundle/pull/1554)

**Comment by wouterj** [comment]
Thanks for sharing this knowledge Jeremy!

I've asked the Doctrine team and they will be able to release a patch version anytime, so we can write this docs as if a stable version with those changes was released. I'll make sure that *is* the case when 6.2 is released stable :)
