### ISSUE TITLE
[Security] Allow configuring a target url when switching user

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#17021]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46338
| PR author(s) | @94noni
| Merged in    | 6.2

**Comment by 94noni** [comment]
I'll handle this :)

**Comment by chalasr** [comment]
That's much appreciated, thanks.

**Comment by 94noni** [comment]
new feature PR is https://github.com/symfony/symfony/pull/47343
thus the doc PR is adapted compared to original feature PR
