### ISSUE TITLE
[FrameworkBundle] Add service and alias deprecation message to debug:co…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17026]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46814
| PR author(s) | @94noni
| Merged in    | 6.2

**Comment by 94noni** [comment]
@fabpot thx for merging, but I am asking myself if this feature needs to be documented?

**Comment by fabpot** [comment]
I don't think so.

**Comment by xabbuh** [comment]
I was about to close here as well. 👍
