### ISSUE TITLE
Add `visibility` context option in `PropertyNormalizer`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17036]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#44902
| PR author(s) | @alamirault
| Merged in    | 6.2

**Comment by wouterj** [comment]
Hi @alamirault! Thanks for contributing this feature to Symfony 6.2!

Are you willing to also add a sentence about these new flags to the documentation? I guess it can be put here: https://symfony.com/doc/current/components/serializer.html#built-in-normalizers (like it's also done for the `UidNormalizer`), followed by a small `.. versionadded:: 6.2` directive telling the constants were introduced in 6.2.

**Comment by javiereguiluz** [comment]
Fixed in #17347.
