### ISSUE TITLE
[TwigBridge] Add support for toggle buttons in Bootstrap 5 form theme

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17079]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43865
| PR author(s) | @ker0x
| Merged in    | 6.2

**Comment by wouterj** [comment]
Correct me if I'm wrong, but I think this is a "it just works" feature that doesn't need any documentation. Let's close for now.
