### ISSUE TITLE
[HttpKernel] Add option to render Surrogate fragment with absolute URIs

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17077]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46514
| PR author(s) | @Kern046
| Merged in    | 6.2

**Comment by wouterj** [comment]
Hi @Kern046! Thanks for this feature :)

Are you maybe also willing (and do you have time) to also add this new option to the docs at the bottom of https://symfony.com/doc/current/http_cache/esi.html ?

**Comment by javiereguiluz** [comment]
Closing as fixed in #17613

**Comment by Kern046** [comment]
> Hi @Kern046! Thanks for this feature :)
> 
> Are you maybe also willing (and do you have time) to also add this new option to the docs at the bottom of https://symfony.com/doc/current/http_cache/esi.html ?

Oops very sorry I completely missed the notification, I would've been happy to help otherwise :grimacing:
