### ISSUE TITLE
[Clock] A new component to decouple applications from the system clock

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17074]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46715
| PR author(s) | @nicolas-grekas
| Merged in    | 6.2

**Comment by wouterj** [comment]
This deserves a new article in `components/`. As the component is quite minimal, this will be a nice short article :)

Anyone up to writing the docs for this? (@nicolas-grekas?)

**Comment by dbrumann** [comment]
I can do this one together with #17434
