### ISSUE TITLE
[Messenger] Add new `messenger:count` command that return a list of tra…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17085]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#46571
| PR author(s) | @ktherage, @ogizanagi, @EXT - THERAGE Kevin
| Merged in    | 6.2

**Comment by ktherage** [comment]
I can work on that but I have no idea on where to put the documentation on the Symfony's website.

**Comment by 94noni** [comment]
@ktherage hey, I would put it after here
https://symfony.com/doc/current/messenger.html#limit-consuming-to-specific-queues

Perhaps not the best place but open a doc PR and it will be challenged on it :)
