### ISSUE TITLE
[Mailer] mention that BCC recipients do not work with DKIM signing

### ISSUE THREAD

**Issue by kickofitall** [symfony/symfony-docs#17106]
I think it should be mentioned that BCC receivers don't work with DKIM signing.
A caution block would be appropriate.
Source: https://github.com/symfony/symfony/issues/44006#issuecomment-1128530738

**Comment by sdespont** [comment]
OK, thanks for adding this precision in the doc. But I don't understand why it was possible to send BCC for signed messages with SwiftMailer ? Was it a mistake ?
