### ISSUE TITLE
[Messenger] Add `TransportNamesStamp` to change the transport while dis…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17113]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39306
| PR author(s) | @asilelik, @fabpot
| Merged in    | 6.2

**Comment by wouterj** [comment]
Hi @asilelik!

I think your cool 6.2 feature deserves documentation. Are you able to create a PR for this?

The most logical place would be somewhere in this section: https://symfony.com/doc/current/messenger.html#routing-messages-to-a-transport (probably in a `.. tip::` at the end, just after the "If you configure routing for both a child and parent class ..." note)

**Comment by abarkine** [comment]
@wouterj thank you for letting me know. Yes, I will be more than happy to include the feature in the mentioned page.
