### ISSUE TITLE
[Mailer] Add a way to inject Stamps when sending an email via Messenger

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17111]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47191
| PR author(s) | @fabpot
| Merged in    | 6.2

**Comment by wouterj** [comment]
Hi @fabpot! I'm not sure I can completely follow the changes, whether this removes the `MessageEvent` or adds an additional event.

I guess we need to add/change https://symfony.com/doc/current/mailer.html#mailer-events Are you able to help us out? :)

**Comment by fabpot** [comment]
@wouterj See #17390
