### ISSUE TITLE
[Mailer] Add a way to change the Bus transport dynamically

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17127]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47190
| PR author(s) | @fabpot
| Merged in    | 6.2

**Comment by wouterj** [comment]
This new `X-Bus-Transport` header can be documented in this section: https://symfony.com/doc/current/mailer.html#sending-messages-async

**Comment by javiereguiluz** [comment]
Closing as fixed in #17623. Thanks
