### ISSUE TITLE
[Mime] Re-allow addIdHeader to be used for 'In-Reply-To' and 'Reference…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17138]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47225
| PR author(s) | @AlbinoDrought
| Merged in    | 6.2

**Comment by wouterj** [comment]
I don't think this needs documentation. We didn't document it before, nor did we document the removal of this feature. So I don't think we need to mention the re-introduction.
