### ISSUE TITLE
Is the page “Nov 2018 Changes to .env” still relevant?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#17133]
It's a bit strange that the documentation for the last version mentions changes made 4 years ago: https://symfony.com/doc/6.1/configuration/dot-env-changes.html

Should this page be removed? What Symfony versions should be affected?

**Comment by javiereguiluz** [comment]
I agree. I think we can delete this page. See #17143.

**Comment by javiereguiluz** [comment]
Closing as fixed in #17143.
