### ISSUE TITLE
[Intl] Update EmojiTransliterator to translate emoji to github and slac…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17191]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47263
| PR author(s) | @lyrixx
| Merged in    | 6.2

**Comment by lyrixx** [comment]
~~There was no doc for the previous PR, not sure this one need it too~~

**edit** I was wrong: https://github.com/symfony/symfony-docs/pull/17088
