### ISSUE TITLE
[Messenger] Pass sender details to SendMessageToTransportsEvent

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17207]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#40152
| PR author(s) | @Jeroeny
| Merged in    | 6.2

**Comment by mdoutreluingne** [comment]
Is this something that needs to be documented? 
Currently there are only links for Messenger events. The events are not [ explained in detail](https://symfony.com/doc/6.2/messenger.html#messenger-events).

**Comment by xabbuh** [comment]
I don't think so. Let's close here.
