### ISSUE TITLE
[HttpClient] Explain how to enable HTTP encoding ("Accept-Encoding" header)

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#17216]
@nicolas-grekas Just noticed that (by default) HttpClient doesn't support compression. I think this should be emphasized more in the docs, since it's an easy (?) way to speed things up, isn't it?

https://symfony.com/doc/current/http_client.html#making-requests

> HTTP compression and chunked transfer encoding are automatically enabled when both your PHP runtime and the remote server support them.

Some questions I'd like to expand on (but don't know the answers):
1. "HTTP compression" refers to an "Accept-Encoding" HTTP header being sent in the request?
2. How can I check what my PHP runtime supports?
3. If HttpClient comes to the conclusion that my PHP supports gzip and deflate, it will send?:
    > Accept-Encoding: gzip, deflate
4. Since Transfer-Encoding is dead in HTTP/2, it's probably not so important to give more details about it?

**Comment by nicolas-grekas** [comment]
http compression *is* enabled by default if the php engine supports it.

**Comment by ThomasLandauer** [comment]
Yeah, I probably messed it up before - now ` accept-encoding: gzip` is being sent by default. But I still can't figure out **why**? What needs to be present in `phpinfo()`? Or how would it be possible to disable it?

**Comment by nicolas-grekas** [comment]
compression is auto-enabled by curl when curl is compiled with it (see `php --ri curl`). Native http client checks with `extension_loaded('zlib')`.

`accept-encoding: identity` disables compression

**Comment by ThomasLandauer** [comment]
Thanks - see https://github.com/symfony/symfony-docs/pull/17218
