### ISSUE TITLE
[DependencyInjection] Handle INI arrays

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17232]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47367
| PR author(s) | @MatTheCat
| Merged in    | 6.2

**Comment by MatTheCat** [comment]
Err I didn't find any mention of defining parameters using an INI file in the documentation. I don't really know what to do here.

**Comment by OskarStark** [comment]
I think we can close here

**Comment by lpd-au** [comment]
https://symfony.com/doc/6.2/components/config/resources.html
