### ISSUE TITLE
[Messenger] Be able to get raw data when a message in not decodable by …

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17243]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#39622
| PR author(s) | @lyrixx
| Merged in    | 6.2

**Comment by lyrixx** [comment]
Hello, I'm not sure there is something to document here. 

Now exception are really clear and some error message are added with instructions

**Comment by xabbuh** [comment]
I guess we do not need to change anything around this in the docs.
