### ISSUE TITLE
Pages not linked in left-side navigation page, breadcrumb trails that don't match it anywhere

### ISSUE THREAD

**Issue by givihuda** [symfony/symfony-docs#17248]
I'm running into contextual navigation issues on a lot of Symfony pages, sometimes found from Google searches, sometimes linked from other sources. The issue is that I can't always tell which section or link the page is from... it seems to be some sort of sub-section page, or one dereferenced, or just existing outside of normal docs. It's a bit disorienting, and hard to find again if a Google search doesn't show it or I don't bookmark them all, which I shouldn't have to do.

Example: https://symfony.com/doc/5.4/service_container/calls.html
Title: Service Method Calls and Setter Injection
Breadcrumb trail: Home > Documentation > Service Container > Service Method Calls and Setter Injection

However, there's not even a "Service Container" link in the navigation page on the left... the closest is "Services / DI" under 'ARCHITECTURE', which links to https://symfony.com/doc/5.4/service_container.html with title "Service Container" (???) What? This is confusing. 

Can somebody explain this apparently discombobulated way the documentation page titles and breadcrumbs and navigation links are set up? When I write my own documentation, I keep titles and trails and navigation paths and terms the same so people aren't going down the wrong path or having frustrating conversations from miscommunications caused by inconsistencies.

Also, is this even fixable? I know it's an older version of Symfony, but our team and clients will still be having conversations about them, and some of these pages have caused confusion and sometimes arguments because somebody was on the wrong page or section based on inconsistent terminology.

**Comment by javiereguiluz** [comment]
I'm sorry about this issues.

Recently we decided to revamp Symfony Docs on symfony.com. We now display the table-of-contents of the current page and we no longer display that long global table-of-contents. I hope things are better now. Thanks.
