### ISSUE TITLE
[Uid] Add UuidV7 and UuidV8

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17258]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47525
| PR author(s) | @nicolas-grekas
| Merged in    | 6.2

**Comment by JohJohan** [comment]
I would like to pick this up

**Comment by javiereguiluz** [comment]
Thanks @JohJohan. All information about UIDs is located in this page: https://github.com/symfony/symfony-docs/blob/6.2/components/uid.rst so please, update its contents as needed to document the new UUID versions. Thanks a lot!
