### ISSUE TITLE
Defining test DATABASE_URL: docs differ from behavior

### ISSUE THREAD

**Issue by truckee** [symfony/symfony-docs#17255]
Projects created with v6.1.4 appear to assume that the name of a test database will be, by definition, the name of the dev/prod database appended by `_test`. This is not reflected in the [documentation](https://symfony.com/doc/current/testing.html#customizing-environment-variables). Isn't this behavior somewhat dangerous - using the same `DATABASE_URL...` in both environments?

**Comment by xabbuh** [comment]
Are you sure about that? Looking at the Doctrine recipe I do not really see where this assumption should be coming from. 🤔

**Comment by truckee** [comment]
I observed the behavior on two Windows machines, beginning with fresh
installations of Symfony 6.1 webapps. If the behavior cannot be replicated
elsewhere I'm prepared to believe there is something unique to my
environment.

**Comment by xabbuh** [comment]
Are you using the Symfony CLI and/or a Docker setup?

**Comment by truckee** [comment]
I'm using the Symfony CLI version 5.4.13.

**Comment by xabbuh** [comment]
Can you create a small application that exposes this behaviour on your end and publish it on GitHub? I will try to check it out on my machine and try to see if I can reproduce this.

**Comment by truckee** [comment]
Well, whatever the problem was it has now resolved itself. I am unable to
reproduce the behavior on either system.

Thanks, though, for getting me to sort this out. I withdraw the issue.

**Comment by xabbuh** [comment]
👍 Cool, closing here for now then. But we can of course reopen once you reexperience it.
