### ISSUE TITLE
[TwigBundle] add option for configuring custom HTML to text converter s…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17262]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47536
| PR author(s) | @xabbuh
| Merged in    | 6.2

**Comment by wouterj** [comment]
This new `twig.mailer.html_to_text_converter` option should be documented on https://symfony.com/doc/current/reference/configuration/twig.html and we can probably add a little tip in https://symfony.com/doc/current/mailer.html#text-content
