### ISSUE TITLE
[Notifier] [RocketChat] Updated RocketChatOptions

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17289]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47581
| PR author(s) | @Léo VINCENT, @lvinc71
| Merged in    | 6.2

**Comment by fabpot** [comment]
I think this is something that should be documented in the README file of the bridge and not in the docs (the same goes for anything specific to one bridge). WDYT?

**Comment by xabbuh** [comment]
I agree with Fabien.

**Comment by OskarStark** [comment]
We already have specific stuff for MS Teams, Slack etc. in the docs. I am for documenting such special use cases not in the README.

**Comment by fabpot** [comment]
Right, I would suggest to move MS teams/Slack/... specificities in the README files. These bridges are not maintained by the core team but by the community.

**Comment by OskarStark** [comment]
Ok then
