### ISSUE TITLE
[Ux] Add/Update docs to show new `make:twig-component` in MakerBundle

### ISSUE THREAD

**Issue by jrushlow** [symfony/symfony-docs#17292]
Re: https://github.com/symfony/maker-bundle/pull/1019

@weaverryan suggested updating the docs for this

`make:twig-component` released in MakerBundle [`v1.46.0`](https://github.com/symfony/maker-bundle/releases/tag/v1.46.0)

cc @kbond

**Comment by kbond** [comment]
See https://github.com/symfony/ux/issues/480. You can close this issue (I don't have the ability).
