### ISSUE TITLE
Add context option to configure the indentation of nested nodes for `YamlEncoder`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17306]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47243
| PR author(s) | @dbu
| Merged in    | 6.2

**Comment by dbu** [comment]
i created https://github.com/symfony/symfony-docs/pull/17305 which mentions the yaml indentation option.

the available context options are not documented unfortunately, i tried to point to the configuration builders at least.
