### ISSUE TITLE
Horizontal scroll on mobile devices on pages with embedded diagrams

### ISSUE THREAD

**Issue by dzhebrak** [symfony/symfony-docs#17311]
Horizontal scroll appears on mobile devices on pages with embedded diagrams.

For example:

- https://symfony.com/doc/current/security.html#authentication-events
- https://symfony.com/doc/6.2/components/serializer.html
- https://symfony.com/doc/current/form/form_themes.html#form-fragment-naming

This can be fixed by adding the following css:

```css
.ui-prose object {
    max-width: 100%;
}
```

**Comment by javiereguiluz** [comment]
Dmitry thanks for reporting this and sorry it took us so long to fix it. This was finally fixed in production.
