### ISSUE TITLE
[Validator] File: add option to check extension

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17316]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47710
| PR author(s) | @dunglas
| Merged in    | 6.2

**Comment by wouterj** [comment]
We should document this new `extensions` option, which checks file extension and whether it matches allowed mime types, in the reference documentation for this constraint: https://symfony.com/doc/current/reference/constraints/File.html

@dunglas are you willing to open a PR for this? :)

**Comment by dunglas** [comment]
@wouterj done https://github.com/symfony/symfony-docs/pull/17414
