### ISSUE TITLE
Recommended referencing for command exit code style

### ISSUE THREAD

**Issue by andrew-demb** [symfony/symfony-docs#17324]
Is there any reason not to use `self::SUCCESS` instead of `Command::SUCCESS` in the snippet from https://symfony.com/doc/current/console.html#creating-a-command ?

```php
// src/Command/CreateUserCommand.php
// ...
class CreateUserCommand extends Command
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // ...

        // return this if there was no problem running the command
        // (it's equivalent to returning int(0))
        return Command::SUCCESS;

        // or return this if some error happened during the execution
        // (it's equivalent to returning int(1))
        // return Command::FAILURE;

        // or return this to indicate incorrect command usage; e.g. invalid options
        // or missing arguments (it's equivalent to returning int(2))
        // return Command::INVALID
    }
}
```

**Comment by javiereguiluz** [comment]
Although both are the equivalent, `self::SUCCESS` is a bit confusing because it looks like something that you have defined yourself in the class. However, `Command::SUCCESS` looks like something that Symfony has defined for you.

I'll keep this open to read more opinions about this. Thanks!

**Comment by javiereguiluz** [comment]
I've asked in Symfony Slack and most people seem to be using `Command::SUCCESS` too, so let's keep it for now.

@andrew-demb thanks for creating this issue because it made us reconsider if this was still a good/common practice. Thanks.
