### ISSUE TITLE
[Form] Add Stimulus example to Form Collections page?

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#17355]
@weaverryan What about showing the Stimulus way of doing it at https://symfony.com/doc/current/form/form_collections.html#allowing-new-tags-with-the-prototype ?
If I write it, will you merge it?
If yes: It's probably better to *add* it to the existing Vanilla-JS code (e.g. with an own heading "Using Stimulus" below), rather than *replace* it?

**Comment by weaverryan** [comment]
I'd say yes, 👍!

My instinct would be to ADD it - e.g. a "JavaScript with Stimulus" and "JavaScript with Vanilla JS", but perhaps others will think we should be more opinionated in favor of Stimulus. But either way, NOT showing how this is done in Stimulus is a diss\service currently.

**Comment by ThomasLandauer** [comment]
Please take a look: https://github.com/symfony/symfony-docs/pull/17364

**Comment by javiereguiluz** [comment]
Closing as fixed in #17364.
