### ISSUE TITLE
[DependencyInjection] Allow injecting the current env into php config c…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17367]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47906
| PR author(s) | @HypeMC
| Merged in    | 6.2

**Comment by wouterj** [comment]
We don't have any documentation about which parameters are accepted in the closure. Maybe it's a good idea to add them somewhere in the Service Container guide.

**Comment by wouterj** [comment]
As for the specific use-case, it seems like we only documented the `#[When]` attribute, not the other formats: https://symfony.com/doc/current/service_container.html#limiting-services-to-a-specific-symfony-environment I think we should add them to the lowest version they apply (5.4?) and use the `string $env` parameter in the 6.2 branch after this change was merged up.
