### ISSUE TITLE
[SecurityBundle] Allow specifying attributes for `RequestMatcher`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17377]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45907
| PR author(s) | @freiondrej-lmc
| Merged in    | 6.2

**Comment by mdoutreluingne** [comment]
I find this new feature very interesting, I would like to document it. But I don't know where to document this, may be [here](https://symfony.com/doc/6.2/security.html#securing-url-patterns-access-control) and [here](https://symfony.com/doc/6.2/security/access_control.html#1-matching-options)? Especially as I have the impression that this feature is only available for the YAML file format.

**Comment by wouterj** [comment]
Hi @mdoutreluingne. Thanks for your enthusiasm about this feature :)

I would suggest documenting it only in https://symfony.com/doc/6.2/security/access_control.html#1-matching-options (Both attributes and route). The configuration supports all formats, but don't worry if you can't find out the XML or PHP format - we can help with that after you've opened a pull request!
