### ISSUE TITLE
[SecurityBundle] Deprecate the `enable_authenticator_manager` option

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17375]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47890
| PR author(s) | @chalasr
| Merged in    | 6.2

**Comment by wouterj** [comment]
We've already applied the necessary changes to the 6.2 here, thanks to @l-vo ! https://github.com/symfony/symfony-docs/commit/1c76da83b90a2c5c0358edea3d8656c7812f8efd
