### ISSUE TITLE
[HttpClient] Add support for "friendsofphp/well-known-implementations"

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17387]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47950
| PR author(s) | @nicolas-grekas
| Merged in    | 6.2

**Comment by wouterj** [comment]
Is there anything to document here, @nicolas-grekas ?

**Comment by fabpot** [comment]
I don't think so, especially as there are discussions about doing it differently (at least, with a different package).
