### ISSUE TITLE
[HttpClient] Add `withOptions()` to `HttplugClient` and `Psr18Client`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17382]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47936
| PR author(s) | @nicolas-grekas
| Merged in    | 6.2

**Comment by wouterj** [comment]
To document this, I think we can add a little code example to https://symfony.com/doc/current/http_client.html#httplug and https://symfony.com/doc/current/http_client.html#psr-18-and-psr-17
