### ISSUE TITLE
[Serializer] Add `SerializedPath` annotation to flatten nested attribut…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17389]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#43534
| PR author(s) | @boenner
| Merged in    | 6.2

**Comment by wouterj** [comment]
Hi @boenner. Thank you for contributing this feature! Do you have time and motivation to also write some docs about it? :)

I think the best place would be a new section right after ["[Using Serialization Groups Attributes"](https://symfony.com/doc/6.2/serializer.html#using-serialization-groups-attributes)"](https://symfony.com/doc/6.2/serializer.html#using-serialization-groups-attributes).
