### ISSUE TITLE
Outdated symfony cli setup.deb.sh url?

### ISSUE THREAD

**Issue by itodor** [symfony/symfony-docs#17403]
Hi, one of my docker images needs to install symfony CLI and it all worked great last week until today when I noticed it failing:
(from official symfony docs)
```
curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash
sudo apt install symfony-cli
```

This url seems to be down (im getting 402) so Im not sure if its just temporal outage or am I missing something but I'm getting: 

```
+ curl -1sLf https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh
+ bash
+ apt install symfony-cli
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package symfony-cli
```

**Comment by OskarStark** [comment]
friendly ping @fabpot

**Comment by fabpot** [comment]
See https://github.com/symfony-cli/symfony-cli/issues/205
