### ISSUE TITLE
Make specific section only searchable

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#17410]
I really like that a whole topic in symfony docs is an a one whole page. But sometimes when I'm using the **browser search** it can be anoying that I jump out of the section I'm currently reading.

For this I did hack the following script together:

```js
var headlines = document.querySelectorAll('.section h2');
var buttons = document.querySelectorAll('.section h2 button');

buttons.forEach((button) => {
    button.remove();
})

headlines.forEach((headline) => {
    const button = document.createElement('button');
    button.style = 'margin-left: auto; font-size: 12px; padding: 2px 12px; border: none';
    button.title = 'Allows to use the browser search only on this specific section by hiding all other content.';
    headline.style = 'display: flex';
    
    button.innerText = 'Only';
    button.onclick = () => {
         var sibling = button.parentNode.parentNode;

          while (sibling = sibling.previousSibling) {
              if (!sibling.hasAttribute) {
                   continue;
              }

              if (!sibling.hasAttribute('style')) {
                  sibling.style = 'visibility: hidden';
              } else {
                  sibling.removeAttribute('style');
              }
          }
          var sibling = button.parentNode.parentNode;
          while (sibling = sibling.nextSibling) {
              if (!sibling.hasAttribute) {
                   continue;
              }

              if (!sibling.hasAttribute('style')) {
                  sibling.style = 'visibility: hidden';
              } else {
                  sibling.removeAttribute('style');
              }
          }
    };
    headline.appendChild(button);
});
```

Which adds a button next to the headline section and set the other content so to `visiblity: hidden` this way I can now only search on the `Section` I'm currently looking at, would be interested to have such feature available in the docs itself. I'm not using display none as that did had a bad UX about jumping page. And visibility hidden reminds you there is more available but hidden.

![show-only-section](https://user-images.githubusercontent.com/1698337/199712734-a6b34962-dd5c-4a6a-a151-3100c6be8875.gif)

**Comment by javiereguiluz** [comment]
Alexander, thanks for this proposal ... but I'm afraid we need to close this as "won't fix". The proposed feature looks too niche and the behavior looks very uncommon to appeal to most of our visitors. Thanks for understanding!

**Comment by alexander-schranz** [comment]
@javiereguiluz no problem thanks for your feedback.
