### ISSUE TITLE
Using `POST` method instead of a `GET` method on the logout section.

### ISSUE THREAD

**Issue by user-error-pixel** [symfony/symfony-docs#17412]
On `https://github.com/symfony/symfony-docs/blob/6.2/security.rst` it might be a good idea to use `POST` as the preferred method when using the logout functionality.
- https://stackoverflow.com/a/14587231

**Comment by javiereguiluz** [comment]
Let's ask @chalasr to see if he thinks that this proposal is a good idea. Thanks.

**Comment by chalasr** [comment]
Sounds good to me 👍  POST is safer in all situations

**Comment by javiereguiluz** [comment]
Fixed in #18353. Thanks @omatamix and thanks Robin for reviewing this.

**Comment by seb-jean** [comment]
We then no longer use `logout_path()` ?
