### ISSUE TITLE
Impossible to install Symfony with composer using PowerShell

### ISSUE THREAD

**Issue by mdoutreluingne** [symfony/symfony-docs#17423]
I have a version not found error for the Symfony installation with composer using the command indicated in the [documentation](https://symfony.com/doc/5.4/setup.html#creating-symfony-applications): 
`composer create-project symfony/skeleton:"^5.4" my_project_directory`
![image](https://user-images.githubusercontent.com/53557695/201321647-7c1c1bd8-de96-4e2f-867b-4a9b952eed69.png)

**Possible solution**

I need to add '*' to specify the version number, so I need to replace the version number to `"^5.4.*"` instead of `"^5.4"`.

If this issue is confirmed for other people, I would create a PR.

**Comment by wouterj** [comment]
This command works for me (using the Fish shell on Linux).

Can you try replacing the double quotes with single ones? `composer create-project symfony/skeleton:'^5.4' my_project_directory`

**Comment by OskarStark** [comment]
Same for me:
<img width="469" alt="CleanShot 2022-11-11 at 12 08 24@2x" src="https://user-images.githubusercontent.com/995707/201328105-fba150aa-d1b4-4411-a0ec-f3e15f95d1d7.png">

<img width="886" alt="CleanShot 2022-11-11 at 12 08 30@2x" src="https://user-images.githubusercontent.com/995707/201328117-c1a7071a-4602-405d-b282-9d03150e0cd4.png">

**Comment by mdoutreluingne** [comment]
I am using PowerShell 7.2.7.

Thank you for your answer. However, using another terminal it works. I didn't know that it depends on the terminal you have.

I close this issue. Thank you!
