### ISSUE TITLE
[Service container] Remove example with deprecated Swift Mailer

### ISSUE THREAD

**Issue by Xesau** [symfony/symfony-docs#17433]
In https://symfony.com/doc/current/service_container/tags.html, the section "[Creating custom Tags](https://symfony.com/doc/current/service_container/tags.html#creating-custom-tags)" has an example using Swift Mailer. Since Swift Mailer has been deprecated/abandoned, an alternative example should be used.

**Comment by javiereguiluz** [comment]
Fixed in #17533. Thanks.
