### ISSUE TITLE
[SecurityBundle] Deprecate enabling bundle and not configuring it

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17467]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48043
| PR author(s) | @alamirault
| Merged in    | 6.3

**Comment by alamirault** [comment]
We can maybe add `deprecated:: 6.3` on this page https://symfony.com/doc/current/security.html, but there is no section configuration, so I don't know where is the best place

**Comment by javiereguiluz** [comment]
The deprecation/error message in the code is very clear and easy to understand. So, I'd say we should do what we do in other similar cases: not add anything special in the docs and rely on this nice deprecation/error message.

**Comment by xabbuh** [comment]
I agree with Javier.
