### ISSUE TITLE
Missing Caddy Webserver Documentation

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#17471]
I think it would be great to have also offical caddy documentation for symfony. There currently is only nginx and apache: https://symfony.com/doc/current/setup/web_server_configuration.html

Sadly I'm not yet using caddy so I don't know yet about what best practices are there to contribute one. But thought I create an issue and maybe someone want to tackle it :).

**Comment by 94noni** [comment]
Perhaps leveraging https://github.com/dunglas/symfony-docker
Also see https://github.com/symfony/symfony-docs/issues/17428

**Comment by wouterj** [comment]
Good idea! I've proposed a config (based on the existing Nginx one) in #17597
