### ISSUE TITLE
Living on the edge for 6.2 is missing a blog post

### ISSUE THREAD

**Issue by sbusch** [symfony/symfony-docs#17491]
Found no way to contribute to the "LIving on the edge" category, so I'm filing an issue:

The blog post [Revisiting Lazy-Loading Proxies in PHP](https://symfony.com/blog/revisiting-lazy-loading-proxies-in-php) is missing on [Living on the edge for 6.2](https://symfony.com/blog/category/living-on-the-edge/6.2)

(All others posts listed from [Symfony 6.2 curated new features](https://symfony.com/blog/symfony-6-2-curated-new-features) are referenced, this is the only one missing)

**Comment by javiereguiluz** [comment]
I'm sorry about this. However, the feature that groups "Living on the edge" posts requires that the posts are title with "New in Symfony X.Y: ...". Now it's too late to change the blog post; I'm sorry, but we must keep it this way. Thanks!
