### ISSUE TITLE
[Notifier] Add Line bridge

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-docs#17499]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48466
| PR author(s) | @kurozumi
| Merged in    | 6.3

**Comment by mdoutreluingne** [comment]
This issue can be closed because the Line bridge has already been added [here](https://symfony.com/doc/6.3/notifier.html#chat-channel)

**Comment by javiereguiluz** [comment]
Closing as fixed then. Thanks @mdoutreluingne.
