### ISSUE TITLE
[Notifier] Link broken in `Using events` chapter

### ISSUE THREAD

**Issue by elementaire** [symfony/symfony-docs#17503]
In https://github.com/symfony/symfony-docs/blob/6.2/notifier/events.rst, which class are we talking with ``...\\..\\Transport`` ?
In the doc (https://symfony.com/doc/6.2/notifier/events.html), it is converted to `class:11a4dae351db4f5052327d08c6ca0c3f1b7b22a8`.

**Comment by OskarStark** [comment]
I openend a PR: https://github.com/symfony/symfony-docs/pull/17504
