### ISSUE TITLE
[Console] #47809 remove exit() call in last SignalHandler

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17544]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48299
| PR author(s) | @akuzia
| Merged in    | 6.3

**Comment by javiereguiluz** [comment]
@nicolas-grekas do you think this change is something we should mention in the docs or is it an internal detail? Thanks.

**Comment by alexandre-daubois** [comment]
From what I understood of the PR and context, I think we can add a little something to the documentation. I'm giving it a try, I'll let you tell me if what I add is relevant 😄
