### ISSUE TITLE
`When` constraint is missing in the list

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-docs#17547]
The [When](https://symfony.com/doc/current/reference/constraints/When.html) constraint is missing in the [Consraints Overview](https://symfony.com/doc/current/reference/constraints.html)

cc @igst

**Comment by OskarStark** [comment]
@symfony/team-symfony-docs there is something strange, when I check the overview, it is already there (line 75), but the link to the constraint itself is not rendered 🤔 

https://github.com/symfony/symfony-docs/blob/db4474f201301f6c61cc6468bcc4330a7f34587d/reference/constraints.rst?plain=1#L69-L81

Any clue?

**Comment by MrYamous** [comment]
Hi, not sure and I didn't try yet but seems missing in reference/constraints/map.rst.inc

https://github.com/symfony/symfony-docs/blob/ac5034851dae008d0be39b4da615a4d94f4cc966/reference/constraints/map.rst.inc#L92-L102

**Comment by OskarStark** [comment]
Indeed, but for what is the file mentioned in my comment then?

**Comment by wouterj** [comment]
The toctree is for both a TOC and file discovery in rSt. The TOC you linked is hidden (see line 5), it's there for file discovery.

**Comment by OskarStark** [comment]
@MrYamous open for a PR
