### ISSUE TITLE
[DomCrawler][FrameworkBundle] Add `assertSelectorCount`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17543]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48424
| PR author(s) | @curlycarla2004
| Merged in    | 6.3

**Comment by OskarStark** [comment]
Are you open to tackle this one too @curlycarla2004?

**Comment by javiereguiluz** [comment]
Closing as fixed in #17640.
