### ISSUE TITLE
[DependencyInjection] Attribute documentation

### ISSUE THREAD

**Issue by kbond** [symfony/symfony-docs#17563]
I'm opening this as a meta issue to track the documentation status of the DI attributes. I ran into some confusion about `AsTaggedItem` in https://github.com/symfony/symfony/issues/48532 which prompted me to look for docs which are missing.

- [x] `AsDecorator` https://github.com/symfony/symfony-docs/pull/16746
- [x] `AsTaggedItem` https://github.com/symfony/symfony-docs/pull/17694
- [x] `Autoconfigure` and `AutoconfigureTag` https://github.com/symfony/symfony-docs/pull/17695
- [x] `Autowire` https://github.com/symfony/symfony-docs/pull/16629
- [x] `MapDecorated` https://github.com/symfony/symfony-docs/pull/16746
- [x] `TaggedIterator` https://github.com/symfony/symfony-docs/pull/17652
- [x] `TaggedLocator` https://github.com/symfony/symfony-docs/pull/17662
- [x] `Target` https://github.com/symfony/symfony-docs/pull/17696
- [x] `When` https://github.com/symfony/symfony-docs/pull/16313

**Comment by alexandre-daubois** [comment]
Hey! Little update on this one.
TaggedIterator: https://github.com/symfony/symfony-docs/pull/17652 (merged)
TaggedLocator: https://github.com/symfony/symfony-docs/pull/17662 (merged)
AsTaggedItem: https://github.com/symfony/symfony-docs/pull/17694
Autoconfigure + AutoconfigureTag : https://github.com/symfony/symfony-docs/pull/17695
Target: https://github.com/symfony/symfony-docs/pull/17696

**Comment by kbond** [comment]
Awesome work @alexandre-daubois! I've updated the description.

**Comment by OskarStark** [comment]
I updated the checkboxes, only one left 👍

**Comment by OskarStark** [comment]
All done
