### ISSUE TITLE
[HttpFoundation] Create migration for session table when pdo handler is…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17569]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48059
| PR author(s) | @alli83
| Merged in    | 6.3

**Comment by alli83** [comment]
ok i will open a PR on 6.3 symfony-docs

**Comment by alli83** [comment]
Doc PR: https://github.com/symfony/symfony-docs/pull/17844

**Comment by javiereguiluz** [comment]
Closing as fixed in #17844.
