### ISSUE TITLE
[SecurityBundle] Set request stateless when firewall is stateless

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17581]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48044
| PR author(s) | @alamirault
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by alamirault** [comment]
I didn't find any doc on stateless firewall.

I think we could add section "Stateless" after https://symfony.com/doc/current/reference/configuration/security.html#firewall-context in 5.4 and add "versionadded" for branch 6.3.

Is it ok ?

**Comment by OskarStark** [comment]
Sounds like a plan 👌🏻

**Comment by javiereguiluz** [comment]
Closing as fixed in #17648

**Comment by alamirault** [comment]
Hello @javiereguiluz,

https://github.com/symfony/symfony-docs/pull/17648 document firewall stateless for 5.4 only.

I now created https://github.com/symfony/symfony-docs/pull/18108 for the new behavior on 6.3
