### ISSUE TITLE
[SecurityBundle] Improve support for authenticators that don't need a u…

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#17585]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48594
| PR author(s) | @wouterj
| Merged in    | 6.3

**Comment by alexandre-daubois** [comment]
I searched a lot on where to add this. But we never talk about authenticator factories. We may add something [here](https://symfony.com/doc/current/security/custom_authenticator.html) to talk about those factories, but I find it very internal and I'm not sure has its place here. Any thoughts? @OskarStark maybe?

**Comment by wouterj** [comment]
The factory thing is indeed internal. The user affecting bit of this feature is that if you use a *stateless* firewall and you use an authentication method that uses self-contained tokens (e.g. JWT tokens with all claims in the token itself), you no longer have to configure a `user_provider` / save the users in the database.

I think the best place to document this is to add a new section to https://symfony.com/doc/current/security/access_token.html , given that is the only authenticator supporting self-contained tokens in Symfony at the moment.
