### ISSUE TITLE
[Security] Allow custom user identifier for X509 authenticator

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17580]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48200
| PR author(s) | @Spomky
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by Spomky** [comment]
Hi @fabpot,

Thank you for this reminder. I created a PR for this new parameter.

Regards.

**Comment by javiereguiluz** [comment]
Fixed in #17582.
