### ISSUE TITLE
Remove some references to 2.x, 3.x, 4.x version

### ISSUE THREAD

**Issue by alamirault** [symfony/symfony-docs#17583]
Hi, 

I found some places were we have references to EOF versions.
Are you ok if we remove/rework these statements on 6.3 branch ?

## Symfony 2 references:

contributing/code/bc.rst

> This promise was introduced with Symfony 2.3 and does not apply to previous versions of Symfony.

## Symfony 3 references:

service_container.rst

> Prior to Symfony 3.3, all services and (typically) arguments were 

components/config/definition.rst

> ``ifEmpty()`` (since Symfony 3.2)

## Symfony 4 references:

profiler.rst

> The possibility to use a matcher to enable the profiler conditionally was removed in Symfony 4.0.

> Symfony Profiler cannot be enabled/disabled conditionally using matchers, because
that feature was removed in Symfony 4.0. However, you can use...

components/browser_kit.rst

> In Symfony versions prior to 4.3, the BrowserKit component could only make
    internal requests to your application. Starting from Symfony 4.3, this
    component can also...

components/event_dispatcher/container_aware_dispatcher.rst

> The ``ContainerAwareEventDispatcher`` was removed in Symfony 4.0. Use
    ``EventDispatcher`` with closure-proxy injection instead.

components/filesystem/lock_handler.rst

> The ``LockHandler`` utility was removed in Symfony 4.0. Use the new Symfony :doc:`Lock component </components/lock>` instead.

**Comment by OskarStark** [comment]
IMHO yes, maybe we man make sure we have some examples/docs for all current usages 👌🏻
