### ISSUE TITLE
You must configure a "Symfony\Component\Mime\BodyRendererInterface" when a "Symfony\Bridge\Twig\Mime\TemplatedEmail" instance has a text or HTML template set

### ISSUE THREAD

**Issue by souna23** [symfony/symfony-docs#17584]
You must configure a "Symfony\Component\Mime\BodyRendererInterface" when a "Symfony\Bridge\Twig\Mime\TemplatedEmail" instance has a text or HTML template set.

i did follow this script 
 
use Symfony\Bridge\Twig\Mime\TemplatedEmail;

$email = (new TemplatedEmail())
    ->from('fabien@example.com')
    ->to(new Address('ryan@example.com'))
    ->subject('Thanks for signing up!')

    // path of the Twig template to render
    ->htmlTemplate('emails/signup.html.twig')

    // pass variables (name => value) to the template
    ->context([
        'expiration_date' => new \DateTime('+7 days'),
        'username' => 'foo',
    ])
;

**Comment by xabbuh** [comment]
Which exact versions do you have installed?

**Comment by souna23** [comment]
this is from composer.lock

            "name": "symfony/mailer",
            "version": "v6.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/mailer.git",
                "reference": "7b355fca167fa5302c77bccdfa0af4d7abc6bd8c"
            },

**Comment by souna23** [comment]
this is from composer.lock

            "name": "symfony/mailer",
            "version": "v6.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/mailer.git",
                "reference": "7b355fca167fa5302c77bccdfa0af4d7abc6bd8c"
            },

**Comment by xabbuh** [comment]
Can you please update to 6.2.2 and check again?

**Comment by souna23** [comment]
thank you it works well now
