### ISSUE TITLE
Impossible to disable user deprecated errors

### ISSUE THREAD

**Issue by NikitaObukhov** [symfony/symfony-docs#17592]
Symfony: symfony/framework-bundle             v5.4.14| v6.1.7
symfony/error-handler                v5.4.15| v6.1.7

Same is with latest 5 and 6 versions. There is no docs of how to disable these useless messages which make impossible to use this framework.

The whole output is messed with hundreds of "[info] User Deprecated:" errors. Impossible to use bin/console - hunderds of deprecation messages. Each request takes multiple seconds because of very slow error handling.

I tried according to stackoverflow (no docs regarding this. You can try "disable deprecated warning site:symfony.com" - no results):
framework.yaml
    php_errors:
        log: false

I tried:
error_reporting(0) - does not work

Actually nothing works. Lots of issues - no solution.

https://github.com/symfony/symfony/issues/35575#issuecomment-629377435

The only working way to handle is to override boot method of App\Kernel:

```
    public function boot()
    {
        parent::boot();
        ErrorHandler::register(null, false)->setLoggers([
            \E_DEPRECATED => [null],
            \E_USER_DEPRECATED => [null],
        ]);
    }
```

**Comment by andriusvo** [comment]
Have you found any proper solution to remove deprecation logs?

**Comment by javiereguiluz** [comment]
In the docs you can see some options to disable the output verbosity of deprecations and to even disable the deprecation helper entirely. See https://symfony.com/doc/current/components/phpunit_bridge.html#disabling-the-verbose-output

So, let's close this one as "fixed". Thanks.

**Comment by andriusvo** [comment]
@javiereguiluz you mentioned disabling logs in PHPUnit, but topic author means in general, the same problem for me. Not sure if it should be closed 🤔

**Comment by javiereguiluz** [comment]
Yes, you can only use these config options when using the PHPUnitBridge component.

If you are not using that component, you'll need to use something like the code shown in the description of this issue (the lines added to the `boot()` method) or implement some custom solution on your own. But, I think that's outside of the scope of the Symfony Docs related to deprecations. Sorry!
