### ISSUE TITLE
components/filesystem.rst ~ character not rendered in public documentation

### ISSUE THREAD

**Issue by derMart** [symfony/symfony-docs#17604]
~ Character looks good in source markdown file: https://github.com/symfony/symfony-docs/blame/6.2/components/filesystem.rst#L346 but it is rendered as space in the resulting public html:

![grafik](https://user-images.githubusercontent.com/1069456/209103683-f2b83d1c-8fa2-4810-8d87-73d6ea83ddd3.png)

**Comment by MrYamous** [comment]
Nice catch, i guess it's converted to a nbsp by a parser if i correctly understand what is happening

**Comment by OskarStark** [comment]
We should use backticks instead of quotes

**Comment by javiereguiluz** [comment]
Fixed in #17624.
