### ISSUE TITLE
[HttpKernel] Allow using `#[HttpStatus]` for setting status code and he…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17602]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48352
| PR author(s) | @angelov
| Merged in    | 6.3

**Comment by fabpot** [comment]
Renamed to WithHttpStatus in symfony/symfony#48876

**Comment by javiereguiluz** [comment]
Closing as fixed in #17692.
