### ISSUE TITLE
[Notifier] GoogleChat CardsV1 is deprecated we must use cardsV2 instead

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17608]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48616
| PR author(s) | @daifma
| Merged in    | 6.3

**Comment by mdoutreluingne** [comment]
I think it is not necessary to document this depreciation because because we do not have examples of code with GoogleChatOptions.
