### ISSUE TITLE
[Validator] Add `getConstraint()` method to `ConstraintViolationInterfa…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17610]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48671
| PR author(s) | @syl20b
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by mdoutreluingne** [comment]
I think it is not necessary to document this depreciation because we do not document the interface `ConstraintViolationInterface` and the method `getConstraint()` .

What do you think about this?

**Comment by syl20b** [comment]
I agree with you.

**Comment by javiereguiluz** [comment]
Closing as fixed in #17721.
