### ISSUE TITLE
[DependencyInjection] Target Attribute must fail if the target does not…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17611]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48707
| PR author(s) | @rodmen
| Merged in    | 6.3

**Comment by javiereguiluz** [comment]
I'm closing this as "won't document" because when this situation occurs, Symfony displays an informative error message, so it's trivial to fix it. Thanks.
