### ISSUE TITLE
Best practices for the suffix of form class names

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony-docs#17619]
Hello,

It would be interesting to have the best practice for the suffix of form class names. For example, would it be `/src/Form/TaskType.php` or `/src/Form/TaskFormType.php`? I find the 2 suffixes on the internet: 

- https://github.com/the-fast-track/book-6.2-1/blob/main/src/Form/CommentFormType.php
- https://github.com/symfony/demo/blob/main/src/Form/CommentType.php

Then we may be able to modify the [Forms section of the Best Practices page](https://symfony.com/doc/current/best_practices.html#forms).

**Comment by javiereguiluz** [comment]
I think that in Symfony Docs, Symfony Demo, etc. we always use just `Type` as the suffix of form classes.

**Comment by OskarStark** [comment]
cc @fabpot as you are responsible for the book

**Comment by fabpot** [comment]
The rename will be part of the next version of the book.

**Comment by seb-jean** [comment]
Thanks @fabpot
