### ISSUE TITLE
[DependencyInjection] Exclude referencing service (self) in `TaggedIter…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17656]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48685
| PR author(s) | @chalasr
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by chalasr** [comment]
From what I see, this could be addressed by adding a small section presenting the `exclude` concept for tagged iterators and locators, mentioning the new default btw.  If I'm right, that could be done in `service_container/tags.rst` next to `
Tagged Services with Index`

**Comment by javiereguiluz** [comment]
Closing as fixed in #17709.
