### ISSUE TITLE
[FrameworkBundle] Add `extra` attribute for HttpClient Configuration

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17659]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48797
| PR author(s) | @voodooism
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by alamirault** [comment]
Documentation is merged, we can close this issue :smile:
