### ISSUE TITLE
[Form] explain how to use `getOrigin()`

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#17670]
`getOrigin()` is mentioned in https://symfony.com/doc/5.4/components/form.html#accessing-form-errors

This documentation is evasive, how people should use `getOrigin()`? I tried and failed, see #17669

Source: https://github.com/symfony/symfony-docs/blob/fd19324c88e9d2447272931e1083f8e1d872ac7f/components/form.rst?plain=1#L755-L757

**Comment by xabbuh** [comment]
Maybe we should remove that sentence. I am not sure it really adds any value.
