### ISSUE TITLE
[Config] Missing example of `$_ENV` usage for environment variables

### ISSUE THREAD

**Issue by miqrogroove** [symfony/symfony-docs#17693]
After reading the Configuration / Environment Variables docs multiple times, I realized the reason it wasn't making sense was that there was no example of using the `$_ENV` superglobal array in PHP to actually read data from the `.env` configuration.  In fact, the only mention of it was this sentence about halfway through the document:

> The .env file is read and parsed on every request and its env vars are added to the $_ENV & $_SERVER PHP variables.

https://symfony.com/doc/5.4/configuration.html

When I found that, it all made perfect sense to me.  There should be an obvious example showing how the `.env` file is intended to be used in PHP app code so that readers don't mistakenly scour the page looking for an API.

**Comment by javiereguiluz** [comment]
Fixed in #17735.

**Comment by miqrogroove** [comment]
This is vague and unhelpful:  "the configuration system provides a better way of working with env vars."

Please add a link to the "Accessing Configuration Parameters" heading later in the article.

I think it would be nice to also mention this somewhere in the Configuration Files section.  In other words, now that you know how to define the config, you'll need to scroll to the end of the article to learn how to use it.

Additionally, the word "Parameters" is being used to mean two different concepts in this article, adding to the confusion.  The Configuration Parameters section explictly distinguishes itself from configuration values.  So why is the other header "Accessing Configuration Parameters" rather than "Access Configuration Values"?
