### ISSUE TITLE
[FrameworkBundle] Rename service `notifier.logger_notification_listener` to `notifier.notification_logger_listener`

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17697]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48678
| PR author(s) | @ker0x
| Merged in    | 6.3

**Comment by alamirault** [comment]
I found no reference of `notifier.logger_notification_listener`

**Comment by OskarStark** [comment]
Thanks for the research, let's close this issue then
