### ISSUE TITLE
Allow Usage of ContentId in html

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17703]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48901
| PR author(s) | @m42e
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by javiereguiluz** [comment]
Looking at the code PR (https://github.com/symfony/symfony/pull/48901), I don't fully understand the description or the code/tests.

@m42e could you please show some scenario where this feature would be useful and a short example of how to use it? Thanks!

**Comment by m42e** [comment]
@javiereguiluz 
The major use-case is anonaddy when forwarding a mail that already has the ids in the text. The workaround would be to replace the ids with a name, which is afterwards replaced by an id again.

**Comment by javiereguiluz** [comment]
Thanks. Can you share a real example of using this feature? Of course, if you prefer, you can submit a PR yourself.

**Comment by m42e** [comment]
Here is an example, stolen from https://github.com/anonaddy/anonaddy/blob/4f47bc4f4cf15e20555e99290e09cc85e82691ba/app/Mail/ForwardEmail.php#L232

```
foreach ($this->emailInlineAttachments as $attachment) {
                        $part = new InlineImagePart(base64_decode($attachment['stream']), base64_decode($attachment['file_name']), base64_decode($attachment['mime']));

                        $part->asInline();

                        $part->setContentId(base64_decode($attachment['contentId']));
                        $part->setFileName(base64_decode($attachment['file_name']));

                        $message->attachPart($part);
                    }
```

It is using the content_id as part identification and it does not touch the body of the mail message. The original message content will still reference the content_id

**Comment by m42e** [comment]
Does this help? I don|t know how to better describe it.

**Comment by alamirault** [comment]
@m42e I tried to document this PR behavior in https://github.com/symfony/symfony-docs/pull/18817

I think we shouldn't document you're use case but be more generic.

Review is welcomed :smile:
