### ISSUE TITLE
[Form] `EnumType`: `group_by` is missing

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#17707]
`group_by` is missing on https://symfony.com/doc/current/reference/forms/types/enum.html

I'm not sure if the text from https://symfony.com/doc/current/reference/forms/types/choice.html#group-by can be reused, cause I don't know how this multi-dimensional array thing would work:

> You can group the <option> elements of a `<select>` into `<optgroup>` by passing a multi-dimensional array to choices

**Comment by alexandre-daubois** [comment]
I'm taking a look at this
