### ISSUE TITLE
Remove all `public=false`

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-docs#17704]
Since Symfony 5.4 public false is the default, so we can remove it from all config examples (yaml, php, xml).

Another nice one would be a new rule for DOCtor to ensure this in the future.

cc @alamirault 😄

**Comment by alamirault** [comment]
Do you have an example ? I found no occurence for this case (except one in alias_private.rst)

**Comment by OskarStark** [comment]
No I just didn't want to forget to check.

Let's close then
