### ISSUE TITLE
[ErrorHandler] try to read SYMFONY_PATCH_TYPE_DECLARATIONS from supergl…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17740]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48976
| PR author(s) | @xabbuh
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by xabbuh** [comment]
not sure that this is really a change we need to add to the documentation

@symfony/team-symfony-docs What do you think?
