### ISSUE TITLE
Consistency using contractions or not: `It's/It is` `You're/You are`...

### ISSUE THREAD

**Issue by alamirault** [symfony/symfony-docs#17743]
Consistency is important. We should use always contractions or not.

IMO I prefer to not use contraction for symfony-docs. Are you agree with this ?

I can make PR for each group (avoiding huge review)

## am

I found 0 occurences of `I'm`
I found 1 occurences of `I am`

## are

I found 254 occurences of `you're`
I found 162 occurences of `you are`

I found 1 occurences of `we’re`
I found 20 occurences of `we are`

I found 0 occurences of `they’re`
I found 135 occurences of `they are`

## is

I found 367 occurences of `it's`
I found 301 occurences of `it is`

## have

I found 59 occurences of `you've`
I found 250 occurences of `you have`

I found 4 occurences of `we've`
I found 20 occurences of `we have`

I found 0 occurences of `they've`
I found 11 occurences of `they have`

## will

I found 97 occurences of `you'll`
I found 250 occurences of `you will`

I found 9 occurences of `it'll`
I found 121 occurences of `it will`

I found 9 occurences of `we'll`
I found 6 occurences of `we will`

I found 2 occurences of `they'll`
I found 17 occurences of `they will`

## would

I found 16 occurences of `you'd`
I found 31 occurences of `you would`

I found 0 occurences of `it'd`
I found 19 occurences of `it would`

I found 0 occurences of `we'd`
I found 2 occurences of `we would`

I found 0 occurences of `they'd`
I found 2 occurences of `they would`

**Comment by OskarStark** [comment]
Should then be ensured by a configurable doctor rule, WDYT?

**Comment by OskarStark** [comment]
@javiereguiluz @wouterj @xabbuh @weaverryan are you ok if we change it that way?
