### ISSUE TITLE
Search performance issue

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony-docs#17775]
I was looking for docs about the new MapEntity and I get exactly no results :D 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/183678/213454818-8bb44aff-a7f6-4804-812b-ca260cc160de.png">

However, after searching in this repo I found that it is documented: https://symfony.com/doc/current/doctrine.html#mapentity-options

**Comment by javiereguiluz** [comment]
We're working at the moment to improve this. So far the results are very promising, so we hope to replace the current search engine by something significantly better.

**Comment by javiereguiluz** [comment]
We're closing this as hopefully fixed by the recent migration to Meilisearch. See https://symfony.com/blog/migrating-symfony-com-search-engine-to-meilisearch
