### ISSUE TITLE
[Lock] create migration for lock table when DoctrineDbalStore is used

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17778]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48999
| PR author(s) | @alli83
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by alli83** [comment]
yes, I'm on it :)

**Comment by javiereguiluz** [comment]
Closing as fixed in #17913.
