### ISSUE TITLE
[Console] Suggestion to add Terminal documentation

### ISSUE THREAD

**Issue by feamsr00** [symfony/symfony-docs#17781]
Hello!

I have found that while Cursor has a nice write up, there no documentation on Terminal. [I wanted to follow a suggestion to request it here](https://github.com/symfony/symfony/discussions/49004).

It would also be rather illustrative to discuss how Terminal and Cursor can be used together.

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Console/Terminal.php

**Comment by javiereguiluz** [comment]
Closing as fixed in #18916.
