### ISSUE TITLE
[Cache] Add Redis Relay support

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17813]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48930
| PR author(s) | @ostrolucky
| Merged in    | 6.3

**Comment by tillkruss** [comment]
@nicolas-grekas: Can I help with this in any way?

**Comment by xabbuh** [comment]
Just from reading the code of the linked PR I would not have any idea how I could opt-in to actually use Redis Relay. So for me without any deep knowledge the most important part that we should how here is how to do the actual configuration.

**Comment by javiereguiluz** [comment]
@tillkruss the best way to help would be to review the PR that documents this feature: see #17870.

Most members of the Docs Team don't have real experience with "Redis Realy", so we need help from someone who can validate the technical side of the PR. Thanks!

**Comment by javiereguiluz** [comment]
Fixed in #17870.
