### ISSUE TITLE
[FrameworkBundle][Workflow] Register alias for argument for workflow se…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17812]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49102
| PR author(s) | @lyrixx
| Merged in    | 6.3

**Comment by lyrixx** [comment]
I'm not sure it needs to be documented

**Comment by alexandre-daubois** [comment]
I actually think it worth it to add a mention about it [here](https://symfony.com/doc/current/workflow.html#accessing-the-workflow-in-a-class)! 🙂

**Comment by javiereguiluz** [comment]
Fixed in #17824. Thanks.
