### ISSUE TITLE
Contributions to Serializer docs are paused

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#17814]
Because of the revamp in the Serializer docs (see #17783) we are pausing all changes and merges to any docs related to Serializer.

Please, don't contribute anything related to Serializer until we finish that revamp. Thanks for understanding!

Pinging the most active contributors (@alexandre-daubois, @alamirault, @94noni) and mergers (@weaverryan, @OskarStark, @xabbuh) so everybody is warned about this. Thanks!

**Comment by alexandre-daubois** [comment]
Got it :+1: 

Would it be conceivable to imagine a work like the unification of the doc of the Console component for example? As @wouterj  raised on one of my PRs, it seems that the trend is to unify the component docs rather than exploding them into several articles. If this is something that could be planned, I would be happy to take care of it for Console for instance :slightly_smiling_face:

**Comment by 94noni** [comment]
@javiereguiluz oki thx for ping :)
i've understand it is a global offer to rewrite doc on component & framework usage
do you have like a roadmap for that? and also writing in symfony/doc vs symfony/symfony 's readme?

thx

**Comment by wouterj** [comment]
Hi! Thank you both for asking how to help with the rewrites.

For now, I would suggest to let us (the doc team) do the main bulk of the work. PRs like this get pretty big, so it's easier to coordinate, review and quickly discuss approaches this way. When the bulk of the work is done, there probably still are tons of things that can be restructured or better worded that you can help with. And of course, reviews on these big PRs are also always very welcome :)

Thanks for all the work and excitement around documentation! :)

**Comment by alexandre-daubois** [comment]
Understood, good luck 💪

**Comment by alexandre-daubois** [comment]
Hey! Just a quick message to know if contributions to the serializer are still paused? :slightly_smiling_face:

**Comment by wouterj** [comment]
I have very little OSS time this month (preparing and executing a big migration at work). I hope to pick up this PR again in July.

I would say adding small sections to document new features is OK (given this is taken longer than I wanted). But let's not rewrite, restructure, add missing docs for features of historic versions, etc. as that'll just be double work and the docs have been in this state for years, so we can survive it for another couple of months.

**Comment by javiereguiluz** [comment]
I'm closing this issue because the main doc contributors are aware of it and because we're merging small changes and additions to the serializer component. We won't merge revamps or huge changes to help with the update. Thanks!
