### ISSUE TITLE
[Config] Allow enum values in EnumNode

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17863]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49098
| PR author(s) | @fancyweb
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by javiereguiluz** [comment]
Fixed in #17865.
