### ISSUE TITLE
Setting cookies within HttpClient is not documented

### ISSUE THREAD

**Issue by speller** [symfony/symfony-docs#17875]
### Symfony version(s) affected

latest

### Description

I want to pass a cookie with Symfont Http Client request. I didn't find a way to do this in the documentation: https://symfony.com/doc/current/http_client.html

### How to reproduce

-

**Comment by alexandre-daubois** [comment]
Hey, it is documented, [here](https://symfony.com/doc/current/http_client.html#cookies) :slightly_smiling_face: Passing a cookie is actually just setting the `Cookie` header to your request :+1:

**Comment by OskarStark** [comment]
Maybe we should add an example in how to use http-client and browser-kit

**Comment by alexandre-daubois** [comment]
Alright, I'm taking a look at it!

**Comment by speller** [comment]
@alexandre-daubois 
The last thing I expected from Symfony components is to build header values manually. 
Now I see that this is not a documentation issue, this is a lack of functionality.
I think all users will be happy to see the built-in functionality to set cookies without workarounds and bandaids.

**Comment by speller** [comment]
Oh, I didn't know that it's possible to use the helper class. Thank you for adding this to the document!

One more question left: how to add multiple cookies with the helper class? Convert cookie objects to strings and merge manually? Can it also be added to the document? I believe this question will arise with many developers. 
Is it possible to integrate a list of cookie objects into the client and free up users from manual operations?

**Comment by alexandre-daubois** [comment]
I also had this problem a few moments ago, actually. I tried something here https://github.com/symfony/symfony/pull/49351, we'll see where it goes :+1:
