### ISSUE TITLE
[Notifier] Introduce FromNotificationInterface for MessageInterface imp…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17891]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49327
| PR author(s) | @fabpot
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by alexandre-daubois** [comment]
Ping @javiereguiluz, these are not mentioned anywhere in the doc, and the goal of this PR is to improve discoverability. I guess this can be closed :slightly_smiling_face:
