### ISSUE TITLE
[HtmlSanitizer] Remove experimental status

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17899]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49343
| PR author(s) | @tgalopin
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by zairigimad** [comment]
Hello @fabpot I would like to help on this, but i think the component is not marked as experimental in the doc, i couldn't find where to remove it

**Comment by OskarStark** [comment]
I double checked, there is nothing to document
