### ISSUE TITLE
Incorrect hyperlinks on the web documention for the Form Types Reference

### ISSUE THREAD

**Issue by Theo-Dancoisne** [symfony/symfony-docs#17904]
https://symfony.com/doc/current/reference/forms/types/#supported-field-types
All hyperlinks in this category target non-existent html files.

So for example this location is correct : https://symfony.com/doc/current/reference/forms/types/email.html
And this one from the hyperlinks is false : https://symfony.com/doc/current/reference/reference/forms/types/email.html
There is one "reference" folder too many.

**Comment by javiereguiluz** [comment]
I guess this is an issue in https://github.com/symfony-tools/docs-builder. That page is not generated by symfony.com. We just output the HTML contents generated by `docs-builder` when building the docs 🤔

**Comment by Theo-Dancoisne** [comment]
@javiereguiluz should I close the issue here and open it in https://github.com/symfony-tools/docs-builder ?

**Comment by wouterj** [comment]
@javiereguiluz this is a known issue of symfony.com when you visit a page without `.html` and with a trailing `/`.

IIRC, you had implemented a fix to redirect the routes with trailing `/` to the route without trailing `/`. But since a year or so, it seems like this redirect is broken. Is there a way you could see if this redirect could be implemented? (happy to help, if there is anything I can do)

**Comment by Theo-Dancoisne** [comment]
I see the issue is solved.

Thank you all.

**Comment by Theo-Dancoisne** [comment]
I see the issue is solved.

Thank you all.

**Comment by Theo-Dancoisne** [comment]
Uh sorry, actually this is not resolved I think, I confused these 2 pages:
https://symfony.com/doc/current/reference/forms/types.html          (links are correct)
https://symfony.com/doc/current/reference/forms/types/#supported-field-types      (links are incorrect)

I'm so confused because both page looks the same.

**Comment by javiereguiluz** [comment]
We've fixed the underlying issue (multiple URLs serving the same resource) by redirecting all URLs to the same single URL. Indirectly, that fix has solved the problem mentioned in this issue. So, let's close as finally solved. Thanks!
