### ISSUE TITLE
Version selector disappears on half-screen view in FHD

### ISSUE THREAD

**Issue by givihuda** [symfony/symfony-docs#17914]
Example: https://symfony.com/doc/5.4/components/console/single_command_tool.html

In full-screen, on FHD or QHD, the selector is there.

In half-screen, on FHD, the selector disappears, and is not anywhere on the page when scrolling down. It's not even in the collapsed menu at the top right.

![image](https://user-images.githubusercontent.com/74785256/219705285-0fa0fb3b-7321-4c62-87ef-07b2caadd3da.png)

There seems to be room to shrink the Search bar and place the Version selector to the right. I'm perfectly OK with the Search bar not even crossing the halfway point in the viewport.

On QHD half-screen, the selector is there.

![image](https://user-images.githubusercontent.com/74785256/219705453-a51baaad-fffb-4277-a1a4-94378ca91129.png)

In most desktop work environments I've seen, people are using FHD screens, or at least far more than anything higher.

I see no reason to hide the Version selector on half-screen of FHD. I often use half-screen for windows, and I don't often see vital elements like this hidden.

**Comment by javiereguiluz** [comment]
@givihuda thanks for reporting this error. I'm going to fix it.

However, if I understood you correctly, you are saying that most people use a desktop with a resolution similar to your first screenshot instead of the second one. My experience is the opposite: I've never seen a developer working on a Desktop with such a small resolution. That's more common in smartphones and tablets.

**Comment by givihuda** [comment]
> I've never seen a developer working on a Desktop with such a small resolution. 

Don't get caught up on "FHD", I'm talking about desktop monitors at 22-24" at FHD as a common example, which is common in office environments I've seen for developers in my region (western USA for over a decade). 

Note that a similar _display block element and text size_ can be shown even at higher resolutions even on smaller screens... I hope that makes sense!

At a smaller screen size at a similar-looking resolution (same real estate area for div blocks and font size), text gets smaller and harder to read. I have a laptop with a 15.4", and FHD text is often right on the line of being hard to read. Note that a screen of similar size can have a higher resolution but same-sized text and display block elements. The point is that I'm just using FHD desktop monitor at about 22-24" as a way of saying "typical display area" when it comes to elements being shifted or hidden at half-screen windows.

> That's more common in smartphones and tablets.

Who codes on a smartphone and tablet? I consider those people insane. They're definitely not common.

I consider a developer insane even that codes on an 11-13" laptop. I don't know how they get anything done. I don't see that often, but it seems to be more in the front-end / JavaScript / admin / marketing / advertising / blogging world where they may touch code, but that's not much in the Symfony world anyway.

A lot of developers use laptops in their non-office work, like at cafes etc, typically MacBooks. Some use the large-ish 15-16" ones, which I think is OK for a "mobile" device (not needing to be attached to a wall and external monitor), and get similar display / text size real estate, and would probably see the same disappearing things that probably shouldn't disappear. It's all about what should reasonably show for docs here, and I think a half-window is not unreasonable for a similar-sized display in my example anyway.

**Comment by javiereguiluz** [comment]
Closing as fixed because in small screens _(not only smartphones)_ we now display a bottom bar with shortcuts. See https://twitter.com/symfonydocs/status/1635273673388195843
