### ISSUE TITLE
[DependencyInjection] Allow trimming service parameters value in XML co…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17938]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49412
| PR author(s) | @alexandre-daubois
| Merged in    | 6.3

**Comment by alexandre-daubois** [comment]
I'm on it 👍

**Comment by alamirault** [comment]
Documentation is merged, we can close this issue :smile:
