### ISSUE TITLE
Kernel parameters list not documented?

### ISSUE THREAD

**Issue by Arkemlar** [symfony/symfony-docs#17935]
Today I searched for a place where I can find the list of exact names for Kernel parameters and failed. It seems a sensitive miss for the documentation. The first place I looked for was https://symfony.com/doc/current/reference/configuration/kernel.html so it would be nice to see Kernel parameters list there.

**Comment by javiereguiluz** [comment]
In the page that you referenced, you can see the names of the kernel parameters: `kernel.project_dir`, `kernel.charset`, etc.

What are you missing in that page? Thanks.

**Comment by Arkemlar** [comment]
I mean all the list of parameters that IDE autocompletion lists here:
![изображение](https://user-images.githubusercontent.com/19671202/220343739-1f87175c-7e2b-475b-bfa8-78846826dd99.png)
In the page I mentioned above - there are much less parameters described.

About `kernel.runtime_environment` discussion found in other [issue](https://github.com/symfony/symfony-docs/issues/14455)

**Comment by alexandre-daubois** [comment]
Oh that's actually parameters defined by the framework config. Maybe we should add a mention in the kernel page about this?

**Comment by javiereguiluz** [comment]
@Arkemlar thanks for the additional details.

Let's think about this a bit more before making any change. Thanks.

**Comment by javiereguiluz** [comment]
Closing as fixed in #18525.
