### ISSUE TITLE
[FrameworkBundle][HttpKernel] Configure `ErrorHandler` on boot

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17949]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49275
| PR author(s) | @HypeMC
| Merged in    | 6.3

**Comment by alexandre-daubois** [comment]
Friendly ping @javiereguiluz, I don't think this one should be documented as it is some kind of "super internal" feature :slightly_smiling_face:

**Comment by javiereguiluz** [comment]
Yes, I've read the PR description and it looks an internal thing not relevant for the docs. Let's close it. In the future we can reconsider this if we receive feedback from people. Thanks!
