### ISSUE TITLE
[FrameworkBundle] Allow disabling dumping of container to XML to improv…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#17952]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49487
| PR author(s) | @ruudk
| Merged in    | 6.3

**Comment by ruudk** [comment]
See https://github.com/symfony/symfony-docs/pull/17954

**Comment by alamirault** [comment]
Documentation is merged, we can close this issue :smile:
