### ISSUE TITLE
Rate limiter config missing in simple login limiting documentation

### ISSUE THREAD

**Issue by uncaught** [symfony/symfony-docs#17966]
The 5.4 documentation for [limiting login attempts](https://symfony.com/doc/5.4/security.html#limiting-login-attempts) doesn't work as specified right out of the box.

It says you only need to define `login_throttling` on your firewall, but by only doing that, you get an error `Service "limiter._login_local_main": Parent definition "limiter" does not exist.`.

You also need to define the config `framework.rate_limiter: ~` for this error to go away.

The documentation mentions the `rate_limiter` config further down the document, but it is missing for the simple setup and apparently required.

So please add this:

```yml
framework:
  rate_limiter: ~
```

Here: 
![image](https://user-images.githubusercontent.com/10322643/221157611-55411537-0a84-47e5-af40-ddbcfd58ae71.png)

**Comment by javiereguiluz** [comment]
Closing as fixed in #18857.
