### ISSUE TITLE
Switching receiver and sender in messenger concept image

### ISSUE THREAD

**Issue by danrot** [symfony/symfony-docs#17973]
I have seen this image in the documentation, and I am wondering if it is just me, or is it wrong?

<img width="600" alt="grafik" src="https://user-images.githubusercontent.com/405874/221430943-ebd2449f-cc48-4240-bf3d-fa3b1ade27be.png">

Here it looks to me as if the receiver is sending and the sender is receiving 🤔

**Comment by xabbuh** [comment]
I agree with you

**Comment by danrot** [comment]
@xabbuh Is there an easy way to change this? AFAICT there is only this image in the docs, and no source file that would allow to edit it easily.

**Comment by xabbuh** [comment]
Maybe @javiereguiluz knows more as he changed the images in #10860.

**Comment by xabbuh** [comment]
I just looked at the image again and maybe it is indeed correct. My reasoning now is this: The message with envelope 1 is received by the receiver which then forwards it to the message bus so that it can be processed by our Symfony application. From there the message can be forwarded to a sender which can send it to external system.

**Comment by danrot** [comment]
@xabbuh I see, but it still seems to be confusing. I think there are a few problems:

1. The blue dots do not convey any meaning, so some context is missing.
2. I thought that this image showed a single process, but it seems like two envelopes are not even the same message.
3. I would consider the `Handler` to be a part of the `Application`, since this is probably implemented by the same developer.

I think especially the second point is problematic. I think it would be easier to understand if this would be split into two images, one for receiving messages and one for sending messages.

**Comment by xabbuh** [comment]
splitting the image might indeed be a good idea

**Comment by javiereguiluz** [comment]
For the images, we have these docs explaining how to create or edit them: https://github.com/symfony/symfony-docs/tree/6.2/_images/sources

The process is sadly pretty cumbersome ... I'd recommend you to only change the Sender/Receiver order. If you need help to do this, we can do this change for you. Thanks.
