### ISSUE TITLE
[RFC] Document Rector on Symfony upgrades major/minor pages

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-docs#17983]
Hi,

I would like to know if such documentation as link/info could be valuable in those pages:

- https://symfony.com/doc/current/setup/upgrade_major.html
- https://symfony.com/doc/current/setup/upgrade_minor.html

There are lot of PHP libraries already documented somewhere in the documentation codebase
and to me, rector tool can benefit such visibility and Symfony community as well

In my mind I have such "rules":

- `UP_TO_SYMFONY_60`
    - https://github.com/rectorphp/rector-symfony/blob/3cebcd90e9b356a860801742616f64d5858a4496/src/Set/SymfonyLevelSetList.php#L112

**Comment by javiereguiluz** [comment]
See #18452.

I think it's a good idea to mention Rector ... but I wouldn't show a real example of using it to upgrade Symfony projects because it will be hard for us to maintain those docs in the future. So, for now, maybe it's enough to just mention it. Thanks.

**Comment by 94noni** [comment]
Indeed i agree, just mentioning is enough and give hint to devs they can go read more on the other doc 👍🏻
