### ISSUE TITLE
Add Reference section for Attributes

### ISSUE THREAD

**Issue by ker0x** [symfony/symfony-docs#17981]
While browsing the documentation, I realized that it was difficult to find correct information about the attributes available in Symfony with explanations about their options.

Therefore, I would like to propose to add a new reference section dedicated to Symfony Attributes similar to what is done for Constraints.

WDYT ?

**Comment by MrYamous** [comment]
Love the idea. A lot of attributes are available in Symfony, some for replace yaml/other format config, some for new features.

About format, maybe each component docs could contains an Attribute reference ?

**Comment by OskarStark** [comment]
@symfony/team-symfony-docs WDYT?

**Comment by fabpot** [comment]
As we have more and more of those, I think it makes sense.

**Comment by wouterj** [comment]
I'm often unsure for references like this. Is it elevant to answer the question "Which attributes does Symfony support?" or is it more relevant to document the attributes when talking about the feature they implement? I think it's mostly the latter.

We can do a better job in documenting the attributes of the DI component in https://symfony.com/doc/current/service_container.html and maybe the same applies to other guides as well. But e.g. the Route attribute is thorougly documented already in the Routing guide.

Imho, making these changes in the main guides would add more value than creating a reference article.

**Comment by fabpot** [comment]
Totally agree. I was more thinking about having a list of supported attributes in the reference section that would point to where they are documented.

**Comment by OskarStark** [comment]
> Totally agree. I was more thinking about having a list of supported attributes in the reference section that would point to where they are documented.

Yes, only as an overview with deep links 👍
