### ISSUE TITLE
[DoctrineBridge] deprecate doctrine schema subscribers in favor of list…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18006]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49610
| PR author(s) | @alli83
| Merged in    | 6.3

**Comment by alamirault** [comment]
I found no reference for the 3 deprecated subscribers in docs

**Comment by alli83** [comment]
@alamirault I'm sorry for the delay,  I'm working on it.

**Comment by alamirault** [comment]
Great ! It was just an observation of the existing :smile:

**Comment by alli83** [comment]
I'am actually a little bit confused where it should be updated in Symfony-docs not seeing them already mentioned. Maybe more focused on why this change ?

**Comment by chalasr** [comment]
Changing a subscriber into a listener does not change the final behavior, so if there is no direct reference to the deprecated classes then therés nothing to do and this can be closed.

**Comment by javiereguiluz** [comment]
OK. Let's close this then. Thanks a lot @alli83 for checking this and thanks to the other reviewers too.
