### ISSUE TITLE
[Routing] Broken link for "Doctrine param conversion documentation"

### ISSUE THREAD

**Issue by artyuum** [symfony/symfony-docs#18021]
On [this page](https://symfony.com/doc/current/routing.html#parameter-conversion) there is the following text:
> Check out the Doctrine param conversion documentation to learn about the #[MapEntity] attribute that can be used to customize the database queries used to fetch the object from the route parameter.

Unfortunately, [the link to the Doctrine param conversion documentation](https://symfony.com/doc/current/doctrine-entity-value-resolver) does not work (404).

**Comment by mdoutreluingne** [comment]
Fix in #18022
