### ISSUE TITLE
[Security] Change the title "Checking to see if a User is Logged In (IS_AUTHENTICATED_FULLY)"

### ISSUE THREAD

**Issue by artyuum** [symfony/symfony-docs#18023]
The title is not consistent with what's explained. [In this section](https://symfony.com/doc/current/security.html#checking-to-see-if-a-user-is-logged-in-is-authenticated-fully), we are suggesting the users to use the `IS_AUTHENTICATED` attribute, and later we are explaining the other attributes. The title should be:
> Checking to see if a User is Logged In (IS_AUTHENTICATED)

**Comment by alamirault** [comment]
Maybe `Checking to see if a User is Logged In` is enough ? With on adjustment in "Secondly, you can use a special "attribute" `IS_AUTHENTICATED` in place of a role:"

**Comment by artyuum** [comment]
I agree. That's better.
