### ISSUE TITLE
[DependencyInjection] deprecate the `@required` annotation

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18044]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48990
| PR author(s) | @alexislefebvre
| Merged in    | 6.3

**Comment by alexislefebvre** [comment]
Actually `@required` had already been removed:

- #17654

So it looks like there's nothing to do here?

**Comment by javiereguiluz** [comment]
Let's close as fixed then. Thanks Alexis!
