### ISSUE TITLE
[Messenger] make StopWorkerOnSignalsListener listen by default on SIGTE…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18040]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49539
| PR author(s) | @lyrixx
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by lyrixx** [comment]
I think there is nothing to document here. Everything is already setup With the framework bundle
