### ISSUE TITLE
[Serializer] Add methods `getSupportedTypes` to allow better performance

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18042]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49291
| PR author(s) | @tucksaun, @nicolas-grekas
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by tucksaun** [comment]
@javiereguiluz should this one be added to the list in #17912 ?

**Comment by nicolas-grekas** [comment]
When documenting, this should also consider symfony/symfony#49735

**Comment by tacman** [comment]
An example?  Usually Symfony deprecations make it pretty easy to fix, but there's not even a return type (which needs to be an array).

```php
    public function getSupportedTypes(?string $format)
    {
        return [];
        // TODO: Implement getSupportedTypes() method.
    }

    // delete this removing the 'implements CacheableSupportsMethodInterface'
    public function hasCacheableSupportsMethod(): bool
    {
        return true;
    }
```

**Comment by nicolas-grekas** [comment]
For inspiration:

```rst
.. versionadded:: 6.3

    The `getSupportedTypes()` method was introduced in Symfony 6.3.

Both :class:`Symfony\\Component\\Serializer\\Normalizer\\NormalizerInterface` and
:class:`Symfony\\Component\\Serializer\\Normalizer\\DenormalizerInterface` contain a new method `getSupportedTypes()`.
This method allows normalizers or denormalizers to expose their supported types and the associated cacheability to the
Serializer. With this info, even if the `supports*()` call is not cacheable, the Serializer can skip a ton of method calls
to `supports*()` improving performance substantially in some cases.

The `getSupportedTypes()` method should return an array where the keys represent the supported types, and the values
indicate whether the result of the `supports*()` method call can be cached or not. The format of the returned array is as
follows:

- The special key `object` can be used to indicate that the normalizer or denormalizer supports any classes or
  interfaces.
- The special key `*` can be used to indicate that the normalizer or denormalizer might support any types.
- The other keys in the array should correspond to specific types that the normalizer or denormalizer supports.
- The values associated with each type should be a boolean indicating if the result of the `supports*()` method call for
  that type can be cached or not. A value of `true` means that the result is cacheable, while `false` means that the
  result is not cacheable.
- A `null` value for a type means that the normalizer or denormalizer does not support that type.

Here is an example of how to use the `getSupportedTypes()` method:

.. code-block:: php

    use Symfony\\Component\\Serializer\\Normalizer\\NormalizerInterface;

    class MyNormalizer implements NormalizerInterface
    {
        // ...

        public function getSupportedTypes(?string $format): array
        {
            return [
                'object' => null, // Doesn't supports any classes or interfaces
                '*' => false, // Supports any other types, but the result is not cacheable
                MyCustomClass::class => true, // Supports MyCustomClass and result is cacheable
            ];
        }
    }

Note that `supports*()` method implementations should not assume that `getSupportedTypes()` has been called before.
```

**Comment by dozer111** [comment]
does it enough to just duplicate the class code like this

```php
public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
    {
        return SomeMyClass::class === $type;
    }

    public function getSupportedTypes(?string $format): array
    {
        return [
            SomeMyClass::class => true
        ];
    }
```

?

**Comment by andrew-demb** [comment]
> does it enough to just duplicate the class code like this
> 
> ```php
> public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
>     {
>         return SomeMyClass::class === $type;
>     }
> 
>     public function getSupportedTypes(?string $format): array
>     {
>         return [
>             SomeMyClass::class => true
>         ];
>     }
> ```
> 
> ?

Yes

**Comment by ro0NL** [comment]
IIUC a one size fits all implemenation is

```
    public function getSupportedTypes(?string $format): array
    {
        return ['*' => false];
    }
```

in case of many complex `supports*` methods

**Comment by FranzBruckner** [comment]
By just reading the [new documentation](https://symfony.com/doc/current/serializer/custom_normalizer.html#performance-of-normalizers-denormalizers)  it's very unclear what cacheable means. I tried to find it out by interpreting the code.

The [old documentation](https://symfony.com/doc/5.x/serializer/custom_normalizer.html#performance) on the other hand describes that pretty well, so maybe it would be a good idea to add this part to the new one.

**Comment by kkevindev** [comment]
> By just reading the [new documentation](https://symfony.com/doc/current/serializer/custom_normalizer.html#performance-of-normalizers-denormalizers) it's very unclear what cacheable means. I tried to find it out by interpreting the code.
> 
> The [old documentation](https://symfony.com/doc/5.x/serializer/custom_normalizer.html#performance) on the other hand describes that pretty well, so maybe it would be a good idea to add this part to the new one.

I think that the current docs (from 6.4 and up) (see https://symfony.com/doc/6.4/serializer/custom_normalizer.html#improving-performance-of-normalizers-denormalizers) is better than the [old documentation (5.x)](https://symfony.com/doc/5.x/serializer/custom_normalizer.html#performance).

The following part is exactly what you are looking for, is it not?
> This does not cache the actual normalization or denormalization result. It only caches the decision of whether a normalizer supports a given type, allowing the Serializer to skip unnecessary supports*() calls and improve performance.
