### ISSUE TITLE
[Uid] Configuration example is invalid

### ISSUE THREAD

**Issue by MrYamous** [symfony/symfony-docs#18054]
Configuration example provided for Uid component in https://symfony.com/doc/current/components/uid.html#generating-uuids seems to be invalid

https://github.com/symfony/symfony/blob/dfea1db1daa773617d37064fc44e9fadb075d402/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L2043

**Comment by OskarStark** [comment]
Friendly ping @fancyweb
