### ISSUE TITLE
[Webhook][RemoteEvent] Add the components

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18061]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48542
| PR author(s) | @fabpot
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by alexandre-daubois** [comment]
The Webhook documentation is in progress: https://github.com/symfony/symfony-docs/pull/17964

**Comment by alexandre-daubois** [comment]
Let's close this one @OskarStark @xabbuh? :slightly_smiling_face:
