### ISSUE TITLE
PSR-7 Bridge documentation links to classes that are not in the main Symfony repository

### ISSUE THREAD

**Issue by radar3301** [symfony/symfony-docs#18062]
The [PSR-7 Bridge documentation](https://symfony.com/doc/current/components/psr7.html) links to interfaces that have been removed from (or never were in?) the main Symfony repository:

> The bridge provides an interface of a factory called `[HttpMessageFactoryInterface](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bridge/PsrHttpMessage/HttpMessageFactoryInterface.php)` that builds objects implementing PSR-7 interfaces from HttpFoundation objects.

This is located at `https://github.com/symfony/psr-http-message-bridge/blob/main/HttpMessageFactoryInterface.php`

> On the other hand, the bridge provide a factory interface called `[HttpFoundationFactoryInterface](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bridge/PsrHttpMessage/HttpFoundationFactoryInterface.php)` that builds HttpFoundation objects from objects implementing PSR-7 interfaces.

This is located at `https://github.com/symfony/psr-http-message-bridge/blob/main/HttpFoundationFactoryInterface.php`

---

This affects all versions of `/components/psr7.rst`, all the way back since it was introduced in 2.7.

Should be a simple fix, replacing:
``` :class:`Symfony\\Bridge\\PsrHttpMessage\\HttpMessageFactoryInterface` ```
with
`[HttpMessageFactoryInterface](https://github.com/symfony/psr-http-message-bridge/blob/main/HttpMessageFactoryInterface.php)`

and

``` :class:`Symfony\\Bridge\\PsrHttpMessage\\HttpFoundationFactoryInterface` ```
with
`[HttpFoundationFactoryInterface](https://github.com/symfony/psr-http-message-bridge/blob/main/HttpFoundationFactoryInterface.php)`

I'd open a pull request myself to fix, but the last time I did, I "didn't do the pull request process right."

**Comment by mdoutreluingne** [comment]
Indeed the links are broken. Thanks for reporting this issue, can you open a PR? The community will help you with your PR :)
we can help with that after you've opened a pull request!
