### ISSUE TITLE
[Messenger] Add a scheduler component

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18067]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47112
| PR author(s) | @upyx, @fabpot
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by alexandre-daubois** [comment]
Let's close this one also?

**Comment by javiereguiluz** [comment]
There's still many work to do to fully document this component, but the initial docs are now read. Let's close it as fixed. Thanks for checking this Alex.
