### ISSUE TITLE
Add extended Symfony YAML features to the YAML Format page?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#18073]
After merging #18058 I realized that in https://symfony.com/doc/current/reference/formats/yaml.html we only show the YAML spec things that we support and mention the things we don't.

Should we also mention the Symfony-specific YAML features such as using PHP constants in YAML config files via the `!php/const ...` notation?

**Comment by MrYamous** [comment]
IMO this kind of feature needs to be more exposed as it can be very useful for a lot a developers in SF community and I think reference page for YAML is a good place to add this and others symfony-specific YAML features.

After more search, it's also mentioned in [Yaml Component documentation](https://symfony.com/doc/current/components/yaml.html#parsing-php-constants) but components documentation can be difficult to reach and this may not be the first place you think to look when you want to define your configuration and as [Configuration parameters example](https://symfony.com/doc/current/configuration.html#configuration-parameters) but without more details about how it works.

**Comment by alexandre-daubois** [comment]
I gave it a try!
