### ISSUE TITLE
[HttpFoundation] Add `ParameterBag::getString()` and deprecate acceptin…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18089]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48525
| PR author(s) | @GromNaN
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by GromNaN** [comment]
https://github.com/symfony/symfony/pull/48525#issuecomment-1472373776 adds an other feature: `FILTER_NULL_ON_FAILURE` should be used otherwise an exception will be thrown on invalid values in 7.0. I don't know how to document it, but it should be.
