### ISSUE TITLE
[DependencyInjection] Add support for generating lazy closures

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18090]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49639
| PR author(s) | @nicolas-grekas
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by javiereguiluz** [comment]
If contributors need inspiration to document this, @nicolas-grekas himself prepared a description of this feature for the "New in Symfony" blog post. See https://symfony.com/blog/new-in-symfony-6-3-dependency-injection-improvements#using-autowiring-to-generate-closures

**Comment by alexandre-daubois** [comment]
Gave a try, I did a few edits on what was previously existing about those attributes :+1:

**Comment by javiereguiluz** [comment]
Fixed in #18347.
