### ISSUE TITLE
Version changer doesn't remember section link

### ISSUE THREAD

**Issue by givihuda** [symfony/symfony-docs#18115]
If I go into a doc page like this: 

https://symfony.com/doc/current/components/http_foundation.html#serving-files

then change the version, the page load loses my place, like this:

https://symfony.com/doc/5.4/components/http_foundation.html

It needs to be aware of the hash part of the path as well.

**Comment by javiereguiluz** [comment]
@givihuda thanks for reporting this issue. We've just deployed a fix for it, so the scroll position is now kept when switching the doc version.

**Comment by givihuda** [comment]
Thank you! That works well.

I haven't tried switching to a version where the sub-link in the URL isn't available, but of course, if it isn't, it would make sense to stay at the top of that newly-selected version's page (which I think it will do anyway). I don't know if that means removing the sub-link from the URL, or redirecting with JavaScript or something like that, but it would make more sense visually of course.
