### ISSUE TITLE
Algolia Search seems to be broken

### ISSUE THREAD

**Issue by atierant** [symfony/symfony-docs#18117]
Hi,

Since yesterday, when I search for something on main website, I have no results. It seems that the Algolia API forbid me to get results.

![image](https://user-images.githubusercontent.com/1587260/227518165-011fe4c3-16d2-45e7-96f9-e50ade4afd75.png)

Can you investigate ? Thanks.

**Comment by javiereguiluz** [comment]
Arnaud, thanks for reporting this.

We are aware of this error but sadly we can't fix it easily. We're moving to a new search experience based on Meilisearch. We're almost ready but we need a bit more of time. We're sorry!

**Comment by atierant** [comment]
> Arnaud, thanks for reporting this.
> 
> We are aware of this error but sadly we can't fix it easily. We're moving to a new search experience based on Meilisearch. We're almost ready but we need a bit more of time. We're sorry!

Thanks a lot Javier !

**Comment by javiereguiluz** [comment]
Closing as fixed. See https://symfony.com/blog/migrating-symfony-com-search-engine-to-meilisearch
