### ISSUE TITLE
`.. index::` is not intepreted on validation page

### ISSUE THREAD

**Issue by alamirault** [symfony/symfony-docs#18122]
https://symfony.com/doc/current/validation.html#validation-callables

![image](https://user-images.githubusercontent.com/9253091/227733746-a32ae5e1-09e7-4060-8934-aeb0fe167bd0.png)

https://github.com/symfony/symfony-docs/blob/5292d7b08dd0a9d4f51c7c43814b21e2f371c0bc/validation.rst?plain=1#L237-L242

Directive seems OK, but is not rendered (adding space do nothing but with versionnadded or note it's ok)

Someone has an idea ?

(Initially reported by @BafS on slack)

**Comment by javiereguiluz** [comment]
In the past we used this a lot, because we published the docs as PDF and this directive allows to build the index to find things quickly by page number.

We no longer use this, so maybe we can remove it? Let's ask the Symfony Docs Team first --> @symfony/team-symfony-docs

**Comment by OskarStark** [comment]
TBH I am not really aware of the `..index::` directive 🤷‍♂️

**Comment by fabpot** [comment]
I think it's safe to remove all these directives. The search engine is the way to go.

**Comment by alamirault** [comment]
Well, I will provide a PR to drop them
