### ISSUE TITLE
[SensioFrameworkExtraBundle] Add message in the bundle documentation page 

### ISSUE THREAD

**Issue by Mick3DIY** [symfony/symfony-docs#18129]
Hello all,

as you know this bundle is not maintained any more, the Github repository "has been archived by the owner on Feb 24, 2023. It is now read-only".

But in the main documentation page [SensioFrameworkExtraBundle](https://symfony.com/bundles/SensioFrameworkExtraBundle/current/index.html), there is no mention to that and the repository is read only... (infinite loop)

How to add a "Caution" message and how to migrate source code to Symfony 6.2+ ?

Sorry for duplicate message or wrong channel/issue.

**Comment by WebMamba** [comment]
The SensioFrameworkExtraBundle is not maintained anymore but all the annotations introduced into this bundle as been moved as Attribute into Symfony. For example, the Security annotation became isGranted. Here is a discussion about this topic: https://github.com/symfony/symfony/discussions/48878
Cheers

**Comment by alamirault** [comment]
I agree we should add a warning and probably add link to symfony docs for theses anootations

```
@Route and @Method
@ParamConverter
@Template
@Cache
@Security & @IsGranted
```

**Comment by alexandre-daubois** [comment]
Do we really need to? I mean, the whole documentation of the latest versions of Symfony stopped mention Sensio's bundle. If one follows the documentation, all attributes used are core ones 😄 But I may be missing the point and maybe the doc could be improved somewhere?

**Comment by alamirault** [comment]
When searching on "route annotation symfony" ~a search engine~ Google, https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/routing.html is the second link.

So I think in some cases "historical" docs pags are better referenced than new Symfony attributes

**Comment by Mick3DIY** [comment]
@alamirault : personally when I search (from Brave search) for "Symfony IsGranted", the first link I have is [https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/security.html](https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/security.html)

(Home -> Documentation -> Bundles -> SensioFrameworkExtraBundle -> @Security & @IsGranted)

It depends if you know well Symfony and its documentation structure or if you search with good search engine & key words :)

> When searching on "route annotation symfony" ~a search engine~ Google, https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/routing.html is the second link.
> 
> So I think in some cases "historical" docs pags are better referenced than new Symfony attributes

**Comment by javiereguiluz** [comment]
Don't know what to do here:

* We can't add a comment from symfony.com or Symfony Docs
* We can only add that via the bundle repository ... which we can't because it's marked as "archived" by GitHub
* ... and, those pages already display a message mentioning that it's deprecated: https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/routing.html It's true that the message could be better (and link to the current alternatives).

**Comment by javiereguiluz** [comment]
We've just deployed some changes and the following page now displays a prominent deprecated warning message:

https://symfony.com/bundles/SensioFrameworkExtraBundle/current/index.html

Closing this as fixed then.
