### ISSUE TITLE
[DependencyInjection] Add support for casting callables into single-met…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18132]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49632
| PR author(s) | @nicolas-grekas
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
If contributors need inspiration to document this, @nicolas-grekas himself prepared a description of this feature for the "New in Symfony" blog post. See https://symfony.com/blog/new-in-symfony-6-3-dependency-injection-improvements#generating-adapters-for-functional-interfaces

**Comment by alexandre-daubois** [comment]
I'm having a look :+1:

**Comment by javiereguiluz** [comment]
Closing as fixed in #18348.
