### ISSUE TITLE
Broken links to docs for 4.2, 4.3 and 4.4

### ISSUE THREAD

**Issue by ryanhughes** [symfony/symfony-docs#18141]
Hi,

The docs for Symfony [4.2](https://symfony.com/doc/4.2/index.html), [4.3](https://symfony.com/doc/4.3/index.html) and [4.4](https://symfony.com/doc/4.4/index.html) have gone missing from the website. These are all linked from https://symfony.com/releases

The same versions are also missing from the list of unmaintained docs on the 404 pages https://symfony.com/doc/4.4/security.html

**Comment by wouterj** [comment]
This was a temporary issue. Documentation for all unmaintained versions are online.

Thanks for reporting!
