### ISSUE TITLE
Update the example provided in the documentation for `Development Versus Production: Environments`

### ISSUE THREAD

**Issue by ovidiuenache** [symfony/symfony-docs#18165]
The example provided in the [Development Versus Production: Environments](https://symfony.com/doc/current/quick_tour/the_architecture.html#development-versus-production-environments) section of the [The Architecture](https://symfony.com/doc/current/quick_tour/the_architecture.html) documentation page is outdated since it is using the old way of splitting the configuration per environment:

![image](https://user-images.githubusercontent.com/20539991/230050078-6f1316d4-620c-4b6a-83df-64505b627821.png)

The default Symfony project created via the binary (or alternatives) is using the new single-file approach with `when@<environment>`.

Can I proceed and create a PR that changes the example?

**Comment by OskarStark** [comment]
Yes please

**Comment by javiereguiluz** [comment]
Fixed in #18167.
