### ISSUE TITLE
[Notifier] Versioned links are not working

### ISSUE THREAD

**Issue by MrYamous** [symfony/symfony-docs#18160]
#17902 introduces versioned links to code repo for Notifier Bridge but generated links seems to be broken 

For example, click on FakeSms on 6.2 doc refers to https://github.com/symfony/symfony/blob/%7Bversion%7D/src/Symfony/Component/Notifier/Bridge/FakeSms/README.md 
instead of
https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Notifier/Bridge/FakeSms/README.md 

Friendly ping @alamirault

**Comment by alamirault** [comment]
All branches are KO on website.
I checked locally builds and links are ok.

I suppose website builds do not use `symfony-tools/docs-builder:^0.20`, but I don't know how it's configured/works

**Comment by javiereguiluz** [comment]
I'm sorry about this. I forgot to update the dependency used by symfony.com. We've just deployed the changes, so the next doc build in a few hours should work as expected. Thanks.
