### ISSUE TITLE
Document How the ProgressBar on Console Uses stderr

### ISSUE THREAD

**Issue by d42ohpaz** [symfony/symfony-docs#18177]
I feel that a note should be added to the [ProgressBar](https://symfony.com/doc/current/components/console/helpers/progressbar.html) documentation stating the console output will always be sent through `stderr`. This is a subtle nuance for anybody who treat `stderr` as an error, similar to how a return code > 0 would indicate a failure of a command. 

Use case: I use [cronic](https://habilis.net/cronic/) to wrap command execution for cron jobs so that any error output, or result code > 0, is treated as a failure and an email be sent notifying developers of a problem. `cronic` relies on the existence of either output in `stderr` or a non-zero result code to make this determination. Suffice it to say, I've been spinning my wheels trying to figure out why my commands are failing successfully.

**Comment by chuckhoupt** [comment]
Many console programs suppress progress bars when running non-interactively. Possibly ProgressBar could be modified to be quiet when non-interactive? I believe this could be done with [`posix_isatty`](https://www.php.net/manual/en/function.posix-isatty.php), at least on Unix-y systems.
