### ISSUE TITLE
[Serializer] Make `ProblemNormalizer` give details about `ValidationFai…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18170]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49944
| PR author(s) | @nicolas-grekas
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Friendly ping @javiereguiluz, this seems really internal, not sure it has its place in the doc :slightly_smiling_face:

**Comment by javiereguiluz** [comment]
I agree. This is a nice feature that provides better error messages ... but nothing to document explicitly. Let's close it. Thanks!
