### ISSUE TITLE
[Serializer] Mark `ObjectNormalizer` as final for 7.0

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18182]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49953
| PR author(s) | @tucksaun
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alamirault** [comment]
I found no place where we extends `ObjectNormalizer`. So I think there is no action to do

**Comment by javiereguiluz** [comment]
Let's close it. Thanks Antoine.
