### ISSUE TITLE
[DoctrineBridge] Deprecate passing doctrine subscribers to ContainerAwa…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18181]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49918
| PR author(s) | @alli83
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by mdoutreluingne** [comment]
I found no reference for `ContainerAwareEventManager` class in docs

**Comment by fabpot** [comment]
Closing then.

**Comment by stof** [comment]
this is not passed explicitly in the doc, because the wiring is done by DoctrineBundle. But https://symfony.com/doc/current/doctrine/events.html#doctrine-lifecycle-subscribers still documents subscribers. So this should be reopened.

**Comment by javiereguiluz** [comment]
Closing as fixed in #18878.
