### ISSUE TITLE
Cache id for anchor tag is not unique

### ISSUE THREAD

**Issue by kriskoch** [symfony/symfony-docs#18194]
Sorry if this isn't the correct place to post this as I think it is a symfony.com website bug vs doc bug, but not sure where I would place it.

https://symfony.com/doc/current/reference/configuration/framework.html#cache

There are two anchor tags that have id="cache" one for validation configuration and one for the cache configuratoin.
This means clicking on  cache in the TOC doesn't take you to where you want to go.

**Comment by alamirault** [comment]
Thanks for your report @kriskoch.

It's a "bug" in our doc generation process.

A pull request in ongoing which fix this case https://github.com/symfony-tools/docs-builder/pull/152, and will be merge and deploy soon I hope

**Comment by javiereguiluz** [comment]
We've just merged and deployed the bug fix in the docs builder tool. In a few hours, the docs will be rebuilt and we should see this and other related issues as fixed. Thanks!
