### ISSUE TITLE
[Mailer] Allow overriding default eSMTP authenticators

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18209]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49900
| PR author(s) | @cedric-anne
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by cedric-anne** [comment]
Documentation update proposed in #18212. Not sure if it is required to document both constructor param update and `setAuthenticators()` method. Indeed, code snippet seems a bit weird with both.

**Comment by javiereguiluz** [comment]
Closing as fixed in #18212.
