### ISSUE TITLE
[Doctrine extensions] Link to Gedmo extensions broken

### ISSUE THREAD

**Issue by RyanFarrah67** [symfony/symfony-docs#18203]
### Affected versions of the doc

 From the 5.4 to the 2.7. Newer versions are completely different docs.

### Problem

The link in the bottom of the documentation (not the page itself) : 

> Implement this services directly by following the documentation for integration with Symfony: [Install Gedmo Doctrine2 extensions in Symfony2](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md)

is broken.

### Possible solution

I think that a link to this version of the _Doctrine extension_ https://github.com/doctrine-extensions/DoctrineExtensions/tree/v2.4.42 will do the job.
Maybe a note to indicate that this version may present incompatibilities with the user _Doctrine_ version and that another version of the _extensions_ may be best suited because I don't know if this particular version will fit all the Symfony documentation pages version (so from 2.7 to 5.4).

**Comment by javiereguiluz** [comment]
Thanks for reporting this error. Could you please tell me in which pages of Symfony 5.4 or 6.2 or 6.3 docs this error occurs? Those are the only maintained versions for the doc and I can't find that link in them. Thanks.

**Comment by RyanFarrah67** [comment]
Sorry, 5.4 doesn't present the problem, i didn't read it but the issue I saw is really about the old doc not
the new one so not the 5.4 version. 

The affected versions go from 2.7 to 4.2 in reality.

**Comment by javiereguiluz** [comment]
Thanks for checking this. Sadly, we must close as won't fix then. We only update the contents of the maintained Symfony versions: https://symfony.com/releases#maintained-symfony-branches
