### ISSUE TITLE
[Mime] Added getDispostion() to TextPart to get current content disposi…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18210]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49824
| PR author(s) | @Cyb0rk
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
I'm closing this as "won't document". It's a self-explanatory method that it's available just right where you need it, so developers will discover it via their IDE or text editor.
