### ISSUE TITLE
[BrowserKit][HttpClient] Update the value of some user agents to comply…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18223]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50053
| PR author(s) | @javiereguiluz
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alamirault** [comment]
I found no reference of these user-agents. So I I think there is nothing to do. Are you agree @javiereguiluz ?
