### ISSUE TITLE
[HttpClient] Allow using multiple base_uri as array for retries

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18224]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49809
| PR author(s) | @Tiriel
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by Tiriel** [comment]
Ok let's finish the job, going to look into this asap if it's ok!
