### ISSUE TITLE
[Security] Added error code to `UserPassword` constraint

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18231]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50069
| PR author(s) | @okorneliuk
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Closing because this is an internal detail. We don't document these error codes for any constraint. Thanks.
