### ISSUE TITLE
composer dump-env prod

### ISSUE THREAD

**Issue by Ernestopheles** [symfony/symfony-docs#18249]
command not working:

> composer dump-env prod

                                      
  Command "dump-env" is not defined.  

composer --version
Composer version 2.5.1

**Comment by xabbuh** [comment]
Which steps did you do before? How did you set up your Symfony application?

**Comment by Ernestopheles** [comment]
This error I get everywhere; all being Contao websites. But shouldn't that be independent of the special project as it is a composer command? If I just open a terminal under Linux having composer installed I get this error.

**Comment by xabbuh** [comment]
`dump-env` is a command provided by the Symfony Flex plugin.

**Comment by Ernestopheles** [comment]
ok, sorry, did not know Contao is not using Flex.
