### ISSUE TITLE
Documentation references non-existent class

### ISSUE THREAD

**Issue by unlikenesses** [symfony/symfony-docs#18242]
In the [security.remember_me_aware](https://symfony.com/doc/current/reference/dic_tags.html#security-remember-me-aware) section, there is a reference to the `AbstractAuthenticationListener` class, which no longer exists (it was removed in [this commit](https://github.com/symfony/symfony/commit/922c1314bd73f14fb8aa80e62b27b3bca66ee7b0)).

**Comment by alamirault** [comment]
I think this tag is not used anymore (`throw new \LogicException(sprintf('Symfony Authenticator Security dropped support for the "security.remember_me_aware" tag, service "%s" will no longer work as expected.', $serviceId));`) in 6.x but I found some references in [source code](https://github.com/symfony/symfony/search?q=%22security.remember_me_aware%22)

@wouterj Can you confirm that code should have been deleted ? I can make a PR on 6.2 in this case ?

**Comment by javiereguiluz** [comment]
Hi @chalasr Do you remember if this `security.remember_me_aware` tag was really removed from code? It's confusing that there are some occurrences it in the code. Thanks

**Comment by wouterj** [comment]
Yes, it is removed as of 6.0 (and deprecated somewhere in 5.x).

**Comment by javiereguiluz** [comment]
OK ... then we should check if these code occurrences are legit or not: https://github.com/search?q=repo%3Asymfony%2Fsymfony+%22security.remember_me_aware%22&type=code

Thanks!

**Comment by wouterj** [comment]
Yes, we can remove them.
