### ISSUE TITLE
Rendering error with `:class:` and `:phpfunction:` at line breaks

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#18271]
If a `:class:` or `:phpfunction:` shortcut happens to be placed on a line break (on the rendered page), the space between the icon and the last word before it is missing.

Two examples at https://symfony.com/doc/5.4/components/options_resolver.html

Source:
```
Also, the default values of the options are buried in the business logic of your
code. Use the :phpfunction:`array_replace` to fix that::
```
Page:
> Also, the default values of the options are buried in the business logic of your code. Use theICON
array_replace to fix that:

Source:
```
Like before, all options will be guaranteed to be set. Additionally, an
:class:`Symfony\\Component\\OptionsResolver\\Exception\\UndefinedOptionsException`
is thrown if an unknown option is passed::
```

Page:
> Like before, all options will be guaranteed to be set. Additionally, anICON
UndefinedOptionsException is thrown if an unknown option is passed:

**Comment by OskarStark** [comment]
This issue should be provided on the Symfony-tools/docs-builder repo

**Comment by ThomasLandauer** [comment]
OK, thanks, closing in favor of https://github.com/symfony-tools/docs-builder/issues/158
