### ISSUE TITLE
Single letter Twig function does not appear in Twig reference sidenav

### ISSUE THREAD

**Issue by ker0x** [symfony/symfony-docs#18289]
It seems that the parser has some difficulty to make reference of single letter titles

See the `t` function for example: 

- [twig_reference.rst](https://github.com/symfony/symfony-docs/blob/6.2/reference/twig_reference.rst#t)
- [twig_reference.html](https://symfony.com/doc/current/reference/twig_reference.html#impersonation-exit-url)

**Comment by OskarStark** [comment]
@javiereguiluz can you transfer this issue to docs-builder repo ?

**Comment by wouterj** [comment]
The underline must at least be 3 characters long.

You can see the t, but it is no title as the underline is only 1 character.

**Comment by javiereguiluz** [comment]
I can't see the _"at least 3 underscore characters"_ constraint in the official RST spec: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#sections

So, is this constraint something from our own RST parser and should we fix it?

**Comment by wouterj** [comment]
Ah indeed, I confused it with the Markdown rules.

Sphinx supports a one length underline, so the Doctrine rst parser is not consistent with it. I just checked the code and it should work with a length of 2.

Personally, given we work on a new parser, I would not invest time in fixing this in the current parser and I would suggest to just use a 2 character underline at the moment. Then in the new parser, I'll make sure it is spec-compliant.

**Comment by javiereguiluz** [comment]
Fixed in #18361.
