### ISSUE TITLE
[OptionsResolver] add `ignoreUndefined()` method to allow skip not inte…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18282]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49608
| PR author(s) | @Constantine Shtompel
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alamirault** [comment]
Option can be documented on this page https://symfony.com/doc/current/components/options_resolver.html

@kshtompel Do you want to give it a try ? (If not I will :wink: )

**Comment by javiereguiluz** [comment]
Closing as fixed in #18302.
