### ISSUE TITLE
Documentation.need to be updated in the part of connection to database specially for my sql as below 

### ISSUE THREAD

**Issue by mina20088** [symfony/symfony-docs#18297]
#The Connection Query string must contains the exact mysql version as an example if you have mysql version 8.0.32 # DATABASE_URL="mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=8.0.32" #if you didn`t do that symfony will not create the database for you and you will not have any access

**Comment by javiereguiluz** [comment]
Hi @mina20088. I don't use MySQL ... but for PostgreSQL I just use e.g. `serverVersion=13` in the connection string and everything works as expected.

Could you please take a look to see if this is specific for MySQL or if maybe something in your app has something to do with this? Thanks!

**Comment by wouterj** [comment]
As far as I know, the serverVersion is not required. If it's not set by a setting, Doctrine will connect to the database in order to figure out the server version. However, as this means it is connecting to the database more often (e.g. during cache warmup, as it needs to know the version to generate the cache), it is recommended to provide a server version.

**Comment by javiereguiluz** [comment]
yes ... but it's enough to say "version = 13", "version = 8" or do you need to say "version = 13.4.1", "version = 8.0.32", etc.? At least for PostgreSQL is not needed ... but I don't know about MySQL.

**Comment by wouterj** [comment]
You should always be as precise as possible (also with PostgreSQL), as this will make Doctrine choose the best platform as possible (sometimes, a patch version introduces a small BC break that requires Doctrine to slightly change its tooling).

https://github.com/doctrine/dbal/blob/3.6.x/src/Driver/AbstractMySQLDriver.php#L34-L78
https://github.com/doctrine/dbal/blob/3.6.x/src/Driver/AbstractPostgreSQLDriver.php#L29-L55

**Comment by mina20088** [comment]
MySQL should be precises in defining the version

**Comment by mina20088** [comment]
I have tried it but it never works untill I defined the version that why I made a pull request to update this section

**Comment by mina20088** [comment]
> Hi @mina20088. I don't use MySQL ... but for PostgreSQL I just use e.g. `serverVersion=13` in the connection string and everything works as expected.
> 
> Could you please take a look to see if this is specific for MySQL or if maybe something in your app has something to do with this? Thanks!

Any ways I will try to make a new symfony application  and try this and give you a feedback

**Comment by mina20088** [comment]
@javiereguiluz hi I will make a new application and try this setup again and give a feed back but unfortunately I don't use other drivers like postgres oe SQLite but this issue is happing on the MySQL

**Comment by wouterj** [comment]
I cannot reproduce this issue. When I start a new demo application, spin up a MySQL database and configure the env var without server version, it correctly creates the database:

```> symfony console debug:container --env-vars

Symfony Container Environment Variables
=======================================

 ------------------- ------------------ --------------------------------------------------------------------------
  Name                Default value      Real value
 ------------------- ------------------ --------------------------------------------------------------------------
  APP_SECRET          n/a                "***"
  DATABASE_URL        n/a                "mysql://root:root@127.0.0.1:32771/root?sslmode=disable&charset=utf8mb4"
  VAR_DUMPER_SERVER   "127.0.0.1:9912"   n/a
 ------------------- ------------------ --------------------------------------------------------------------------

 // Note real values might be different between web and CLI.

> symfony console doctrine:database:create
Created database `root` for connection named default
```

Please use one of the support channels (https://symfony.com/support) if you need more help getting this working.

**Comment by mina20088** [comment]
I created a new one and th same issue is there
