### ISSUE TITLE
[Notifier] Add SMS options to Clickatell notifier

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18307]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#48573
| PR author(s) | @gnito-org
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alamirault** [comment]
Reverted/dropped in https://github.com/symfony/symfony/pull/50308 so issue can be closed
