### ISSUE TITLE
Doctrine update Documentation.need to be updated in the part of connection to database specially for my sql as below 

### ISSUE THREAD

**Issue by mina20088** [symfony/symfony-docs#18317]
I made this issue to update the documentation on database part specially in the part that talks about  connection and configuration of my sql connection string connection string must have the version of my sql to work without issue 
The issue below contains all of the details and contain a pull request to update the docs I added my feedback what's next 

https://github.com/symfony/symfony-docs/issues/18297

**Comment by wouterj** [comment]
See https://github.com/symfony/symfony-docs/issues/18297#issuecomment-1547547441
