### ISSUE TITLE
Revert #17299

### ISSUE THREAD

**Issue by FlyingDR** [symfony/symfony-docs#18328]
According to a description of #17299 and https://github.com/symfony/symfony/issues/37626#issuecomment-662349310 information about manual filtering of the Doctrine migrations table was restored in documentation because it was unclear why it was removed previously.

It was removed because of the implementation of automatic registration of Messenger's table schema in Doctrine schema in https://github.com/symfony/symfony/pull/36655 which is landed in Symfony 5.1. 

Because of this, having this tip in the Symfony documentation is not actual and misleading. I would like to propose to revert #17299 to remove it again.

**Comment by javiereguiluz** [comment]
To be honest, I don't fully understand your issue. You say that we should remove this tip, but the resources that you linked (like https://github.com/symfony/symfony/issues/37626#issuecomment-662349310) seem to indicate that we must have that tip.

Could you please elaborate your issue a bit? Thanks!

**Comment by FlyingDR** [comment]
Sure. The tip in #17299 explains how to prevent Doctrine Migrations from removing the Messenger table from the schema. Doctrine's schema tool is unaware of the Messenger's table as it is not part of the application's schema and normally will try to remove it. The provided tip tries to "hide" Messenger's table from the schema tool by filtering it out using a schema filter.

But https://github.com/symfony/symfony/pull/36655 adds support for automatic adding required SQL to the schema. Because of this Doctrine's schema tool will see the Messenger's table SQL as part of the application's schema and will not include table removal in the migration.

Effectively it means that there is no need to hide Messenger's table from the schema tool because it is automatically included in the application's schema. And because of this, the tip has no practical meaning and can be removed.

I submitted this issue several months ago, so I may forget some details of the original intention. It is also possible that I misunderstood something. But at least from the practical point of view Doctrine Migrations does not attempt to remove Mesenger's table nowadays without schema filter from the tip.

**Comment by javiereguiluz** [comment]
I now fully understand the issue. @FlyingDR thanks a lot for the detailed description.

We're trying to fix this issue in #18899.
