### ISSUE TITLE
Missing UriSigner documentation

### ISSUE THREAD

**Issue by alamirault** [symfony/symfony-docs#18330]
Reported by @alexander-schranz  on Slack

https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/HttpKernel/UriSigner.php is not documented.

Improvement in blog post: https://symfony.com/blog/new-in-symfony-5-1-improved-urisigner

I don't know where we can document it usage

**Comment by alexander-schranz** [comment]
From component point of view I think it would be part of: https://symfony.com/doc/current/components/http_kernel.html

**Comment by wouterj** [comment]
I would love to have this somewhere in the framework docs (non-component). I think the Controller article might be the best place for this? (or Routing, but that seems 100% focused on route generation)

**Comment by alexander-schranz** [comment]
Must say I was first confused that it is not part of the routing component 😄, would have expected that its a class there. Or the http-foundation like the [UrlHelper](https://symfony.com/doc/current/components/http_foundation.html#generating-relative-and-absolute-urls). The http-kernel was a little bit unexpected place for that class, for me. Opened a discussion about moving it [here](https://github.com/symfony/symfony/issues/50384).

**Comment by javiereguiluz** [comment]
I'm trying to document this at #18518.

**Comment by alexander-schranz** [comment]
Sounds good for me will try to finish https://github.com/symfony/symfony/pull/50392 next when I have some time.
