### ISSUE TITLE
[7.0] Bump to PHP 8.2 minimum

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18340]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50404
| PR author(s) | @nicolas-grekas
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Closing as fixed in #18360.
