### ISSUE TITLE
[HttpKernel] Add optional `$className` param to `ControllerEvent::getAt…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18368]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50335
| PR author(s) | @HypeMC
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Let's close this as "won't document". We only mention the `getAttributes()` method once in the docs and the new argument added in this PR is trivial to discover and understand. Thanks.
