### ISSUE TITLE
[Serializer] Remove abstract uid denormalization code

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18376]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50558
| PR author(s) | @fancyweb
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
@fancyweb if you have some time for this, could you please check if the docs need to update anything related to this change? Thanks a lot!
