### ISSUE TITLE
Wrong url to PasswordHasher page from Symfony

### ISSUE THREAD

**Issue by merlijndetovenaar84** [symfony/symfony-docs#18383]
On this page [https://github.com/symfony/password-hasher](https://github.com/symfony/password-hasher ) in the right corner, under the title: "About" the URL refers to a page that doesn't exist anymore. It should be [https://symfony.com/components/PasswordHasher](https://symfony.com/components/PasswordHasher) instead of https://symfony.com/password-hasher.

**Comment by xabbuh** [comment]
@fabpot @nicolas-grekas I think one of you needs to fix that.

**Comment by javiereguiluz** [comment]
Sorry about this. The `symfony.com/password-hasher` shortcut URL should work. We have shortcuts for all components:

https://symfony.com/console
https://symfony.com/polyfill-php82
https://symfony.com//event-dispatcher
etc.

So, we've added this missing shortcut URL and when we deploy the changes, it will work as intended. Thanks!

**Comment by javiereguiluz** [comment]
The change has been deployed, so the following URL now works:

https://symfony.com/password-hasher
