### ISSUE TITLE
[Workflow] Invalid php configuration

### ISSUE THREAD

**Issue by pmontoya** [symfony/symfony-docs#18380]
Hi,

I try to switch from yaml to php configuration for one of my workflow and I see that the documentation about this point is wrong (or not up to date, or may be I miss something) on page https://symfony.com/doc/current/workflow.html#creating-a-workflow (PHP configuration).

The class `Symfony\Config\FrameworkConfig` doesn't exists and method `workflows()` neither.
I don't find this class in history of `symfony/config` component.

I'll create a PR for updating documentation if I find how to write this configuration (I someone has a example, it'll be much appriate 😄 )

Thank you.

**Comment by xabbuh** [comment]
These config classes are generated when the cache is warmed up (in `var/cache/dev/Symfony/Config` IIRC).

**Comment by pmontoya** [comment]
Sorry, I miss it.
Thank you for your answer. I close the issue.
