### ISSUE TITLE
[DoctrineBridge] Deprecate using the old DBAL logger system

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18389]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50579
| PR author(s) | @derrabus
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
To solve this, we'll need help here from someone who understands Doctrine well. Thanks a lot!

**Comment by derrabus** [comment]
I haven't found any documentation on the classes that were affected by those deprecations.

**Comment by javiereguiluz** [comment]
That's great news! So, let's close this as "fixed".

Alexander, thanks a lot for taking the time to review this!
