### ISSUE TITLE
[Mailer] Document the optional HttpClient dependency

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#18386]
While reviewing symfony/symfony#50598, I searched the docs for any hints about mailer bridges relying on the HTTP Client, but I found none.

In [the section on 3rd party transports](https://symfony.com/doc/current/mailer.html#using-a-3rd-party-transport), I see a list of composer packages that I can install to enable interfacing with those 3rd party services. This might lead to the false conclusion that simply installing the package next to the name of the service I'd like to interface with is enough. However, this is in most cases only true for SMTP-based transports.

If I want to use the web API of a service instead, I might need to install `symfony/http-client` as well. Not doing so will result in a runtime failure. Taking into account that developers usually rely on MailDev or a similar SMTP-based catcher for local development, that runtime failure might not be discovered until deploying to a staging or production system.

The least we can do here is documenting this optional dependency on the page I've linked above.

**Comment by alexandre-daubois** [comment]
Would something like this suit? :slightly_smiling_face:
 
https://github.com/symfony/symfony-docs/pull/18387

**Comment by derrabus** [comment]
Wow, that was fast. Thanks for picking up this topic so quickly.

**Comment by derrabus** [comment]
Fixed by #18387
