### ISSUE TITLE
[DoctrineBridge] MariaDB server version no longer needs the prefix

### ISSUE THREAD

**Issue by NanoSector** [symfony/symfony-docs#18395]
The MariaDB server version no longer needs the prefix starting with Doctrine DBAL 4.x. The docs currently have a note mentioning the `mariadb-` prefix requirement:
https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration

Doctrine DBAL currently throws a deprecation notice:
```
User Deprecated: Version detection logic for MySQL will change in DBAL 4. Please specify the version as the server reports it, e.g. "10.9.3-MariaDB" instead of "mariadb-10.9". (AbstractMySQLDriver.php:125 called by AbstractMySQLDriver.php:37, https://github.com/doctrine/dbal/pull/5779, package doctrine/orm)
```

This seems to be already implemented by Doctrine: https://github.com/doctrine/dbal/pull/5779

In preparation of DBAL 4.x it might be preferred to change the documentation to avoid confusion.

**Comment by javiereguiluz** [comment]
Thanks fore reporting this.

This deprecation message is triggered since version 3.6.0: https://github.com/doctrine/dbal/releases/tag/3.6.0

But there's something I don't understand:

* This will change in DBAL 4.x
* Specify the version as the server reports

But if we are NOT in DBAL 4 yet, we shouldn't change this, right?

**Comment by NanoSector** [comment]
I feel like it is very much like how Symfony implements changes and reports deprecations for behaviour that will be enforced in the future.

However judging by [the PR which adds the deprecation warning](https://github.com/doctrine/dbal/pull/5844), the change is indeed not functional until DBAL 4.

**Comment by javiereguiluz** [comment]
I've created #18424 to try to solve this. Is it good enough for you? Thanks

**Comment by NanoSector** [comment]
I looked into this a bit more. I think what happened is that https://github.com/doctrine/dbal/pull/5779 initially removed a couple of checks to clean up logic, but https://github.com/doctrine/dbal/pull/5795 reverts this change for reasons specified in it; https://github.com/doctrine/dbal/pull/5844 therefore adds a deprecation warning so this can be definitively changed in DBAL 4.

I think it should be safe to add this to the documentation.
