### ISSUE TITLE
[DoctrineBridge] Remove DBAL 2 support

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18397]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50571
| PR author(s) | @derrabus
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
We do not really need to update documentation arounds this, do we?

ping @derrabus

**Comment by derrabus** [comment]
I did a quick search and haven't found anything that needs an update. Let's close.

**Comment by javiereguiluz** [comment]
Alexander, thanks for reviewing this. Let's close then.
