### ISSUE TITLE
Old Documentation to updated version links to 7.0 instead of 6.3

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#18393]
https://symfony.com/doc/2.6/cookbook/console/console_command.html

<img width="1040" alt="Bildschirmfoto 2023-06-09 um 10 25 37" src="https://github.com/symfony/symfony-docs/assets/1698337/9a9588a6-d7d7-4f7c-a266-782675b71781">

**Comment by javiereguiluz** [comment]
Alexander, thanks for reporting this.

We've just deployed a fix for it, so we're closing this as fixed. Cheers!
