### ISSUE TITLE
[SecurityBundle] Enabling `SecurityBundle` and not configuring it is no…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18390]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50573
| PR author(s) | @alexandre-daubois
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
I don't think that we need to update the documentation around this. The error message does explain the issue well enough.
