### ISSUE TITLE
[DoctrineBridge] Remove deprecated classes and `ContainerAwareEventMana…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18394]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50575
| PR author(s) | @alexandre-daubois
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
This can be closed as nothing seems to appear in the doc about removed classes

**Comment by javiereguiluz** [comment]
Let's close it then. Thanks for reviewing it.
