### ISSUE TITLE
Configuration 

### ISSUE THREAD

**Issue by Peter-omereyone** [symfony/symfony-docs#18400]
Hello guys, can't seem to find .env file after downloading symfony with composer. I was expecting to find the file to configure smtp for testing on my localhost. Well I've been using PHPMailer for some time but people keep saying symfony is the best. So am just trying to learn symfony mailer. So what what I want is how to fire-up and get started. Again  am looking for .env file or the configuration file as seen on the documentation and is there any other thing I need to do to get the mailer ready to work? I can find my way around the code since there's a sample. Please am 100% newbie

**Comment by wouterj** [comment]
Hi! 

Are you following the instructions from https://symfony.com/doc/current/setup.html#creating-symfony-applications to create a new Symfony project? Given you do not see a `.env` file, I suspect you're using a wrong package to create the project.

I'm going to close here, as this is were we track things to document in the documentation. Please use one of the [support channels](https://symfony.com/support) to ask for help from the community.

**Comment by Peter-omereyone** [comment]
@wouterj I just wanted to use symfony mailer must I install the symfony framework? I used composer require symfony/mailer
to install. Is there anything I have to do? Or should I install Symfony

**Comment by wouterj** [comment]
See the readme of the component on how to use it without the framework: https://github.com/symfony/mailer#mailer-component The `.env` file is a framework feature.
