### ISSUE TITLE
Difference between the code and the documentation on option create_new_console of Symfony Process

### ISSUE THREAD

**Issue by spipu** [symfony/symfony-docs#18414]
Hi,

On this page https://symfony.com/doc/current/components/process.html we can read 

> The create_new_console option is only available on Windows!

![image](https://github.com/symfony/symfony-docs/assets/10595905/92f99d1e-e531-4c6e-9ea4-d34ebfd5f4a6)

But on the code https://github.com/symfony/process/blob/6.3/Process.php#L1180 we can read

> Enabling the "create_new_console" option allows a subprocess to continue to run after the main process exited, on both Windows and *nix

![image](https://github.com/symfony/symfony-docs/assets/10595905/a86306f2-0707-447a-b954-d79b55a25a5c)

i checked the code, the method _destruct of the process class has been modified to make it working on linux. I also tested it on debian, and it works.

It is since v5.2

**Comment by javiereguiluz** [comment]
Closing as fixed in #18415.

**Comment by spipu** [comment]
thanks !
