### ISSUE TITLE
[Console] Aligned multiline text in vertical table

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18436]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50691
| PR author(s) | @jaytaph
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
I don't think this needs to be documented. This is easily seen when you build such tables.
