### ISSUE TITLE
[Routing] Add FQCN and FQCN::method aliases when applicable

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18437]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50084
| PR author(s) | @fancyweb
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alamirault** [comment]
Where is the best place to document it ?

Is  a note in https://symfony.com/doc/current/routing.html#generating-urls is ok ?
