### ISSUE TITLE
[Question] Is possible to contribute to documentation with my own library?

### ISSUE THREAD

**Issue by gremo** [symfony/symfony-docs#18456]
I've created a new Docker environment for Symfony (https://github.com/gremo/symfony-sail). I believe in this project and use it at work, on a daily basis (maintaining 40+ Symfony projects). However, it is not yet mature enough for production (it would be in a couple of weeks).

Am I allowed to contribute to the documentation with my own library, or is this repository closed to "new" projects?

Sorry for asking but I can't find this information in the [documentation](https://symfony.com/doc/current/contributing/documentation/overview.html).

**Comment by alexandre-daubois** [comment]
Hello, I'm not sure to understand what you mean by "contribute with my own library"? What would you like to add to the documentation exactly?

**Comment by gremo** [comment]
Hi, thank you, and sorry for any ambiguity. What I meant was to include additional pages and documentation for the project I created, similar to what you can find on https://symfony.com/bundles (although, it won't be a bundle, but rather in a separate section/directory).

**Comment by javiereguiluz** [comment]
Hi @gremo! Sorry, but we don't publish the docs of other projects. The only exception are bundles, but we're very restrictive for that too (to be included, bundles must be very popular or provide some important feature, must have been released a long time ago, etc.)

In any case, thanks for creating this project and don't forget to mention it in the Symfony Slack (https://symfony.com/slack) so others can know about it. Thanks!

**Comment by gremo** [comment]
No problem, thanks for the clarification!
