### ISSUE TITLE
Doing double-shift twice on the documentation breaks search

### ISSUE THREAD

**Issue by alexandre-daubois** [symfony/symfony-docs#18466]
It seems the double-shift shortcut has a little problem on the website. Steps to reproduce:

- Double-shift
- Enter a few words
- Double-shift again, this should flush the previously filled search field
- No search is done when typing something else

Tried in Google Chrome on Ubuntu 23.04.
Good luck on this fix, please tell me if you need any additional info :slightly_smiling_face:

**Comment by javiereguiluz** [comment]
I've spent some time trying to fix this and I couldn't. My guess is that I'm missing some Symfony UX thing somewhere.

I read this (https://symfony.com/bundles/ux-live-component/current/index.html#model-updates-don-t-work-when-external-javascript-changes-a-field) and I triggered the `change` event manually, but it's not working 😐 

I'll keep trying to fix this.

**Comment by alexandre-daubois** [comment]
I guess the source code of the website is in a private repo, but if I can help in any way it would be a pleasure :slightly_smiling_face:

**Comment by smnandre** [comment]
Do you still need a hand on this @javiereguiluz  ?

**Comment by javiereguiluz** [comment]
We've just deployed some fixes for this ... so I'm happy to close it as fixed. Thanks!
