### ISSUE TITLE
[HttpFoundation] Remove deprecated classes, method and behaviors

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18478]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50826
| PR author(s) | @GromNaN
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
It seems this one can be closed
