### ISSUE TITLE
[HttpKernel] Remove deprecated code paths

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18491]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50858
| PR author(s) | @nicolas-grekas
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
- [x] Remove `ArgumentValueResolverInterface`, use `ValueResolverInterface` instead
   (deprecated in #18498)
- [x] Remove `StreamedResponseListener`
    (this is only mentioned in the "Create your own framework" doc; we don't need to update that)
- [x] Remove `AbstractSurrogate::$phpEscapeMap`
   (there are no mentions about this in the docs)
- [x] Remove `HttpKernelInterface::MASTER_REQUEST`
   (there are no mentions about this in the docs)
- [x] Remove `terminate_on_cache_hit` option from `HttpCache`
   (deprecated in #18496)
