### ISSUE TITLE
[Security] Remove deprecated code paths

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18490]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50866
| PR author(s) | @nicolas-grekas
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Before removing deprecated things in 7.0 branch, we need to check if those things are marked as deprecated in 6.2/6.3/6.4 branches. Thanks!

**Comment by alexandre-daubois** [comment]
It seems this one can be closed 🙂

**Comment by javiereguiluz** [comment]
Let's close it as fixed then. One more completed issue for 7.0 branch! Thanks.
