### ISSUE TITLE
[Lock] 7.0 remove deprecations in Lock Component

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18504]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50880
| PR author(s) | @fafiebig
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Before removing deprecated things in 7.0 branch, we need to check if those things are marked as deprecated in 6.2/6.3/6.4 branches. Thanks!
