### ISSUE TITLE
Block quotes are not rendered correctly

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#18535]
Example: The console error messages at https://symfony.com/doc/current/frontend/asset_mapper.html#missing-importmap-entry

Source code has 4 spaces indentation, which should be fine, according to https://docutils.sourceforge.io/docs/user/rst/quickref.html#block-quotes

**Comment by javiereguiluz** [comment]
Thanks for reporting this.

I'm closing it as fixed because we've deployed some changes to add styles to `<blockquote>` elements.
