### ISSUE TITLE
[DependencyInjection] Improve reporting named autowiring aliases

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18559]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50718
| PR author(s) | @nicolas-grekas
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Seems this one can be closed, this error message doesn't appear in the doc

**Comment by nicolas-grekas** [comment]
Don't we have any example of the debug:autowiring command?

**Comment by alexandre-daubois** [comment]
Oh my bad, there is actually a few `debug:autowiring` outputs that needs an update. Taking care of the change 👍
