### ISSUE TITLE
Book // Fast Track // 6.2 // Going from Zero to Production // Initializing the Project // version 5.4 ?

### ISSUE THREAD

**Issue by steiha** [symfony/symfony-docs#18567]
If I got things right the command to initialize the project should reference the current version.

https://symfony.com/doc/current/the-fast-track/en/3-zero.html#initializing-the-project

So I would say that this command uses the old version 5.4 ...
symfony new guestbook --version=5.4 --php=8.1 --webapp --docker --cloud

... so I think it should look like this ...
symfony new guestbook --version=6.2 --php=8.1 --webapp --docker --cloud

Anyway, thanks for the great tools and documentation you create!

**Comment by xabbuh** [comment]
ping @fabpot

**Comment by fabpot** [comment]
Fixed now.
