### ISSUE TITLE
Symfony version update issue

### ISSUE THREAD

**Issue by gopikrish19** [symfony/symfony-docs#18574]
Hi, 

     I have updated my symfony application from 6.2.9 to 6.3.1, once updated the version, I am getting the error from doctrine orm mapping 

     error: **Warning: Attempt to read property "name" on string**

Once i downgrade the version previous version, its working fine, Please let me know the issue with this update

**Comment by javiereguiluz** [comment]
@gopikrish19 I'm sorry about this, but this repository is only to discuss about the Symfony Docs.

For general questions about Symfony support, please use any of the two options listed here under "Open-Source Support":

https://symfony.com/support

Thanks!
