### ISSUE TITLE
[Messenger] Deprecate `StopWorkerOnSignalsListener`

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18583]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50997
| PR author(s) | @HypeMC
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
`StopWorkerOnSignalsListener` is not mentioned in the doc and thus can be closed as there's no deprecation notice to add :slightly_smiling_face: 

But there might be something to add after this comment: https://github.com/symfony/symfony/pull/50997#issuecomment-1645621110
