### ISSUE TITLE
[Console] Add documentation for `ProgressIndicator`

### ISSUE THREAD

**Issue by welcoMattic** [symfony/symfony-docs#18580]
We have a `ProgressIndicator` in Console component for years (almost 10!), but no documentation about it. It could easily be used as spinner to display progression of task without a predictable number of elements.

Code: https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Console/Helper/ProgressIndicator.php

**Comment by alexandre-daubois** [comment]
Having a look :slightly_smiling_face:
