### ISSUE TITLE
[FrameworkBundle] Deprecate doctrine/annotations integration

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18589]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50888
| PR author(s) | @derrabus
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
What's the prefered way to go here?

- Should we simply remove `php-annotations` code blocks and `annotation` occurrences in 7.0?
- Should we add a deprecation message somewhere in 6.4 ? Like next to each `php-annotations` block ?

I can take care of what will be decided :slightly_smiling_face:

**Comment by javiereguiluz** [comment]
Let's ask @wouterj and @xabbuh because they always have good ideas about how to handle deprecations like this one. Thanks.

**Comment by wouterj** [comment]
My first thought would be to simply remove all `php-annotations` blocks in 6.4 already and only leave the annotations docs where we explicitly talk about them (but as far as I see, we most often only talk about attributes in 6.4 already) + add a deprecation directive in only these places.

**Comment by xabbuh** [comment]
I also had the same thought. Adding a deprecation notice to all annotation examples would probably be too much of work.

**Comment by javiereguiluz** [comment]
Closing as fixed in #18590
