### ISSUE TITLE
[Form] Deprecate `FormEvent::setData()` for events that do not allow it

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18594]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51043
| PR author(s) | @HeahDude
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
@HeahDude Is there anything to do here? Or is #18587 sufficient enough (I would say it is)?

**Comment by HeahDude** [comment]
I agree, let's close this issue.
