### ISSUE TITLE
[Config] Better document dumping env vars in prod

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#18605]
I just stumbled upon changes made in https://github.com/symfony/symfony-docs/pull/16416.
Since the Flex command is neither deprecated nor replaced by the core one, I find the description confusing (the core command is not part of Flex).
Also the "new" way requires more boilerplate and is not optimal, to run the command the dotenv files needs parsing, whereas when using composer it can be done before running any console commands.
I suggest to document both ways, explaining why the old one is optimal, and why the new one can be necessary.

I you agree, I would be happy to take care of it.

**Comment by javiereguiluz** [comment]
I'm not an expert about this, so I'm not sure what to do here. Let's ask to our biggest expert @nicolas-grekas to see if he can recommend us what to do. Thanks!

**Comment by nicolas-grekas** [comment]
I agree with @HeahDude (and with @wouterj, which proposed the same): we should tell about the way that just works out of the box, and tell about the more involding way in a "Note" or "Tip" box.

**Comment by HeahDude** [comment]
@nicolas-grekas thanks for the feedback :). I'll take care of it.
