### ISSUE TITLE
Clarify `framework.cache.prefix_seed` config node is only used at compile time

### ISSUE THREAD

**Issue by mbabker** [symfony/symfony-docs#18609]
We use the [`framework.cache.prefix_seed`](https://github.com/symfony/recipes/blob/dc03e6b23f90bfd10520a2a939dd19b8f8ae7016/symfony/framework-bundle/6.4/config/packages/cache.yaml#L3-L4) config in an app that has separate prod and staging environments to help further isolate some of our cache data.  In our app, we've configured this to use an environment variable with a unique value per environment.  However, I recently noticed that one of our caches looked to be getting shared across environments, and after digging, I found this was because the config value is written to the `cache.prefix.seed` container parameter that's only used as a build (compile) parameter.  This resulted in our build step unexpectedly using the env var's default value and our deployment platform env vars having no effect.

To keep others from making this mistake, it might be good to note that this config is only used at compile time.

**Comment by alexandre-daubois** [comment]
Does [this update](https://github.com/symfony/symfony-docs/pull/18616) makes sense to you? :slightly_smiling_face:
