### ISSUE TITLE
[Form] Remove deprecations in form events

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18612]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51076
| PR author(s) | @HeahDude
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by HeahDude** [comment]
Same as #18594, we can close here I think.
