### ISSUE TITLE
[Messenger][Process] add `RunProcessMessage` and `RunProcessMessageHand…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18629]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49813
| PR author(s) | @kbond
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Working on it

**Comment by kbond** [comment]
Awesome, thanks @alexandre-daubois! BTW, I have a few similar PR's that hopefully will be merged soon: https://github.com/symfony/symfony/pull/49814 & https://github.com/symfony/symfony/pull/49815

**Comment by alexandre-daubois** [comment]
Oh that's great! I really can't wait for the `RunCommandMessage` to be merged 😍 Will have an eye on the issues, I'll definitely take care of documenting those two ones once they're merged 💪

**Comment by kbond** [comment]
I'm thinking, once the scheduler documentation is complete, we add a section there as well. I think, for the most part, these features will be used by scheduler (at least, the addition of scheduler is what prompted these features).

(just wanted to note this so we don't forget)
