### ISSUE TITLE
Add types to public and protected properties

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18620]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51069
| PR author(s) | @nicolas-grekas
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
I don't think we need to change anything in the documentation here.
