### ISSUE TITLE
[PsrHttpMessageBridge] Import the bridge into the monorepo

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18637]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51100
| PR author(s) | @fabpot, @dunglas, @KorvinSzanto, @xabbuh, @aimeos, @ahundiak, @Danielss89, @rougin, @csunolgomez, @Jérôme Parmentier, @mtibben, @Nyholm, @ajgarlag, @uphlewis, @samnela, @grachevko, @nicolas-grekas, @tinyroy, @danizord, @Daniel Degasperi, @rbaarsma, @Ekman, @4rthem, @derrabus, @mleczakm, @iluuu1994, @Tobion, @chalasr, @lemon-juice, @franmomu, @cidosx, @erikn69, @AurelienPillevesse
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
There is nothing to change here I think. The change is transparent for the users of the bridge.
