### ISSUE TITLE
[Templating] Remove the component

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18648]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51170
| PR author(s) | @fabpot
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
I guess [this page](https://symfony.com/components) has to be updated, but I don't think we have hands on it in this repository?

**Comment by javiereguiluz** [comment]
You are right. The good news is that the mentioned page (and others like https://symfony.com/stats/downloads) are updated automatically using Packagist.org API. So, when the package is marked as "deprecated" in Packagist.org, it will be shown as "deprecated" on symfony.com too a few hours later.

**Comment by alexandre-daubois** [comment]
Awesome, thank you for the explanation!

**Comment by javiereguiluz** [comment]
@nicolas-grekas if you can, please mark the Templating component as abandoned in Packagist.org so it can be rendered as `Deprecated` on symfony.com. Thanks!

**Comment by javiereguiluz** [comment]
We're going to mark this component as "abandoned" just after the Symfony 7 release. We've taken note of this so we're closing this as "fixed". Thanks.

**Comment by wouterj** [comment]
That sounds like a change in policy. We used to mark packages as abandoned only when all its versions are EOL

The 5.4 and 6.4 version is not abandoned.

**Comment by javiereguiluz** [comment]
I see ... so, we should keep this component "as is" until November 2027?

Could that be confusing? The component is deprecated in 2023 and, starting from November 2023, it won't even exist in new Symfony branches. This could lead to _"what's happening with this component that doesn't exist in 7.x but it's not marked as deprecated/abandoned?"_

**Comment by wouterj** [comment]
It is marked as deprecated, not as abandoned. I think linking the "deprecated" label on https://symfony.com/components to the "abandoned" label on Packagist is maybe not a good idea.

If we mark the package as abandoned on Packagist, everyone (including people on 5.4) will get a warning every time they run composer install/update: `Package symfony/templating is abandoned, you should avoid using it. No replacement was suggested.` This is even more confusing, as this is not a deprecation for 5.4 but for 6.4.

**Comment by javiereguiluz** [comment]
OK, I'm reopening this issue because this is not as clear as I thought. Thanks.

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed". We're going to add a change to symfony.com so we can display this component as "deprecated" without having to mark it as "abandoned" on Packagist. The change will be deployed in the coming hours/days. Thanks!
