### ISSUE TITLE
[Notifier] support local development for sns by adding sslmode option

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18652]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50879
| PR author(s) | @Ferror
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alamirault** [comment]
I created 2 PR to document Amazon Notifier options (5.4), and this new option on symfony code repository
