### ISSUE TITLE
[Serializer] Add support for seld/jsonlint

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18660]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51172
| PR author(s) | @ostrolucky
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alamirault** [comment]
I think it must be documented on https://symfony.com/doc/current/components/serializer.html#encoders

But there is nothing on `JsonDecode` class and theses options (json_decode_associative, json_decode_recursion_depth, json_decode_options)

**Comment by ostrolucky** [comment]
PR created
