### ISSUE TITLE
[HttpKernel] Support backed enums in `#[MapQueryParameter]`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18679]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51004
| PR author(s) | @andersmateusz
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
I tried to document this one but I'm not sure there's a big gain here on doing so. It would mean adding an enum in the `UserDTO` example in `controller.rst` in 6.4, but it feels a bit odd and out of place to suddenly add a enum property in the example all of a sudden. I suggest to close this one
