### ISSUE TITLE
[Intl] Add support for ISO 3166-1 numeric codes

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18672]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51073
| PR author(s) | @benr77
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by benr77** [comment]
Already done https://github.com/symfony/symfony-docs/pull/18610

**Comment by javiereguiluz** [comment]
Closing as fixed in #18610.
