### ISSUE TITLE
Group together all articles on the same subject

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony-docs#18708]
The idea would be to group together all the articles on the same subject into a single page to simplify the search for information in a given field (example: Symfony Messenger).

There are so many different URLs, it's hard to get all the information you need to master a given subject.

- https://symfony.com/doc/current/components/messenger.html
- https://symfony.com/doc/current/messenger.html
- https://symfony.com/doc/current/messenger/dispatch_after_current_bus.html
- https://symfony.com/doc/current/messenger/handler_results.html
- https://symfony.com/doc/current/messenger/multiple_buses.html

What do you think about it ?
If you agree, I can submit a PR to try to improve it.

**Comment by javiereguiluz** [comment]
Hi Aurelien. Yes, we've done this in many different topics (configuration, console, DI, templates, etc.) In the past we created multiple small articles, but that's cumbersome when trying to read everything about a single topic.

So, now we do this:

* Create a single reference article with the 90% of the contents related to that topic
* Keep separate articles for the rest 10% and those edge or very advanced contents related to that topic

So, the trick here is to correctly decide which articles to merge into the main article.

I'm not an expert in the Messenger component. Let's ask @xabbuh and @OskarStark about this to see if they can propose which articles should be merged and which should be kept as separate articles. Thanks!
