### ISSUE TITLE
The documentation about console sections should mention that the height of the terminal is the limit for overwriting

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#18738]
Terminals only allow overwriting the _visible_ content.

https://symfony.com/doc/current/console.html#output-sections should make that clear.
the first use case mentioned in the page (showing multiple progress bars) is fine as progress bars don't grow in height. However, the second mentioned use case (appending content in a table) is more risky (if the table is in the first section and you only append to it and the section is a small one in height, it will work. But that won't work if you try to have 2 sections showing tables in which you append).

See https://github.com/symfony/symfony/issues/35012 for some discussions about it.

**Comment by stof** [comment]
note that Symfony 6.2+ supports setting a max height on sections, which allows to have cases where you have multiple lists in separate sections in which new lines are appended, but by removing older lines. As long as the sum of all max heights is smaller than the terminal height, this will also work fine as shown in https://github.com/symfony/symfony/pull/51355#pullrequestreview-1573615471 (once the bugfix is merged)

**Comment by javiereguiluz** [comment]
Closing as fixed in #18894.
