### ISSUE TITLE
[Notifier][Webhook] Add Vonage support

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18745]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51315
| PR author(s) | @smnandre
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by smnandre** [comment]
Could i get some help to redact this one ? I could use some advice / example

**Comment by OskarStark** [comment]
Check the notifier.rst file in this repo and add your bridge to the table 👍🏻😃

**Comment by smnandre** [comment]
> Check the notifier.rst file in this repo and add your bridge to the table 👍🏻😃

The notifier part was already there, i only added the webhook support 😅

**Comment by OskarStark** [comment]
Oh sorry I missed that. 

We currently don't have a Webhook documentation, so let's keep this ob hold
