### ISSUE TITLE
UX bundle: add information about AssetMapper config

### ISSUE THREAD

**Issue by jmsche** [symfony/symfony-docs#18748]
The [UX bundle docs](https://symfony.com/doc/current/frontend/create_ux_bundle.html) are missing some information about AssetMapper/Import maps.

What I found for now:

- add a "importmaps" config in the "symfony" object, which seems to be the same as the "peerDependencies" config
- configure the bundle to prepend the bundle's asset dist path to the AssetMapper paths
- maybe there's something wrong in my TS config (which should be the same as the docs), but it does miss a default export, so something should be fixed

**Comment by javiereguiluz** [comment]
Closing as fixed in #18755.
