### ISSUE TITLE
How to make symfony work perfectly with Codeigniter 4 framework 

### ISSUE THREAD

**Issue by Gadrawingz** [symfony/symfony-docs#18777]
Need to know how to make symfony work perfectly with Codeigniter 4 framework without any compatibility issue!

**Comment by javiereguiluz** [comment]
@Gadrawingz Codeigniter 4 is a framework and Symfony is also a framework, so you can't run the Symfony framework inside of Codeigniter.

You could install/use some standalone Symfony packages inside Codeigniter or any other PHP application. Please refer to the docs at https://symfony.com/doc and if you have support questions, use any of the free support channels shown on https://symfony.com/support

Thanks!
