### ISSUE TITLE
[Callback] Missing information about payload in callback

### ISSUE THREAD

**Issue by PrOF-kk** [symfony/symfony-docs#18787]
Currently the [documentation](https://symfony.com/doc/current/reference/constraints/Callback.html#callback-1) states that the only parameters passed to the callback are the validated object (if callback is not concete) and the ExecutionContextInterface.  
However since https://github.com/symfony/symfony/pull/16909 the payload is passed as well.  
The examples show this correctly (added with https://github.com/symfony/symfony-docs/pull/6593) but the description does not

**Comment by javiereguiluz** [comment]
Fixed in #18791.
