### ISSUE TITLE
[Mailer][Webhook] Add Sendgrid webhook support

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18800]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50705
| PR author(s) | @WoutervanderLoopNL
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by ChibyJade** [comment]
A Webhook doc for 3rd party transport may be created first.
