### ISSUE TITLE
[Security] Add badge resolution to profiler

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18854]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51585
| PR author(s) | @Jean-Beru
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
I'm closing this because, even if it's a nice feature, there's no need to document this explicitly. Developers will just enjoy this feature when using the profiler. Thanks.
