### ISSUE TITLE
[Validator] Declaration of Custom Constraint

### ISSUE THREAD

**Issue by maMykola** [symfony/symfony-docs#18868]
# Setup

Docs: https://symfony.com/doc/5.4/validation/custom_constraint.html#creating-the-constraint-class
Repo: https://github.com/maMykola/custom-validation-constraint

| Name | Value |
| ----- | ----- |
| Symfony | 5.4.28 |
| PHP | 8.2.10 |

## Steps to reproduce

1. clone the repository `git clone git@github.com:maMykola/custom-validation-constraint.git`
2. install packages `composer install`
3. execute the command `bin/console app:validate-entity`

### Actual Result
The error shown in console:
```log
[critical] Error thrown while running command "app:validate-entity". Message: "Unknown named parameter $mode"

In AcmeEntity.php line 13:
                                 
  Unknown named parameter $mode  
                                 

app:validate-entity

2023-09-15T11:57:01+00:00 [critical] Uncaught Error: Unknown named parameter $mode
```

### Expected Result
The command should be executed without errors.

**Comment by xabbuh** [comment]
That's a bug in the docs indeed. The constraint needs a constructor with a named argument for each option that can be configured (the built-in constraints have that).

**Comment by maMykola** [comment]
> That's a bug in the docs indeed. The constraint needs a constructor with a named argument for each option that can be configured (the built-in constraints have that).

like this one? https://github.com/maMykola/custom-validation-constraint/blob/main/src/Validator/ContainsAlphanumeric.php

**Comment by xabbuh** [comment]
@maMykola indeed

**Comment by javiereguiluz** [comment]
@maMykola would you have some time to send a Pull Request to fix this? If you can't, we'll try to fix this ourselves. Thanks a lot!

**Comment by maMykola** [comment]
> @maMykola would you have some time to send a Pull Request to fix this? If you can't, we'll try to fix this ourselves. Thanks a lot!

sure, I'll try this week.

@javiereguiluz for both 5.4 and 6.3 versions?

**Comment by javiereguiluz** [comment]
You only need to submit one PR for the lowest maintained branch that has the issue. Here's the always updated list of maintained branches: https://symfony.com/releases#maintained-symfony-branches

Then, we'll merge your PR in that branch and all the upper branches, including 6.4 and 7.0.

Thanks!
