### ISSUE TITLE
AutowireServiceClosure Example is Broken

### ISSUE THREAD

**Issue by miqrogroove** [symfony/symfony-docs#18886]
Without promoting the constructor parameter, this example doesn't work.

https://github.com/symfony/symfony-docs/blob/03b667bd132577d262d277e131728c5860b26913/service_container/autowiring.rst?plain=1#L695-L699

It will throw `Warning: Undefined property` every time.

PR to be attached momentarily.

**Comment by javiereguiluz** [comment]
Closing as fixed in #18887.
