### ISSUE TITLE
[Print mode] some content are overflowed between paper pages

### ISSUE THREAD

**Issue by ildar-aim** [symfony/symfony-docs#18900]
While printing the documentation I have noticed that 
1) A new block appears 
![image](https://github.com/symfony/symfony-docs/assets/1235868/25b102d2-4f73-466f-b6d9-f6f6bddca466)
2) It overflows some valuable content

For example, on the page 
https://symfony.com/doc/current/service_container/factories.html

the string `App\Email\NewsletterManager:` is lost between paper A4page1 and A4page2

![Screenshot 2023-09-20 at 12 05 18](https://github.com/symfony/symfony-docs/assets/1235868/79890626-4ed7-4173-ace2-f5c1c203dfed)

**Comment by ildar-aim** [comment]
Save as PDF

![Screenshot 2023-09-20 at 12 19 56](https://github.com/symfony/symfony-docs/assets/1235868/4f5a560c-b9dd-461a-9454-7bd8dcc3afd0)

**Comment by javiereguiluz** [comment]
We've just deployed some fixes to improve the print styles, so this should be fixed. Thanks.
