### ISSUE TITLE
[AssetMapper] Add support for CSS files in the importmap

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18939]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51543
| PR author(s) | @weaverryan
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by OskarStark** [comment]
@weaverryan is this something we need to document?

**Comment by smnandre** [comment]
I think it's been done (probably in the big front/asset mapper update)
- https://symfony.com/doc/current/frontend/asset_mapper.html#handling-css
- https://symfony.com/doc/current/frontend/asset_mapper.html#handling-3rd-party-css
