### ISSUE TITLE
Hover effect in the footer section on the socials icons

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [symfony/symfony-docs#18935]
@javiereguiluz ,Please assign this issue to me under hacktoberfest'2023 contributor 
![footer](https://github.com/symfony/symfony-docs/assets/125626654/4a670a6e-00de-4a3d-a91c-cd935844174c)

**Comment by javiereguiluz** [comment]
Hi @MOHDNEHALKHAN.

Thanks for your proposal but, the source code of symfony.com website is not publicly available, so nobody can submit pull requests to it. Also, we prefer to not add the hover effect to those links.

In any case, there are some Symfony issues that are marked as "Good first issue" that might inspire you for contributions. See https://github.com/symfony/symfony/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Thanks!
