### ISSUE TITLE
[Messenger] RejectRedeliveredMessageException should not be retried

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18945]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51756
| PR author(s) | @nikophil
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by nikophil** [comment]
I think RejectRedeliveredMessageException is not even documented, maybe it's the right occasion to do it

**Comment by alexandre-daubois** [comment]
I think it's really an internal change that doesn't necessarily needs to be in the documentation :thinking: Where would you put this information?
