### ISSUE TITLE
[Serializer] Make `ProblemNormalizer` give details about Messenger’s `V…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18944]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51779
| PR author(s) | @MatTheCat
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
@javiereguiluz I guess this one can be closed, the current description in `serializer.rst` seems enough 🙂 

```rst
:class:`Symfony\\Component\\Serializer\\Normalizer\\ProblemNormalizer`
    Normalizes errors according to the API Problem spec `RFC 7807`_.
```
