### ISSUE TITLE
[FrameworkBundle] Change BrowserKitAssertionsTrait::getClient() to be p…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18948]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51793
| PR author(s) | @fabpot
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Nothing to change here I guess as `BrowserKitAssertionsTrait` is not mentioned anywhere, + seems too internal to be documented 🙂
