### ISSUE TITLE
[AssetMapper] Allow simple, relative paths in importmap.php

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18941]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51729
| PR author(s) | @weaverryan
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
I'm closing as "won't fix". We almost never display the actual contents of `importmap.php` and when we do, we don't explain the internals of it. So, I don't think we need to document this. Thanks.
