### ISSUE TITLE
[AssetMapper] Add audit command

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18989]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51650
| PR author(s) | @Jean-Beru
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
@Jean-Beru I'll be using your screenshots from your PR to document this if it's alright for you :slightly_smiling_face:

**Comment by Jean-Beru** [comment]
@alexandre-daubois No problem, there's no copyright on these screenshots :smile:  Thank you.

**Comment by alexandre-daubois** [comment]
Great! And congrats for this command! :raised_hands:
