### ISSUE TITLE
Docs about PCNTL extension

### ISSUE THREAD

**Issue by phansys** [symfony/symfony-docs#19006]
We have several places where we are using the [PCNTL](https://www.php.net/manual/en/intro.pcntl.php) extension. Recently, some PRs were created to check if the functions or constants provided by this extension are available before trying to use them (by instance, symfony/symfony#51791).

Searching in the codebase and the docs, I don't see any clear insight about the requirement for the extension.
**Docs:**
- https://github.com/search?q=repo%3Asymfony%2Fsymfony-docs%20pcntl&type=code
- https://github.com/search?q=org%3Asymfony+pcntl+language%3AMarkdown&type=code

**Composer suggestions:**
- https://github.com/search?q=repo%3Asymfony%2Fsymfony+pcntl+path%3A**%2Fcomposer.json&type=code

Additionally, there are some reports about issues generated by containers compiled with different setups between the `cli` and the other PHP SAPIs, where the `cli` SAPI was including the extension and the other did not: https://github.com/symfony/symfony/issues/37005.

Considering this sentence in the extension documentation, having the extension enabled only in the `cli` SAPI seems legit:
>Process Control should not be enabled within a web server environment and unexpected results may happen if any Process Control functions are used within a web server environment.

Based on this, I think we should provide clear instructions about how to proceed regarding this extension for the most common use cases.

**Comment by alexandre-daubois** [comment]
I tried to add a few things in the doc about it, hope this helps :slightly_smiling_face:

**Comment by phansys** [comment]
Hi @alexandre-daubois!
First of all, thank you.

I think this helps, but IMO, we should be clear about our position regarding the extension availability and configuration.
- We are suggesting to install the extension? If yes, I think we should include it in the `suggest` section of the related packages.
- We should provide a guide on how configure the extension regarding the different SAPIs.

WDYT?

**Comment by alexandre-daubois** [comment]
Adding it to the `suggest` section is a good idea to me! May I create the PR about it or would you like to do it? :slightly_smiling_face: 

I'm not sure about the configuration of the extension however. I don't think we'd like to write (and maintain) documentation that belongs to other libraries and packages. It is not related to Symfony directly. This is just my opinion, and I think we should ask @javiereguiluz and @OskarStark on this point :slightly_smiling_face:

**Comment by phansys** [comment]
>Adding it to the suggest section is a good idea to me! May I create the PR about it or would you like to do it? 🙂

I'll try to provide the PRs today.

>I'm not sure about the configuration of the extension however. I don't think we'd like to write (and maintain) documentation that belongs to other libraries and packages. It

I'm not suggesting to write docs about how the extension works, but about the proper configuration in a Symfony app, regarding the potential issues in compiled containers shared between multiple SAPIs.

**Comment by nicolas-grekas** [comment]
> Adding it to the suggest section is a good idea to me

For the record, we ruled out "suggest" entries from composer.json files (too much maintenance burden).

**Comment by fabpot** [comment]
> > Adding it to the suggest section is a good idea to me
> 
> For the record, we ruled out "suggest" entries from composer.json files (too much maintenance burden).

It's not just about the maintenance; it's also about the low value those suggestions have.

**Comment by phansys** [comment]
@alexandre-daubois, do you think we have chance to prevent the usage of the extension on the _web_ context? See [this example](https://github.com/symfony/symfony/issues/37005#issuecomment-638163612).

**Comment by alexandre-daubois** [comment]
I'm not sure. The manual states that unexpected behavior may happen "if any Process Control functions are used within a web server environment". Only the usage if discouraged, not the installation of the extension. Also, the PHP setup is often the same between the CLI and the web env so I'm not sure we can really write something about this here :confused:

**Comment by wouterj** [comment]
We've introduced one bug in a single release, which raises awareness of this extension. But I would say it generally shouldn't need such high level of awareness. You only need it, when you need it (i.e. when you rely on process signals).

Symfony takes care of not using signal features when this extension is not available (except for this one case). If anything, we should look into improving our CI to make sure we run a job without the pcntl extension.

Let's get the proposed PR merged :+1:
