### ISSUE TITLE
[AssetMapper] Add outdated command

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19011]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51845
| PR author(s) | @maelanleborgne
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Closing as fixed in #19005.

**Comment by Maelan** [comment]
You pinged the wrong Maëlan, the good one is @maelanleborgne.

**Comment by javiereguiluz** [comment]
Sorry! and thank you for reporting the wrong ping.
