### ISSUE TITLE
[Workflow] Revert deprecation about Registry

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19010]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51976
| PR author(s) | @lyrixx
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
we should probably revert #17878

**Comment by lyrixx** [comment]
I don't think so. I still believe the registry is a bad idea and not performant. Injecting the right workflow is the best option!

**Comment by OskarStark** [comment]
I think it's better to revert the PR and add this as a note/caution/warning, because many issues were raised on how to achieve sth. which is not possible without injecting the whole registry, isn't it?

I would avoid such questions in the future, if we can solve this by documenting it 🤷‍♂️

**Comment by lyrixx** [comment]
We discussed with @alexandre-daubois IRL, and the best things to do is to talk about the registry as late as possible with a big warning: "Don't use it, but if you need to use it, here is the solution"
