### ISSUE TITLE
[HttpFoundation] Cookies Having Independent Partitioned State (CHIPS)

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19027]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52002
| PR author(s) | @fabricecw
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Hi @fabricecw! Congrats on your first PR :clap: Would you like to write the doc for this feature or can I take care of it? :slightly_smiling_face:

**Comment by fabricecw** [comment]
Hi @alexandre-daubois! I checked the docs and I'm not sure if there is a useful spot to document the new flag. I thought about documenting all flags for cookies, but not sure if this really helps. Glad about any inputs from your side!

**Comment by alexandre-daubois** [comment]
I would take a look at https://symfony.com/doc/current/components/http_foundation.html#setting-cookies. Then, at the end of this section, I would add something like this :

```rst
You can also define a `partitioned cookie`_ thanks to the :method:`Namespace::withPartionned` method::

// Some example

.. versionadded:: 6.4

    The support fort partionned cookies was introduced in Symfony 6.4.

// At the end of doc
.. _`partitioned cookie`: (url to some external doc)
```

That's how I would do it :slightly_smiling_face:

**Comment by alexandre-daubois** [comment]
I agree that there wouldn't be much added value in documenting all the cookie flags. But as @nicolas-grekas pointed out in your PR, it's an important, new and little-known (for now) change. I personally think that's worth mentioning, at least in a few lines, at this location.

Feel free to ping me in your PR if you want me to have a look at it once it's ready!

**Comment by fabricecw** [comment]
Great, thank you! Let me work something out and I would appreciate your feedback.

**Comment by javiereguiluz** [comment]
I'm going to publish a "New in Symfony 6.4" post about this early next week. You could use it as inspiration if you want.

**Comment by fabricecw** [comment]
Thanks! I'm a bit busy these days but I will address the docs as soon as I can.

**Comment by javiereguiluz** [comment]
Here's the blog post: https://symfony.com/blog/new-in-symfony-6-4-chips-cookies

I'd say in the docs we shouldn't explain at all what these CHIPS cookies are. Just link to good resources like MDN.

No worries Fabrice. There are many active contributors (like @alexandre-daubois for example) and some can take over and document this if needed. Thanks!
