### ISSUE TITLE
[AssetMapper] Add a "package specifier" to importmap in case import nam…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19031]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52024
| PR author(s) | @weaverryan
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Hey @weaverryan, we may need your help here 😄 The PR is big! But it _seems_ these are major improvements for the DX and I'm not sure there is something to add or update in the doc. Can you confirm? Thank you! 😊

**Comment by weaverryan** [comment]
My pleasure - thanks for asking about it :). I plan to look at the AssetMapper docs fairly soon and make sure they are fully up to date for 6.4. However, it makes even more sense to make sure, piece-by-piece, that we are talking about the new stuff and not forgetting anything. Then my PR can just be a small cleanup and rephrasing.

ANYWAY, I'm not sure if anything is needed here either. The use-case would be that someone wants to add a package to their system - e.g. `bootstrap` - but alias it to some other name - e.g. `shoestrap`. That's a rare thing to do, and there is a syntax for doing it in `importmap:require` and this syntax IS documented there: https://github.com/symfony/symfony/blob/c02610e501a78faca37a5b6051f3ca5592c67af0/src/Symfony/Component/AssetMapper/Command/ImportMapRequireCommand.php#L60-L62

So, I'm not sure that's worth mentioning tbh. Perhaps we could document it if we *actually* get a few people who are trying this and can't figure it out.
