### ISSUE TITLE
[FrameworkBundle][Serializer] Deprecate annotations

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#19036]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51470
| PR author(s) | @alexandre-daubois
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by OskarStark** [comment]
We should remove it in 7.0 entirely, WDYT @nicolas-grekas ?

**Comment by nicolas-grekas** [comment]
In 6.4?

**Comment by OskarStark** [comment]
Yeah its still valid and you can use it, so we "deprecated" it in #19046 but will remove any mention about AnnotationLoader in 7.0

**Comment by xabbuh** [comment]
Is there anything else to do here?

**Comment by alexandre-daubois** [comment]
It's been removed from the 7.0 doc, so I'd say no :slightly_smiling_face:
