### ISSUE TITLE
[validation/translations] Add `TranslatableMessage` class to doc

### ISSUE THREAD

**Issue by cavasinf** [symfony/symfony-docs#19049]
Can we add a paragraph in https://github.com/symfony/symfony-docs/blob/6.4/validation/translations.rst about how to translate with [TranslatableMessage](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Translation/TranslatableMessage.php) since it is out from [Symfony 6.2 (blog)](https://symfony.com/blog/new-in-symfony-6-2-better-php-translation-extractor)

Like so:
```php

use Symfony\Component\Translation\TranslatableMessage;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[Assert\Callback]
public function validate(ExecutionContextInterface $context, mixed $payload): void
{
    $context->buildViolation(new TranslatableMessage('author.name.not_blank', [], 'validators'))
            ->atPath('name')
            ->addViolation()
    ;
}
```

**Comment by alexandre-daubois** [comment]
I think that's a good idea, would you like to provide a PR?

**Comment by cavasinf** [comment]
First time writing in rst.. but I tried.
Can you check it @alexandre-daubois and tell what need to be changed?

Also, how do you check the final look? With references/code block/... (I'm a Markdown guy)

**Comment by alexandre-daubois** [comment]
I made a feedback 🙂 

If you want to have a look at the "final" look, you can follow steps of the README to build the doc locally: https://github.com/symfony/symfony-docs#build-documentation-locally
