### ISSUE TITLE
[AssetMapper] Warn of missing or incompat dependencies

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#19052]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51849
| PR author(s) | @weaverryan
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
I'd say it's more a DX improvement that doesn't necessarily needs to be documented
