### ISSUE TITLE
[Workflow] List place and transition listeners in profiler

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19063]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51211
| PR author(s) | @lyrixx
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by lyrixx** [comment]
Like #19061, I think this one does not need documentation
