### ISSUE TITLE
Problem with Tutorial Code for Retrieving Comments from a Specific Conference

### ISSUE THREAD

**Issue by alouiMK** [symfony/symfony-docs#19103]
I'm facing an issue while following a Symfony tutorial. The problem is related to retrieving comments associated with a specific conference. Here's a detailed description of the issue:

- I'm currently following a Symfony tutorial to build a conference guestbook application.
- In this application, I need to retrieve comments for a particular conference.
- The tutorial provides code for this purpose, but it isn't functioning as expected.
- I have confirmed that there are comments stored in the database for various conferences.
- However, when I use the provided code to retrieve comments for a specific conference, it doesn't return any results.
- Notably, I can successfully retrieve all comments using $commentRepository->findAll().
- I'm seeking assistance to understand why the code from the tutorial isn't functioning as intended and to find a solution that allows me to correctly retrieve comments for a specific conference.

The code I'm using in my controller is as follows:
```php
/**
 * @Route("/conference/{id}", name="conference")
 */
public function show(Environment $twig, Conference $conference, CommentRepository $commentRepository): Response
{
    
    return new Response($twig->render('conference/show.html.twig', [
        'conference' => $conference,
        'comments' => $commentRepository->findBy(['conference' => $conference], ['createdAt' => 'DESC'])
    ]));
}
```
Your assistance in resolving this issue is greatly appreciated. Thank you for your help and insights.

**Comment by alexandre-daubois** [comment]
I think this is something you might address [to discussions](https://github.com/symfony/symfony/discussions) :slightly_smiling_face:
