### ISSUE TITLE
Please stop using "skoop" for installation symfony in windows.

### ISSUE THREAD

**Issue by alexeyp0708** [symfony/symfony-docs#19125]
### Description

This is such a crude solution that I deleted important files because of it and am struggling with recovery
https://github.com/ScoopInstaller/Scoop/issues/5726

They forcefully delete the entire directory, which is a serious mistake. As a result of this error, I lost important data.
https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/bin/uninstall.ps1#L57

Until they fix this issue, it's best to include other ways to install symfony in your instructions.

**Comment by curry684** [comment]
How is this an important issue for Symfony developers to solve? I'm sorry for the issues you are experiencing but you are having an issue with Scoop, not Symfony. To my knowledge, Symfony only officially recommends using Scoop to install the Symfony CLI, which is unrelated to the framework, its components and your project files.

**Comment by alexeyp0708** [comment]
I'm not trying to convince. I understand that there are problems with skoop,
I learned about SCOOP from your documentation when I wanted to install Symfony Cli.
But the SCOOP product turned out to be so raw that it led me to this problem.
Previously, the description of the procedure for installing symfoni-cli on Windows was different

I installed scoop for symfony-cli because it says so in your documentation.
I think it’s worth adding additional sources to the documentation for installing symfony-cli for Windows or installing and configuring it manually.

**Comment by stof** [comment]
@alexeyp0708 the download page already has an alternate method for installing the CLI by downloading it manually.

**Comment by wouterj** [comment]
I understand loosing files is very frustrating, but I'm not sure if an issue in the deinstallation process of Scoop is very much related to Symfony CLI.

Scoop appears a commonly used package manager to install development tools. We've been using the Scoop installation instructions for Windows since January 2022. And, as said by @stof, the download page contains an alternative by installing the binaries directly.

I don't think there is anything for us to do here.

**Comment by dennisheiden** [comment]
> @alexeyp0708 the download page already has an alternate method for installing the CLI by downloading it manually.

(Windows here)
I'm new to the symfony-cli and the provided information on the website and in the binary's readme is just incomplete. And yes, I'm not used to use console binaries. What I'm supposed to do with the binary? Why not just include an installer which does the setup.

Scoop btw. doesn't work, at least for me:

![image](https://github.com/symfony/symfony-docs/assets/25924499/ea9e4cd8-aad2-4944-8bcc-74043c48ef20)

(I already did the bucket updates etc.)

![image](https://github.com/symfony/symfony-docs/assets/25924499/55827b60-d184-49da-b2fb-c0c06878ede2)
![image](https://github.com/symfony/symfony-docs/assets/25924499/44e0a8e1-7baa-4c58-8864-5f4f23702f5e)

Sorry, I'm just frustrated. I just want to build quick with Symfony and spend hours researching all the pre-install setup stuff.

**Comment by wouterj** [comment]
Please use one of the community support channels to get help: https://symfony.com/support

**Comment by dennisheiden** [comment]
> Scoop appears a commonly used package manager to install development tools. We've been using the Scoop installation instructions for Windows since January 2022. And, as said by @stof, the download page contains an alternative by installing the binaries directly.
> 
> I don't think there is anything for us to do here.

I think a bit more information in the readme file about the manual install method would be really useful (instead of just refering to the website which contains (afaik) no information at all).
