### ISSUE TITLE
[Form] Deprecate not configuring the `default_protocol` option of the `…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19146]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50922
| PR author(s) | @MatTheCat
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by MatTheCat** [comment]
I guess documentation update must wait v8 when the default value will be changed?
