### ISSUE TITLE
Does Symfony\Config\MonologConfig exist?

### ISSUE THREAD

**Issue by ghost** [symfony/symfony-docs#19156]
When searching Github for `org:symfony MonologConfig` no such PHP class (or whatever PHP like) exists.

However in docs we can see this (in PHP config tab):
https://symfony.com/doc/current/logging/channels_handlers.html#switching-a-channel-to-a-different-handler

**Comment by 94noni** [comment]
those files are generated dynamically in the cache folder, as per their class comment "* This class is automatically generated to help in creating a config."

to help/ease the definition of container config etc

**Comment by ghost** [comment]
You're right. Thank you. Do you think there is a place in the documentation where we could mention this?

**Comment by 94noni** [comment]
no idea really, perhaps lets wait core maintainers ideas if it is first relevant and if so, where can it be documented :)

**Comment by ghost** [comment]
btw. do you know when this feature (creating config classes on the fly) was introduced? I'd really like to read PR description and discussion in comments.

**Comment by 94noni** [comment]
no idea :s 
perhaps try searching for some comment of the generated class on the symfony/symfony repo and find with git blame some original PR

**Comment by alexandre-daubois** [comment]
I once saw the news about it and that how I learnt it was generated on the fly, but I can't find it anymore 🤔

Anyway I think I know where we can add this mention, as you're not the first to ask. I think it worth it. I'll have a look today 😊

**Comment by ghost** [comment]
> do you know when this feature was introduced?

https://github.com/symfony/symfony/pull/40600

**Comment by alexandre-daubois** [comment]
Actually this is something already present in the docs: https://symfony.com/doc/current/configuration.html#using-php-configbuilders

But I still created a new PR to add a note about indexing those classes, as it is a recurring question anyway
