### ISSUE TITLE
[AssetMapper] What about upgrading packages (dependencies)?

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#19163]
In Webpack Encore, I  can do `yarn upgrade-interactive` (probably also possible in npm) to check for 3rd party package updates - basically the same as `composer update`. Is something like this available in AssetMapper, and how?
To me this is such a handy feature that it should be included in the comparison table at https://symfony.com/doc/current/frontend.html - might be a crucial feature for some people.

The only documentation I could find is at https://symfony.com/doc/current/frontend/asset_mapper.html#importing-3rd-party-javascript-packages

> To update all 3rd party packages in your importmap.php file, run:
php bin/console importmap:update

But what does this command do exactly?

Ping @weaverryan

**Comment by smnandre** [comment]
```
php bin/console importmap:update 
```

And some others here: https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/AssetMapper/Command/

**Comment by javiereguiluz** [comment]
Closing as fixed because the docs (see https://symfony.com/doc/current/frontend/asset_mapper.html#importing-3rd-party-javascript-packages) now explain the `importmap:outdated` and `importmap:update` commands.

Thanks.
