### ISSUE TITLE
[Website] Wrong dev versions in the select input

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#19197]
Hello! I noticed that when the time comes for many dev versions of symfony, the select is missing some:

<img width="290" alt="Screenshot 2023-11-29 at 11 31 34 AM" src="https://github.com/symfony/symfony-docs/assets/10107633/38d29e0d-fbe7-492f-a2d4-22a0087bfbee">

7.0 and 7.1 should be mentioned as `(dev)` versions just like 6.4.

I guess the logic in the `for` should always add it until the current version is matched.

**Comment by OskarStark** [comment]
@javiereguiluz can you please have a look on this one? Thanks

**Comment by javiereguiluz** [comment]
Thanks for reporting this Jules.

After thinking about this, I've decided to close this as "won't fix".

The worst-case (6.4 + 7.0 + 7.1) only happens for 1 week every 2 years. And the other case (6.4 + 7.0) happens for a few weeks every 2 years.

Changing this would be a non-trivial amount of work so, given that it's a rare temporary issue, let's keep it. Thanks for your understanding 🙏
