### ISSUE TITLE
[Messenger] Add `--all` option to `messenger:consume`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19213]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52411
| PR author(s) | @javaDeveloperKid
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Hi @javaDeveloperKid, it seems it is your first merged feature. Congrats! Would you like to try to document it? :slightly_smiling_face:

**Comment by ghost** [comment]
Sure. I can't remember why I haven't done that together with a feature :thinking:

**Comment by ghost** [comment]
@javaDeveloperKid Hey there, I would like to work on this.!

**Comment by ghost** [comment]
@alexandre-daubois If u don't mind can u guide me through how raising PR works in this repo, I am new to this repo?
