### ISSUE TITLE
Incorrect file location to code sign smyfonys binary on MAC OS

### ISSUE THREAD

**Issue by red-smeg** [symfony/symfony-docs#19223]
Hi,

I'm using the latest version of the CLI 5.7.3 running on macOS (Sonoma) 14.2 and in the documentation on page [https://symfony.com/doc/current/setup/symfony_server.html](https://symfony.com/doc/current/setup/symfony_server.html)

it states that to code sign it you should run the command 

`sudo codesign --force --deep --sign - /opt/homebrew/Cellar/symfony-cli/{version}/bin/symfony`

I believe the location for the homebrew Cellar has moved to  /usr/local/Cellar

**Comment by xabbuh** [comment]
Thank you for the report @red-smeg. Can you please check if the changes I propose in #19224 would solve this for you?

**Comment by red-smeg** [comment]
When I do the command in the PR I get 

❯ whereis -q symfony
/usr/local/bin/symfony

So not sure that will fix it.  That said I have updated using Cakebrew to CLI version 5.8.14 and all is well

**Comment by javiereguiluz** [comment]
@red-smeg if you run this command, do you see multiple locations for the `symfony` binary?

```
❯ whereis -a symfony
```
