### ISSUE TITLE
[HttpClient] Add HttpOptions->addHeader as a shortcut to add an header …

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19236]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52946
| PR author(s) | @Dean151
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by Dean151** [comment]
I'd be happy to help here as well, but on the Http-Client documentation, there is no mention of the HttpOptions object at all.
https://symfony.com/doc/current/http_client.html

**Comment by wouterj** [comment]
Hi @Dean151. Congratz with the code PR merge :)

I think it makes sense to document this nice helper class. We can add a little paragraph to https://symfony.com/doc/current/http_client.html#configuration saying like "There is this nice helper that you can use to build up the options array". And then show an example (maybe even copy the existing code example and provide the HttpOptions alternative).

Then, I don't think we need to document all available methods on this class in the documentation: we can just link to the class and let people discover all methods themselves (or use their autocompletion).

Are you willing to do this task? (happy to guide you)

**Comment by Dean151** [comment]
I'd be happy to write a small generic paragraph on HttpOptions on this page.
But since this class exists since 4.3, should I target 4.3 branch?

**Comment by wouterj** [comment]
In the docs, we're following the ["maintained versions"](https://symfony.com/releases#symfony-releases-calendar) from Symfony's release policy. So it would be great if you submit this to the 5.4 branch (the oldest maintained branch).
