### ISSUE TITLE
[Mailer] Dispatch event for Postmark's "inactive recipient" API error

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19233]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52916
| PR author(s) | @vicdelfant
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by vicdelfant** [comment]
@fabpot given that there is no clear structure for documenting transport-specific features like this yet, are there any objections to adding it under the [Mailer Events](https://symfony.com/doc/7.1/mailer.html#mailer-events)? Also in case the `PostmarkDeliveryEvent` (or `DeliveryEvent`, rather) would be transport-agnostic in the future.

**Comment by xabbuh** [comment]
Would it make sense to add this to the readme of the Postmark bridge in the code repository?

**Comment by vicdelfant** [comment]
That would be similar to the ones for Sendgrid and Sendinblue, so I guess it could work? IMHO it prevents the official docs from get cluttered with information that’s too specific.
