### ISSUE TITLE
[PropertyAccess][Serializer] Fix "type unknown" on denormalize

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19232]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52879
| PR author(s) | @seferov
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
I think this can be closed, nothing to add in the doc here 🙂

**Comment by seferov** [comment]
> I think this can be closed, nothing to add in the doc here 🙂

Agree.

@fabpot thanks for merging the PR
