### ISSUE TITLE
"Read Documentation" link to Clock Component documentation missing

### ISSUE THREAD

**Issue by pathmissing** [symfony/symfony-docs#19256]
I discovered that the "View Documentation" link is missing for the clock component in the components overview:
https://symfony.com/components/Clock

To the best of my knowledge, the "Symfony Components" page is not part of the symfony-docs repository, therefore this issue might be misplaced. If someone can point me to the right direction I will gladly create a merge request for the fix.

**Comment by SebLevDev** [comment]
For me the documentions of the component is on symfony-docs repository
https://github.com/symfony/symfony-docs/blob/7.0/components/clock.rst

**Comment by xabbuh** [comment]
It's also readable at https://symfony.com/doc/current/components/clock.html. But the link is indeed missing.

**Comment by pathmissing** [comment]
You are right, I just figured I mention it because the page /components/Clock was the first result I saw on Google for my specific search term.

**Comment by ghost** [comment]
@pathmissing Hey, I would like to solve it if you don't mind : )

**Comment by OskarStark** [comment]
Sure, go ahead, thanks

**Comment by wouterj** [comment]
This list is maintained in an internal repository. Let's friendly ping @javiereguiluz if he can fix this for us.

**Comment by javiereguiluz** [comment]
We've just deployed some fixes for this. The doc link for the Clock component and other components should now work. Thanks!
