### ISSUE TITLE
[Scheduler] Missing docs

### ISSUE THREAD

**Issue by KDederichs** [symfony/symfony-docs#19264]
Hey,

the Scheduler has been around for a while now (even if experimental) but there's still no docs for it (https://symfony.com/doc/current/scheduler.html is 404).

Question would be what's missing or do you generally only release docs for non experimental stuff?

**Comment by alexandre-daubois** [comment]
@alli83 is actively working on it :slightly_smiling_face: We're working with @kbond and @weaverryan to first create an outline of what the documentation will look like.

We've never been so close to see the documentation of this component! :+1:

**Comment by KDederichs** [comment]
Haha ok thanks for the update, looking forward to seeing it then :D

**Comment by OskarStark** [comment]
For reference
* https://github.com/symfony/symfony-docs/pull/19244

**Comment by javiereguiluz** [comment]
Let's close this as "fixed" because the initial docs have been merged and we're currently working on sending PRs to document the missing parts. Thanks.
