### ISSUE TITLE
[AssetMapper] Incorrect code example

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony-docs#19311]
On this page https://symfony.com/doc/6.4/frontend/asset_mapper.html#page-specific-css-javascript

This block 

![ScreenShot-2023-12-18-23 31 46](https://github.com/symfony/symfony-docs/assets/400092/0ec3aee7-200a-4d36-827d-4aa6ef1a5224)

causes this error

![ScreenShot-2023-12-18-23 32 47](https://github.com/symfony/symfony-docs/assets/400092/0aa272dd-344b-405c-91dd-274f8db2646b)

Because the entrypoints should be passed as an array, The correct code should be 

`{{ importmap(['app', 'checkout']) }}`

**Comment by OskarStark** [comment]
cc @smnandre @weaverryan

**Comment by smnandre** [comment]
That is 100% true

**Comment by PhilETaylor** [comment]
Thanks!
