### ISSUE TITLE
[HttpKernel] Add `HttpException::fromStatusCode()`

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#19336]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#53212
| PR author(s) | @nicolas-grekas
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
We don't have a dedicated place for HttpException. Thus, I'm not sure this should be documented somewhere.

**Comment by javiereguiluz** [comment]
I'm not sure either. Let's ask @wouterj, @xabbuh and @OskarStark if they think we should document this. Thanks!

**Comment by xabbuh** [comment]
I don’t think we need it.
