### ISSUE TITLE
[AssetMapper] Add integrity hash to the default es-module-shims script

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19349]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#53251
| PR author(s) | @smnandre
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because this is an implementation detail. We don't display the exact URL of the shim in the docs, so there's no need to add the integrity hash to it. Thanks.
