### ISSUE TITLE
Babel configuration docs does not mention configureBabelPresetEnv

### ISSUE THREAD

**Issue by stollr** [symfony/symfony-docs#19355]
In the encore docs about the [Babel configuration](https://symfony.com/doc/current/frontend/encore/babel.html) is is explained how to use `.configureBabel`. But nothing is said about `configureBabelPresetEnv`.

**Comment by javiereguiluz** [comment]
Let's ask @WebMamba to see if we should add something in the docs about `configureBabelPresetEnv()`. I don't know what that is and if Encore supports it or not. Thanks!

**Comment by WebMamba** [comment]
Hey, I think this is not documented because it's part of the recipes. So when you install webpack-encore you should endup with.
```js
.configureBabelPresetEnv((config) => {
  config.useBuiltIns = 'usage';
  config.corejs = 3;
})
```

We can maybe add this code in the snippet of this page: https://symfony.com/doc/current/frontend/encore/babel.html ?

**Comment by javiereguiluz** [comment]
@WebMamba thanks for your comment ... in #19460 we're trying to make the change you proposed.

**Comment by stollr** [comment]
It would be nice if a link to an explanation of those preset env settings could be added, too.

**Comment by WebMamba** [comment]
Do you mean a link to this page: https://babeljs.io/docs/babel-preset-env ?

**Comment by stollr** [comment]
Yes, that's correct

**Comment by javiereguiluz** [comment]
Good idea! I updated the PR to add the link. Thanks.
