### ISSUE TITLE
5.4 docs are broken

### ISSUE THREAD

**Issue by oliveiraev** [symfony/symfony-docs#19378]
When I select 5.4 docs version, it redirects me to 5.x and every single documentation page renders a 404 error.

<img width="339" alt="image" src="https://github.com/symfony/symfony-docs/assets/320460/7e6bee7d-4e82-4949-b8c3-e7fa57d88951">

Is not a problem with the selector itself. If I directly refer to any 5.4 link it also redirects me to 5.x and then errors with 404.

https://symfony.com/doc/5.4/setup.html
https://symfony.com/doc/5.4/forms.html

It was working until yesterday about 3pm UTC.

Thank you for the amazing work.

**Comment by Jibbarth** [comment]
@javiereguiluz announced this change on the symfony slack here : https://symfony-devs.slack.com/archives/C8WHX21K7/p1704366643682589

![image](https://github.com/symfony/symfony-docs/assets/3168281/01615250-1b22-4e63-979c-fce2deecb83b)

There is no more 404 on link you provided now (at least, from my side :sweat_smile:)

**Comment by javiereguiluz** [comment]
Yes, the reported error only happened for a while because we were in the middle of this big change. But, everything should be working now.

We've also published a blog post about this: https://symfony.com/blog/simpler-versioning-for-symfony-docs

Let's close as fixed then. Thanks.

**Comment by oliveiraev** [comment]
> @javiereguiluz announced this change on the symfony slack here : https://symfony-devs.slack.com/archives/C8WHX21K7/p1704366643682589
> 
> 
> 
> ![image](https://github.com/symfony/symfony-docs/assets/3168281/01615250-1b22-4e63-979c-fce2deecb83b)
> 
> 
> 
> There is no more 404 on link you provided now (at least, from my side :sweat_smile:)

I confirm that everything is okay by now.

Thank you for the clarification and thanks to @javiereguiluz for the agility on fixing it.
