### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'jquery')

### ISSUE THREAD

**Issue by dimanche-matin** [symfony/symfony-docs#19380]
This error is present in console of some pages like https://symfony.com/components/Apache%20Pack or https://symfony.com/components/Scheduler. And the copy button on each of these ones (visible from bs lg breakpoint) doesn't work.

**Comment by javiereguiluz** [comment]
Thanks for reporting this error. We've just fixed it and deployed the changes to production. So, let's close this as fixed. Thanks.
