### ISSUE TITLE
[AssetMapper] JS dependency not found

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#19397]
In a Symfony app where I'm using Webpack Encore, I have this:

```js
import { format } from 'date-fns-tz';
# ...
```

I'm upgrading the app to AssetMapper. The experience is pretty smooth so far and most things are working. But, when I try to add that JS dependency, I'm seeing this error:

```console
$ php bin/console importmap:require date-fns-tz

In JsDelivrEsmResolver.php line 123:

  Error 404 requiring packages from jsDelivr for "date-fns/format/index.js", "date-fns/_lib/toInteger/index.js", "date-fns/_lib/getTimezoneOffsetIn
  Milliseconds/index.js", "date-fns/_lib/cloneObject/index.js". Check your package names. Response: Couldn't find the requested file.


In CommonResponseTrait.php line 170:

  HTTP/2 404  returned for "https://cdn.jsdelivr.net/npm/date-fns@3.1.0/format/index.js/+esm".
```

I also tried this, but no luck either:

```console
$ php bin/console importmap:require date-fns-tz/src/format

In JsDelivrEsmResolver.php line 123:

  Error 404 requiring packages from jsDelivr for "date-fns-tz/src/format". Check your package names. Response: Couldn't find the requested file.


In CommonResponseTrait.php line 170:

  HTTP/2 404  returned for "https://cdn.jsdelivr.net/npm/date-fns-tz@2.0.0/src/format/+esm".
```

I have two questions:

(1) How to solve this issue? _(this is more for support, sorry 🙏 )_

(2) Should we add a new entry in the AssetMapper FAQ (https://symfony.com/doc/current/frontend/asset_mapper.html#frequently-asked-questions) to explain what to do when some dependency doesn't exist?

Thanks!

**Comment by smnandre** [comment]
1) I think this may be related to this : https://github.com/marnusw/date-fns-tz/issues/260#issuecomment-1875733321

**Comment by javiereguiluz** [comment]
Let's close this one as "won't fix".

At the end, I removed `date-fns` and replaced it with just a few lines of plain JS code. I've updated more apps to AssetMapper since I opened this issue ... and I didn't see any issue like this again. So, let's close and wait to see if we receive more feedback. Thanks!
