### ISSUE TITLE
[Config] Allow custom meta location in `ResourceCheckerConfigCache`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19496]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52043
| PR author(s) | @ruudk
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alamirault** [comment]
Only `ConfigCache` is documented in `components/config/caching.rst`

However `metaFile` was not added to`ConfigCache` construct (which extends `ResourceCheckerConfigCache)`, should we update this class in symfony source code ?

**Comment by alamirault** [comment]
I created https://github.com/symfony/symfony/pull/53868 to also allow to configure meta file in `ConfigCache`
