### ISSUE TITLE
Doctrine Configuration Reference (DoctrineBundle) invalid XML namespace and XSD schema links

### ISSUE THREAD

**Issue by Perf** [symfony/symfony-docs#19519]
In the beginning of Doctrine Configuration Reference documentation page there is a section:

> When using XML, you must use the http://symfony.com/schema/dic/doctrine namespace and the related XSD schema is available at: https://symfony.com/schema/dic/doctrine/doctrine-1.0.xsd

If you will try to open these links, you will get "Page not found".

Docs page: https://symfony.com/doc/6.4/reference/configuration/doctrine.html

Please update the docs with the valid links.

**Comment by dkarlovi** [comment]
Duplicate #18275

**Comment by xabbuh** [comment]
closing in favour of #18275
