### ISSUE TITLE
Sentence repeated in security documentation.

### ISSUE THREAD

**Issue by Globostofo** [symfony/symfony-docs#19544]
Hi :^)

I found a sentence repeated twice in the documentation, a few lines apart on the security page.

https://github.com/symfony/symfony-docs/blob/2ae2c17dbc55d9875551168ffe2e9bf44aabe2e1/security.rst#L612-L613

https://github.com/symfony/symfony-docs/blob/2ae2c17dbc55d9875551168ffe2e9bf44aabe2e1/security.rst#L628-L629

I was wondering if it wouldn't be better to remove one of them.

Thanks in advance for your feedback :)

**Comment by alexandre-daubois** [comment]
Good catch, I think it can be removed 🙂
