### ISSUE TITLE
Wrong PHP documentation for Workflow

### ISSUE THREAD

**Issue by AurelienPillevesse** [symfony/symfony-docs#19559]
I installed `symfony/workflow` on a Symfony 7.0 project and I wanted to implement the PHP configuration which is available here : https://symfony.com/doc/current/workflow.html#creating-a-workflow.

But it didn't work at all. `FrameworkConfig` seems not to exist anymore, at least not at the place where it's written in the example.

**Comment by xabbuh** [comment]
Did you get an error? The class is generated inside the cache directory.

**Comment by javiereguiluz** [comment]
Let's close this because probably this fixed somehow.

Otherwise, please provide more details about the error and we'll reopen this. Thanks!
