### ISSUE TITLE
Website: "Edit" link not working in "5.x" docs

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#19563]
The "Edit this page" link on https://symfony.com/doc/5.x/security.html leads to https://github.com/symfony/symfony-docs/edit/5.x/security.rst which doesn't exist.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. We've fixed it and now, `5.x` edit links correctly redirect to edit `5.4` docs (same for all `.x` versions, that are now redirected to `.4`).
