### ISSUE TITLE
Improve search on symfony.com/doc

### ISSUE THREAD

**Issue by ghost** [symfony/symfony-docs#19595]
I wonder if we can improve the docs global search. It looks like it doesn't work in some cases. Let's say I want to search for `it will then be sent to the`. It's not found. 

![image](https://github.com/symfony/symfony-docs/assets/25783196/b8188ed4-041e-4976-b756-ba1cfc2f6271)

With some other phrase it works but it looks like random.

Another thing I see is that even though it finds a desired result, it does not bold all the words what is not intuitive. Example:

![image](https://github.com/symfony/symfony-docs/assets/25783196/1cb23f67-a38b-4cd7-be72-6eef99691aca)

P.S. Could you tell me if this search works on reStructured files or some outputed, final files. If the former then I wonder how it handless all this keywords and keysigns like `::`, code samples etc.

**Comment by javiereguiluz** [comment]
The search engine is implemented with Meilisearch (see https://symfony.com/blog/migrating-symfony-com-search-engine-to-meilisearch). If you want to find an exact match, wrap it with quotes, like in Google --> `"it will then be sent to the"`

**Comment by ghost** [comment]
> The search engine is implemented with Meilisearch (see https://symfony.com/blog/migrating-symfony-com-search-engine-to-meilisearch). If you want to find an exact match, wrap it with quotes, like in Google --> `"it will then be sent to the"`

Thank you. I can see the information that the search is implemented by Meilisearch is shown when the search results are presented, at the bottom. Do you think it would be better DX if we added a link (e.g. hidden under some kind of :information_source: icon) that would lead to specific Meilisearch's docs page where query language is explained?


> like in Google

:smile: Good to know after two decades of using Google.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix". It doesn't feel OK to add "usage instructions" to the search engine to explain features like literal search with `"` quotes, excluding terms with `-`, etc.

About the bold words, that's something given to us by Meilisearch, so we don't have control about that part. Sorry!
