### ISSUE TITLE
[AssetMapper] Deprecate unused method `splitPackageNameAndFilePath`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19624]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54125
| PR author(s) | @smnandre
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by smnandre** [comment]
I'm not sure this will require any doc, as the method was never used if i'm not mistaken :)

**Comment by javiereguiluz** [comment]
You are right Simon. Closing as "fixed" because this method wasn't mentioned in the docs. Thanks.
