### ISSUE TITLE
[AssetMapper] Recommend `Cache-Control` instead of `Expires` HTTP header?

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#19626]
@weaverryan Is there a specific reason why you're recommending to set `Expires` and not `Cache-Control` at https://symfony.com/doc/current/frontend/asset_mapper.html#optimizing-performance ?

According to https://stackoverflow.com/q/5799906/1668200 `Cache-Control` is something like the "successor" of `Expires`. And Lighthouse is only mentioning `Cache-Control`: https://developer.chrome.com/docs/lighthouse/performance/uses-long-cache-ttl?utm_source=lighthouse&utm_medium=devtools#how_to_cache_static_resources_using_http_caching

So what do you think about changing the recommendation to `Cache-Control`?

**Comment by smnandre** [comment]
I think we should use both. The word `expires` is really self)explanatory for newcomers (in a functional way i mean), but you're absolutely right, when we speak implementation / RFC, we should do it using "Cache-Control", as it superseeds Expires entirely !

**Comment by ThomasLandauer** [comment]
OK, see https://github.com/symfony/symfony-docs/pull/19628 - I squeezed the word "expiry" in :-)
