### ISSUE TITLE
[Configurating a web server] Missing the section adding-rewrite-rules-for-apache (6.3+)

### ISSUE THREAD

**Issue by ampmonteiro** [symfony/symfony-docs#19649]
Hi,

since version 6.2 the section  ` adding-rewrite-rules-for-apache` is missing, Why ?

version 6.2

![image](https://github.com/symfony/symfony-docs/assets/31895754/407a42c6-c274-4c6b-b6b3-69641a169433)

version 6.3, this section do not shows anymore. 

This sections showed  if not using PHP-FPM, on for small website or for simple web dev env on Apache using `mod_php/PHP-CGI`

how to generate or gives a htaccess template by running: `composer require symfony/apache-pack`.

Please put it back.

Thank you.

**Comment by javiereguiluz** [comment]
This was removed in #17597, as part of some effort to update and modernize the Web Server Configuration article. Maybe @wouterj can confirm if the "rewrite rules for Apache" section was removed on purpose or maybe it was an oversight and we could re-add it. Thanks!

**Comment by wouterj** [comment]
If I recall correctly, we removed the sections that were either using an old version of Apache or talking about using a `.htaccess` file in the webroot (i.e. the apache-pack). This is a bad practice that we don't want to advocate by documenting it.

However, I see we now do not show the rewrite rules anywhere. In the nginx config example, the rewrite is already part of the main example. I think we should also include the relevant rewrite rules in the main Apache example.

It's been years since I last used Apache, are you maybe willing to make a PR with this change @ampmonteiro?

**Comment by ampmonteiro** [comment]
Hi @wouterj  and @javiereguiluz ,

> If I recall correctly, we removed the sections that were either using an old version of Apache or talking about using a `.htaccess` file in the webroot (i.e. the apache-pack). This is a bad practice that we don't want to advocate by documenting it.
> 

On old version like  Apache 2.2, i agree. However, on `.htaccess`, not so much, because if you are using a sharing host service with Apache web server then your only choice is to have a `.htaccess`  file for routing work as it should.

Another scenario is for example, for those using OS like  `Windows` or `MacOS` ,  to quick start using PHP installing tools like `WAMP`, `MAMP` or `XAMP` , which they use apache, just copy the `.htaccess` file which is a simple and fast way to setup frameworks like `Symfony`.

Last, in my case, which i  use Linux Desktop OS base, it is easy, at least for me, just create and build a docker single container based on Apache with mod_php with just php ext i need and composer installed (you can see [here](https://github.com/ampmonteiro/sf6-build-your-first-app) last time create a simple symfony project).

> However, I see we now do not show the rewrite rules anywhere. In the nginx config example, the rewrite is already part of the main example. I think we should also include the relevant rewrite rules in the main Apache example.
> 

> It's been years since I last used Apache, are you maybe willing to make a PR with this change @ampmonteiro?

About PR, no need for me to do it, because the sections about apache that exist on version 6.2, except related to apache 2.2, are just fine and more than enough, so my suggestion, just use what already exist on version 6.2.

Of course you improve some, by doing what you also suggest:
Like i said there is situations / case, that the dev dont have access to the file where you should create the virtualhost and copy there the lines that are on .htacess file over the virtualhost config. Or for the dev, the .htacess file is enough.

But please mention and keep the composer command  `composer require symfony/apache-pack`.

Another suggestion is, make available the `.htaccess` file when install the framework, in public folder, like laravel framework do.

Thank you.

**Comment by javiereguiluz** [comment]
Closing as fixed in #20016
