### ISSUE TITLE
Ampersand is wrongly handled in the double-shift search bar

### ISSUE THREAD

**Issue by alexandre-daubois** [symfony/symfony-docs#19665]
On the website, it seems the ampersand has some bad times being handled in the title of a result:

<img width="650" alt="Capture d’écran 2024-03-12 à 10 08 37" src="https://github.com/symfony/symfony-docs/assets/2144837/73f1112b-4f61-49cb-9cc9-45c06df6238f">

I think it is some backend concern but in case it is important, tested on Safari with macOS 14.4.

**Comment by javiereguiluz** [comment]
Thanks for reporting this Alex! I'm happy to say that this is now fixed. Cheers!
