### ISSUE TITLE
[Serializer] Add context for `CamelCaseToSnakeCaseNameConverter`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19683]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#53898
| PR author(s) | @AurelienPillevesse
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
This should be put on hold, because the PR introduces a breaking change. The implementation is likely to change from what it is now.

**Comment by xabbuh** [comment]
The BC break was fixed in symfony/symfony#54531.
