### ISSUE TITLE
[HttpFoundation] Add temporary URI signed

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19684]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#51502
| PR author(s) | @BaptisteContreras
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by BaptisteContreras** [comment]
I'll do it asap 😃

**Comment by alexandre-daubois** [comment]
Hello @BaptisteContreras, do you think you'll find time to create the PR? No worries if you can't, we'll take care of it 🙂

**Comment by BaptisteContreras** [comment]
Hi @alexandre-daubois, I'm planning to work on it this WE 🙂
