### ISSUE TITLE
[Conventions] List of code values: remove comma ?

### ISSUE THREAD

**Issue by smnandre** [symfony/symfony-docs#19686]
When listing code values, I believe omitting commas could significantly enhance readability. 

Although it might be slightly less correct from a syntactical standpoint, I think the trade-off is worthwhile.

Example there: https://symfony.com/doc/current/reference/formats/yaml.html#booleans 

| with | without |
| - | - |
| <img width="450" alt="with" src="https://github.com/symfony/symfony-docs/assets/1359581/90030ab8-6b25-4905-b475-588dd1e6a220"> | <img width="450" alt="without" src="https://github.com/symfony/symfony-docs/assets/1359581/30d80522-26b8-4d03-9afa-a78ebe182389"> | 

WDYT ?

**Comment by javiereguiluz** [comment]
Yes, I agree. A single whitespace to separate chars looks better than a comma.

But, let's wait for more opinions before doing any change. Thanks.

**Comment by xabbuh** [comment]
works for me 👍

**Comment by OskarStark** [comment]
Yes 🙌
