### ISSUE TITLE
[WebProfilerBundle] Allow to search inside profiler tables

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19681]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#53885
| PR author(s) | @javiereguiluz
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Let's close this one because it's a UI feature that can be self-discovered by users without much effort. Thanks.
