### ISSUE TITLE
[ExpressionLanguage] Null-Coalescing operator supporting non-existent data

### ISSUE THREAD

**Issue by adamkiss** [symfony/symfony-docs#19695]
Potential doc issue for https://github.com/symfony/symfony/issues/54359

Docs suggest that [Expression Language supports null-coalescing operator](https://symfony.com/doc/current/components/expression_language.html#null-coalescing-operator) for variables not passed in:

```php
$data = ['exists' => 1];
$language->evaluate('doesnt_exist ?? 2', $data);
```

But it was suggested to me in the linked issue that the code doesn't seem to actually support that, and that null coalescing operator also isn't mentioned in https://symfony.com/doc/current/reference/formats/expression_language.html#supported-operators

**Comment by stof** [comment]
To be exact, the `if it exists` part is true when accessing potentially-missing array keys. But accessing a non-existent variable won't be allowed even with this operator (side note: this is also the way this operator works in JS, where `a ?? 'fallback'` will still throw a ReferenceError if the variable `a` does not exist)

**Comment by adamkiss** [comment]
@stof It specifically calls out "like PHP null-coalescing", where `$never_defined ?? 'fallback'` is perfectly valid thing.

**Comment by stof** [comment]
Yeah, this part should be updated. I'm not saying that the doc is correct right now. But the part saying `if it exists` must not be removed entirely either.
