### ISSUE TITLE
[Bug] Symfony Doc Display Issue on Desktop

### ISSUE THREAD

**Issue by David-Moisan** [symfony/symfony-docs#19702]
Hi 👋, 

I noticed a display problem on all the documentation on the Symfony website.
I have a 1920 x 1080 desktop screen and the element having the class "doc-sidebar-sticky" shifts all the style. I don't have the problem on the phone.

Here is a screenshot : 

![Screenshot 2024-03-23 at 15-35-16 ChoiceType Field (select drop-downs radio buttons   checkboxes) (Symfony Docs)](https://github.com/symfony/symfony-docs/assets/62502246/0c40fde9-37f4-43e3-85a7-527933b316bd)

Have a nice week end

**Comment by c33s** [comment]
just tested it with some browsers (some of them are a little old, i have them for verifiing webpage compatibility)
works on:
- firefox 124.0
- iceraven 2.16.1

broken on:
- firefox 115.9.1 (default firefox installed on debian 12 current stable release; last verstion working on win7)
- tor browser (firefox esr 115.9.1)
- waterfox classic 2022.11
- chromium 109 (last chrome working on win7)

**Comment by David-Moisan** [comment]
Sorry, I didn't specify but indeed I have Firefox 115.9.1

**Comment by javiereguiluz** [comment]
Sadly I don't have access to those old browsers. Can you please debug this error and tell me if it can be fixed easily by changing some styles? Thanks!

**Comment by c33s** [comment]
the browser console reveals no  js/css error to me but a 404 for `https://symfony.com/assets/styles/code.css`

![image](https://github.com/symfony/symfony-docs/assets/649209/57a05733-6296-499b-92e4-787338c9ef6d)

is the source code of symfony.com public? wouldn't it be easier to look there what changed with the last release? my guess would be some polyfill was dropped or some browsers where removed from the build targets.

as firefox esr (esr means extended support release, which is firefox 115) is bundled with debian stable (12 bookwork) which is supported until june 2026 and has long term support until june 2028 it could be a good idea to keep ff 115 in the compatibility grid. also chrome 109 and ff 115 are the last versions which run on win7.

download links for "older" browsers:
- https://www.mozilla.org/en-US/firefox/enterprise/#download
- https://www.torproject.org/download/
- https://classic.waterfox.net/

as workaround it is possible to resize the browser smaller to trigger the breakpoint where the burger menu appears. then the page works.

![image](https://github.com/symfony/symfony-docs/assets/649209/044ebbfc-7853-4b00-a2a3-056901c2470b)

**Comment by stollr** [comment]
Same problem here, with Firefox ESR on Debian. I have looked into the CSS and found the reason for the issue. In `https://symfony.com/assets/styles/doc-c540be15984e569e9ff6aa6cb7967f95.css` nested CSS is used:

```css
.content-sidebar-wrapper.content-sidebar-wrapper-left {
  .content { order: 1; }
  .sidebar { order: -1; }
}
```

CSS nesting is only supported in Firefox since [v117](https://caniuse.com/css-nesting). As this rule is ignored, the navigation and the content is displayed interchanged.

It would be nice if the use of nested CSS could be reverted for some time.

**Comment by javiereguiluz** [comment]
@stollr thanks a lot! That's the bug. We definitely don't want to use CSS nesting yet because support is not universal. I'll fix it very soon.

**Comment by javiereguiluz** [comment]
We've just deployed some changes to symfony.com, so hopefully this error is fixed now. Thanks.

**Comment by stollr** [comment]
Yes, looks good again. Thank you for your fast fix ;-)

**Comment by David-Moisan** [comment]
Thank you :)
