### ISSUE TITLE
[Validator] Using TranslateableMessage with ExecutionContext::buildViolation

### ISSUE THREAD

**Issue by SebTM** [symfony/symfony-docs#19704]
Regarding: https://symfony.com/doc/current/validation/translations.html
From: https://github.com/symfony/symfony-docs/pull/19054#issuecomment-1992270698

From my experience in a project where I tried to use it like that it failed as the type declaration only allows "string" (https://github.com/symfony/validator/blob/6.4/Context/ExecutionContext.php#L157C21-L157C35) or so I miss something here? 

Even TranslateableMessage implements "__toString" does not help as it would only return the template-message without resolving/translating it. (https://github.com/symfony/translation/blob/6.4/TranslatableMessage.php#L35)

I checked it for the version I used (6.4) but it seems to be the same for 7.X - if I missed something maybe we can clarify the example 🙏🏻

**Comment by alamirault** [comment]
@alexandre-daubois do you think PR should be reverted ? or adjusted

Not sure this example works

**Comment by alexandre-daubois** [comment]
Actually I think the code should be updated 🙂 Let's see where it goes

- https://github.com/symfony/symfony/pull/54487

**Comment by javiereguiluz** [comment]
Symfony code was updated so this feature now works as explained in the docs. Thanks!
