### ISSUE TITLE
[Uid] Add a note on the use of entity primary keys

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony-docs#19705]
It would be interesting to add a note on the use U*id values for primary key in an entity. 
This use is bad practice.
What do you think ?

**Comment by javiereguiluz** [comment]
Can you please share some resources where they explain that this is a bad practice and the reasons for it?

Also, let's keep in mind that we have lots of different UIDs, so maybe some are bad for PKs but not others. Thanks!

**Comment by seb-jean** [comment]
For my part, I use ULIDs.

Yes, there is the comment https://github.com/symfony/symfony/issues/41544#issuecomment-859662356.

What do you think ?

**Comment by javiereguiluz** [comment]
I'm afraid that's not enough. We'd need good resources that provide reasoned arguments to prove that this is a bad practice. E.g. if it's bad for performance reasons, show a good benchmark, etc. Thanks.

**Comment by seb-jean** [comment]
I don't have any resources, benchmarks, etc.

**Comment by gnito-org** [comment]
If you use ULID, then you can also use UUID V7. 

Like ULID, UUID V7 also provides monotonically increasing values that are lexicographically sortable.

I've been using V7 as primary keys without any issues.

**Comment by javiereguiluz** [comment]
I search about this and read a lot of different posts. There seems to be a consensus on the drawbacks, so I propose to add that in #19783.
