### ISSUE TITLE
The file "/config" does not exist.  at FileLocator.php line 46 

### ISSUE THREAD

**Issue by featuriz** [symfony/symfony-docs#19719]
I'm trying **Building your own Framework with the MicroKernelTrait** from: https://symfony.com/doc/current/configuration/micro_kernel_trait.html

```sh
composer require symfony/config symfony/http-kernel \
  symfony/http-foundation symfony/routing \
  symfony/dependency-injection symfony/framework-bundle
```
This run success and created a index.php as per doc and copy pasted the code (<?php ... )

Then `symfony server:start` => server starts with no problem. But when i go to http://localhost:8000/random/10 .

![Screenshot from 2024-03-28 10-13-39](https://github.com/symfony/symfony-docs/assets/10089154/927fb3cb-127c-4e68-9aea-3f0f8144be35)

**Comment by featuriz** [comment]
I completed the tutorial in this page. and came back and recreated this file index.php also I deleted public,src,templates. Then this works fine.

* **/config** folder is must.

Because in `use MicroKernelTrait;` file `/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php` there is hardcode for /config folder.
`$configDir = $this->getConfigDir();`

**Comment by OskarStark** [comment]
That sounds like something for you @xabbuh 😄

**Comment by OskarStark** [comment]
I tried and you are right, after creating an empty config/ folder it works

**Comment by yceruto** [comment]
FYI, we are making the `config/` dir optional for 7.2 https://github.com/symfony/symfony/pull/57408

**Comment by javiereguiluz** [comment]
Thanks Yonel! I've added a note about this in #19970. Hopefully, we'll need to remove that note in 7.2 branch.
