### ISSUE TITLE
[Twig Reference] Filter `humanize` add exemple to capitalize behavior

### ISSUE THREAD

**Issue by RonanSauvage** [symfony/symfony-docs#19758]
Actually, the doc presents the behavior of replacing underscores with spaces and evoked capitalization of the string. But in the example just before, capitalization is not represented. 

So two options seems possible to me : 

- keep current text and just add other exemple for capitalization behavior : 

> Makes a technical name human readable (i.e. replaces underscores by spaces or transforms camelCase text like `helloWorld` to `hello world` and then capitalizes the string **like `helloWorld` to `Hello World`**).

- group the two behaviors into a single example : 

> Makes a technical name human readable (i.e. replaces underscores by spaces or transforms camelCase text and then capitalizes the string **like `helloWorld` to `Hello World`**).

I'm ready to create the corresponding pull request, I would just like to get advice on the best solution from someone familiar with maintaining the doc.

Personally I find the second solution better.

**Comment by alexandre-daubois** [comment]
Second solution seems the best/clearest to me 🙂

**Comment by javiereguiluz** [comment]
@RonanSauvage thanks for reporting this. I agree that this is a bit confusing.

I also like the second proposal ... but I also think we should expand this a bit more with some real examples to better understand what this does. See #19774

**Comment by RonanSauvage** [comment]
Hello @javiereguiluz 

Thank you for your feedback and for the correction. In fact, the result is much better. I was shy about my RA.
It's a great experience for my next PR proposal.

Thanks again
