### ISSUE TITLE
Cast env vars to null or bool when referencing them using `#[Autowire(e…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19785]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#53971
| PR author(s) | @ruudk
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
not sure if there is anything we need to document here

**Comment by javiereguiluz** [comment]
I agree. Let's close this one because the new behavior is common sense and what people would expect. In the docs we only briefly mention `#[Autowire(env: 'SOME_ENV_VAR')]` and never explain issues with boolean or nullable arguments.

Thanks!
