### ISSUE TITLE
[Mailer] [Resend] Add Resend webhook signature verification

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19799]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54525
| PR author(s) | @welcoMattic
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
Is there anything to document here? This rather looks like an internal change to me.

**Comment by welcoMattic** [comment]
~It looks like just adding a line in this [table](https://symfony.com/doc/current/webhook.html#usage-in-combination-with-the-mailer-component)~ 

My bad, I looked at 7.0 doc version. In 7.x it's already there, so no need to update anything. We can close.

To be explicit: Resend webhooks were handled in the [first PR](https://github.com/symfony/symfony/pull/53554), but without signature verification.
