### ISSUE TITLE
[ExpressionLanguage] Document precedence

### ISSUE THREAD

**Issue by homersimpsons** [symfony/symfony-docs#19803]
## Current status

The page https://symfony.com/doc/current/reference/formats/expression_language.html#supported-operators does not document operators precedence.

## Objective

Add documentation about operators precedence.

## Why?

Today I wanted to check the precedence of some operator in order to update a code, I had an expression that could translate to the following ambiguity:
```php
var_dump(! null === false); // => ((!null) === false) => false
var_dump(! (null === false)); // => true
```

We can find the precedence in https://github.com/symfony/expression-language/blob/b8ec919a6d3d47fc4e7845c256d164413207bf73/Parser.php#L24

I think that this information should be accessible in the doc directly, but I understand that it won't benefit a lot of users so I'm wondering how it should be presented. Maybe just a collapsible array at the end, or when the precedence is mentioned in:

> You must use parentheses because the unary operator not has precedence over the binary operator matches.

**Comment by 94noni** [comment]
A note block could be added and document this internal behavior i think yes 👍🏻

**Comment by OskarStark** [comment]
I really like this note and we should merge it. However, what about a debug command? We have the same for listener priorities

**Comment by homersimpsons** [comment]
> However, what about a debug command?

I'm not sure to understand, there is no command for symfony's expression language, right?

**Comment by OskarStark** [comment]
Yes, I would propose to create one

**Comment by homersimpsons** [comment]
What would be the purpose of such command? How do you see its interface?

**Comment by OskarStark** [comment]
I would output the list from the docs PR, if we can get the info programmatically

**Comment by homersimpsons** [comment]
> I would output the list from the docs PR, if we can get the info programmatically

Yes we can definitely get it programatically rather easily (minus some formating / arranging).

The repo does not have a dependency on the console component, I'm not exactly sure how to approach this. Another command I can think of would be an easy "debug" command where someone could provide an expression (and possibly variables) and get the result.

**Comment by javiereguiluz** [comment]
Given that the list of operators is very rarely updated, I'd just handle this manually.
