### ISSUE TITLE
[HttpKernel] Introduce `#[MapUploadedFile]` controller argument attribu…

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#19802]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49978
| PR author(s) | @renedelima
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by rcsofttech85** [comment]
@chalasr  could you please confirm this issue..I noticed a small bug.

https://github.com/symfony/symfony/issues/54871
