### ISSUE TITLE
[Serializer] Add `XmlEncoder::CDATA_WRAPPING_PATTERN` context option

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19851]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54663
| PR author(s) | @alexpozzi
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexpozzi** [comment]
Sure, I'll try to take some time this week to work on it.

**Comment by alexpozzi** [comment]
PR created https://github.com/symfony/symfony-docs/pull/19883
