### ISSUE TITLE
[DoctrineBundle] Use a full version number in examples with `serverVersion`

### ISSUE THREAD

**Issue by nicwortel** [symfony/symfony-docs#19876]
Doctrine DBAL 3.6.0 [deprecated incomplete version numbers](https://github.com/doctrine/dbal/pull/5844) for the `serverVersion` value (for example `8` or `8.0` for MySQL):

![afbeelding](https://github.com/symfony/symfony-docs/assets/1055691/715bbac4-63b2-4790-8769-eba23c210a67)

While the deprecation warnings are no longer there in DBAL 4, the [DBAL documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/4.0/reference/configuration.html#automatic-platform-version-detection) (updated in https://github.com/doctrine/dbal/pull/5971) states that `serverVersion` should contain a full version number:

> Please specify the full server version as the database server would report it. This is especially important for MySQL and MariaDB where the full version string is taken into account when determining the platform.

This is also supported by the [UPGRADE.md](https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-disallowed-partial-version-numbers-in-serverversion):

> The `serverVersion` connection parameter must consist of 3 numbers:
> 
> ```diff
> -'serverVersion' => '8.0'
> +'serverVersion' => '8.0.31'
> ```

However, most of the Symfony documentation I found still contains examples which configure the `DATABASE_URL` like this:

```
DATABASE_URL="mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=5.7"
```

...which seems to conflict with the Doctrine DBAL documentation.

For example:

- https://symfony.com/doc/current/doctrine.html#configuring-the-database
- https://symfony.com/doc/current/doctrine/dbal.html
- https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration

Should we update these examples to contain a full version number? It seems like the [more recent Flex recipes for DoctrineBundle](https://github.com/symfony/recipes/blob/main/doctrine/doctrine-bundle/2.8/manifest.json#L14) are already using full version numbers, compared to the older recipes.
I'm happy to send a PR, but I wanted to discuss this in an issue before submitting a PR.

This could be related to the following issues / PRs:

- https://github.com/symfony/symfony-docs/issues/19138
- https://github.com/symfony/symfony-docs/issues/18297

**Comment by alamirault** [comment]
Thank you for the explanation.

PR is welcome to avoid deprecation or exception for newcomers
