### ISSUE TITLE
Split the config/routes.yaml file into multiple files

### ISSUE THREAD

**Issue by ghost** [symfony/symfony-docs#19884]
Hey there,

I'm looking to break down my [config/routes.yaml](https://github.com/chesslablab/website/blob/main/config/routes.yaml) file into multiple files but found no documentation about it. I'd want to do something similar as described for previous versions of Symfony:

- [Symfony2: Splitting routing.yml in multiple files](https://stackoverflow.com/questions/16355385/symfony2-splitting-routing-yml-in-multiple-files)

More specifically, I'd want to create two .yaml files: 

- pages.yaml
- blog.yaml 

🙏 Thank you for the help.

**Comment by 94noni** [comment]
it should work similarly 

can you share code that dont work for you with the symfony version you are using ?

**Comment by ghost** [comment]
At the moment there's no code in place, just this [config/routes.yaml](https://github.com/chesslablab/website/blob/main/config/routes.yaml) file with two sample blog entries: `blog_hello_world` and `blog_getting_started`. 

See https://github.com/chesslablab/website/issues/259

**Comment by ghost** [comment]
Let me keep you posted that this issue has just been opened: 

- https://github.com/chesslablab/website/issues/303

Happy coding!
