### ISSUE TITLE
[broken link] Slack link no longer active

### ISSUE THREAD

**Issue by RyanFarrah67** [symfony/symfony-docs#19885]
It seems that the Slack link/channel is no longer active or has changed emplacement without being updated on the Symfony website.

Here's a non-exhaustive list where you can find it broken : 

* https://symfony.com/community
* https://symfony.com/doc/current/contributing/code/bugs.html
* https://symfony.com/support

**Comment by RyanFarrah67** [comment]
I found this old discussion https://github.com/symfony/symfony/discussions/48732 about an user complaining about the same thing but this was revolved.

**Comment by xabbuh** [comment]
@javiereguiluz will exchange the Slack invite link soon and things will then work again.

**Comment by javiereguiluz** [comment]
Thanks for the ping. I've just updated the invite link ... but right now Slack shows an error page saying that "something went wrong" but gives no other explanation. Hopefully this is a temporary issue on Slack side.

**Comment by javiereguiluz** [comment]
The temporary issue was solved and https://symfony.com/slack works again. Closing as fixed. Thanks.

**Comment by nito-web** [comment]
Is slack putting an expire on this links? It is broken again.

<img width="667" alt="image" src="https://github.com/user-attachments/assets/8b1f14ec-6186-4280-8ed9-6c5166a0bc18" />

Same for the link in @javiereguiluz last comment, this link gives me the same result.

**Comment by nito-web** [comment]
Never mind, it seems to work again. Last time it took a day, this time it took a day. When you run into the same issue, just wait a day 😆
