### ISSUE TITLE
[Validator] Make `PasswordStrengthValidator::estimateStrength()` public

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#19903]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54881
| PR author(s) | @yalit
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by derrabus** [comment]
See my comment https://github.com/symfony/symfony/pull/54881#issuecomment-2114455724: We should document how we can leverage `AutowireCallable` to gain access to the password strength computation in arbitrary services.

**Comment by yalit** [comment]
For the documentation, do we update the validator documentation? I've not seen a dedicated PasswordStrength constraint documentation 

And for the autowiring so we update the generic container documentation or do we add it linked to the constraint/validator doc?

**Comment by yalit** [comment]
I was looking on my phone, now that's it's cloned, I found the PasswordStrength doc file.

As there is no dedicated documentation for the Validator itself and only for the constraint, I would proposeto add a section "Learn more" at the end of the PasswordStrength constraint doc page that would link to a new page:
- How to get or override the estimated strength computation

The new page would simply indicate :
1. that the method estimateStrength in the Validator is now public (+ providing a link to the lines in the code)
2. if that method is not aligned with the needs, there is a way to udpate the estimation method for the Validator using a dedicated closure as argument of the Validator and refer to the following page of the container doc : https://symfony.com/doc/current/service_container/service_closures.html

Would that be a good fit? I'm willing to take a shot at this but it will be my first time updating the documentation, so I might need some guidance (reading the contributing guidelines is ongoing).

**Comment by derrabus** [comment]
Sounds good to me. Feel free to submit a first draft and we iterate from there.

**Comment by javiereguiluz** [comment]
Closing as fixed in #19910.
