### ISSUE TITLE
[Notifier] [Bluesky] Allow to attach image

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19908]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54756
| PR author(s) | @jdecool
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by OskarStark** [comment]
It's documented via README
