### ISSUE TITLE
[Notifier] [Slack] Add button block element and `emoji`/`verbatim` opti…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19929]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54737
| PR author(s) | @cvergne
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by cvergne** [comment]
Hi, I was about to do it following this issue, but I've noticed there is no documentation about each notifier integration.  
[Each integration](https://symfony.com/doc/current/notifier.html#chat-channel) refers to its [README](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Notifier/Bridge/Slack/README.md) in the documentation.

So maybe I should have updated the README to enhance examples with my changes ? :/
Tell me what's the best thing to do and I'll follow :)

Thanks !

**Comment by xabbuh** [comment]
@cvergne Adding something to the bridge's example is indeed the best idea. :)
