### ISSUE TITLE
[Notifier] Add Primotexto bridge

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19927]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54747
| PR author(s) | @Samael tomas
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
the related PR is #19835

**Comment by javiereguiluz** [comment]
Closing as fixed in #19835.
