### ISSUE TITLE
[TypeInfo] Proxies methods to non-nullable and fail gracefully

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19930]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54679
| PR author(s) | @mtarld
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
I don't think we need to document this as it's purely internal.

**Comment by OskarStark** [comment]
Argh 😄
