### ISSUE TITLE
[Uid] Make `AbstractUid` implement `Ds\Hashable` if available

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19948]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57313
| PR author(s) | @jahudka
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
IMO this is an implementation detail that we do not need to document

@symfony/docs What do you think?

**Comment by wouterj** [comment]
Agreed, this is a classic "it just works" feature that we don't need to document explicitly.
