### ISSUE TITLE
[UX] Make symfony.com/ux redirect to current version ?

### ISSUE THREAD

**Issue by smnandre** [symfony/symfony-docs#19981]
I just realized the URL https://symfony.com/ux redirects to https://symfony.com/doc/5.x/frontend/ux.html

Could you make it redirect to https://symfony.com/doc/current/frontend.html ?  

(this URL is not _used_  anymore i believe, but is present on many doc pages, READMEs, blog posts..)

**Comment by javiereguiluz** [comment]
Thanks Simon! I just updated the URL of the redirection and deployed the changes. Cheers!

**Comment by smnandre** [comment]
Thank you @javiereguiluz \o/
