### ISSUE TITLE
"/components" returns 500 response status code

### ISSUE THREAD

**Issue by andrew-demb** [symfony/symfony-docs#19982]
https://symfony.com/components returns a 500 response status code.

![image](https://github.com/symfony/symfony-docs/assets/12499813/6dd16406-71cf-47f0-835b-69088c6a0005)

This link is mentioned in PHP The Right Way site - https://phptherightway.com/#:~:text=Hoa%20Project-,Symfony,-Components

**Comment by javiereguiluz** [comment]
@andrew-demb thanks for reporting this error. We just fixed it and deployed the fix.
