### ISSUE TITLE
SVG images don't work on 5.X version

### ISSUE THREAD

**Issue by JakeFr** [symfony/symfony-docs#19999]
Images in SVG format are not displayed on version 5.x

The HTTP-Kernel diagram is missing
[https://symfony.com/doc/5.x/components/http_kernel.html](https://symfony.com/doc/5.x/components/http_kernel.html)
When I visit pages with complete version number it works fine
[https://symfony.com/doc/6.4/components/http_kernel.html](https://symfony.com/doc/6.4/components/http_kernel.html)

Same thing for the serializer doc
[https://symfony.com/doc/5.x/components/serializer.html](https://symfony.com/doc/5.x/components/serializer.html)

I check the code, SVG path are relative `<object data="../_images/components/http_kernel/http-workflow.svg"`
so it results in a 404 request, as `/5.x/` don't exist.

same things on other branches for older major versions 4.x ...

**Comment by javiereguiluz** [comment]
@JakeFr thanks for reporting this bug. We've just merged some fixes and deployed them, so the images are shown again in 5.x docs, e.g. https://symfony.com/doc/5.x/components/http_kernel.html
