### ISSUE TITLE
[Notifier] Add Sipgate bridge

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20023]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57627
| PR author(s) | @Lukas Kaltenbach, @sakul95
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by sakul95** [comment]
Sure thing, I created a pull request for the documentation under the notifier page: https://github.com/symfony/symfony-docs/pull/20018

How else can I help? :smiley:
