### ISSUE TITLE
[SecurityBundle] Link to the profile the token was (de)authenticated

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20037]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57692
| PR author(s) | @MatTheCat
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by MatTheCat** [comment]
Apart from a screenshot in https://symfony.com/doc/current/profiler.html#installation it does not seem like the WebProfiler content is documented?

**Comment by javiereguiluz** [comment]
You are right. Let's close this as "won't fix" because this nice feature will be discovered by folks using the profiler and it needs no explanation. Thanks.
