### ISSUE TITLE
[FrameworkBundle] Add `exit` option to `secrets:decrypt-to-local` comma…

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#20034]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57670
| PR author(s) | @dciprian-petrisor
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
~Not sure we need to document this.~ (should indeed be documented, I missed the new option)

**Comment by dciprian-petrisor** [comment]
Sure thing, I think I'll get to this in the next day or two

**Comment by javiereguiluz** [comment]
Closing as fixed in #20055.
