### ISSUE TITLE
[FrameworkBundle]  terminate with non-zero exit code when a secret coul…

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#20057]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57797
| PR author(s) | @xabbuh
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Closing as fixed in #20058.
