### ISSUE TITLE
[Cache] Add optional ClockInterface to ArrayAdapter

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony-docs#20069]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57836
| PR author(s) | @jasiolpn
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by jasiolpn** [comment]
Hello.
First of all thank you for quick response to my pr. It was unexpected  but very nice :slightly_smiling_face: 

I created pr with docs update in https://github.com/symfony/symfony-docs/pull/20070

**Comment by javiereguiluz** [comment]
Closing as fixed in #20070.
