### ISSUE TITLE
[Form] Deprecate VersionAwareTest trait

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#20075]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57839
| PR author(s) | @derrabus
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
I can't find any occurrence of this trait in the docs, so I'm closing this issue as not planned.

**Comment by derrabus** [comment]
Thanks for checking!
