### ISSUE TITLE
[Serializer] Normalizer Callback params confusion: $innerObject should be called $attributeValue and $outerObject should be just $object

### ISSUE THREAD

**Issue by mindaugasvcs** [symfony/symfony-docs#20080]
https://github.com/symfony/symfony-docs/blob/35e5b7dcb42234a8b9343e4a880e9b9cff73f710/components/serializer.rst?plain=1#L759

Normalizer Callback params confusion:
$innerObject should be called $attributeValue and $outerObject should be just $object.

**Comment by xabbuh** [comment]
PR welcome to improve the naming
