### ISSUE TITLE
The Emoji component should have its dedicated documentation

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#20114]
currently, the documentation for the Emoji component is a section in the documentation page of the string component: https://symfony.com/doc/current/string.html#working-with-emojis

This is quite confusing given that this component does not rely on `symfony/string` (its input is a PHP string) nor has shortcuts in `symfony/string` at all (except in the Slugger, but this has a separate dedicated section in the page).

This documentation should be moved to a dedicated page (that could then become the documentation link used on https://symfony.com/components/Emoji)

**Comment by smnandre** [comment]
When we created the component, I made a PR with such a page (before its content was moved/fusionned in String)

Nothing amazing, but It could probably be a good starting point.

**Comment by smnandre** [comment]
Update: found it https://github.com/symfony/symfony-docs/pull/19489

**Comment by javiereguiluz** [comment]
Closing as fixed in #20216.
