### ISSUE TITLE
[Security] Deprecate empty user identifier

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20125]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58007
| PR author(s) | @ajgarlag
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by xabbuh** [comment]
I don't think we need to document this.

**Comment by thibaut22200** [comment]
I don't think documentation is needed for this PR
