### ISSUE TITLE
[HttpClient] Add support for amphp/http-client v5

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20132]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#54179
| PR author(s) | @nicolas-grekas
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by nicolas-grekas** [comment]
I had a quick look, there's nothing to do.
