### ISSUE TITLE
[Scheduler] Add capability to skip missed periodic tasks, only the last…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20130]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58001
| PR author(s) | @eltharin
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by eltharin** [comment]
Sure! It's already done :)
https://github.com/symfony/symfony-docs/pull/20118

**Comment by javiereguiluz** [comment]
Closing as fixed in #20118.
