### ISSUE TITLE
[Cache] Ask for adding the fourth optional parameter of the RedisAdapter with explanations and examples 

### ISSUE THREAD

**Issue by lkolndeep** [symfony/symfony-docs#20146]
Hello folks,

I noticed that in the documentation of the RedisAdapter: [Redis Adapter Doc](https://symfony.com/doc/7.0/components/cache/adapters/redis_adapter.html), there is no mention of the fourth optional parameter of this adapter which is the marshaller.

It could be nice to add this in the RedisAdapter documentation with explanations and some examples too.

Thanks in advance,

Regards,

**Comment by alamirault** [comment]
@lkolndeep You'are right, do you want to give it a try ?

**Comment by lkolndeep** [comment]
@alamirault Hello, yes it could be nice! I will try to do it.

**Comment by javiereguiluz** [comment]
Closing as fixed in #20399.
