### ISSUE TITLE
[Validator] Add `$groups` and `$payload` to `Compound` constructor

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20152]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58062
| PR author(s) | @derrabus
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by thibaut22200** [comment]
Can be closed:

Already in reference/constraints/Compound.rst

```
l.105 to l.110
Options
-------

.. include:: /reference/constraints/_groups-option.rst.inc

.. include:: /reference/constraints/_payload-option.rst.inc
```

**Comment by derrabus** [comment]
Those are the options, not the constructor arguments. What's new is that those options can be set through names arguments. Maybe we should show on https://symfony.com/doc/current/reference/constraints/Compound.html a custom compound constraint used as an attribute with a validation group.
