### ISSUE TITLE
[Webhook] Pass original request to `RequestParserInterface`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20156]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58047
| PR author(s) | @alexandre-daubois
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
I'm not sure there's something to do here, `RequestParserInterface` doesn't seem to be mentioned at all (and not sure it should be anyway :slightly_smiling_face:)

**Comment by javiereguiluz** [comment]
OK, let's close this then. Thanks for checking it.
