### ISSUE TITLE
[Notifier] Support for desktop notifications via `jolicode/JoliNotif`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20168]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57683
| PR author(s) | @ahmedghanem00
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
This is being done in #20076.

**Comment by ahmedghanem00** [comment]
Thank you, This has been done in a separate PR as Javier has explained.

**Comment by javiereguiluz** [comment]
Closing as fixed in #20076.
