### ISSUE TITLE
[Ldap] Add support for sasl_bind and whoami LDAP operations

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#20179]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58042
| PR author(s) | @manu0401
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
@manu0401 will you have some time to contribute the docs changes for this feature?

The Symfony Docs team doesn't use LDAP so this is not easy for us. We can help with anything relatd to the contribution, syntax formatting, etc. Thanks a lot!

**Comment by manu0401** [comment]
On Thu, Sep 26, 2024 at 01:53:46AM -0700, Javier Eguiluz wrote:
> @manu0401 will you have some time to contribute the docs changes for this feature?

I cannot promise, but I can try. Where should I look?

-- 
Emmanuel Dreyfus
***@***.***

**Comment by javiereguiluz** [comment]
@manu0401 I'd say, the most appropriate place to mention this would be:

https://github.com/symfony/symfony-docs/blob/7.2/security/ldap.rst

and/or

https://github.com/symfony/symfony-docs/blob/7.2/reference/configuration/security.rst#ldap-authentication

(Also, maybe take a look here just in case: https://github.com/symfony/symfony-docs/blob/7.2/components/ldap.rst)

Thanks!

**Comment by manu0401** [comment]
On Mon, Sep 30, 2024 at 01:52:37AM -0700, Javier Eguiluz wrote:
> https://github.com/symfony/symfony-docs/blob/7.2/security/ldap.rst
> https://github.com/symfony/symfony-docs/blob/7.2/reference/configuration/security.rst#ldap-authentication

That two ones do not look relevant for this change.

> (Also, maybe take a look here just in case: https://github.com/symfony/symfony-docs/blob/7.2/components/ldap.rst)

Here we could add this before "Once bound (or if you... "

--- cut here ---
Alternatively you can perform a SASL bind with more optional arguments.
$ldap->saslBind($dn, $password, $mech, $realm, $authcId, $authzId, $props);

$ldap->whoami() returns the authorized identity.
--- cut here ---


-- 
Emmanuel Dreyfus
***@***.***

**Comment by javiereguiluz** [comment]
Closed by #20292.
