### ISSUE TITLE
[Console][Process] Add `$verbosity` argument to `mustRun` helper method

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#20178]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58074
| PR author(s) | @willrowe
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by willrowe** [comment]
I'm not sure where in the docs this should be added. I can't find anywhere that `mustRun` is referenced in the process helper section.

**Comment by nicolas-grekas** [comment]
Looks like we need doc for the method indeed!

**Comment by javiereguiluz** [comment]
The `mustRun()` method is documented here: https://symfony.com/doc/current/components/process.html#usage

In any case, we don't document the `verbose` argument of `run()`, so I think we shouldn't document it here either. It's a nice feature, but it's easy to discover by users. Thanks.
