### ISSUE TITLE
[FrameworkBundle] Remove default value for `gc_probability` config opti…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20196]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58165
| PR author(s) | @nicolas-grekas
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
This is a "good first issue" if anyone wants to start contributing to Symfony Docs.

Check this comment to know what changed in the related PR --> https://github.com/symfony/symfony/pull/58165#issuecomment-2329434886

**Comment by javiereguiluz** [comment]
Closing as fixed in #20204.
