### ISSUE TITLE
make test case classes compatible with PHPUnit 10+

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20202]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58182
| PR author(s) | @xabbuh
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by Titi68730** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by MrYamous** [comment]
I feel like this doesn't need to be documented

**Comment by javiereguiluz** [comment]
Not the actual work done on Symfony's code ... but I guess we'll need to do similar changes in the docs shown on Symfony Docs (but only when we decide to bump the minimum PHPUnit version used in docs to 10).

**Comment by javiereguiluz** [comment]
Closing as "won't fix" for the reasons given in https://github.com/symfony/symfony-docs/pull/20237#issuecomment-2371718717 Thanks!
