### ISSUE TITLE
DiveIntoHTML5.info is down

### ISSUE THREAD

**Issue by Chris53897** [symfony/symfony-docs#20248]
Used here. maybe more?
https://symfony.com/doc/current/reference/forms/types/search.html

**Comment by javiereguiluz** [comment]
For technical contents like this, let's always link to MDN (https://developer.mozilla.org/) 

Will you have time to submit a PR for the oldest Symfony maintained branch (see https://symfony.com/releases#maintained-symfony-branches) that has this issue? Thanks!

**Comment by MrYamous** [comment]
> For technical contents like this, let's always link to MDN (https://developer.mozilla.org/)

Most field types in doc haven't link to external documentation, what do you think about remove the broken link without replacing it with MDN ?

**Comment by javiereguiluz** [comment]
@MrYamous yes, that might be better in this case. Maybe we added that link because the `search` input was a new thing. I did that in #20249.

**Comment by javiereguiluz** [comment]
Closing as fixed in #20249.
