### ISSUE TITLE
[AssetMapper] Search & filter assets in `debug:asset-map` command

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20263]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58141
| PR author(s) | @smnandre
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by smnandre** [comment]
The command is already mentioned in the doc, do we need to precise all the arguments / give an example ? 

cc @javiereguiluz  ?

**Comment by javiereguiluz** [comment]
@smnandre it really depends. Generally, we don't document all options/arguments. But, for some important commands and/or some important options/arguments, we make an exception and document them.

I think these new options are useful enough to mention them, so I created #20275.

**Comment by javiereguiluz** [comment]
Closed by #20275.
