### ISSUE TITLE
Code line numbers render inline instead of stacking

### ISSUE THREAD

**Issue by tombohub** [symfony/symfony-docs#20272]
This is how it looks like for me at https://symfony.com/doc/current/validation/raw_values.html
![image](https://github.com/user-attachments/assets/3840e88a-22d5-443a-96ee-c31e724510be)

Many other examples like this

**Comment by javiereguiluz** [comment]
@tombohub I cannot reproduce this with any browser.

Please, tell us which browser and OS are you using.

**Comment by tombohub** [comment]
Thanks for checking, after your comment I suspected it's caused by some extension and it was. [Zadarma](https://chromewebstore.google.com/detail/click-to-call-zadarma/lkignmdgfllplgaabepannhkjbenhmak?hl=en) extension caused the glitch
