### ISSUE TITLE
[Mailer][Webhook] Fix SendGrid Webhook parsing

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20271]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58401
| PR author(s) | @kbond
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by JohJohan** [comment]
`SendGrid` is already documented as having webhook support see: https://symfony.com/doc/current/mailer.html#using-a-3rd-party-transport we now have support for multiple events we could add this as a version added note not sure. @kbond what do you think?

**Comment by kbond** [comment]
To me, this is a bug fix that doesn't warrant a versionadded. Admittedly, it is a gray area as the fix requires a new webhook feature. Thoughts from anyone else?

**Comment by javiereguiluz** [comment]
I agree too. It looks more like a bug fix, so no need for explicit documentation.

Thanks for checking this!
