### ISSUE TITLE
[TwigBridge] Update main.css email stylesheet to latest foundation-emai…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20295]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58448
| PR author(s) | @phasdev
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
No need to update the docs. We only mention Foundation Email CSS in https://github.com/symfony/symfony-docs/blob/7.2/mailer.rst#inky-email-templating-language and we use the following URL for the link:

```
.. _`download the foundation-emails.css file`: https://github.com/foundation/foundation-emails/blob/develop/dist/foundation-emails.css
```

By pointing to the `develop` branch we're always pointing to the most recent version.
