### ISSUE TITLE
[Config] Allow using `defaultNull()` on `BooleanNodeDefinition`

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#20309]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58490
| PR author(s) | @alexandre-daubois
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Given this is kind of a bug fix, I don't think this should be documented. It would be weird to add a special note about it in https://symfony.com/doc/current/components/config/definition.html.

**Comment by javiereguiluz** [comment]
You are right, Alex. Let's close this as "won't fix". Thanks.
