### ISSUE TITLE
Uniformise `caution` or `warning` directive usage

### ISSUE THREAD

**Issue by MrYamous** [symfony/symfony-docs#20371]
Hi ! 
While working on a PR I did some research on layout details and realized that the  `caution` or `warning` admonitions are rendered the same way in Symfony Doc. See [Doctrine](https://symfony.com/doc/current/doctrine/associations.html#setting-information-from-the-inverse-side) (this is warning) and [Lock](https://symfony.com/doc/current/lock.html#locking-a-resource) (this is caution) as exemples 

I also found #19181 about about a previous work on `caution` and `danger` and IMO there is no particular need to introduce more granularity in the admonitions that are available by differentiating `caution` and `warning`
So I propose to remove one of the two syntaxes, maybe `warning` because it's the least used in the documentation 

It's probably not a very important topic but looks good one to make documentation writing simpler and more understandable

**Comment by OskarStark** [comment]
I am in favor of changing caution to warning, so we end up with: info, (tip), warning and danger. I would also want to have a doctor rule afterwards, keeping the docs clean from caution then. WDYT?

**Comment by TimoBakx** [comment]
I'll work on this during the #SymfonyHackday.

**Comment by OskarStark** [comment]
Closed in
* #20448
