### ISSUE TITLE
[Mercure] Explain if Caddy's `publisher_jwt` and `subscriber_jwt` should be the same or different

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#20378]
Ping @dunglas 
Mercure's Caddyfile contains **two** keys: `publisher_jwt` and `subscriber_jwt` (by default populated through the environment variables `$MERCURE_PUBLISHER_JWT_KEY` and `$MERCURE_SUBSCRIBER_JWT_KEY`).
But the bundles's `config/packages/mercure.yaml` contains only **one** `secret`.
How does this fit together? Are people supposed to use the same string for both keys in the Caddyfile?
* If yes, then why do two settings exist? And isn't this a security risk (kindof allowing subscribers to publish)?
* If no, then how to pass the two strings to the bundle?

**Comment by wouterj** [comment]
Hi! The secret refers to the publisher secret, maybe it makes sense to clarify this in https://symfony.com/doc/current/mercure.html#configuration. As far as I know, the PHP side can only publish messages.

**Comment by dunglas** [comment]
The component used to only publish, but it can now also subscribe thanks to the Twig integration.
The bundle has not been updated to support using two different secrets. The proper fix is to update the bundle (it's on my to-do list, but any help is welcome!).

**Comment by wouterj** [comment]
Thanks for clarifying this @dunglas and nice catch, Thomas!

I see there already is an issue about this on the bundle side: https://github.com/symfony/mercure-bundle/issues/91 So let's close here, and document the new option once it's available in the bundle.
