### ISSUE TITLE
Bug with searching on the results page

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-docs#20375]
When I search for something on symfony.com:
<img width="333" alt="Screenshot 2024-11-07 at 18 39 36" src="https://github.com/user-attachments/assets/e6dd0980-a773-42a8-ae7e-1193b47a4dbb">

It opens https://symfony.com/search?q=hello page with the text field and results:

<img width="647" alt="Screenshot 2024-11-07 at 18 40 49" src="https://github.com/user-attachments/assets/1a52d816-08d3-49f5-8c07-91e3ad27ad01">

When I write something in that search field and press enter - it breaks the results:
<img width="473" alt="Screenshot 2024-11-07 at 18 41 11" src="https://github.com/user-attachments/assets/b45403ec-e46c-4361-bc8f-9f10515c7290">

Because it opens https://symfony.com/search?query=hello+world

Seems the problem in the field name - it should be just `q` instead of `query` there.

**Comment by javiereguiluz** [comment]
Thanks for reporting this Victor. It's now fixed.
