### ISSUE TITLE
Questioning the use of static calls to assert* methods

### ISSUE THREAD

**Issue by JoolsMcFly** [symfony/symfony-docs#20392]
Hi all.

Pretty much everywhere in doc pages involving tests, calls made to `assert*` methods are not static but use `$this`.
Any reason not to use `self::assert*`?

Example: https://symfony.com/doc/6.4/form/unit_testing.html
`self::assertTrue($form->isSynchronized());`

instead of 
`$this->assertTrue($form->isSynchronized());`

?

Thanks!

**Comment by MrYamous** [comment]
Hello, 

Sometimes `self:assert` is used too, in [HTTPClient doc](https://symfony.com/doc/current/http_client.html#full-example) for example
I don't think there's a specific guideline about which one to use in the documentation. Sometimes it's done one way, sometimes another.
But maybe it's something that could be standardized

**Comment by JoolsMcFly** [comment]
Hi.

If it's something I can help with let me know. I'd gladly give it a go.

**Comment by javiereguiluz** [comment]
In 6.4 branch, there are only 7 occurrences of `self::assert` and 74 occurrences of `$this->assert`.

But, as @JoolsMcFly said, the most correct form would be `self::assert`. So, I agree on making this change.

Let's ask the other Symfony Docs Team members what do they think: @OskarStark, @xabbuh, @wouterj. Thanks!

**Comment by xabbuh** [comment]
Not using `self::` is in line with the Symfony coding style. IIRC that's the reason why most of the usages in the docs are this way.

**Comment by wouterj** [comment]
Historically projects used `$this->assertX` for PHPunit test (I guess they were non-static in the older versions?). I think the common PHP developer is much more used to the non-static call variant.

Besides that, it is also still what the PHPunit documentation uses and [there are no plans to changing that](https://github.com/sebastianbergmann/phpunit/issues/2735). So I'm :+1: for making them all consistent to `$this->assertX()`.

**Comment by OskarStark** [comment]
Let's use $this to be consistent and in line with the code base.

In my projects I also use the static ones

**Comment by javiereguiluz** [comment]
The consensus is to standardize into non-static methods, so I created #20405 to change the few static assert calls. Thanks!
