### ISSUE TITLE
ChoiceType choice_loader option example incorrect

### ISSUE THREAD

**Issue by Thorry84** [symfony/symfony-docs#20395]
On this page: https://symfony.com/doc/current/reference/forms/types/choice.html#reference-form-choice-loader

The following example is seen:

```
            'choice_loader' => function (Options $options): ChoiceLoaderInterface {
                return ChoiceList::loader(
                    // pass the instance of the type or type extension which is
                    // currently configuring the choice list as first argument
                    $this,
                    // pass the other option to the loader
                    new CustomChoiceLoader($options['some_key']),
                    // ensure the type stores a loader per key
                    // by using the special third argument "$vary"
                    // an array containing anything that "changes" the loader
                    [$options['some_key']]
                );
            },
```

However it hasn't been possible to pass a Closure to the option choice_loader for some time now. 
https://github.com/symfony/symfony/blob/4e1cf89449edfe2ac18ac5688e174a16f290bfe1/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L371
The allowed options are `'null', ChoiceLoaderInterface::class, ChoiceLoader::class`

The example should probably be updated to the current syntax.

**Comment by yceruto** [comment]
No matter which option types are allowed, you can always define a Closure function for any option, as long as the first argument is `Options $options`.

Check out the doc for this feature here: https://symfony.com/doc/current/components/options_resolver.html#default-values-that-depend-on-another-option

**Comment by yceruto** [comment]
It’s a convenient way to lazily define a default value, especially when you need access to the values of other options or when one option depends on another.

**Comment by Thorry84** [comment]
Ah right, you are totally correct.

The error I was getting was:

`The option "choice_loader" with value Closure is expected to be of type "null" or "Symfony\Component\Form\ChoiceList\Loader\ChoiceLoaderInterface" or "Symfony\Component\Form\ChoiceList\Factory\Cache\ChoiceLoader", but is of type "Closure".`

But that was because the first parameter was Options, but not in the right namespace. The error threw me off thinking a closure wasn't possible anymore (even though I had used it in an older Symfony v5 project).

Thanks for the clarification!
