### ISSUE TITLE
Symfony installer fails on Fedora Core 41 + sOLUTION

### ISSUE THREAD

**Issue by wirepatch** [symfony/symfony-docs#20419]
The [Fedora Core (FC) Symfony installation instructions](https://symfony.com/download) read:

```
curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.rpm.sh' | sudo -E bash
sudo dnf install symfony-cli
```

This fails for two reasons on current FC 41:

1. The installer executes `dnf config-manager --add-repo $repofile`. However `--add-repo`has been replaced by `addrepo` followed by a source specification. Unfortunately I did nor find `setup.rpm.sh`in either project `symfony` nor `symfony-docs`  on Github being unable providing a merge request. I'm thus presenting a patch here:

    ```
    # diff -Naur setup.rpm.sh.orig setup.rpm.sh
    --- setup.rpm.sh.orig	2024-11-27 14:57:46.888834494 +0100
    +++ setup.rpm.sh	2024-11-27 15:29:54.474869416 +0100
    @@ -554,7 +554,7 @@
                 local yum_dnf_config_manager="dnf config-manager"
             fi
    
    -        retry 3 "$yum_dnf_config_manager --add-repo $repofile" &>$tmp_log
    +        retry 3 "$yum_dnf_config_manager addrepo --from-repofile $repofile" &>$tmp_log
             local rc=$?
             elif test "$manager" == "microdnf"; then
             mv "$repofile" "/etc/yum.repos.d/symfony-stable.repo"
    ```

2. The downloaded `symfony-stable.repo` file contains an `autorefresh=1` setting for all three repositories. In contrast to the older `dnf` version 4  this option gets no longer ignored but is being flagged as error.

**Comment by wirepatch** [comment]
Note: The above patch might fail on other / older distributions

**Comment by dkarlovi** [comment]
@javiereguiluz both of these observations are correct:

1. the patched version of the install script works
3. the `autorefresh=1` is causing issues and you're unable to proceed

**Comment by javiereguiluz** [comment]
Sorry for the late reply.

Let me ping @fabpot and @nicolas-grekas because I think they are the only ones who can update that file to fix the installation problems of Symfony CLI on Fedora systems. Thanks.

**Comment by fabpot** [comment]
See https://github.com/symfony-cli/symfony-cli/issues/543
