### ISSUE TITLE
[Website][TypeInfo] Missing documentation link for TypeInfo component

### ISSUE THREAD

**Issue by MrYamous** [symfony/symfony-docs#20422]
[TypeInfo page](https://symfony.com/components/TypeInfo) is missing [documentation link](https://symfony.com/doc/7.2/components/type_info.html)

**Comment by javiereguiluz** [comment]
Thanks for reporting this. We just fixed this and the TypeInfo component page includes the link to its docs. See https://symfony.com/components/TypeInfo
