### ISSUE TITLE
[Mailer][Notifier] Add webhooks signature verification on Sweego bridges

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20441]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58651
| PR author(s) | @welcoMattic
| Merged in    | 7.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by welcoMattic** [comment]
@fabpot @xabbuh I guess there is no additional documentation needed here. Sweego is already mentioned as 3rd party supporting webhooks (both in Mailer and Notifier docs). The only remaining thing is about configuring the `secret`, which is documented in README for every Bridges that support signed webhooks.

Let's close?

**Comment by OskarStark** [comment]
Yes, thanks for the feedback
