### ISSUE TITLE
[AssetMapper] add support for assets pre-compression

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20442]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#59020
| PR author(s) | @dunglas
| Merged in    | 7.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
I'm going to add docs for this feature during the #SymfonyHackday.

**Comment by javiereguiluz** [comment]
Closing as fixed in #20446.
