### ISSUE TITLE
[Console] Add support of millisecondes for `formatTime`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20460]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58946
| PR author(s) | @SebLevDev
| Merged in    | 7.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by SebLevDev** [comment]
Since my PR was merged, I’ll take care of updating the documentation this evening.

**Comment by javiereguiluz** [comment]
Closing as fixed in #20469.
