### ISSUE TITLE
:method: role creates wrong url

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#2156]
We have a very strange error on the documentation. If you take a look at http://symfony.com/doc/current/components/finder.html (or any other article which uses the `:method:` role) the links to the API docs for methods become something like this: `http://api.symfony.com/2.1/Symfony/Component/Finder/Finder.html#exclude()` while it should become this: `http://api.symfony.com/2.1/Symfony/Component/Finder/Finder.html#method_exclude`.

I thought it was an error in the extensions created by Fabian, but [that](https://github.com/fabpot/sphinx-php/blob/master/sensio/sphinx/phpcode.py#L69) looked correct:

````phyton
full_url = base_url % full_class.replace('\\', '/') + '.html' + '#method_' + method
````

The link that is created looks like the old way of generating links. When we changed to the new link format in the API doc generator, @weaverryan had changed this 8 months ago in: fabpot/sphinx-php@a9d5ec517b4878246ecb461162720e5d8b8e577d

To me, it looks like the documentation generator uses an old version of the sphinx extensions by Fabien.

/cc @fabpot 

@weaverryan this should get a 'website' label

**Comment by WouterJ** [comment]
@javiereguiluz do you have an answer already?

**Comment by javiereguiluz** [comment]
@WouterJ unfortunately I don't. I have sent several emails about this to the person responsible of fixing it but I never got a response :(

**Comment by xabbuh** [comment]
@fabpot @javiereguiluz I don't want to sound harsh, but it really is a pity to have this issue open for so long. Is there anything that we can do to solve this?

**Comment by javiereguiluz** [comment]
@xabbuh this issue *may* have been finally solved. A change has been deployed and it will be applied the next time the documentation is rebuilt. Let's wait and see.

**Comment by WouterJ** [comment]
Woot, great news :) (and just in time, I was planning to ping you on this at the meeting this afternoon :wink: )

**Comment by xabbuh** [comment]
You may not believe me, but I really did not read your comments before the meeting. :)

**Comment by javiereguiluz** [comment]
I'm happy to confirm that this error has been fixed and now all the `:method:` links work as expected  :tada: :tada: :tada:

**Comment by xabbuh** [comment]
woohoo :+1:
