### ISSUE TITLE
Not working code in documentation for custom DQL 

### ISSUE THREAD

**Issue by monbro** [symfony/symfony-docs#2185]
According to the problem https://github.com/stof/StofDoctrineExtensionsBundle/issues/136#issuecomment-12741329 i would recommend to add

    orm.auto_generate_proxy_classes: %kernel.debug%

    orm.entity_managers.default.auto_mapping: true

to http://symfony.com/doc/current/cookbook/doctrine/custom_dql_functions.html

It seems to be a common problem and without these two settings i can not add custom dql functions to my entity manager.

**Comment by WouterJ** [comment]
Closing, see my comment in #5007. As usual, if someone disagrees, feel free to commit.
