### ISSUE TITLE
[Cookbook] Document how to get information from an error screen

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#2203]
Getting the correct information from an error screen can be hard for beginners. As discussed in #1824 it is a good idea to create an article about this page and how you can debug your symfony2 application quickly.

 > @weaverryan this should get a `doc request` and `actionable` label.

**Comment by javiereguiluz** [comment]
This issue seems a bit vague. @WouterJ could you please share a quick outline or a list of the ideas that you have for such an article? Thanks.

**Comment by weaverryan** [comment]
I'm going to close this. I don't think a section on how to read error messages will be read (though, I do often tell people "Please actually read the messages, most of them are trying to help you"). 

@WouterJ If you have some actionable items that you'd like to propose, then definitely re-open.

Thanks!
