### ISSUE TITLE
Refactor the Uploading Document

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#2346]
The document in question: http://symfony.com/doc/current/cookbook/doctrine/file_uploads.html

There are a number of open issues about this document:

* #2278 
* #1559 
* #600 
* #2120 

Here's a summary of issues:

a) I really dislike the use of paths inside the entity itself

b) Complication of the callbacks not triggering if *only* the file object property is changed (since it's not mapped). This may not be avoidable, but should be solved as simply as possible).

c) I agree that the VichUploaderBundle should be suggested to help with much of this

Suggestions: One big theme is building-up in complexity from little to more.

1) We should first show how to upload files. It's very easy and includes implementing the UploadedFile object which you can get off of the Request. This should live as a little "cookbook" in the HttpFoundation component

2) Have a cookbook article that talks about uploading in Symfony, but nothing about Doctrine. This would include using a Form, validation, and moving the uploaded file in the controller.

3) Update the Doctrine file uploads doc to build off of the new, short doc in (2). So, it would start with pointing you to (2), then continue by building an entity, persisting, etc.

**Questions**

* [ ] What is a good (but still somewhat simple - I don't want to introduce services with lots of big logic to do this) way to keep track of where different "types" of files are uploaded. For example, suppose a site allows you to upload avatars and product images - the first is stored in `/uploads/avatars` and the second in `/uploads/products`. Where each type is stored should be stored in configuration somewhere, then accessed in the controller and in the view. I want to show a nice, but still simple way you might handle this.

**Comment by javiereguiluz** [comment]
I think we can close this issue now that #5375 is merged.

**Comment by weaverryan** [comment]
@javiereguiluz what do you think about removing http://symfony.com/doc/current/cookbook/doctrine/file_uploads.html entirely now?

**Comment by javiereguiluz** [comment]
I agree ... but only when I implement the changes that you suggested here https://github.com/symfony/symfony-docs/pull/5375#issuecomment-113608774 I plan to do that soon.

**Comment by weaverryan** [comment]
@javiereguiluz if that's on your list (which would be awesome), then I'll close this :). Thanks!
