### ISSUE TITLE
Bad practice in the form data transformer cookbook

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#2471]
The [data transformer cookbook](http://symfony.com/doc/current/cookbook/form/data_transformers.html) is configuring the entity maanegr by passing it through an option. This is a bad practice. Dependencies should be injected in the type through the constructor. Otherwise, all parent fields would need to know the EM too to pass it.

To allow switching between managers, the clean way is to allow passing its name (which is a string, not an object) and getting it from the registry. See the [DoctrineType](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Form/Type/DoctrineType.php) for instance.

**Comment by iltar** [comment]
:+1: I agree, this would be the best solution.
