### ISSUE TITLE
Twig template naming convention

### ISSUE THREAD

**Issue by pulzarraider** [symfony/symfony-docs#2515]
Correct me if I am wrong, but Symfony2 documentation does not specify if filename of Twig template should be written in camelCase (articleDetails.html.twig) or with underscores (article_details.html.twig).

In [Symfony naming conventions](http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions) is note: 
>Use alphanumeric characters and underscores for file names;

But in [Including other templates](http://symfony.com/doc/current/book/templating.html#including-other-templates) doc section is mentioned template filename in camel case: articleDetails.html.twig 

In the majority of open source bundles there are underscores used in template filenames (for example Sonata, KnpPaginatorBundle,MopaBootstrapBundle, GenemuFormBundle,  AdmingeneratorGeneratorBundle), but some use camelCase filenames (FOSFacebookBundle) or they mix it together (for example FOSUserBundle, FOSMessageBundle).

So what`s the recommended way? This should be clearly explained in documentation.

Also Twig coding standars should be linked somewhere in documentation: http://twig.sensiolabs.org/doc/coding_standards.html

**Comment by OHB** [comment]
@WouterJ I don't see on the linked page where it talks about the naming of templates at all...it talks about the _location_ of templates and all of the examples use `index.html.twig`. Unless I'm totally missing something but I don't see the word "lowercase", for example.

As a side question, how bad do people think it is to skip the standard in this case? I'm working on a project that necessarily has long twig names for partials (myspecialinterestingpartial.html.twig) and frankly I'd love to see that be mySpecialInterestingPartial.html.twig purely for readability. I can't see it as a cardinal sin to go that way but does anyone else have an opinion? (Can't do anything about the length of the names so don't ask)

**Comment by thomas-koch-comsolit** [comment]
Please reopen this issue. It's not solved as long as the decision is not documented in a place without ambiguity. As @OHB said, the linked Template chapter in the Symfony best practices does not talk about file names and does not contain the string "case".

**Comment by WouterJ** [comment]
This will be fixed by: https://github.com/symfony/symfony-docs/pull/4779

**Comment by WouterJ** [comment]
And it now also talks about naming :) Closing now

http://symfony.com/doc/current/best_practices/templates.html#template-locations

**Comment by leevigraham** [comment]
Latest doc link: https://symfony.com/doc/current/best_practices.html#templates

**Comment by abdellahrk** [comment]
Thank you @leevigraham, I sometimes get confused on this. Even being a long time Symfony dev.
