### ISSUE TITLE
Better documentation for UploadedFile

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#2542]
People have a hard time with the way we manage uploaded file extension and mime type. And also the difference between what the client send and what we guess. I've just sent a PR on symfony/symfony to clarify the PHPdoc, but I think we need some documentation here about this topic.

see symfony/symfony#7809 (this PR also references interesting tickets that might help writing the doc).

**Comment by WouterJ** [comment]
I disagree with my previous comment now.

We should instead add a new section to http://symfony.com/doc/current/components/http_foundation/introduction.html, talking about files. It should then explain how the mime type guessing works.

**Comment by valioDOTch** [comment]
+1

**Comment by HeahDude** [comment]
Some references from #7953, that should be clarified too:

* How this MIME type detection works: how does Symfony selects the guesser (file extension based, binary file detection, etc.), how to configure/change that behavior.
* What can I do when the guess has issues; for example for Microsoft Office file types: https://github.com/symfony/symfony/issues/22702
* How can I define my own MIME types; to avoid issues when FileinfoMimeTypeGuesser fails: https://github.com/symfony/symfony/issues/22888

**Comment by javiereguiluz** [comment]
Closing this in favor of the file uploading meta-issue: #8255.
