### ISSUE TITLE
uncompleted documentation cookbook/security/entity_provider.html

### ISSUE THREAD

**Issue by gondo** [symfony/symfony-docs#2756]
This tutorial needs more love. Here is a list of few things what i found confusing or incorrect:

* [x] 1. discrepancy in table names. table "acme_users" declared in user class, but table "user" referenced in select query `select * from user;`

* [x] 2. missing `create table users` description. (this can be guessed by putting together information from annotations from user class and provided output of select query, but why so complicated?)

* [ ] 3. missing reference on how to generate passwords with salt (provided link gives vague general idea but does not give answer on how to create password what would be usable in presented example)

* [x] 4. some random, unexplained and possibly unrelated code: #2753 

* [x] 5. `you can still authenticate with maxime` - this is confusing, as it is the first time that  some `maxime` is mentioned. missing password for `maxime` and missing reference to when this authentification should be tried for the first time. also this would not work because user class is referencing `UserRepository` in annotation, but `UserRepository` was not yet defined. (it will be later in the tutorial)

* [x] 6. missing `create table acme_groups` declaration.

* [x] 7. `Group` should be renamed to `Role` to avoid unnecessary confusion, and it should be declared as `class Role implements RoleInterface`

* [x] 7. tutorial should mention how to generate missing setters/getters by `php app/console doctrine:generate:entities Acme/UserBundle` (this does it for both User and Group as per http://symfony.com/doc/current/book/doctrine.html#generating-getters-and-setters )

* [x] 8. missing at least 1 working example of user and password for testing (f.e.: u: 'admin', p: 'password', p-hash: 'd033e22ae348aeb5660fc2140aec35850c4da997', salt: '')

* [x] 9. missing at least 1 working example of role/group and user assignment to this role/group.

* [x] 10. missing explanation how is the user mapped to the role/group. this time not even `select * from groups` is provided

### Question:
how should the user role be saved in the `groups` table?
this is my users table

id | username | salt | password | email | is_active
--- | --- | --- | --- | --- | --- 
 1 | admin | | `d033e22ae348aeb5660fc2140aec35850c4da997` | admin@admin.com | 1

and this is my current groups table:

id | name  | role
--- | --- | ---
1 | admin | ROLE_ADMIN

but when i login as admin/admin (yes admin is the correct password) the user role on return is empty.

### Answer
ok i've noticed that after running table doctrine:generate:entities there is one more table created what mapps user to the role.

**Comment by javiereguiluz** [comment]
This issue seems to have been solved in the merged #2765 PR. If that's true, should we close it?

**Comment by gondo** [comment]
@javiereguiluz issue you mentioned is about documentation, this there is no code change. or am i missing something?

**Comment by weaverryan** [comment]
I'll close this - I've almost certainly checked off the last item with #5083 

Thanks!
