### ISSUE TITLE
Fully document monolog bundle configuration

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony-docs#2862]
Here are a few things that got added today that would be nice to find in the docs I think for discoverability:

- [x] I added many missing handlers to the config and documented the whole thing in the code, it'd be great if someone could port it over to the real docs https://github.com/symfony/MonologBundle/blob/master/DependencyInjection/Configuration.php#L24-155
- [x] Regex based exclusion of 404 errors from the logs https://github.com/symfony/MonologBundle/issues/5#issuecomment-21756562
- [x] You can now define additional channels without having to create a tagged service https://github.com/symfony/MonologBundle/issues/39#issuecomment-21756703

That is all, thanks!

**Comment by javiereguiluz** [comment]
It's been two years since this issue was opened. I think it's time to close it as "won't fix". Besides, I don't see the point of duplicating the information that is already included in the PHPdoc. And if we really want to put that information in a real documentation, don't you think it should be included in the Monolog doc and not in Symfony doc or Monolog bundle doc?

**Comment by Seldaek** [comment]
Well, it doesn't belong in monolog much IMO, at least not yet, maybe in 2.0 if we have option arrays they could map closer to the symfony config.

Anyway what could be a think is to at least link to the configuration source file from the docs "for more info see there"?

**Comment by weaverryan** [comment]
Agree with @Seldaek - this isn't a "wont fix" it's just a "nobody has done it yet" - it's a simple issue - just add a link from the monolog configuration reference to https://github.com/symfony/MonologBundle/blob/master/DependencyInjection/Configuration.php#L24-155 to help people out. I agree @javiereguiluz that there's no reason to duplicate :)
