### ISSUE TITLE
Add tips from @beberlei blog post in the documentation

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#2924]
I think that the information contained in the article written recently by @beberlei should be included somewhere in our docs.

http://www.whitewashing.de/2013/08/19/speedup_symfony2_on_vagrant_boxes.html

What do you think?

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because the related article (https://symfony.com/doc/current/setup/homestead.html) already mentions Benjamin's tips for improved performance. Thanks!
