### ISSUE TITLE
Customization of collection row form styling

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#3202]
See symfony/symfony#4909 - I don't think this is a detail we have in the docs currently.

#1998 is related, but I don't believe the approach is the "correct" one (but it's been some time since I reviewed it). We should look at symfony/symfony#4909 and include an entry in the `form_collections` doc about how to correctly customize the styling of a collection row.

**Comment by WouterJ** [comment]
#1998 has been replaced by #4629 The suggestion of stof mentioned in the PR seems to be the correct way.

**Comment by WouterJ** [comment]
Eventually, this is now fixed by https://github.com/symfony/symfony-docs/pull/4629
