### ISSUE TITLE
Spellings

### ISSUE THREAD

**Issue by bicpi** [symfony/symfony-docs#3237]
Concerning the discussion in PR #3234 about the spelling of "e-mail/email/E-Mail" I've created a list of similiar spelling inconsistencies. If we agree on a notation I can update the docs. Please note that for some words the inconsistency is that they are used UC first or not (like stylesheet vs. Stylesheet). Of course, I don't mean the headings.

* stylesheet - Stylesheet
* front-end - frontend - front end
* Full-Stack - Full stack
* Symfony2 Framework - form framework - Form framework
* Save-handler - Save handler
* Dependeny Injection Tags - Dependeny Injection Container - dependeny injection container
* Event Dispatcher - event dispatcher
* Event Subscriber - event subscriber
* Symfony2 Standard Distribution - Symfony2 Standard Edition
* Console Command - console command
* email - Email - e-mail
* Boolean - boolean 
* web debug toolbar - Web Debug Toolbar
* Exception - exception
* object-oriented - object oriented

**Comment by weaverryan** [comment]
I believe this can be closed now... so I'm doing it :)
