### ISSUE TITLE
Entity\Role can't be serialized after using getUsers

### ISSUE THREAD

**Issue by LewisW** [symfony/symfony-docs#3480]
In the cookbook, under the Managing Roles in the Database section of the [Security Entity provider] (http://symfony.com/doc/current/cookbook/security/entity_provider.html#managing-roles-in-the-database), you provide an example Entity for Roles. Whilst you don't explicitly provide code for getUsers, if the user were to generate and use this method using the standard code generators, they may bump into the same problem that we had.

Basically, Symfony's Firewall serializes the security token (in ContextListener::onKernelResponse). This then serializes the user and their roles (UsernamePasswordToken::serialize). When Role::getUsers is called, these users are stored in the role object which is then serialized by the firewall at the end of the request. On subsequent requests, Symfony dies when unserializing these (could anyone shed some light on why it would likely do this? Does it have a maximum size it can unserialize? I haven't had time to look much in to this yet).

The cookbook suggests using a custom object serializer from the User entity (I believe due to a PHP 5.4 bug). This solution can also be used in Role entity to solve the problem. So something like the following:

    /**
     * @see \Serializable::serialize()
     */
    public function serialize() {
        return serialize(array(
            $this->id,
            $this->name,
            $this->role
        ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized) {
        list (
            $this->id,
            $this->name,
            $this->role
            ) = unserialize($serialized);
    }

Anyway, I thought I'd mention it on here in case anyone has a similar problem, and in the hopes a note could possibly be added to the cookbook. I'm happy to send PR if needed, or investigate further in to this issue if anyone is interested.

**Comment by javiereguiluz** [comment]
I don't know if this issue is still relevant. @xabbuh @WouterJ do we still mention the `Role` entity in the docs or we just recommend to always use `ROLE_*` strings?

**Comment by xabbuh** [comment]
It looks like this part vanished when we reworked the article. Thus, I'm going to close here.

@LewisW Thank you for reporting this. Anyway, please feel free to reopen if you don't agree or if you find any other spot where we are doing something similar.
