### ISSUE TITLE
Document how to reference assets

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#3575]
After a 30 min. talk with @iltar, it became clear that the asset/assetics docs are a bit confusing.

2 main points:
1. The words assets and assetics are very similair
2. There are not many words about referencing assets. For instance, we randomly use `@AcmeDemoBundle/Resources/public/...`, `bundles/acmedemo/...`, `some/*`, etc. We could document how to work with them.

Related issue: #1099
Usefull stackoverflow Q/a: http://stackoverflow.com/q/9500573/1149495

**Comment by javiereguiluz** [comment]
We should rethink this issue and "merge" it with the second part of this PR related to the new Asset component: #4987.

It'd be very helpful to have a TODO list of the things to review/update/add. Thanks.

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because we now properly document the Asset component, we have "best practices" for assets, the new Webpack Encore to replace Assetic, etc.
