### ISSUE TITLE
[form/form_collections] Mention Doctrine's orphanRemoval

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony-docs#3602]
I was reading http://symfony.com/doc/current/cookbook/form/form_collections.html and it didn't mention the `orphanRemoval` option to automatically delete relations.

`orphanRemoval: Boolean that specifies if orphans, inverse OneToOne entities that are not connected to any owning instance, should be removed by Doctrine. Defaults to false.`

Shouldn't it be in there instead of the manual foreach/removeElement?

**Comment by WouterJ** [comment]
As you can read in #4634 , orphanRemoval is not equal to the code shown in that article. This is why I'm going to close this one.

If you don't agree or think something is still missing, feel free to comment and we'll reopen.

Thanks!
