### ISSUE TITLE
Missing documentation for RedirectableUrlMatcher

### ISSUE THREAD

**Issue by insekticid** [symfony/symfony-docs#3740]
There is no info about using this class

**Comment by WouterJ** [comment]
In fact, the [Routing component](http://symfony.com/doc/current/components/routing/introduction.html) docs are far from complete. It focuses more on creating routes than all other things.

I propose to split the current introduction chapter into 3 chapters:

 1. Defining Routes
 1. Matching Routes
 1. Generating URLs

This allows us to talk about each topic in more detail (like mentioning how to use the RedirectableUrlMatcher in "Matching Routes"). It also allows us to remove most things from the Routing book chapter, but than can be done in another PR.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix". We're no longer going to document stand-alone components and we're going to focus exclusively on using components inside a Symfony application. Considering this, the detailed working of `RedirectableUrlMatcher` is an internal detail that users don't need to care about when using Symfony. Thanks.
