### ISSUE TITLE
Sticky headers hide the anchor links text

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#3974]
As reported by @weaverryan when you click on any anchor link (e.g. http://symfony.com/doc/current/book/controller.html#requests-controller-response-lifecycle) the sticky headers hide the text of this link and the result is pretty bad for website visitors.

I tried to fix this issue using some techniques [explained in this StackOverflow question](http://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header) but none of them was successful.

The main problem in our case is that the usually hidden anchor link (`a.headerlink`) is visible for us:

```
<h2>
  Requests, Controller, Response Lifecycle
  <a class="headerlink" href="#requests-controller-response-lifecycle"
        title="Permalink to this headline">
    ¶
  </a>
</h2>
```

Could anyone please help us solving this issue? Thanks!

**Comment by javiereguiluz** [comment]
Hopefully, this long-standing problem has been solved. I've tested it in the documentation section and in the blog. Everything seems to work as expected. If you agree, please close this issue. If not, please provide more details about the error. Thanks.

**Comment by WouterJ** [comment]
@javiereguiluz the headlines look great in the docs and blog. However, you've missed these edge cases I found:

* Sidebar anchors: http://symfony.com/doc/current/book/installation.html#book-installation-permissions
* Anchors without a headline: http://symfony.com/doc/current/book/security.html#book-security-template-expression (it should link to the versionadded directive)
* Footnotes http://symfony.com/doc/current/contributing/code/bc.html#id54

**Comment by javiereguiluz** [comment]
@WouterJ I'm glad to inform you that this annoying problem has been fixed even for the edge cases that you found. The website will now scroll via JavaScript to the right anchor link. Everything will be online soon after the next website deploy.

**Comment by javiereguiluz** [comment]
@WouterJ the website is now deployed and all these issues have been fixed. If you agree, let's close this issue.

**Comment by WouterJ** [comment]
Nice animation!

**Comment by xabbuh** [comment]
I'm wondering if I am the only one who still has issues with the sticky headers. Visiting http://symfony.com/doc/current/book/installation.html#book-installation-permissions looks like this for me (using Firefox 34):

![installation](https://cloud.githubusercontent.com/assets/1957048/5687147/b8256b1c-9849-11e4-8010-b558431bf99b.png)

**Comment by javiereguiluz** [comment]
@xabbuh this is what should happen: the page smoothly scrolls to the location of the anchor link once the page is loaded. Here it is a GIF showing it in action on my computer:

![sticky_menu](https://cloud.githubusercontent.com/assets/73419/5687527/edd16bb8-984d-11e4-8b5d-f1e1546e1c5a.gif)

In order to work, this needs JavaScript and the page must be completely loaded. Please check if there is any error in the browser inspector. Thanks.

**Comment by xabbuh** [comment]
@javiereguiluz There are no JavaScript errors and no failures for the files being loaded. Strangely enough, it works with Chrome 39.

**Comment by xabbuh** [comment]
@javiereguiluz I checked this again. When using Chrome everything works as expected. Using Firefox doesn't work though (I tested this on different systems and even with a fresh profile). Furthermore, clicking on one of the table of contents items on the left sight doesn't work either.

**Comment by javiereguiluz** [comment]
@xabbuh thanks again for reporting and investigating this problem. I can confirm that the problem existed and it's been fixed. Now it must be merged, deployed, etc.

The problem was that `animate` doesn't work with `scrollTop` on Firefox the same way as other browsers. The solution was found [here](http://stackoverflow.com/questions/8149155/animate-scrolltop-not-working-in-firefox):

```js
// works everywhere except on Firefox
$('body').animate({ scrollTop: ... });

// works everywhere
$('html, body').animate({ scrollTop: ... });
```

**Comment by xabbuh** [comment]
@javiereguiluz Thank you! I'll check again when the fix is deployed and will close here then.

**Comment by stof** [comment]
@javiereguiluz any idea when this will be deployed ? It is annoying

**Comment by javiereguiluz** [comment]
@stof I know that the changes have already been merged on symfony.com code but I don't control the deployment process, so I can't really say anything else. I'm sorry.

**Comment by javiereguiluz** [comment]
@stof @xabbuh I have good news for you! The fixes have been deployed and now everything works as expected. If you agree, please close this issue. Thanks!

**Comment by xabbuh** [comment]
Thank you @javiereguiluz :heart: It now works as expected. :smiley:

**Comment by xabbuh** [comment]
even the edge case @WouterJ listed in https://github.com/symfony/symfony-docs/issues/3974#issuecomment-68689085
