### ISSUE TITLE
[EventDispatcher] Subscribers vs Listeners

### ISSUE THREAD

**Issue by ManInTheBox** [symfony/symfony-docs#3987]
Might be worth adding one note why should one choose event listener over subscriber and vice versa. As far as I know they act essentially the same if configured properly. For example an event subscriber is aware of subscribed events by implementing [`EventSubscriberInterface::getSubscribedEvents()`](https://github.com/symfony/EventDispatcher/blob/master/EventSubscriberInterface.php#L49). But event listeners can also listen on several events simply by adding more tags:

```xml
<service id="awesome_listener" class="Super\AwesomeListener">
    <tag name="kernel.event_listener" event="kernel.view" method="onKernelView" priority="1" />
    <tag name="kernel.event_listener" event="kernel.view" method="onKernelView" priority="2" />
    <tag name="kernel.event_listener" event="kernel.view" method="onKernelView" priority="3" />
    <tag name="kernel.event_listener" event="kernel.view" method="onKernelView" priority="4" />
    <!-- Any event type, handler method, as much as you want... -->
</service>
```

Also it might be a good idea to uniquely distinguish them all with `Listener` suffix (talking about class name). People seem to be confused what _listener_ is and what is _subscriber_ and they usually do things like `ProfilerListener` but also `RequestSubscriber` in their own code. And they say that is in official documentation which is [true](https://github.com/symfony/symfony-docs/blob/master/components/event_dispatcher/introduction.rst#using-event-subscribers) (look for `StoreSubscriber `) :)

Thanks!

**Comment by javiereguiluz** [comment]
I've added a note comparing listeners and reviewers in #5377 See details: https://github.com/symfony/symfony-docs/commit/8a1d73bd3357909579ffe9f0ae991834dd1b39ee

I've reused most of the @stof's comment, but please review the note. Thanks!

**Comment by javiereguiluz** [comment]
This issue can be closed as "fixed" as of this merge: https://github.com/symfony/symfony-docs/pull/5377/files#diff-6366c83737e1ec46c8aeee833de474c1R253

**Comment by TomasVotruba** [comment]
I'm sharing my thoughs on *why* chosing subscribers over listeners: [Don't ever use Listeners](https://www.tomasvotruba.cz/blog/2019/05/16/don-t-ever-use-listeners/)
