### ISSUE TITLE
Error on Cookbook

### ISSUE THREAD

**Issue by ajouve** [symfony/symfony-docs#4032]
I don't know if this is really an error, on this page:
https://github.com/symfony/symfony-docs/blob/master/cookbook/form/data_transformers.rst 

or

http://symfony.com/doc/current/cookbook/form/data_transformers.html

I have an error when I am using $options['em'], the key does not exists

**Comment by javiereguiluz** [comment]
This issue seems to be fixed in raulfraile@b241206 but it was never merged. Can we do anything about this?

**Comment by xabbuh** [comment]
ping @raulfraile

**Comment by raulfraile** [comment]
@javiereguiluz @xabbuh I just created a PR for this, I hope it's ok!
