### ISSUE TITLE
[DX] Mention translation extractors and JMSTranslationBundle

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4061]
I just realized that we don't ever mention `translation:update` (except when talking about the `translation.extractor` DIC tag). We should show a good workflow of managing your translations with this command. We _do_ talk about `translation:debug`.

Also, see symfony/symfony#11293. Personally, I'd like to recommend that people use JMSTranslationBundle. I admin I haven't used the core extractor very much, but JMS seems more feature rich.

I tagged this as DX, because I think that if you're managing a large number of translations, we're not really explaining a good "workflow" yet.

Thanks!

**Comment by WouterJ** [comment]
:+1: A good location would be `/book/translation`.

**Comment by snoek09** [comment]
Please note the current state of the JMSTranslationBundle:

https://github.com/schmittjoh/JMSTranslationBundle/issues/213

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because the mentioned bundle is abandoned and we're removing any mention about it (see #8865).
