### ISSUE TITLE
How can we help doc translators?

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#4078]
The doc community (you!) are really active. That's very great: Symfony is one of the most actively maintained documentations and is moving towards almost 100% feature coverage!

However, there is also a downside on this. A downside where @gregquat and @garak can tell you a lot more about. The translators simply can't keep up with the pace. It so worse, we even have to ["highly recommend against creating new translations"](https://github.com/symfony/symfony-docs/issues/3831). I just had to remove 2 other translations because they are simply dead: https://github.com/symfony/symfony-docs/pull/4077

And that makes me really sad. Translations are meant to get "the Symfony word" to even more people. But at the moment, they just provide outdated docs. That's really demotivating for the few translators that still work on their translations.

What can we do about it? How can we motivate people to work on their localized docs as active as they do on the english version? Is there maybe another way of providing a translation? How do other big, active, projects manage this?

Or should we just stop translating the official docs and promote people to write Symfony tutorials in their own language on their blog? Should we maybe create a section on symfony.com with localized, proofreaded, tutorials?

(this is tagged as DX because i18n is a big part of the experience for people)

/cc @fabpot, @javiereguiluz

**Comment by Alsatian67** [comment]
Why don't you simply disable the merging of older branches in newer branches for translated docs ?
-> So long nobody has translated it for the new version, there is no translated page ...

**Comment by xabbuh** [comment]
The meeting is done by the translators in their repository. The only decision we can make is to not feature particular versions on symfony.com.

**Comment by garak** [comment]
Translations have been removed, so we can likely close this issue. Only action left is updating https://symfony.com/doc/master/contributing/documentation/translations.html

**Comment by xabbuh** [comment]
FYI, [a blog post has also been published](http://symfony.com/blog/discontinuing-the-symfony-community-translations).

**Comment by xabbuh** [comment]
see #5744 for the documentation update
