### ISSUE TITLE
[Security] Consider adding some information about checking Symfony signatures

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#4089]
Fabien published today a very interesting article: [Signing Project Releases](http://fabien.potencier.org.nyud.net/article/73/signing-project-releases). Is this something that we should mention in the official Symfony documentation?

If you agree, here it is my initial proposal:

  * Add a very short note on the installation chapter about the possibility of checking Symfony signatures (this note is just a link to the content described bellow).
  * Add a new cookbook under the Security section about checking the Symfony signature. This would be a very short version of the original Fabien's article. We won't explain anything in detail. We would just explain how to securely check the signature of Symfony releases whether you use the raw source code from GitHub or the Composer version.

**Comment by WouterJ** [comment]
It can be closed now!

(btw, maybe this should be integrated into the installer?)

**Comment by xabbuh** [comment]
> (btw, maybe this should be integrated into the installer?)

symfony/symfony-installer#21 for anyone looking into this :)
