### ISSUE TITLE
Avoiding duplicated documentation

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#4100]
Especially for the Form component, we have many things documented twice (in the book and in the components part) as @weaverryan  stated in #4085:

> It's difficult because the form component has a significant amount of duplication, in part because we thought that we might try to make it work for both the component and framework all in one page (but I don't think that makes sense anymore). Ideally, I'd like to find a way to duplicate less.

This may not only be true for the Form component, but may also occur for other components and they should be checked accordingly. Therefore, this issue is to discuss whether or not we can overcome these duplicated descriptions and if we agree on avoiding duplication how exactly this can be achieved.

**Comment by javiereguiluz** [comment]
I think we can close this issue because it's too generic. Besides, we are already committed to reduce duplication in lots of places.
