### ISSUE TITLE
[Components][Security] Taking the Security component split into account

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#4151]
Starting with Symfony 2.4, the Security component has been split into four packages: ``symfony/security-acl``, ``symfony/security-core``, ``symfony/security-csrf`` and ``symfony/security-http``. This should be documented in some way at least in the components documentation.

**Comment by javiereguiluz** [comment]
This issue was supossedly fixed by #5435. I don't know if you still consider it unfixed or if there was some error with the tool that closes issues when merging pull requests. Thanks.

**Comment by WouterJ** [comment]
As the PR was merged with a squash, the commit was not a proper merge commit. This means that GitHub will only close the issues after "closes" in the commit message once the commit was merged into the master branch.
