### ISSUE TITLE
[DX] Quick entry about parameters.yml and parameters.yml.dist

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4174]
I just realized that we don't directly explain `parameters.yml` and `parameters.yml.dist` anywhere. Heck, I think we barely explain the significance of `parameters.yml`.

I would like to add a small entry talking about these and also what to expect with the Incenteev ParameterHandler. Then, we could link to this from inside the parameters.yml and parameters.yml.dist files in the SE.

See also symfony/symfony-standard#701

**Comment by javiereguiluz** [comment]
If you could provide me an outline of the things to explain, I could take care of this. Thanks.

**Comment by weaverryan** [comment]
@javiereguiluz I'm not totally sure. But, if you google for "symfony configuration", you only get back results for the Config component and other things. There is no "Symfony Framework Configuration" article that explains `config.yml`, `config_dev.yml`, `parameters.yml`, etc - though this article (http://symfony.com/doc/current/cookbook/configuration/environments.html) is related.

I want:

1) A single "How to Configure Symfony" entry
2) It has a section explaining very basically that `config.yml` let's you configure bundles - with a link to the reference section
3) It has a section explaining `parameters.yml`, `parameters.yml.dist` and what do expect with Incenteev
4) It has a quick section explaining the `config_dev.yml` files and how you can use them to tweak settings in the environments. Then a link to the full environments section.

I would appreciate any :+1: or :-1: feedback on this idea. It makes sense to me, but I don't want to create work if others don't think it's necessary.

Thanks!

**Comment by javiereguiluz** [comment]
@weaverryan I like your idea a lot ... and I have two additional suggestions:

  * What about mentioning some information about using environment variables for configuration. I find this technique very common when deploying applications.
  * Related to the previous item: we should explain "the one true way" of configuring very sensitive configuration options, such as the database credentials.

**Comment by weaverryan** [comment]
@javiereguiluz good idea! It'll be the well-rounded entry on "how to configure" in general

**Comment by WouterJ** [comment]
:+1:

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because these files are not needed when using Symfony Flex and they will be removed fro Symfony 4, which will be release in just a few months. Thanks!
