### ISSUE TITLE
[Doctrine] Security issue in handling file uploads with Doctrine

### ISSUE THREAD

**Issue by Mak-Di** [symfony/symfony-docs#4177]
[Doc file] (https://github.com/symfony/symfony-docs/blob/2.3/cookbook/doctrine/file_uploads.rst)
```php
protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
```
I don't think that storing the upload file inside of document root is a good idea.

**Comment by WouterJ** [comment]
I'm :+1: for adding a small caution to the article. Something like:

```rst
.. caution::

    Be aware that this will save the file inside the document root, which
    can be accessed by everyone. Consider placing it out of the document
    root and adding custom viewing logic when you need to secure the files.
```

Btw, @Mak-Di, the article is far from a best practice (see also https://github.com/symfony/symfony-docs/issues/2346 ). We would be very happy if anyone can turn it into a best practice article :)
