### ISSUE TITLE
cookbook->form_collections hint for options

### ISSUE THREAD

**Issue by Sicaine** [symfony/symfony-docs#4180]
Hi,

we had an issue with subform in forms and opened an issue: https://github.com/symfony/symfony/issues/11659

In short: if you embed a form into a form as collection, the method will not be properly send down. Therefore it is necessary to use options:
'options' => array(
            'method' => $options['method'],
        ),

It might be a good position for a hint on this issue in the cookbook:
http://symfony.com/doc/current/cookbook/form/form_collections.html

It might be also a good idea to have an example in the reference as well:
http://symfony.com/doc/current/reference/forms/types/collection.html#options

Tx,

Sigi

**Comment by WouterJ** [comment]
I also believe it's a very edge case and I'm leaning a bit towards -1 here.

**Comment by xabbuh** [comment]
I agree with this being an edge case. However, what do you think about adding a note to the description of the `method` option explaining that this option is not inherited by subforms?

**Comment by weaverryan** [comment]
@xabbuh I think it's more true that no options are inherited by sub forms, right? And for almost everything - that makes perfect sense.

**Comment by iltar** [comment]
I don't think the `method` is something you should be using at all for this. I believe it's only used to render the form tag, which is always the value of the top level type. I think this issue should be closed as it doesn't make sense to enforce this.

**Comment by Sicaine** [comment]
Yes after nearly 4 years this issue should be closed.

We had a specific problem which i solved, tx to the hint in the issue i linked to.

It doesn't make sense to keep this open if no one is seeing a value in extending the documentation anyway.

**Comment by weaverryan** [comment]
Cheers!
