### ISSUE TITLE
Split "Advanced Container Configuration" article

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#4228]
This article (which lives in components/dependency_injection) is some sort of dump place for all topics which we couldn't place anywhere else. This doesn't make it easy to find, while some topics in there are really best practises which should be advertised more.

 * [ ] Three topics ("Marking services as public/private", "Aliasing" and "Decorating Services") are related to the way you make your services open for extensibility. This should be moved into a new article, telling you everything about these concepts and learning you best practises.

 * [x] The "Synthetic Services" topic can also be moved to its own chapter, telling you how to inject instances into the container.

 * [x] At last, the "Requiring files" topic can be moved to a simple sidebar in the introduction chapter.

**Comment by WouterJ** [comment]
Checked last 2 tasks, as they are done in #5284 

The first task is a little difficult, mostly because we can't find a good name for it (we discussed during the sprintday). If anyone can come up with a nice title, we can start working on it. Otherwise, I propose to just leave it in the advanced article.

**Comment by javiereguiluz** [comment]
Closing it as "fixed". At the end, after the [documentation reorganization](http://symfony.com/blog/introducing-the-new-symfony-documentation), we moved the remaining topics to a new article titled "How to Create Service Aliases and Mark Services as Private". Thanks Wouter for working on this!
