### ISSUE TITLE
[DX] Improving documentation when multiple languages are possible

### ISSUE THREAD

**Issue by ajanssens** [symfony/symfony-docs#4229]
Symfony 2 comes with a lot of possibilities when it comes to configuration : YAML, XML or plain old PHP.
We also have sometimes the choice to use Annotations. As for the templating there's Twig and PHP.

Most of the time documentation is well referenced with every languages but there's still a few pages where we can only find YML when XML and PHP are possible like this one : http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html

I've made a PR (https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/325) to cover a few gaps but, by example, I don't really know how to set "type Annotation" from an import in PHP.

Here is some other pages when languages are missing : 

http://symfony.com/doc/current/book/propel.html : config.yml only, then XML for schema. I'm not using Propel but i'm asking myself : can't I use YAML here ? Or even Annotations ?

http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html#creating-a-converter : In this one converter service only in YAML and XML. PHP is missing.

I think there's a bit more of them. A really few, I'd like this DX Issue to be a first move to track this pages down and fill the gaps :)

**Comment by WouterJ** [comment]
Closing as the Propel book is going to be removed (https://github.com/symfony/symfony-docs/pull/4900) and the other examples are from third party bundles, which should be fixed and reported in their repository. I'm almost 100% sure that the core docs documents every format everywhere.
