### ISSUE TITLE
Improve documentation in "Configuring a Web Server"

### ISSUE THREAD

**Issue by MichaelMackus** [symfony/symfony-docs#4232]
I ran into an issue today where one of our LESS assets was not compiling correctly. The problem line was an @import line linking to the a component file (from our bundle's public folder).

This issue is easily fixed with adding a "FollowSymlinks" apache option to the root symfony application directory (not the web folder).

I think a simple note or just "Options FollowSymlinks" for the root symfony directory in the Web Server Configuration documentation would help here: http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html

I think this issue only applies to assets installed using symlinks (which seems relatively common). Also to note is this symfony app is inside a Vagrant VM.

**Comment by weaverryan** [comment]
Hi @MichaelMackus!

I think @xabbuh has the right suggestion. But, I don't think this has anything to do with LESS - it's more generic than that. If you're using `assets:install --symlink`, then don't you *need* this directive for those assets to be available? So, we should almost recommend this setting (unless someone can tell me I'm mistaken). But, it *can* be a security risk (imagine if you sym-linked to your root directory, or if an attacker managed to create that symink), so I'm not sure we can recommend it - in which case having it commented-out with some notes seems like the best option.

If I'm thinking wrong about any points here, please let me know :).

Thanks!

**Comment by MichaelMackus** [comment]
@weaverryan sounds about right... pretty sure its all assets installed with --symlink

The error doesn't seem to occur any more with [puphet's](http://puphpet.com) default config. It *did* occur on the default config around the time I posted this issue (or perhaps it was a little older), so I think this is relevant to some people enough to warrant a note in the docs.

Security implications are definitely something to think about... but we might be able to limit this by adding it to a directory config specifically for the assets dir? I know personally I like to firewall my dev boxes fairly well, so we might even want a security specific section if it doesn't already exist.

Not really 100% sure but even if this issue is found via google or something, hopefully it helped at least one other person :)

**Comment by weaverryan** [comment]
We've just merged in a PR related to this. Thanks @MichaelMackus for the original issue and conversation :).
