### ISSUE TITLE
Properly Document how to override core classes

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4234]
Hi guys!

First, see symfony/symfony#11881. Basically, we should be using service decoration and *not* recommending that you override any `*class` parameters. We *do* talk about service decoration in `components/dependency_injection/advanced.rst`, but I propose that we show a quick cookbook article on how to override a *real* core service.

It might also be nice to change the existing article to use examples better than foo and bar :). See https://github.com/symfony/symfony-docs/pull/3753/files#r17416550.

**Comment by WouterJ** [comment]
Closing in favor of #4234
