### ISSUE TITLE
[RFC] The Symfony Console Style Guide

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#4265]
This is the proposal for the new Symfony Console Style Guide. Please review it as soon as you can, because the schedule is pretty tight. We'd like to update most of the commands for Symfony 2.6 version.

[Download Symfony Console Style Guide](https://www.dropbox.com/s/63un0aazjnv148h/symfony_console_style_guide.pdf?dl=1) (PDF, 89 KB)

**Comment by xabbuh** [comment]
@javiereguiluz Is there any news about this?

**Comment by javiereguiluz** [comment]
@xabbuh no news at all :(  @kbond did a great work transforming this PDF guide into actual code and he created new console methods for commands, but there seems to be no interest in updating all the framework's commands (which is a lot of work by the way).

**Comment by xabbuh** [comment]
@javiereguiluz Can you give a quick overview of what you think would be the next steps? As far as I understand, the guide is finished and people could start reworking all commands. Is that right?

**Comment by WouterJ** [comment]
With the new styles now merged into the code and the core commands in progress of being updated, I think it's time to move this issue forward.

I think the best first step is to transform the latest PDF in this issue into reStructured Text formatting in the documentation. This way, we can easily discuss the guide and improve it.

**Comment by xabbuh** [comment]
@javiereguiluz Can you please add a link to the current (final) version of the style guide to your initial description? It would make it easier for people wanting to contribute to find the most recent version.

**Comment by javiereguiluz** [comment]
We can close this as "fixed". The feature is implemented since Symfony 2.7 and the docs are published at https://symfony.com/doc/current/cookbook/console/style.html
