### ISSUE TITLE
[Cookbook][Doctrine] Update DoctrineBundle version information for the DoctrineOrmMappingsPass

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#4273]
The ``versionadded`` directive in the [cookbook article](http://symfony.com/doc/current/cookbook/doctrine/mapping_model_classes.html) about providing mapping classes for several Doctrine implementations states that you can use it with DoctrineBundle 1.2.1. However, the ``DoctrineOrmMappingsPass`` has been introduced with 1.3.0-beta1 (see doctrine/DoctrineBundle#333).

**Comment by WouterJ** [comment]
For some reason, #4544 did make it into 2.3 and 2.5, but was removed from 2.6+. I've now cherry picked it into 2.6+ so this issue can now be closed
