### ISSUE TITLE
Initializing a new projet from composer

### ISSUE THREAD

**Issue by acidjames** [symfony/symfony-docs#4305]
Hi, Here are the questions asked when initializing a new project from composer:

Would you like to install Acme demo bundle? [y/N] n
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_driver (pdo_mysql):
database_host (127.0.0.1):
database_port (null):
database_name (symfony): 
database_user (root):
database_password (null): 
mailer_transport (smtp):
mailer_host (127.0.0.1): 
mailer_user (null):
mailer_password (null):
locale (en): fr
secret (ThisTokenIsNotSoSecretChangeIt): KNAKIBALLS!!!!!!!!
debug_toolbar (true):
debug_redirects (false):
use_assetic_controller (true):

I understand most of us know what to enter here but for instance, some may not understand what "use_assetic_controller" implies. I browsed the documentation and the project initialisation doc doesn't refer to all these questions. I'm refering to the friendliness concept of project initialisation...

**Comment by WouterJ** [comment]
I'll close this issue now, as the installer has become the official way of installing Symfony.
