### ISSUE TITLE
Potential note about using a join query in the form collection docs

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4323]
I was chatting with @guilhermeblanco on Twitter, and we realized that if you're using Doctrine and doing something with a form `collection`, then you'll definitely have the n+1 problem. Of course, the `collection` type can be used without Doctrine, but if we can add a note to the reference doc (and/or the cookbook article) about querying with a join, then it might be an easy performance.

**Comment by vudaltsov** [comment]
this issue is about the same question: https://github.com/symfony/symfony-docs/issues/3374

I can make a PR on such a note.

**Comment by javiereguiluz** [comment]
It'd be great if someone could send a small note about this. Thanks!

**Comment by javiereguiluz** [comment]
Fixed by #11019.
