### ISSUE TITLE
[RFC] Change Resources/meta/LICENSE and Resources/doc/index.rst

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony-docs#4335]
Currently the [best practise for reusable bundles](http://symfony.com/doc/current/cookbook/bundles/best_practices.html#directory-structure)  says 

> The following files are mandatory:
HelloBundle.php;
Resources/meta/LICENSE: The full license for the code;
Resources/doc/index.rst: The root file for the Bundle documentation.
These conventions ensure that automated tools can rely on this default structure to work.

I think it's time to change that. I would propose to simply say there should be

1. a LICENSE file in the root directory and a [license property in composer.json](https://getcomposer.org/doc/04-schema.md#license)
2. a README file (in any format, e.g. README.md or README.rst) in the root directory that serves as an entry point to the documentation

I think this has several advantages:

1. this is how Symfony itself is also structured. For example, the documentation of symfony bundles is not in Resources/doc but in a separate repository. So symfony does not follow it's own best practises at the moment.
2. the LICENSE file in the root is common practise in open source but Resources/meta/LICENSE is not
3. the README is also common practise, especially when using github. This also makes it independent of the format. And most bundles don't use `rst` format anyway from my experience but markdown, e.g. [FosUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle/tree/master/Resources/doc). Which would also go against the current best practise.

**Comment by WouterJ** [comment]
The rules are now made more flexible, allowing both locations for the LICENSE file and both rst and markdown for the README file
