### ISSUE TITLE
[Console] Document the interaction process

### ISSUE THREAD

**Issue by gossi** [symfony/symfony-docs#4366]
Hey guys,

I just wrote a CLI application using the symfony console component, which is great. I know from composer, that there is an interactive mode, where I can get some user-input. Unfortunately there was no official documentation for it. So I looked up the source in composer and symfony to get my job done. Would be nicer to just read it on the symfony documentation, because it was opened anyway as a reference for me.

Thanks

**Comment by WouterJ** [comment]
This is indeed missing (#4996 is also related). It should at last be added to the console component documentation.

**Comment by WouterJ** [comment]
Fixed by https://github.com/symfony/symfony-docs/pull/5319
