### ISSUE TITLE
Document Security Events

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4373]
See the `SecurityEvents` class for these 2:

* `security.interactive_login`
* `security.switch_user`

And [AuthenticationEvents](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/AuthenticationEvents.php) for these 2:

* `security.authentication.success`
* `security.authentication.failure`

We should at least have a mention of them somewhere and when you would use them. This relates partially to #802. I've also never been clear on `security.interactive_login`, it's name and PHPDoc suggests that there are other, non-interactive ways to login, and so that a listener to this would not cover all login cases.  I'm not sure what that includes/doesn't include.

**Comment by arnaugm** [comment]
What would be the best event to listen to in the case I want to show a message every time a user logs in (including remember me option enabled) and this user has some specific characteristics?

I understand that ```security.interactive_login``` is not enough.
If I use ```security.authentication.success```, what happens when the user is authenticated but not authorized?

**Comment by arnaugm** [comment]
I just realized that ```security.authentication.success``` is triggered in every request, not only after the login. Now I understand better the reason of ```security.interactive_login```.

I checked that the remember me cookie triggers ```security.interactive_login``` as well, which means that this feature is considered interactive.
