### ISSUE TITLE
Security Voter not aware of role hierarchy in Symfony Best Practises

### ISSUE THREAD

**Issue by richard-keller** [symfony/symfony-docs#4389]
The section on Security suggests using Security Voters to implement complex security logic. The provided code example makes use of the `getRoles()` function to determine whether the user has the given role. However, it should be noted that this won't work if role hierarchies are used, since the User entity is not aware of the full role hierarchy.

Code snippet in question:

```php
protected function isGranted($attribute, $post, $user = null)
{
    if ($attribute == self::CREATE && in_array(ROLE_ADMIN, $user->getRoles())) {
      return true;
    }

    return false;
}
```

I imagine that the best way to handle this would be to use something like `$securityContext->isGranted('ROLE_ADMIN')`  but then we should be injecting `security.context`, and not the User.

Edit: It would appear that using `security.context` isn't a great idea, since it works using the token for the currently logged-in user. Regardless, I think the documentation should note that the solution provided will not work for hierarchical role structures.

**Comment by jdachtera** [comment]
First inject @security.role_hierarchy into the voter. Then use this code:

    protected function hasRole($roleName, TokenInterface $token)
    {
        foreach ($this->roleHierarchy->getReachableRoles($token->getRoles()) as $role) {
            if ($roleName === $role->getRole()) {
                return TRUE;
            }
        }
        return FALSE;
    }

**Comment by WouterJ** [comment]
If I understand things correctly, this can't be fixed at the moment. @javiereguiluz can you please confirm?

**Comment by javiereguiluz** [comment]
@WouterJ sadly this problem cannot be solved yet. There is a pending PR https://github.com/symfony/symfony/issues/14048 which unfortunately didn't get much attention.

**Comment by weaverryan** [comment]
See https://github.com/symfony/symfony/issues/14048#issuecomment-143464257 - this is now actionable in 2.8 and we really should have a cookbook article or section about this.

**Comment by weaverryan** [comment]
this is now fixable in Symfony 2.8: see #5908 for the example. Someone needs to update `best_practices/security.rst` to close this issue and #5728

**Comment by weaverryan** [comment]
Fixed!
