### ISSUE TITLE
Missing documentation for creating third-party bundles

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#4393]
The other day, during a meet up organized by the Symfony Barcelona group, some developer asked me why there isn't a document describing the whole process of creating a third-party bundle.

There is of course documentation for some parts of the process of creating a third-party bundle (such as how to expose a semantic configuration), but there is no document describing in detail the whole process. Important things such as creating the first empty skeleton for the bundle and testing the bundle inside a real application are missing.

Given that there are +3,000 public bundles, it's strange that this documentation doesn't exist yet. Do you think we should create it?

Update: it's also important to add docs about [how to test stand-alone bundles](https://github.com/symfony/symfony-docs/issues/4503)

**Comment by romaricdrigon** [comment]
I totally agree!
While creating a Bundle I came across the same questions, I was thinking about writing it some day.

**Comment by timglabisch** [comment]
:+1:

**Comment by WouterJ** [comment]
The testing part is covered in #4503. It would be interesting if we could have a new cookbook about it!

**Comment by javiereguiluz** [comment]
closing in favor of #8629, which lists all the issues to be fixed related to bundles.
