### ISSUE TITLE
Add description for the "validation_groups" option

### ISSUE THREAD

**Issue by webmozart** [symfony/symfony-docs#4401]
The documentation of the "validation_groups" option for the "form" type is missing. The option should make clear what the options actually does, which seems to be confusing for many users. See symfony/symfony#12342 for example.

**Comment by WouterJ** [comment]
To be clear: This has to be added to `/reference/form/types/form.rst`.

The option is only valid on the root node and is used to specify which groups will be used by the validator. This should be made clear in the description.

**Comment by xabbuh** [comment]
Additionally, we should add the same warning (that this option is only evaluated for the root form type) in the book where we talk about validation groups.

**Comment by iltar** [comment]
It's slightly documented on: http://symfony.com/doc/current/form/validation_groups.html

However, it's missing the callback documentation and it's not listed on https://symfony.com/doc/current/reference/forms/types/form.html
