### ISSUE TITLE
[Security] No mentioning of PersistentToken for "Remember me"?

### ISSUE THREAD

**Issue by althaus** [symfony/symfony-docs#4414]
Hey,

I just dug into the "Remember me" handling and was quite suprised to find a Doctrine based token store. As this method improves the security by only storing an authentication token in the client, this should be at least mentioned in the docs. It also helps if you're using some custom authentication handling so that you could hook up in the RememberMeServices.

http://symfony.com/doc/current/cookbook/security/remember_me.html

Cheers
Matthias

**Comment by PReimers** [comment]
As far as I can see, it's mentioned in the documentation.

**Comment by althaus** [comment]
Uhh... that's been a long time ago... brain hurts...

As far as I can relive this from our current implementation I've been hasseling around with the `\Symfony\Component\Security\Http\RememberMe\PersistentTokenBasedRememberMeServices` although my text above sounds more like the `DoctrineTokenProvider` linked.

Hmm... feel free to close the issue due to uncertainness.

**Comment by OskarStark** [comment]
> Hmm... feel free to close the issue due to uncertainness.

Lets close here, thank you for the feedback @PReimers and @althaus 👍
