### ISSUE TITLE
Documentation for Asset Packages

### ISSUE THREAD

**Issue by langj** [symfony/symfony-docs#4439]
Currently Asset Packages are only documented in the [Framework Full Default Configuration Reference](http://symfony.com/doc/current/reference/configuration/framework.html#full-default-configuration)

It would be nice to have a little more Documentation about this Feature because it's quiet usefull.

I think the important PRs are:
* symfony/symfony#202
* symfony/symfony#1047

**Comment by WouterJ** [comment]
@langj I've included some more information in the config in https://github.com/symfony/symfony-docs/pull/4736/files#diff-c0c158a40398b72fa4f0c9d0accbc169R1085 Do you think this is enough?

**Comment by langj** [comment]
Yes, it looks good. Thank you.

**Comment by javiereguiluz** [comment]
This issue can be closed because the issue reporter is happy with the improvements made by @WouterJ. Moreover, asset packages will be soon better explained in the soon-to-be-merged Asset component documentation (see #4987).

**Comment by WouterJ** [comment]
@javiereguiluz both PRs aren't merged yet. According to our conventions, we'll leave this one open until they are merged.

**Comment by WouterJ** [comment]
Both PRs are merged now
