### ISSUE TITLE
[Best practices] Link to The components in the last page, misplaced link?

### ISSUE THREAD

**Issue by skafandri** [symfony/symfony-docs#4474]
In the [last page](http://symfony.com/doc/current/best_practices/tests.html) of Best practices section, there is a link in the footer to [The components](http://symfony.com/doc/current/components/index.html) section from the documentation.

I think that link should be either removed, either presented as a *see also* or *read more*. The way is presented now is misleading. It gives the impression that is the **next chapter** of Best practices section while it is not.

**Comment by xabbuh** [comment]
@javiereguiluz Interestingly, there are pages without any links (for example http://symfony.com/doc/current/cookbook/console/console_command.html). Do you know the reason for this?

**Comment by javiereguiluz** [comment]
@xabbuh I don't know why does that happen. In any case, we are probably going to change this navigation a bit and in the new version the links are back. I'll tell you when these changes are deployed in production.

**Comment by javiereguiluz** [comment]
The changes I mentioned to the doc navigation have been deployed:

### Before

![desktop_before](https://cloud.githubusercontent.com/assets/73419/12086326/41f27b10-b2c9-11e5-8657-1be718cfaf03.png)

### After

![desktop_after](https://cloud.githubusercontent.com/assets/73419/12086327/443ae704-b2c9-11e5-8eee-db9bc10737dd.png)

---

After much thought about this, we decided to not make any further changes for the moment to this navigation. So we can close this issue as "won't fix". Thanks.
