### ISSUE TITLE
[HttpKernel] Missing documentation about HttpKernel Extension

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#4492]
Recently I've made a PR for the `SecurityComponent` to remove the `SecurityContext` in 3.0. I found something in the `SecurityExtension` that caught my eye:

```php
$this->addClassesToCompile([
    // list of class names
]);
```

I've never seen this method before so I went on searching for it. It seems like the HttpKernel component has a custom Extension that adds this method and the `SecurityExtension` extends this. It seems like this makes it possible to add the contents of the classes to `classes.php` in your cache directory.

When I was looking for documentation, I couldn't find any. I was expecting it to be on at least one of the following pages:
 - http://symfony.com/doc/current/cookbook/bundles/extension.html
 - http://symfony.com/doc/current/components/http_kernel/introduction.html
 - http://symfony.com/doc/current/book/performance.html

Should this be a feature that's documented? If that's the case, I can take a look at how it exactly works, implement it and write down when you should or should not add classes to this list.

**Comment by WouterJ** [comment]
@javiereguiluz talk can be found at: https://youtu.be/B8Sbo-JxKMo?t=7m11s

I propose to add a new section about adding classes to compile in `cookbook/bundles/extension. We can then add a nice tip in `book/performance` linking to this new section. I won't add it to the HttpKernel components, as it's not talking about extensions at the moment (those component docs has to be updated).
