### ISSUE TITLE
[Config] Clarify the difference between lists and maps

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#4509]
It seems that it is a bit unclear when the Config component processes an array node in the tree builder either as a map or as a list. Especially the effects of `useAttributeAsKey()` should be clarified (see symfony/symfony#12304 for the context).

**Comment by WouterJ** [comment]
This should be done in `components/config/definition`

**Comment by vishalraj82** [comment]
I am using useAttributeAsKey, but could not find any way for the child keys to have only boolean values. Any help ?

**Comment by xabbuh** [comment]
@vishalraj82 We only use GitHub to keep track of what needs to be done in the documentation. I suggest you use one of [the support channels](http://symfony.com/support) to reach out for help. Thank you for understanding.
