### ISSUE TITLE
Nav bar is no longer sticky

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#4515]
The nar bar moves into a sticky position at after some 100 pixels, it just scrolles out of the screen. This means most of the time, there is no sticky nav bar.

I experienced this on a Windows 8.1 PC using Chrome 41.0.2224.3

**Comment by javiereguiluz** [comment]
I can't reproduce this problem on Mac OS. The navbar is sticky for desktops, but not for tablets or smartphones. Could you please provide more information about this issue? Thanks!

**Comment by WouterJ** [comment]
I can't reproduce now, but I know I've had it last week. When I have it again, I'll make a screenshot. Closing this unless I experience it again.

Btw, the download button in the sticky nav is just 1px more to the right than code blocks. Can you please add `margin-right: 1px;` to `#header-download-sticky`? :)

**Comment by javiereguiluz** [comment]
@WouterJ I can't reproduce the problem. The Download button looks completely aligned to me:

![download_button_alignment](https://cloud.githubusercontent.com/assets/73419/5614438/8b08fa46-94f1-11e4-9b62-685a2ed57d9f.png)
