### ISSUE TITLE
[WCM] [Cookbook] [Security] Change the interface which needs to be implemented by a user repository

### ISSUE THREAD

**Issue by mtrojanowski** [symfony/symfony-docs#4543]
The symfony ticket: https://github.com/symfony/symfony/pull/12733

If the code is merged, in this artice http://symfony.com/doc/current/cookbook/security/entity_provider.html#authenticating-someone-with-a-custom-entity-provider the interface used by the repository should be changed to the new interface and the `supportsClass` function can be deleted from the implementation.

**Comment by mtrojanowski** [comment]
This is now connected to the PR #15947, which introduces slightly different changes. Nevertheless it will need a fix in the docs if the PR is accepted so please keep this issue open.

**Comment by WouterJ** [comment]
Will be fixed by https://github.com/symfony/symfony-docs/pull/5993
