### ISSUE TITLE
[Best practices] broader translation keys naming conventions

### ISSUE THREAD

**Issue by hellomedia** [symfony/symfony-docs#4563]
Could there be extra suggestions for translation keys naming conventions ?
In the best practices, I currently see `label.username` and `title.post_list`. What other categories would be recommended ? `button.xxx` , `menu.xxx` ? What about longer text ?
NB: I see the point for categories ( label, title .... ) but obviously it can also lead to duplicates.
I would love to read Fabien's insight on this.

**Comment by mpdude** [comment]
This could also include a recommendation whether or not to use a particular message domain (e. g. "forms", like we also already have "validators") for messages like form labels.

Also, should the form type/name be included, like `signup_type.username.label` or `signup_type.submit.button`?

**Comment by javiereguiluz** [comment]
I agree with @xabbuh: it's hard to provide a good generic solution here, besides the obvious one that we are already using (`button` + something, `label` + something, etc.)  In addition, few people have asked us about this, so I'm closing as won't fix. But we can discuss about this again in the future. Thanks!
