### ISSUE TITLE
[2.6] Document PdoSessionStorage::createTable

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4610]
In Symfony 2.6, there is a createTable method that could be used to create the session table, instead of doing it by hand. See http://stackoverflow.com/questions/27342318/symfony-2-6-login-randomly-fails#answer-27343220

I think we should find a nice way to document using this instead of (potentially) listing all the SQL needed on that page.

**Comment by WouterJ** [comment]
Fyi, this issue is talking about this article: http://symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html

**Comment by javiereguiluz** [comment]
Fixed by #9104.
