### ISSUE TITLE
[Best Practices] More elaborated flat controller example

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#4616]
This issue was originally opened at the code repository. Quoting @Vinorcola from symfony/symfony#12418:

> Hi everybody,
> 
> I'm not sure if it is the best place to talk about this, but I'll try. The official best practices reveals some important things on the way to adopt when developping a Symfony2 app. One of them is about the flat controller. However, the example given (of a controller) is a so simple example that it is impossible to make a fat controller with it anyway. It would be more relevant to show a more elaborate controller (with email sending, form usage, session variables usage, etc.) to see how we must do to create flat controllers.
> 
> Because the current example does not help realy much...

**Comment by WouterJ** [comment]
Should we use an example of the [demo application](https://github.com/symfony/symfony-demo)?

**Comment by Vinorcola** [comment]
@javiereguiluz Yep, no problem.
