### ISSUE TITLE
[enhancement][documentation]remember my symfony version in books

### ISSUE THREAD

**Issue by bastien-g** [symfony/symfony-docs#4678]
Hi,

**I think it would be pretty handy to remember (maybe by cookie) the last Symfony version we looked for in documentation (Books).**

For example, i am actually working with Symfony 2.3 and i have to select version 2.3 every time i have a look to the doc so it is little tedious. And it can be a problem if you try to use a functionality that is not in your current Symfony version yet.

Hope i am not the only one in this case...

**Comment by javiereguiluz** [comment]
After considering all options and after much thought, we've decided to not change the current behavior. We can close this issue as "won't fix" then. Thank you all for the discussion and for giving your opinions about this proposal!
