### ISSUE TITLE
Reword kernel.event_listener description

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#4680]
In the DIC tags reference, we should reword the description of the `kernel.event_listener` tag. Currently, it can be understood wrongly as something that's only meant for core things.

Thanks to our IRC friends for reporting this issue!

 > *ChairmanOfBoard*: What I stumped at, was that it seemed like kernel.event_listener was just for core events, and that somehow I felt maybe one should create their own event dispatcher outside the main one
 > *Lumbendil*: no
 > *Lumbendil*: what made you think such a thing? :)
 > *ChairmanOfBoard*: This doc
 > *ChairmanOfBoard*: http://symfony.com/doc/current/reference/dic_tags.html
 > *ChairmanOfBoard*: For example, if you have a service that you would like to register as a listener to one of Symfony's core events, you can flag it with the kernel.event_listener tag.
 > *ChairmanOfBoard*: I don't think I thought enough about that line, and took it the wrong way
 > *ChairmanOfBoard*: Also the name "kernel.event_listener" makes it sound like its just for kernel events

**Comment by bicpi** [comment]
@WouterJ I don't quite get what is confusing here. Is it the description in the overview table at the beginning or the [detailed description](http://symfony.com/doc/current/reference/dic_tags.html#kernel-event-listener)?

**Comment by WouterJ** [comment]
It's not the documentation that is confusing, it's the name of the tag. As we can't rename the tag simply, we should make it clear to explicitely tell them that this tag is for your own listeners/subscribers.

**Comment by javiereguiluz** [comment]
I'm trying to reword this content in #5445 but I don't know if the new explanation is better than the existing one.
