### ISSUE TITLE
Change Reference header style for improved readability

### ISSUE THREAD

**Issue by ifdattic** [symfony/symfony-docs#4684]
I think it might be a good idea to customize the headers a little more to help distinguise between sections (which would improve readability).

For example in http://symfony.com/doc/current/reference/configuration/framework.html#session the difference between **session** and **name** is so small that it's hard to notice the difference between a configuration block and available keys.

![screen shot 2014-12-25 at 1 37 14 pm](https://cloud.githubusercontent.com/assets/966877/5553873/bd2570a4-8c3b-11e4-9fc7-6b1f8ae188be.png)

**Comment by weaverryan** [comment]
@javiereguiluz :+1: let's do it and then we can check to see if there are any adverse side effects. But clearly, the changes you've made are better.

@iltar that makes sense to me - someone can just open a PR for that change :)

**Comment by WouterJ** [comment]
I don't like @iltar's suggestion much (but don't care much about it too :P).

**Comment by javiereguiluz** [comment]
We've updated the styles for lots of "configuration reference": forms, twig, framework, CMF, etc.  Even if we've carefully reviewed most of pages, it'd be great if you could also review all the pages linked from http://symfony.com/doc/current/reference/index.html

When we verify that everything is right, we can safely close this issue. Thanks!

**Comment by xabbuh** [comment]
> While at it, would it be an idea to have the options comma separated?

I don't really care. But this change actually requires a lot of manual work.

**Comment by xabbuh** [comment]
@javiereguiluz Is the lot of space between two configuration options intended?

**Comment by javiereguiluz** [comment]
@xabbuh it depends. In this page http://symfony.com/doc/current/reference/configuration/framework.html#trusted-proxies there are two un-explained options and that makes it to look bad. For the rest of options, there is a lot of white space to improve readability, so it's intended. In any case, if a lot of you think it's too much white space, let's tweak it.

**Comment by WouterJ** [comment]
I like it! :+1: 

Is this done automatically or manually? E.g. if the CMF adds a new bundle or if we change doctrine to this way better reference format, do we need to ping you so you can add those pages to the build process?

**Comment by xabbuh** [comment]
@javiereguiluz I don't care that much. So, let's keep it as long as nobody else objects. :)

**Comment by javiereguiluz** [comment]
@WouterJ it should be automatic. The problem may arise when using very complex config references (such as CMF, which contains lots of nested options). So it could be necessary some manual tweaks in the future for some special pages.

**Comment by weaverryan** [comment]
Thanks Javier - it looks really great to me. I'm satisfied :)

**Comment by xabbuh** [comment]
I'm going to close then as everbody seems to be happy with the new style. :+1:
