### ISSUE TITLE
Improve the SecurityFactoryInterface documentation

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#4705]
This was initially opened by @langj on the code repository in symfony/symfony#10870:

> The methods of the SecurityFactoryInterface do not have any comments. It would be helpfull if there were comments describing how the methods should be implemented and how the are used.
> 
> http://symfony.com/doc/2.3/cookbook/security/custom_authentication_provider.html
> is describing the Interface a bit, but especially the signature of the create method is unclear.

**Comment by rdohms** [comment]
This interface needs at the very least a docblock to explain its return value, it gives absolutely no clue as to the implementation. Very sad to see the original bug report dismissed.

**Comment by cordoval** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Closing as fixed because some comments were added to the code in https://github.com/symfony/symfony/pull/18114  We won't add detailed explanations about methods and their signatures because we don't usually do that in the Symfony Docs (because that makes docs impossible to maintain). Thanks!
