### ISSUE TITLE
[Template Inheritance] Missing note regarding different AppKernel location

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#4714]
I was having an issue regarding overriding twig template when following the TwigBundle example for custom error pages. The documentation points out that I should place it in `app/Resources/TwigBundle/views/Exception/error.html.twig`. I've tried this and it didn't work. 

A little more context; I'm porting a Symfony1 application to Symfony2. Currently in a state where we have replaced 100% of the actions and we wanted to implement a fully Symfony2 error page.

Our `AppKernel` is located in a different directory: `apps/myapp/lib/` due to compatibility with Symfony1. This was also the reason why the examples didn't work. Once I moved it to `apps/myapp/lib/Resources/TwigBundle/views/Exception/error.html.twig`, everything was working fine.

Scanning the docs, I missed a part where it mentioned that `app/` is used because that's where the `AppKernel` is as it uses `kernel.root_dir`. I wasn't able to find a proper location to put this and a discussion on IRC with @WouterJ pointed out that there might actually be more that needs moving around to solve this "confusion".

**Comment by javiereguiluz** [comment]
I don't like the idea of adding this explanation to the regular docs. To me, using multiple kernels is still a very uncommon edge case.

I propose instead to add this information, as well as any other issue specific to multi-kernel apps, to the article that describes how to use multiple kernels in Symfony (this article doesn't exist yet: see #997)

**Comment by iltar** [comment]
@javiereguiluz it's not about multiple kernels in particular. I had my kernel in a different locations due to framework migrations and seemingly simple things can become quite a pain without this being documented.

**Comment by javiereguiluz** [comment]
@iltar I see. Anyway, having the kernel in a different location looks even more uncommon to me. Maybe we could add a cookbook about how to move the kernel to another location and all the troubles that you'll find, such as the location of the templates.

**Comment by javiereguiluz** [comment]
@iltar almost two years after my last comment I think you were right and I was wrong :( I'm trying to fix this in #7844.
