### ISSUE TITLE
Clarify form_login versus simple_form

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4718]
From this discussion: https://github.com/symfony/symfony-docs/pull/4606#discussion_r21440342

There, I say:

> Is the only difference between form_login and simple_form the fact that simple_form requires the authenticator key?
> 
> If that's true, the we could potentially have an addendum/note to this chapter that says something like:

``` rst
If you have a form login, but need to do something custom to check the username
and password validity (e.g. call out to an API or have a third field - e.g. accessKey
in your login form) then you can use the very similar simple_form with a custom
authentication [link to custom_password_authenticator.rst].
```

We just need to clarify if my assumption above is correct. And if so, add the given note (and maybe also clarify in the `custom_password_authenticator.rst` entry that `simple_form` has identical configuration to `login_form`, except for the `authenticator` key.

**Comment by javiereguiluz** [comment]
I'm closing this issue because it was created 4 years ago and we haven't received any comment or similar questions about this, so the community doesn't care about this. Thanks!
