### ISSUE TITLE
book's links to methods documentation not pointing to the method

### ISSUE THREAD

**Issue by HassanCehef** [symfony/symfony-docs#4750]
Hello,

In the docs (book or cookbook) on the website, there are links to the documentation of specific methods of a class/interface/.... Those links contain anchors that don't point to the right method, ie by clicking on the link you are at the top of the class/interface documentation : you must then use ctrl+F to jump to the method's doc quickly.

For instance, in [this page from the cookbook](http://symfony.com/doc/current/cookbook/configuration/front_controllers_and_kernel.html#the-kernel-class) you have a link to the documentation of ```registerBundle()```. It points to the link http://api.symfony.com/2.6/Symfony/Component/HttpKernel/KernelInterface.html#registerBundles() instead of http://api.symfony.com/2.6/Symfony/Component/HttpKernel/KernelInterface.html#method_registerBundles

The ``#registerBundles()`` should be changed in ``#method_registerBundles``

Here's [the source (.rst) of the page I used as an example](https://github.com/symfony/symfony-docs/blob/2.6/cookbook/configuration/front_controllers_and_kernel.rst). You use (line 91)
````  :method:`Symfony\\Component\\HttpKernel\\KernelInterface::registerBundles` ```` to create a link to the doc. That's all the information I could gather.

I did not check the pdf version.

**Comment by WouterJ** [comment]
This is indeed a long open bug in the docs. We've tried everything to fix this with the things we can handle, but we haven't succeeded. Now some of the guys from SensioLabs ( @javiereguiluz ) is working on this.

While you did a great job doing research for this bug, I'm going to close it in favor of https://github.com/symfony/symfony-docs/issues/2156 . Your PR is now referenced, so your contribution is not lost.

Happy new year!

**Comment by javiereguiluz** [comment]
I'd like to add to Wouter's comment that we're actively investigating this issue and hopefully it'll be fixed soon. Thanks!
