### ISSUE TITLE
Replace {% render '...' %} by {{ render('...') }}

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#4754]
`{% render '...' %}` is discouraged since Symfony 2.2. In Symfony 3.0 will disappear forever. See https://github.com/symfony/symfony/pull/13233

I propose to review all the documentation to remove any `{% render %}` mention and usage. If necessary, we could add a small note indicating that `{% render %}` was used in the "ancient" Symfony versions, but let's state clear that it should never be used.

**Comment by WouterJ** [comment]
Thanks for creating the issue!

But I'm going to close it, as we've updated all docs already when the original deprecation PR was merged. (we almost never used deprecated things in the docs) If you find a usage of this tag, feel free to comment :)
