### ISSUE TITLE
Line numbers in bash code blocks

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#4770]
If I am not mistaken, we didn't have line numbers in bash code blocks before. At least, it looks really weird to me (see for example http://symfony.com/doc/current/book/installation.html#creating-the-symfony-application).

ping @javiereguiluz

**Comment by WouterJ** [comment]
Afaik, we always did have them.

**Comment by javiereguiluz** [comment]
Wouter is right. Those lines have been there forever. See an archive.org snapshot of 2013: https://web.archive.org/web/20130602073945/http://symfony.com/doc/current/book/installation.html

We can safely close this issue as *won't fix*.
