### ISSUE TITLE
Fix broken styling when using section inside section

### ISSUE THREAD

**Issue by ifdattic** [symfony/symfony-docs#4783]
On http://symfony.com/doc/current/book/forms.html#twig

![screen shot 2015-01-06 at 3 15 05 pm](https://cloud.githubusercontent.com/assets/966877/5629164/3bbcd782-95b9-11e4-890b-ef177d4b41da.png)

**Comment by javiereguiluz** [comment]
@ifdattic thanks for reporting this issue. To be completely honest, I don't really know what to do with this problem. The white background looks bad in this case, but looks right in all the rest of admonitions. Creating another set of icons for admonitions inside sidebars looks too much to me.

Are admonitions inside sidebars very common? If not, maybe the best solution would be to turn that admonition into a regular paragraph.

What do others think about this?

**Comment by ifdattic** [comment]
In my opinion the only "nice" solution if keeping the image would be to use CSS to create round white borders and making the current white background in the image transparent. I think someone who does more front end development would be able to provide more info.

I actually like and think in this case turning it into a simple paragraph is a good solution.

As for how common it's I will know in a month or two (depending on how much time I will have for reading documentation), but so far I think this is the only occurrence.

**Comment by javiereguiluz** [comment]
I've looked for in the docs and, at least for 2.3 branch, these nested admonitions are very rare. There are only these occurrences:

.. caution::
  book/forms.rst
  cookbook/web_server/built_in.rst

.. note::
  form/introduction.rst

.. tip::
  reference/constraints/Callback.rst

**Comment by xabbuh** [comment]
@javiereguiluz Is there a specific reason not to have a transparent background in the images?

**Comment by javiereguiluz** [comment]
@xabbuh in reality the image is semi-transparent. The white part is needed to create the rounded margin shown at the top left corner of the admonition boxes.

**Comment by xabbuh** [comment]
@javiereguiluz yes, makes sense

**Comment by WouterJ** [comment]
@javiereguiluz I've created something to make this possible: http://jsbin.com/rumerufusi/3/watch (I didn't use the image icons, you probably want to use that, but only the circle)

**Comment by ifdattic** [comment]
Noticed while using FF on smaller screen that first letter is partly hidden

![screen shot 2015-02-02 at 9 09 57 am](https://cloud.githubusercontent.com/assets/966877/6005311/1c670bfa-ab12-11e4-9a2c-bd7493a6505f.png)

**Comment by javiereguiluz** [comment]
It only took me a year ... but this is finally fixed. It will be available on symfony.com after the next deploy. I used @WouterJ's proposal to fix this.

### Before

![nested_before](https://cloud.githubusercontent.com/assets/73419/12167096/790af95c-b52a-11e5-8b64-fa9aa5d2eeab.png)

### After

![nested_after](https://cloud.githubusercontent.com/assets/73419/12167103/7c124e34-b52a-11e5-8480-2199c41e2e28.png)

---

We also took this opportunity to update icons a bit and make them vectorial. Besides, we added a new icon for "see also" which matches the style of the other icons:

### Before

![before_seealso](https://cloud.githubusercontent.com/assets/73419/12167129/9854a5a6-b52a-11e5-8dc4-c9cf233c41c0.png)

### After

![after_seealso](https://cloud.githubusercontent.com/assets/73419/12167131/9b32dfb8-b52a-11e5-9815-c945873a2df9.png)

**Comment by WouterJ** [comment]
Great changes, @javiereguiluz! The screenshots look very nice (especially the see also icon felt very strange before these changes).

**Comment by ifdattic** [comment]
The changes look great!

**Comment by javiereguiluz** [comment]
The changes have been deployed. If you agree with them, we can close this issue as fixed. Thanks!

**Comment by xabbuh** [comment]
:+1: Looks great! Thank you Javier!
