### ISSUE TITLE
[2.7] Validator API: 2.4 version is gone, configuring API version is deprecated

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4804]
See symfony/symfony#13338 (and there will be other work later, potentially to simplify further: https://github.com/symfony/symfony/pull/13338#issuecomment-69344601).

At the very least, I believe in 2.7, 2.5-bc will be available to all users, since the PHP minimum version has been bumped.

**Comment by xabbuh** [comment]
part of this will be covered with #4807

**Comment by WouterJ** [comment]
Ref #4094

**Comment by weaverryan** [comment]
See symfony/symfony#14016. The 2.4 validator API is removed in 2.7 AND the 2.5-bc mode (and the whole configurability of the API version) was deprecated.

**Comment by stof** [comment]
Actually, the 2.5-BC mode is the only way in 2.7 (i.e. having the new API and the BC layer available at the same time). The only reason for the 2.5-BC vs 2.5 (which is actually the 3.0 API) madness was because we wanted to avoid bumping the requirement to 5.3.9 in 2.5 (which actually was a mistake IMO)

**Comment by weaverryan** [comment]
@stof it certainly caused a lot of confusion :).

So now in 2.7, it functions like every other feature: it has a new way, and the old way exists, but is deprecated. Very simple.

**Comment by javiereguiluz** [comment]
I'm confused: is there anything left to do in the validator docs? Thanks!

**Comment by javiereguiluz** [comment]
I'm closing this as no longer relevant ... but if I'm wrong, please reopen ir. Thanks!
