### ISSUE TITLE
[Best Practices] weird link captions in cross references

### ISSUE THREAD

**Issue by dbu** [symfony/symfony-docs#4822]
The best practices articles have many places where a cross reference uses the full title of a cookbook entry or doc chapter, making for weird grammar: "If you need to execute some code before or after the execution of your controllers, you can use the EventDispatcher component to How to Setup before and after Filters." for example, http://symfony.com/doc/2.3/best_practices/controllers.html#pre-and-post-hooks

almost every section has one of those links. not harmful, but a bit confusing.

**Comment by javiereguiluz** [comment]
@dbu I agree that these cross references are pretty bad. Thanks for reporting it!

I'll take care of fixing this issue.

**Comment by WouterJ** [comment]
I always prefer to use quotes when referencing articles: `If you need to execute some code before or after the execution of your controllers, you can use the EventDispatcher component to "How to Setup before and after Filters".` 

However, I know @weaverryan isn't a big fan of this

**Comment by xabbuh** [comment]
@WouterJ At least, imho you example doesn't read really better.
