### ISSUE TITLE
[Best Practices] find better twig extension example

### ISSUE THREAD

**Issue by dbu** [symfony/symfony-docs#4823]
http://symfony.com/doc/2.3/best_practices/templates.html uses a custom markdown twig extension as example. but there is https://github.com/KnpLabs/KnpMarkdownBundle (and probably 2 dozen other markdown bundles on packagist). while the example is simple, it is promoting to reinvent the wheel for such a thing. rather install an existing bundle for such a basic task than do your own.

**Comment by lyrixx** [comment]
I used to teach how to create a twig extension with an awesome sample ;)

```php
<?php

class RainbowExtension extends \Twig_Extension
{
    private static $rainbowColors = array(
        '#FF0000',
        '#FF7F00',
        '#FFFF00',
        '#00FF00',
        '#0000FF',
        '#4B0082',
        '#8F00FF',
    );

    public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter('rainbow', array($this, 'rainbow'), array('is_safe' => array('html'))),
        );
    }

    public function rainbow($string)
    {
        $output = '';
        foreach (preg_split('//u', $string) as $i => $char) {
            $output .= sprintf('<span style="color:%s">%s</span>', self::$rainbowColors[$i % 7], $char);
        }

        return $output;
    }

    public function getName()
    {
        return 'rainbow';
    }
}
```

**Comment by stof** [comment]
@lyrrix you are missing the escaping of the input string. Your awesome function will miss the escaping of ``<`` in the string for instance, breaking the HTML (it may be hard to use it for XSS though due to the way it wraps chars)

**Comment by lyrixx** [comment]
@stof good point ;) but modern browser works well with escaped `<` ;)

**Comment by stof** [comment]
@lyrixx the issue is that it might encourage people to mark their filters as safe when they are actually not (and with an internal logic which does not forbid using the missing escaping for XSS purposes)

**Comment by javiereguiluz** [comment]
@dbu you are right about being a not interesting example. But in the case of the Best Practices book, that's the point. We don't mind about what we do, but how we do it. We need extremely simple and trivial examples for everything we show. Complicating examples would be counterproductive for the purpose of the Best Practices book.

Let's see what does @weaverryan, coauthor of this book, think about this, but right now I think the best would be to close this issue as "won't fix".

**Comment by dbu** [comment]
i have nothing against a trivial example, i totally see why you need something that is as simple as possible. but i think taking markdown which has [more than a full page of results on packagist](https://packagist.org/search/?q=%2Bmarkdown%20%2Bbundle) gives the wrong idea. imho people should use existing bundles for such cases (in the end its never as simple as one thinks, and then we have the next NIH markdown bundle). in that sense, if we could fix the rainbow example (html encode the argument) it would seem the better example to me, its more clear that its just an example.

best practices btw could mention packagist and discuss when to use an existing bundle and when to do your own.

**Comment by weaverryan** [comment]
I don't have a preference, but I definitely see @dbu's point, which tells me that we should seek out another example. And personally, I kind of love the `RainbowExtension` - it's fun, and it's clear that *it* is not the "point". For me, +1 for our RainbowExtension.

**Comment by WouterJ** [comment]
:+1: for rainbow too.

**Comment by javiereguiluz** [comment]
I only have one problem the RainboxExtension example: it looks like a joke ... and that could damage the perception of the entire document.

I always prefer realistic examples, even when the actual example is not important and it's just a mean to explain something else. A Markdown extension is a usual requirement by thousands of developers, whereas a RainbowExtension is useless and no one will ever use or need something like that.

**Comment by xabbuh** [comment]
I tend to agree with @javiereguiluz here. The example doesn't seem like a real use case. More importantly, you would probably not write an extension for this, but the Twig `cycle()` function instead.

**Comment by dbu** [comment]
good point too, about not having kind of a joke example in the best practices. i guess the problem then is that any reasonable and simple extension probably already exists. so it could either be a more theoretical example with calling a acme.my_service doStuff() or we could simply add a note to say that markdown is for the sake of the example and you should really first go to packagist and see if something already exists. maybe we could link to cookbook/bundles/installation.rst for that.

if we can agree on one of those (theoretical example or note) i am happy to do a PR.

**Comment by weaverryan** [comment]
I like silly things. But I'm also just fine with a note - the upside of Markdown is that the problem we're solving is easily understandable. And a note would tell them that it's just serving as a simple illustration of things.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because the discussion stalled and no agreement was reached. Besides,  our resources are very limited, so let's focus first on completing all the missing docs and then we'll improve the existing docs. Thanks!

**Comment by dbu** [comment]
okay. i am still up to do the PR if rian or you have an opinion which would be the best solution.
