### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SofHad** [symfony/symfony-docs#4827]
The EmailSenderListener link is broken, because the api class does not exist.
on this page: http://symfony.com/doc/current/reference/dic_tags.html#kernel-terminate

**Comment by WouterJ** [comment]
Hmm, indeed. Swiftmailer is no longer part of core Symfony, so it's no longer rendered there. I'm +1 for removing the API link, but maybe we can link to the api docs of swiftmailer? /cc @fabpot

**Comment by stof** [comment]
I don't think the API docs of swiftmailer are rendered online, but you could link to the source on github
