### ISSUE TITLE
What do we define as the max line length for code blocks?

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#4858]
See https://github.com/symfony/symfony-docs/pull/4778#issuecomment-68770710

Since the website is now response, code blocks have no longer a fixed width and avoiding horizontal scrollbars isn't possible at any time. What should we keep as max line length rule for code blocks?

* Use the 85 character rule we're using already (but did not apply to the docs)
* Use 72 to be consistent with the text
* Use 95, the maximum amount of characters when the site reaches its max width
* Use somthing else

/cc @weaverryan @xabbuh

**Comment by javiereguiluz** [comment]
We can make the code listings responsive ... but only if we remove the line numbering.

**Comment by WouterJ** [comment]
@javiereguiluz I think you didn't understand me. The problem is that the width of the code block is no longer static, but variable (until a certain max-width). This means there is no way we can fully promise our "no horizontal scrollbars" statement. Now, we have to define until what length we're going to support this.

**Comment by weaverryan** [comment]
Hmm, I'm not sure :). Sure, I want to keep things from being too long (just like we do in real coding), but sometimes I don't care. For example, I'm not too concerned if a long XML namespace declaration goes long. But if I had to choose, I'd say we keep things under 85 - but not worry about some less-important edge-cases. On average then, since we'd be keeping things under 85, that would probably make most long lines be 80 or less.

**Comment by weaverryan** [comment]
Btw, I'm pretty happy with how the site looks on mobile - I was just playing around with it :)

**Comment by ifdattic** [comment]
I personally have my editor set up to display two vertical lines at 80 and another at 120 symbols. From that I noticed 80 looks about the right choice. With code blocks being intended by 4 symbols the 80 line about where you reach the right side of the code block.

**Comment by WouterJ** [comment]
I think we can agree that there is a not-so-strict line length of 85 characters for code blocks. Someone has to add this to the documentation standards (`/contributing/documentation/standards`)

**Comment by anacicconi** [comment]
It's already defined on line 60 of https://github.com/symfony/symfony-docs/edit/2.7/contributing/documentation/standards.rst

**Comment by xabbuh** [comment]
Indeed, good catch @anacicconi!

@WouterJ @weaverryan I suggest to just close here then. What do you think?

**Comment by weaverryan** [comment]
Agreed on the standard and that the standard is documented. Thanks point @anacicconi for pointing that out - it's nice to close issues :)
