### ISSUE TITLE
Sticky Locale based on User Entity

### ISSUE THREAD

**Issue by peterrehm** [symfony/symfony-docs#4862]
I think it is a common requirement that you want to define your locale based on
a database value. E.g. the locale property of the user entity.

There is no direct way to access the user in the LocaleListener hence it is registered
before the FirewallListener and so no token exists. 

How about an additional chapter explaining how to achieve this adding a listener to
the security.interactive_login event and storing the locale in this step?

If this is wanted I might find the time for a draft.

**Comment by xabbuh** [comment]
I would be :+1: on this.

**Comment by WouterJ** [comment]
I think it's a perfect topic for the cookbook (the Translation section). :+1:

**Comment by peterrehm** [comment]
I added it as chapter to the existing entry about the sticky locale session.
