### ISSUE TITLE
Add DoctrineBundle to the /bundles section

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4863]
See https://github.com/symfony/symfony-docs/pull/4719#issuecomment-68607811

We'd like to put DoctrineBundle into this section so that it's rendered nicely. Then, we can link to *its* reference section, instead of maintaining our own (which is a duplicate). @javiereguiluz what do you think?

**Comment by stof** [comment]
The reference in the DoctrineBundle repo is now uptodate.

**Comment by javiereguiluz** [comment]
I was about to integrate DoctrineBundle into symfony.com, but I ran into some RST issues. I'm trying to fix them here: https://github.com/doctrine/DoctrineBundle/pull/377

**Comment by xabbuh** [comment]
[It's there](http://symfony.com/doc/master/bundles/DoctrineBundle/index.html). Thanks!
