### ISSUE TITLE
The current version of the documentation recommends the use of Validation Groups for forms

### ISSUE THREAD

**Issue by DudeNamedBen** [symfony/symfony-docs#4888]
The current version of the documentation recommends the the use of Validation Groups, even though they have been deprecated. Is there any alternative to using the setDefaultOptions method in the new version of symfony? Or will you have to construct the OptionsResolver manually and filter the configuration array with that?

http://symfony.com/doc/current/book/forms.html#validation-groups

**Comment by WouterJ** [comment]
There is nothing wrong with validation groups. And `setDefaultOptions` is deprecated and replaced by `configureOptions` in 2.7. `setDefaultOptions` is not deprecated in Symfony 2.6, so the current version docs should still use `setDefaultOptions`.

There is already a PR to update the 2.7 docs to use configureOptions: https://github.com/symfony/symfony-docs/pull/4786

**Comment by DudeNamedBen** [comment]
Oh yeah, you are right sorry.
