### ISSUE TITLE
[2.6] bootstrap form themes and form_label with checkbox

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4906]
We should note that `form_label` should not be used on checkbox fields - it renders nothing - symfony/symfony#13501

**Comment by weaverryan** [comment]
Bah, nevermind, this is already included - I was looking on the wrong branch :). I'll update the issue to *just* be about `form_label`.

**Comment by stof** [comment]
You should not that this depends on the theme (the default theme does not render the label inside the widget. Only the bootstrap theme does)
