### ISSUE TITLE
Pagoda Box deployment

### ISSUE THREAD

**Issue by EmanueleMinotto** [symfony/symfony-docs#4910]
[Pagoda Box](https://pagodabox.io/docs/) has a new system of deployment and it is not easy start using it with Symfony 2.

Could be a good idea start a subsection in the Cookbook? Under the [Recipes about Deployment](http://symfony.com/doc/current/cookbook/deployment/index.html) a subsection for them, like those already wrote for Microsoft Azure Website Cloud, Heroku Cloud and Platform.sh.

**Comment by Tolmark12** [comment]
+1

**Comment by timglabisch** [comment]
:-1: i would like to start to reference external documentations. the maintenance shouldn't be up to the documentation team.

**Comment by javiereguiluz** [comment]
I'm closing this because we only add deployment articles for very popular services and I'm not sure Paboda Box fits in that category (by the way, their blog and Twitter account haven't published anything in more than a year).
