### ISSUE TITLE
Symfony website - transparent header due to blocked scripts

### ISSUE THREAD

**Issue by ifdattic** [symfony/symfony-docs#4912]
If I open the Symfony website (http://symfony.com/doc/current/book/templating.html) one of script fails with 502 status code and leaves the top header transparent.

![screen shot 2015-01-24 at 2 59 55 pm](https://cloud.githubusercontent.com/assets/966877/5887461/88a2f08e-a3da-11e4-870d-8da16b669b9b.png)

**Comment by javiereguiluz** [comment]
The top black bar is served by SensioLabsConnect service, which is not related to symfony.com. Sadly, sometimes this bar doesn't load or loads very slowly. I don't really know what can we do to solve this issue from the symfony.com point of view.

**Comment by ifdattic** [comment]
My thinking (depends on how the website is implemented) was maybe having that block as 0 height (CSS) and after it's loaded a callback adds a class making it the correct size (or something along those lines).

It's not really a big deal, but sometimes it looks strange when the top part is transparent (or maybe add the background or something to it).

**Comment by javiereguiluz** [comment]
I'm glad to say that this issue is fixed. We now always display a black toolbar at the top, even when JavaScript is blocked.

**Comment by WouterJ** [comment]
:+1: Good job!
