### ISSUE TITLE
Route with nested placeholders

### ISSUE THREAD

**Issue by timglabisch** [symfony/symfony-docs#4913]
i stumbled around the support for nested placeholders while reading the router tests.
take a look at: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/Tests/RouteCompilerTest.php#L124

i am not sure about if this is really useful and why symfony should support this - but it does. So we should document this "feature"?

**Comment by WouterJ** [comment]
Can we come up with a good use-case? I'm against documenting it if we can't find a use of it. If we can find a use case, we can add a small sentence to it like "You can also nest placeholders, for instance when you want ..."

**Comment by WouterJ** [comment]
Hmm, looked a bit better and I understand now that when nesting, only the inner placeholder is used. Afaik, `{` is forbidden in URLs? Is there any reason why someone would want to do this?

I'm now even more -1 on documenting this.

**Comment by javiereguiluz** [comment]
I agree with @WouterJ. Documenting this feature would produce no real benefit for end users.

**Comment by xabbuh** [comment]
I agree. So I'm going to close this.

@timglabisch If you can come up with a valid use case we can still reopen here though.
