### ISSUE TITLE
Form parent class must be AbstractType

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#4923]
[This section](http://symfony.com/doc/current/book/forms.html#creating-form-classes) of the documentation could tell that the parent [must always be](https://github.com/symfony/symfony/issues/13490#issuecomment-71468518) `AbstractType`

**Comment by WouterJ** [comment]
This is not true. However, there is a big difference between the Form hierarchy and the PHP inheritance. Using both does not work. We may should add that into details to a cookbook article.

**Comment by flip111** [comment]
If it's not true then that means that sometimes you can use PHP inheritance and sometimes not. Can we make a list of situations where it's good to use it and where not good to use it?

**Comment by stof** [comment]
Well, you could use PHP inheritance if you don't use the form type hierarchy, but I don't see any use case for that. You would loose some features without gaining any AFAIK.

**Comment by WouterJ** [comment]
@stof but we can't say that we should force extending AbstractType. Take the button groups for example. Each type need to implement FormTypeInterface, that's the only requirement.

However, it extending a type (for instance ChoiceType) and setting `choice` as parent in the form hierarchy leads to unexpected behaviour (at least, if you don't understand what's going on internally).

So maybe we should add cookbook article (if we haven't already) about creating a form type. In it, we will just show how create form types without any inheritance stuff. However, in a last section of the article, we will explain the Form inheritance system.

**Comment by stof** [comment]
@WouterJ the rule is that you should probably never extend an existing form type class. Then, you can either extend AbstractType or reimplement the whole interface yourselves (even though I don't think about any reason for this).

**Comment by WouterJ** [comment]
I propose to create a new cookbook recipe in `cookbook/form` that talks about the Form inheritance model, as many are confused by it. This should also explicitely warn users to not extend form types using PHP.

**Comment by flip111** [comment]
:+1:

**Comment by iltar** [comment]
Seems like this information is still missing. Should consider if virtual inheritance still the way to go.

**Comment by stof** [comment]
well, using PHP inheritance allows you to reuse the logic in the form type. But it does not make the Form component aware of a hierarchy between these types, and so the theming layer will consider them as totally unrelated (and type extensions too). So yes, the type hierarchy is still relevant.
