### ISSUE TITLE
Cookbook Model Classes for several Doctrine Implementations

### ISSUE THREAD

**Issue by velikanov** [symfony/symfony-docs#4927]
I found this chapter extremely important for all Reusable Bundles maintainers
But also I found it completely useless for beginners :(

Here is my issue:
I'm trying to follow best practices in case of data storing, so I want to use the multi-manager Model pattern instead of hardly defined Entity or Document.
So, I extended the "build" function with the example showed… and what's the next step?
The next step is XML mapping generation - it's absent in the docs
Okay, we did make XML mapping file, but what's the next step?
I don't know, I'm stuck here.
I tried thousand ways to populate my model, but it just don't see it.
`./app/console doctrine:mapping:info` - no my Model there.
`doctrine:scheme:update`, `migration:` and so on - no luck at all…
What must I do to make a Model and force it to work?
I don't know.
Please, if anyone understands how this should work - update the docs with full practical example.
Now it just passes us to FosUserBundle (2.3) and CmfRoutingBundle source code - are you serious?
I find it completely useless for now.
Thank you.

The test project lies here: https://github.com/velikanov/model-test-2.6
The Bundle definition: https://github.com/velikanov/model-test-2.6/blob/master/src/AppBundle/AppBundle.php
The model mapping XML: https://github.com/velikanov/model-test-2.6/blob/master/src/AppBundle/Resources/config/doctrine/model/Test.orm.xml
The model itself: https://github.com/velikanov/model-test-2.6/blob/master/src/AppBundle/Model/Test.php

**Comment by velikanov** [comment]
I can update this chapter
But I can do it just when I'll understand how to deal with it

**Comment by velikanov** [comment]
Finally, I got it
The docs needs to be updated with:
0. The link to XML Mappings in Doctrine docs
1. Setting the parameter (in code) like ```$container->setParameter(…);```
2.1. Updating doctrine-bundle
2.2. Updating doctrine-orm

**Comment by javiereguiluz** [comment]
Not sure if this old issue is still relevant ... In any case, I'd like to not add more docs of third-party tools and services (like Doctrine in this case). We've recently removed some of this doc related to third-part docs, so we'll need to be careful here.

**Comment by javiereguiluz** [comment]
Closing because of the lack of feedback and because docs probably were improved since this issue was opened originally. Thanks!
