### ISSUE TITLE
@ character not shown as is

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#4942]
In headlines and in the page title, the `@` character is not shown as is, but is displayed as `&#64;` instead (see http://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/annotations/routing.html for example).

**Comment by WouterJ** [comment]
It seems to be only wrong in HTML title and the page headline, the breadcrumbs show the correct version.

/cc @javiereguiluz

**Comment by javiereguiluz** [comment]
Thanks for reporting this error. It's now fixed and it will be online after the next website deploy.

**Comment by javiereguiluz** [comment]
The fix for this problem is now deployed, so we can close this issue. Thanks.

**Comment by xabbuh** [comment]
Thank you @javiereguiluz!
