### ISSUE TITLE
Make it more clear that form names need to be unique

### ISSUE THREAD

**Issue by jakzal** [symfony/symfony-docs#4960]
Currently, [the docs say](http://symfony.com/doc/current/book/forms.html#creating-form-classes): 

> This new class contains all the directions needed to create the task form (note that the getName() method should return a unique identifier for this form "type"). 

I propose it's made more visible the name should be unique. It's no where verified, and might lead to unexpected problems (like https://github.com/symfony/symfony/issues/13590).

**Comment by javiereguiluz** [comment]
Do you really think that this is a documentation problem? I think that obscure problems like this should be reported using an exception thrown by the Form component.

**Comment by jakzal** [comment]
I don't think it's trivial to solve in the code (ping @webmozart). 

I agree it's not really user friendly at the moment. However, even if we solved it in the code, this is an important detail, which should be highlighted in the docs in my opinion.

**Comment by WouterJ** [comment]
It's already highlighted: "should return a unique identifier"

I don't think we can solve it better. Instead, I agree with @javiereguiluz, the code should have some validation for it to also help people who don't read the docs.

**Comment by jakzal** [comment]
@WouterJ it's not highlighted. It doesn't stand out visually ;)

**Comment by Nek-** [comment]
:+1: i notice beginners like make many types that have same names. More than that, they name them like sf types.

**Comment by stof** [comment]
@WouterJ allowing to overwrite a form type by registering a type again with this name is actually a feature.

**Comment by WouterJ** [comment]
Closing as #5076 added a caution, which is the most clear way of warning the user in the docs.
