### ISSUE TITLE
Incorrect documentation for caching

### ISSUE THREAD

**Issue by Elendev** [symfony/symfony-docs#4970]
The last example of the Expression language caching section (https://github.com/symfony/symfony-docs/blob/2.6/components/expression_language/caching.rst) doesn't work : 
```php
$expression = new SerializedParsedExpression(
        serialize($language->parse('1 + 4', array()))
    );
```
The ``SerializedParsedExpression`` constructor requires a ``$nodes`` parameters.
I'm not really sure on how to do it the right way.

**Comment by stof** [comment]
The first argument should be the expression itself, which is missing here. I sent a PR fixing it

**Comment by Elendev** [comment]
So, if I understand correctly : if I want to optimize an expression evaluation by serializing it, for example in database, I have to keep both the serialized parsed expression and the expression to be able to use it with `SerializedParsedExpression` ?

**Comment by stof** [comment]
@Elendev yes, because the expression object must be able to give the original expression when being casted as string.

**Comment by Elendev** [comment]
@stof ok I understand, thank you for the explanation
