### ISSUE TITLE
Document available routing types

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#4973]
We seem to have no documentation on the available routing loader types that you configure when loading a resource in `app/config/routing.yml`. Nor do we document how Symfony determines the loader when no type is used and what the benefit of the type setting is. I've seem a couple of people asking for such docs the last weeks.

I think this can be added to `book/routing` directly in the ["Including External Routing Resources"](http://symfony.com/doc/current/book/routing.html#including-external-routing-resources) section.

**Available loaders**: yaml, php, xml, annotation (if SensioFrameworkExtraBundle is registered)

**How loaders are choosen**
When no type is configured, it's based on the extension. The first matching loader will be used. When a type is configured, both extension and type are taken into account. For instance, a file `custom_routing.yml` with type `yaml` will be loaded by the yaml loader, while a `custom_routing.php` with type `yaml` will not be loaded, as no loader matches both the `.php` extension and the `yaml` type.

**The benefit of the type setting**
Types allow you to use different loaders for the same extension, for instance a `.php` extension can be loaded by both the PHP and the annotation loader. Using the type `annotation` will make sure it's loaded by the annotation loader.

/refs https://github.com/symfony/symfony/issues/13623

**Comment by FusionDev-OpenSource** [comment]
Please add accepted configuration parameters for Routing component. (section You like to know full list of configuration options)

**Comment by WouterJ** [comment]
What more do you expect to be documented?

**Comment by FusionDev-OpenSource** [comment]
I just dont know if there are more config options available for Routing. Im new to symfony, but im curious. Thanks

**Comment by WouterJ** [comment]
You can only configure routes or import resources. Both are explained in detail in the Routing book article, the type details were the only things missing.

There are some global configuration settings for the routing component which are documented in the FrameworkBundle configuration reference.

**Comment by FusionDev-OpenSource** [comment]
You mean this? http://symfony.com/doc/current/reference/configuration/framework.html

Yes the global config are the ones I didnt find.

**Comment by WouterJ** [comment]
Ah, in that case: They'll be added to that article very soon. We've rewritten the complete FrameworkBundle config reference to document every available config option: #4736

**Comment by LS05** [comment]
What's the status of this issue? 
Would like to solve it. Any suggestions?
Thank you :)

**Comment by osavchenko** [comment]
But you can find all information about formats in the doc:
[Creating routes](https://symfony.com/doc/current/routing.html#creating-routes) - about different formats and how to use annotations and [External resources](https://symfony.com/doc/current/routing/external_resources.html) with additional information.

**Comment by wouterj** [comment]
During the EU-FOSSA hackathon, we did look into this and turns out indeed everything is covered well in the documentation (as indicated by @osavchenko). So we can close this! :tada:
