### ISSUE TITLE
2.5 docs do not have the unmaintained caution yet

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#4975]
2.5 is unmainted as of February 1st, but the docs do not yet show the unmaintained caution.

I'm not sure how it's implemented, but maybe it's a good idea to rely on http://symfony.com/roadmap.json?version=2.5?

/cc @javiereguiluz

**Comment by javiereguiluz** [comment]
2.5 is no longer supported for fixes. but it's supported until July 2015 for security fixes. Should we deprecate it before the end of security fixes?

**Comment by WouterJ** [comment]
@javiereguiluz we stop merging into a branch at the same moment as the code does. So we stop supporting a version as soon as it reaches eom.

**Comment by javiereguiluz** [comment]
I've just deprecated the 2.5 version on symfony.com. The change will be online soon after the usual review/merge/deploy process.
