### ISSUE TITLE
[Suggestion] Move the SwiftmailerBundle and MonologBundle docs to the bundle repos

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#4983]
Given that these bundles are versionned independently of Symfony, having their doc in the symfony-docs repo makes it hard to handle version changes (new features in these bundles can be used in any version of Symfony as soon as you update the bundle, because they both support Symfony 2.3+ in their latest version).
The doc for these bundles should then of course be rendered on symfony.com

What do you think @WouterJ @weaverryan @xabbuh ?

**Comment by WouterJ** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1: Sounds like a reasonable change to me (we already have the same for other bundles that are closely related to Symfony).

**Comment by weaverryan** [comment]
I wrote a big note that I was -1 on this, then changed it. My biggest issues is that these other repositories have less attention on them, so I'm afraid the docs would suffer because of that.

**Comment by WouterJ** [comment]
@weaverryan looking at the activity for the monolog docs, I don't think it recieves much attention here too

**Comment by weaverryan** [comment]
Ok, :+1: from me - let's try it. Steps:

1) Get *something* bootstrapped for the docs for each
2) Get them rendered on the site
3) Move the docs over to the bundle and replace the existing entries with external links.

We still need to make the docs feel integrated - so I'd still want them to show up in the cookbook, for example, it would just take you into their docs.

**Comment by WouterJ** [comment]
MonologBundle
---

* [ ] **[easy pick]** Create a `Resources/doc/index.rst` file in the bundle
* [ ] **[easy pick]** Add an installation chapter in the bundle following the [standard template](http://symfony.com/doc/current/cookbook/bundles/best_practices.html#installation-instructions)
* [ ] Start adding (+ rewriting) the [monolog chapters](http://symfony.com/doc/current/cookbook/logging/index.html) to the bundle documentation
* [ ] **[to be done by @javiereguiluz]** Add the bundle to the site
* [ ] **[easy pick]** Remove the duplicated docs from the Symfony documentation + add some redirects to the new URLs

SwiftmailerBundle
---

* [ ] **[easy pick]** Create a `Resources/doc/index.rst` file in the bundle
* [ ] **[easy pick]** Add an installation chapter in the bundle following the [standard template](http://symfony.com/doc/current/cookbook/bundles/best_practices.html#installation-instructions)
* [ ] Start adding (+ rewriting) the [swiftmailer chapters](http://symfony.com/doc/current/cookbook/email/index.html) to the bundle documentation
* [ ] **[to be done by @javiereguiluz]** Add the bundle to the site
* [ ] **[easy pick]** Remove the duplicated docs from the Symfony documentation + add some redirects to the new URLs

**Comment by xabbuh** [comment]
@snoek09 started this for the SwiftmailerBundle in symfony/SwiftmailerBundle#102.

**Comment by javiereguiluz** [comment]
Closing this old issue as done. We've already moved some doc to those external repos, but we can't move the essential docs about logging and mailer out of the main Symfony Docs. So we've finished here. Thanks!
