### ISSUE TITLE
Links to the Table Helper API are broken

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#4986]
On the [*Table Helper* page](http://symfony.com/doc/master/components/console/helpers/tablehelper.html), in the [*Customize Table Layout using Rendering Options* part](http://symfony.com/doc/master/components/console/helpers/tablehelper.html#customize-table-layout-using-rendering-options), the links don't work:

 * [2.3](http://symfony.com/doc/2.3/components/console/helpers/tablehelper.html#customize-table-layout-using-rendering-options)
 * [master](http://symfony.com/doc/master/components/console/helpers/tablehelper.html#customize-table-layout-using-rendering-options)

The anchors are wrong, for example the link to the `setPaddingChar()` method should be [`[...].html#method_setPaddingChar`](http://api.symfony.com/master/Symfony/Component/Console/Helper/TableHelper.html#method_setPaddingChar) instead of [`[...].html#setPaddingChar()`](http://api.symfony.com/master/Symfony/Component/Console/Helper/TableHelper.html#setPaddingChar%28%29)

**Comment by stof** [comment]
duplicate of https://github.com/symfony/symfony-docs/issues/2156

**Comment by alexislefebvre** [comment]
Ok. I close this.
