### ISSUE TITLE
Document the new auto_alias tag in the serive container in 2.7

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#4992]
From symfony/symfony#12526

Docs is mostly here https://github.com/symfony/symfony/issues/11460#issuecomment-58690219

**Comment by WouterJ** [comment]
This at least has to be documented in `reference/dic_tags`. Besides that, it may even deserve a cookbook recipe

**Comment by javiereguiluz** [comment]
For reference purposes, here it is the (brief) blog post explaining this new feature: http://symfony.com/blog/new-in-symfony-2-7-dependency-injection-improvements#added-an-auto-alias-compiler-pass
