### ISSUE TITLE
transchoice typos

### ISSUE THREAD

**Issue by duncancumming** [symfony/symfony-docs#4994]
You have the following:

    {% transchoice count %}
        {0} There are no apples|{1} There is one apple|]1,Inf] There are %count% apples
    {% endtranschoice %}

and:

    {% transchoice count with {'%name%': 'Fabien'} from "app" %}
        {0} %name%, there are no apples|{1} %name%, there is one apple|]1,Inf] %name%, there are %count% apples
    {% endtranschoice %}

and:

    <?php echo $view['translator']->transChoice(
        '{0} There are no apples|{1} There is one apple|]1,Inf[ There are %count% apples',
        10,
        array('%count%' => 10)
    ) ?>

I assume each one has a syntax error for the >1 range, and they should all be
`[1,Inf]`

**Comment by WouterJ** [comment]
Your explanation is correct, as it equals the syntax used in the examples. The syntax you propose (`[1,Inf]`) is not correct. But don't worry, we get lots of questions about this.

`[1,Inf]` means >=1
`]1,Inf]` means >1

There is however an inconsistency between the first 2 and the last example. I would prefer if we changed everything to the syntax of the last example, as that's the only valid set (Inf is not a number and cannot be part of a set, strictly spoken). It might also avoid confusion about non-existing typos.
