### ISSUE TITLE
Add article about creating a console application

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#4997]
The Symfony Console component has a pretty nice API for creating a simple console application in a single file. However, it's not document anywhere. See http://www.hackdenver.com/blog/how-to-build-a-command-line-app-in-php for an example.

I think we should add an article to `components/console` about using this API.

**Comment by luciantugui** [comment]
@WouterJ [console component](http://symfony.com/doc/current/components/console/introduction.html), [single command application](http://symfony.com/doc/current/components/console/single_command_tool.html)

**Comment by WouterJ** [comment]
@luciantugui both don't tell the nice API as shown in the article I linked.

**Comment by WouterJ** [comment]
For the record, this syntax:

```php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

// Create the application
$console = new Application('My App', '1.0');

// Register a new command
$console
    ->register('greet')
    ->setDescription('Greet someone')
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $output->writeln('Hello');
    });

// Run the application
$console->run();
```

**Comment by javiereguiluz** [comment]
Closing this as "fixed" because the article https://symfony.com/doc/current/components/console/single_command_tool.html is enough to explain how to create a full Symfony console app in a single app. Thanks!
