### ISSUE TITLE
'Custom' exception overriden when using PreAuthentication

### ISSUE THREAD

**Issue by Silverspur** [symfony/symfony-docs#4998]
I'm following the [How to Authenticate Users with API Keys](http://symfony.com/doc/current/cookbook/security/api_key_authentication.html) tutorial.

When I'm giving a correct API key, everything works well. On the other hand, when the API key is either incorrect or missing, the code is supposed to throw an exception (for instance `BadCredentialsException` in the first case). However, this exception seems to be overriden and the final request response is an `AuthenticationCredentialsNotFoundException` thrown by Symfony `AccessListener.php`.
In the logs, I read this message:

```
Authentication exception occurred; redirecting to authentication entry point (A Token was not found in the SecurityContext.)
```

This lets me think that the exception thrown in the PreAuthenticator is somehow discarded and the security mecanism only complains a step further that it can find no Token (which is indeed normal given the incorrect API key provided).

If this is the expected behaviour (which I'd found sad) there is no point in proposing a PreAuthenticator that uses exceptions in the doc...

**Comment by only-style** [comment]
You solved this problem? I also get this error..

**Comment by Silverspur** [comment]
Unfortunately, no...

**Comment by WouterJ** [comment]
The exception is indeed [catched by the `SimplePreAuthenticationListener`](https://github.com/symfony/Security/blob/8787e41ac6d0bc2dda6ff8aede0de30dc020f6fb/Http/Firewall/SimplePreAuthenticationListener.php#L83-L99). This one logs the thrown exception and resets the token to `null`.

Optionally, it'll use the simple pre-authenticator to handle the exception if it implements the `AuthenticationFailureHandlerInterface`.

If the token is null, [the `AccessListener` throws a new exception](https://github.com/symfony/Security/blob/master/Http/Firewall/AccessListener.php#L52-L54).

So, I believe throwing an exception in the simple pre-authenticator *is* usefull, it lets you handle the exception in a nice way. Maybe, we should implement the `AuthenticationFailureHandlerInterface` in the simple pre-authenticator to show how to handle such an exception.

**Comment by javiereguiluz** [comment]
Closing because we've updated this article to use Guard and because Symfony has removed `SimplePreAuthenticationListener` in 5.0 so it doesn't make sense to keep mentioning it in the docs. See https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/CHANGELOG.md#500 Thanks!
