### ISSUE TITLE
new installer and gitignore

### ISSUE THREAD

**Issue by jubalh** [symfony/symfony-docs#5025]
http://symfony.com/doc/current/book/installation.html
States:
"If you're using a version control system like Git, you can safely commit all your project's code. The reason is that Symfony applications already contain a .gitignore file specially prepared for Symfony."

It seems this is not the case when using the new recommended symphony installer instead of composer.

Shouldn't it get added to the zip? Otherwise I will create a PR for documentation, so users can be aware.

**Comment by javiereguiluz** [comment]
@jubalh thanks for reporting this error.

You are right ... but not for long ;)  The latest version of the Symfony Installer already creates the `.gitignore` file and removes everything related to Symfony Standard Edition (see https://github.com/symfony/symfony-installer/commit/ed84f7abbcd4fa1865112f71c011e728fca34e22).

However, this feature is not available in the latest Symfony Installer version published as a PHAR and that you can get with the `symfony self-update` command. Fabien (@fabpot) needs to tag first a new version of the installer and publish it. So we'll have this feature very soon.

**Comment by jubalh** [comment]
@javiereguiluz I see. Good to know :-)
So not mentioning in docu since quicker resolved than adding the hint?

**Comment by WouterJ** [comment]
Yes, I don't think it'll make sense to document this and remove it again in some weeks.

**Comment by jubalh** [comment]
Okay, good with me :-)

Just thought maybe others out there just assume the gitignore to be there and happily use "add ." and commit like I did, and wanted to help them not to make the same mistake :-)

You can close this issue then.

**Comment by javiereguiluz** [comment]
The new version of the Symfony Installer has been published and this is no longer an issue. I think we can safely close this issue. @jubalh thanks for reporting this problem in the first place.

**Comment by xabbuh** [comment]
Indeed, I'm going to close here now. Thanks @jubalh for reporting the issue and thanks @javiereguiluz for fixing it.
