### ISSUE TITLE
Redirections per branch are broken

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5045]
Following a discussion with @weaverryan in https://github.com/symfony/symfony-docs/pull/4947#issuecomment-75695312 I checked for a working example of different `redirection_map` entries. However, this does seem to be broken currently. You can check this when trying to visit the [Filesystem component docs](http://symfony.com/doc/2.3/components/filesystem.html) for the `2.3` branch. You are redirected to http://symfony.com/doc/2.3/components/filesystem/introduction.html which only exists since Symfony 2.6.

ping @javiereguiluz @fabpot

**Comment by fabpot** [comment]
AFAIK, the redirection map has never been version aware.

**Comment by xabbuh** [comment]
@fabpot Hm, following the discussion in #4341 starting with https://github.com/symfony/symfony-docs/issues/4341#issuecomment-62682734 I think that this used to work recently.

**Comment by stof** [comment]
@fabpot any change to make them version aware ?

**Comment by WouterJ** [comment]
ping @javiereguiluz @fabpot

**Comment by javiereguiluz** [comment]
We can close this as "fixed" because we now use a different `redirection_map` per version. Thanks.
