### ISSUE TITLE
No PDF generated for Symfony CMF Bundles, Components, Cookbook

### ISSUE THREAD

**Issue by jdespatis** [symfony/symfony-docs#5048]
There's a strange thing on http://symfony.com/doc/master/cmf/index.html,
There's only one PDF for the 3 sections Quick Tour, Book Tutorial

But no PDF for the sections Bundles, Components, Cookbook
=> It would be nice to generate a big full pdf for all those 6 sections in one single file!

PDF is really nice for reading in offline mode

**Comment by dbu** [comment]
@javiereguiluz i think you manage that part, right? do you see something we do wrong in our .rst code?

**Comment by stof** [comment]
having a single huge PDF is probably a pain because each bundle and the CMF docs are rendered totally separately (and with independent versions, making it a nightmare to select the content of the PDF).
However,  it might be possible to build separate PDFs for them (it probably requires updates to the build process)

**Comment by WouterJ** [comment]
@stof what @jdespatis was the Bundles section inside the CMF docs

**Comment by jdespatis** [comment]
@WouterJ indeed, I was speaking globally about those 3 sections not generated
The very useful parts are the components and the cookbook for Symphony CMF indeed

The bundles section would be nice to have in PDF
I've forgotten the section Contributing. May be nice also to have in PDF?

If it's just a question of configuration of the build process to have a pdf for every section, then why not doing it ?
(I don't know at all how this build works indeed)

The fact is I love reading a 500 pages PDF :)

**Comment by javiereguiluz** [comment]
I'm closing this issue in favor of the meta-issue related to PDF problems: #7030. Hopefully soon we'll work on fixing those errors.
