### ISSUE TITLE
Custom validation constraint have a different behavior with arrays

### ISSUE THREAD

**Issue by xavismeh** [symfony/symfony-docs#5049]
When using custom validation with an array, the workflow is slightly different from the one described on http://symfony.com/doc/current/cookbook/validation/custom_constraint.html and it should be fixed in here as told by @stof on https://twitter.com/Stof70/status/571278956973977600
I could write it by myself however I don't really know how to organize it ... On the existing page ? On a new one ?
Let me know !

**Comment by stof** [comment]
The workflow is not different at all. What is different is that the property path is different for object properties and array elements.
What should be improved is probably the explanation about how property paths are working.

**Comment by xabbuh** [comment]
I might be overlooking something, but where on that page do we talk about property paths at all?

**Comment by stof** [comment]
well, we show an example using ``atPath()``, which expects a property path as argument. But the issue is probably than we indeed do not explain how property paths are working.

**Comment by xabbuh** [comment]
Hm, that example is precisely about validating an object. So, we should either think about another example or just add a short note about how the property path works.

**Comment by xavismeh** [comment]
That was the point of my question @xabbuh ;-) Which solution would be better ? A dedicated page or a "side note" on the existing one ?
To me, the second solution seems better as the page is named "How to Create a custom Validation Constraint" and does not mention objects. Feedbacks appreciated !

**Comment by WouterJ** [comment]
There is already a page about property paths: http://symfony.com/doc/current/components/options_resolver.html

Maybe we can refactor the property path syntax to a new article in the options resolver component doc and link to it from a few places where we use property paths?

**Comment by stof** [comment]
@WouterJ your link is probably invalid. Property paths arepart of the PropertyAccess component, not of the OptionsResolver one

**Comment by WouterJ** [comment]
Ah, indeed. Fixed it

**Comment by xavismeh** [comment]
UP : I think this "issue" should be closed by now, shouldn't it ?

**Comment by WouterJ** [comment]
Unless I'm missing something, my comment (https://github.com/symfony/symfony-docs/issues/5049#issuecomment-76915529) still holds true. (my last comment was about fixing a misplaced link in that comment)
