### ISSUE TITLE
Documentation for the new PhpUnit bridge

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5059]
symfony/symfony#13398 introduced the new PhpUnitBridge that will ship with Symfony 2.7. I think we should at least write a bit about it in the testing section of the cookbook.

**Comment by WouterJ** [comment]
I'll try to take care of it (already started writing an article about preparing for sf3)

**Comment by stof** [comment]
This should be reopened. We should have a documentation page for the component itself, showing how to use it and describing its nice features (different modes, matching a single deprecation, etc...)

**Comment by xabbuh** [comment]
done with #5059
