### ISSUE TITLE
typo: Expection instead of Exception

### ISSUE THREAD

**Issue by ilstefano** [symfony/symfony-docs#5067]
hi,
there's a little typo within the charts on http://symfony.com/doc/current/components/http_kernel/introduction.html#the-kernel-view-event at the top-right corner: The 'event' triggering the 'Exception' entity is labeled 'Expection' instead of 'Exception'.

Yours
steffe

**Comment by xabbuh** [comment]
Thank you @ilstefano for reporting this bug. Really nice catch.

@weaverryan It seems like you committed the images initially. Do you still have the raw data and will be able to change the text?

**Comment by WouterJ** [comment]
@xabbuh the images are from @fabpot's slides iirc.

**Comment by weaverryan** [comment]
Yep, these are locked up in some old slides. I doubt Fabien still has the source, unfortunately. So, I guess we can keep this open, but there's no easy fix for now.

**Comment by xabbuh** [comment]
I tried to fix the images in #5108. Let me know what you think about it.

**Comment by weaverryan** [comment]
Ha, yep, Christian took care of it for us in #5108 :). You rock!
