### ISSUE TITLE
Update to recommend the built-in Serializer instead of JMSSerializer

### ISSUE THREAD

**Issue by dunglas** [symfony/symfony-docs#5069]
Follows symfony/symfony#13875

> @andreaslarssen The doc is in the process of being updated, see this PR for instance: https://github.com/symfony/symfony-docs/pull/4675/files
>
> JMSSerializer still have advanced features (especially regarding XML support) that are unlikely to be added in the Symfony built-in Serializer. However, most of the "must have" features have been added to the built in component including groups support, circular references handling, property name converter, normalization of objects having both publics properties and getters / setters...
>
> IMO, we can update the doc to explain how to use the built-in Serializer instead of recommending using JMS Serializer. Any help is welcome.

**Comment by javiereguiluz** [comment]
In #5074 I've removed the only explicit reference to JMS serializer that I've found in the documentation. And in #5075 I've removed a comment about a built-in serializer limitation which is no longer true for Symfony 2.6+.

**Comment by dunglas** [comment]
Thank you @javiereguiluz!

**Comment by dunglas** [comment]
Another related issue: #4698
