### ISSUE TITLE
Misuse of doctrine:generate:entities in documentation.

### ISSUE THREAD

**Issue by alex-ception** [symfony/symfony-docs#5070]
In the documentation, on the topic about generating getters and setters on entities, it's said to use doctrine:generate:entities MyEntity (http://symfony.com/doc/current/book/doctrine.html#generating-getters-and-setters)

However, according to an old issue on doctrine (https://github.com/doctrine/DoctrineBundle/issues/282), Ocramius answered (https://github.com/doctrine/DoctrineBundle/issues/282#issuecomment-56259385) that the goal of this command should not be used to generate getters and setters : 

Quote :
"@shideon yes, but we don't see real value in people running the generator over and over again. The generator is meant to be used to import legacy schemas, NOT to generate getters/setters and overwrite existing classes.

I realize that this is a crusade against a functionality that is useful to some people, but we really only had a lot of bugs and misuses coming from it, and that for customizations that should be applied post code-generation by the developer that is working on the project."

**Comment by javiereguiluz** [comment]
@alex-ception I don't think we should change this explanation. Even if @Ocramius comments are very reasonable, the truth is that everybody uses this command to generate the getters/setters of the entities. So I guess people don't mind about the original purpose of the command but its actual usefulness.

**Comment by Ocramius** [comment]
> but we really only had a lot of bugs and misuses coming from it

10000x this.

**Comment by alex-ception** [comment]
The fact is, it does not work using psr4 convention when used with composer auto loader. And since psr-4 is not planned to be supported by doctrine in this command, it will mislead users. At least a Warning on psr-4 should be added

**Comment by shideon** [comment]
+1 for @alex-ception's idea that a note should be added.

There's definitely a contradiction here too.

Symfony
> This is a safe command - you can run it over and over again

Doctrine
>  The generator is meant to be used to import legacy schemas, NOT to generate getters/setters and overwrite existing classes.

I was personally fine using the generator how I wanted but

**Comment by WouterJ** [comment]
+1 for removing the misusage from the documentation. It'll tell people a straight story: This command isn't created for the purpose most people use it for. As such, don't expect it to work.

Documentation is, sadly, often seen as the "official approach": If something is document, it's the way to go. We should make it very clear that it is not the case here. I think we can do that by removing the usage of the command (at least from the book chapter).

Thanks @alex-ception for opening this issue.
@Ocramius if you have more of these misusage in the Symfony documentation, I would like to learn more about it and see how we can improve those bits. :)

**Comment by javiereguiluz** [comment]
@WouterJ may I ask you which would be the alternative? It looks like we're saying users: please spend 15 minutes writting useless getters/setters because the authors of the command that do that for you  don't think that you should use it.

**Comment by Ocramius** [comment]
> please spend 15 minutes writting useless getters/setters

They should spend a couple of hours thinking about what they want *before* writing getters/setters (if that's even what they really want)

**Comment by snroki** [comment]
@alex-ception +1

@javiereguiluz any IDE can generate some getters/setters as well, you don't need to spend 15 minutes on it

**Comment by javiereguiluz** [comment]
Do you think we could propose to not add getters/setters and use public properties instead?

**Comment by Ocramius** [comment]
> Do you think we could propose to not add getters/setters and use public properties instead?

No, I propose that people stop treating their domain model as a multi-dimensional typed array ;-)

**Comment by alex-ception** [comment]
We should at least add in the documentation that using that command does not work with psr-4 and add a Warning about how the proper use of this command

**Comment by shideon** [comment]
[Relevant docs](http://doctrine-orm.readthedocs.org/en/latest/reference/tools.html#entity-generation)

**Comment by WouterJ** [comment]
@javiereguiluz for almost all of your classes, devs already create their getters and setters. I don't see why they can't do this for their entities. Most of them will use a IDE to not lose time writing them, or they don't care and use Vim :)

If they really don't like writing code, they could use `doctrine:generate:entity` to generate the complete entity code (class definition, getters, setters, properties, etc).

Why I think we shouldn't recommend misusing this command:

* Having to write them yourself makes you think about which getters/setters you actually need;
* We remove some confusion if the tool doesn't work as expected
* We remove some work load for the Doctrine guys, who are very busy, by not making people open bug reports of features that really shouldn't make it into Doctrine
* Using the command doesn't really bring a lot

**Comment by stof** [comment]
@WouterJ creating getters and setters for all classes is a mistake. For services, it is even worse than for entities (and it can create bugs when you make your dependencies mutable btw).

However, I agree with your reasons for not recommending the command.
