### ISSUE TITLE
New best-practice for Symfony Forms

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5077]
In #5076 we've reworded an important note as follows:

```
The ``getName()`` method returns the identifier of this form "type". These
identifiers must be unique in the application. Unless you want to override
a built-in type, they should be different from the default Symfony types
and from any type defined by a third-party bundle installed in you application.
Consider prefixing your types with ``app_`` to avoid identifier collisions.
```

Should we make the ``app_`` prefix recommendation a formal best practice?

* [x] A) Add a note to the best practices (#5093)
* [ ] B) Update usages within the documentation to have the `app_` prefix

**Comment by xabbuh** [comment]
Same question as in #5076: Should we use `app.` instead to be consistent with service name recommendations?

Besides that I like this idea. :+1:

**Comment by stof** [comment]
@xabbuh dots are forbidden in type names, so the answer is no

**Comment by weaverryan** [comment]
:+1:

**Comment by weaverryan** [comment]
I've just merged this in and updated the description to have a todo to add the `app_` prefix to all the existing form types on the docs.

**Comment by snoek09** [comment]
Part B is done so this can be closed, right?

**Comment by xabbuh** [comment]
You are right @snoek09.
