### ISSUE TITLE
Rewrite Blacklist Entry without Voters

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#5084]
This article http://symfony.com/doc/current/cookbook/security/voters.html needs to be rewritten using a simple event listener. Using a voter is awkward - see #4304 for the conversation.

**Comment by stof** [comment]
Well, this article is not about blacklisting entries but about explaining how to write voters (see the URL). So the proper fix would be to rewrite the chapter to use a better example

**Comment by weaverryan** [comment]
@stof But we have the other voter article now, which is much better: http://symfony.com/doc/current/cookbook/security/voters_data_permission.html. So perhaps the best option is to remove the blacklisting one entirely. A quick scan shows me that it doesn't add anything unique, except for the Access Decision Strategy part, which could be moved to the other one.
