### ISSUE TITLE
Service architecture intention

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#5089]
This post is made on the request of @xabbuh. The goal is to make clear what exactly the intention of the service container concept is in relation to the user's (programmers) application code (NOT the framework itself). And possible define a set of guidelines of which your application code must adhere to to be compatible with the architecture outline in the current service container documentation.

To keep it simple...this is what i have seen happening in my own application code as well as questions by other symfony users: People want to do something in their application code implentation (examples follow). This is not (easy) possible with the current service container. This post is not about wether the current architecture is good or not good. But simply to discus the different meaning of the implementation not fitting the architecture:
- Is the implementation inheriently bad -- an anti-pattern no matter in which architecture
- The implementation fits in with the service architecture (no conflict here)
- The implementation does not fit in with the architecture, but would not conflict (some parts of the app might be designed differently)
- The implementation does not fit in with the architecture, and also it would create conflicts when used anyway.
- The implemtation does fit in with the architecture, but the framework is missing features to support this case.

With conflict i don't mean exceptions or code crashing, rather issues like maintainebility / readibility of code.

Two examples
- Services in entities -- a popular stackoverflow answer suggest grabbing the container from global scope _if you really want to do it this way_
- unserializing objects with services -- i have not found any implementation that could do this at this point

Also read [this comment here](https://github.com/symfony/symfony/issues/12222#issuecomment-80789191) which describes some sentences of the documentation that are somewhat ambigious.

**Comment by javiereguiluz** [comment]
@flip111 thanks for opening this issue. To be honest, although you provide a lot of detailed information, I find your message not very *actionable*. Just to be clear: you are asking us to review any explanation or mention about the Symfony Dependency Injection Container and verify if it's correct or at least not ambiguous?

If my assumption is correct, it would be very useful if you could provide us a list of the contents to review. Thanks.

**Comment by flip111** [comment]
Well orignally i wanted to do stuff mentioned [in this issue](https://github.com/symfony/symfony/issues/12222) .. now i'm throwing stuff out here that i noticed. I hoped people would participate in a way so it that it will lead to a more actionable item. As of right now i'm struggling a litte bit but i will try to keep thinking about it because i feel it would be worth it. I don't have enough information to determine where to go next. Perhaps, like you say, it would be good to have a list of very concrete contents and maybe some questions about them?

`Put simply, a Service is any PHP object that performs some sort of "global" task.`
* what's a "global" task?
* what kind of other tasks are there? (examples)
* should other (non-global) tasks have no dependencies at all? Or should they be handled in another way then with DIC?

`The advantage of thinking about "services" is that you begin to think about separating each piece of functionality in your application into a series of services.`
Object orientated code / domain driven design. Often has objects that manipulate themselves. But they are NOT A SERVICE.
* What does the documentation mean with "functionality" ?
* Is the documentation saying here that each functionality should be in a service??

The article for the service container links to wikipedia as more background information
`A service-oriented architecture (SOA) is a design pattern in which application components provide services to other components via a communications protocol, typically over a network.`
* Is there more background information available with the people who are familiar with the symfony service container?
* If so perhaps we can link to another source that is more specific on service orientated architecture in an application. (To get the documentation right, I would rather verify this with the original authors intend then to find my own sources)

If someone could shed some more light on this, it would be lovely. I honestly wouldn't know how else to present this. So if it's not good you can close this issue.

**Comment by javiereguiluz** [comment]
I'm closing this because the proposal didn't gain much traction. I'm sorry. Moreover, given that Symfony has introduced a ton of changes related to services and the container, we've already made lots of changes in the docs. Lastly, all the docs related to services are a top priority for us to reword/improve (as well as Cache, Config and Security). We just need to find more resources to do that. Thanks!
