### ISSUE TITLE
Wrong description of `empty_data` option for `number` field type

### ISSUE THREAD

**Issue by fre5h** [symfony/symfony-docs#5091]
The description of `empty_data` option http://symfony.com/doc/current/reference/forms/types/number.html#empty-data contains the following code:

```php
$builder->add('gender', 'choice', array(
    'choices' => array(
        'm' => 'Male',
        'f' => 'Female'
    ),
    'required'    => false,
    'placeholder' => 'Choose your gender',
    'empty_data'  => null
));
```

I think it was cope-pasted from here http://symfony.com/doc/current/reference/forms/types/choice.html#empty-data

It is example for `choice` field type, so for `number` it should be different.

**Comment by timglabisch** [comment]
:-1: its an Inherited option

**Comment by fre5h** [comment]
@timglabisch It is inherited, but example is for `choice` type. Or it is ok?

**Comment by fre5h** [comment]
I just found that same `choice` example is for all field types. I thought it is only wrong for `number` field. So if it is ok and it should be so then close the issue. But I thought I should be different

**Comment by timglabisch** [comment]
from my point of view it's fine. you'll see the base examples from the inherited fields. so it's not really about number.

**Comment by fre5h** [comment]
good
