### ISSUE TITLE
[2.7][Console][Table] Add doc about colspan/rowspan + multiple header lines.

### ISSUE THREAD

**Issue by aitboudad** [symfony/symfony-docs#5119]
PR: https://github.com/symfony/symfony/pull/13438

**Comment by javiereguiluz** [comment]
Here you can find a blog post about this feature that could be use as inspiration for the documentation: http://symfony.com/blog/new-in-symfony-2-7-advanced-table-layouts-for-console-commands

**Comment by WouterJ** [comment]
This should be added to `components/console/helper/table`
