### ISSUE TITLE
[Validation][DX] Null is considered valid

### ISSUE THREAD

**Issue by ByStones** [symfony/symfony-docs#5122]
Hello,
I tried to validate an entity with an Assert\Choice constraint and discovered that it is considered valid if you pass in a NULL value. This is really counter intuitive and I did not find any information in the validation documentation about this behavior. Only after looking at the "JSR303 Bean Validation specification" which is in the first paragraph I found out about this.

There should be some kind of warning or hint that NULL values will not be checked/considered valid.

**Comment by xabbuh** [comment]
Thank you @ByStones for opening this issue. However, I'm gonna close this nonetheless as we already have an issue that covers this (see #4244). I added your description to that to provide some more context. Your feedback is really appreciated and we would be really happy if you could create a pull request to solve this issue or make some suggestions how to address this issue. Thank you once again!
