### ISSUE TITLE
[Console] Note about semantic verbosity methods & OutputInterface

### ISSUE THREAD

**Issue by apfelbox** [symfony/symfony-docs#5123]
Hi,

the part about the more semantic methods in [The Console Component > Creating a basic Command > Verbosity Levels](http://symfony.com/doc/current/components/console/introduction.html#verbosity-levels) could include a small note:

The semantic methods (`isQuiet`, `isVerbose`, etc.) are only defined in the implementation class, not the interface. So if you typehint against the interface (as you should), your IDE will complain about missing methods.

Maybe a small note there would clear that up? Or is it not necessary? What do you think?

**Comment by javiereguiluz** [comment]
@apfelbox thanks for opening this issue. I agree that this information could be useful ... but I have doubts whether this may be too much.

**Comment by apfelbox** [comment]
@javiereguiluz thanks for your response.

I thought the same thing. On one hand, one should not cram all possible information into the docs, on the other hand this can be quite a puzzling experience. I just wanted to send in the hint about this possible issue, not sure on how to proceed here.

**Comment by WouterJ** [comment]
Let's add a little sentence to this section: "For backwards compatibility, these methods do not exist in the interface until Symfony 3.0."
