### ISSUE TITLE
[Advanced DI] Short guide on how to make a service alias private

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#5138]
A colleague of mine was looking for a way to make an alias private due to the nature of how privates work, the original services are private too. He managed to trace back in the code that there's a secondary way of defining the Alias; By using `Symfony\Component\DependencyInjection\Alias::__construct($id, $public = true)`. 

An example can be found in the Doctrine bundle (`DoctrineExtension.php`): `$container->setAlias($aliasId, new Alias($serviceId, false));`. I think this would be a useful and easy feature to document.

**Comment by WouterJ** [comment]
In order for this to be an easy pick, we have to show where to put this information.

For now, this can be added to `components/dependency_injection/advanced.rst`. But I'd like to revisit that article once (#4228).

**Comment by iltar** [comment]
I think that for now, it could just be a small paragraph below the current Alias and be taken along when the section is revised.

**Comment by javiereguiluz** [comment]
@iltar is this 3-year old issue still relevant after all change sin the DI component? Thanks.

**Comment by iltar** [comment]
Not entirely sure, but I don't see others asking for the feature so I suppose we can close it 👍
