### ISSUE TITLE
[Security] Missing documentation regarding AccessDeniedHandlerInterface

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#5139]
I've seen a few occasion where custom access denied handling is required. It's not rocket science to implement, you put `access_denied_handler: service.id` on your firewall configuration and implement the `AccessDeniedHandlerInterface` in this service. 

I think this could be a simple explanation but add some real value to the docs.

**Comment by WouterJ** [comment]
I vote to add this information to `reference/configuration/framework`
