### ISSUE TITLE
[2.7] Remove Synchronized services from documentation

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#5140]
As of Symfony 2.7, Synchronized services are deprecated. This means that http://symfony.com/doc/current/cookbook/service_container/scopes.html has to be updated to remove the documentation of the synchronized services. Apart from some minor rewordings, the main thing that's needed is the removal of option (a): http://symfony.com/doc/current/cookbook/service_container/scopes.html#a-using-a-synchronized-service

@xabbuh @weaverryan as this feature really only makes sense in 2.3, should we do this in the 2.6 branch or 2.7 branch?

**Comment by weaverryan** [comment]
I vote for 2.7, mostly to keep consistent with changing the docs only on the version when something was *actually* deprecated. And as a bonus, 2.6 hits end of maintenance in July anyways - so it's got a short life.
