### ISSUE TITLE
[2.7] Document the new LogoutUrlExtension

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#5142]
As of 2.7, a new `LogoutUrlExtension` was added. This brings two new Twig functions:

* `logout_url(key = null)` - absolute logout URL (key is the firewall, null is current firewall)
* `logout_path(key = null)` - relative logout URL

These have to be documented in the `references/twig_reference.rst`.

Refs https://github.com/symfony/symfony/pull/13475

**Comment by Keirua** [comment]
I guess this issue can be closed, since logout_path and logout_url are already documented:
https://github.com/symfony/symfony-docs/blob/2.3/reference/twig_reference.rst

**Comment by WouterJ** [comment]
Hmm, indeed. I was incorrect as these functions already existed, but in the SecurityBundle. They just have been extracted to the TwigBridge.
