### ISSUE TITLE
[Bundles] Documention of FOSRestBundle shows wrong version

### ISSUE THREAD

**Issue by xelaris** [symfony/symfony-docs#5151]
E.g. the content of http://symfony.com/doc/master/bundles/FOSRestBundle/2-the-view-layer.html seems to be the **1.6 / master** version of FOSRestBundle doc, but the version label on the upper right corner shows **1.5 version**. This is significant, since the setTemplateData feature described there doesn't exist in version 1.5.

Calling http://symfony.com/doc/1.5/bundles/FOSRestBundle/2-the-view-layer.html shows also the master version and a warning about a not maintained version.

I think there should be a version drop down with **1.5 version** and **1.6 / master**?

ping @javiereguiluz

**Comment by WouterJ** [comment]
Afaik, these version dropdown boxes are based on configuration and are not generated automatically. Each time you have a new version of the docs, you should make sure one of the Sensio website guys update the version checker.

**Comment by WouterJ** [comment]
@javiereguiluz can you please edit the configuration for the FOSRestBundle version switcher?

**Comment by weaverryan** [comment]
ping @javiereguiluz - FOSRestBundle has a 1.7 version now too. Could we make this an option controller by the bundle (for some reason, I feel like we talked about this on some other issue)?

**Comment by WouterJ** [comment]
@weaverryan you probably mean https://twitter.com/javiereguiluz/status/606723874915545088

**Comment by weaverryan** [comment]
Ha, that was it indeed - good memory!

**Comment by xabbuh** [comment]
@javiereguiluz FOSRestBundle started development on the upcoming 2.0 version recently. Can we do an update for it?

**Comment by javiereguiluz** [comment]
I think we can close this issue as "fixed":

![fosrestbundle_doc](https://cloud.githubusercontent.com/assets/73419/11777451/ed75fe52-a24e-11e5-8079-d77b604fac50.png)

**Comment by xelaris** [comment]
@javiereguiluz Yes, looks good. Thank you.
