### ISSUE TITLE
[DX] Improve fast readability of the doc

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-docs#5175]
Hi,

It would be **great** if those 2 pages (maybe more)

- http://symfony.com/doc/current/book/index.html
- http://symfony.com/doc/current/cookbook/index.html

could have a kind of **label tagging**, or **createAt/modifiedAt datetime** so that developer could **bump faster** on the page they want to read **since their last move on the symfony.com documentation** website (switching doc version to see doc changes)

-----------------------------------------------

For example, this before after screenshot

![capture d ecran 2015-04-14 a 10 06 59](https://cloud.githubusercontent.com/assets/1358361/7133025/229c8b76-e28f-11e4-878f-3a710ca0f23d.jpg)

![capture d ecran 2015-04-14 a 10 12 23](https://cloud.githubusercontent.com/assets/1358361/7133000/df16fbc0-e28e-11e4-9168-b9221f9e7970.jpg)

ping @WouterJ @weaverryan

**Comment by xabbuh** [comment]
Thank you for this proposal @94noni. I have one question about it: how would you expect the *updated* button to be displayed? Based on the user's last visit? Based on content differences between different versions? Something else?

**Comment by 94noni** [comment]
Hi @xabbuh 
of course not the user's last visit, but simply a new text/button/image in the file on the new branch version :)

**Comment by javiereguiluz** [comment]
We can close this issue as "won't fix". Our backlog of things to do is already huge ... and this feature would be incredibly hard to do it right. In any case @94noni thanks for proposing this nice feature.

As an alternative, we have the "A month of Symfony Docs" blog post series.
