### ISSUE TITLE
[EventDispatcher] Should examples of events include the Event annotation? 

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#5176]
As of 2.5 the `@Event` annotation was added to [events within symfony](https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=%5C%40Event&type=Code). Despite of not everyone agreeing, it makes searching for event names a lot easier. I supposed this can be seen as a standardization. In my opinion symfony examples should reflect this annotation. Personally I have decided to add this in my own code because it makes searching a lot easier.

I think the only place that would need the `@Event` in the example would be here, [but a proper search could be conducted](https://github.com/symfony/symfony-docs/search?utf8=%E2%9C%93&q=%22final+class%22&type=Code): [/component/event_dispatcher/introduction.html#creating-and-dispatching-an-event](http://symfony.com/doc/current/components/event_dispatcher/introduction.html#creating-and-dispatching-an-event)

Should `@Event` be stated in the docs or not?

**Comment by dupuchba** [comment]
IMO it would confused new sf users as it has no impact on the code nor the design.
:-1: for me

**Comment by WouterJ** [comment]
I think we should keep this as an internal standard for Symfony.

**Comment by iltar** [comment]
Closing this due to lack of comments and is probably not worth a change as it has been open for quite long.
