### ISSUE TITLE
Changing echo/print in examples to use (var_)dump

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#5177]
I think the code should be looked through and see if usages of echo and print can be limited. I think the best replacement could be a reference to `dump()` to output data, but a `var_dump()` could be sufficient too, depending on whether it's framework or a component documentation. An example of using `echo` can be found on [/components/event_dispatcher/introduction.html#event-name-introspection](http://symfony.com/doc/current/components/event_dispatcher/introduction.html#event-name-introspection)

**Comment by WouterJ** [comment]
Actually, why don't we remove the echo and just use `// ...`?

**Comment by iltar** [comment]
It's an option, but might not apply to all output-using examples. For this page it might be nicer to indeed use a comment.
