### ISSUE TITLE
BC promise doesn't care about constants

### ISSUE THREAD

**Issue by dosten** [symfony/symfony-docs#5224]
Searching in the BC promise i don't find any information about the removal, etc of a constant in a normal or API class. Ex: In symfony/symfony#14531 the `PATTERN` constant it's not necessarry but i don't know if i can remove it since the class is tagged as `@api`.

**Comment by stof** [comment]
Constants are public in PHP, so they cannot be removed

**Comment by dosten** [comment]
Agree, what do you think about adding this into the "Changing Interfaces/Classes" tables in the BC promise page?

**Comment by stof** [comment]
@dosten sounds good to me. Can you send a PR to improve it ?

**Comment by WouterJ** [comment]
:+1:

**Comment by dosten** [comment]
Yes, of course

**Comment by dosten** [comment]
Before sending a PR i want to be sure about the changes allowed.

| Type of Change  | Regular | API
| --------------- | ------- | ---
| Add constant    | yes		| no
| Remove constant | no		| no
| Change value    | no		| no

Adding a constant to a API class/interface must be allowed?

**Comment by WouterJ** [comment]
@dosten I would say:

| Type of Change  | Regular | API
| --------------- | ------- | ---
| Add constant    | yes		| yes
| Remove constant | no		| no
| Change value    | yes		| no

/cc @fabpot @webmozart

**Comment by dosten** [comment]
@WouterJ I'm not sure about allow to change the value of a constant in a normal class/interface.

**Comment by dosten** [comment]
ping @fabpot @webmozart

**Comment by stof** [comment]
Changing the value of the constant depends of what the goal of the constant is. In most cases, it is not allowed. But we have a constant in the Yaml component providing a regex IIRC, and changing the value to fix a bug in the regex would be allowed for instance

**Comment by dosten** [comment]
So, we can allow to change the value of a constant in a regular or API class/interface with a footnote?

**Comment by javiereguiluz** [comment]
Closing it as fixed by #5672.
