### ISSUE TITLE
In Documentation Chapter Validation

### ISSUE THREAD

**Issue by Symfomany** [symfony/symfony-docs#5235]
In chapter Validation , why there isn't Expression Assert Validator in validation list? 

http://symfony.com/doc/current/reference/constraints/Expression.html

**Comment by WouterJ** [comment]
It's in the list under "Other Constraints": http://symfony.com/doc/current/book/validation.html#other-constraints (second item). So I'm closing this now, feel free to comment if there still are problems :)
