### ISSUE TITLE
[RFC] [DX] Profiler/WDT must/should be more documented

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-docs#5239]
The **Symfony Profiler/WDT** is a **great tool** that must/should be more documented for developers (mostly newcomers)

Maybe [here](http://symfony.com/doc/current/cookbook/profiler/index.html) or maybe directly in the related feature's book entry
- talk about new added features (form, dump, translation, ajax) since last LTS 2.3
- replace old screenshots showing the WDT on the doc (when 2.7 LTS will be released) ([cf](http://symfony.com/doc/2.7/book/installation.html#running-the-symfony-application))

**Comment by javiereguiluz** [comment]
Closing as fixed. Screenshots are updated and new docs have been added, including the WebProfilerBundle config options. See #8221.
