### ISSUE TITLE
search engine for the documentation ? 

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony-docs#5243]
the documentation of symfony2 is great and one of the most complete I've seen so far but its density makes it very hard to know where to look.

of course one can rely on google to search but it has some huge drawbacks:

  * google is blocked in some countries (China for example where my team is located) and local search engine does not index symfony.com
  * for some topics , the symfony2 docs is far from being the first result, and most of the time only one page of the doc will be presented in the result.
  * it's cluttered with other pages you're not interested with.
  * old pages of symfony1 etc. are sometimes returned. (for some junior developers/intern, they may not know that there used to be a symfony1)

so it would be really the "cerise sur le gateau" if symfony.com could come with a search bar for the book/cookbooks

**Comment by dupuchba** [comment]
:+1: for it, but I think it depends on Sensiolabs team to implement it (ping @fabpot )

**Comment by stof** [comment]
there used to be one and it was removed because it was not working well.

/cc @javiereguiluz

**Comment by allan-simon** [comment]
last time I was thinking,  as the doc is available here, would it be possible to try different search engine/configuration on a "non-official" server until we get something acceptable ?

**Comment by 1ed** [comment]
I think Algolia would be great as a search engine and a huge improvement to UX.

There is a blog post how they implemented that for laravel (and there is an ongoing PR for [bootstrap](https://github.com/twbs/bootstrap/pull/16901)): 
 https://blog.algolia.com/how-to-build-a-helpful-search-for-technical-documentation-the-laravel-example/

I know those docs have much simpler structure what we have, but Algolia willing to help in the implementation:

> One of our missions is to help all developers to better access and navigate technical documentations. If you are working on an open source project we’d be happy to help you! We will provide you with a free Algolia account and with any support to make your implementation a best-in-class reference. Drop us a note!

What do you think? Is there a plan?

/cc @weaverryan @WouterJ @xabbuh @javiereguiluz @fabpot @stof

**Comment by javiereguiluz** [comment]
We are going to re-enable the documentation search soon. We're already working on this. I can't set a specific date for this and I can't disclose more details at the moment. Please I ask you a little more patience. Thanks!

**Comment by dupuchba** [comment]
@javiereguiluz good news, can we have any insights on technical choice you are making on this ?

**Comment by javiereguiluz** [comment]
@dupuchba not yet, sorry. But when we implement it, we'll explain all the details and we'll publish a blog post.

**Comment by dupuchba** [comment]
ok, great :-)

**Comment by fabpot** [comment]
Closing as the new search engine is now available: http://symfony.com/search
