### ISSUE TITLE
[Security] Instructions in "How to Simulate HTTP Authentication in a Functional Test " don't work

### ISSUE THREAD

**Issue by parhamdoustdar** [symfony/symfony-docs#5244]
If you look at the documentation page [here](http://symfony.com/doc/current/cookbook/testing/http_authentication.html), just before the final configuration example, it's said that:

> The trick is to include the http_basic key in your firewall, along with the form_login key:

When I put the mentioned piece of configuration inside my `config_test.yml`, the login form is still displayed, even in the `test` environment. I am unaware of how having multiple authorization listeners works in Symfony, so I don't know how to fix this myself.

**Comment by WouterJ** [comment]
It does still render the login form. However, as the `http_basic` authenticator is also enabled, it can also be used to login.

This means that in the unit tests, you can send the credentials using request headers, as shown by the first 2 examples in the mentioned code block. This is also explained in the paragraph you quoted:

 > When your application is using a form_login, you can simplify your tests by allowing your test configuration to make use of HTTP authentication. **This way you can use the above to authenticate in tests, but still have your users log in via the normal form_login.**

I'm going to close this issue, as it seems like there is no problem. However, feel free to comment if you don't fully grasp it yet or have ideas on how to avoid this confusion in the future.

**Comment by parhamdoustdar** [comment]
Thank you for your in-depth explanation. It appears like others also have this issue, since my questions on IRC and StackOverflow ([http://stackoverflow.com/questions/30138561/how-can-i-test-a-page-behind-a-security-firewall-in-symfony/30142389?noredirect=1#comment48405455_30142389](How can I test a page behind a security firewall in Symfony?)).

Now that I know the solution though, I can try to make the text explicitly mention this and send a pull request. It would also be a good practice for me to become a documentation contributor. Is that all right?

**Comment by WouterJ** [comment]
> Now that I know the solution though, I can try to make the text explicitly mention this and send a pull request. It would also be a good practice for me to become a documentation contributor. Is that all right?

Of course! :)
