### ISSUE TITLE
Build reports for third-party bundles

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5256]
Now, that some popular bundles have their documentation on symfony.com, could we please expand [the build errors report page](http://symfony.com/doc/build_errors) to show errors for these bundles too?

ping @fabpot @javiereguiluz

**Comment by javiereguiluz** [comment]
The build errors report page was alreading cheking the doc for the new bundles. However, it didn't show the information properly.

We've just made a change to only show the doc which contains errors. So you no longer see "No errors" messages for the doc that is correct. This makes this page much more actionable and easier to understand.

**Comment by stof** [comment]
@javiereguiluz are you sure ? the page shows ``No errors`` for multiple repos, including SensioFrameworkExtraBundle, but newer repos don't appear at al there.

Or maybe your list of repos is paginated and you are missing the pagination controls ?

**Comment by javiereguiluz** [comment]
After some thorough revision, I've made some additional changes. The error log display was correct (no pagination issues, etc.) but in some cases the doc error logfile wasn't generated at all!  We'll see the latest changes on symfony.com in a few hours.

**Comment by xabbuh** [comment]
@javiereguiluz Are you sure? Anyway, we still get errors from the Italian documentation which should at least be removed (same for the French translations).

**Comment by WouterJ** [comment]
At the moment, only Italian build errors are shown. Italian docs are no longer shown on symfony.com.

Can the build error page please be restored and at least show the english docs build error log?

**Comment by javiereguiluz** [comment]
I'm glad to announce that the doc build error logs have been reenabled and they can be trusted again:

http://symfony.com/doc/build_errors

Thanks a lot to the SensioLabs sysadmins!
