### ISSUE TITLE
Jquery add/remove tag in "How to Embed a Collection of Forms" bug

### ISSUE THREAD

**Issue by srokatonie** [symfony/symfony-docs#5258]
Hi, it's first time I'm writing here.

This assumes that every time you submit it doesn't go through because of i.e. validation.
You add some tags (3), then submit form, then delete first tag (index 0) and then submit. Then add another tag (4) and submit. And now there's the problem, because the tag nr 3 is gone, instead of having 3 tags you have 2. It's because jquery adds field with an index that already exists, therefore the most recent field with the duplicated index is used.

The problem seems to be here
`$collectionHolder.data('index', $collectionHolder.find(':input').length);`
Where it's the length check but not the highest index, I think.

I'm working on a solution, but probably won't be too beautiful

**Comment by srokatonie** [comment]
So I came up with this awful hack since I can't go deep into this right now:

```javascript
function addMessageLineForm($collectionHolder, $newLinkLi) {

	//...

	// get the new index
        var index = $collectionHolder.data('index');

	//is the index highest?
	var absHighestIndex = getHighestIndex();
	if (index < absHighestIndex) {
		index = absHighestIndex;
	}

	// count the current form inputs we have (e.g. 2), use that as the new
	//...

}

//...

function getHighestIndex() {
	var length = $collectionHolder.find(':input').length;
	if (length) {
		var indexes = [];
		for (var i = 1; i <= length; i++) {
			var inputName = $collectionHolder.find('li:nth-child('+ i +') input').attr('name');
			var inputNameArr = inputName.split("][");
			console.log(inputNameArr);
			// inputNameArr = ["appbundle_form_name[parent_field", "index", "collection_field]"]
			//it's the second (1) value in array
			var inputIndex = inputNameArr[1];
			indexes.push(inputIndex);
		};
		//find the highest value and add 1 for next field
		var highestIndex = Math.max.apply(null, indexes) + 1;
		return Math.max(highestIndex);
	}
}
```

**Comment by iltar** [comment]
Is this really an issue for the docs? Seems more like a usability issue with collections and entities, one that you can't really solve without either a lot of code in your form type.

**Comment by javiereguiluz** [comment]
Sadly we have received lots of bugs reports about this issue. It's still pending to be fixed. In any case, in order to focus our efforts, I'm closing this one as "duplicate" of this other issue: #6924. Thanks!
