### ISSUE TITLE
Improve "Testing Documentation" in contributing guide

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#5259]
We should improve http://symfony.com/doc/current/contributing/documentation/format.html#testing-documentation to make it a bit less confusing.

From #3917:
- [ ] We should explain how the build will look like.
- [ ] Tell about the additional _ext directory and how not to add it to the PR.

**Comment by snoek09** [comment]
The _exts directory is already in the gitignore file.

**Comment by stof** [comment]
@snoek09 the ``_exts`` directory is a submodule

**Comment by snoek09** [comment]
@stof Thanks, I don't see the additional _ext directory. When is it created?

**Comment by snoek09** [comment]
Also mentioned here: https://github.com/symfony/symfony-docs/pull/3917#issuecomment-45432943
Seems to me it's not needed any more to mention this.

**Comment by WouterJ** [comment]
I think we should tell something about the submodule stuff, as it can introduce weird results for `git status` when you're on an out of date branch. We should explain how to avoid/remove this troube imo

**Comment by xabbuh** [comment]
I am not sure if we really need to document this anymore now that you can see how your PR will look like thanks to our platform.sh previews.

**Comment by javiereguiluz** [comment]
I agree with @xabbuh. The current situation is much better than when this issue was created. Now we validate the syntax with Travis and we provide a real doc rendering thanks to Platform.sh.
