### ISSUE TITLE
Make sure "pre auth" article mentions that you need an anonymous firewall

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#5264]
Hi guys!

See symfony/symfony#13751 - if you're going to return `null` from `createToken()`, you must have `anonymous` on in your firewall so that you at least get the `AnonymousToken`.

Thanks!

**Comment by xabbuh** [comment]
reopening here as we may want to put some more clarification here (see https://github.com/symfony/symfony-docs/pull/5943#issuecomment-163390943)
