### ISSUE TITLE
[HttpFoundation] Explain the impact of the stat cache on the BinaryFileResponse

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5268]
The result of a `filesize()` call as well as a call to `SplFileInfo::getSize()` are cached to improve speed. However, as the `BinaryFileResponse` relies on the `getSize()` method to return a proper HTTP response, it must be ensured that `clearstatcache()` is called before the response will be returned.

For example, this behaviour led to some confusion in symfony/symfony#11102.

**Comment by dupuchba** [comment]
Good catch !

**Comment by kherge** [comment]
Created a PR!

Let me know if the wording could be better.
