### ISSUE TITLE
[Templating] Global Twig Variables: Clarify what a "more complicated variable" is

### ISSUE THREAD

**Issue by bicpi** [symfony/symfony-docs#5274]
In http://symfony.com/doc/2.3/cookbook/templating/global_variables.html#using-a-twig-extension, the documentation suggests creating a Twig extension with `getGlobals()` when the needed variable, e.g. an object, is too complicated. Maybe this is a bit confusing as you can use services with the @-Syntax mentioned above. So what could be a more complicated object than what you could do with a service object, does someone has an example for it?

**Comment by javiereguiluz** [comment]
I understand the note as *"if you want to pass some object which is not associated with a service"*. I'm not sure if it needs rewording, but I'm willing to do that if the doc managers agree.

**Comment by xabbuh** [comment]
What would be an alternative sentence?

**Comment by javiereguiluz** [comment]
Closing it as fixed because this section was removed starting from 2.7: http://symfony.com/doc/2.7/templating/global_variables.html
