### ISSUE TITLE
[RFC] Should we comply with Doctrine Best Practices?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5315]
The other day @ocramius published the slides of his recent talk called [Doctrine Best Practices](http://ocramius.github.io/doctrine-best-practices/#/1). If you check out the slides, you'll see that our Doctrine-related documentation should be updated.

My question is: should we really update our documentation? Or should we "ignore" these recommendations (with all the due respect to @ocramius) because they are targeted to very experience developers?

-----

Here it is a list of the most important Doctrine Best Practices:

1) Disallow Collection access from outside the Entity

```php
// Don't do this
class User
{
    private $bans;

    public function getBans() {
        return $this->bans;
    }
}

// Do this
public function banUser($userId)
{
    $user = $this->repository->find($userId);

    $user->getBans()->add(new Ban($user));
}
```

2) Keep collections hidden in your entities

```php
class User
{
    private $bans;  // <-- private collection

    public function ban() {
        $this->bans[] = new Ban($this);
    }
}
```

3) Avoid lifecycle callbacks (don't use them for business logic/events)

4) Avoid auto-generated `id` and use UUIDs instead

```php
public function __construct()
{
    $this->id = Uuid::uuid4();
}
```

5) Avoid composite primary keys.

6) Use annotations in private packages and XML mappings in public packages.

7) "Eager loading" is useless.

8) "Extra lazy" indicates high risk areas.

9) Avoid bi-directional associations.

10) Query functions are better than custom repositories.

```php
// custom repository
final class UserRepository
{
    public function findUsersThatHaveAMonthlySubscription()
    {
        // ... INSERT DQL/SQL HELL HERE ...
    }
}

// query functions
final class UsersThatHaveAMonthlySubscription
{
    public function __construct(EntityManagerInterface $em) { ... }

    public function __invoke()
    {
        // ... INSERT DQL/SQL HELL HERE ...
    }
}
```

**Comment by Ocramius** [comment]
I should probably rename the talk "Ocramius' opinions on doctrine best
practices", btw ;-)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by javiereguiluz** [comment]
Closing it because the lack of feedback shows that the Symfony Community probably doesn't care about this.
