### ISSUE TITLE
Documentation not being built

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5322]
It seems that the documentation has not been built since about one day. However, the [build errors page](http://symfony.com/doc/build_errors) does not provide any feedback about failed build jobs.

Is this maybe related to the [update of the conf.py file](https://github.com/symfony/symfony-docs/pull/5283#issuecomment-104867992)?

ping @fabpot @javiereguiluz

**Comment by xabbuh** [comment]
ping @fabpot @javiereguiluz Can you please check the build server's error log?

**Comment by javiereguiluz** [comment]
@xabbuh I'm looking into it with the help of the devops who manages the server. I'll keep you posted.

**Comment by xabbuh** [comment]
Thank you Javier!

**Comment by javiereguiluz** [comment]
I've just found the cause of this problem and the new lexers are now working locally on my computer:

![symfony_docs_new_lexers](https://cloud.githubusercontent.com/assets/73419/7880355/039c2316-05f9-11e5-8be5-53bc86aee287.png)

Sadly, solving the problem on symfony.com server could take a bit of time (in the worst case scenario it will be solved on next Monday).

**Comment by xabbuh** [comment]
Thanks for the feedback. Does it mean we can just wait or is their anything to do on our side?

**Comment by javiereguiluz** [comment]
@xabbuh we're on it and everything should be solvable on our side. Thanks.

**Comment by weaverryan** [comment]
@javiereguiluz with the release of 2.7 (I believe this weekend), we're missing some important documents - like the new re-worked Upgrade section by @WouterJ and also the new "deprecation warnings" thing that I just merged.

If rolling back #5283 temporarily would fix the issue, I'd be +1 for that. I'd like Fabien to be able to link to the upgrade docs from the release blog post (was just about to bother him about this, when I noticed the docs aren't up).

Thanks!

**Comment by javiereguiluz** [comment]
Good news. This change has been merged and deployed. This means that tonight the documentation should be generated as usual. I'll keep you posted.

**Comment by weaverryan** [comment]
pffff, well then disregard my comment! Thank you so much Javier (and anyone else that helped)!

**Comment by xabbuh** [comment]
Thank you @javiereguiluz and who else was involved. Everything is rendered nicely now! :)
