### ISSUE TITLE
[Bug] symfony.com/roadmap

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-docs#5330]
Hi guys,

:warning: The version on this page are wrong 2.3.28 and 29 is released, same for 2.6.7/8
:warning: Seems the same on http://symfony.com/versions.json

Shouldn't this json file updated? If yes, why is it not automatic? 
Released are form +2 days :s

Thanks

**Comment by WouterJ** [comment]
Ping @fabpot @javiereguiluz

**Comment by javiereguiluz** [comment]
I'm sorry for this. The versions were correctly updated, but we need to wait for the next deploy of the website. I can't comment on details but it will take a bit more time. Sorry.

**Comment by 94noni** [comment]
Ok, it was just a check :)
Thx

**Comment by WouterJ** [comment]
Closing in that case :)
