### ISSUE TITLE
Broken link to the VarDumper component

### ISSUE THREAD

**Issue by Keirua** [symfony/symfony-docs#5349]
In the component section of the documentation, the VarDumper section has errors:
http://symfony.com/components
It points to the incorrect github repository, indicates no documentation (while there is one already), and there is no summary

![vardumper-error](https://cloud.githubusercontent.com/assets/1223316/7935228/7e1673d8-092f-11e5-97c1-42344b2d1296.png)

**Comment by Keirua** [comment]
Ok, just figured out that it's linked to the Symfony website and not to the documentation

**Comment by stof** [comment]
see https://github.com/symfony/symfony-marketing/pull/256 for the missing doc URL for the component
