### ISSUE TITLE
Array example needs an explanation in quick_tour/the_view.html

### ISSUE THREAD

**Issue by ThinkALot** [symfony/symfony-docs#5366]
In this page:

http://symfony.com/doc/current/quick_tour/the_view.html

In this section:

Embedding other Controllers

the 2nd example contains this:

return $this->render('default/top_articles.html.twig', array(
            'articles' => $articles,
));

The array needs to be explained. Specifically, how does the array work?

**Comment by andesk** [comment]
Isn't the array already explained some paragraphs higher under http://symfony.com/doc/current/quick_tour/the_view.html#getting-familiar-with-twig ? I think there is no need to repeat that.

**Comment by javiereguiluz** [comment]
I'm closing because we're going to revamp the Quick Tour entirely and we'll change everything. Thanks!
