### ISSUE TITLE
text correction?

### ISSUE THREAD

**Issue by bokonet** [symfony/symfony-docs#5370]
http://symfony.com/doc/current/cookbook/logging/monolog_email.html

`The mail handler is a fingers_crossed handler which means that it is only triggered when the action level, in this case critical is reached. It then logs everything including messages below the action level. The critical level is only triggered for 5xx HTTP code errors.`

Is it `below the action level` or `above the action level`?

**Comment by snoek09** [comment]
That should be 'above the action level' based on text below that part:

```
If you want both 400 level and 500 level errors to trigger an email, set the action_level to error instead of critical. See the code above for an example.
```

**Comment by bokonet** [comment]
Now i hopefully understand the text: `It then logs everything including messages below the action level.`

May be this text should be easier to understand:
`The mail handler is a fingers_crossed handler which means that it is only triggered when the action level, in this case critical is reached. The critical level is only triggered for 5xx HTTP code errors.` But If the level is reached once, the finger_crossed handler will log everything, including messages below the action level.

am i right?

**Comment by snoek09** [comment]
From https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/FingersCrossedHandler.php

```
Buffers all records until a certain level is reached

The advantage of this approach is that you don't get any clutter in your log files.
Only requests which actually trigger an error (or whatever your actionLevel is) will be
in the logs, but they will contain all records, not only those above the level threshold.
```

**Comment by xabbuh** [comment]
@bokonet @snoek09 Does anyone of you like to create a pull request for this?

**Comment by snoek09** [comment]
I would like to. Not sure about the definitive text though.

After reading the `FingersCrossedHandler` comment it seems the cookbook documentation is right.
I agree it's a bit confusing.

**Comment by snoek09** [comment]
@xabbuh there's a pull request: https://github.com/symfony/symfony-docs/pull/5414
