### ISSUE TITLE
Missing image from security doc

### ISSUE THREAD

**Issue by jbinfo** [symfony/symfony-docs#5376]
I verified in doc and I found it, so, I think it's a problem of deployment 
![selection_025](https://cloud.githubusercontent.com/assets/761378/8081208/ed1bcd32-0f6a-11e5-821f-c5f5b4b3cfc6.png)

The missing image is:
![security_authentication_authorization](https://cloud.githubusercontent.com/assets/761378/8081247/3a1ade48-0f6b-11e5-9d00-3bc5665fd0b3.png)

**Comment by jbinfo** [comment]
Not only for symfony 2.1 but in multiple versions.

**Comment by xabbuh** [comment]
Are you sure that this is still valid for maintained versions? I didn't see anything related to it in the `2.3`, `2.6` and `2.7` branches.

**Comment by jbinfo** [comment]
For maintained version the doc doesn't use that picture, only in 2.0 / 2.1 / 2.2 / 2.4

**Comment by xabbuh** [comment]
I don't think we should put much effort in fixing this for the unmaintained versions.

@fabpot @javiereguiluz However, can this actually be an issue for maintained versions too if an image is present in only some of the branches?

**Comment by WouterJ** [comment]
@javiereguiluz do you know why images are not taken from the version, but instead only from one branch (which seems to be the master branch)?

**Comment by javiereguiluz** [comment]
@WouterJ I've checked this again and it each version seems to use their own images stored in the `_images/` directory.

In any case, we can close this issue as "won't fix" because sadly, unmaintained versions don't get any updates.

**Comment by javiereguiluz** [comment]
**Update**: we can now close this as "fixed" because problems with images were solved when we regenerated the entire documentation from scratch:

![security_image](https://cloud.githubusercontent.com/assets/73419/13350973/d5b4c680-dc83-11e5-8b0a-aed803db9d40.png)
