### ISSUE TITLE
Potentially confusing wording

### ISSUE THREAD

**Issue by richardudovich** [symfony/symfony-docs#5380]
The following quote: 

"*External service configuration can be imported in two different ways. The first - and most common method - is via the imports directive. Later, you'll learn about the second method, which is the flexible and preferred method for importing service configuration from third-party bundles.*" 

from: 
https://github.com/symfony/symfony-docs/edit/2.7/book/service_container.rst 
made me wonder why is the first method most common when the 2nd is more flexible and preferred

**Comment by xabbuh** [comment]
While the second approach gives you more flexibility it also adds a lot of complexity. Do you have an idea how we can improve the wording to make that more clear?

**Comment by richardudovich** [comment]
Maybe something like this:

External service configuration can be imported in two different ways. The first method, commonly used to import container configuration from the bundles you've created - is via the imports directive. The second method, although slightly more complex offers more flexibility and is commonly used to import third-party bundle configuration. Read on to learn about both methods.

**Comment by xabbuh** [comment]
@richardudovich Do you like to open a pull request with this? The sentence can be more refined there then.

**Comment by richardudovich** [comment]
done... https://github.com/symfony/symfony-docs/pull/5383
