### ISSUE TITLE
Installation screen is wrong as of 2.7

### ISSUE THREAD

**Issue by harikt** [symfony/symfony-docs#5395]
As of 2.7 the installation screen is wrong or don't show as in the screenshot in 

http://symfony.com/doc/2.7/book/installation.html#running-the-symfony-application

Needs update https://twitter.com/harikt/status/609776555519160320 .

Thank you @weaverryan

**Comment by smatejic** [comment]
Fixed

**Comment by weaverryan** [comment]
Yep - see #5400!
