### ISSUE TITLE
Update documentation to describe ArrayChoiceList usage

### ISSUE THREAD

**Issue by ryancastle** [symfony/symfony-docs#5405]
For users upgrading from 2.3 to 2.7, there are a lot of deprecation warnings around `ChoiceList`, `SimpleChoiceList` and `ChoiceListInterface`. The recommendation is to use `ArrayChoiceList` instead. However, there currently isn't any documentation about how to use that, and the current 2.7 documentation suggests using the deprecated `ChoiceList`. See http://symfony.com/doc/current/reference/forms/types/choice.html#choice-list

This is a very complicated area of Symfony forms which has been in a bit of flux due to potential API changes, so it would be good to have some examples of usage.

I'd update the docs myself, but I haven't figured out how `ArrayChoiceList` actually works yet.

**Comment by xabbuh** [comment]
@ryancastle Thanks for mentioning this. However, I will close here though as we are already aware of this (see #5179). Anyway, thanks again. :)

**Comment by ryancastle** [comment]
Yeah. Fair enough. I didn't find that one.

**Comment by adamelso** [comment]
I've been looking through all the resources I can find... Symfony Docs, Symfony News posts, UPGRADE.mds, the source code, GitHub issues linked from here and others, StackOverflow, to name a few.

However, I am still not 100% certain what the upgrade course is for replacing the deprecated ObjectChoiceList with ArrayChoiceList.

As far as I can see, #5876 does not cover this issue which was meant to replace the closed #5179.

**Comment by HeahDude** [comment]
Hi @adamelso, see #6393. Hope that helps.

Cheers
