### ISSUE TITLE
Incorrect URL for homepage on a newly created project - The Quick Tour

### ISSUE THREAD

**Issue by cuthbert19** [symfony/symfony-docs#5440]
In file symfony/symfony-docs/blob/2.7/quick_tour/the_big_picture.rst , at raw 66, it's suggested that the URL for accessing the newly-created project is http://localhost:8000 . That's not right, or at least not for the current version of Symfony.
It took me a while to realize that the correct url is http://localhost:8000/app/example , as is correctly stated in the "installer" section of the Symfony book.

**Comment by xabbuh** [comment]
Thank you very much for reading the docs so carefully and even reporting the bug here @cuthbert19. You are absolutely right about this. However, I am going to close this issue nonetheless as we already have an open ticket covering this (see #5353).
