### ISSUE TITLE
[RFC] Remove glossary

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#5462]
It has recieved it's last word-changing change on September 18th, 2013. The article itself doesn't seem to be linked from anywhere on symfony.com (doc index, navigation, ...). The `:term:` roles linking to the glossary have not been added since I'm reviewing PRs.

In other words: It hasn't recieved any love from us since I joined the docs.

I don't know about the amount of visitors (/cc @javiereguiluz), but I would like to propose the article. I think all terms are covered with just as nice (or nicer) descriptions in the related book/cookbook pages, meaning people are directly on the good page to read more about the topic.

/cc @xabbuh @weaverryan

**Comment by xabbuh** [comment]
Just in case someone is wondering what this is all about: The glossary can be seen at http://symfony.com/doc/current/glossary.html.

**Comment by xabbuh** [comment]
Oh, I just found where it is linked: http://symfony.com/doc/current/genindex.html (if a term is used in the glossary)

**Comment by xabbuh** [comment]
Anyway, as a last comment in this row. ;) Unless Javier reveals that there are a lot of people visiting the glossary, I will be absolutely :+1: to remove it. It's completely outdated and didn't receive any love.

**Comment by weaverryan** [comment]
Let's remove it. When I first started with RST, I thought it was a neat idea, but I don't think anyone is using it - the fact that there have been probably zero pull requests to this section shows how many people are using it.

**Comment by javiereguiluz** [comment]
During the last 12 months, the Glossary page has been the 230th most popular doc page. Its traffic is marginal, so I think it's safe to remove it.

**Comment by xabbuh** [comment]
@javiereguiluz Thanks, do we need to wait for you to remove references to it on the web site first to not break the build process?
