### ISSUE TITLE
In the book there seems to be an illegal validate call

### ISSUE THREAD

**Issue by daften** [symfony/symfony-docs#5469]
It says that since 2.5 the validation api accepts the groups as third argument, but the API seems to disagree: http://api.symfony.com/2.7/Symfony/Component/Validator/ValidatorInterface.html

https://symfony.com/doc/current/book/validation.html#validation-groups

**Comment by xabbuh** [comment]
The 2.5 API is in a `Validator` subnamespace: http://api.symfony.com/2.7/Symfony/Component/Validator/Validator/ValidatorInterface.html#method_validate

So there is no issue and I'm going to close here. But anyway thank you for taking the time to open an issue. :)

**Comment by WouterJ** [comment]
The API link is wrong indeed. It should link to the `Symfony\Component\Validator\Validator\ValidatorInterface` instead of `Symfony\Component\Validator\ValidatorInterface`.

**Comment by daften** [comment]
There is a link in the top section of the page next to implements ;)
