### ISSUE TITLE
The image in the release schedule page is outdated

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#5470]
The image https://github.com/symfony/symfony-docs/blob/13e4d92e805cc2ee7eead57ab5367a83a7c1470b/images/release-process.jpg should be updated to display 3.0 and later releases rather than a 2.9 release 6 months after 2.8. The table below is uptodate, but not the image

**Comment by javiereguiluz** [comment]
I'm going to recreate this image. Thanks for the heads up.
