### ISSUE TITLE
[create_framework] phpunit test error

### ISSUE THREAD

**Issue by emillosanti** [symfony/symfony-docs#5487]
error when running phpunit test:

Call to a member function fromRequest() on a non-object in .../src/Simplex/Framework.php on line 29

resolved by adding

    protected function getFrameworkForException($exception)
    {
        //...

        $matcher
            ->expects($this->once())
            ->method('getContext')
            ->will($this->returnValue($this->getMock('Symfony\Component\Routing\RequestContext')))
        ;

based on old issue : 
https://github.com/fabpot/Create-Your-Framework/issues/29

http://webcache.googleusercontent.com/search?q=cache:yufENRDJeo8J:https://github.com/fabpot/Create-Your-Framework/issues/29+&cd=2&hl=en&ct=clnk

**Comment by xabbuh** [comment]
for the records: #5488 fixes this issue

**Comment by xabbuh** [comment]
sorry, wrong button
