### ISSUE TITLE
Claim in documentation not supported by code

### ISSUE THREAD

**Issue by rcousens** [symfony/symfony-docs#5502]
http://symfony.com/doc/current/cookbook/bundles/best_practices.html

![screenshot from 2015-07-08 13 11 14](https://cloud.githubusercontent.com/assets/6834920/8562221/d957b84c-2572-11e5-8a56-34c57d29d5e6.png)

I cannot find any reference in Symfony2 code to EventListener being a specific emplacement (I understand that it may be a convention) whereas the Command, Controller and Resources subdirectories have some degree of auto-wiring functionality during compiler passes hence the specific emplacement claim.

Command: src/Symfony/Component/HttpKernel/Bundle/Bundle.php <-- wires up Command directory
Controller: src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php <-- relies on a specific emplacement of Controller to generate short names
etc...

My understanding of "specific emplacement" is that it is mandated due to the way Symfony2 processes bundles being loaded into the AppKernel. Am I missing something here? 

You could put listeners under any directory and it makes no difference. It's just poor style. This is not true for the other directories listed in the screenshot above.

**Comment by javiereguiluz** [comment]
What if we add a third column to that table explaining if the location is `mandatory` or `convention`?

**Comment by xabbuh** [comment]
@javiereguiluz sounds like a good idea to me

**Comment by rcousens** [comment]
I will submit a PR for this tonight.

**Comment by rcousens** [comment]
Got time put aside to do this over the weekend. Promise it's coming!
