### ISSUE TITLE
[Cookbook][WebServer] mention the force option of the server start command

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5504]
In symfony/symfony#15134, a new `--force` option was introduced for the `server:start` command which is useful when PHP's built-in web server terminated unexpected, but the lock file does still exist. In this case, the `server:start` command would refuse to start a new server process telling you that there already is a running process. The `--force` could then be used to (try to) start a new process anyway.

This could simply be documented by adding a small tip in the chapter that explains how to control the internal web server (see http://symfony.com/doc/current/cookbook/web_server/built_in.html).

**Comment by vincentaubert** [comment]
what about this version? @xabbuh

**Comment by vincentaubert** [comment]
fixed
