### ISSUE TITLE
Why does the documentation recommend using `https off;` with nginx

### ISSUE THREAD

**Issue by wjzijderveld** [symfony/symfony-docs#5517]
In the [Configuring a Web Server](http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx) it includes `fastcgi_param HTTPS off;` for the nginx configuration. This can cause issues when you are using HTTPs.

I guess that this config is partly copied [from the nginx wiki](http://wiki.nginx.org/Symfony)?
But there it makes more sense, as the Nginx also mentions the SSL server.

Our usecase is an oauth server, which is using the Symfony Security component. In the `HttpUtils` it [lets the request generate the uri](https://github.com/symfony/Security/blob/143998de26178e2bbcd6924676a26ae15ab67745/Http/HttpUtils.php#L134-L140) when a relative path is given. The [Request then uses the HTTP flag](https://github.com/symfony/HttpFoundation/blob/a681f02dfc53fdb4f54bff72a19c103916bcede2/Request.php#L1249) to determine if it should generate an https url. This caused our oauth to redirect our https call back to a http url.

I would suggest we remove the line from documentation here and let the default values be used. I think most distributions use a file similar as mentioned here: http://wiki.nginx.org/PHPFcgiExample

**Comment by weaverryan** [comment]
:+1: I just checked one of my configs (that supports https) and I in fact do not have the line you're talking about removing.

**Comment by weaverryan** [comment]
And yea, iirc, I think we just copied from the NGINX wiki - but only copied the http part.

**Comment by wjzijderveld** [comment]
Thanks! I'll create a PR then :smile:
