### ISSUE TITLE
Add documentation for using Symfony without bundles.

### ISSUE THREAD

**Issue by nesl247** [symfony/symfony-docs#5535]
A bundle is supposed to be a reusable set of code, which means that AppBundle for instance, is unneeded. It's becoming more and more popular to go "bundleless", and thus we should have documentation on how to do this.

I'm going to try and write this documentation per discussions with @weaverryan. It seems to be something that other people are interested in.

To Do:
- [ ] Placement of twig templates
- [ ] Configuration for entities
- [ ] Configuration of routes
- [ ] Recommendations on how to use `src/`
- [ ] Placement of DataFixtures and the parameter to run it (`--fixtures=app/DataFixtures/ORM`)

**Comment by dupuchba** [comment]
Here is my opinion : 
As a sf user, I don't get the point to use The Fullstack Framework if I don't use other 3rd party Bundle.
If I want to go bundleless, I would prefer use components IPO

**Comment by xabbuh** [comment]
@dupuchba Imho the point is more to explain how you can write your application without the need to create an application bundle (actually, there is no need to create a bundle for your application code and bundles just make it easier to publish code that could be reused in other applications).

**Comment by dupuchba** [comment]
@xabbuh ok, I didn't get it that way. Now it make more sense :-)

**Comment by iltar** [comment]
@nesl247 A few other important parts are:
 - The configuration of the autoloading in `app/`
 - Custom service loading, when your app grows a single services.yml is not sufficient anymore
 - Translations loading
 - Explaining the difference between `app/config/` and `app/Resources/config/`

**Comment by stof** [comment]
@iltar the configuration of autoloading is not related to bundles. It is just using Composer features directly.
Regarding services.yml, you can just split it in multiple files and import all of them (services.yml is just a file imported this way in the app skeleton)

**Comment by stof** [comment]
and for translations, if you follow the best practices, they are already placed in ``app/Resources/translations``, meaning there is no change needed to go bundleless.

**Comment by iltar** [comment]
@stof correct, but `composer.json` will require an additional autoload rule for `app/*` which has to be added somewhere (docs, standard edition etc.).

**Comment by nesl247** [comment]
What's in `app/*` that needs to be autoloaded? I wasn't planning on writing docs recommending using `app/*` at all for your source code, just translations, twig, etc. I was going to write this using `src/<Project>`. I've got nothing in my `composer.json` mentioning `app/*` and I've been running bundleless for a couple of months.

**Comment by iltar** [comment]
That works too.

**Comment by javiereguiluz** [comment]
I'm closing this old issue because with Symfony Flex, we'll no longer have bundles for our own code starting from Symfony 4.0. So, this proposal to add just an article explaining how to get rid of app bundles won't be needed ... because we'll update the entire docs to get rid of those bundles. Thanks!
