### ISSUE TITLE
Remove any reference to the web configurator

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5539]
We are trying to remove the web configurator in https://github.com/sensiolabs/SensioDistributionBundle/pull/217

The `config.php` file will remain, but it will no longer allow to update the `parameters.yml` file. It will be just a pure techniacl requirements checker.

I've looked for any reference of using or mentioning the `config.php` file as a web configurator, but I've found none. It'd be great if other doc reviewers could verify that this is correct. Thanks.

**Comment by xabbuh** [comment]
I don't think we ever referenced to the web configurator anywhere.

**Comment by WouterJ** [comment]
I believe we did/do in the quick tour

**Comment by javiereguiluz** [comment]
The web configurator has been finally removed, so we can now make any needed change (if any) or close this issue. Thanks!

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because I can find no reference to this removed web configurator.
