### ISSUE TITLE
Symfony Demo project needs more visibility

### ISSUE THREAD

**Issue by JulienItard** [symfony/symfony-docs#5541]
**Symfony Demo Project** : https://github.com/symfony/symfony-demo

Hi,

I think this project needs more visibility ! The official website never speaks about it. We should have a link to this repo in the homepage in Learn > Other ressources.
Also, we should have a link in the Documentation page in sidebar menu and in Symfony Best Practices section.

What do you think ? For now, beginners and others can't find this project.

**Comment by xabbuh** [comment]
We talk about it in the installation chapter. But I think you are right that this is probably not enough. Maybe we should introduce sidebar elements in the different chapters if there is a good example in the demo application for a concept we describe.

**Comment by WouterJ** [comment]
/cc @javiereguiluz As you're our site guy and demo maintainer

:+1: to add links to the demo app in multiple locations of symfony.com, for instance:

* Homepage -> additional resources
* Downloads (it should at least mention `symfony demo` imo)
* http://symfony.com/what-is-symfony (it already is full with things for beginners, I think the demo deserves it's own box and icon, just like the quick tour)

---

For the Quick Tour, I think we should rewrite it to use the demo application as example and no longer the removed AcmeDemoBundle. We've brought up this topic a couple of times now, but we never started anything. (/cc @weaverryan maybe add this to the meeting topic list?)

---

At last, as the demo contains these nice "the code behind this page" overlays, why not publishing it online at e.g. demo.symfony.com?

**Comment by JulienItard** [comment]
I think the future release of 3.0 could be a good opportunity to completely rewrite the Quick Tour with Symfony Demo.

Having an online demo is a really good idea because with it we can show the world how Symfony works without installaling anything. It's a kind of *interactive* tutorial.

**Comment by javiereguiluz** [comment]
The Symfony Demo application is already promoted prominently in the Download page:

![symfony_demo_application](https://cloud.githubusercontent.com/assets/73419/10365097/de5e768c-6dc0-11e5-8d36-ec422cb0933d.png)

The proposal to rewrite the Quick Tour using the Demo application should be tackled in a different issue/pull request. That's why I think we can close this issue as "fixed". Thanks.

**Comment by xabbuh** [comment]
@javiereguiluz What do you think about updating the "What is Symfony?" section too as @WouterJ suggested?

**Comment by javiereguiluz** [comment]
We can close this issue as "fixed". For now we're not going to show the Demo app in more pages. We'll do that in the future, when we revamp the Quick Tour for example. Thanks!

**Comment by weaverryan** [comment]
cool :)
