### ISSUE TITLE
Update docs for the new Welcome Page

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5549]
We're working on adding back a "Welcome Page" for new Symfony apps. See https://github.com/symfony/symfony-standard/pull/834

We should show and mention this "Welcome Page" in the Quick Tour, the installation chapter and any other appropriate page.

**Comment by javiereguiluz** [comment]
I'll take care of this issue myself :)

**Comment by javiereguiluz** [comment]
This can be closed as fixed by #5628

**Comment by WouterJ** [comment]
You are able to close these issues as well, @javiereguiluz. Don't worry about closing obviously fixed issues like this, you're part of the deciders team :)

**Comment by stof** [comment]
@WouterJ he is not flagged as repo collaborator. Are you sure he has the access to close it ? (well, this one yes as he is the author)
