### ISSUE TITLE
[2.7 BC break] Assetic-bundle throws error message in prod environment

### ISSUE THREAD

**Issue by XitasoChris** [symfony/symfony-docs#5565]
When using the Assetic bundle to manage assets, I get an exception in prod environment:

> Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Symfony\Bundle\AsseticBundle\Templating\StaticAsseticHelper::__construct() must be an instance of Symfony\Component\Templating\Helper\CoreAssetsHelper, instance of Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper given, called in /srv/www/htdocs/myproject/app/cache/prod/appProdProjectContainer.php on line 307 and defined" at /srv/www/htdocs/myproject/vendor/symfony/assetic-bundle/Templating/StaticAsseticHelper.php line 33

From having a look at the code, it seems the problem is that in 2.7 the `templating.helper.assets` service has a different type:
> The templating.helper.assets was refactored and returns now an object of the type Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper instead of Symfony\Component\Templating\Helper\CoreAssetsHelper. You can update your class definition or use the assets.packages service instead. Using the assets.packages service is the recommended way. The templating.helper.assets service will be removed in Symfony 3.0. ([UPGRADE-2.7.md](https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.7.md))

The Assetic bundle requires an instance of the (now deprecated) `Symfony\Component\Templating\Helper\CoreAssetsHelper` ([StaticAsseticHelper.php:33](https://github.com/symfony/AsseticBundle/blob/master/Templating/StaticAsseticHelper.php#L33)) but is now given the new class `Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper`.

This change was introduced in commit [f74a1f2dc34d8b141e1f4bfbbfa1dbb7d955fe42](https://github.com/symfony/symfony/commit/f74a1f2dc34d8b141e1f4bfbbfa1dbb7d955fe42).

It seems to me this is a backwards compatibility break which should be fixed for Symfony 2.7. Or do you think that the AsseticBundle should simply update their type hint (which also fixes the problem)?

**Comment by XitasoChris** [comment]
Sorry, just realized that I created this in the wrong project. Recreated at https://github.com/symfony/symfony/issues/15381 .

Please close/delete this issue.

Thanks!

**Comment by stof** [comment]
@XitasoChris you can close it yourself

**Comment by stepanets** [comment]
Hi, I've got the same error after update symfony from 2.3 to 2.7.2. This error occurs when I call `foreach ($view['assetic']->javascripts(array(...` in my php template. Is it bug or should I make something to fix it?

**Comment by XitasoChris** [comment]
@stepanets This issue is closed, please add any further comments to the linked issue in the symfony project.

To fix the problem temporarily, see http://stackoverflow.com/a/31670848/447490.
