### ISSUE TITLE
Enforce HTTPS for the documentation

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5590]
If I did not miss anything, we use HTTPS to refer to the Symfony documentation from external resources (for example, in the code repository). However, it is still possible to access the documentation via HTTPS **and** HTTP (see FriendsOfSymfony/FOSUserBundle#1909). In my opinion, accessing the documentation via plain HTTP should always redirect to the HTTPS version.

/cc @javiereguiluz

**Comment by javiereguiluz** [comment]
We can close this issue as "won't fix". For now we don't plan to "force redirect" HTTP to HTTPS, neither for the docs nor for the rest of the website. Of course we'll reevaluate this decision periodically in the future. Thanks for understanding it.
