### ISSUE TITLE
[RFC] Change the recommended location for the license file in shared bundles

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#5599]
When writing the best practices for shared bundles years ago, the documented rule was to put the license file in ``Resources/meta/LICENSE``.
In https://github.com/symfony/symfony-docs/pull/5014#discussion_r25121421 I suggested to change this rule to also allow having it at the root, as this is a common convention and even well-known bundles are doing this (DoctrineBundle for instance).

However, there is a new reason to encourage having it at the root: Github is introducing a [new API](https://developer.github.com/v3/licenses/) to be able to know the license of a repository. They are doing this because they want to improve the usage of licenses among repos published on Github: https://github.com/blog/1964-open-source-license-usage-on-github-com
But according to examples I found about it, it expects the file to be at the root. I tried with SensioGeneratorBundle (which has the license file in ``Resources/meta``) and the license API returns that the license is not found.

Given that most shared bundles are available on Github, it would make sense to recommend putting the license at the root of bundles rather than deep inside them.

what do you think @symfony/deciders ?

**Comment by lsmith77** [comment]
+1

**Comment by fabpot** [comment]
:+1:

**Comment by xabbuh** [comment]
makes sense

**Comment by fabpot** [comment]
I would recommend it to be **only** in the root directory and allow it to be in the meta directory for BC reasons.

**Comment by stof** [comment]
@fabpot agreed. this matches my idea.

**Comment by dunglas** [comment]
+1

**Comment by stof** [comment]
What do you think about making a blog post on symfony.com to announce this new recommendation (once we have the doc updated for it) ? It could help having bundles switching to the new location.

**Comment by Tobion** [comment]
ref #4335
