### ISSUE TITLE
PHP minimum version requirement changed from Symfony 2.6.9 to 2.6.10

### ISSUE THREAD

**Issue by alexdomsa** [symfony/symfony-docs#5602]
There is an inconsistency between the minimum PHP version specified in the  "Requirements for Running Symfony" doc for Symfony 2.6.* and the actual one. 

In the document is specified "PHP needs to be a minimum version of PHP 5.3.3" which is true for version between 2.6.0 and 2.6.9.
Upgrading to Symfony 2.6.10 or 2.6.11, I saw in composer.json that minimum PHP version is set to 5.3.9

I don't know exactly if it is an issue in symfony-documentation or the issue is in symfony repository (meaning that they shouldn't have changed PHP minimum version from 2.6.9 to 2.6.10 or 2.6.11).

**Comment by xabbuh** [comment]
I think we should update the documentation.

**Comment by xabbuh** [comment]
Hm, looking at this again, I don't think there is an issue at. Symfony 2.6 still requires PHP 5.3.3 as the minimum version: https://github.com/symfony/symfony/blob/2.6/composer.json#L19

**Comment by alexdomsa** [comment]
Hmm, I saw that last week, but when installing on local environment, the composer.json was looking different. 
I tried today a fresh install of Symfony 2.6.10 and 2.6.11 and it specifies the correct PHP version.

**Comment by alexdomsa** [comment]
I will close this task.

**Comment by WouterJ** [comment]
Maybe you installed 2.7, which indeed bumped the requirement to 5.3.9?

**Comment by alexdomsa** [comment]
I have tried with 2.6.10 and 2.6.11 and both installs were requiring 5.3.9
After some days, when I retried, the specified version was 5.3.3
It is strange, but at least it's fixed now. Maybe it was some branch-alias which messed up the install (just a supposition)
