### ISSUE TITLE
Add cookbook entry about uploading and validating multiple files

### ISSUE THREAD

**Issue by Koc** [symfony/symfony-docs#5603]
http://symfony.com/doc/current/cookbook/controller/upload_file.html missing info about option `multiple=true`
http://blog.arithm.com/2014/11/24/validating-multiple-files-in-symfony-2-5/

**Comment by OskarStark** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Here it is another recent article about this topic: http://www.theodo.fr/blog/2015/07/manage-multiple-files-upload-in-symfony/

**Comment by OskarStark** [comment]
> Here it is another recent article about this topic:
> http://www.theodo.fr/blog/2015/07/manage-multiple-files-upload-in-symfony/
>

Great article

**Comment by javiereguiluz** [comment]
Closing this in favor of the file uploading meta-issue: #8255.
