### ISSUE TITLE
var-dumper docs

### ISSUE THREAD

**Issue by glensc** [symfony/symfony-docs#5604]
looks like var dumper docs are missing!

```
07:43:20  glen> hi, there's some bug: vardumper.summary: http://symfony.com/components
07:43:30  glen> as well subpages http://symfony.com/components/VarDumper
08:00:47  jrobeson> glen, file it in the symfony docs repository
```

**Comment by stof** [comment]
This content is coming from https://github.com/symfony/symfony-marketing

**Comment by xabbuh** [comment]
@glensc Thank you for reporting the missing description. I'm gonna close here in favor of symfony/symfony-marketing#272.
