### ISSUE TITLE
internal web server ran with dev environment by default 

### ISSUE THREAD

**Issue by rmed19** [symfony/symfony-docs#5611]
Hi,
In the chapter "Create your First Page in Symfony" of the Symfony book, "Creating a Page: Route and Controller" section, "What's the app_dev.php in the URL?" paragraph : it's mention that http://localhost:8000/lucky/number execute app.php file, but by default the internal web server ran with dev environment only if we specify another environment when executing the server:run command. So http://localhost:8000/lucky/number execute app_dev.php by default.

Thx.

**Comment by WouterJ** [comment]
This is now fixed by #6239
