### ISSUE TITLE
I want to fix typo but can not find page in docs repository

### ISSUE THREAD

**Issue by dkop** [symfony/symfony-docs#5626]
The link for page http://symfony.com/doc/bundles/
Also page doesn't have link "Edit this page"

**Comment by WouterJ** [comment]
These are hardcoded in a private GitHub repository. If you show the typo here and ping @javiereguiluz (one of the guys with access to this repository), it'll be fixed on the next deploy.

For now, I'm closing this as it isn't something we can fix (but feel free to leave a comment).

**Comment by dkop** [comment]
@javiereguiluz 
Typo in: controllers based <b>d</b>on Doctrine entities

**Comment by javiereguiluz** [comment]
@dkop thanks for reporting this typo. It's fixed now. However, as explained by Wouter, we'll need to wait for the next website deploy. Thanks!
