### ISSUE TITLE
Installation documentation needs to be fixed

### ISSUE THREAD

**Issue by JVerstry** [symfony/symfony-docs#5627]
Hi, while going through the installation documentation (https://symfony.com/doc/current/book/installation.html) to create a symfony application, I ran into an issue I have reported on stackoverflow (http://stackoverflow.com/questions/32027702/symfony-error-no-route-found-for-get-app-example).

It needs a small fix at the bottom of the page. The http://localhost:8000/app/example link should be replaced with http://localhost:8000/.

**Comment by Nek-** [comment]
Looks like the version of symfony is wrong too. The recommanded version is 2.7, not 2.3.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. We've updated the installation chapter in #5628.

@Nek- I don't understand your comment. Where do we recommend to install 2.3 version? Thanks!

**Comment by Nek-** [comment]
@javiereguiluz here in the command:

```
composer create-project symfony/framework-standard-edition my_project_name "2.3.*"
```

**Comment by jzawadzki** [comment]
@Nek- as I see it, it's only an example of showing possibility of installation of specific version (not recommending any version)
> If you need to base your application on a specific Symfony version, provide that version as the second argument of the create-project command:

Also 2.3 is still current LTS so no problem of it being there.

**Comment by Nek-** [comment]
@jzawadzki maybe I'm wrong but i think the last LTS is [2.7](http://symfony.com/roadmap)

**Comment by jzawadzki** [comment]
@Nek- yes - of course - 2.7 - I still live in 2.3 world ;)
