### ISSUE TITLE
http://api.symfony.com/2.7 redirects to http://api.symfony.com:8080/2.7/

### ISSUE THREAD

**Issue by andrewnicols** [symfony/symfony-docs#5653]
Visiting the versioned API link _without_ a trailing slash causes a redirect to the correct path, but with port 8080 added to the URI.

**Comment by xabbuh** [comment]
ping @fabpot @javiereguiluz

**Comment by xabbuh** [comment]
Any news on this?

@lyrixx Are you able to help us (not sure who's the right person to ping about this issue)?

**Comment by javiereguiluz** [comment]
This error has been finally fixed :tada: so we can close this issue. Thanks!

**Comment by xabbuh** [comment]
Thanks!

**Comment by Sofianio** [comment]
Why is http://api.symfony.com/ redirecting me to github now?
I want the api doc!

**Comment by javiereguiluz** [comment]
@Sofianio I'm afraid the Symfony API doc was removed a few weeks ago and now we redirect to GitHub directly.

**Comment by Sofianio** [comment]
@javiereguiluz That's very unfortunate, I found the api doc more simple to understand than the official documentation
