### ISSUE TITLE
Broken link in serializer documentation 

### ISSUE THREAD

**Issue by tiemevanveen** [symfony/symfony-docs#5671]
FYI This link is broken on this page: http://symfony.com/doc/current/components/serializer.html

![image](https://cloud.githubusercontent.com/assets/1330668/9637723/a75be21c-51a2-11e5-83e6-f156fd7a18c2.png)

I can't find the right target.

**Comment by stof** [comment]
the link you give in the title of the issue (which is a bad place to put an URL btw, as it is not clickable) is *not* a documentation page but an edition form in Symfony.

**Comment by stof** [comment]
hmm, regarding the issue, I think this is related to the fact that api.symfony.com only shows API doc for classes tagged as ``@api``.
@fabpot can this be changed ? It is causing issues in the documentation regularly (it is unexpected to be unable to link to the API of some classes). We also got the same issue about protected methods not being displayed while they are extension points which should be documented (and the documentation current expects to be able to link to them, see the discussion in https://github.com/symfony/symfony-docs/pull/5553)

**Comment by tiemevanveen** [comment]
> which is a bad place to put an URL btw, as it is not clickable.

You're right. Fixed 

> the link you give is not a documentation page but an edition form in github.

Check

**Comment by xabbuh** [comment]
I am not sure if this issue is really related to the `@api` tag. We removed them recently and apparently the API docs are still there.

**Comment by javiereguiluz** [comment]
I think we can close this issue as "fixed". The link now works as expected:

![api_link](https://cloud.githubusercontent.com/assets/73419/11868112/e6be27e2-a4b5-11e5-8ee6-0d61d2680473.gif)

**Comment by xabbuh** [comment]
Yes, works for me too.

**Comment by tiemevanveen** [comment]
Jup, works. Thanks for fixing.

**Comment by SpacePossum** [comment]
:+1:
