### ISSUE TITLE
[ExpressionLanguage] improve the range operator description

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5679]
see https://github.com/symfony/symfony/pull/15560#issuecomment-135727783

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because I don't know how can we improve the doc for the range operator. By default it's only useful in combination with the `in` operator, as shown in the example. Reopen if you disagree and please, provide some ideas for a better example. Thanks!
