### ISSUE TITLE
[Form] Mention DataMappers or add a cookbook entry how to use them

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony-docs#5686]
@webmozart published a [blog post](https://webmozart.io/blog/2015/09/09/value-objects-in-symfony-forms/) that shows how to use custom data mappers. They are useful when a form is bound to an object that does not provide getters and setters in a symmetrical way but needs to be treated differently on reading and writing. Immutable value objects are the predominant example.

Now I may be missing something, but it seems as if the term "DataMapper" appears *nowhere* in the documentation, something that might be worth improving.

**Comment by xabbuh** [comment]
You are absolutely right @mpdude. However, we already have #5459 which takes care that we don't miss this so I am closing here. Thanks again anyway.

**Comment by mpdude** [comment]
Oops I missed that. Thanks!
