### ISSUE TITLE
[RFC][Security] Better usage of "encoding" and "hashing" terms

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5688]
Matt Brunt mentioned [in this Twitter discussion](https://twitter.com/TheMattBrunt/status/641929155626561536):

> "even if you already have some passwords encoded using a different cost" - Dear Symfony documentation: encoding !== hashing

Although we use `encoder` term extensively (because of the `security.yml` configuration) we may review the explanations to see if we could use instead the `hashing` term in some cases, which is more common when talking about passwords.

**Comment by xabbuh** [comment]
I agree that we can be more careful in choosing the right terms in the Security documentation.
