### ISSUE TITLE
Strange authorization checker example

### ISSUE THREAD

**Issue by greg0ire** [symfony/symfony-docs#5693]
In [this §](http://symfony.com/doc/current/cookbook/security/voters.html#how-to-use-the-voter-in-a-controller), the code snippet shows how to get the authorization checker, but not how to use it. I guess `denyAccessUnlessGranted` probably uses it internally, but that is confusing.

**Comment by xabbuh** [comment]
Thanks for reporting this @greg0ire. This should be fixed now by #5711.
