### ISSUE TITLE
Session should be retrieved from Request object rather than constructed

### ISSUE THREAD

**Issue by AndrewCarterUK** [symfony/symfony-docs#5694]
In the [session management documentation](http://symfony.com/doc/current/components/http_foundation/sessions.html) ([source](https://github.com/symfony/symfony-docs/blob/2.8/components/http_foundation/sessions.rst)), an example is given of a Session object being constructed from defaults.

This falls back on using the native session storage method, which is basically a wrapper for the $_SESSION superglobal. This similar to doing Request::createFromGlobals() whenever you need the request object!

I'm currently working on a technique for keeping Symfony applications alive between HTTP request cycles. Applications written using code such as that featured in this example present a problem to the project.

I think that the example source code should be changed so that all examples show the session being obtained by calling Request::getSession(). The documentation for configuration of sessions should also be changed to show how to configure the session service, rather than how to change the constructor arguments of the session object.

If others agree, I can spend some time sorting out a pull request - though that might be better left to someone with experience writing symfony documentation.

Interested to hear your thoughts,

Andrew

**Comment by stof** [comment]
This code is for the component itself. In such case, there is nothing ensuring that the Session object got injected in the Request object. there is a listener in HttpKernel to do it when using the kernel.
the Session object still needs to be implemented somewhere (you should indeed not create the Session object in the place where you use it, but in a single place).

And configuring the session service has not its place in the component doc, as component docs are about using the component itself, not FrameworkBundle.

**Comment by AndrewCarterUK** [comment]
This makes sense - it'll be confusing for users though as it's the first result when searching for Symfony sessions.

Would it be appropriate to add a note directing users of the full stack framework to [this documentation](http://symfony.com/doc/current/book/controller.html#managing-the-session) or even just mentioning that they shouldn't be constructing the session object in this way?

Also, even in the cookbook, examples are given showing the session object being constructed rather than obtained from the request: http://symfony.com/doc/current/cookbook/session/proxy_examples.html
