### ISSUE TITLE
Moving the suggested license file location for bundles to the bundle root?

### ISSUE THREAD

**Issue by jrobeson** [symfony/symfony-docs#5697]
What do folks think about the current suggested location of the license files? Currently that would be Resources/meta, but I think it'd be better placed in the bundle root directory.

**Comment by stof** [comment]
already done: https://github.com/symfony/symfony-docs/issues/5599

**Comment by stof** [comment]
See http://symfony.com/doc/current/cookbook/bundles/best_practices.html#directory-structure

**Comment by jrobeson** [comment]
oh good. i figured I would have noticed that. guess not :)
