### ISSUE TITLE
Documentation should not reference external BCrypt tool

### ISSUE THREAD

**Issue by AndrewCarterUK** [symfony/symfony-docs#5698]
Currently [the documentation](http://symfony.com/doc/current/book/security.html#c-encoding-the-user-s-password) suggests using [this online tool](https://www.dailycred.com/article/bcrypt-calculator) to generate BCrypt hashes.

Although this tool may have been set up with the best of intentions - we have no way of proving that the operator is not farming the input BCrypt hashes (or that the service has not been compromised).

I think these references in the documentation should be removed, as it is not a good security practice to generate password hashes like this.

**Comment by stof** [comment]
now that we have the commands to generate password hashes in Symfony 2.7+, we should recommend it instead of suggesting the online tool.

**Comment by xabbuh** [comment]
I agree with @stof. Additionally, we can add a warning on the `2.3` branch to address the concerns raised by @AndrewCarterUK.
