### ISSUE TITLE
[Announcement] Documentation translations will be removed soon

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5699]
In the past we've talked a lot about the translations of the Symfony Documentation, so we won't repeat the same arguments here. We'd like to announce that, after much thought, we've made a decision: any non-English documentation will be removed from symfony.com website.

We appreciate the work made by our French and Italian friends and we ask them to not be upset about this decision. Your work is not wasted because the original documentation has a very liberal license which allows you to publish the translations in your own websites (that's for example what the Spanish, Japanese, Brazilian, etc. communities do).

We'll make the needed changes in the coming days and we'll set up the appropriate redirections to avoid 404 errors for the current translated doc pages.

Thank you all for understanding this decision.

**Comment by xabbuh** [comment]
The [blog post has been published](http://symfony.com/blog/discontinuing-the-symfony-community-translations) so we no longer have to keep this open. Thanks @javiereguiluz for announcing it here in advance.
