### ISSUE TITLE
Circular as well as not-present mention in the choice_list section of the Form Type Reference

### ISSUE THREAD

**Issue by afoeder** [symfony/symfony-docs#5712]
In http://symfony.com/doc/current/reference/forms/types/choice.html#choice-list, it says

> The choice_list option of ChoiceType was deprecated in Symfony 2.7. You should use choices or choice_loader now.

But `choices` says to better use `choice_list`(that's the circular mentioning); and there can nothing be found named `choice_loader`.

**Comment by stof** [comment]
this is an issue in the documentation of ``choices`` in 2.7+ then.

and ``choice_loader`` should indeed be documented

**Comment by xabbuh** [comment]
Thank you for reporting this, Adrian. However I will close here nonetheless as we already have an issue for this (see #5179).
