### ISSUE TITLE
Add a cookbook about writing custom profiler panels with support for several profiler versions

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#5716]
When redesigning the profiler and the toolbar, I put a constraint on allowing third-party bundles to support the old and the new design at the same time in their own panel (so that they don't have to drop support for Symfony <2.8 when updating to support the new design).

We need to document this feature to make bundle authors aware of it. The explanation about how it works is available in https://github.com/symfony/symfony/pull/15160#issuecomment-126271208.
Note that the recommended usage of the variable should be documented, to ensure your bundle works fine when we bump the variable in the future (the comment I linked assumes a case where we bumped it several times in the future to explain how it would work).

**Comment by stof** [comment]
@javiereguiluz given that you have some experience on updating bundles to support the new profiler, you may be the right guy to work on this.

Regarding the location of the explanation, I don't know whether it should go into http://symfony.com/doc/current/cookbook/profiler/data_collector.html or in a separate cookbook. I will let the doc team decide on it.

**Comment by javiereguiluz** [comment]
I will take care of this. I want to also document the new elements which can be used by profiler panels (metrics, toggler, etc.)  But first, I need this other PR to get merged: #5592  Thanks!

**Comment by javiereguiluz** [comment]
I'm closing this because, sadly, it's too late (this article would only be important if your bundle supports both 2.7 and newer Symfony versions). Relevant bundles which include profiler panels are already using Symfony 3 ... and soon they'll use Symfony 4, so this article wouldn't be useful for them. Thanks!
