### ISSUE TITLE
Add webserver configuration for Plesk

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-docs#5718]
Edit: Workaround here: https://github.com/symfony/symfony-docs/issues/5718#issuecomment-157139438

**Comment by xabbuh** [comment]
I am not in favor in adding more information here (I also think that Plesk is not the right tool to manage your server, but you should use the command line instead). Though let's see what others think about this.

@JHGitty Do you have some explanations (other references) why these changes are necessary?

**Comment by JHGitty** [comment]
Did not get working static files with the above solution yet. Maybe somebody has any idea how to fix it.

The issue is that you can not use "location /" nginx configuration in Plesk. That is a basic issue on Plesk but there are a lot of providers here in Germany who are using the Plesk system for their customers. The customers are able to add the "nginx additional configuration".

I need any way to bypass "location /".

Original:
```nginx
location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
```

My try to bypass:
```nginx
if (!-f $request_filename){
    rewrite ^/(.*)$ /app.php last;
}
```

But this solution seems to have issues with static files? I am not sure. Maybe here is any specialist for nginx webservers.

I think it would be great to have any solution. **If we not add it to the official documentation we should have any workaround here for users from Google.**

**Comment by javiereguiluz** [comment]
If the only change needed is about the location, I'm :+1: to add these lines commented:

```
# uncomment these lines if you can't override the "/" location (e.g. when using Plesk)
# if (!-f $request_filename){
#     rewrite ^/(.*)$ /app.php last;
# }
```

**Comment by JHGitty** [comment]
@javiereguiluz I am not a specialist for nginx webservers. Will it work correctly?
If yes: Why to use `try_files` if the other code does the same?

**Comment by JHGitty** [comment]
It works fine on production mode (= app.php). But app_dev.php is not working anymore.

Does anybody have an idea how to fix this issue?

**Comment by JHGitty** [comment]
Working solution:
1. Enable 'Smart static files processing'
2. Enable 'Serve static files directly by nginx'.
3. Use the following additional nginx configuration.

For production:
```nginx
if (!-f $request_filename){
    rewrite ^/(.*)$ /app.php last;
}
```

For development:
```nginx
if (!-f $request_filename){
    rewrite ^/app_dev.php(.*)$ /app_dev.php last;
    rewrite ^/(.*)$ /app.php last;
}
```

**Comment by JHGitty** [comment]
There is an official request to the Plesk developers to fix this issue. But this may take a while.

I don't think that this issue will be fixed in the next months.

Please vote here to let the official Plesk developers know that you really need an official fix: https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/13072257-nginx-remove-location-directive-from-de

**Comment by davidwieler** [comment]
Voted! 
Simply silly how they thought including a default `location / {}` was a good idea.

**Comment by JHGitty** [comment]
So you tried out ``location = / {}`` as workaround on Plesk 12.5 (or higher)? That might be great! In this case we could even use the official Symfony documentation and just change it to ``location = / {}`` syntax.

**Comment by JHGitty** [comment]
Thanks - it works! :+1:

**Comment by JHGitty** [comment]
@davidwieler The workaround works fine except for the path ``/``. Do you know why?

I disabled  the options ``Smart static files processing`` and ``Serve static files directly by nginx`` and I've used this configuration:

```nginx
location = / {
	try_files $uri /app.php$is_args$args;
}

# PROD
location ~ ^/app\.php(/|$) {
	internal;
```

**Comment by davidwieler** [comment]
@JGGitty I ended up having to do some rewrites, and adding some stuff to change the way slashes are handled. I'm not sure if this will help you, but here is everything I added into my Plesk settings:

merge_slashes on;

```
## Make sure everything is forwarded to https://
if ($scheme = http) {
	return 301 https://$server_name$request_uri;
}

## Remove trailing slashes
rewrite ^/(.*)/$ /$1 permanent;

## If the index.html (can be anything) is looked for, redirect to /
rewrite ^(.+)/index.html$ $1 permanent;

location = /index.html {
	internal;
	error_page 404 =301 $scheme://msgable.com/;
}
location = / {
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-MSGABLE 'test';
	proxy_pass https://127.0.0.1:8484;
}
location ~ / {

	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_pass https://127.0.0.1:8484;

}
```

**Comment by JHGitty** [comment]
Adding this code does **not** help:
``rewrite ^/(.*)/$ /$1 permanent;``

**Comment by davidwieler** [comment]
Possible solution to auto-downloaded php files: [Nginx serves .php files as downloads, instead of executing them(http://stackoverflow.com/questions/25591040/nginx-serves-php-files-as-downloads-instead-of-executing-them)

**Comment by javiereguiluz** [comment]
Let's close this old issue because none of doc maintainers use that server and we cannot validate or review or maintain this change. Besides, it looks like they should first solve the issue reported here: https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/13072257-nginx-remove-location-directive-from-de  Thanks!
