### ISSUE TITLE
[Config] Ability to use a service to check for the freshness of cache entries

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5723]
This feature was added in symfony/symfony#15738. #5136 should probably written before to save duplicated work.

**Comment by weaverryan** [comment]
@mpdude What do you recommend that we do for this? Can you write something? Or do you at least have a quick highlight of the parts you think are most important?

thx :)

**Comment by javiereguiluz** [comment]
I'm closing this because the main article where this should be added doesn't exist. I've added it to the list of things to document in the #5136 meta issue.
