### ISSUE TITLE
Gulp Cookbook article

### ISSUE THREAD

**Issue by samsch** [symfony/symfony-docs#5725]
I think it would be helpful to have an article on basic Gulp setup with Symfony. I have setup Gulp with Symfony twice now, and it would be good to have a set structure for asset destination and source, and the method of replacing Assetic.

I dropped Assetic entirely, and put my assets in app/Resources/assets under js and sass folders. I setup my Gulp tasks to run sass, uglify, concat, and sourcemap before dumping the files in web/css and web/js/min. My vendor assets are pulled directly from the vendor/bower or node_modules/ folders (I setup one project with only npm, but I kept bower in the other).

Once configured, I run gulp watch when I need to work on assets, and my assets are in testable form and ready for production.

I have git ignore node_modules, but otherwise include app/Resources/assets/\* and web/ in my repo, so no need for Gulp on the production system.

If I had the time to expend on this, I would write the article and pull request myself. As it is, I can share some of my gulpfiles and changes made to templates for including files if it would help someone else make this.

**Comment by xabbuh** [comment]
I think this is a good idea. We already have an article about Bower in the front-end section of the cookbook and an article about Gulp would in my opinion fit there quite well.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because since this article was proposed, Gulp is no longer considered the best practice and all projects are moving to Webpack (including Laravel, Rails, etc.)  Besides, we'll announce some news around this "soon". Stay tuned ... and thanks for understanding this decision.
