### ISSUE TITLE
Update voter documentation for supportsAttribute and supportsClass deprecation

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#5728]
See symfony/symfony#15151

This may only be `components/security/authorization.rst`

**Comment by Koc** [comment]
`cookbook/security/voters.rst` also requires changes

**Comment by weaverryan** [comment]
Further updated at symfony/symfony#16601

**Comment by weaverryan** [comment]
PR added

**Comment by weaverryan** [comment]
Ah, the `best_practices/security.rst` also needs to be updated.
