### ISSUE TITLE
[Console] The interactive shell is deprecated

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5729]
The interactive shell will be deprecated in Symfony 2.8 (see symfony/symfony#15892) and we should reflect the fact in the documentation (it is described in the cookbook).

**Comment by Tobion** [comment]
Code Removed in symfony/symfony#15936

**Comment by xabbuh** [comment]
@Tobion and I talked about this and we thought that it could be a good idea to remove the documentation for this feature in older branches too.

@javiereguiluz @weaverryan @WouterJ What do you think?

**Comment by WouterJ** [comment]
Afaik, our normal plan with deprecations is to show a big caution box before the description of a deprecated feature in older versions and only remove it in the 3.0 version. I think we should do the same here.

**Comment by javiereguiluz** [comment]
I agree with @WouterJ.

**Comment by weaverryan** [comment]
This is already merged :)
