### ISSUE TITLE
[Readability] Make all docs compatible with reader

### ISSUE THREAD

**Issue by dupuchba** [symfony/symfony-docs#5732]
Hi everyone, 

As a Safari user I use a lot a feature called Reader that make articles look awesome (specially if you want to focus), see below.

<img width="1279" alt="capture_d ecran_2015-09-27_a_13_00_19" src="https://cloud.githubusercontent.com/assets/911705/10122380/d656372e-6517-11e5-9661-2a883ed5dcfd.png">

It does work well on "The Book" section of Symfony documentation.

For some reasons, this feature **is not enable on other sections (The Cookbook, Components).**

**Does anyone have any ideas why ?**

Thanks a lot :-).

**Comment by xabbuh** [comment]
I did some quick research and from what I read on https://mathiasbynens.be/notes/safari-reader it could be that our cookbook articles simply are too short to make them compatible with the Reader feature.

**Comment by dupuchba** [comment]
I've read this one (from 2010), but how do you explain **The Component** part ?

**Comment by dupuchba** [comment]
OK, I've checked in many places in the doc, it's pretty random...

**Comment by dupuchba** [comment]
I close this one as I didn't find any valuable doc explaining the process for safari to have reader
