### ISSUE TITLE
[WCM] Remove the "full-stack web framework" references

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5737]
When [this PR](https://github.com/symfony/symfony-standard/pull/860) gets merged, Assetic will be removed from the Symfony Standard Edition. Then, we'll need to reword some parts of the Symfony documentation (and the website).

If I understand these changes right, moving asset management to pure frontend tools would mean that Symfony (or at least the Symfony Standard Edition) is no longer a "full-stack" web framework but just a "server-side framework".

**Comment by gnugat** [comment]
I've always wondered if "full-stack" referred to the use of (almost) all Symfony components, or to the type of website built (full-stack vs frontend / backend separation).
Depending on the intended meaning we can either remove it, rename it, or add some explanations.

**Comment by javiereguiluz** [comment]
I understand "full-stack web framework" as something that lets you build an entire web site or web app from scratch.

**Comment by javiereguiluz** [comment]
Closing this issue because Symfony will still be a full-stack framework after Assetic removal. You can't combine, compile or minimize web assets with Symfony ... but you can still serve web assets with Symfony.
