### ISSUE TITLE
DI extensions implementing the CompilerPassInterface will be processed automatically

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5738]
With the `ExtensionCompilerPass` from symfony/symfony#13761, container extensions implementing the `CompilerPassInterface` will be executed automatically during compilation of the container.

**Comment by stof** [comment]
Your description is wrong. They don't implement a new interface (which does not exist). they implement the existing ``CompilerPassInterface`` (and we have a new ``ExtensionCompilerPass`` used in the component automatically and responsible for the new feature)

**Comment by xabbuh** [comment]
Oh, good catch. Thanks @stof.

**Comment by xabbuh** [comment]
see #5920 for the PR
