### ISSUE TITLE
Reorganize the documentation about asset management

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#5739]
Currently, the Symfony doc gives first-class citizenship to Assetic. Because of https://github.com/symfony/symfony-standard/pull/860, this is not a good idea anymore.

So here are my proposal:
- documentation which talks purely about Assetic should be moved to Assetic itself (I don't know whether we have such content)
- documentation for AsseticBundle should be moved to the bundle and rendered in the bundle section, as done for other bundle
- we should have a cookbook article about the way to manage assets, showing several options:
  - using gulp/grunt/whatever and then referencing the output of the build (as far as Symfony is concerned, gulp or grunt don't exist)
  - mentionning Assetic can be used for a pure php solution (if you end up using node-based tools, using gulp/grunt is better than piping it through Assetic), with a link to the documentation of the bundle.

what do you think about this ?

**Comment by xabbuh** [comment]
:+1: This totally makes sense. We already started to document front-end tools (Bower is already published) and someone asked (see #5725) for documentation for gulp recently).

**Comment by stof** [comment]
IMO, we should not have an article explaining the usage of gulp itself. We should have an article explaining how to use an external build tool (which can be gulp, grunt, browserpack, or whatever else). Otherwise, we would either have the same article for all of them, or we would be documenting gulp itself, which is a bad idea (linking to the glup doc is much better for that, as it is maintained by the gulp team, and so is uptodate)

**Comment by javiereguiluz** [comment]
Closing it because this proposal is "deprecated" now that we have Webpack Encore. We've created lots of new docs and we'll create more about managing assets with Encore. Thanks!

**Comment by stof** [comment]
Well, the work on encore actually forced us to do what was requested here: documenting how to reference assets managed by an external build tool (as Encore is such a build tool, external to the Symfony stack)
