### ISSUE TITLE
[Translation] Ability to format a message catalogue without actually writing it

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5743]
see symfony/symfony#15786

I am not sure if this really needs to be documented, but we should not lose track of it.

@aitboudad What do you think?

**Comment by aitboudad** [comment]
Indeed the chapter [Creating a Custom Dumper](http://symfony.com/doc/current/components/translation/custom_formats.html#creating-a-custom-dumper ) needs to be updated.
I'll work on it!

**Comment by aitboudad** [comment]
see #5745
