### ISSUE TITLE
Document for new SymfonyStyle and other changes?

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#5746]
@javiereguiluz I haven't been watching the `SymfonyStyle`-related changes (the class was new in 2.7) much (though I like the pretty) - is there something we should document related to this?

**Comment by javiereguiluz** [comment]
Yes, we should document all the methods available for commands (`title()`, `section()`, `table()`, etc.)  We are still deciding some code details (see https://github.com/symfony/symfony/issues/16000) but once we settle on that and test the redesigned commands, we'll start documenting everything.

To better understand what does this new style bring, I like this analogy: so far, commands mixed "CSS" and "HTML". With this new class, commands care only about "semantic HTML" and the "CSS" is automatically applied by Symfony. The result is commands with cleaner and more concise code.

**Comment by weaverryan** [comment]
@javiereguiluz and that's exactly why I'm excited about documenting them - free, good-looking styling and less styling-stuff in your code to make it happen. thx :)

**Comment by JHGitty** [comment]
Same here - I'll feel happy if the documentation is ready.

**Comment by WouterJ** [comment]
There is a PR now: #6017
