### ISSUE TITLE
Documentation for the route builder

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5748]
see symfony/symfony#15778

**Comment by weaverryan** [comment]
This is partially included in the micro kernel docs: #5899. I'm not really sure what else we need to show, most of it is kind of php-doc level stuff (what methods can I call, what arguments are there).

**Comment by javiereguiluz** [comment]
I agree with Ryan. The useful part is documented and the rest is probably too internal. Let's close.
