### ISSUE TITLE
SecurityBundle logout.target is not needed / not documented?

### ISSUE THREAD

**Issue by jonasarts** [symfony/symfony-docs#5751]
I was mislead by the SecurityBundle Full Default Configuration, showing the option

```twig
security:
    firewalls:
        somename:
            logout:
                target: /
```

which I interpreted as path or route-name, to which will be redirected on logout.

I got a solution at http://stackoverflow.com/questions/32902400/symfony-logout-target-never-applied, it's working great. But somebody with deeper knowledge than me should document this configuration option or probably remove it, if it's no longer in use?

Regard
Jones

**Comment by javiereguiluz** [comment]
@jonasarts I don't fully understand your issue. The `target` option of the `logout` section works right both for URLs and routes. You can easily test it in [the Symfony Demo application](https://github.com/symfony/symfony-demo). Just change the value of this option in `app/config/security.yml` and login + logout in the application.

**Comment by jonasarts** [comment]
Hi @javiereguiluz, I was quickly able to check the demo application. In deed it's working perfectly on my dev machine. Therefore I have probably an issue because I hooked into the logout event. I will check this on the demo application. If I can reproduce it, I will update here my results. In the meantime we can close this issue. Sorry for bothering.
Jones
