### ISSUE TITLE
Extract DebugBundle related parts from VarDumper component docs

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5754]
The documentation for the VarDumper component contains information related to the DebugBundle (see #5584). These information should be extracted into cookbook articles.

**Comment by javiereguiluz** [comment]
I'm closing this old issue as "won't fix". It's true that we mention the DebugBundle in a short section of the VarDumper component ... but that's fine. We do the same in other components (e.g. mention PropertyAccess in Serializer, Translation and Validator in Form, etc.)and even sometimes we say: *"if you use this component inside a full Symfony app ..."* so I guess this is OK. Thanks!
