### ISSUE TITLE
Document how to use xdebug.file_link_format in different environments?

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5759]
In symfony/symfony#14340 it was requested to be able to use the `xdebug.file_link_format` with a virtual machine. Is that something that we consider as a valuable contribution to the documentation (for example, explaining how to configure this value depending on your development environment)?

**Comment by BenjaminPaap** [comment]
Personally I would not expect this in a symfony documentation. My first location would be the vendor of my IDE. The time I noticed that configuration option I searched the internet on how to set up my IDE to get this thing working (I failed :smile:). And as mentioned in the comments of symfony/symfony#14340 this should be more a case for IDE vendors.

**Comment by dupuchba** [comment]
@xabbuh I think it's a good idea but I would see it in a "Tips" section

**Comment by javiereguiluz** [comment]
In my opinion we shouldn't document this in the current Symfony documentation. If we implement a new strategy for the Symfony Docs regarding the virtual machines and we start adding articles related to them, then I'd change my opinion.

**Comment by nicolas-grekas** [comment]
See #19807 for a Symfony-inside solution that is coming to 3.2

**Comment by javiereguiluz** [comment]
Closing it as fixed by https://github.com/symfony/symfony/pull/19807 and #6944.
