### ISSUE TITLE
[RFC] Add notes about the deprecation of PHP templates

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5760]
PHP templates are second-class citizens for Symfony and they will be removed from the core in 3.0. We could add some notes in 2.3/2.7 docs recommending the reader not to use PHP templates in their applications.

**Comment by xabbuh** [comment]
What do you actually think about dropping the PHP template examples at all (at least from the `master` branch)? It seems that noone from the documentation team actively uses PHP templates and when it comes to more than really simple examples we would probably struggle to spot any mistakes in them.

**Comment by javiereguiluz** [comment]
@xabbuh I agree with removing any trace of PHP templating in Symfony docs.

Meanwhile I've created #5769 to add a caution about not using PHP templates.

**Comment by WouterJ** [comment]
Closing for now, as templates are not dropped for another 2 or so years.
