### ISSUE TITLE
Traditional Login Form does not need http_basic: configuration

### ISSUE THREAD

**Issue by JVerstry** [symfony/symfony-docs#5763]
This is more like cherry on the cake rather than a fundamental issue, but the documentation available at: http://symfony.com/doc/current/cookbook/security/form_login_setup.html about creating a traditional login form seems to imply that `http_basic:` configuration is required.

My initial thought was it should not be required since a login form typically replaces basic http authentication. But, since I am not a Symfony2 expert, I asked a question on Stackoverflow at http://stackoverflow.com/questions/32990643/symfony2-is-basic-authentication-configuration-required-for-traditional-login/32990667#32990667 and someone confirmed that it is not required.

I believe we should mention this in the documentation for the sake of clarity.

**Comment by xabbuh** [comment]
Yes, I think you are right. I don't know how this slipped in, but I think we should simply remove it from the documentation.

**Comment by javiereguiluz** [comment]
This error probably originated because the article is a follo up of the security introduction. That's why you can read this phrase at the beginning:

> This chapter assumes that you've followed the beginning of the security chapter and have http_basic authentication working properly.

In any case, thanks @JVerstry for reporting this issue. A pull request to fix it is ready at #5768.
