### ISSUE TITLE
The child node “secret” at path “security.firewalls.main.remember_me” must be configured -> from code example

### ISSUE THREAD

**Issue by JVerstry** [symfony/symfony-docs#5765]
I was trying to implement the remember me feature using the documentation (http://symfony.com/doc/current/cookbook/security/remember_me.html), but I got the following error message:

    The child node “secret” at path “security.firewalls.main.remember_me” must be configured

I opened a StackOverflow question at: http://stackoverflow.com/questions/32993824/the-child-node-secret-at-path-security-firewalls-main-remember-me-must-be-co/32998125.

Someone says `key` has been replaced with `secret`. I have updated my config and indeed the error is gone, but a new one appears. The documentation needs to be updated.

**Comment by xabbuh** [comment]
Thank you for reporting this @JVerstry. The good news is that we already have an open pull request that tackles this issue (see #5761).

**Comment by xabbuh** [comment]
However, using the old config option (`key`) should still work, but simply trigger a deprecation warning. Do you really use Symfony 2.8 or did you maybe install Symfony 3.0?

**Comment by JVerstry** [comment]
When I run my app in dev mode (app_dev.php), the version in the debug toolbar at the bottom of my page is 2.8.0-DEV. The require in my composer.json is "symfony/symfony": "2.8.x-dev".

**Comment by stof** [comment]
There is a bug in the BC layer. See https://github.com/symfony/symfony/pull/16176 for the fix
