### ISSUE TITLE
Proposed Nginx configuration does not allow custom handled 404 page on URI /app.php

### ISSUE THREAD

**Issue by sustmi** [symfony/symfony-docs#5785]
Currently proposed [Nginx configuration](https://github.com/symfony/symfony-docs/blob/3c830bc4d7eca0201381cc62e21030880afd6922/cookbook/configuration/web_server_configuration.rst#nginx) does not propagate URI that starts with `/app.php` to the application. Instead, Nginx gives plain "404 Not Found" error page.

I tried to install [symfony-demo](https://github.com/symfony/symfony-demo) and use the proposed Nginx configuration.
When I go to `http://localhost/app99.php` I get custom 404 page (rendered through the application).
But `http://localhost/app.php` gives me a plain 404 error page (directly from Nginx).
The same applies to `http://localhost/app.php/anything`.

Could you change it to a configuration that propagates all URLs to the application?

**Comment by stof** [comment]
This was actually done on purpose, to hide the fact that the project uses Symfony (just like app_dev.php and config.php should not be available in your prod config, as explained in the comments). See the comment saying that you should just remove the ``internal;`` keyword to make it available for anyone.

**Comment by sustmi** [comment]
Thanks for pointing out, @stof . I completely overlooked that. 

However, I think that putting `internal;` in the config actually exposes information that the application uses Symfony.
If any non-existent URL gives me rendered 404, but `/app.php` gives me plain 404 I can pretty certainly say that the application uses Symfony.
If it gave me the rendered 404 for all non-existent URLs instead, I would have no clues about what framework the application uses.

**Comment by sustmi** [comment]
I have another problem. I am not sure if it is problem in Nginx configuration or Symfony's `Request` class. Maybe you can point me to the right direction.

I removed the `internal;` statement from the Nginx config.

Now I execute this in app.php:
```
var_dump($request->getBasePath(), $request->getBaseUrl());
```

For URL `http://localhost/app.php/non-existent/` it gives me:
```
string(0) ""
string(8) "/app.php"
```

And for URL `http://localhost/app99.php/non-existent/` it gives me:
```
string(0) ""
string(0) ""
```

When I dump `$_SERVER` it differs only in `DOCUMENT_URI` that is `/app.php/non-existent/` in the first case and `/app.php` in the second case.

**Comment by sustmi** [comment]
Just to clarify, I think that `$request->getBaseUrl()` should return empty string when I go to `/app.php/non-existent/`.

**Comment by stof** [comment]
well, that's expected, as ``http://localhost/app99.php/non-existent/`` is considered as being the ``/app99.php/non-existent/`` path in the Request, with URL rewriting enabled (so without showing the front controller in the URL when it needs to reach Symfony rather than reaching assets), while ``http://localhost/app.php/non-existent/`` is considered as being the ``/non-existent`` path in the Request, but displaying the front controller in the URL because of no front controller rewriting.
Read the difference between both methods to understand why it is not empty.

My own Nginx config is a bit different, as I never want to allow including the front controller in the URL, but I don't want to make Nginx reject ``/app.php/non-existent-urls`` (it will still reject ``/app.php`` alone though, but my config could probably be improved a bit more):

```nginx
server {
    #site root is redirected to the app boot script
    location = / {
        try_files @site @site;
    }
    #all other locations try other files first and go to our front controller if none of them exists
    location / {
        try_files $uri $uri/ @site;
    }
    
    # deny access to .htaccess, .svn .bzr .git files
    location ~ /\.(ht|svn|bzr|git) {
        deny  all;
        access_log      off;
        log_not_found   off;
    }
    
    #return 404 for all php files as we do have a front controller
    location ~ \.php$ {
        return 404;
    }
    
    location @site {
        fastcgi_pass php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/app.php;
    }
}
```

**Comment by sustmi** [comment]
I am not sure if I completely understand your reply, so I will try to reword my question.

I would like to completely hide the front controller from user, so if I enter `http://localhost/asdf` into browser I want to get:
```php
$request->getBaseUrl(); // ""
$request->getRequestUri(); // "/asdf"
```
and if I enter `http://localhost/app.php/asdf` I want to get:
```php
$request->getBaseUrl(); // ""
$request->getRequestUri(); // "/app.php/asdf"
```

Is that possible?

**Comment by peterrehm** [comment]
@sustmi you are working with the wrong calls.

            $request->getRequestUri()
            $request->getPathInfo()

Are exactly what you were looking for.

**Comment by peterrehm** [comment]
I guess this can be closed.

**Comment by sustmi** [comment]
I don't understand how does it help me @peterrehm .

With URL `http://localhost:8090/xpp.php/asdf` I get:
```php
$request->getBaseUrl() // ""
$request->getRequestUri() // "/xpp.php/asdf"
$request->getPathInfo() // "/xpp.php/asdf"
```
and with URL `http://localhost:8090/xpp.php/asdf` it is:
```php
$request->getBaseUrl() // "/app.php"
$request->getRequestUri() // "/app.php/asdf"
$request->getPathInfo() // "/asdf"
```

Don't you think that if we want to hide the existence of the front-end controller the value for these two URLs should differ only in one letter? Or to be more specific, for URL `http://localhost:8090/xpp.php/asdf` it should be:
```php
$request->getBaseUrl() // ""
$request->getRequestUri() // "/app.php/asdf"
$request->getPathInfo() // "/app.php/asdf"
```

I don't think that current behaviour fatally wrong, but it smells. And if you trace the smell you will findthe `Request::prepareRequestUri` and `Request::prepareBaseUrl` methods. The complexity is overwhelming.

**Comment by peterrehm** [comment]
Long story short whatever you need (with or without the controller name) there are methods for it available. But for sure, it is complex.

**Comment by javiereguiluz** [comment]
Let's close this stalled issue and if someone wants to propose improvements to [the current Nginx proposed config](https://symfony.com/doc/current/setup/web_server_configuration.html#nginx) please create a pull request with the changes or open an issue listing the specific problems of the current file. Thanks!
