### ISSUE TITLE
missing constraint parameter in url

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony-docs#5802]
http://symfony.com/doc/current/reference/constraints/Url.html

-> missing parameter dnsMessage

**Comment by xabbuh** [comment]
Thank you for reporting this @poolerMF.

For anyone wanting to work on this: Changes should be applied on the `2.7` branch. The `dnsMessage` option was introduced in symfony/symfony#12956 together with the `checkDns` option and controls the message that will be shown in case the DNS check failed.
