### ISSUE TITLE
Controller as service - DI configuration, Routing configuration from best practices

### ISSUE THREAD

**Issue by zdenekdrahos** [symfony/symfony-docs#5803]
After recent discussion with my colleague when we get [controller as service](https://github.com/symfony/symfony-docs/blob/25fe7374d95ce9fa0bef37a5ae95557d68e3effe/cookbook/controller/service.rst) to work I think that documentation is missing some basic information. It's hard to describe our situation so I'll give you an example.

## Example

_1._ Start fresh project with [standard edition](https://github.com/symfony/symfony-standard)
_2._ Pass twig engine to `DefaultController`

```
    private $twig;

    public function __construct(\Symfony\Component\Templating\EngineInterface $e)
    {
        $this->twig = $e;
    }
```

_3._ Of course, I get an error

```
Catchable Fatal Error: Argument 1 passed to
AppBundle\Controller\DefaultController::__construct()
must be an instance of Symfony\Component\Templating\EngineInterface, none given
```

_4._  The error remains when controller's service is registered

```
    my_test_controller:
        class: AppBundle\Controller\DefaultController
        arguments:
            - @templating
```

_5._ Read documentation once again. Follow tip *You can also use annotations to configure routing using a controller defined as a service. See the FrameworkExtraBundle documentation for details,* where I find information about registering controller as service at [the end of the page](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/routing.html#controller-as-service).

```
/** @Route(service="my_test_controller") */
```

_6._ Because I only passed `@templating` to constructor and didn't change line of code in controller I get error like

```
Error: Call to a member function get() on null
    // return $this->container->get('templating')->renderResponse($view, $parameters, $response);

Error: Call to a member function getParameter() on null
    // $this->container->getParameter('kernel.root_dir')
```

_7._ I change` $this->render` to `$this->twig->renderResponse`. but I still want to get parameter from `Symfony\Bundle\FrameworkBundle\Controller\Controller`. Error tells me that `$container` is null, so I search how could I pass container to controller:

```
        calls:
            - [setContainer, [@service_container]]
```

### 1. DI configuration, confusing routing configuration

Current documentation mentions only [routing example](http://symfony.com/doc/current/cookbook/controller/service.html#referring-to-the-service) where every route is defined in `routing.yml`. I think that is a little misleading. Best practices recommend [routing.yml + annotations](http://symfony.com/doc/current/best_practices/controllers.html#routing-configuration).

Even when I define controller as service I wouldn't use `$this->forward('my_test_controller:indexAction')` but usual route `app_default_index`. For me name of controller's service is irrelevant detail that I typically use only in `@Route` annotation.

I understand that `@Route` is from different bundle so it's documented on other page. But as you can see in the fifth step of the example it isn't easy to find information about registering controller's DI. In addition the tip mentions routing configuration, not DI configuration so I am not sure if Symfony beginner could find it.

### 2. Controller as service extends base controller

I know it sounds weird. But especially in legacy apps it is common situation that base Controller cannot be completely removed. Little note about using base controller in controller registered as service would be great. But that's a minor issue. I guess that if you come to situation like that you are usually experienced enough to solve this problem.

**Comment by xabbuh** [comment]
Thanks for reporting this @zdenekdrahos. Indeed we really need to update the routing configuration in this cookbook article (it doesn't matter that the annotation is from the SensioFrameworkExtraBundle as we use it everywhere else too).

However, I don't think we should tackle your second issue. As you said you can probably easily figure out how to do it if you really need this and on the other hand we would document something that shouldn't be considered good practice otherwise.

**Comment by stof** [comment]
IMO, your case 2 is a weird case. If you cannot migrate it to avoid using the base container-aware controller, you should not make your controller a service.

I guess most of your issues here are because you try to turn an existing controller into a service, and so you indeed have to change lots of things. It is easier to make it a service from the start. Migrating from an approach to the other is harder than trying to use a service for a new controller.

**Comment by javiereguiluz** [comment]
Recently we decided to stop promoting the concept of "controllers as services". We've removed all the mentions to them from the docs and we just maintain a dedicated article (http://symfony.com/doc/current/controller/service.html).

Do you still think we need to improve that article? Thanks!
