### ISSUE TITLE
[RFC] Combine two sections with similar content

### ISSUE THREAD

**Issue by carlos-granados** [symfony/symfony-docs#5823]
In the cookbook we have two sections ("Install and Upgrade" and "Upgrading") which include related and similar entries. I think it would make sense to merge these two sections into a single one (probably "Install and Upgrade"). Since this is not a trivial change as it requires moving and renaming several files, please let me know if you agree that this makes sense before I do the job to create a PR for this

**Comment by borisklotz** [comment]
To merge the two sections sounds absolutly reasonable as they cover identical/related topics. I would vote for it.

**Comment by carlos-granados** [comment]
@xabbuh @weaverryan @javiereguiluz, any thoughts on this?

**Comment by weaverryan** [comment]
@carlos-granados check out my comments here: https://github.com/symfony/symfony-docs/pull/5155#issuecomment-104933684

I don't care too much either way, but if they were combined, I would definitely want it called "Install and Upgrade" so both keywords are findable.

thx :)

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" because after our doc reorganization, these two sections have been merged into a new one called "Setup". @carlos-granados thanks for proposing this improvement in the first place!
