### ISSUE TITLE
[RFC] Consider using "Sentence case" for section titles

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5830]
As [explained here](http://symfony.com/doc/current/contributing/documentation/standards.html#english-language-standards), Symfony documentation uses "a variant of the title case" for the section titles. I propose to switch to using ["sentence case"](https://en.wikipedia.org/wiki/Letter_case#Headings_and_publication_titles) for titles.

Reasons to change:

  * The current casing is very complex to explain to people.
  * Its rules are arbitrary (according to [this Wikipedia article](https://en.wikipedia.org/wiki/Letter_case#Headings_and_publication_titles))
  * Even our doc managers confess to have problems understanding it.
  * It doesn't even have a name (it's called *"a variant of the title case"*)
  * It's not that common ("sentence case" is much more common)

As you can see, the features of the current title casing go against "the Symfony spirit" and common practices. The "sentence case" would be a better fit because it's standard, easy to explain and use, rational and predictable.

**Comment by xabbuh** [comment]
I tend to agree with you. I am not sure if "sentence case" is the best style, but agreeing on a style that is easier to understand and doesn't confuse contributors too much seems reasonable to me.

**Comment by WouterJ** [comment]
For titles, using title case is pretty common in the English language. Title casing is just about capitializing some words in titles. The exact rules depend on the house style. The Symfony Doc Standards is the house style guide for the Symfony documentation, so as long as it's described in there, it's not arbitrary.

I'm not really sure if closed class is such a big problem, we usually just do something and it doesn't matter if it isn't 100% correct. If we want to choose another one (to be clear, I'm not -1 against choosing another one), my vote would go for "*First word and all other words capitalised except for articles, prepositions, conjunctions and forms of to be*". This rule is close to what we have now and much easier to understand.

**Comment by javiereguiluz** [comment]
Closing it because changing this convention would require a great amount of effort. In a separate issue or pull request we can discuss about simplifying the rules of the existing practice. Thanks.
