### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by webdevsHub** [symfony/symfony-docs#5839]
There is a wrong link in `cookbook/psr7.rst` => Install section => last sentence

"Use Composer (zendframework/zend-diactoros on Packagist) or refer to the project documentation to install it."

"Packagist" links to https://packagist.org/packages/symfony/psr-http-message-bridge instead of https://packagist.org/packages/zendframework/zend-diactoros

I tried to create a PR and change it but that link is connected to "Packagist" string which is already used. So any fix would also imply a change of other parts of that document, so I created an issue

**Comment by xabbuh** [comment]
Thanks for reporting this @webdevsHub. :+1: I have created a pull request to address this issue (see #5841).
