### ISSUE TITLE
problem with document: Create Framework > The DependencyInjection Component

### ISSUE THREAD

**Issue by aliselcuk** [symfony/symfony-docs#5842]
While trying to learn Symfony, I bumped into this problem, No matter what I couldn't define any route method other than GET.

```
$sc->register('context', 'Symfony\Component\Routing\RequestContext');
```

when used like this, RequestContext ignores REQUEST_METHOD, and uses GET always. After hours of searching, found a dirty solution:

```
$sc->register('context', 'Symfony\Component\Routing\RequestContext')->addMethodCall('fromRequest', [\Symfony\Component\HttpFoundation\Request::createFromGlobals()]);
```

Maybe you would like to state and correct this somehow in the document for newcomers like me

**Comment by javiereguiluz** [comment]
@aliselcuk sorry for the delay in responding you.

You say that you stumbled upon this problem while trying to learn Symfony. However, the `RequestContext` thing is extremely advanced and requires you to dig deep into the Symfony internals. Most Symfony developers, even experienced ones, never use this class explicitly and a lot of them are even unaware of the existence of this class. In the Symfony docs, we only mention it very briefly in the HttpKernel and the Routing components.

So my question to you is: where did you find the information about this class? Why did you think this class was important to learn Symfony? Did you read this in some tutorial? Thanks.

**Comment by aliselcuk** [comment]
Thanks for the response.
I was following "Create your own framework with Symfony components" series. 
I followed them all and while playing with the result framework I noticed that framework was ignoring post request method. 

After hours of debugging the code with phpdebug I found the problem I mentioned above.

Long story short, the result code provided in http://symfony.com/doc/current/create_framework/dependency-injection.html can not handle POST routes.

**Comment by javiereguiluz** [comment]
@aliselcuk thanks for the info. Personally I think that using the book to learn Symfony is a big mistake. The reason is that the mentioned doc is very misleading: it looks easy and approachable ... but it goes as deep as one can go and therefore, it's for experienced Symfony developers.

In any case, I'll bring this issue to our next Symfony Docs meeting (due in 3 weeks). We'll discuss about how to show in the Symfony Docs index a clear path for Symfony newcomers. Thanks!

**Comment by aliselcuk** [comment]
@javiereguiluz I got your point. Thanks for taking the time to state it.
