### ISSUE TITLE
Add documentation for anonymous services

### ISSUE THREAD

**Issue by Haehnchen** [symfony/symfony-docs#5854]
Do we have any documentation for "anonymous services"? i googled some terms about this feature but not getting results on the official page. Some improvements would be nice here. :)

related: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/595

> The XML format supports anonymous services. An anonymous service is a service that does not need a name and is defined directly in its use context. It can be very convenient when you need a  service that won't be used outside of another one scope:
> http://fabien.potencier.org/symfony-service-container-using-xml-or-yaml-to-describe-services.html

**Comment by xabbuh** [comment]
I am not sure if we should really document this. Imho it's only useful for the dumpers to be able to dump the optimised container. But as the end user you don't really need this feature as making services private leads to the same anyway when the container is compiled.

**Comment by xabbuh** [comment]
And by the way, the Yaml format does not support anonymous services and won't get this feature in the future (see symfony/symfony#16328).

**Comment by HeahDude** [comment]
@xabbuh So may be this one should get closed.

**Comment by Oliboy50** [comment]
@xabbuh You're right, but this is maybe the only "syntactic sugar" for XML to compensate for its insane verbosity... It just seems sad to not document this :trollface:

**Comment by SimonHeimberg** [comment]
When "anonymous service" is undocumented, it should not be mentioned in the doc in  http://symfony.com/doc/current/service_container/service_locators.html#defining-a-service-locator

**Comment by Haehnchen** [comment]
now it should be documented; also mentioned in #7694, see also https://github.com/symfony/symfony/pull/21970

**Comment by HeahDude** [comment]
Reopening until all versions and formats are properly documented.

**Comment by javiereguiluz** [comment]
Fixed by #9909 and #10041.
