### ISSUE TITLE
Add info/examples about Business Logic

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-docs#5865]
Currently there is this Best Practice:

```
Use annotations to define the mapping information of the Doctrine entities.
```

http://symfony.com/doc/current/best_practices/business-logic.html#doctrine-mapping-information

I think there should be more information about this Best Practice.

Currently I try to work with models and only know things about entities. That because I read a lot of different blog entries and try to understand the Best Practice for models.

For example I have two entities Team and User and want to do this:

```
$team->fire($user);
```

I think it is not a good idea to mix entities and business logic - that because I need to create a "Team" model (php file in AppBundle\Model).

But then I would have duplicate properties in the model and entity (for example the name of the team).

**Maybe that because it is Best Practice to create a model, extend from it as entity and then map everything with YAML?**

Something similiar is done by FOSUserBundle.
https://github.com/FriendsOfSymfony/FOSUserBundle/tree/master/Model

What do you think?

**Comment by WouterJ** [comment]
To extract the `$team->fire($user);` logic from the entity, I would create a `UserFireHandler#fire($team, $user)` or a `TeamManager#fire($team, $user)` method or the like. This class is completely unaware of the persistence layer (and as a result doesn't need mappings) and would do something like:
```php
class TeamMember
{
    public function fireFromTeam(Team $team, User $user)
    {
        $user->setTeam(null);
        $team->getUsers()->remove($user);
    }
}
```

Having 2 classes that reference the same thing that are both persisted (which is your case if I understand it correctly) seems incorrect.

Models are often used to be able to use different backends (for instance, Doctrine ORM and MongoDB ODM). The generic parts are then extracted in a model and for the ORM/ODM specific parts the entity/document is created (which extends the generic model). **For application code** (that's the target for the best practices guide), **I recommend not to use this practice, unless you work on an application that must work with different backends.**

In the Symfony documentation, there is ["How to Provide Model Classes for several Doctrine Implementations"](http://symfony.com/doc/current/cookbook/doctrine/mapping_model_classes.html) to explain how to use mappings and models. But again, this practice is only recommended for highly flexible applications or big third party bundles like FOSUserBundle.

**Comment by JHGitty** [comment]
I think there should be some documentation about this in the official Symfony documentation. There should be some suggestions how to handle the business logic in combination with entities (or similiar). A few examples would be helpful.

**Comment by javiereguiluz** [comment]
I agree that this doc could be useful ... but it's too generic and it's not directly related to Symfony (it could be better published in the Doctrine project). Besides, there are lots of different ways to solve this and there isn't a clear winner (it depends on your circumstances, your team, your project, etc.)

So, I'm afraid I must close this as "won't fix".
