### ISSUE TITLE
Authentication Token Always Null - listener called BEFORE the security firewall

### ISSUE THREAD

**Issue by houss2040** [symfony/symfony-docs#5867]
I want to customize my errors pages : 404, 403 & 500 Code Error .

I want to show Menu in the page error according to connected user, But i cant get current user because the listener of exeption if called BEFORE the security firewall.

There is any solution to resolve this problem ?

Thanks.

**Comment by WouterJ** [comment]
Please do not use the issue trackers for support questions. Such questions should be asked on [StackOverflow](stackoverflow.com/questions/tagged/symfony2) or IRC (#symfony on freenode). The issue tracker is purely for wrong or missing docs and typos.

Btw, as far as I know, there is no solution to your problem. Whenever an error occurs before the firewall, you can't do anything (as the firewall needs the router in case a user is not authenticated). You can use an if statement to check whether the error page is called before or after the firewall (in case of an error in the controller for instance) and only display the menu when it's executed after.
