### ISSUE TITLE
Change description of the list of media types link in book/http_fundamentals

### ISSUE THREAD

**Issue by douglasnaphas** [symfony/symfony-docs#5875]
http://symfony.com/doc/current/book/http_fundamentals.html has a link to "Wikipedia's List of common media types article". The destination of the link is https://www.iana.org/assignments/media-types/media-types.xhtml. There does not appear to be a list of common media types on Wikipedia, so the text "Wikipedia's List of common media types article" should be changed to "IANA's list of common media types".

**Comment by WouterJ** [comment]
I would change "A list of common media types can be found on Wikipedia's List of common media types article." to ``You can see a `list of common media types`_ on IANA.`` Can you maybe make the change (by clicking on the "Edit" button and changing the sentence + the reference name at the bottom of the article)?

**Comment by douglasnaphas** [comment]
@WouterJ, that change is in the pull request above.
