### ISSUE TITLE
main or default firewall ?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#5878]
https://github.com/symfony/symfony-standard/blob/2.8/app/config/security.yml#L16

http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

maybe the docs are out of date and default changed to main ?

**Comment by xabbuh** [comment]
Thank you for reporting this @flip111. Technically, it is not important how we name the firewall. But it indeed would be easier to understand if we followed the same names as the code. So we should update our example(s).
