### ISSUE TITLE
New article "How to upgrade your bundle to Symfony 3.0"

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5879]
### Problem

Symfony 3.0 is approaching fast. If you've tried to upgrade your apps to Symfony 3, you've probably failed because none of the popular bundles is compatible with Symfony 3 yet.

### Solution

Let's create a short article explaining how to make third-party bundles compatible with Symfony 3.

### What we need from you

Ideas, comments and proposals to outline the contents of that article. Once the outline is ready, I'll try to write the article so we can review it and publish it as soon as possible. Thanks!

**Comment by javiereguiluz** [comment]
Some ideas of things we should explain:

  * How to test your bundle in a Symfony 3.0 application *(it's not that easy right now becuase things are very unstable ... for example I cannot make the Symfony Demo app work for 3.0)*
  * How to check for deprecated features used in your bundle.
  * Reference documents explaining all the deprecated Symfony features *(the UPGRADE.md files should be enough)*
  * How to set up Travis to test your bundle for both Symfony 2 and 3.

**Comment by weaverryan** [comment]
Is there a model bundle (`composer.json`, `.travis.yml`, needing to do any weird things to keep compatibility with 3.0, but also older versions) that can be used as a model?

**Comment by javiereguiluz** [comment]
Our friend @WouterJ has set up a public list with the current Symfony 3 support of the most popular bundles: https://docs.google.com/spreadsheets/d/1GOxJ2lNpLxN12YyZ87Bhsxb0iLAQ7e4UDZbJSly8Sy8/edit#gid=0

**Comment by theofidry** [comment]
@javiereguiluz can we add any bundle to it or should we go through a process of some kind for that?

**Comment by javiereguiluz** [comment]
Wouter told me that it's OK if the community adds their own bundles. We just started with the Top 30.

**Comment by WouterJ** [comment]
I think we should not add any random bundle from KNPbundles on the list as, let's face it, there are many bundles that have a very limited user group and maintaince. I think it's important to have most of the popular/widely used bundles in the list.

**Comment by dudemelo** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Another thing we should mention:

  * Install this: composer require --dev "symfony/phpunit-bridge"

**Comment by WouterJ** [comment]
* Don't use `Kernel::VERSION_ID` to check the API version, check the specific component. E.g. for the OptionsResolver API rewrite (2.6), use `method_exists('Symfony\Component\OptionsResolver\OptionsResolver', 'setDefined')` (most of the time, can be shortend as `method_exists($resolver, 'setDefined')`. For the Form component type name refactoring and everything related to that (2.8), use `method_exists($this, 'getBlockPrefix')` in form types or `class_exists('Symfony\Component\Form\Util\StringUtil')`.

**Comment by iltar** [comment]
@javiereguiluz I was searching for some docs on it but all I could find was this: http://symfony.com/blog/new-in-symfony-2-7-phpunit-bridge

I simply ran the install and it worked though. The weird thing is,  it's also in symfony/symfony thus I expected it to be working already, but it didn't. I had to manually add it to require-dev before it did anything. https://github.com/symfony/symfony/tree/2.8/src/Symfony/Bridge/PhpUnit

**Comment by iltar** [comment]
Okay small addition to my previous reply, it's kind of confusing how the bridge is integrated into the framework and phpunit. I found some docs on https://github.com/symfony/phpunit-bridge but I could find 0 documentation via google besides of that. I went to this repository and searched for `phpunit-bridge` to end up on this page: http://symfony.com/doc/current/cookbook/upgrade/major_version.html

Maybe something could be done to index this page a bit better?

**Comment by umpirsky** [comment]
@javiereguiluz I started a tool to help with the upgrade https://github.com/umpirsky/Symfony-Upgrade-Fixer.

I hope people will recognize the potential and contribute fixers. That will make tool more useful for everyone. If you mention it in the article, I think that will help. :)

**Comment by javiereguiluz** [comment]
I can work on this tomorrow morning ... or at least I can try to bootstrap the article.

**Comment by WouterJ** [comment]
I just added it to my list for tomorrow evening, but if you want to do it @javiereguiluz feel free to do so :)

**Comment by TomasVotruba** [comment]
Just wondering, is these similar *sheets* initiative for Symfony 4?
I would love to help with upgrading with @RectorPHP
