### ISSUE TITLE
Use ContainerAwareTrait

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-docs#5884]
```
The AppBundle\Menu\Builder class extends Symfony\Component\DependencyInjection\ContainerAware that is deprecated since version 2.8, to be removed in 3.0. Use the ContainerAwareTrait instead.
```

Code from documentation:
http://symfony.com/doc/master/bundles/KnpMenuBundle/index.html#method-a-the-easy-way-yay

Maybe there are more code examples which should use ContainerAwareTrait.

**Comment by JHGitty** [comment]
rel https://github.com/KnpLabs/KnpMenuBundle/issues/290

**Comment by xabbuh** [comment]
@JHGitty Did you find an example in the docs that is not related to the KnpMenuBundle or should we close here in favour of the issue you linked?

**Comment by JHGitty** [comment]
@xabbuh https://github.com/symfony/symfony-docs/search?utf8=%E2%9C%93&q=ContainerAware

**Comment by WouterJ** [comment]
Both cases should be changed to extend `Symfony\Bundle\FrameworkBundle\Controller\Controller` instead. Can you make that change @JHGitty? (as you should get the credits!)

**Comment by JHGitty** [comment]
Anybody can do it :-) I have not much time for it.

**Comment by stof** [comment]
@WouterJ no, they should not extend Controller. They are not controllers. They should use the trait

**Comment by WouterJ** [comment]
@stof unless I'm missing something, both search results are controllers.

**Comment by JHGitty** [comment]
@stof WouterJ is talking about these lines:
https://github.com/symfony/symfony-docs/search?utf8=%E2%9C%93&q=ContainerAware

Both are controllers: FriendMessageController and MainController.

**Comment by stof** [comment]
ah sorry, indeed
