### ISSUE TITLE
Wrap all '@' [at] symbols in yaml with single quotes

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#5910]
In 2.8, unwrapped `@` symbols are deprecated. We need to update that across the docs. I think this is already a standard, but I don't know if we're following it everywhere.

**Comment by xabbuh** [comment]
I am pretty sure it is because the Sphinx lexer uses the Yaml 1.1 spec and otherwise wouldn't render them with pretty syntax highlighting.

**Comment by WouterJ** [comment]
See https://github.com/symfony/symfony-docs/pull/5911 (IIRC, Yaml 1.1 only forbits to use `@` as the first character in a string)

**Comment by xabbuh** [comment]
Tha's true but even the YAML 1.2 spec only mark them as reserved as the first character in an unquoted sring (see http://www.yaml.org/spec/1.2/spec.html#id2774157).
