### ISSUE TITLE
Ambiguity on Access Decision Manager's Strategy

### ISSUE THREAD

**Issue by thedamnedrhino** [symfony/symfony-docs#5912]
There currently two articles concerning the AcessDecisionManager's Strategy, [the one from the Security Component](http://symfony.com/doc/current/components/security/authorization.html#access-decision-manager) and [the One from the Cookbook](http://symfony.com/doc/current/cookbook/security/voters.html#changing-the-access-decision-strategy). Reading the description of the ***affirmative*** strategy, I noticed that these two don't match. The one from the Security Component states:
> grant access as soon as any voter returns an affirmative response.

which means make the decision as soon as any voter ***grants*** **OR** ***denies*** access.  
But according to the one from the cookbook:
> This grants access as soon as there is one voter granting access.

Which is self explanatory but is in contradiction with the former description of this strategy.  
 I have found this latter description to be Correct.

**Comment by xabbuh** [comment]
Thank you for opening this issue @thedamnedrhino. Honestly, to me "any voter returns an affirmative response" sounds the same as "any voter grants access". But I would be happy to use the same sentence here as in the cookbook if that makes thinks more clear (which actually is the goal of our documentation :)).

**Comment by thedamnedrhino** [comment]
You're right actually, I had an incorrect understanding of the meaning of `affirmative`.

**Comment by xabbuh** [comment]
Well, I think that's a reason to think about changing that sentence. There are probably more (non-native speaker) people who feel the same and if we can help understanding the docs by choosing a different wording, then imo that's the way to go.

**Comment by WouterJ** [comment]
Let's use "grants access" instead of "affirmative" in the cookbook (while it explains the naming of the strategy, it's not a basic-english word and we can easily work around using it)
