### ISSUE TITLE
[Important] Configuration blocks no longer shown on symfony.com

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#5918]
@javiereguiluz 

The configuration block directives seems to be no longer shown on symfony.com. See for instance http://symfony.com/doc/current/book/security.html "Initial security.yml Setup" after the first paragraph (but they are missing everywhere).

Seems like something there is some mismatch between versions or the like (the versions used on travis/platform.sh are working correctly, you can maybe use them as a reference?).

**Comment by iltar** [comment]
I quote from IRC:
> \<Grox\> Hello. Do somebody knows, why the main Doctrine User class is absent here http://symfony.com/doc/current/bundles/FOSUserBundle/index.html#a-doctrine-orm-user-class ?

Could this be related?

**Comment by weaverryan** [comment]
@iltar yep, it looks like that issue is also from this

**Comment by lunetics** [comment]
Got force to download the symfony-docs and Compile it by hand
Am 30.11.2015 15:53 schrieb "Ryan Weaver" <notifications@github.com>:

**Comment by javiereguiluz** [comment]
I have good and bad news.

Good news: config blocks have started to appear again on symfony.com. Example: http://symfony.com/doc/current/book/security.html

Bad news: we could have more issues like these during the next days until we find a definitive solution for this. I'm really sorry.

**Comment by weaverryan** [comment]
Thanks - let's keep an eye on it.

**Comment by stof** [comment]
@javiereguiluz it is bad news to have such surprise during a release+hackday week...

**Comment by xabbuh** [comment]
@javiereguiluz So I guess we can close this and other related issues now. Is that right?

**Comment by javiereguiluz** [comment]
Yes. Things seem to be stable ... and we'll do some changes in the near future to make them better. Thanks.

**Comment by ogizanagi** [comment]
Some blocks are still missing apparently :/. For instance, on http://symfony.com/doc/master/cookbook/templating/global_variables.html.

**Comment by xabbuh** [comment]
Another example: http://symfony.com/doc/2.7/cookbook/session/sessions_directory.html (see #6036)

ping @javiereguiluz

**Comment by javiereguiluz** [comment]
The error reported in this issue is fixed. We've probably fixed all the other related errors as well.
