### ISSUE TITLE
[2.7+] Installation hint for required php-extensions phar

### ISSUE THREAD

**Issue by Brutus5000** [symfony/symfony-docs#5919]
Hi guys,

I have a suggestion for the installation doc:
It would be great if you could add the hint that the phar-extension for php is required to be active to run "symfony new my_new_project".

Otherwise you get no response from calling symfony in the shell. I only found out because i used the suggested workaround using composer. Composer gives you a hint.

I don't know whether phar is active in php on default. On my synology nas it's definitely not active on default.

**Comment by xabbuh** [comment]
Imo such a change makes sense. We can simply add a note directive to relevant sections of the documentation:

```rst
.. note::

    Please make sure that the `phar extension`_ is installed and enabled.
    Otherwise, the installer will simply return without doing anything nor
    giving you any output.
```

And add the bottom of the changed files add this then:

```rst
.. _`phar extension`: http://php.net/manual/en/intro.phar.php
```

Thanks for reporting this @Brutus5000.
