### ISSUE TITLE
Some code samples are not displayed 

### ISSUE THREAD

**Issue by gayanath** [symfony/symfony-docs#5932]
http://symfony.com/doc/current/book/routing.html

Please see the attached screenshot. There should be a code sample in "Basic Route Configuration" (verified via Google cache) but it's not displayed. Tested in Chrome and Firefox in a Mac and Chrome in a Nexus 5.
<img width="761" alt="code-sample-missing" src="https://cloud.githubusercontent.com/assets/3097902/11463487/6e8d5c12-9776-11e5-8365-fc1cea5d11ac.png">

**Comment by javiereguiluz** [comment]
@gayanath thanks for reporting this issue. We're working to solve this as soon as possible.

**Comment by xabbuh** [comment]
Thank for reporting the issue @gayanath. However, I am closing here as we already have #5918 to keep track of this bug. Thank you!
