### ISSUE TITLE
"configuration-block" code blocks completely missing from symfony.com

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#5933]
@javiereguiluz See http://imgur.com/YUK84Fa from https://symfony.com/doc/current/book/security.html#b-configuring-how-users-are-loaded

All `configuration-block` directives aren't rendering at all on symfony.com right now. Is it from the update made recently? Bad timing on this :)

**Comment by javiereguiluz** [comment]
Sadly you are right. All `configuration-blocks` are gone. We're trying to fix it and rest assure we consider this super urgent.

**Comment by WouterJ** [comment]
Closing as duplicate of #5918

**Comment by xabbuh** [comment]
Looks like they are missing again.

**Comment by fabpot** [comment]
Fixed now.
