### ISSUE TITLE
[2.8] Document new form features

### ISSUE THREAD

**Issue by althaus** [symfony/symfony-docs#5934]
As a followup of #5179: The [news](http://symfony.com/blog/new-in-symfony-2-8-form-improvements) list new features in the form component. Would be great to update the reference accordingly:

- [x] Added the prototype_data option to collection type
- [x] Added choice_translation_domain option for date-related types (this is missing in general for 2.7)
- [x] Allowed to return null for query_builder
- [x] Foundation 5 form theme

Ping @weaverryan

Cheers
Matthias

**Comment by weaverryan** [comment]
Thanks @althaus - I've marked this for 2.8 (as most of it is relevant to 2.8) and marked it as actionable.

**Comment by althaus** [comment]
OK. Will check if I can do some basics on this one again.

**Comment by WouterJ** [comment]
Fyi, I've check (4) as it's now mentioned in http://symfony.com/doc/current/cookbook/form/form_customization#what-are-form-themes The others seem to be still valid. Please note that the `choice_translation_domain` has now documentation, so it's simply a case of including the option in the date related articles.

**Comment by HeahDude** [comment]
Second box can be checked now :)

**Comment by WouterJ** [comment]
The last open points is about http://symfony.com/doc/current/reference/forms/types/entity#query-builder It should be documented to accept returning null. See http://symfony.com/blog/new-in-symfony-2-8-form-improvements#allowed-to-return-null-for-query-builder for more details.

It should be kept short and straight-to-the-point, like "You can return null to achieve X".

**Comment by JonEastman** [comment]
@WouterJ I'll give the last point a shot!

**Comment by HeahDude** [comment]
@WouterJ Please close this one :) Thanks to everyone!

**Comment by xabbuh** [comment]
Yeah, this is finished now!
