### ISSUE TITLE
A lot of configuration blocks have disappeared from documentation

### ISSUE THREAD

**Issue by michaelperrin** [symfony/symfony-docs#5936]
Hi!

A lot of configuration blocks have disappeared from the Symfony documentation.
They are still in the `rst` files, but they are simply not displayed, and I didn't find the reason.

Example: http://symfony.com/doc/current/book/security.html and look for this sentence:

> The default configuration looks like this

And there is no default configuration below (although the RST file has it in its source).
Almost all pages are concerned. Do you have any idea on reason of this issue?

**Comment by javiereguiluz** [comment]
@michaelperrin thanks for reporting this error. Sadly we are aware of this big problem and we are working on it.

---

@xabbuh, @WouterJ please don't close this issue as "duplicated" because we're getting lots of reports for this error. If people see this issue in the the GitHub issue list, chances are that they don't report it again. Thanks.

**Comment by michaelperrin** [comment]
Thanks @javiereguiluz, I looked for an other issue when opening it, and didn't see an existing one indeed.

**Comment by WouterJ** [comment]
@javiereguiluz but they can already see the original issue in the issue list?

**Comment by javiereguiluz** [comment]
@WouterJ no, because people only look at the first issue :(  The best proof is that we've received lots of repeated reports for this error.

**Comment by stof** [comment]
@WouterJ depending on where they search, they might be searching only among *open* issues

**Comment by WouterJ** [comment]
@stof there is an open issue: https://github.com/symfony/symfony-docs/issues/5918

**Comment by fabpot** [comment]
Fixed now.
