### ISSUE TITLE
[documentation] Php header missing in an example code

### ISSUE THREAD

**Issue by ottoshmidt** [symfony/symfony-docs#5937]
An example code for controllers.php from chapter Symfony versus Flat PHP (http://symfony.com/doc/current/book/from_flat_php_to_symfony2.html#add-a-touch-of-symfony) should contain <?php 
header somewhere at the top (Listing 2-17 in the pdf book, p. 21).

**Comment by xabbuh** [comment]
Thank you for reporting this @ottoshmidt.

Actually, I am not sure if we weren't better off with removing the opening tags in this chapter too like we do in all other parts of the documentation. Imho it doesn't add much value but only causes confusion if we mix different styles.

**Comment by WouterJ** [comment]
:+1: for removing all opening tags.
