### ISSUE TITLE
PDF download of book gives 404

### ISSUE THREAD

**Issue by blackholegalaxy** [symfony/symfony-docs#5939]
Hi everyone, 
While trying to download the book as PDF, browser send me to this url: https://symfony.com/pdf/Symfony_book_3.0.pdf?v=4

Which, actually, gives a 404 error.

Maybe there is a problem with PDF rendering of the books. It seems that the same issue occurs with cookbook.

**Comment by xabbuh** [comment]
Thanks for reporting this @blackholegalaxy.

@javiereguiluz Can you have a look here?

**Comment by mheki** [comment]
also the same 404 error can be found with https://symfony.com/pdf/Symfony_book_2.8.pdf

**Comment by blackholegalaxy** [comment]
In fact it seems every pdf generated by website is affected.

**Comment by javiereguiluz** [comment]
I'm sorry for the lack of response here, but the SymfonyCon conference has blocked me from doing anything else. I'll take care of this soon.

**Comment by blackholegalaxy** [comment]
NP. If this can help, please note not every PDF is affected. Old generated PDF seems to work properly. E.g: http://symfony.com/pdf/Symfony_book_2.7.pdf (generated on sept 25) seems to work fine.

**Comment by fabpot** [comment]
I've just fixed this issue. All PDFs are now up-to-date and ones for the latest versions are also available now.

**Comment by WouterJ** [comment]
:+1: Thanks @fabpot
