### ISSUE TITLE
Removed option deep in Validator/Valid is still present

### ISSUE THREAD

**Issue by janedbal** [symfony/symfony-docs#5944]
[Valid constraint](https://github.com/symfony/symfony-docs/blob/3.0/reference/constraints/Valid.rst) has deprecated option ```deep``` since 2.5 and it was removed in 3.0. The deprecation isn't mentioned in previous versions of docs and the removed option are still documented in 3.0

**Comment by xabbuh** [comment]
That's good catch @janedbal! Thank you very much for reporting this. What we actually need to do is to mark the option as deprecated in the `2.7` branch (older branches are not maintained anymore except for `2.3` which is not affected by this) and after that entirely remove the option from the `3.0` branch.
