### ISSUE TITLE
Symfony 3 docs states PHP minimum version is 5.3 while composer requirement is 5.5

### ISSUE THREAD

**Issue by felipsmartins** [symfony/symfony-docs#5947]
Reading symfony 3 docs, in [Requirements for Running Symfony](http://symfony.com/doc/current/reference/requirements.html) page, it's possible to see the minimum php version required is is 5.3, while composer defines  php >= 5.5 as minimum requirement, see:

![sf3-composer-](https://cloud.githubusercontent.com/assets/454116/11565655/a61dd58c-99bd-11e5-90ee-a3d6a90d6ac8.png)

In docs:

![sf3-req-docs](https://cloud.githubusercontent.com/assets/454116/11565689/c86bec3c-99bd-11e5-8e2b-292a2e4765df.png)

It seems that there is some inconsistency, right?
it strikes me that Symfony docs needs some update.

**Comment by WouterJ** [comment]
This has now been fixed by #5948. Thanks for such a detailed issue @felipsmartins!
