### ISSUE TITLE
Installing the ClassLoader component with Composer makes installing the ClassLoader component largely irrelevant

### ISSUE THREAD

**Issue by hpierce1102** [symfony/symfony-docs#5949]
Installing the ClassLoader component by using Composer brings in Composer's own ClassLoader, which has significant overlap with Symfony's ClassLoader. 

There's a note on [The PSR-4 Class Loader](http://symfony.com/doc/current/components/class_loader/psr4_class_loader.html) page suggesting that the loader should only be used when Composer is not available - but it looks like this is relevant to the PSR-0 and ClassMap loaders too. I think it would be more clear if this note were moved to the [introduction page](http://symfony.com/doc/current/components/class_loader/introduction.html).

It would also make things more clear if we tweaked the install instructions to promote `$ git clone` rather than using `$ composer require symfony/class-loader`.  This would be more consistent with the documentation pages that follow that use `require_once '/path/to/src/Symfony/Component/ClassLoader/ClassLoader.php';` instead of `require_once vendor/autoload.php`

**Comment by javiereguiluz** [comment]
I agree ... but given that this component will be deprecated soon, in #7383 I propose to add just a note about this, instead of making all the changes proposed in this PR.
