### ISSUE TITLE
Navigation hides part of the titles

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5950]
When you follow some anchors (for example, when you visit http://symfony.com/doc/current/components/http_kernel/introduction.html#component-http-kernel-kernel-controller), the title of that anchor is partially hidden due to the sticky navigation:

![symfony com](https://cloud.githubusercontent.com/assets/1957048/11602849/de1d4da2-9add-11e5-9220-50b054c365b0.png)

This is probably due to the fact that the download button is below the actual navigation items. I experienced this with Firefox 42 on Ubuntu.

ping @javiereguiluz

**Comment by javiereguiluz** [comment]
The main problem is that we added a new menu item called `Search`, so on very small screens the Download button no longer fits. This is really hard to fix without changing a lot of things. Let's see if someone comes up with some ideas.

**Comment by javiereguiluz** [comment]
We can close this issue as "won't fix". The menu items are "untouchable" and the logo and download button must be displayed too. Sadly this issue has no easy solution.

**Comment by xabbuh** [comment]
@javiereguiluz Wouldn't it be acceptable to display the "Download" button "outside" the content container (to its right for example)?

**Comment by javiereguiluz** [comment]
@xabbuh sadly we cannot do that because it would mean a lot of changes to the underlying HTML/CSS markup. However, I've done some tweaks to reduce the padding a top and to remove the icon of the *Download* button. Hopefully this will improve the situation for some people (but it may be useless to you).

**Comment by xabbuh** [comment]
@javiereguiluz Great! This looks good again now!
