### ISSUE TITLE
Update the security documentation for Symfony 2.8

### ISSUE THREAD

**Issue by jonasarts** [symfony/symfony-docs#5967]
As 'intention' is no longer supported as security configuration since Symfony 2.8, this setting should now be replaced in the online documentation with the csrf_token_id setting (and not only in the upgrade file).

https://github.com/symfony/symfony/pull/16722
http://symfony.com/doc/current/reference/configuration/security.html

Regards, Jonas

**Comment by WouterJ** [comment]
This is fixed some weeks ago with https://github.com/symfony/symfony-docs/pull/6152 Thanks for submitting this issue!
