### ISSUE TITLE
Rendering a Template example lists non-new use statement as "new"

### ISSUE THREAD

**Issue by dangoodspeed** [symfony/symfony-docs#5969]
In the example on
http://symfony.com/doc/current/book/page_creation.html#rendering-a-template-with-the-service-container

It says
`    // --> add this new use statement`
`    use Symfony\Bundle\FrameworkBundle\Controller\Controller;`

When it's not a new use statement.  I'm a beginner reading through the docs, but I _think_ it's the wrong use statement.

**Comment by ogizanagi** [comment]
Actually, I would rather say that the previous examples extend the Controller class, and so have this use statement too soon.

The shown controller should should only extends the base `Symfony\Bundle\FrameworkBundle\Controller\Controller` one in the ["Rendering a Template (with the Service Container)"](http://symfony.com/doc/current/book/page_creation.html#rendering-a-template-with-the-service-container) section IMO.

**Comment by dangoodspeed** [comment]
Took me a while to figure out what @ogizanagi  meant (I'm a beginner), but yes I agree... removing all mentions of
`    use Symfony\Bundle\FrameworkBundle\Controller\Controller;` and ` extends controller` from the LuckyClass for the first five sample codes on the page_creation site would make the learning process a bit easier for those new to Symfony like myself.

**Comment by ogizanagi** [comment]
@dangoodspeed : I've suggested those changes in the above PR. Thanks !
