### ISSUE TITLE
[3.0] Form component documentation says to use classes SessionCsrfProvider and DefaultCsrfProvider, which were removed in 3.0

### ISSUE THREAD

**Issue by OJezu** [symfony/symfony-docs#5971]
In documentation of form component for 3.0 version the whole CSRF Protection is wrong:

http://symfony.com/doc/current/components/form/introduction.html#csrf-protection

Classes SessionCsrfProvider and DefaultCsrfProvider were removed from Form Component in 3.0
https://github.com/symfony/form/blob/2.8/Extension/Csrf/CsrfProvider/DefaultCsrfProvider.php#L14

**Comment by xabbuh** [comment]
Good catch @OJezu. In fact we need to update the document in the `2.7` branch to use the new classes from the Security CSRF component instead (the replacing classes are referenced in the deprecation notices of the legacy classes).

**Comment by xabbuh** [comment]
see #6077 for the pull request

**Comment by vincentaubert** [comment]
ping @xabbuh I have just rebased the branch with latest 2.7 changes see #6077. Is it ok for you to merge ?
