### ISSUE TITLE
API docs for 2.8 are missing

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5975]
Currently, the API docs for Symfony 2.8 (and probably 3.0) are missing from api.symfony.com.

ping @javiereguiluz @fabpot

**Comment by Hanmac** [comment]
like in my referenced ticket, some API docs for master is missing too. (and something is even missing for 2.7)

**Comment by weaverryan** [comment]
ping @javiereguiluz!

**Comment by fabpot** [comment]
I've just generated the new API docs for 2.8 and 3.0 and removed API docs for unmaintained versions.

**Comment by xabbuh** [comment]
Perfect! Thank you @fabpot!
