### ISSUE TITLE
Broken links in "Custom Save Handlers" of "Configuring Sessions and Save Handlers"

### ISSUE THREAD

**Issue by xurshid29** [symfony/symfony-docs#5976]
These links are broken in "Custom Save Handlers" section:
[PdoSessionHandler](http://api.symfony.com/3.0/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.html), [MemcacheSessionHandler](http://api.symfony.com/3.0/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcacheSessionHandler.html), [MemcachedSessionHandler](http://api.symfony.com/3.0/Symfony/Component/HttpFoundation/Session/Storage/Handler/MemcachedSessionHandler.html), [MongoDbSessionHandler](http://api.symfony.com/3.0/Symfony/Component/HttpFoundation/Session/Storage/Handler/MongoDbSessionHandler.html), [NullSessionHandler](http://api.symfony.com/3.0/Symfony/Component/HttpFoundation/Session/Storage/Handler/NullSessionHandler.html)

**Comment by ogizanagi** [comment]
This issue is related to #5975

**Comment by xabbuh** [comment]
@ogizanagi is right about that. So I am closing here as a duplicate, but thank you anyway for reporting this issue @xurshid29. That's really appreciated!
