### ISSUE TITLE
PDF on web Symfony site "not found"

### ISSUE THREAD

**Issue by Krazitchek** [symfony/symfony-docs#5978]
Hello, downloadable PDF Symfony 3 documentation on Symfony web site does not work, pdf are missing:

"Document not found
This document does not exist for the 3.0 Symfony version"

Could you fix this please ?

**Comment by xabbuh** [comment]
ping @javiereguiluz

**Comment by WouterJ** [comment]
Duplicate of https://github.com/symfony/symfony-docs/issues/5939

**Comment by javiereguiluz** [comment]
I've asked about this and I'm waiting for the response (sadly this is something I cannot fix myself).

**Comment by fabpot** [comment]
I've just fixed this issue. All PDFs are now up-to-date and ones for the latest versions are also available now.
