### ISSUE TITLE
Session save handling config is a little all over the place

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#5985]
When trying to link to how to use custom session handlers from somewhere, I realized it's explained in many places. Suppose I want to show someone how they can use the `framework.session.handler_id` to use PDO, or redis for session handling. We have many potential links:
- http://symfony.com/doc/current/cookbook/session/sessions_directory.html (only shows file storage options)
- http://symfony.com/doc/current/cookbook/doctrine/pdo_session_storage.html (specific to PDO)
- http://symfony.com/doc/current/components/http_foundation/session_configuration.html (is component docs, so no actual service config stuff)

The reference section links to http://symfony.com/doc/current/cookbook/doctrine/pdo_session_storage.html, which is actually the best article on the topic. Perhaps we make it just a little bit more generic to mention the other options?

**Comment by javiereguiluz** [comment]
Fixed by #11027, which consolidates most of the basic session stuff in the reference `/session.rst` article.
