### ISSUE TITLE
Unexpected "stylesheets" tag

### ISSUE THREAD

**Issue by itrascastro** [symfony/symfony-docs#5986]
Testing Symfony 3 I get this error when I follow this example:

http://symfony.com/doc/current/cookbook/assetic/asset_management.html#cookbook-assetic-including-css

Code:

    {% stylesheets 'css/*' filter='cssrewrite' %}
    <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}

Error:

    Unknown "stylesheets" tag in ::base.html.twig at line 14

**Comment by WouterJ** [comment]
As of Symfony 2.8, the AsseticBundle is no longer included in the Symfony Standard Edition. If you want to use Assetic, you have to install & register it:

 1. Execute this command: `composer require symfony/assetic-bundle`
 1. Add `new Symfony\Bundle\AsseticBundle\AsseticBundle(),` to the `$bundles` array in `app/AppKernel.php`

As it has been removed just before the 2.8/3.0 releases, we didn't update the docs yet. However, it'll be updated soon by https://github.com/symfony/symfony-docs/pull/5973

**Comment by itrascastro** [comment]
Thank you
