### ISSUE TITLE
There is no "cssrewrite" filter

### ISSUE THREAD

**Issue by itrascastro** [symfony/symfony-docs#5987]
Symfony 3
assetic-bundle installed
Following this example: http://symfony.com/doc/current/cookbook/assetic/asset_management.html#cookbook-assetic-including-css

Code:

        {% stylesheets 'css/*' filter='cssrewrite' %}
            <link rel="stylesheet" href="{{ asset_url }}" />
        {% endstylesheets %}

Error:

    An exception has been thrown during the compilation of a template ("There is no "cssrewrite" filter.")

**Comment by Deamon** [comment]
as of [this chapter](https://symfony.com/doc/current/cookbook/assetic/asset_management.html#filters) of the page you linked to, did you declare the `cssrewrite` filter in the config file?

**Comment by WouterJ** [comment]
Hi @itrascastro! Can you please use [any of the channels](http://symfony.com/support) listed on the Community support page for support questions instead of this issue list? This issue tracker should purely be used to report missing or wrong documentation. Thanks!
