### ISSUE TITLE
About How to Create Form Type Extension

### ISSUE THREAD

**Issue by richardpq** [symfony/symfony-docs#5991]
Maybe I'm wrong or I didn't understand the goal of the article, but on the documentation of  [How to Create a Form Type Extension](http://symfony.com/doc/2.8/cookbook/form/create_form_type_extension.html) after create the extension, there is a section [Using The Form Type Extension] (http://symfony.com/doc/2.8/cookbook/form/create_form_type_extension.html#using-the-form-type-extension) in which I would think the extension that has been created will be used, but instead the normal FileType is used with a new option.

I'm not sure is that is the intention of the article of even if that would work in that way.

**Comment by yceruto** [comment]
@richardpq the Form Type Extension adds features on top of existing types only. In this case to FileType. You may have misinterpreted the goal.

**Comment by richardpq** [comment]
I see, perfect thanks

On Wed, Dec 9, 2015 at 11:49 AM, Yonel Ceruto González <
notifications@github.com> wrote:

> @richardpq <https://github.com/richardpq> the Form Type Extension adds
> features on top of existing types only. In this case to FileType. You may
> have misinterpreted the goal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/symfony/symfony-docs/issues/5991#issuecomment-163320902>
> .
>



-- 
*Atte.*
*Richard R. Perez Q.*
