### ISSUE TITLE
Use ContainerAwareTrait instead of own implementation

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-docs#6010]
The new ``ContainerAwareTrait`` should be used instead of an own implementation.

Example:
https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html#using-the-container-in-the-fixtures

This:
```php
class LoadUserData implements FixtureInterface, ContainerAwareInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }
```

Should be changed to:
```php
class LoadUserData implements FixtureInterface, ContainerAwareInterface
{
  use ContainerAwareTrait;
```

**Comment by xabbuh** [comment]
We do not manage the DoctrineFixturesBundle documentation in the symfony/symfony-docs repository. Their documentation is maintained in [their own repository](https://github.com/doctrine/DoctrineFixturesBundle) and simply rendered on symfony.com.

So unfortunately I have to close here and ask you to please report the issue over there. Thanks so much for noticing this anyway.

**Comment by JHGitty** [comment]
Thanks. https://github.com/doctrine/DoctrineFixturesBundle/issues/154
