### ISSUE TITLE
Updating csrf doc for Symfony 3

### ISSUE THREAD

**Issue by chinmayshah24** [symfony/symfony-docs#6031]
Hey guys,

https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md
Says this:
`The options "csrf_provider" and "intention" were renamed to "csrf_token_generator" and "csrf_token_id".`

However this is not updated here (for 3.0 version):
http://symfony.com/doc/current/cookbook/security/csrf_in_login_form.html

I hope this is the right place for reporting it.

**Comment by ogizanagi** [comment]
@chinmayshah24 : Thank you for reporting this ! Actually, there is already a PR about that, but still needs progress: #5942 . I hope there'll be news on this PR any time soon, because many users are encountering this when upgrading to Symfony 3.

**Comment by WouterJ** [comment]
Thanks for submitting this "bug" report, @chinmayshah24! Some weeks ago, https://github.com/symfony/symfony-docs/pull/6152 was merged which fixes this.
