### ISSUE TITLE
Use HTTPS on the download page

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6035]
Since #6012 the installation chapter in the book should use HTTPS to download the Symfony installer. Now we also need to update the [download page](http://symfony.com/download).

ping @javiereguiluz

**Comment by javiereguiluz** [comment]
These changes have been merged in symfony.com's source code. Now we just need to wait for the next deploy. Thanks.

**Comment by javiereguiluz** [comment]
This change is now live on http://symfony.com/download
