### ISSUE TITLE
Code blocks are missing on cookbook/session/sessions_directory.html

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#6036]
I don't see code blocks on this page: http://symfony.com/doc/2.7/cookbook/session/sessions_directory.html

I tried all the versions by using the switcher, and used Firefox and Chromium, I never saw the code.

Example of the output:

> This means that when you clear the cache, any current sessions will also be deleted:
> 
> Using a different directory to save session data is one method to ensure that your current sessions aren't lost when you clear Symfony's cache.

Here is the corresponding page in this repository: https://github.com/symfony/symfony-docs/blob/2.7/cookbook/session/sessions_directory.rst

**Comment by xabbuh** [comment]
You are right about this @alexislefebvre. I close this issue however as we keep track of it in #5918.
