### ISSUE TITLE
Add documentation for the polyfill packages

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6052]
Thanks to the different polyfill packages many PHP functions that have been introduced in recent versions can also be used in earlier PHP versions. We should create a section that explains what a polyfill is and which versions are now avaiable when using each polyfill package.

**Comment by WouterJ** [comment]
:+1: I was thinking about this as well when creating #6044.

Maybe just document it as a Symfony component in the components section?

**Comment by javiereguiluz** [comment]
Fixed by #9846.
