### ISSUE TITLE
Unit testing FormType with constructor

### ISSUE THREAD

**Issue by hackzilla** [symfony/symfony-docs#6053]
This code used to work in Symfony <= 2.7 
```php
        $userManager = $this->getMock('Hackzilla\Bundle\TicketBundle\User\UserInterface');
        $form = $this->factory->create(new \Hackzilla\Bundle\TicketBundle\Form\Type\TicketMessageType($userManager));
```

However in Symfony 3.0, the following error is thrown.

```
Symfony\Component\Form\Exception\UnexpectedTypeException: Expected argument of type "string", "Hackzilla\Bundle\TicketBundle\Form\Type\TicketMessageType" given

/ticketapp/vendor/hackzilla/ticket-bundle/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:64
/ticketapp/vendor/hackzilla/ticket-bundle/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:39
/ticketapp/vendor/hackzilla/ticket-bundle/Tests/Form/Type/TicketMessageTypeTest.php:33
```

The functionality was changed in this commit. There doesn't seem to be any mention of the above, in any change logs, only that getName was deprecated.

[[Form] removed deprecated FormType::getName()](https://github.com/symfony/symfony/commit/582f3a39b73857b0b9f5e5641a00a2f01a39c579#diff-5c1348d69be32426ff20446c9e812365R108)

I've been on the hunt for documentation that explains how to do this.

In [How to Unit Test your Forms (3.0)](http://symfony.com/doc/current/cookbook/form/unit_testing.html), the following code appears, but I can't see how it'd work.
```php
        $type = new TestedType();
        $form = $this->factory->create($type);
```

Whereas it should be passed in as a string.

```php
$form = $this->factory->create('\AppBundle\Form\Type\TestedType');
```

Though I'm still confused as to how you're supposed to do the above when your type has a constructor.

Closest I have found seems to be:

```php
class TicketMessageTypeTest extends TypeTestCase
{
    protected function getExtensions()
    {
        $userManager = $this->getMock('Hackzilla\Bundle\TicketBundle\User\UserInterface');
        $ticketMessageType = new \Hackzilla\Bundle\TicketBundle\Form\Type\TicketMessageType($userManager);

        return [new PreloadedExtension([
            $ticketMessageType->getBlockPrefix() => $ticketMessageType,
        ], [])];
    }
...
}
```

**Comment by WouterJ** [comment]
The article you reference indeed needs an update. In case the form type doesn't have dependencies, you would pass the fully-qualified class name instead of an instance.

If your form type has dependencies, the solution you proposed seems to be correct. I don't like it that much either... @webmozart do you have an alternative or an idea how we can improve testing form types with dependencies?

**Comment by hackzilla** [comment]
There is something I'm missing with the above example, as it still errors, and I the form type isn't in FormRegistry.

**Comment by webmozart** [comment]
You were on a good path already. Something like this should work:

```php
protected function setUp()
{
    $this->user = $this->getMock(UserInterface::class);
    
    parent::setUp();
}

protected function getExtensions()
{
    return array(
        new PreloadedExtension(array(
            new TicketMessageType($this->user)
        )),
    );
}

public function testFoobar()
{
    $form = $this->factory->create(TicketMessageType::class);
    
    // ...
}
```
