### ISSUE TITLE
Redirect old versions of the docs

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#6060]
It seems like old versions are removed from symfony.com (2.0, 2.1, 2.2, 2.5). We always try very hard to keep every link to the docs working (that's our BC promise if you will).

Back in the days of 2.0, 2.1 and 2.2, the version number was always in the URL (instead of the `current` keyword that is mostly used now). This means that there are lots of links including these version numbers on the web.

As these versions are removed, a 404 not found page is now shown. I think it'll be better to redirect them to a newer version number (e.g. latest in the major, 2.8) or just `current`.

/cc @javiereguiluz

**Comment by javiereguiluz** [comment]
For now I'm treating this issue as an error. In my opinion doc pages should never be removed, no matter if their versions are unmaintained. I'll keep you posted about this. Thanks for reporting it!

**Comment by xabbuh** [comment]
I think it's okay to remove them from the version switcher but at least accessing them should indeed be possible.

Thanks for looking into this @javiereguiluz.

**Comment by javiereguiluz** [comment]
Old doc pages are up again on symfony.com. The idea is to never remove an old page so links don't break and people using legacy apps can read the right docs. We just display a very clear warning message to alert the readers that this is a deprecated doc. Example:

![deprecated_doc](https://cloud.githubusercontent.com/assets/73419/12178799/b0535d66-b573-11e5-81d2-d8ca0e1d99b8.png)

**Comment by xabbuh** [comment]
Thank you Javier!
