### ISSUE TITLE
JMS/SecurityExtraBundle is referenced but cannot be installed with Symfony 3.*

### ISSUE THREAD

**Issue by cameronmurphy** [symfony/symfony-docs#6065]
JMS/SecurityExtraBundle requires `symfony/framework-bundle: ~2.1` and cannot be installed with Symfony 3.0. The 'Securing Methods Using Annotations' section suggests using it. Should the docs perhaps suggest the `@Security` annotation instead?

https://github.com/symfony/symfony-docs/blob/3.0/cookbook/security/securing_services.rst

**Comment by stof** [comment]
`` @Security`` cannot be used on services, so it cannot be suggested in this cookbook.

My suggestion is to add a note saying that the bundle is not yet compatible with 3.0 (and if you need it, you can contribute to the bundle to help updating it)

**Comment by WouterJ** [comment]
Given that the latest beta version does support Symfony 3, I think we can safely close this issue. By the time a pull request is created, submitted and merged, a stable 1.6 version is probably available.

**Comment by WouterJ** [comment]
Closing as there is a 1.6.0 release supporint Symfony 3: https://github.com/schmittjoh/JMSSecurityExtraBundle/releases/tag/1.6.0
