### ISSUE TITLE
Code example missing

### ISSUE THREAD

**Issue by aistis-** [symfony/symfony-docs#6069]
Hello,

I guess some code examples are missing at
http://symfony.com/doc/current/cookbook/routing/service_container_parameters.html
https://github.com/symfony/symfony-docs/blob/3.0/cookbook/routing/service_container_parameters.rst

**Comment by xabbuh** [comment]
ping @javiereguiluz There are still issues with some configuration blocks (see also #5918).

Thanks for reporting this @aistis-!

**Comment by javiereguiluz** [comment]
The error reported in this issue is fixed. We've probably fixed all the other related errors as well.
