### ISSUE TITLE
platform.sh service hook disabled?

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6074]
It looks like the service hook for the platform.sh preview builds is no longer triggered.

ping @fabpot @javiereguiluz

**Comment by WouterJ** [comment]
Yeah, discovered it as well.

Javier and Fabien probably can't help us out much here. @GuGuss probably can :) I looked at the settings and I can't see anything weird. Seems like it stopped working 8 days ago.

**Comment by xabbuh** [comment]
Ah well, I expected to see at least something in the status box if the hook is still activated on GitHub's end (I don't have permission to access the repo settings).

**Comment by fabpot** [comment]
Looks like Github config is fine:

![image](https://cloud.githubusercontent.com/assets/47313/11991961/7a9a10c4-aa20-11e5-99e0-d8c267fe699b.png)

**Comment by GuGuss** [comment]
Hi,

We're looking into this.

**Comment by WouterJ** [comment]
Great, thanks!

**Comment by GuGuss** [comment]
Hi,

It's now working again. We simply restarted a service which was possibly too busy to continue.

This issue can be closed :+1: 

In the future, you can also submit a support ticket so that if I'm away or not available, our support team can still help you.

**Comment by xabbuh** [comment]
Thank you very much @GuGuss!
