### ISSUE TITLE
Rename all Acme to AppBundle

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-docs#6083]
https://github.com/symfony/symfony-docs/search?utf8=%E2%9C%93&q=Acme

**Comment by WouterJ** [comment]
:-1: This is far from true. There are many valid Acme usages:

 * When talking about bundles. E.g. there are still articles talking about creating sharable bundles and including files from installed bundles. In such cases, Acme is the best vendor name.
 * The components talk about standalone usages. This means there so no bundle concept and the vendor namespace should still be used: Acme.

**Comment by JHGitty** [comment]
Oh, you are right. Thanks.
