### ISSUE TITLE
Prevent duplicate examples

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-docs#6084]
There are a few examples which are duplicated. That because some code is outdated.

For example:
http://symfony.com/doc/current/cookbook/console/console_command.html

Something similar is found here:
http://symfony.com/doc/current/components/console/introduction.html

The second code is outdated (for example it contains Acme instead of AppBundle).

Is there any way to embed code from other documentation pages or something like that?
Any idea to prevent duplicate code examples?

**Comment by xabbuh** [comment]
Well, the second example actually is not outdated. It is part of the components section which is about using the components standalone. Thus the best practices do not apply there.

**Comment by JHGitty** [comment]
Oh, you are right.
