### ISSUE TITLE
[RFC] Streamline the book chapter about forms

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6093]
### Problem

The [book chapter about Symfony Forms](http://symfony.com/doc/current/book/forms.html) tries to explain everything about them. That chapter contains 1,988 lines, more than 69,000 characters and the resulting HTML page is 33,802 pixel height. This makes the chapter overwhelming for most users, specially newcomers.

### Solution

I'd like to move most of the contents to cookbooks and show in the book just the usual form handling and rendering. In detail:

I'd maintain in the book:

  * The entire "Creating a Simple Form" section.
  * Some of the "Form Vlaidation" section (without validation groups)
  * Rendering the form (including "Rendering each Field by Hand" but not form themes)
  * Creating Form classes

I'd move to cookbooks:

  * Validation groups
  * Field types and type guessing
  * Form theming
  * Forms and Doctrine
  * Embedded Forms
  * Forms as services

---

Thoughts about this idea? Any tip about how to move those contents without breaking any existing URL? Thanks!

**Comment by xabbuh** [comment]
> Thoughts about this idea? Any tip about how to move those contents without breaking any existing URL? Thanks!

We could add a "Learn more from the cookbook" section at the end (don't we already have one), link to all the new cookbook articles there and add labels for the removed headlines above the section.

**Comment by javiereguiluz** [comment]
@xabbuh I was thinking about linking some articles inside the contents. For example: after we explain the normal form rendering, we add some links to "form theme" cookbook telling them: do you use Bootstrap or Foundation frameworks? We can format forms for you; Do you have extremely advanced needs for form rendering? Define a custom form theme; etc.

Same goes for validation. We explain the basic one and then we link to the "validation groups" feature.

But for the rest of articles, I agree about this "Learn more" section.

**Comment by xabbuh** [comment]
@javiereguiluz Sure, for those recipes where we have related content, we can link it there (and we should do that as this is most likely the place where people will search for it at first).

**Comment by javiereguiluz** [comment]
If no one opposes to this, I'll start working on it this week.

**Comment by felipsmartins** [comment]
I think it is a good idea, @javiereguiluz. Mainly the "validation groups" section which ought to fit better in a  section such as "advanced form" (IMO).

**Comment by javiereguiluz** [comment]
Closing this issue because it's too generic. We're already working on this task, but it will take us a lot of time.
