### ISSUE TITLE
Link to the Symfony CMF documentation

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6097]
IIRC before the redesign of the documentation navigation, there was a link to [the Symfony CMF documentation](http://symfony.com/doc/master/cmf/index.html) in the vertical naviation. Now this is no longer present and I do not find a way to access the CMF documentation easily from symfony.com. Can and should we do anything about this? Maybe adding an entry to [the bundles overview page](http://symfony.com/doc/bundles/).

ping @javiereguiluz @WouterJ @dbu @lsmith77

**Comment by javiereguiluz** [comment]
Yes, we'll add this link back in the doc index and maybe in the bundles page too.

**Comment by dbu** [comment]
cool. @javiereguiluz tell us if we can do anything on the symfony-cmf-docs repository side to improve integration.

**Comment by javiereguiluz** [comment]
We can close this as fixed because the CMF is now linked from the new doc index page. Thanks.
