### ISSUE TITLE
[Security-Acl] Missing docs (about updateUserSecurityIdentity() method) in 2.7, 2.8, 3.x series

### ISSUE THREAD

**Issue by felipsmartins** [symfony/symfony-docs#6099]
Browsing on Symfony ACL related issues, I found this PR: [#8650 ](https://github.com/symfony/symfony/pull/8650) (*[Security][Acl] Add MutableAclProvider::updateUserSecurityIdentity*) and its related documentation for new method: PR #3319

However, this doc update entry appears only in the doc pages of symfony 2.6 but not in 2.7, 2.8, 3.x doc pages. Look:

![selecao_176](https://cloud.githubusercontent.com/assets/454116/12077293/ea63fc2e-b1bb-11e5-88f3-32b1cd67dbdc.png)

![selecao_177](https://cloud.githubusercontent.com/assets/454116/12077296/f4a537fc-b1bb-11e5-92c7-606a6a34d3a2.png)

As this entry is an important note, why it was removed from documentation? Maybe a mistake? I've noticed "2.5 versionadded" has removed since this commit:  [Removed 2.5 versionadded as its deprecated](https://github.com/WouterJ/symfony-docs/commit/7d2f0f3cbdb753cf19c44db53883cdb27a4cf8f7)

**Comment by xabbuh** [comment]
Thank you very much for spotting and reporting this issue @felipsmartins. You are right that we should keep this information (we always remove `versionadded` for EOLed versions in the `master` branch and sometimes, like with this one, we miss that there was more important information in them that we have to keep).

I opened #6100 to fix this.
