### ISSUE TITLE
Security docs recommend usage of deprecated class

### ISSUE THREAD

**Issue by zsturgess** [symfony/symfony-docs#6103]
http://symfony.com/doc/current/components/security/secure_tools.html

In the 3.0+ version of the docs, use of the deprecated `Symfony\Component\Security\Core\Util\SecureRandom` class is still recommended.

This needs to be updated to talk about the `random_bytes()` function and the `paragonie/random_compat` package, the recommended replacement.

**Comment by zsturgess** [comment]
@WouterJ I can see my PR merged with your edits on the 2.3 branch, but not against the 3.0 branch - was merging up forgotten, or do you tend to merge up in batches on the docs repo?

**Comment by WouterJ** [comment]
@zsturgess I'm doing a merge day today. At the end of the day, I'll merge up all branches at once. Expect your changes to be live in the 3.0 docs this evening at last.
