### ISSUE TITLE
[2.3] Missing configuration example 

### ISSUE THREAD

**Issue by jskirzynski** [symfony/symfony-docs#6112]
Hello,
there is no configuration example in: http://symfony.com/doc/2.3/cookbook/doctrine/resolve_target_entity.html after text: *"Next, you need to configure the listener, which tells the DoctrineBundle about the replacement:"*. I have checked and there is the example only in source file (https://raw.githubusercontent.com/symfony/symfony-docs/2.3/cookbook/doctrine/resolve_target_entity.rst) but it is not shown on the website.

Thanks

**Comment by xabbuh** [comment]
Thanks for reporting this @jskirzynski. We have an issue with rendering configuration blocks on the website (see also #5918 and #6069).

@javiereguiluz Do you have an idea about this?

**Comment by javiereguiluz** [comment]
The error reported in this issue is fixed. We've probably fixed all the other related errors as well.
