### ISSUE TITLE
Missing php header in the first script src/AppBundle/Controller/LuckyController.php

### ISSUE THREAD

**Issue by olberger** [symfony/symfony-docs#6116]
It seems a pretty common FAQ that the Route isn't recognized if the LuckyController.php doesn't start with the PHP header '<?php', and unfortunately that's the first code that any beginner in Symfony will try to write (copy/paste).

I'd suggest to add that header to the code in https://github.com/symfony/symfony-docs/blob/3.0/book/page_creation.rst#creating-a-page-route-and-controller

Hope this helps.

**Comment by javiereguiluz** [comment]
@olberger thanks for bringing up this issue for discussion.

I know that doc managers are against these opening tags. But as you said, this is the first code listing for lots of Symfony developers. Would it hurt to add `<?php` just for the first code sample of this article?

**Comment by xabbuh** [comment]
Would that help so much? I mean someone who really doesn't have much experience with PHP would very likely stumble upon the second example then, wouldn't they?

**Comment by javiereguiluz** [comment]
@xabbuh yes I know. However, in theory only the first example would be copied+pasted entirely. The other code listings are modifications of the original one.

**Comment by WouterJ** [comment]
Closing this for the reasons mentioned in https://github.com/symfony/symfony-docs/pull/6389

If you don't agree, feel free to comment.

**Comment by olberger** [comment]
I beg to disagree that this must be obvious for PHP devs. If only the autoloader detected the file and reported a missing PHP header, that would be much better, but in the meantime, it is quite confusing to the newbee, and very much looks like symfony is broken at first impression.

But hey, this is your project, so I won't argue any more. Thanks for caring anyway.

**Comment by WouterJ** [comment]
> But hey, this is your project, so I won't argue any more. Thanks for caring anyway.

The documentation is written for those who read it. We appreciate your opinion very much and we're always looking into making things as clear as possible.

I've just submitted a pull request with my proposed fix: https://github.com/symfony/symfony/pull/18869 If this is merged, you would see a *The file "..." does not contain PHP code. Did you forgot to add the "<?php" start tag at the beginning of the file?* message. I hope this will make things clear for further beginners.

Thansk for the report!
