### ISSUE TITLE
Add doctrine listener example for simple registration form

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-docs#6117]
Encode the password (**you could also do this via Doctrine listener**)
Source: http://symfony.com/doc/current/cookbook/doctrine/registration_form.html#handling-the-form-submission

I think we should add an example to encode the password with a doctrine listener.

**Comment by javiereguiluz** [comment]
I'm closing this old issue because in #10799 we've decided to solve this differently using the MakerBundle. In any case, as we do with every proposal, we thank you for creating this issue because it helped us think about this. Thank you!
