### ISSUE TITLE
Update form "login" and "login_check" to use same URL?

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#6126]
When setting up a login form, we have the user create 2 routes (e.g. `/login` and `/login_check`). Someone at SymfonyCon asked me, wouldn't it be easier (to write and understand) if we just used the `/login` URL for both? `form_login` already *only* handles POST requests, so the GET would just render the login controller.

**Comment by felipsmartins** [comment]
That sounds like a great idea

**Comment by timglabisch** [comment]
simpler :+1:
