### ISSUE TITLE
[reference] [form] [options] error_mapping

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#6153]
in the given example :

```php
public function setDefaultOptions(OptionsResolverInterface $resolver)
{
    $resolver->setDefaults(array(
        'error_mapping' => array(
            'matchingCityAndZipCode' => 'city',
        ),
    ));
}
```
in this reference :
>The left side of the error mapping also accepts a dot ., which refers to the field itself. That means that any error added to the field is added to the given nested field instead;

"left side" is actually the wrong side, I mean the "right side"...

**Comment by WouterJ** [comment]
It's correct, as shown in [this blog post](http://symfony.com/blog/form-goodness-in-symfony-2-1#error-mapping-fu). As far as I understand it, a dot means every violation on any field of this form is mapped to the `city` field.

As it's a bit unclear (I don't 100% understand it and you were confused as well), I think we should at least add the code example in the blog posts to make things a bit more clear. Can you maybe add this?

**Comment by HeahDude** [comment]
@WouterJ I don't understand as this example it is set as default, so all errors for fields of this form are mapped to one field ?

**Comment by HeahDude** [comment]
Ok I confirm `'.'` mapped all unmapped validation rules.
Will do as you suggest

**Comment by HeahDude** [comment]
Hi @WouterJ, I've left a [comment](https://github.com/symfony/symfony-docs/pull/6156#discussion_r52102212) on the PR.

Once you reviewed it, I think we can close this issue.
