### ISSUE TITLE
Several components have missing mergers

### ISSUE THREAD

**Issue by bburnichon** [symfony/symfony-docs#6164]
For example, there are no mergers declared for the Asset component that appeared with Symfony 2.7 branch.

http://symfony.com/doc/current/contributing/code/core_team.html

Below is a list a component with missing mergers:
Asset
ClassLoader
CssSelector
ExpressionLanguage
Filesystem
Finder
Security
Templating

**Comment by WouterJ** [comment]
Unless I'm wrong, if a component has no merger, it's the project leader that's the only one that is allowed to merge. (/cc @fabpot please confirm here)

However, I think this page is a bit old now, as I see teammembers (even deciders) merging PRs as well (I also believe merging isn't the place which should be done by main maintainers of components, it's voting that should give mergers priority).

**Comment by fabpot** [comment]
@WouterJ is right.

The page is still relevant. I don't think any decider merges anything, do you have an example of that happening?

Voting is not enough. The maintainer of a component has the last word if he thinks that a change does not fit well with the philosophy of the component.
