### ISSUE TITLE
[Debugging] Class cache cannot be disabled anymore

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6169]
In http://symfony.com/doc/current/cookbook/debugging.html#disabling-the-bootstrap-file-and-class-caching say that you can disable the generation of the class cache by removing the call to the `loadClassCache()` method from the `Kernel` class. However, this is no longer true with the new `ClassCacheCacheWarmer` that was introduced in Symfony 2.8 and generates the class cache when the application cache is warmed up (see also symfony/symfony#17439).

**Comment by xabbuh** [comment]
see #6263

**Comment by weaverryan** [comment]
Thanks @xabbuh!
