### ISSUE TITLE
[Form] Time type doc on placeholders is outdated for 2.6+

### ISSUE THREAD

**Issue by kix** [symfony/symfony-docs#6178]
[As far as I can see in the Symfony source](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Form/Extension/Core/Type/TimeType.php#L66), the placeholder for `TimeType` needs to be an array with `hour`, `minute` and `second` keys, although the doc now simply includes a quite irrelevant description of `ChoiceType` placeholder usage from [`/reference/forms/types/options/placeholder.rst.inc`](https://github.com/symfony/symfony-docs/edit/2.8/reference/forms/types/options/placeholder.rst.inc)

**Comment by xabbuh** [comment]
Good catch @kix. Looks like something we need to fix.
