### ISSUE TITLE
Accessing the paylod in the Callback constraint

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6185]
Since Symfony 2.6 it is possible to pass custom payload data to the constraint validators. However, it was not possible to access this payload in the Callback constraint. With Symfony 3.1 this will now be possible as the payload is passed as an additional argument to the callback (see symfony/symfony#16909).

**Comment by WouterJ** [comment]
This new parameter to the callback should be documented in http://symfony.com/doc/current/reference/constraints/Callback.html (at least, all examples should be updated to have a `$payload` parameter as last parameter)

**Comment by jorgelbg** [comment]
The `payload` option is documented on http://symfony.com/doc/current/reference/constraints/Callback.html, but the examples indeed are not taking this parameter. If it's ok I'll try to update the examples.

**Comment by jorgelbg** [comment]
I think it would be a great addition at least one example that actually uses the `$payload` parameter. Any thoughts?

**Comment by WouterJ** [comment]
@jorgelbg hmm, I can't come up with a nice example as well... For now, I have merged https://github.com/symfony/symfony-docs/pull/6593 and you can create a new PR as soon as we find a nice example.
