### ISSUE TITLE
[FrameworkBundle] The Templating Configuration is Inaccurate for 3.0, Missing Asset Configuration Docs

### ISSUE THREAD

**Issue by chrisguitarguy** [symfony/symfony-docs#6195]
Version 3.0 dropped the various deprecated `assets_*` from `templating` in the framework bundle configuration and moved them into `assets`.

The [configuration reference still shows the 2.X stuff](https://github.com/symfony/symfony-docs/blob/3a7624ff1fd26750f3aff817715f80041207f8f0/reference/configuration/framework.rst) and needs to be brought up to date with 3.0

**Comment by snoek09** [comment]
There's a PR for this: https://github.com/symfony/symfony-docs/pull/6172

Please check and comment.

**Comment by chrisguitarguy** [comment]
Oops! Should have looked a bit closer. This is effectively a duplicate of #6146, so I'll close
