### ISSUE TITLE
TrustedHeaderNames documentation unclear

### ISSUE THREAD

**Issue by xDaizu** [symfony/symfony-docs#6198]
The [documentation](http://symfony.com/doc/2.7/components/http_foundation/trusting_proxies.html) is unclear about _where_ to use the method `Request::setTrustedHeaderName();`. 

I assume it must be in the front controller (`app.php`) but, in any case, I think it should be explicitly stated how to use it _properly_.

**Comment by xabbuh** [comment]
Well, the part of the documentation you link to is about using the component standalone. There, we cannot give any clear advice how do that properly as this basically depends on how you integrate the component in your application.
