### ISSUE TITLE
Ldap Components documentation missing?

### ISSUE THREAD

**Issue by Herod** [symfony/symfony-docs#6201]
Based on this link https://github.com/symfony/ldap the online documentation link seems to be broken.

The link:
https://symfony.com/doc/2.8/components/ldap.html

Is this related to the documentation itself or it's a mistake in the ldap readme.md?

**Comment by raulconti** [comment]
I think it's an error in the readme.md.

According to this page: http://symfony.com/components there is no documentation yet for this component.

Perhaps the readme should link to [blog](http://symfony.com/blog/new-in-symfony-2-8-ldap-component)

**Comment by xabbuh** [comment]
Yes, the docs are currently missing. But luckily we are aware of this and have #5756 to keep track of it. That's why I'm closing this as a duplicate. Thank you anyway for reporting it.
