### ISSUE TITLE
Search result showing raw RST source as content

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#6216]
![](http://i.imgur.com/TEad5xm.png)

**Comment by xabbuh** [comment]
@javiereguiluz Are you able to help here? Or should we ping someone else?

**Comment by javiereguiluz** [comment]
I'm working to improve this. Thanks for reporting it.

**Comment by javiereguiluz** [comment]
Update: the search engine on the website hasn't been updated yet, but we are working on this. Besides fixing this issue, we're working to improve the overall quality of the search results.

**Comment by javiereguiluz** [comment]
We can close this as "fixed" because the new version of the search engine has been deployed: http://symfony.com/search

This is still in "public beta" so please don't say anything about the search engine in public (we'll announce it soon, we'll publish a blog post explaining the internals, etc.)
