### ISSUE TITLE
[Form] [BestPractice] Forms as services section outdated

### ISSUE THREAD

**Issue by backbone87** [symfony/symfony-docs#6232]
https://symfony.com/doc/current/best_practices/forms.html#registering-forms-as-services

The reasoning given in this section is outdated.
Since the change to form type handling (since 2.8 iirc), i think the only reason left to register your form types as services is when you want to inject some dependencies into it.

**Comment by WouterJ** [comment]
I agree with your opinion and proposal. Can you maybe make a PR with this change by clicking on the "edit" button of that page?
