### ISSUE TITLE
Make IvoryCKEditorBundle the official WYSIWYG editor for Symfony

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6248]
From [this discussion](https://github.com/symfony/symfony/issues/15316) in the code repository, it seems a lot of people want some bundle to be named "the official WYSIWYG editor bundle for Symfony".

I propose [IvoryCKEditorBundle](https://github.com/egeloen/IvoryCKEditorBundle) to be that official bundle. If you have other proposals, please add a comment.

---

Once we make a decision, we'll do the following:

  * Contact the bundle's author to let him/her know about this.
  * Convince the author to let us transform the bundle's doc to RST format.
  * Integrate the bundle's doc in symfony.com
  * Add, where necessary, some help notes in the Symfony docs mentioning and recommending this bundle.

**Comment by WouterJ** [comment]
:+1:

**Comment by yceruto** [comment]
:+1:

**Comment by numerogeek** [comment]
:+1:

**Comment by javiereguiluz** [comment]
If anyone has a different opinion before we make the final decision, please add a comment as soon as possible. Thanks!

**Comment by xabbuh** [comment]
:+1:7

**Comment by javiereguiluz** [comment]
The opinions are unanimous, so let's make this happen. I've contacted the original creators of the bundle: https://github.com/egeloen/IvoryCKEditorBundle/issues/210

**Comment by egeloen** [comment]
I just merged the new doc format.

**Comment by javiereguiluz** [comment]
@egeloen thank you very much for transforming the documentation of your bundle to RST format. I've just made the pull request to add your bundle to symfony.com docs. We need to wait a bit until it's reviewed/merged/deployed, but in my local computer it works as expected:

![ivory_ckeditor_bundle_doc](https://cloud.githubusercontent.com/assets/73419/13288170/037176ba-db0b-11e5-9d4b-869e1cb22940.png)

**Comment by fabpot** [comment]
http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/index.html

**Comment by WouterJ** [comment]
Cool, thanks everyone for the work done to make this possible!
