### ISSUE TITLE
[Form] order of options in choice types references

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#6261]
It seems to be a convention to use an alphabetical order for options in field type references.

But things got a little messy in choice types as of 2.7.

Concerning `EntityType` I could fix that in #6260 or we should wait for it to be merged before applying a global fix for this issue.

@WouterJ @xabbuh WDTH ?

**Comment by xabbuh** [comment]
That's a good idea. We deliberately ordered the options alphabetically some time ago and I think we should maintain that.

**Comment by HeahDude** [comment]
Agreed. What about `EntityType` ? I guess it would avoid conflicts if changes are done in #6260, WDYT ?

**Comment by xabbuh** [comment]
@HeahDude The `entity` type otpions are already not sorted in the 2.3 docs. I would start reordering them there.
