### ISSUE TITLE
Reference cookbook in components documentation

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony-docs#6268]
As of now if you check the documentation for the [Form component](http://symfony.com/doc/current/components/form/index.html) we have a very... lacking documentation. It just mention the basic usage of the Form component and do not mention much about the internals, transformers and such. But if you check the [cookbook entry for the Form](http://symfony.com/doc/current/cookbook/form/index.html), it's a complete different story.

I'm not questioning the component/cookbook separation. However I do find not very user-friendly to have to check *both* the cookbook entry besides the doc. Something along the lines "See more advanced usage in the cookbook" could be added in the component entry. This way when a user wants to check the documentation for a component, he will be aware right away that there is more somewhere else, even if he's not familiar with the Symfony doc.

Note that I gave the example of the Form but it can be applied to other components as well.

**Comment by xabbuh** [comment]
I agree with you. This is also in a way related to the restructuring of the book chapter about forms which we discuss in #6093.

**Comment by theofidry** [comment]
Well I gave the use case of the form but it's far from being limited to it. And besides adding cookbook entries in the component doc, we should also add the book ones.

**Comment by javiereguiluz** [comment]
@theofidry yes, we agree with you. The Symfony Docs team met during the SymfonyCon Paris conference and discussed about this. It's my fault that the thing we agreed upon are not implemented yet. I'm sorry for being late with this.

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" after our recent [Symfony Docs reorganization](http://symfony.com/blog/introducing-the-new-symfony-documentation). Thanks!
