### ISSUE TITLE
[Form] Documentation on Model Transformers Is No Longer Valid for Symfony 3.0, Produce Deprecation Warnings in 2.8

### ISSUE THREAD

**Issue by chrisguitarguy** [symfony/symfony-docs#6276]
Symfony 2.8 [deprecated passing type objects to the form factory or builder](https://github.com/symfony/symfony/blob/d6418d4b367f9b3fd89387fdbd7c2ecc945c037b/src/Symfony/Component/Form/FormFactory.php#L104), but the [docs still use type objects in the data transformer cookbook example](https://github.com/symfony/symfony-docs/blob/1f4113fb1b3c85c8ca8660d1884e3055cebae7a6/cookbook/form/data_transformers.rst#using-the-transformer).

The example in the docs could probably be rewritten to use options rather than constructor arguments.

**Comment by ogizanagi** [comment]
Dependencies should not be passed as options using the OptionResolver component, but using the constructor and defining the form type as a service instead.

Maybe I've missed something, but [the doc you mentioned](http://symfony.com/doc/current//cookbook/form/data_transformers.html#using-the-transformer) already advises you to create a service for the form type :confused:

**Comment by chrisguitarguy** [comment]
Gotcha, I could have gotten an older version of the docs from a google search maybe or I didn't read it clearly. Either way, closing!
