### ISSUE TITLE
PR table header, usefull for the docs?

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#6287]
Seems like OSS world is now really exicted about the [latest feature of GitHub](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) to provide PR description templates.

We do have such a summary table for the docs, but we've always be very not-strict with it (most important thing is to have a very low blocker for people to fix things). Does it make sense to include this template for the docs?

/cc @javiereguiluz @xabbuh @weaverryan

**Comment by theofidry** [comment]
:+1: it would actually make things easier as would avoid to have people check on the website for the template to copy/paste it :)

And it's still only a template, it doesn't *force* you to comply to it.

**Comment by javiereguiluz** [comment]
We could show the template table, but prepeding it with a phrase like this: *If your changes are not trivial, please fill in this table. Otherwise, delete it.*

**Comment by weaverryan** [comment]
:+1: with friendly messaging of course so people know it's "ok" if they mess it up. I also copy and paste the table a lot.

**Comment by xabbuh** [comment]
I am not sure if we really need that table at all. Most PRs recently didn't include it and we didn't have any problems without it. What do you think about just removing it from the docs too instead of adding something new?

**Comment by WouterJ** [comment]
I think adding a message makes templates even less friendly: It's something that always has to be removed.

**Comment by javiereguiluz** [comment]
In #6367 I'm proposing a simplification of the contribution process which removes this PR table.

**Comment by weaverryan** [comment]
Closing this - now that the table is no longer included
