### ISSUE TITLE
Enlarge / get better the series for "Create your own Framework"

### ISSUE THREAD

**Issue by joserprieto** [symfony/symfony-docs#6301]
Dear friends:
Recently, I made an implementation of Sf components, for an application (propietary), to provide it a better architecture, extensibility, and scalability.
I implemented:
- Front controller pattern.
- Routing component.
- HTTP Foundation component.
- HTTP Kernel component.
- EventDispatcher component.
- ServiceContainer component.

And, plus of the original tutorial,
- Config component.
- YAML loader for routing and service container.
  Apart of the "framework", i made a console for a few of simple commands; this may be useful, to construct "modules" or "controllers" from skeletons, and so on.

What do you think about enlarge the series, and add some (or all) of this features / concepts?

Thanks in advance.

**Comment by javiereguiluz** [comment]
@joserprieto I'm really sorry but I must close this as "won't fix" because of the lack of response from the community. I'm sorry that this time your proposal didn't make it, but please keep making new proposals in the future. Thanks!
