### ISSUE TITLE
[RFC] Updating the design of the code listings

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6306]
I was trying, once again, to solve this issue https://github.com/symfony/symfony-docs/issues/5687 and I thought: maybe we can update the design of the code listings a bit and solve this issue too.

So, I'd like to propose these changes and I'd like to read your opinions before I submit the changes.

### Before

![before_code](https://cloud.githubusercontent.com/assets/73419/13317561/1375cb00-dbb6-11e5-875c-88e2c537f7f9.png)

### After

![after_code](https://cloud.githubusercontent.com/assets/73419/13317564/173a41e4-dbb6-11e5-9ff4-6f757d12194e.png)

### New tabs in action

![code_listing](https://cloud.githubusercontent.com/assets/73419/13317571/1e2fc9ba-dbb6-11e5-8603-96a84f6e748c.gif)

### New tabs for small code listings

![codelisting_two_tabs](https://cloud.githubusercontent.com/assets/73419/13317580/24c0a59c-dbb6-11e5-8d4c-caa8e4cd52bb.png)

### New tabs in Firefox

(it looks exactly the same as Chrome; all problems are fixed!)

![code_firefox](https://cloud.githubusercontent.com/assets/73419/13317586/2cb62fb0-dbb6-11e5-968d-52b67513cb0e.png)

**Comment by stof** [comment]
:+1: from me

**Comment by xabbuh** [comment]
:+1: I like it too.

**Comment by WouterJ** [comment]
:+1: Looks great!

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because you all agreed with this and the new design is already merged on symfony.com code. We'll start to see it online after the next deploy.
