### ISSUE TITLE
Add docs for TargetPathTrait

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#6335]
See symfony/symfony#17714

**Comment by javiereguiluz** [comment]
In which book section or cookbook article should we document this? It's really a tiny (but nice) feature.

**Comment by javiereguiluz** [comment]
Where do you think we should document this?

* security/target_path.rst
* security/custom_authentication.rst
* ...?

**Comment by javiereguiluz** [comment]
Fixed by #9112.
