### ISSUE TITLE
$csrfProvider definition is missed

### ISSUE THREAD

**Issue by sensorario** [symfony/symfony-docs#6338]
In this file, $csrfProvider definition is missed: https://github.com/symfony/symfony-docs/blob/master/components/form/introduction.rst

**Comment by WouterJ** [comment]
Thanks for reporting this!

This should be replaced with `$csrfManager` from the previous section. This was changed in the 2.7 version of the documentation.

**Comment by snoek09** [comment]
I'm fixing this.
