### ISSUE TITLE
Consider improving the documentation of access decision strategies

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6339]
As @fabpot said in https://github.com/symfony/symfony/issues/15130#issuecomment-116621951 we probably need to consider improving the documentation around this feature.

**Comment by WouterJ** [comment]
I don't really get what has to be improved. Can you please make this issue more explicit, @javiereguiluz ?

**Comment by javiereguiluz** [comment]
After reading Wouter's comment I'm closing this as "won't fix". The strategies are perfectly explained in the cookbook about voters: http://symfony.com/doc/current/cookbook/security/voters.html#changing-the-access-decision-strategy
