### ISSUE TITLE
Guidelines for using GitHub reactions

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6346]
As you know, GitHub as added [reactions to issues, comments and pull requests](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments). Do you think we should decide some basic guidelines to use them?

If you agree, this would be my proposal:

  * Use only `:+1:` or `:-1:` to vote for things.
  * Use reactions only for Issues and PRs, not comments.
  * Stop using :+1: and :-1: in comments as a voting mechanism.

Thoughts? Thanks!

**Comment by xabbuh** [comment]
I'd say let's wait some time to see how people actually use reactions. I would rather not put something more in the contribution guidelines that is not really necessary and focus on important stuff instead.

**Comment by javiereguiluz** [comment]
I wouldn't put this information in the contribution guide. And besides, few people read it :disappointed: The question was more about how we should use them. For example, in this PR (https://github.com/symfony/symfony-docs/pull/6345) you voted in an empty comment and I used a reaction icon.

**Comment by xabbuh** [comment]
At least for our internal voting mechanism we would have to stick to comments until `gh` is able to determine core team votes from reactions.

**Comment by xabbuh** [comment]
But I agree that it would now better if people generally used reactions to support a thread instead of pushing notifications to everyone by commenting with +1.

**Comment by javiereguiluz** [comment]
That's a good point! I've added an issue in the `gh` tool to see what do they decide.

**Comment by javiereguiluz** [comment]
I'm closing it because at `symfony-docs` we don't have a problem with this at all. Few people vote on issues/PRs, so let's do nothing about this for now. Thanks!
