### ISSUE TITLE
Update the PR table in the contributing guide

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6357]
As pointed by @vladapopster, the contributing guide (http://symfony.com/doc/current/contributing/code/patches.html#make-a-pull-request) contains a PR table which is not updated to the latest one used in the Symfony repository (it lacks the `Branch` row for example).

**Comment by WouterJ** [comment]
Now we have PR templates on github, do we actually need to duplicate the template in the contributing docs? It seems like it can only get outdated and doesn't add anything more than saying "Fill in the table in the PR template."

**Comment by xabbuh** [comment]
I agree with Wouter. Let's just remove the table from the docs.

**Comment by javiereguiluz** [comment]
This can be closed as "fixed" because #6365 was merged. Thanks!

**Comment by mvar** [comment]
Are there any notes why Issue and Pull Request templates were removed? @wouterj wrote that "Now we have PR templates on github" but I can't see any. Same for the main Symfony repository.

**Comment by xabbuh** [comment]
@mvar At some point we decided that most of the time having to fill out a table is too cumbersome for simple documentation contributions and we wanted to further lower the burden to contribute to the docs.
