### ISSUE TITLE
[Form] Add form chaining example to cookbook

### ISSUE THREAD

**Issue by hackzilla** [symfony/symfony-docs#6407]
I've struggled with making complex Symfony forms for a while now.

My biggest issue is trying to build a chained select (e.g. country, region, city).
The solution I usually go with is load all the options in symfony, and deal with it in javascript.

However this has validation implications that I haven't addressed.

What I'd like to see is a cookbook example showing how chained selects work in a pure Symfony environment, with resubmitting to the server with the data coming from an API or a Database.

**Comment by xabbuh** [comment]
@hackzilla Isn't this basically what we currently describe at http://symfony.com/doc/current/cookbook/form/dynamic_form_modification.html#cookbook-form-events-submitted-data?

**Comment by hackzilla** [comment]
It sort of is, but I was thinking a more explicit example.

Since I posted this I managed to get a working solution that could be the basis for my requested example.

**Comment by xabbuh** [comment]
Having a more concrete example might help to understand the concept. So if you would to open a pull request, we will be happy to review it.

**Comment by hackzilla** [comment]
I'll create a fork of symfony-demo to make sure how I've coded it is acceptable.

**Comment by hackzilla** [comment]
I have created a basic changed select that I believe works in Symfony 2.8 and 3.0.

https://github.com/hackzilla/symfony-chain-select-demo/commit/ddaee3d8d2fb009e81234319771ce4711a997407

http://127.0.0.1:8080/app_dev.php/en/admin/post/new

Would this be the best way to base the documentation?

An addition I could add would be using javascript to submit the form on change for Level1-3.

**Comment by hackzilla** [comment]
sorry I forgot to tag you in the above comment @xabbuh

**Comment by javiereguiluz** [comment]
I think I'm going to close this issue because the current form docs contain exactly the chained form example mentioned in the first comment of this issue: https://symfony.com/doc/current/form/dynamic_form_modification.html#form-events-submitted-data

The current doc is already very complex and hard to maintain, so we prefer to not add more complex examples or additional examples which are very similar to existing ones. Thanks for understanding.
