### ISSUE TITLE
[Autowiring] Document how to autowire a third-party class

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#6408]
See https://github.com/symfony/symfony/pull/18040#issuecomment-199573489

Probably near the end of this document: http://symfony.com/doc/current/components/dependency_injection/autowiring.html - after we explain how to use `autowiring_types` for services that _we_ control.

**Comment by javiereguiluz** [comment]
Is this 1-year old issue something that we still want to document given the huge changes introduced in autowiring recently?

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because autowiring changed a lot since this issue was created and the new articles about it already explain everything:

* https://symfony.com/doc/current/service_container/autowiring.html
* https://symfony.com/doc/current/service_container/3.3-di-changes.html
