### ISSUE TITLE
[Form] Add examples for submitting PATCH requests without handleRequest()

### ISSUE THREAD

**Issue by Nomad145** [symfony/symfony-docs#6415]
Greetings,

I ran into a specific use case where a single page application was submitting a form to a REST API without a submit button via an HTTP PATCH method.  I had read somewhere (probably StackOverflow) that `handleRequest()` handles partial updates since Symfony 2.x, but since there wasn't a submit button, `handleRequest()` wouldn't submit the form.

Long story short, I wasn't able to find documentation regarding a solution until I saw the API for the `submit()` function with the optional `$clearMissing` parameter.  I'm willing to submit a PR with this use case highlighting the ability to do partial updates via the `submit()` function if it sounds useful to anyone else.

**Comment by HeahDude** [comment]
Good idea! :+1:

**Comment by xabbuh** [comment]
Sounds like a good idea to me.

@Nomad145 We welcome every pull request that tries to improve the documentation. :)

**Comment by Nomad145** [comment]
Sweet!  I'll see what I can do!
