### ISSUE TITLE
Add documentation for the new Inflector component

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6417]
Inflector is a new component added to Symfony: https://github.com/symfony/symfony/commit/facb21eed9cb4bc3d98522c8c55a03b59defa024  Sadly we don't have any documentation for it.

I can write the docs, but I'd like to ask for help to @teohhanhui, the author of the component. Could you please mention the main features of the component and its limitations/problems/when not to use it? 2 or 3 short phrases will be enough for us. And if you have some cool code examples, please share them too. Thanks!

**Comment by teohhanhui** [comment]
The component was merely extracted from PropertyAccess. I did not write it.

@webmozart is the original author.

**Comment by javiereguiluz** [comment]
@teohhanhui OK, sorry!

**Comment by javiereguiluz** [comment]
I'm closing this because the Inflector "component" si something internal and not a real component.
