### ISSUE TITLE
The contributing documentation has a weird navigation on the website

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#6442]
The contributing documentation (http://symfony.com/doc/current/contributing/index.html) is accessible through the `Community` tab of the website through the `How to be involved` menu entry. But then, these pages have the documentation navigation on the left, which does not include any link to the contributing section.

I think it would make sense to include the contributing section in the menu. What do you think @javiereguiluz ?

**Comment by WouterJ** [comment]
I agree with you, @stof. Before the redesign of the sidebar, there always was such a link in the sidebar. I think it has to be reintroduced (together with a link to the CMF docs).

**Comment by xabbuh** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Maybe we could solve this problem adding a new "Contributing" entry to the "Guides" menu?

**Comment by stof** [comment]
@javiereguiluz this would be fine with me

**Comment by javiereguiluz** [comment]
A quick update: "Contributing" has been added to the "Guides" menu of the doc section ("Workflow" has been added too). It hasn't been deployed yet, but it will "soon".

**Comment by javiereguiluz** [comment]
This has been finally deployed. Closing it as fixed.
