### ISSUE TITLE
[Form] Incorrect description for choice_attr option of ChoiceType field

### ISSUE THREAD

**Issue by mvar** [symfony/symfony-docs#6443]
Current [choice_attr](http://symfony.com/doc/current/reference/forms/types/choice.html#choice-attr) description:

> Use this to add additional HTML attributes to each choice. **This can be an array of attributes (if they are the same for each choice)**, a callable or a property path (just like choice_label).

Actually it's not possible to set attributes for all choices at once. You need to redefine attributes for each choice separately:

```php
'choice_attr' => [
    'Choice A' => ['class' => 'foo'],
    'Choice B' => ['class' => 'foo'],
    ...
    'Choice Z' => ['class' => 'foo'],
],
```

Please correct me if I'm wrong.

**Comment by HeahDude** [comment]
Hi @mvar, actually you're right about that. But you can do:
```php
'choice_attr' => function () { return array('class' => 'foo'),
```
I've already open an issue https://github.com/symfony/symfony/issues/18318 and a PR to change that.

See also https://github.com/symfony/symfony-docs/pull/6393.

I think we can close here. Thank you.

**Comment by mvar** [comment]
@HeahDude thanks for comment. I'm closing this issue as the problem is known :)
