### ISSUE TITLE
Consider improving the templating chapter

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6468]
Symfony 3.0.4 introduced a BC-break ... which actually fixed a long-standing bug.

Apparently, wrong template paths like this one worked before 3.0.4: `WidgetsCoreBundle:weather/five_days.html.twig`

The right path would be `WidgetsCoreBundle::weather/five_days.html.twig` or `WidgetsCoreBundle:weather:five_days.html.twig`.

A lot of people seem to be using wrong template paths unawarely, because we've received lots of issue reports: https://github.com/symfony/symfony/issues/18522, https://github.com/symfony/symfony/issues/18364, https://github.com/symfony/symfony/issues/18497 and https://github.com/symfony/symfony/issues/18653.

One of the issue reporters said: _"it's not that clear in the doc: http://symfony.com/doc/current/book/templating.html"_ and _" it's not really clear for this point in the docs"_.

---

Posible solutions:
- Reword part of that chapter to explain things better.
- Switch to the cool and modern and amazing namespaced templating notation: `@WidgetsCore/weather/five_days.html.twig`

**Comment by ogizanagi** [comment]
@javiereguiluz : I think the `2.8.4` version is also affected.

**Comment by xabbuh** [comment]
As a reference: Switching to the namespaced syntax also was discussed in the past in #3849.

**Comment by peshi** [comment]
I use the @Template annotation and I receive.
```
Unable to find template "AppBundle:Default:index..twig" (looked into: ....
```

**Comment by javiereguiluz** [comment]
@peshi it seems that the `@Template` annotation in your case can't detect the format of the request. That's why the guessed template is `AppBundle:Default:index..twig` instead of for example `AppBundle:Default:index.html.twig`.

This "automagical" guessing mechanism is one of the things some Symfony developers don't like about `@Template` ... and that's why it's one of the few annotations we don't officially recommend to use.

**Comment by peshi** [comment]
@javiereguiluz Thanks for the tip, I found why it suddenly stopped working. It seems there's a problem with FOSRestBundle's view_response_listener. Disabled that and it's working again.

**Comment by javiereguiluz** [comment]
Closing it as fixed because we no longer use this template syntax anywhere (see #8120).
