### ISSUE TITLE
[Service container] Improve documentation

### ISSUE THREAD

**Issue by gerryvdm** [symfony/symfony-docs#6476]
I found the documentation for importing services through container extensions very confusing.

http://symfony.com/doc/current/book/service_container.html#importing-configuration-via-container-extensions

> When the configuration is parsed, the container looks for an extension that can handle the framework configuration directive. The extension in question, which lives in the FrameworkBundle, is invoked and the service configuration for the FrameworkBundle is loaded. If you remove the framework key from your application configuration file entirely, the core Symfony services won't be loaded. The point is that you're in control: the Symfony Framework doesn't contain any magic or perform any actions that you don't have control over.
> 
> Of course you can do much more than simply "activate" the service container extension of the FrameworkBundle. Each extension allows you to easily customize the bundle, without worrying about how the internal services are defined.

In the documentation, it is implied that not having an extension key in the loaded configuration file does not load any services for that extension. While that might be the case for some extensions, typically not having an extension's key will still load several if not all service definitions.

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" because this article was completely rewritten and the mentioned contents no longer exist. I'm sorry!
