### ISSUE TITLE
`--verbose` does not allow values

### ISSUE THREAD

**Issue by TobiasXy** [symfony/symfony-docs#6477]
It is not possible to use the `--verbose` option with a value as it is described here:

https://symfony.com/doc/current/components/console/usage.html#global-options

A command like this will fail:
`php bin/console router:match / --verbose=2`

See this bug report in the symfony/symfony repository: https://github.com/symfony/symfony/issues/18546

**Comment by xabbuh** [comment]
Thanks for spotting and reporting this @TobiasXy. It should be easy to fix.

**Comment by xabbuh** [comment]
So what I meant is we would warmly welcome if you would like to create a pull request for this. :)
