### ISSUE TITLE
"images/request-flow.png" references Symfony2

### ISSUE THREAD

**Issue by danielcotton** [symfony/symfony-docs#6480]
`images/request-flow.png` has "Symfony2 Kernel" instead of "Symfony3 Kernel".

I'd submit a PR, but I'm not sure how the graphic is generated.

**Comment by javiereguiluz** [comment]
Updating these images is very time-consuming ... so we usually don't do it 😢   However, if we update this, we should replace `Symfony2` by `Symfony` to make it future-proof. Thanks!

**Comment by danielcotton** [comment]
If that's the case, I'm happy to fill in the "2" with the background color and submit a PR.

Is that okay with you?

**Comment by javiereguiluz** [comment]
@danielcotton that would be a dirty hack ... so I love it 😁
