### ISSUE TITLE
[RFC] [Proposal] Code snippet convention

### ISSUE THREAD

**Issue by phansys** [symfony/symfony-docs#6484]
Use backticks when referencing functions, classes, variables, etc. This should be the same for error and exception messages, docblock descriptions, comments or wherever any of these elements are pointed. 

By instance:
```php
/**
 * @return string
 *
 * @deprecated Since version 2.8 and will be removed in 3.0. Use `Acme\Baz::someMethod()` instead. 
 */
public function someDeprecatedMethod()
{
    @trigger_error(sprintf('The `%s()` method is deprecated since version 2.8 and will be removed in 3.0. Use `Acme\Baz::someMethod()` instead.', __METHOD__), E_USER_DEPRECATED);

    return Baz::someMethod();
}
```

**Comment by WouterJ** [comment]
Ping @symfony/deciders please share your opinion about this (you're spending more time on the code than me).

Personally, I'm -0.5 on this. I don't think it matter much. Changing everything would probably take quite some time (which could have been spent on reducing open issues as well for instance).

**Comment by phansys** [comment]
I understand your point @WouterJ. I could take this more as an encourage than a rule, in order to allow the move in an easier way. Thank you for your feedback.

**Comment by phansys** [comment]
I forgot to mention that parameters and service names should be also considered in this RFC. Although they are simple strings, they have some kind of extra relevance since they are representing something else.
By instance: ```Please use the `templating` service```

**Comment by javiereguiluz** [comment]
I agree with wrapping some words inside sentences to make them more legible (e.g. `Please use the "templating" service` instead of `Please use the templating service`). However, I don't like the backtick convention. If I'm right, in Symfony we are already doing this for some errors but using double quotes instead of backticks.

**Comment by phansys** [comment]
I think you're right about the current usage @javiereguiluz. I'm proposing the backticks because IMHO it's already a convention for code snippets, while the single/double quotes are intended for strings.

**Comment by javiereguiluz** [comment]
@phansys beware that backticks are a bit misleading. It's true that we add them in the doc sources ... but they never appear in the actual doc. They are just a trick to display `<code> ... </code>`

**Comment by WouterJ** [comment]
> It's true that we add them in the doc sources ... but they never appear in the actual doc.

Markdown is very popular among developers (and well-known because of it's use on GitHub and StackOverflow and such). This backtick has become a very common way of referencing inline code in plain text.

**Comment by javiereguiluz** [comment]
@WouterJ yes, but readers never ever see a backtick in the actual docs.

**Comment by phansys** [comment]
@javiereguiluz, sure. Given you dislike the backtick notation, it would be nice if you could suggest some other delimiter for code snippets in order to distinguish them from common strings.

**Comment by javiereguiluz** [comment]
The double quote, which is what Symfony is already using. Quick examples from PRs which were updated in the last minutes: https://github.com/symfony/symfony/pull/18533/files#diff-cbf4adbe966f30abf1ece8cabbbf6e06R131 and https://github.com/symfony/symfony/pull/17660/files/8924b23c6a9832b54eddb75ac22134798b648683#diff-cd90b97b50abf20fa94468689e7486afR90

**Comment by javiereguiluz** [comment]
@phansys in any case, in the example you used at the beginning of this PR, I'd do the following:

```php
/**
 * @return string
 *
 * @deprecated Since version 2.8 and will be removed in 3.0. Use Acme\Baz::someMethod() instead. 
 */
public function someDeprecatedMethod()
{
    @trigger_error(sprintf('The %s() method is deprecated since version 2.8 and will be removed in 3.0. Use Acme\Baz::someMethod() instead.', __METHOD__), E_USER_DEPRECATED);

    return Baz::someMethod();
}
```

Backticks or any other delimiter is not needed (in my opinion) because nothing can be misunderstood when we remove them.

**Comment by phansys** [comment]
Maybe my example isn't the better use case for the situation where I think this RFC can be more useful @javiereguiluz. Think the situation where you have an entity called by instance User and you need to make a distinction in the same sentence when you're talking about the conceptual User and the entity called `User`.

**Comment by javiereguiluz** [comment]
@phansys yes. In those cases I propose to use `"` as Symfony does on its code.

**Comment by phansys** [comment]
What happen then when you need to mix literal strings with snippets? You end using the same "notation" for both cases, which doesn't seem very semantic or helpful to me.

**Comment by iltar** [comment]
One advantage might be that by notating the deprecations/exception references with backticks, the toolbar could automatically create links to relevant documentation. Besides of that, using simply " would be good enough for me

**Comment by fabpot** [comment]
I'm also -0.5 on this one. I don't see a huge benefit but I can see a huge amount of work. Not worth it if you ask me.

**Comment by Tobion** [comment]
I agree that special values should be enclosed in quotes or backticks. But which one does not really matter to me. I'd go with what we used so far.

**Comment by phansys** [comment]
What about cases like this:
```
Please pass "someStringArg" as first argument: `SomeClass::someMethod('someStringArg')`
```
Using double quotes, it should be:
```
Please pass "someStringArg" as first argument: "SomeClass::someMethod('someStringArg')"
```
If you feel comfortable with the double quotes notation, I haven't any other objection. But note that this should be used escaping the single quotes when used as a error/exception message:
```php
trigger_error('Please pass "someStringArg" as first argument: "SomeClass::someMethod(\'someStringArg\')"', E_USER_DEPRECATED);
```

**Comment by nicolas-grekas** [comment]
Same POV as Fabpot for me: this is going to be a big burden for a low practical added value. We use double quotes today, mostly, let's document what we already do. But changing the existing messages in batch looks like a terrible idea to me: lots of work and time spent *not* on fixing bugs or implementing features. And I know *I'm* going to do it when merging branches (with other mergers) :-)

**Comment by xabbuh** [comment]
@phansys Imo your example would rather be worded `Pass "someStringArg" as the first argument to "SomeClass::someMethod()`.

Besides that I agree with @fabpot and @nicolas-grekas.

**Comment by phansys** [comment]
If the major votes are for double quotes, I'm fine with that @xabbuh, I agree with your rewording. Although there are many places to do that change anyway. That is why I propose to make this change in a progressive way instead a immediate whole replace. Take into account that there are many other rules that aren't strictly respected in the code base.

**Comment by fabpot** [comment]
I'm closing this one now as nobody in the core feels the urge to change anything.

**Comment by phansys** [comment]
Thank you for your thoughts guys. I'll try to open a PR with the double quotes notation when I find some time.

**Comment by javiereguiluz** [comment]
@phansys thanks but if I understood the above comments right ... we are not planning to change the current messages to add quotes. We'll do that for the new messages introduced in the future.

**Comment by phansys** [comment]
@javiereguiluz, if we'll do that for the new messages introduced in the future, don't we need to document it? Personally, I don't like to see the same structures written in different forms depending on who, when or where; which finally leads to unpredictable code.
