### ISSUE TITLE
v2.7 Voter is using v3.0 directions

### ISSUE THREAD

**Issue by totaltrash** [symfony/symfony-docs#6486]
There were a lot of changes to the voter between 2.7 and 3.0, and i think the 3.0 directions have leaked into the 2.7 branch documentation.

For example, the Voter interface changed, there is no Voter abstract class in 2.7 (https://github.com/symfony/symfony-docs/blob/2.7/cookbook/security/voters.rst#the-voter-interface), AbstractVoter should be used as per 2.6 (https://github.com/symfony/symfony-docs/blob/2.6/cookbook/security/voters.rst#the-voter-interface).

I think the 2.7 voter documentation needs to be replaced with the 2.6 doc?

**Comment by WouterJ** [comment]
Thanks for the bug report @totaltrash! I did something wrong yesterday while merging PRs (resulting in having the 3.0 docs available under the 2.7 docs). I've now fixed this with https://github.com/symfony/symfony-docs/pull/6490
