### ISSUE TITLE
[Form] CollectionType entry_type option

### ISSUE THREAD

**Issue by mpaquet** [symfony/symfony-docs#6487]
I think the [2.3+](http://symfony.com/doc/2.3/reference/forms/types/collection.html) doc is wrong about the **entry_type** option : the correct option is **type** from 2.3 to 2.7 included.
Probably a merge issue :)

**Comment by HeahDude** [comment]
Right, actually the same goes for `entry_options` and its example of `ChoiceType` usage...

**Comment by HeahDude** [comment]
Thanks @mpaquet for reporting this. I've opened #6488.

**Comment by mpaquet** [comment]
In fact that is not the only issue with this doc page, like FQN which should not be mentioned before 2.8 as an example.

**Comment by mpaquet** [comment]
I close this since the issue is already reported and treated.

**Comment by mpaquet** [comment]
This is now fixed for 2.3 but not for 2.7.

**Comment by WouterJ** [comment]
It's now fixed everywhere (refs https://github.com/symfony/symfony-docs/issues/6501 )
