### ISSUE TITLE
[Question] [CS] Effort / gain vs respecting CS

### ISSUE THREAD

**Issue by phansys** [symfony/symfony-docs#6512]
I'm opening this ticket because I think we need a clearer definition of what coding standards means for Symfony or which is the weight of each rule defined at [Structure](https://github.com/symfony/symfony-docs/blob/master/contributing/code/standards.rst#structure) section. If they have different levels of importance or respectability, I propose to restructure that chapter in order to use the keywords defined at [RFC 2119](http://www.ietf.org/rfc/rfc2119.txt) ("MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL") as done in [PSR-2](http://www.php-fig.org/psr/psr-2/).

Lately I'm noticing that there are some changes that aren't taken into account because the effort which they can demand or the gain that they can offer. In some cases they are [proposals for new standards](https://github.com/symfony/symfony-docs/issues/6484), but in others they indeed are [fixes for structures that don't respect our established set of rules](https://github.com/symfony/symfony/pull/18624).

BTW, I only have acknowledgement of both of these examples because I was who proposed them, but I'm suspecting that there could be some other similar cases.

**Comment by xabbuh** [comment]
Well, I think this is more about talking about code that already exist and is sitting there for quite some time. The problem simply is that, making huge changes in older branches "just" to comply with our CS, merging branches up  to `master` (which soon can include **six** branches) becomes a complete nightmare and raises the risk for making a mistake without giving as that much gain. The moment where we need to focus on having code being consistent with our rules is when a PR is created that adds these new lines of code on top of the existing code base.

**Comment by phansys** [comment]
Your concern is totally understandable @xabbuh. What do yo think about my [proposal](https://github.com/symfony/symfony/pull/18624#issuecomment-213951379) to make this decision explicit?

**Comment by javiereguiluz** [comment]
@phansys even if you are right, I'm afraid that we won't make any changes to the existing code because of the mentioned problems. I'm sorry but this is something we'll need to live with at least for some years.

**Comment by phansys** [comment]
Sure @javiereguiluz, thank you. My proposal is to make it explicit at CS docs, telling  which of our rules **MUST** be considered in a strict way and which of them **SHOULD** be taken as suggestions.
Given that distinction, I think the decision of which of these rules may be considered offended by some piece of code would be much easier.
In other words, code offending **SHOULD**-rules can be handled with this proposed appendix, which obviously can be tied to any number of rules:
>Please note some early Symfony versions do not follow this convention and have not been updated for mergeability reasons.

**Comment by WouterJ** [comment]
Every rule applies to the new code, not existing.

**Comment by phansys** [comment]
Thanks for your response @WouterJ.
Can you please tell me how to read the comments of #6484? I think there was some positive votes for documenting a new rule, but the ticket was closed because it can lead "a huge amount of work". If your statement is right, I don't know how a new rule can affect existing code.

**Comment by WouterJ** [comment]
@phansys in this case, changing all exception messages to use backticks instead of quotes means a ton of changes in the current code (= affecting existing code). This has to be done in 2.3, which will lead to merge conflicts in 2.7. In 2.7, this has to be done again for new messages in 2.7, which lead to merge conflicts in 2.8. And this goes on and on for 2.8, 3.0, 3.1 and master.

So using backticks is not worth it, especially as the code already uses double quotes for this.

I don't think we have to make this more explicit in the coding standard document. It is documenting the standard, not the implementation of the standard anyway. For this reason, I'm going to close this issue. Of course, if you don't agree with this decision, feel free to comment.
