### ISSUE TITLE
Documentation version switch for bundles

### ISSUE THREAD

**Issue by malarzm** [symfony/symfony-docs#6516]
I tried emailing @javiereguiluz some time ago but since I haven't heard back yet I thought I'll try to ask here too:

I'm looking for a way to change docs version dropdown for [DoctrineMongoDBBundle](http://symfony.com/doc/master/bundles/DoctrineMongoDBBundle/index.html), specifically I'm thinking about switching bundle versions to Symfony 2.x and Symfony 3.x - how can one achieve this? I tried to look for some configuration for 3rd party bundles but I couldn't find it anywhere.

**Comment by WouterJ** [comment]
These checkers are configured in a private repository for symfony.com Only some people can access it ( @javiereguiluz and @fabpot are the ones I know).

**Comment by javiereguiluz** [comment]
@malarzm I received your email but I couldn't reply it yet. I'm sorry. I have too many pending things at the moment. I'll come back when I can work on this. Thanks!

**Comment by malarzm** [comment]
Thanks guys for quick answer! :) Closing issue then, will wait for @javiereguiluz unless there's somebody else who could pick this up?
