### ISSUE TITLE
Update DomCrawler example

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6519]
According to https://github.com/symfony/symfony/issues/18660#issuecomment-215428953 some example of the DomCrawler docs is wrong.

> This example is no longer valid ;)
>
> use Symfony\Component\CssSelector\CssSelector;
>
> CssSelector::disableHtmlExtension();
> $crawler = $crawler->filter('default|entry media|group yt|aspectRatio');

**Comment by xabbuh** [comment]
This should be done for the `2.8` branch as this is the version where the new CssSelector API was introduced.

**Comment by WouterJ** [comment]
This is fixed by https://github.com/symfony/symfony-docs/pull/6536
