### ISSUE TITLE
Should kernel.terminate be non-blocking with Apache / mod_php?

### ISSUE THREAD

**Issue by deviantintegral** [symfony/symfony-docs#6520]
I have some code that registers a terminate event to upload an image to S3 after sending it to the client. According to the [docs on the terminate event](http://symfony.com/doc/3.0/components/http_kernel/introduction.html#the-kernel-terminate-event) this should only be non-blocking on fastcgi implementations, but for me it's also non-blocking with a standard mod_php setup under Ubuntu 14.04.

As soon as [\Symfony\Component\HttpFoundation\Response::closeOutputBuffers](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L381) executes the image is flushed to the client. I tested both with output_buffering at the default 4K and at a way-too-large 10M. Is there some other PHP setting I've missed that could let flushing work? Or should the docs be updated to indicate that mod_php is fine for a non-blocking terminate event?

**Comment by xabbuh** [comment]
Can someone else confirm this?

**Comment by javiereguiluz** [comment]
If you look at the `send()` code in Response.php class:

```php
public function send()
{
    $this->sendHeaders();
    $this->sendContent();

    if (function_exists('fastcgi_finish_request')) {
        fastcgi_finish_request();
    } elseif ('cli' !== PHP_SAPI) {
        static::closeOutputBuffers(0, true);
    }

    return $this;
}
```

So it's clear that it needs `fastcgi_finish_request()`. I'm not an expert on this ... but Apache seem to have some support for FastCGI protocol through mod_proxy and mod_proxy_fcbi (see https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html)  Maybe that's what's happening in your case?

**Comment by deviantintegral** [comment]
Good thought! I'm only using mod_php on my local, and neither of the proxy modules are enabled in apache.

**Comment by javiereguiluz** [comment]
Let's close this for now because we're trying to improve this ... and we may start recommending to solve this differently (see #9806) like using queues, now that they are native starting from Symfony 4.1. Thanks!
