### ISSUE TITLE
[Yaml] Document the deprecated arguments of parser and dumper?

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#6524]
Trying to start working on #6226 to document the new YAML flags, I'm thinking that maybe we should add a third section to the YAML component doc, something like:

YAML component:
 - Introduction
 - Format
 - Advanced Format Using Flags
    - Parser
    - Dumper

Of courses, I could have post it in the corresponding issue but I noticed that actually this doc is missing in previous version (2.7?), since we can already use some (now deprecated) extra parameters in `parse()` and `dump()`.

Shouldn't we start by documenting these parameters, then fix #6226 by adding depreciations notices?

Thanks.

EDIT
-------

- [X] Detail arguments and object parsing,

- [x] Document `objectForMap`

**Comment by xabbuh** [comment]
Yes, I think it makes sense to document features that were available before with the old way to achieve this first.

**Comment by HeahDude** [comment]
Still needs a PR in 2.7 for object maps before we can close, I added checkboxes to the description, first checked by #6582.

**Comment by xabbuh** [comment]
The second task will be accomplished by #6590.
