### ISSUE TITLE
Proposed changes for code listings on symfony.com

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6531]
This is a *"For Your Information"* issue explaining some changes that will be introduced in the coming days for symfony.com doc.

---

### Code lines are no longer wrapped

In the past, we wrapped long code lines. This is great if your line numbers respect the wrapping, but ours don't. The reason is that Sphinx uses different `<table>` elements for the line numbers and for the code, so it's impossible to keep them in sync. In this example the line number 6 wraps and makes the number 7 to be wrongly assigned:

![before-wrap-lines](https://cloud.githubusercontent.com/assets/73419/15010609/44e53b68-11ed-11e6-8a7a-09f10ba3fd1b.png)

The only viable solution is to prevent line wrapping, so long lines will now produce an overflow:

![after-wrap-lines](https://cloud.githubusercontent.com/assets/73419/15010624/59361f4c-11ed-11e6-91d7-d9c9e8f36c57.gif)

This won't be a big problem because doc maintainers are very strict with long lines and we don't have many code samples that suffer this problem.

### Line numbers won't be displayed for short code listings

Currently we add line numbers even for code listings which contain 1 line, for example console commands:

![before_linenos](https://cloud.githubusercontent.com/assets/73419/15010652/83c7acc6-11ed-11e6-8d74-814d8e2e4f50.png)

Soon we'll only display line numbers if the code listing has 5 or more lines:

![after_linenos](https://cloud.githubusercontent.com/assets/73419/15010667/8faab6c8-11ed-11e6-85e5-79d25aa29da5.png)

**Comment by WouterJ** [comment]
Thanks for the info! I never knew we wrapped long lines in the code blocks.

**Comment by xabbuh** [comment]
I didn't know that too. But the changes perfectly make sense to me. 👍

**Comment by javiereguiluz** [comment]
Closing this issue because there was enough time to read the announcement. Thanks!
