### ISSUE TITLE
How to add documentation for inherited methods?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#6534]
I wanted to add a description for [this method](http://api.symfony.com/3.0/Symfony/Component/DomCrawler/Crawler.html#method_count) but i didn't know how.

**Comment by xabbuh** [comment]
I am not sure if we really should document this method too. I mean the documentation is not the API docs. We do explain concepts here, but if you are interested in the full API, you can always visit http://api.symfony.com/master/index.html or use your IDE's autocompletion support.

**Comment by WouterJ** [comment]
Besides @xabbuh's points, we do use the countable functionality of the dom crawler in this docs. I think this can be closed.

**Comment by flip111** [comment]
@xabbuh hmm i think i worded it wrong or something. Because i considered the API docs to be part of the documentation. So this is not the place to ask about the API docs?

**Comment by xabbuh** [comment]
@flip111 That's indeed something different as the API docs are generated based on the docblocks that are part of the code.
