### ISSUE TITLE
Change array() notation to short version

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#6537]
Since symfony 3.0 is PHP 5.5.9 and higher only, can we use `[]` instead of `array()` everywhere in the documentation? I find myself manually replacing this after i copy paste an example from the docs.

**Comment by xabbuh** [comment]
I am against doing this everywhere. We still need to maintain the docs for 2.x for some years and merging `2.x` branches up to `3.0` becomes a nightmare when the notations differ. We can maybe discuss to use the short syntax for new examples in 3.0 and higher (I'm pretty sure we already discussed that somewhere). Though this means mixing styles in the docs which might be confusing too.

**Comment by javiereguiluz** [comment]
I agree with @xabbuh here. The short notation is great ... but the problems it would introduce in our workflow are not worth it. I'm afraid that the situation is similar for Symfony code and we probably never use the short array syntax.

**Comment by WouterJ** [comment]
We can of course change everything (in old and new branches) to the short syntax when Symfony 2.x has all reached end of maintaince.

**Comment by javiereguiluz** [comment]
Symfony 2.x reaches end of maintenance on November 2019 ... so we'll have to wait a bit 😄

**Comment by flip111** [comment]
Doesn't look worth it, unless a pretty-print step is introduced into the documentation pipeline. That would also open up some other possibilities so might be worth looking into ^^

**Comment by WouterJ** [comment]
@flip111 what do you mean with a pretty-print step?

**Comment by flip111** [comment]
Like [CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) or [PHP Parser](https://github.com/nikic/PHP-Parser), you could serve up a customized version of the documentation. For example i also prefer 2-spaces instead of 4-spaces, this would then be trivial to do once the pipeline supports it. It would move formatting of code into the toolchain.
