### ISSUE TITLE
Version switcher on API docs

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#6538]
Almost always my entry into the symfony API is through google and i land on a page such as [this one](http://api.symfony.com/3.0/Symfony/Component/Console/Input/InputOption.html). There is no version switcher there, but there is on the [main page](http://api.symfony.com/3.0/). Would it be possible to add a version switcher on the sub-pages too?

**Comment by javiereguiluz** [comment]
I consider this issue annoying too. However we can't do anything on Symfony Docs to fix it. This is something to improve on Sami, the tool used to generate the API. See https://github.com/FriendsOfPHP/Sami

**Comment by javiereguiluz** [comment]
Closing this as "fixed" because all API pages include now the version selector. For example, the first page mentioned in the issue report: http://api.symfony.com/3.0/Symfony/Component/Console/Input/InputOption.html

**Comment by flip111** [comment]
It has improved. But please reopen because when i go to

http://api.symfony.com/2.3/Symfony/Component/Console/Input/InputOption.html

and then click on another branch in the top left i loose the page (InputOption) and i find myself back at "the start" of the documentation.

**Comment by javiereguiluz** [comment]
@flip111 I'm afraid we can't fix this from Symfony. It's configured like that [in this line](https://github.com/FriendsOfPHP/Sami/blob/3a46b98e2fa4d4819018e3767ba6346bfed92957/Sami/Resources/themes/default/layout/layout.twig#L58) of the Sami project templates

![sami_version](https://cloud.githubusercontent.com/assets/73419/18081623/65806a2c-6e9b-11e6-9175-b1ed4144e573.png)

Please open an issue in https://github.com/FriendsOfPHP/Sami repository. Thanks!
