### ISSUE TITLE
DomCrawler parents only on first node of selection?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#6542]
Not sure if i'm reading [this](https://github.com/symfony/symfony/blob/b85ab60b70f0dcff62ac8438e91e7a93c44823da/src/Symfony/Component/DomCrawler/Crawler.php#L469-L492) right. The DomCrawler seems to take the first node and traverse up the tree until the root node. But i think that the selection can have different parents, when i saw the function description i would expect it gets the parent of each node in the selection. So with 5 nodes selected i would get 5 parents, of which some could be the same parent (an array of 5 references of which some references to the same object). A better description here about what this function actually does would help a lot.

I might open up an issue on the symfony repo later, but let's improve documentation first i think ^^

**Comment by xabbuh** [comment]
The term "current selection" maybe could be improved. However, as we are talking about the method's docblock here the change would have to be done in the code. That's why I am closing here. But please feel free to open an issue in the code repository to further discuss this.

**Comment by flip111** [comment]
ok @xabbuh i assume you agree with me that it's indeed the way the DomCrawler works. How would you improve the description of "current selection" though?
