### ISSUE TITLE
[RFC] Updating the documentation of the Yaml component

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6543]
In http://symfony.com/doc/current/components/yaml/introduction.html we explain how to parse and dump using two different methods: `Parser`/`Dump` classes and static methods of `Yaml` class.

I don't like when we have several ways of doing the same thing ... and I like it less when we don't explain their differences or tell the user when to use each alternative.

So I propose the following:

  * Use the static methods to show the basic usage.
  * Explain the object oriented API later in a new section of that article.
  * Add some info about when to use each alternative.

**Comment by HeahDude** [comment]
👍 Any thought on #6524? If you want to suggest a clear roadmap here we could close it.

**Comment by xabbuh** [comment]
Oh, I completely missed this issue when creating #6598. So the first task is checked now anyway.

However, I don't think we really need to explain the internal API. I cannot think of a use case that justifies using the `Parser` or `Dumper` class directly that is so common that we should include it in the documentation. Developers who are in the need of using the classes directly will still be able to figure out how to do that themselves.

**Comment by javiereguiluz** [comment]
I'm closing this because of being partially fixed by #6524 and being partially duplicated by #6226.
