### ISSUE TITLE
Ignore invalid reference arguments in collections

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6550]
#6511 adds a description for the DependencyInjection component's feature to ignore missing arguments in method calls. symfony/symfony#17132 expanded this to also drop invalid references when being passed as part of a collection argument.

**Comment by WouterJ** [comment]
Hmm, I'm wondering if it makes sense to document this as it seems very detailed and not really usefull to 99% of the readers.

**Comment by xabbuh** [comment]
I think we can simply add a short sentence to the recently added documentation.
