### ISSUE TITLE
Outdated composer install instructions

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony-docs#6555]
[The install instructions](http://symfony.com/doc/current/cookbook/composer.html) still refers to use the `curl` command, which has been removed in favour of the installer for various reasons.

What do you want to do? Update this page or just link to [Composer install instructions](https://getcomposer.org/doc/00-intro.md)?

**Comment by xabbuh** [comment]
I think we should remove the existing document from the table of contents. Then we should update all links to it to point to the installation instructions on getcomposer.org and only keep the existing one to maintain existing deep links from other third-party pages (we could update it to directly link to the subsections of the Composer installation documentation).

**Comment by WouterJ** [comment]
We've written the article because the composer install docs still do not suggest a global installation by default. Unless that's fixed, we should keep the current doc imo.

**Comment by javiereguiluz** [comment]
I agree with Wouter.

**Comment by celdia** [comment]
We should keep this doc I think. Because we could need curl for others purposes or PHP projects.

**Comment by xabbuh** [comment]
@WouterJ is right about the reason why we added the article in the past. So we should indeed update it.

**Comment by snoek09** [comment]
I'll update the instructions.
