### ISSUE TITLE
Broken link to event API documentation

### ISSUE THREAD

**Issue by Oliboy50** [symfony/symfony-docs#6565]
Here http://symfony.com/doc/current/reference/events.html#kernel-controller (same issue with other doc versions).

This link is broken: [RequestDataCollector](http://api.symfony.com/3.0/Symfony/Bundle/FrameworkBundle/DataCollector/RequestDataCollector.html) (in the "built-in Symfony listener related to this event" table)

Maybe the link should point to the Component's RequestDataCollector class?

**Comment by alexislefebvre** [comment]
It looks like this class has been removed: http://api.symfony.com/3.0/Symfony/Bundle/FrameworkBundle/DataCollector.html

**Comment by xabbuh** [comment]
Thanks for reporting this @Oliboy50. This is indeed the wrong namespace being used here. I opened #6568 to fix it.

**Comment by WouterJ** [comment]
It's now fixed, thanks for reporting!
