### ISSUE TITLE
CsrfExtension namespace wrong in the documentation

### ISSUE THREAD

**Issue by yamiko-ninja** [symfony/symfony-docs#6602]
The documentation for the [form component](http://symfony.com/doc/current/components/form/introduction.html#csrf-protection) uses `Symfony\Component\Security\Extension\Csrf\CsrfExtension` which is not defined. 

I believe the correct class is `Symfony\Component\Form\Extension\Csrf\CsrfExtension`.

Am I right? If so I can do a pull request to update the doc.

**Comment by xabbuh** [comment]
Good catch and welcome your pull request. :)
