### ISSUE TITLE
form collection label not correct ?

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#6607]
My form prototype looks something like this

``` html
<data-prototype="<div class="form-group">
  <label class="col-sm-2 control-label required">__name__label__</label>
<div class="col-sm-10">
```

After replacement of `__name__` it looks like: `0label__`, `1label__`, etc ..

i just followed the tutorial with the matching javascript

**Comment by xabbuh** [comment]
@HeahDude Would you mind having a look here?

**Comment by HeahDude** [comment]
Hi @flip111, it seems what you're experiencing with the label is expected.

In a collection type all sub types (including the prototype) use the same `entry_options` as options, and their label should often be set to an empty string or `null`to prevent using their incrementing integer names as default or repeating the same label for all entries:
```php
'entry_options' => array(
    'label' => false,
    // ...
),
```
When not set as above, the [default label used by the prototype](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/CollectionType.php#L32) is the `prototype_name` option (default to `__name__`) suffixed by `label__`.

You could also used `data-prototype="{{ form_widget(form.tags.vars.prototype)|e }}` as in the note [there](http://symfony.com/doc/current/cookbook/form/form_collections.html#allowing-new-tags-with-the-prototype), printing only the "widget" of the prototype should avoid the label issue.

**Comment by flip111** [comment]
This shows up as the label for the CollectionType itself, seems like a bug then that the Entry label would affect the CollectionType label ??

For symfony i would suggest making the default label `__label__` and not `label__` because you also replace `__name__` and not `name__`.

For symfony-docs i would suggest making a change in the javascript part that also does something with the label. Because right now when you just follow the docs you see this `label__` and you think you did something wrong. `__name__` is handled by this line:

```js
var newForm = prototype.replace(/__name__/g, index);
```

The [part](http://symfony.com/doc/current/cookbook/form/form_collections.html#allowing-new-tags-with-the-prototype) you are pointing to says: `To render it, make the following change to your template:`. This is misleading because when you don't explicitly put it there there will be a protoype rendered anyway. Why not make it so that the code you need stays minimal and after that point to possibilities to customize it?

**Comment by HeahDude** [comment]
We cannot change the entry default label as it would be a major BC break.

`__name__` should be used to change the "name" attribute of the form, what happens here is that you can also change the prototype label using `__name__label__`.

I agree that some changes should be made on that part of the docs though, but I don' t see no bug here.

**Comment by flip111** [comment]
The comment on the bug is a mistake on my part. So you suggest to replace `__name__label__` first and then `__name__` or first `__name__` and then `label__` ?

**Comment by HeahDude** [comment]
`__name__label__` first.
