### ISSUE TITLE
Warn users that clearing the cache will sometimes make database connections

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6621]
See https://github.com/symfony/symfony/issues/18853 for details. This is a feature/bug of Symfony/Twig, so it will take some time to fix it. Meanwhile, let's add some warnings in the docs.

**Comment by csarrazi** [comment]
Actually, it's during cache warmup, not cache clear. Also, it should be made more obvious that running `cache:clear` actually triggers a cache warmup by default (i.e. without the `--no-warmup` option).

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because the related Doctrine issue was finally solved. Thanks!
