### ISSUE TITLE
Recommend to install PHPUnit from the .phar archive (without Composer)?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#6625]
According to @WouterJ:

> You shouldn't require PHPunit as a dev dependency (and you've proofed with this issue again why you shouldn't).
> 
> Download the `phpunit.phar` and put it in a directory that's in your `$PATH`.

Source: https://github.com/symfony/symfony/issues/18903#issuecomment-222294957

But the documentation doesn't recommend to install PHPUnit without Composer: http://symfony.com/doc/current/book/testing.html

Should the documentation mention that using `phpunit.phar` is the recommended way to use PHPUnit?

**Comment by JEDIBC** [comment]
I tend to disagree. 

If phpunit is not a dependency, then you don't have `\PHPUnit_Framework_TestCase` anymore and all your tests extends an abstract class which doesn't exist.

Furthermore, the IDE's won't be able to autocomplete the methods provided by PHPUnit.

**Comment by alexislefebvre** [comment]
@JEDIBC But you can't install PHPUnit with Composer and Symfony 3.1.

**Comment by JEDIBC** [comment]
I know you can't but it is a temporary situation.

Documenting that phpunit shouldn't be installed as dev dependency is an error for me.

**Comment by alexislefebvre** [comment]
@JEDIBC : Please note that this issue is an open question. I was looking for a way to avoid users frustrated by broken dependencies.

The #6628 PR may be rewritten as something like *Due to a bug in […], PHPUnit can't be installed with Composer. Until the bug is fixed, PHPUnit can be installed through the `.phar` file*.

**Comment by alexislefebvre** [comment]
It looks like the root problem has been fixed: https://github.com/phpspec/prophecy/pull/275

**Comment by alexislefebvre** [comment]
The problem has been fixed, it's now possible to install Symfony 3.1 and PHPUnit 5.4:

    $ composer require "symfony/symfony:3.1.*" "phpunit/phpunit:~5.4" --no-interaction --no-progress -vvv --profile
    […]
    [146.4MB/15.16s] Writing lock file
    [146.4MB/15.16s] Generating autoload files
    [147.2MB/15.40s] Memory usage: 147.19MB (peak: 188.62MB), time: 15.4s

(use this command only during tests, PHPUnit should go in the `require-dev` section of `composer.json`)

**Comment by Glideh** [comment]
```bash
$ composer require --dev phpunit/phpunit
```

Worked fine for me
