### ISSUE TITLE
Impossible to scroll horizontally with long snippets

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony-docs#6653]
In [Symfony ProgressBar#Custom Format](http://symfony.com/doc/current/components/console/helpers/progressbar.html#custom-formats), there is a long snippet:

<img width="739" alt="screen shot 2016-06-14 at 10 50 07" src="https://cloud.githubusercontent.com/assets/5175937/16038675/02fd9abe-321e-11e6-830e-fb6efc7260b2.png">

Not sure if the issue applies to just here or is more global.

**Comment by WouterJ** [comment]
@javiereguiluz this seems like an bug introduced with the changes documented in https://github.com/symfony/symfony-docs/issues/6531

**Comment by javiereguiluz** [comment]
@WouterJ you are right. @theofidry if you find other similar bugs, please share the links in this issue. Thanks!

**Comment by javiereguiluz** [comment]
This is now fixed upstream and it will be on symfony.com after the next deploy. Thanks!
