### ISSUE TITLE
Disable faulty translation in documentation

### ISSUE THREAD

**Issue by CoalaJoe** [symfony/symfony-docs#6657]
Hey there. You should add the no translate attribute to your symfony documentation. Otherwise google will translate them which results into false code.

![2016-06-16 11_36_49-wie https erzwingen oder http fur verschiedene urls symfony cookbook](https://cloud.githubusercontent.com/assets/5689499/16112226/b7e71452-33b6-11e6-8ca9-c702d6857740.png)

**Comment by javiereguiluz** [comment]
👍  I'm going to fix this. Thanks for reporting it.

**Comment by javiereguiluz** [comment]
I've checked this issue a bit and we have two possible solutions:

* Add the `<meta name="google" content="notranslate" />` tag to prevent translating the entire page ([reference](https://support.google.com/webmasters/answer/79812?hl=en))
* Allow to translate the pages, but prevent translating `<code>` and `<pre>`. This requires to add a `class="notranslate"` to all of these elements ([reference](http://stackoverflow.com/questions/9628507/how-can-i-tell-google-translate-to-not-translate-a-section-of-a-website/9629628#9629628))

I'd like to read some opinions about this from the community. Thanks!

**Comment by WouterJ** [comment]
Definitely solution 2 for me. If people want to translate the documentation text, I think they should be free to do so, we just have to prevent that the code examples are translated.

**Comment by xabbuh** [comment]
I agree with @WouterJ.

**Comment by javiereguiluz** [comment]
We can close this as "fixed" because this feature has been added to the private Sphinx renderer used to generate Symfony Docs. `<code>` and `< pre>` elements will now include `class="notranslate"`. We just need to wait for the deploy and the full regeneration of the docs (this could take a while). Thanks!

**Comment by xabbuh** [comment]
I am closing here then.

@CoalaJoe Please let us know if the issue persists for you the next days.
