### ISSUE TITLE
[Coding Standards] inheritdoc PHPDoc tag must always be inline.

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony-docs#6661]
A [Symfony PHP-CS-Fixer fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) named `phpdoc_inline_tag` exists:

> Fix PHPDoc inline tags, make inheritdoc always inline.

But I saw no indication about this rules on the [coding standards documentation](http://symfony.com/doc/current/contributing/code/standards.html).

This should be added IMHO to avoid confusion between bundles developer and issue opening of this kind: https://github.com/sonata-project/dev-kit/issues/180 :wink:

**Comment by ju1ius** [comment]
For reference, an excerpt of the [inheritdoc tag](https://phpdoc.org/docs/latest/guides/inheritance.html#the-inheritdoc-tag) documentation:

> Currently some applications have DocBlocks containing just the `{@inheritDoc}` inline tag to indicate that their complete contents should be inherited. This usage breaks with the PHPDoc Standard as summaries cannot contain inline tags and inheritance is automatic; you do not need to define a special tag for it.
>
> However, it does make clear that an element has been explicitly documented (and thus not forgotten). As such we are working to include a new (normal) tag in the PHPDoc Standard `@inheritDoc` that will serve that purpose.

**Comment by Soullivaneuh** [comment]
@ju1ius I don't think they follow this rule.

**Comment by ju1ius** [comment]
@Soullivaneuh which is precisely why I posted the documentation.

**Comment by Soullivaneuh** [comment]
And I think this should be discussed on another issue too. :-)

This issue is about adding missing documentation for the **actual** rule.

**Comment by ju1ius** [comment]
Ok didn't get that :wink:

**Comment by javiereguiluz** [comment]
@Soullivaneuh are you saying that we should write inheritdoc like this?

```php
/** {@inheritdoc} */
public function __construct($dummy) {
    // ...
}
```

instead of this?

```php
/**
 * {@inheritdoc}
 */
public function __construct($dummy) {
    // ...
}
```

Because I can't find a single use of the first notation in the Symfony code. It's always like the second example.

**Comment by javiereguiluz** [comment]
Closing this as fixed because the docs already say `Inline the @inheritdoc tag`. See https://symfony.com/doc/current/contributing/code/standards.html#documentation

However, I think this is wrong and I've opened #9211 to change this. Thanks!

**Comment by devnix** [comment]
Don't know if it has changed I(I doubt it) but the documentation clearly says
>**Don't** inline PHPDoc blocks, even when they contain just one tag (e.g. don't put /** {@inheritdoc} */ in a single line);
