### ISSUE TITLE
Document ConsoleLogger::hasErrored()

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6663]
We should find a good place where to document this new method (see symfony/symfony#19090).

**Comment by wouterj** [comment]
I think this can be documented in http://symfony.com/doc/current/console/logging.html , just before or after the "Logging non-0 Exit Statuses" section.

**Comment by javiereguiluz** [comment]
Instead of `console/logging.rst`, at the end I decided to document it in `console/logger.rst` because it seemed more appropriate. Thanks.
