### ISSUE TITLE
SSL & Mixed content

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-docs#6682]
Just leaving this here.. :)

https://symfony.com/doc/current/index.html

![image](https://cloud.githubusercontent.com/assets/1047696/16358916/a87558da-3b22-11e6-8dd1-ff82824e297e.png)

**Comment by WouterJ** [comment]
ping @javiereguiluz anything you want to do here or should we just close this (as sensio doesn't have ssl afaik)?

**Comment by ro0NL** [comment]
The form could be fixed at least :angel: I use _HTTPS everywhere` anyway. But perhaps its considerable to force https, google is doing it ;-)

**Comment by javiereguiluz** [comment]
@WouterJ you are right. There is nothing we can do from symfony.com point of view. The good news is that sysadmins are aware of this issue and it will be fixed in the future. Thanks!

**Comment by ro0NL** [comment]
Ah sorry, the api endpoint is http only i see now.
