### ISSUE TITLE
Outdated image on the Symfony book, page security.html

### ISSUE THREAD

**Issue by AscanderS** [symfony/symfony-docs#6694]
Hi. 
The image _security_http_basic_popup.png_ on page security.html of the Symony Book, version 2.8 (at least) on, reflects an URL of the form **localhost:8000/app_dev.php/admin** instead of one of the new style: **http://localhost:8000/admin**.

This is a very unimportant detail that remains from older versions.

**Comment by xabbuh** [comment]
ping @javiereguiluz 

Thank you for reporting this @AscanderS!

**Comment by WouterJ** [comment]
Nice catch, @AscanderS! I've submitted a fix for this in https://github.com/symfony/symfony-docs/pull/6709

@xabbuh not sure why you pinged javier here?
