### ISSUE TITLE
Document to NEVER use getRouteCollection() / how to check if route exists

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#6710]
It isn't clear for people to not use `Router#getRouteCollection()`. Using this method will regenerate the Routing cache on each request, making apps very slow. I think we should explicitely tell people to not use this method.

A common use case of this method seems to be checking whether a route exists (https://github.com/symfony/symfony/pull/19270, http://stackoverflow.com/q/14136484/1149495, http://stackoverflow.com/q/17241235/1149495, etc.). Maybe we can document to catch the `RouteNotFoundException` in such cases and then explain to not use `getRouteCollection()`.

**Comment by javiereguiluz** [comment]
@WouterJ Symfony provides `hasXXX()` methods for (almost) everything. Do you know why there isn't a `hasRoute()` method? Thanks

(In any case, an application which is not sure about its own routes and needs to check if they exist, looks fragile to me).

**Comment by WouterJ** [comment]
> (In any case, an application which is not sure about its own routes and needs to check if they exist, looks fragile to me).

It's less fragile than you might think. Take for example a site using the CMF Routing bundle, which loads routes from a database. An admin might create/remove routes that an app depends on. For example, in the CMF we had to manage the case of a menu item trying to link to a route that was removed.

 > Symfony provides hasXXX() methods for (almost) everything. Do you know why there isn't a hasRoute() method? Thanks

The router is dumped in cache. This removes the complete `$routes` array and uses static matching instead (using many nested if statements and such). So in fact, the router doesn't really know about the available routes in production (when it's cached).

**Comment by ogizanagi** [comment]
@WouterJ: But providing a new `Router::hasRoute($name)` method in which we can try to generate the route or catch the `RouteNotFoundException` would help to avoid people to rely on the `Router::getRouteCollection()` method on runtime. What do you think ?

**Comment by TiMESPLiNTER** [comment]
Maybe we should even consider to set this method to `protected`? It's only used at one place which is not in the `Router` class (constructor of `Symfony\Bundle\WebProfilerBundle\Controller\RouterController`). Or at least mark it as `@internal`.

**Comment by emovere** [comment]
My URL structure is like facebook/twitter:
site.com/Username

To let the user set the username, I need to check if a path of a route matches a username.
If getRouteCollection() should not be used, whats the correct way of checking this?

**Comment by javiereguiluz** [comment]
Fixed by #9845.
