### ISSUE TITLE
Possible typo in the documentation?

### ISSUE THREAD

**Issue by dossan** [symfony/symfony-docs#6712]
I was reading the [_first_ article](http://symfony.com/doc/current/book/http_fundamentals.html#requests-and-responses-in-symfony) in the Symfony's official book, and at a certain point there's:

    ...
    $request->request->get('bar', 'default value if bar does not exist');
    ...

Even though I'm not yet familiar with Symfony, I guess that who wrote this documentation didn't meant to access the `request` attribute of a `request` variable/object...

**Comment by dossan** [comment]
Maybe there's really a property called `request` from the next paragraphs of the same tutorial...

**Comment by WouterJ** [comment]
@dossan yes, the `Request` class has a `request` property. `$_GET` variables are put in `$request->query` (get vars are sent in the URI query) and `$_POST` variables are put in `$request->request` (post vars are sent with the request). See also the comment just above that line:

 > ```php
 > // retrieve GET and POST variables respectively
 > $request->query->get('foo');
 > $request->request->get('bar', 'default value if bar does not exist');
 > ```

I guess it's safe to close here?
