### ISSUE TITLE
Update the doc for one command applications

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#6729]
I can't find any issue/PR that updates the doc about building [single command application](http://symfony.com/doc/current/components/console/single_command_tool.html) since https://github.com/symfony/symfony/pull/16906 made it easier.

I'll try to propose it soon and reference this. If someone pick it sooner, perfect.

**Comment by lyrixx** [comment]
See: https://github.com/symfony/symfony-docs/pull/6876

**Comment by chalasr** [comment]
Closed in #6876
