### ISSUE TITLE
Update Yaml docs to list the features not supported

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6730]
The Yaml component purpose is to parse the config files in Symfony apps. We have added some additional features to make it more useful, but we'll never make it spec-compliant.

Let's improve the Yaml docs adding this note about the purpose of the component and let's list the main unsupported features (such as https://github.com/symfony/symfony/issues/12095).

**Comment by javiereguiluz** [comment]
@xabbuh and @GuilhemN you are our biggest YAML experts. Maybe you can quickly scan the TOC of the YAML 1.2 spec here http://www.yaml.org/spec/1.2/spec.html and tell me the most important features not supported by the YAML component? Then I'll make the necessary changes in the docs. Thanks!

**Comment by GuilhemN** [comment]
- Multi documents aren't supported (`---` and `...` markers in a YAML file).
- Complex mapping keys (keys beginning with `?`) and complex values (beginning with `?` too)
- Non-scalars mapping keys and soon non-string/non-int keys (in 4.0)
- Tagged values as keys
- `!!set`, `!!omap`, `!!pairs`, `!!set`, `!!seq`, `!!bool`, `!!int`, `!!merge`, `!!null`, `!!timestamp`, `!!value`, `!!yaml` (see http://www.yaml.org/type/)
- Global tags (TAG directive `%TAG ! tag:example.com,2000:app/` and global references to a tag `!<tag:example.com,2000:app/foo>`)
- Not having a key in a mapping (`{foo, bar}` should be parsed as `{foo: ~, bar: ~}`)
