### ISSUE TITLE
Note that using apache in dev needs an update in .htaccess

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#6731]
In the installation article, when people are using apache, they should change the `web/.htaccess` file to route all routes to the `app_dev.php` front controller. Otherwise, they'll keep using the prod environment during the development.

Related #6475

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because in the docs we use the builtin web server (which uses app_dev.php by default) and in a few months, everything will change because we'll have just a single `public/index.php` controller configured with env vars.
