### ISSUE TITLE
Delete or improve "How to Simulate Authentication with a Token in a Functional Test" article

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#6741]
I propose to delete the ["How to Simulate Authentication with a Token in a Functional Test"](http://symfony.com/doc/current/cookbook/testing/simulating_authentication) cookbook article:
- It's an alternative of ["How to Simulate HTTP Authentication in a Functional Test"](http://symfony.com/doc/current/cookbook/testing/http_authentication.html), but it doesn't explain when to use this or the other technique.
- At the bottom, it says _"The technique described in How to Simulate HTTP Authentication in a Functional Test is cleaner and therefore the preferred way."_ Why should we document something that's not recommended?
- The technique doesn't look clean at all.

**Comment by javiereguiluz** [comment]
I dislike the "Auth with a token" tutorial a lot. However, in complex applications the alternative "Auth in tests" technique doesn't work. I always see the first technique implemented.

---

In any case, I'd merge both articles and add a brief explanation about when to use each of them.

**Comment by javiereguiluz** [comment]
Done in #7507.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #7507.
