### ISSUE TITLE
Code blocks width no longer limited

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#6742]
Is it intended that code blocks no longer show scrollbars, but instead just increase their width untill all content fits?

See for example http://symfony.com/doc/current/cmf/bundles/create/introduction.html#rendering-content

![sf-code-block-width](https://cloud.githubusercontent.com/assets/749025/16707502/bed8cb30-45d0-11e6-9370-6475d173e33a.png)

/cc @javiereguiluz

**Comment by javiereguiluz** [comment]
Thanks for reporting this bug. Sadly the changes we introduced recently caused a million of edge cases. I'll take a look next week.

**Comment by javiereguiluz** [comment]
Related to #6910 and closing as "fixed" for the same reasons. Thanks!
