### ISSUE TITLE
Adding pictures and complete example to articles

### ISSUE THREAD

**Issue by nbro** [symfony/symfony-docs#6751]
I'm reading the Symfony's docs, and I've a few suggestions to improve it, in general.
1. First, you could add pictures of what's happening when something is being described. 
2. I think that versions of the articles and lectures in video format would also be useful. 
3. Finally, the complete and _working_ examples could be provided so that users, who eventually didn't manage to follow the article/lecture completely, because of misunderstandings, etc, could have a look at the code.

I think that in general the docs are quite good, but this doesn't mean they can't still be further improved!

**Comment by javiereguiluz** [comment]
@dossan thanks for these nice proposals!

1. Regarding the pictures, we're working on the diagrams at the moment (updating them and adding them if needed). Do you also refer to screenshots? If yes, can you remember some content where screenshots would had been helpful?
2. That will be "impossible" to achieve by the docs team. Hopefully there are already lots of third-party learning resources, such as our good friends at http://knpuniversity.com
3. This is very tricky. I agree that sometimes an entire example that can be copy+pasted is exactly what you need. However, that would be very complicated to maintain: we should copy the full example several times in the article and highlight different parts or we should show the entire example and the explain it in the next sections, losing the reference of the code. In any case, a thing that we can do, and we are actively doing at the moment, is to create shorter and more focused articles. That will help a lot for this.

**Comment by javiereguiluz** [comment]
Closing it as "fixed" because we're already working on 1) and we can't do 2) and 3). Thanks!
