### ISSUE TITLE
Consider improving the file upload tutorial

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6753]
A Symfony newcomer is having some troubles following it: https://github.com/symfony/symfony/issues/19361

**Comment by wouterj** [comment]
So the problem here is that we use the *same* property for the file path saved in the DB and the file saved in the DB.

What's very clear here is that using entities in the form is *not* the good solution for file uploads. We should instead [use a DTO for the form](http://stovepipe.systems/post/avoiding-entities-in-forms). This is a very good place to actually show this much better practice :)

**Comment by javiereguiluz** [comment]
I don't agree with Wouter's comment. Uploading a file in Symfony is already more complex than it should be. Forcing the user to create more classes and complicate things a bit more would be too much in my opinion.

My reasoning may sound simplistic, but this is what I think:

1. Symfony framework is a web framework
2. A framework helps you providing features to avoid repeating trivial and common tasks
3. Uploading files is a common and trivial task in web applications
4. Therefore, Symfony should provide "something" to make file uploads trivial

**Comment by xabbuh** [comment]
@javiereguiluz But these are two (not completely) different things: Even if we come up with a better technical solution in the Symfony core (which we would still need to find), we will still have to provide good docs for already released versions (where to me using a DTO is way better than putting stuff into your entities that doesn't belong there).

**Comment by Koc** [comment]
We could add link to bundles wich reduce boilerplate code and provide support of multiple storage systems and persistence layer, like https://github.com/dustin10/VichUploaderBundle or https://github.com/vitiko/IphpFileStoreBundle

**Comment by Koc** [comment]
relates to #5603

**Comment by javiereguiluz** [comment]
Closing this in favor of the file uploading meta-issue: #8255.
