### ISSUE TITLE
The Bundle System - Why?

### ISSUE THREAD

**Issue by ErichHartmann** [symfony/symfony-docs#6760]
Why is the bundle system still relevant? The current documents (docs) don't make a persuasive argument; and the current best practices, focused on a single AppBundle, seem to undermine the original philosophy for the Bundle System even more.

The current Symphony Book article regarding the Bundle System makes some very broad and vague _marketing_ statements (some of which now seem over taken by events), "A bundle is similar to a plugin in other software, but even better. The key difference is that everything is a bundle in Symfony, including both the core framework functionality and the code written for your application. Bundles are first-class citizens in Symfony."

Symfony2 was officially released in late-July, 2011. It was clear at the time that "decoupled and cohesive components" were a unique feature of Symfony. They obviously built the road to today's success, but are Bundles still a best practice today given 5 years of further development in both Symfony and PHP? If so, why?

If the current Bundle System remains the preeminent way of describing a decoupled, but cohesive plugin to a Symfony application, I recommend the argument made more fulsome in the documentation.

**Comment by stof** [comment]
@ErichHartmann AppBundle is the single bundle written in your project. This does not mean it is the only bundle *used* in your project.
The recommendation went to using a single AppBundle for project-specific code, because most projects using multiple bundles were not using decoupled bundles anyway, making the separation useless.
Bundles are still the way to hook into Symfony (they are the extension point of the kernel and its process building the DI container).

**Comment by ErichHartmann** [comment]
Agreed on all points, but your looking at it from the perspective of someone intimately familiar with Symfony (and years of discussions here on Github). The reason I suggested that the benefits should be made more clear in the docs is that a neophyte (the book's intended audience) isn't familiar with those details or benefits.

Most new PHP users (or new to Symfony) are simply using composer to add new project requirements to their own software with what appear to be all the same benefits-- and without the additional "bundle system". If so, then why the bundle system?

It seems clear in other parts of the documentation that adding services and simply hooking into the DI container is simply a matter of adding additional details to the configuration.

You can see bundles acting as adapters (and the benefits), but can someone who needs to read the book?

**Comment by micheal** [comment]
My view of the bundle system is a bit different.

When I add multiple bundles to my project, I don't always expect decoupling. But my goal is to provide some separation of duties.

For example, I could shove all functionality in the single AppBundle. My user entity, my blog entities, the controllers for all of those, but it gets a bit unwieldy.

What I like doing is create a `UserBundle` for my project. It's usually small with a couple of controllers and a user entity. Then I like creating a `BlogBundle`. It has several entities and a few controllers. Then I have a bundle for some other small feature of my site. While the bundles are small by themselves, I don't have to keep sorting through one monolithic bundle. I know the blog functionality is in the blog. I know the user functionality is in the user bundle. I can keep things organized that way.

**Comment by ErichHartmann** [comment]
Does not appear to be much interest here. Closed.
