### ISSUE TITLE
The components PDF is partialy rendered

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony-docs#6779]
Hi,

probably a side effect of Mercury Project, but the PDF generated for the Components documentation is partialy rendered :/

[Symfony_components_3.1.pdf](https://github.com/symfony/symfony-docs/files/390107/Symfony_components_3.1.pdf)

Mickaël

**Comment by javiereguiluz** [comment]
I'm closing this issue in favor of the meta-issue related to PDF problems: #7030. Hopefully soon we'll work on fixing those errors.
