### ISSUE TITLE
Validation groups could be easier to find

### ISSUE THREAD

**Issue by totaltrash** [symfony/symfony-docs#6782]
I was looking for information on 'validation groups', so I went to the [validation page](http://symfony.com/doc/current/validation.html), hit ctrl+f, entered 'group', and couldn't find what i was looking for. 2 suggestions:

1. Rename the link in [learn more](http://symfony.com/doc/current/validation.html#learn-more) titled 'How to Apply only a Subset of all Your Validation Constraints' to something that includes the text  'validation groups'.

2. Move that link up above the preceding link 'How to Dynamically Configure Validation Groups' (which is a more specialist article).

**Comment by javiereguiluz** [comment]
I agree that "Validation Groups" is a very common term for this feature. What if we replace the original title:

```
How to Apply only a Subset of all Your Validation Constraints
```

by something like this:

```
How to Select the Constraints to Apply using Validation Groups
```

**Comment by wouterj** [comment]
Or, something we used in other places as well to fix these issues:

    How to Apply only a Subset of all Your Validation Constraints (Validation Groups)

**Comment by totaltrash** [comment]
I think either title would make it quicker to find.
