### ISSUE TITLE
Some feedback regarding the new documentation

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#6789]
First of all, I would like to say that you guys did an awesome job! It looks really slick and I had no issues getting my way around. After some clicking, I'd like to add some feedback:
- When switching between Guides and Getting Started, the sub-menu collapses nicely. But the Components part is not a sub-menu and leaves either of the 2 other open. Also if both are closed, the Guides section is opened instead of kept closed. 
- The list of components could become a sub-menu as well, should solve the above problem.
- The Table of Contents is hidden below those menus, this means that you'll have to scroll a whole page before you see it cramped in a tiny spot. Maybe it could be moved to the right side instead? There's more than enough space on my screen (960px, width of half the screen).
- Some Guide pages have a different setup, like 1 link to another page while others have a lot of content, I'm not entirely sure what the flow behind this is.
- I would love to see a flow diagram that shows how to determine where your new documentation should be placed. Like a new feature or a guide, should I place it as link on a page or inline the guide? etc.
- The search seems broken: http://symfony.com/search?q=ArgumentResolver I'm expecting to find at least [the http kernel page](http://symfony.com/doc/current/components/http_kernel.html#httpkernel-driven-by-events) because it's mentioning this class, but I get 0 results. When I try to find the documentation about it, I can't find any of it either. Looking for http://symfony.com/search?q=controller+resolver doesn't really give me any results. Eventually I found [Extending Action Argument Resolving](http://symfony.com/doc/current/controller/argument_value_resolver.html) via the Getting Started Controller references on the bottom. However, this page doesn't belong to the routing component, it's in the HttpKernel component but isn't listed there

**Comment by Pierstoval** [comment]
Sorry for digging up this issue, but this prevents me from creating a new maybe useless one

> The Table of Contents is hidden below those menus, this means that you'll have to scroll a whole page before you see it cramped in a tiny spot. Maybe it could be moved to the right side instead? There's more than enough space on my screen (960px, width of half the screen).

I totally agree on this point: the table of contents is very important and should be the first element visible on the top left, and I would even recommend to add a left-affix to it for it to be visible anytime when scrolling.

For now, it's not intuitive at all because the global guide menu is the first element seen at the top left.

What do you think?

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed" because most of the reported issues have been solved: the list of components, the position of the TOC, the result page for ArgumentResolver, etc. Thanks for this detailed list of things to solve!
