### ISSUE TITLE
Include a guide for speed up the initialization time.

### ISSUE THREAD

**Issue by LukBukkit** [symfony/symfony-docs#6815]
I had this problem and found nothing in the documentation, so i used google and found [this article](http://stackoverflow.com/questions/12905404/symfony2-slow-initialization-time) on Stackoverflow. It would be useful, if this was included this in documentation.

**Comment by javiereguiluz** [comment]
@LukBukkit this is a nice idea! We already have an article about performance tips, so I've updated it to mention the realpath cache setting explained in the article that you linked: #6937.

**Comment by LukBukkit** [comment]
Thank you :)
