### ISSUE TITLE
list of chapters/topics are not set chronologically in specific component inside The Components documentation.

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-docs#6817]
f.e. in http://symfony.com/doc/current/components/dependency_injection.html
1. there is no longer chronologically list of topics, as it was other day, reflecting list of chapters in offline Components documentation. There is only "Learn More" at the bottom. 

So in topic http://symfony.com/doc/current/components/dependency_injection/workflow.html that at other day was last chapter still is sentense at the begining 

> In the preceding pages of this section, there has been little to say about where the various files and classes should be located.

 But now, this topic appears 3rd top on the "Learn More" list

**Comment by javiereguiluz** [comment]
You are right. I've reworded the intro in #7497.  Thanks for reporting this problem!
