### ISSUE TITLE
how to get pdf version of "The Routing Component" documentation (and other components)?

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-docs#6828]
There is no longer pdf version of components documentation available.

I would like to read f.e. http://symfony.com/doc/current/components/routing.html  in pdf. 

there is nothing about that in The Components Book at 
 http://symfony.com/pdf/Symfony_components_3.1.pdf?v=4

is these problems arise because of some work in progress?

**Comment by xabbuh** [comment]
see #6779 and #6809
