### ISSUE TITLE
[Routing] Consider adding a notice for slashes in parameter

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#6832]
Reading http://symfony.com/doc/current/routing/slash_in_parameter.html#configure-the-route, I think we should advise to use the trick only for last parameter, or be careful about using slash as separator in such cases.

ref https://github.com/symfony/symfony/issues/13017#issuecomment-231365604

**Comment by wouterj** [comment]
How is this not possible? We use it with great success in https://github.com/symfony-cmf/resource-rest-bundle

**Comment by HeahDude** [comment]
@wouterj I don't say it's not possible, sorry for the misleading.

I mean when there are other parameters following one which can have slashes, and that slashes are used as separators between those parameters, it may lead to weird behaviour for matching, or for generating url, especially if some of them are optional.

**Comment by javiereguiluz** [comment]
I'm closing this as "fixed". I know I fixed this recently, but I can't find the PR. At the bottom of this article you can find the "note" explaining this: https://symfony.com/doc/current/routing/slash_in_parameter.html

**Comment by xabbuh** [comment]
@javiereguiluz #8020 :)
