### ISSUE TITLE
Document the new kernel.controller_arguments event

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6854]
- This feature was added in Sf 3.1: https://github.com/symfony/symfony/pull/18440
- There was an attempt to document this (see #6434) but we couldn't finish it.

**Comment by mickaelandrieu** [comment]
@javiereguiluz if I may ask, your previous PR sounds "good enough" to me: why did motivate you to close it ?

Mickaël

**Comment by javiereguiluz** [comment]
@mickaelandrieu because Wouter and Stof comments made me realize that I was trying to document something that I don't fully understand. It needs more work.

**Comment by javiereguiluz** [comment]
This is the only pending issue of the [Symfony 3.2 milestone](https://github.com/symfony/symfony-docs/milestone/12) which I cannot fix myself. @stof, @iltar would you have some time to add docs for this feature or add some comment or example in this issue so I could try to write some docs? Thanks!

**Comment by javiereguiluz** [comment]
Closing as fixed by #10640. The new docs can be seen in https://symfony.com/doc/current/reference/events.html#kernel-controller-arguments
