### ISSUE TITLE
Guard Multiple Guard Authenticators entry_point config

### ISSUE THREAD

**Issue by billsworld** [symfony/symfony-docs#6859]
I am confused by this portion of the docs. Why do I need to specify the `entry_point` if I have multiple authenticators?

http://symfony.com/doc/current/security/multiple_guard_authenticators.html#multiple-authenticators-with-shared-entry-point

Also, I think the Guard docs could be helped by making it very clear that Guard does not have anything to do with your controllers. An authenticator simply listens to every request on its own and decides if authentication should take place. The `getCredentials` method is the starting block for this process.

If I am new to Guard this is the most important concept that I need to understand. Looking through a project that already uses Guard this is not obvious and the docs don't help to make it clear.

Thanks.

**Comment by wouterj** [comment]
Entry points are called when a user visits a page that requires authentication. An entry point then (for instance) redirects the user to a page where then can authenticate, e.g. a login form.

If you have multiple authenticators, the security system still needs to redirect the user to a place to authenticate the users. It can't know or guess which authenticator it needs to use to determine where to redirect the user to. This is why you must explicitly tell the Security system which authenticator to use for the redirection.

**Comment by billsworld** [comment]
ok thanks for the explanation @wouterj it sounds like the key to the ```entry_point``` is the ```start``` method.

**Comment by javiereguiluz** [comment]
Closing as fixed by #10423, which refactored and improved all Symfony security docs. Thanks!
