### ISSUE TITLE
Docs for ResetType button are unclear

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony-docs#6864]
Hi,

if we copy paste the samples produced in this page, we will generate an instance of `ButtonType` instead of `ResetType`.

2 possibles solutions:
- duplicate the templates included (few gains, few pains ?)
- Maybe add a note like this: "Note theses examples come from `ButtonType` documentation, and you have to use `ResetType::class` instead in order to generate a reset button"

What do you think ? 

Mickaël

**Comment by snoek09** [comment]
This issue is there for most code examples in the Type documentation.
To fix this a lot of include files have to be duplicated and changed to match the correct Type.

**Comment by mickaelandrieu** [comment]
@snoek09 I'm not in favor of mork work for Docs team, this is why I suggest - also - to add a notice :)

**Comment by weaverryan** [comment]
Nice catch @mickaelandrieu! Of course the first option is better, but more work. So, let's do the 2nd option.

Btw, internally, we've been talking about adding more intelligence to our build process, so that we could - in theory - include templates, but pass them variables.

**Comment by snoek09** [comment]
The `SubmitType` documentation has the same issue.

**Comment by mickaelandrieu** [comment]
Thank you @xabbuh
