### ISSUE TITLE
Make it possible to expanded the components menu item

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#6875]
This will avoid confusion when people visit the components docs.

Another solution is to collapse all menu items when visiting components docs.

Ref https://github.com/symfony/symfony-docs/pull/6874#issuecomment-239678948

/cc @javiereguiluz

**Comment by chalasr** [comment]
It would be a nice improvement 👍  Having to first visit the index is a bit annoying

**Comment by javiereguiluz** [comment]
I agree too. We'll do that in the near future (sorry, too busy at the moment).

**Comment by javiereguiluz** [comment]
This has been finally implemented and it will be online after the merge/deploy process.

---

This is how it looks:

![menu-components](https://cloud.githubusercontent.com/assets/73419/22981564/05dc9e92-f39d-11e6-951d-8db3a40d1df6.png)

---

And this is the full list (only components with docs are listed, so no Polyfills for example):

![menu-components-all](https://cloud.githubusercontent.com/assets/73419/22981575/116009d4-f39d-11e6-91c8-05311bf72ca6.png)

**Comment by HeahDude** [comment]
Is it deployed?

**Comment by javiereguiluz** [comment]
Not yet. Sorry.

**Comment by javiereguiluz** [comment]
This was finally deployed ... so let's close it as fixed. Thanks!
