### ISSUE TITLE
UniqueEntity message can't include the value

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#6929]
Constraint messages can include `{{ value }}` in the `message` option to display the wrong value introduced by the user. Apparently, you can't do the same in the `UniqueEntity` constraint, so it should be documented here: http://symfony.com/doc/current/reference/constraints/UniqueEntity.html#message

**Comment by HeahDude** [comment]
Yes, it's been introduced in 2.8.

**Comment by javiereguiluz** [comment]
I'm getting reports (via email) from people who can't make this work. By the way, what's the `{{ value }}` when the UniqueEntity is matched against several values?

**Comment by HeahDude** [comment]
The `value` always represents the validated value (ref https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L131).

By default it is not used in the validation message (ref https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntity.php#L28).

Using it in a custom message should work nevertheless.
