### ISSUE TITLE
[PhpUnitBridge] Provide guidelines to debug handler change

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony-docs#6969]
For various reasons, valid or not, the PhpUnitBridge handler may change in the process causing a generic `THE HANDLER HAS BEEN CHANGED` error message.

After discussing IRL a bit with @nicolas-grekas over an issue I had, we concluded more help could be provided in the doc regarding this issue. There is a lot of reasons why the handler may change, so there is no easy way to tell why and if it's valid or not, but some tips could be provided to avoid the user to have to debug the bridge himself to figure out what's going on. The code could then be updated to link to this doc besides this `THE HANDLER HAS BEEN CHANGED` message.

I would be glad to do the PR, but as I can't immediately I'm putting this issue as a reminder :)

**Comment by xabbuh** [comment]
What were some possible reasons you came up with?

**Comment by theofidry** [comment]
- your framework register it's error handler in the bootstrapping process (Laravel): I had trouble setting phpunit bridge in Laravel because of that
- have an error in your trigger error. If it is silenced, you won't get any information on it besides this message (`THE HANDLER HAS BEEN CHANGED`) which is not very pratical

**Comment by nicolas-grekas** [comment]
Closing since there is no trivial reason for this.
