### ISSUE TITLE
Broken link for CMF docs

### ISSUE THREAD

**Issue by mario6097** [symfony/symfony-docs#7002]
hi

at http://symfony.com/doc/master/cmf/bundles/content/index.html
link/button 'Download as pdf' opens a "Not found page" http://symfony.com/pdf/Symfony_cmf_2.0.pdf?v=4

cheers
mario

**Comment by javiereguiluz** [comment]
I'm closing this in favor of #7268 which links to all the issues related to the doc build problems. Thanks!
