### ISSUE TITLE
Missing information about cache integration inside framework bundle

### ISSUE THREAD

**Issue by Koc** [symfony/symfony-docs#7006]
http://symfony.com/doc/master/reference/configuration/framework.html
1. there is no mention about cache section
2. some other cache references are outdeted - for example `framework.annotations.cache` default is `php_array` https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L598 but doc says that is `file`

//cc @nicolas-grekas

**Comment by Steveb-p** [comment]
Please, whoever is/will be adding documentation for it, note that pools declared in configuration are private by default :)

**Comment by nicolas-grekas** [comment]
3.2 added the framework.cache.prefix_seed config entry

anyone willing to give it a try?

**Comment by HeahDude** [comment]
Is https://github.com/symfony/symfony-docs/pull/7245 enough to close here?

**Comment by xabbuh** [comment]
Closing here for now. If someone disagrees, please scream. :)

**Comment by Koc** [comment]
@HeahDude, @xabbuh 

http://symfony.com/doc/master/reference/configuration/framework.html#reference-annotations-cache

> 2. some other cache references are outdeted - for example framework.annotations.cache default is php_array https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L598 but doc says that is file

also there is no any mention about how to enable tagged cache

**Comment by joksnet** [comment]
FrameworkBundle configuration reference [framework.rst](https://github.com/symfony/symfony-docs/blob/master/reference/configuration/framework.rst#cache-1) says:

> Set this option to `validator.mapping.cache.doctrine.apc` to use the APC cache provide from the Doctrine project.

But is deprecated according to [UPDAGRE-3.4.md](https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.4.md#frameworkbundle):

> The `validator.mapping.cache.doctrine.apc` service has been deprecated.

**Comment by teohhanhui** [comment]
@joksnet That's not related to this issue.

**Comment by javiereguiluz** [comment]
Closing thanks to #11367 and all the other recent PRs related to the Cache. Thanks.
