### ISSUE TITLE
Issues with PDFs generated for doc contents

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7030]
This is a meta-issue to fix all the issues related to PDF contents:
- [ ] [No PDF generated for Symfony CMF Bundles, Components, Cookbook](https://github.com/symfony/symfony-docs/issues/5048)
- [ ] [The components PDF is partialy rendered](https://github.com/symfony/symfony-docs/issues/6779)

**Comment by BatsaxIV** [comment]
Hi, any news for this bug? It would have been nice to download the entire components documentation in PDF:)

**Comment by javiereguiluz** [comment]
I'm closing this in favor of #7268 which links to all the issues related to the doc build problems.
