### ISSUE TITLE
Best practices possibly leading users into security issue

### ISSUE THREAD

**Issue by emil-nasso** [symfony/symfony-docs#7087]
On the best practices pages, there is a section about twig extensions.

https://github.com/symfony/symfony-docs/blob/master/best_practices/templates.rst

In the `getFilters()` method `is_safe` is set to `array('html')`. According to the twig documentation; "If your filter acts as an escaper (or explicitly outputs HTML or JavaScript code), you will want the raw output to be printed. In such a case, set the is_safe option:".

``` php
public function getFilters()
    {
        return array(
            new \Twig_SimpleFilter(
                'md2html',
                array($this, 'markdownToHtml'),
                array('is_safe' => array('html'))
            ),
        );
    }
```

If someone new to symfony reads this (they probably are if they are just reading the best practices for the first time) this would probably use the new filter like this:

```
{{ comment.body|md2html }}
```

This is a security issue if the comments body contains user inputted data. With the  snippet above, no escaping is automatically performed. The proper way to use it would be like this:

```
{{ comment.body|escape|md2html }}
```

Another option would be to add some form of escaping in the extension. You could use the symfony escaper (probably prefered, don't know how to do that though, or enable esaping in parsedown ( https://github.com/erusev/parsedown/wiki/Tutorial:-Get-Started ).

Either way, i think this should be documented and explained in the best practices documentation. Right now there is no explaination about `is_safe` or any usage example.

There are probably many ways to solve this like adding a usage example that uses `{{ comment.body|escape|md2html }}` and explains why you have to escape or leave that out and just have some sort of warning-text that tells the reader about the issue and the possible solutions.

I can update the documentation, but i'm not sure what kind of change would be preferred.

**Comment by javiereguiluz** [comment]
@emil-nasso thanks for rising this concern. It's always tricky to balance security with a good developer experience.

You explained everything perfectly, so let's focus on the possible solutions:

1) Enable the markup escaping in our Markdown parser. It's built-in and super easy to use: `->setMarkupEscaped(true)`
2) Escape the original contents before passing them to the Twig extension. We can do this with the `pre_escape` Twig option ([see details](http://twig.sensiolabs.org/doc/advanced.html#automatic-escaping)).

**Comment by Simperfit** [comment]
@javiereguiluz I would vote for solution one  ;)

**Comment by emil-nasso** [comment]
I think i would vote for solution two. :) That would make it a solution that is useable when you write an extention that isn't using this exact library. It also keeps escaping consistent, the symfony/twig method is always used.
