### ISSUE TITLE
not working example in "How to Override any Part of a Bundle"

### ISSUE THREAD

**Issue by gehadibtikar** [symfony/symfony-docs#7093]
Hi,
The *.class parameters was removed from symfony.
https://github.com/symfony/framework-bundle/commit/3777050007e7dfef257087ef1f954a8cc7c27883

because of that the example related to overriding the translator class not working anymore in symfony3.

```
# app/config/config.yml
parameters:
    translator.class: Acme\HelloBundle\Translation\Translator
```

http://symfony.com/doc/current/bundles/override.html

**Comment by xabbuh** [comment]
Thanks for reporting this mistake @gehadibtikar. Luckily, this will be fixed when we merge #7090.
