### ISSUE TITLE
Make "forward" or "cross" links discernible

### ISSUE THREAD

**Issue by mpdude** [symfony/symfony-docs#7103]
It would be great if we could have some kind of marker, icon or similar for links that are forward references within the same page.

Here's why: When trying to read a documentation page from top to bottom, I often come across many links and references I consider important. I have developed the habit of opening these links in a new tab immediately as a kind of "reading list", to make sure I follow up the other sections as well.

If I could tell from looking at the linked text that it forward-references a section I will come across anyway later on the current page, I don't need to open this tab. It will rather confuse me if I later on find to have a page open I've already read.

Does that make sense?

**Comment by javiereguiluz** [comment]
After thinking about this, we've decided to not implement this feature. It's true that it can be useful in some specific cases, but the occurrence of same-page anchors is very low in Symfony docs.

Although this time your proposal didn't make it, please keep proposing improvements to the Symfony Docs and website. Thanks!
