### ISSUE TITLE
[Form] Add documentation for DataMapperInterface

### ISSUE THREAD

**Issue by B-Galati** [symfony/symfony-docs#7121]
Hello,

I think it would be a really good idea to document this interface as it represents an awesome feature with forms. It has been documented on some blog posts like [webmozart](https://webmozart.io/blog/2015/09/09/value-objects-in-symfony-forms/) but that's all.

What do you think ? Is it voluntary ?
Thanks.

**Comment by ogizanagi** [comment]
Hi @B-Galati .

There is a pending PR about this long-time undocumented feature: See https://github.com/symfony/symfony-docs/pull/6900

If you're more interested by this feature, you can also give a look to https://github.com/symfony/symfony/pull/19367 ;)

**Comment by B-Galati** [comment]
Thanks @ogizanagi ! I looked for a similar issue/PR before opening this one but I missed them :disappointed: 

Anyway, thanks again. I close this issue as it is a duplicated.
