### ISSUE TITLE
Help us being featured at "24pullrequests"

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7123]
Hi all,

We are trying to get Symfony Docs featured in 24pullrequests. If you think that this repo is friendly to newcomers and useful helping contributors, please vote `+1` to the following comment:

https://github.com/24pullrequests/24pullrequests/issues/1570#issuecomment-258847496

Thank you!

**Comment by yceruto** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Let's close this issue as "fixed" because we already made the Symfony community aware of this initiative. Now let's wait and see if they decide to accept our proposal. Thanks!
