### ISSUE TITLE
Review all the articles related to bundles

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7126]
As Fabien said [in this comment](https://github.com/symfony/symfony/pull/19596#issuecomment-248515375):

> I think that the [bundle] extension system should never be used for anything but Open-Source/shared bundles.

But if you read the [article about creating an extension class](http://symfony.com/doc/current/bundles/extension.html) you don't see a big warning message saying: *"DON'T USE THIS in your Symfony app. This is only useful if you create bundles published as third-party bundles."*

I feel that the same goes for other articles, but I cannot share here specific links to those articles.

---

So, I'd like to revisit all the articles related to bundles, simplify the articles related to in-app bundles and better separate them from articles related to third-party bundles.

**Comment by wouterj** [comment]
Until https://github.com/symfony/symfony/pull/20107 is merged, creating Extension class for the AppBundle still makes sense.

But I agree on the main idea behind this issue. I've already done this while rewriting the extension/configuration articles: http://symfony.com/doc/current/bundles/configuration

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because the future of Symfony is bundle-less, so it will be impossible to create "bundle extensions" for your own app ... you won't have bundles in the first place!
