### ISSUE TITLE
[API DOC] 3.0 & 3.1 : incomplete Controller documentation

### ISSUE THREAD

**Issue by renomarx** [symfony/symfony-docs#7138]
Hello,

I don't really know if this is the place to report this issue, but i've found something weird on symfony API doc :
Since Symfony 3.0, some public methods have been made private in Base Controller: 
3.1 : https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php

2.8 : https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php

In consequence, the API documentation does not contain methods signature anymore : 
http://api.symfony.com/3.1/Symfony/Bundle/FrameworkBundle/Controller/Controller.html

In consequence some links in Symfony Documentation for the Base Controller are broken, like in this page: 
http://symfony.com/doc/current/controller.html
With link : 
http://api.symfony.com/3.1/Symfony/Bundle/FrameworkBundle/Controller/Controller.html#method_generateUrl

**Comment by xabbuh** [comment]
This is indeed an issue with how the API docs are generated as it only exposes public elements.

@fabpot Is that something that can easily be fixed by updating the config of Sami or doesn't Sami support documenting non-public methods at all?

**Comment by xabbuh** [comment]
Looks like this is related to FriendsOfPHP/Sami#236.

**Comment by javiereguiluz** [comment]
@xabbuh in the PR that you linked it looks like anything non-private is exposed, so protected methods should be exposed. So there might be another issue related to this.

**Comment by stof** [comment]
@javiereguiluz is the prod using Sami 4 ?

**Comment by javiereguiluz** [comment]
I can't confirm the Sami version, but it's probably 3.2.1-DEV

**Comment by javiereguiluz** [comment]
I've double checked this issue and it looks like we didn't enable the docs for non-public methods. This config was missing:

```php
// document all methods and properties
$sami['filter'] = function () {
    return new TrueFilter();
};
```

I've proposed this fix and, if accepted, it will eventually be merged/deployed on symfony.com

**Comment by stof** [comment]
@javiereguiluz any news about the fix ?

Btw, I would not use a TrueFilter. We don't want to document private methods. Use the DefaultFilter in Sami 4 (and implement a dedicated filter in Sami 3 copying the Sami 4 implementation as the DefaultFilter was different in Sami 3)

**Comment by xabbuh** [comment]
@javiereguiluz Was the fix ever deployed? Did it change anything?

**Comment by javiereguiluz** [comment]
Not yet. We need the new Sami version, which can't be deployed on our current server. "Soon" we'll change to a better srver where we can deploy anything and we'll finally fix this. Thanks.

**Comment by javiereguiluz** [comment]
Closing this issue here because we already have an issue in the internal repository of symfony.com to track this. It all depends on some server migration which still doesn't have an estimated completion date. I'm sorry.
