### ISSUE TITLE
Missing documentation for assets.version_strategy

### ISSUE THREAD

**Issue by darrylhein** [symfony/symfony-docs#7143]
I can't find documentation on the configuration option `assets.version_strategy`. It appears to work (setting to a service name), but I can't find anything in the [framework/assets config section](http://symfony.com/doc/current/reference/configuration/framework.html#assets) regarding it.

If it is truly missing, I can write the documentation.

**Comment by javiereguiluz** [comment]
@darrylhein you are so right! Luckily we have two pending pull requests about this:

* https://github.com/symfony/symfony-docs/pull/7140
* https://github.com/symfony/symfony-docs/pull/7141

They'll be merged soon, so I'm closing this issue as fixed. Thanks!
