### ISSUE TITLE
[HttpFoundation] Trusted Proxies verification code

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony-docs#7153]
I struggled to get Symfony to work properly with my trusted proxy.

I believe a section with code snippets on how to verify if your trusted proxy settings are working would go a long way to making things easier to debug. It was hard to know how to check.  

Perhaps something to check the $request object vs the headers?

http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html
or
http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html

**Comment by javiereguiluz** [comment]
I'm closing this old issue because in the past months we improved the docs about trusted proxies, so hopefully this was solved. Thanks.
