### ISSUE TITLE
[HttpFoundation] Trusted Proxies SSH tunnel / stunnel note

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony-docs#7154]
I struggled to get Symfony to work properly with my trusted proxy.

I believe that a note would have been using, about how if you are using a SSH tunnel or stunnel between your haproxy server and webserver (they are not on the same box) that your trusted proxy ip may be `127.0.0.1` and that you should not list the actual IPs for your haproxy servers, but localhost instead.

http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html
or
http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html

**Comment by javiereguiluz** [comment]
Closing this old issue because the current article about trusted proxies (https://symfony.com/doc/current/deployment/proxies.html) mention the `127.0.0.1` IP and explains the special scenarios where it may make sense.
