### ISSUE TITLE
Document the cache.prefix_seed option

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#7162]
When you deploy multiple applications into the same path (on different servers) that share the same cache backend you need to configure the `cache.prefix_seed` option to prevent naming collisions.

**Comment by xabbuh** [comment]
@nicolas-grekas Anything from your side to add here?

**Comment by nicolas-grekas** [comment]
You also need to set this option when using blue/green deployment strategies.

**Comment by nicolas-grekas** [comment]
And more generally, when you need to completely abstract out the actual deployment directory (think offline cache warmups)

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/20616
