### ISSUE TITLE
Add docs for the new VarDumper features

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7177]
I don't know if all of them should be documented, but VarDumper added a ton of new features in Symfony 3.2:

* [x] Add maxDepth & maxStringLength display options (https://github.com/symfony/symfony/pull/18948), will be covered by #7217
* [x] Get dump as string with `$dumper->dump(..., true);` (https://github.com/symfony/symfony/pull/19755)
* [x] Add LinkStub to create links in HTML dumps (https://github.com/symfony/symfony/pull/19816)
* [x] Add ClassStub for clickable & shorter PHP identifiers (https://github.com/symfony/symfony/pull/19826)
* [x] Add flags to allow fine tuning dumps representation (https://github.com/symfony/symfony/pull/17305), will be covered by #7217
* [x] Allow dumping subparts of cloned Data structures (https://github.com/symfony/symfony/pull/19672)
* [ ] Optionally pass dumper into DumpExtension (https://github.com/symfony/symfony/pull/18466)

**Comment by phrix32** [comment]
[symfony/symfony#19755](https://github.com/symfony/symfony/pull/19755) has already been documented with [this commit](https://github.com/symfony/symfony-docs/commit/3033bc7c7a331390c2123b11a5f530c6c390e5ec#diff-a51810423ba9cbb1cdad9af3a5501a5fR159)

**Comment by phrix32** [comment]
[symfony/symfony#19672](https://github.com/symfony/symfony/pull/19672) has already been documented with [this commit](https://github.com/symfony/symfony-docs/commit/cb66d83236a9b33f806e22d7ec0ae5621f6642d5#diff-a51810423ba9cbb1cdad9af3a5501a5f)

**Comment by sawmurai** [comment]
No idea where / if to document https://github.com/symfony/symfony/pull/18466. Any ideas anyone? 

This PR ads the missing documentation (#18948 and #17305). The rest (except for #18466) already is documented.

PR: https://github.com/symfony/symfony-docs/pull/7217

**Comment by xabbuh** [comment]
@phrix32 Thank you for this great investigation. I have transformed the issue description into a list of tasks and checked both items.

**Comment by sawmurai** [comment]
https://github.com/symfony/symfony/pull/19816 and https://github.com/symfony/symfony/pull/19826 were documented with 3033bc7c7a331390c2123b11a5f530c6c390e5ec.

https://github.com/symfony/symfony/pull/18948 and https://github.com/symfony/symfony/pull/17305 are documented with https://github.com/symfony/symfony-docs/issues/7217. So only https://github.com/symfony/symfony/pull/18466 is left. No idea where do document this, tho.

**Comment by xabbuh** [comment]
Right now you have to replace the `var_dumper.html_dumper` service or modify it to your needs in a compiler pass when using the full stack Symfony framework.

**Comment by sawmurai** [comment]
@xabbuh Should that be documented at all? I would think that most of the time the default HtmlDumper is used anyway. If it should be documented: how? Provide config example for a service definition or simply class instantiation?

**Comment by xabbuh** [comment]
I am not sure if it's really worth documenting that.

**Comment by chalasr** [comment]
I think the HtmlDumper search utility added in 3.3 deserves a mention as well (https://github.com/symfony/symfony/pull/21109, https://github.com/symfony/symfony/pull/21238)

**Comment by xabbuh** [comment]
@chalasr thanks, I created #7381

**Comment by gabiudrescu** [comment]
I would add two more things to the documentation of VarDumper:
 - that dump() function is not available by default in PROD environment for a Symfony Standard instance
 - you can use `{{ dump() }}` in Twig to dump all available variables. 

the first one I'd add because I found the hard way that deploying an app where you used dump() in a template will end up with a HTTP 500. 

the seconds is a funny thing I just discovered while watching some KNP tutorials. 

if you agree with my proposal, I can submit a PR.

**Comment by xabbuh** [comment]
Both sound like a good idea to me. The first one should probably be a warning in the existing article. For the argumentless `dump()` call I am not sure yet where to place it though.

**Comment by javiereguiluz** [comment]
Closing as "fixed" because the only missing item is related to the Twig's DumpExtension, which is not documented in any way in the docs. Thanks.
