### ISSUE TITLE
Add docs for array values in route defaults

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7180]
In https://github.com/symfony/symfony/pull/11394 @xabbuh added support for array values in route defaults. Should we document this?

**Comment by xabbuh** [comment]
I am not sure if we really need to document it. However, to give some context: The missing support for arrays for default values in the XML format was noticed when dealt with #4017.

**Comment by javiereguiluz** [comment]
@xabbuh OK then. Let's close this as "won't fix". Thanks.
