### ISSUE TITLE
A typo in "The book, Chap2, page 19"

### ISSUE THREAD

**Issue by MedUnes** [symfony/symfony-docs#7202]
I think there is a typo in **"The book, version 2.8" at Chapter2, Page19.**

It have been stated:

> "For organization, both controllers (formerly index.php and show.php) are now PHP functions and each has been moved into a separate file named controllers.php:",

while the context talks about list.php and show.php

I have attached a picture to illustrate this.
![image](https://cloud.githubusercontent.com/assets/8580094/20754972/91f05026-b70d-11e6-9ad8-5960405dadb1.png)

**Comment by MedUnes** [comment]
another  typo at the same page:

> But **but** careful not to confuse the terms

Should be:
But **be** careful not to confuse the terms.

![image](https://cloud.githubusercontent.com/assets/8580094/20757320/0979f25c-b716-11e6-8aae-afab89b2c840.png)

**Comment by xabbuh** [comment]
Thank you for reporting these typos @MedUnes. I opened #7207 which fixes the second one. Though I do not fully understand which issue you see with your first example. Can you explain this with more details or describe what you would like to see instead?

**Comment by MedUnes** [comment]
The two controllers are (listAction() and showAction() ) so the sentence should have been written 

> "For organization, both controllers (formerly **list.php and show.php**) are now PHP functions and each has been moved into a separate file named controllers.php:",

instead of

> "For organization, both controllers (formerly **index.php and show.php**) are now PHP functions and each has been moved into a separate file named controllers.php:",

**Comment by xabbuh** [comment]
But the filename used before on that page always was `index.php` when referring to the controller (`list.php` was only ever used for the template), wasn't it?

**Comment by MedUnes** [comment]
if so it might be, though the context is a bit confusing, it might need more precision.

**Comment by xabbuh** [comment]
Yeah, you might not be wrong. It's sometimes hard to tell that because of different perspectives. Do you have an idea how we could improve the current wording?

**Comment by javiereguiluz** [comment]
I agree with @MedUnes and I've opened #7838 to fix the remaining issue.
