### ISSUE TITLE
Missing images in Workflow Component

### ISSUE THREAD

**Issue by dominikhajduk** [symfony/symfony-docs#7209]
Hello,
thanks for great job with SF 3.2! 

On page: https://symfony.com/doc/current/components/workflow.html image related to workflow is missing: https://symfony.com/doc/current/_images/states_transitions.png. File exist but in:  https://symfony.com/doc/3.2/_images/states_transitions.png.

![screen shot 2016-12-01 at 19 02 14](https://cloud.githubusercontent.com/assets/11769575/20805864/c290fc1c-b7f8-11e6-8ff8-8d2998d9e26a.png)

Unfortunately the same I get here:
* https://symfony.com/doc/current/workflow/dumping-workflows.html
* https://symfony.com/doc/current/workflow/state-machines.html
* https://symfony.com/doc/current/workflow/usage.html

One more after visit: https://symfony.com/doc/master/components/workflow.html Workflow is only mentioned but doc missing. Not sure bug or feature? ;)

**Comment by stof** [comment]
@javiereguiluz can you have a look at this ?

**Comment by gitomato** [comment]
Hello,
From what I understand, component images should be in this directory (in their own subdirectory) :
https://github.com/symfony/symfony-docs/tree/master/_images/components

**Comment by javiereguiluz** [comment]
The image path looks correct in the `.rst` file and in the generated HTML code. I've asked to the sysadmins to take a look at this. Let's wait a bit and see. Thanks!

**Comment by xabbuh** [comment]
Thank you for reporting this @dominikhajduk. It looks like the issue is resolved now.

**Comment by dominikhajduk** [comment]
Yes. Thank you.
