### ISSUE TITLE
Missing option placeholder in form options

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony-docs#7238]
hello

there is no option placeholder in any version
http://symfony.com/doc/current/reference/forms/types/form.html

**Comment by HeahDude** [comment]
Hi @poolerMF I'm not sure to understand your issue.

Every form can use `placeholder` as a key of the `attr` option. But the `placeholder` option is tied to `ChoiceType` and its children to handle an extra item without value in choice lists (i.e "Choose something").

**Comment by poolerMF** [comment]
I'm sorry, your're right ... my mistake
