### ISSUE TITLE
[SensioFrameworkExtraBundle] Incorrect docs version

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony-docs#7244]
http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html
shows
http://symfony.com/doc/master/bundles/SensioFrameworkExtraBundle/annotations/converters.html
instead of 
http://symfony.com/doc/3.0/bundles/SensioFrameworkExtraBundle/index.html

**Comment by javiereguiluz** [comment]
I'm super late to this ... but I've finally managed to fix it locally and it will be online on symfony.com after the next merge and deploy.

Thanks for reporting this issue!

**Comment by vudaltsov** [comment]
Awesome, thnx

**Comment by HeahDude** [comment]
@javiereguiluz can be closed now?

**Comment by javiereguiluz** [comment]
Not yet. Sorry.

**Comment by javiereguiluz** [comment]
This was finally deployed ... so `current` now shows `3.0` instead of `master`. Thanks for reporting it!

**Comment by vudaltsov** [comment]
@javiereguiluz, thanx for fixing it ;)
