### ISSUE TITLE
[DI] Documentation for the autowire() shortcut method

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#7255]
The new `autowire()` method of the `ContainerBuilder` that was introduced in symfony/symfony#20648 is a shortcut for `$container->setDefinition($id, (new Definition($class))->setAutowired(true))`.

**Comment by wouterj** [comment]
This method can be documented in http://symfony.com/doc/current/service_container/definitions 

The method can also be document and used in the PHP code examples in http://symfony.com/doc/current/components/dependency_injection/autowiring.html

**Comment by GuilhemN** [comment]
see https://github.com/symfony/symfony-docs/pull/7858
