### ISSUE TITLE
Is user_checker missing from the Security configuration defaults docs

### ISSUE THREAD

**Issue by darrylhein** [symfony/symfony-docs#7259]
I'm looking at this page https://github.com/symfony/symfony-docs/edit/3.2/reference/configuration/security.rst and wondering if `user_checker` is missing, if it's meant to missing, or if I'm just missing it.

**Comment by xabbuh** [comment]
Actually, it looks like this page completely misses all the firewall related config options. Do you think it would be helpful to have all of them documented here?

**Comment by darrylhein** [comment]
I'm seeing the firewalls section starting at line 121...or am I misunderstanding?

**Comment by xabbuh** [comment]
Indeed, but that's only the full default configuration. Though I agree we should add it here. However, further down where we explain more option we don't have anything about the firewall related options.
