### ISSUE TITLE
Serializer doc issues

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7282]
Reported by @magarzon in the #support channel of Symfony's Slack:

-----

Is there a way to disable the cache for the serializer? I'm having problems with the cached metadata, I've tried to set cache: false in framework config, but it's not working

Weird thing is that there is a service defined serializer.mapping.cache.symfony that is a "memory cache", but that doesn't works with the serializer, it complains that doesn't implements Doctrine\Common\Cache\Cache interface. Probably an issue?

because it has the "same" name as the recommended cache in the documentation, serializer.mapping.cache.apc

Probably it's my code, I'm going to check

No, it's not my code, it's  documentation not up-to-date and probably bad naming: serializer.mapping.cache.apc is deprecated since 3.1, but is still recommended in this doc without any warning: https://symfony.com/doc/current/serializer.html#enabling-the-metadata-cache

**Comment by javiereguiluz** [comment]
Can anyone with experience using Serializer please verify this bug report? Thanks!

**Comment by xabbuh** [comment]
The `serializer.mapping.cache.apc` service is indeed deprecated since https://github.com/symfony/symfony/pull/18567 (merged into the `3.1` branch).

**Comment by javiereguiluz** [comment]
If someone understands the Serializer component well, please continue my failed pull request to fix this: https://github.com/symfony/symfony-docs/pull/8133/files  Thanks!

**Comment by javiereguiluz** [comment]
@xabbuh in my failed PR (#8133) you made some useful comments about how to fix this. Do you think you could finish this issue yourself? It's the last one pending in the ancient [Symfony 3.1 milestone](https://github.com/symfony/symfony-docs/milestone/11), so it'd be great to finish it. Thank you!

**Comment by xabbuh** [comment]
see #10039
