### ISSUE TITLE
choice_value callback argument can be null

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#7311]
For example, when the initial data of the form type is `null`, the callback used for the `choice_value` option will receive `null` as an argument. We need to make this clear in the reference of the `ChoiceType`. See symfony/symfony#21116 for more context information.

**Comment by HeahDude** [comment]
There were also https://github.com/symfony/symfony/issues/20402, https://github.com/symfony/symfony/issues/19246.

One of my resolution for 2017 is to get back to work on the docs :), so a first step will be to finish https://github.com/symfony/symfony-docs/pull/6393.
