### ISSUE TITLE
The debug:router command now displays the controller class name

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7332]
This command now displays the "callable" of the controller. If this command output is displayed somewhere, we need to update the contents.

See https://github.com/symfony/symfony/pull/20809

**Comment by mickaelandrieu** [comment]
The only reference to this command doesn't show a command output for a specific route, see https://symfony.com/doc/current/routing/debug.html#main

Even if you think it's worth to complete the actual docs, we can close this issue.

**Comment by javiereguiluz** [comment]
@mickaelandrieu closing it then! Thanks for reviewing it. (We don't include the full command's output unless there is a good reason to do it ... so let's not include it here either).
