### ISSUE TITLE
Validator now supports DateTimeInterface instances for times

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7333]
Added in https://github.com/symfony/symfony/pull/21106

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" because the current validator docs don't mention DateTime, so there's no need to mention that DateTimeInterface is also supported.

**Comment by xabbuh** [comment]
@javiereguiluz Imho we should reopen here. In the [Time constraint reference](http://symfony.com/doc/current/reference/constraints/Time.html) we have the following sentence:

> Validates that a value is a valid time, meaning either a `DateTime` object [...]

**Comment by javiereguiluz** [comment]
@xabbuh thanks! I've created #7405 for this.
