### ISSUE TITLE
Missing details in symfony-docs/configuration/micro_kernel_trait.rst 

### ISSUE THREAD

**Issue by olberger** [symfony/symfony-docs#7348]
The "[Building your own Framework with the MicroKernelTrait](http://symfony.com/doc/current/configuration/micro_kernel_trait.html)" article misses a few details so that it works "out of the box".

Here's a list of some I've spotted:

- The php -S should be issued inside web/
- an example _app/Resources/views/micro/random.html.twig_ could be provided

Hope this helps.

Best regards,

**Comment by dominikhajduk** [comment]
@olberger proposed PR with missing views https://github.com/symfony/symfony-docs/pull/7568

**Comment by dominikhajduk** [comment]
Proposed also PR for first mentioned issue https://github.com/symfony/symfony-docs/pull/7570

**Comment by dominikhajduk** [comment]
@olberger @xabbuh as both points are described now I think issue can be close.
