### ISSUE TITLE
Advice about bootstrap file is not up to date

### ISSUE THREAD

**Issue by garak** [symfony/symfony-docs#7357]
This part of the docs http://symfony.com/doc/master/performance.html#use-bootstrap-files looks not up to date with latest changes made in this PR https://github.com/symfony/symfony-standard/pull/1030

**Comment by teohhanhui** [comment]
I think the docs can also recommend removing https://github.com/symfony/symfony-standard/blob/v3.2.6/composer.json#L35 when using PHP >= 7.0, say with this in `composer.json`:

```json
{
    ...
    "require": {
        "php": ">=7.0.0",
        ...
    }
    ...
}
```

The related code blocks could also be removed from both `app.php` and `app_dev.php`.

**Comment by ricknox** [comment]
Current issue status:

- Present in [2.7](http://symfony.com/doc/2.7/performance.html#use-bootstrap-files) (Requires PHP `>=5.3.9`). Advise: keep it.
- Present in [2.8](http://symfony.com/doc/2.8/performance.html#use-bootstrap-files) (Requires PHP `>=5.3.9`). Advise: keep it.
- Present in `3.0`, `3.1` and `3.2` but are not maintained versions.
- Not present in `3.3` (Requires PHP `^5.5.9|>=7.0.8`). Advise: add note about version lower than PHP 7.
- Not present in `3.4` (Requires PHP `^5.5.9|>=7.0.8`). Advise: add note about version lower than PHP 7.
- Not present in `4.0` (Requires PHP `^7.1.3`). Advise: don't change or add anything.

ping: @weaverryan @xabbuh @javiereguiluz

**Comment by xabbuh** [comment]
If I am not completely mistaken, we had changes during the last half year which more or less ignored legacy PHP versions like 5.3 and so on. To me, we could just bring the docs for 2.7 and 2.8 in line with the Symfony 3 docs.

**Comment by javiereguiluz** [comment]
Closing as fixed. 2.8 and 3.4 include the "bootstrap" section but with a big warning about PHP 7. Starting from 4.0, the "bootstrap" section no longer exists. Thanks!
