### ISSUE TITLE
[FrameworkBundle] Config subpaths can now be dumped

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7370]
See https://github.com/symfony/symfony/pull/20689

`config:dump-reference` now takes a second optional argument to only dump part of the entire config. Example:

```
$ ./bin/console config:dump-reference FrameworkBundle profiler
```

**Comment by chalasr** [comment]
Are we used to document options of a command? We did the same change in 3.2 for `debug:config` (https://github.com/symfony/symfony/pull/18940) but the whole command doesn't seem to be documented

**Comment by javiereguiluz** [comment]
@chalasr I think you are right ... but I'm not sure, so I've created #7375 and I'll let Doc Maintainers to decide what to do. Cheers!
