### ISSUE TITLE
Explanation of Session/NamespacedAttributeBag usage

### ISSUE THREAD

**Issue by alexwybraniec** [symfony/symfony-docs#7378]
The docs for Sessions (setting up, configuring, extending) and especially NamespacedAttributeBag are pretty poor.

Seemingly this SO response gives the only clue as to how to make NamespacedAttributeBag work in Symfony 3.

http://stackoverflow.com/questions/12279247/how-to-use-namespaced-sessions-in-symfony2/12279483#12279483

I will attempt to improve the docs myself, but before I start is there a better reference to look at first?

**Comment by ThomasLandauer** [comment]
I've taken a first step to explain this: https://github.com/symfony/symfony-docs/pull/7643

**Comment by javiereguiluz** [comment]
Fixed by #7643.
