### ISSUE TITLE
The Console Helpers page contain incorrect partial and title

### ISSUE THREAD

**Issue by dominikhajduk** [symfony/symfony-docs#7429]
The Console Helpers page (http://symfony.com/doc/2.7/components/console/helpers/index.html) contains incorrect partial taken probably from http://symfony.com/doc/2.7/components/index.html and title `The The Console Helpers Component` > `The Console Helpers`.
This issue occurs for all versions from 2.0 to the current one.
I tried find that place but after few approaches I'm done. Can't find solution. If you can please give me some idea I can look deeper.

![screen shot 2017-01-30 at 22 17 44](https://cloud.githubusercontent.com/assets/11769575/22442160/a3f29844-e73a-11e6-9738-883033d45092.png)

**Comment by javiereguiluz** [comment]
@dominikhajduk thanks for reporting this error. It's normal that you couldn't find the place to fix this ... because it belongs to the symfony.com source code, so it can't be fixed in this repository. I'm going to take a look into this. Thanks!

**Comment by javiereguiluz** [comment]
This bug has just been fixed and it will be deployed into production soon. In my local environment, this is how this page looks now:

![symfony-console-helpers-doc](https://cloud.githubusercontent.com/assets/73419/22462965/d86fe7aa-e7af-11e6-920d-b9646adf0e3c.png)

**Comment by dominikpgs** [comment]
👍 thanks!

**Comment by javiereguiluz** [comment]
This was finally deployed, so I'm closing it as fixed.
