### ISSUE TITLE
Constructors are now always autowired

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7436]
As of https://github.com/symfony/symfony/pull/21306 the constructor is now always autowired, so there's no need to add `__construct` here:

```yaml
services:
    Foo\Bar: { autowire: ['__construct', 'set*'] }
```

**Comment by weaverryan** [comment]
Closing this. In 3.3, it's the same behavior as 3.2, so there's nothing to change (except to doc the ability to autowire method calls, but that's a different issue already)
