### ISSUE TITLE
Document AbstractRecursivePass

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7440]
In https://github.com/symfony/symfony/pull/21327 a new `AbstractRecursivePass` was introduced. Not sure if we need to document this, but it's cool because it removes lots of boilerplate code.

**Comment by chalasr** [comment]
Not sure we need to document this too. IMHO you don't need to use this unless you have a lot of passes with such boilerplate code like in the core, which is unlikely to happen in final applications I think. I might be wrong, let's see what other think.

**Comment by xabbuh** [comment]
Agreed, I can't think of an everyday example where this could be useful.

**Comment by javiereguiluz** [comment]
Closing then. Thanks for your comments!
