### ISSUE TITLE
[DI] autowiring-types deprecated in place of aliases

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#7445]
See symfony/symfony#21494

Not only do we need to remove autowiring-types, we should show clearly how you can use aliases to choose what class should be autowired for a specific interface/class.

Also, Stof noted that you can/should mark these aliases as private: we don't need them to be available on the final, cached container.

**Comment by javiereguiluz** [comment]
In case it's useful: http://symfony.com/blog/new-in-symfony-3-3-deprecated-the-autowiring-types

**Comment by mvrhov** [comment]
With this deprecated, can I get a different path to implement the feature in this PR https://github.com/pomm-project/pomm-bundle/pull/55/commits/4b998267a18da9199eb7284ae592bccc45236f02#diff-f3fa84fa353839f0e811b03d9d0c24b6
