### ISSUE TITLE
[Deploy] Deployment to Swisscom Application Cloud (Cloud Foundry based)

### ISSUE THREAD

**Issue by lbayerl** [symfony/symfony-docs#7448]
Before I start a pull request for this doc (which would be my first) I'd rather prefer to ask whether that's interesting for the community and ask for some feedback if valuable at all.

There is a [section](https://symfony.com/doc/current/deployment.html#using-platforms-as-a-service) in the docs about how to deploy on Platform as a Service.

So far there is no part about [Cloud Foundry](https://www.cloudfoundry.org/) based PaaS offerings like Swisscom Application Cloud, IBM Bluemix and others.

We are not related to Cloud Foundry or any of those offerings but created a full how-to and example on how to deploy a standard Symfony application on Swisscom Application Cloud on [Github](https://github.com/lbayerl/symfony-on-swisscomdev).

I already (automatically) created an rst version of it.

Is this something you're interested in?

**Comment by javiereguiluz** [comment]
We must close this as "won't fix" because as part of our efforts to simplify things, in #8721 we've removed all deployment articles.

**Comment by laytoneverson** [comment]
@lbayerl, have you published this anywhere else? I am lost and feel that your writeup may help...

**Comment by lbayerl** [comment]
Yes, you can find it here: https://github.com/lbayerl/symfony-on-swisscomdev
