### ISSUE TITLE
Fix "How to Change the default Target Path Behavior" article

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7449]
Article: http://symfony.com/doc/current/security/target_path.html

Problems:

* It looks too complex
* It uses `.class` parameters
* It assumers that you are using the Symfony Framework (services.yml, AppBundle, etc.) but the article belongs to the components (maybe this is not an error because there's no other way to explain it).

**Comment by yceruto** [comment]
Related to https://github.com/symfony/symfony-docs/issues/5547

**Comment by javiereguiluz** [comment]
Closing because the `/security/target_path.html` article no longer exists in Symfony 3.3 or newer.
