### ISSUE TITLE
Enhance logging in compiler passes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7475]
Should we add a mention to this? See https://github.com/symfony/symfony/pull/21396

**Comment by iltar** [comment]
I can't find any documentation of this feature at all in the current docs. I think it would be nice to have this documented for more advanced usages.

**Comment by nicolas-grekas** [comment]
Not sure this needs doc, the profiler panel is enough IMHO.

**Comment by xabbuh** [comment]
I agree
