### ISSUE TITLE
Best Practices: Parameter naming

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony-docs#7504]
http://symfony.com/doc/current/best_practices/configuration.html is silent on the naming of (app) parameters.

Ideally they should all be prefixed by `app.` to avoid any naming conflicts. If that's undesirable, then we should add a recommendation not to use the dot (.) character in parameter names, in order to avoid any potential conflicts with parameters defined by bundles.

**Comment by robfrawley** [comment]
Why would it be undesirable to use period in service names? Otherwise, I agree it could be helpful to newcomers to provide guidance on service naming. I, myself, have gone through a number of distinct naming conventions in different projects. :-)

**Comment by teohhanhui** [comment]
Using the period character opens up the opportunity for conflict. Consider:

FosUserBundle defines all of its parameters starting with `fos_user.` -
according to Symfony's [Best Practices for Reusable Bundles](
https://symfony.com/doc/current/bundles/best_practices.html)

If the app defines any parameters starting with `fos_user.` it's then
susceptible to having conflicts.

Thus the only safe way is to use `app.` (because we do not and should not
expect there to be any `AppBundle` out there) or to avoid periods
altogether.

**Comment by robfrawley** [comment]
I follow until you say "or avoid periods altogether" as I fail to see how that would help stop conflicts. There are a ton of services that could be overridden if someone avoids periods, such as "annotation_reader", "doctrine", "file_locator", "filesystem", "event_dispatcher", "http_kernel", and more. Thus, avoiding periods does not avoid conflicts.

**Comment by teohhanhui** [comment]
Yes, you're right. That's why that was my fallback option, if prepending
`app.` to everything is deemed undesirable.
