### ISSUE TITLE
Add docs for the new WebLink component

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#7515]
see symfony/symfony#21478

**Comment by javiereguiluz** [comment]
This feature is now a new component called WebLink. See https://github.com/symfony/symfony/pull/22273 and https://symfony.com/blog/new-in-symfony-3-3-weblink-component

**Comment by guzzlefry** [comment]
Would it be possible to mention this in "http://symfony.com/blog/new-in-symfony-3-3-asset-preloading-with-http-2-push"? Google finds that when searching for "http/2 push symfony".

Also, a quick mention of how to enable it.

**Comment by javiereguiluz** [comment]
@dunglas has published a nice article about WebLink and HTTP/2 push, etc. See https://dunglas.fr/2017/10/symfony-4-http2-push-and-preloading/

He asked me if it would be OK to use that article as the base of the docs of the WebLink component. I think it's a good idea. @xabbuh @wouterj @weaverryan what do you think? Thanks!

**Comment by xabbuh** [comment]
I think it should be split into several smaller articles or shortened a bit, but as a starting point this looks like a good idea to me.

**Comment by javiereguiluz** [comment]
Fixed by #10309.
