### ISSUE TITLE
Missing references in FrameworkBundle Configuration doc

### ISSUE THREAD

**Issue by maidmaid** [symfony/symfony-docs#7525]
Working on symfony/symfony#21081, I found a few missing references in [FrameworkBundle Configuration ("framework")](https://symfony.com/doc/current/reference/configuration/framework.html) documentation. It's:

- [x] ``framework.profiler.matcher.ips`` -> this option was removed: https://symfony.com/doc/4.0/profiler/matchers.html
- [x] ``framework.workflow.*`` -> https://github.com/symfony/symfony-docs/pull/11041
- [x] ``framework.session.use_cookies`` -> https://github.com/symfony/symfony-docs/pull/11039
- [x] ``framework.session.metadata_update_threshold`` -> https://symfony.com/doc/current/reference/configuration/framework.html#metadata-update-threshold
- [x] ``framework.request.*`` -> https://symfony.com/doc/current/reference/configuration/framework.html#request
- [x] ``framework.validation.static_method`` -> https://github.com/symfony/symfony-docs/pull/11040
- [x] ``framework.property_info`` -> https://symfony.com/doc/current/reference/configuration/framework.html#property-info
- [x] ``framework.cache.*`` -> https://symfony.com/doc/current/reference/configuration/framework.html#reference-cache

**Comment by javiereguiluz** [comment]
I'm closing this as fixed 🎉  because everything has been documented or there are open pull requests for adding the docs. Thanks for reporting this.
