### ISSUE TITLE
Install Unreleased Symfony Version uses 2.7 as example

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#7529]
[This page](https://symfony.com/doc/current/setup/unstable_versions.html#main) shows how to install Symfony 2.7. So the example is outdated.

Should it be changed to the next LTS `3.4` or major release `4.0` instead? We may show as an exemple `3.3` today but the page will need to be updated after every release, every 6 months.

The page may also be improved by adding a link to the [roadmap](https://symfony.com/roadmap?version=2.7#checker) or [releases](https://symfony.com/doc/current/contributing/community/releases.html) so that users know what unstable versions are available.

**Comment by wouterj** [comment]
I think we may even delete the article, https://symfony.com/doc/current/setup.html#basing-your-project-on-a-specific-symfony-version shows how to install unstable versions.

**Comment by alexislefebvre** [comment]
Thanks @wouterj. Should I open a PR now or wait for more comments on this issue?

**Comment by HeahDude** [comment]
It is not outdated since 2.7 is still maintained. Doing so will install the master commit of this branch before next patch release instead of the current stable patch tagged in 2.7.

**Comment by wouterj** [comment]
Thinking about this a bit more, I think we should keep the article, but update some things:

 * Reorder the sections, first do "Upgrading your Project to an Unstable Symfony Version" and then "Creating a New Project Based on an Unstable Symfony Version". Updating a project to test an RC release is more common than creating a new project to test it.
 * Replace `composer create-project` with `symfony new ...` unstable install things (and especially the beta/RC commands, which can be usefull)
 * Update both sections to focus more on installing RC and beta releases and less on installing the dev version.
 * (Maybe updating the "Upgrading your Project to an Unstable Symfony Version" by installing a completely unthinking dev version, e.g. "Assume 2.94 hasn't been released yet")

If you can do the changes in a PR (or maybe just some of these), it would be very awesome! :)

**Comment by HeahDude** [comment]
Let's wait for Flex before doing to much change on this part :).

**Comment by alexislefebvre** [comment]
Now that Flex has been released, what should be done about the page mentioned in this PR?

**Comment by alexislefebvre** [comment]
This has been fixed in #8625.
