### ISSUE TITLE
Document the new _instanceof section for services configuration

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7538]
See https://github.com/symfony/symfony/pull/21530

**Comment by javiereguiluz** [comment]
**Update**  As of https://github.com/symfony/symfony/pull/22286 this feature is no longer experimental.

**Comment by weaverryan** [comment]
See also symfony/symfony#22234

**Comment by javiereguiluz** [comment]
Closing it as fixed by #7807.

**Comment by weaverryan** [comment]
Actually, it looks like this was not covered in #7807. I mention it at the bottom of the issue description as "not covered". So, we still need this somewhere :).

**Comment by HeahDude** [comment]
See #8239.
