### ISSUE TITLE
Simplified UserPasswordEncoderCommand

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7539]
Not sure if we show the details of this command ... but if we do, we must update it because it was simplified to show a choice list of possible user classes.

See https://github.com/symfony/symfony/pull/20677

**Comment by ogizanagi** [comment]
I don't think the command was documented somewhere. But maybe a simple note could be added in the ["How to Manually Encode a Password"](https://symfony.com/doc/current/security/password_encoding.html) page for the cases someone is seeking how to manually encode the password, but does not search the programmatic way (for instance when adding a user to the in_memory provider)

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" because we already mention the command here http://symfony.com/doc/current/security.html#c-encoding-the-user-s-password  and we don't explain the details or show its output ... so there's nothing to update!
