### ISSUE TITLE
Build the Documentation Locally (does not works in Windows)

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-docs#7548]
I have recently tried to build the documentation locally and this throws an exception during the build process:

> _build\make html
Running Sphinx v1.3.1
making output directory...
A Translator for the html builder is changed.
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 622 source files that are out of date
updating environment: 622 added, 0 changed, 0 removed
reading sources... [ 37%] configuration/external_parameters <===
Exception occurred:
  File "C:\Python27\lib\site-packages\sensio\sphinx\configurationblock.py", line 65, in run
    innernode = nodes.emphasis(self.formats[language], self.formats[language])
KeyError: u'apache' <===

This is due to some (code-block) languages such as [`apache`][1], [`nginx`][2], [`terminal`][3] (and maybe other) are absent into (`sphinx-php` python extension) [formats collection][4]?

However, the online documentation looks very well.

  [1]: https://github.com/symfony/symfony-docs/blame/3.2/configuration/external_parameters.rst#L96
  [2]: https://github.com/symfony/symfony-docs/blame/3.2/configuration/external_parameters.rst#L105
  [3]: https://github.com/symfony/symfony-docs/blame/3.2/configuration/external_parameters.rst#L110
  [4]: https://github.com/fabpot/sphinx-php/blob/master/sensio/sphinx/configurationblock.py#L20-L35

**Comment by snoek09** [comment]
How was sphinx-php installed? Did you use:
`pip install sphinx~=1.3.0 git+https://github.com/fabpot/sphinx-php.git`

I don't know how this works for Windows.

**Comment by robfrawley** [comment]
@yceruto The code block languages you referenced are handled by the core [Pygments](http://pygments.org/)-based [Sphinx](http://www.sphinx-doc.org/en/stable/) code block highlighting engine, not [sphinx-php](https://github.com/fabpot/sphinx-php). If I understand the `sphinx-php` implementation correctly, code blocks are routed there so it can _add additional_ languages, as well as perform some additional operations to simplify code blocks, and then calls are forwarded to the core implementation. How have you setup your environment? Building the docs works perfectly fine on Linux using the base set of `sphinx` packages in combination with `sphinx-php`.

**Comment by javiereguiluz** [comment]
@yceruto the Apache, Terminal, etc. are configured in this file: https://github.com/symfony/symfony-docs/blob/master/_build/conf.py#L114  which should be used by "build make".

**Comment by yceruto** [comment]
@robfrawley, @javiereguiluz Yes, you're right, this issue comes from build configuration, in this sense, I've executed `$ _build\make html`, but in Windows this one try to load the `conf.py` from the root folder instead, so I can't build that :( ?
```
Error: Config directory doesn't contain a conf.py file.
```

**Comment by snoek09** [comment]
What happens if you `cd` to the `_build` directory first and do a `make html` there?

**Comment by yceruto** [comment]
@snoek09 then:
```
Sphinx error:
master file C:\...\symfony-docs\_build\index.rst not found
```

My only one workaround was to copy `_theme` folder and `conf.py` file to the root and execute `_build\make html` then this work.

**Comment by snoek09** [comment]
Thank you! I think `Make.bat` should be updated. What happens if you change line 8 to:

```
set BUILDDIR=.
```

**Comment by yceruto** [comment]
@snoek09 nothing change :( same errors

**Comment by snoek09** [comment]
Also for `_build\make html`?

**Comment by yceruto** [comment]
@snoek09 Yes.

 * **In linux** and `_build$ make html` execute: 
```
sphinx-build -b html -c . -d ./doctrees  ../ ./html 
``` 
 * **In Windows** after install all deps to build this documentation, `$ _build\make html` execute:
```
sphinx-build -b html -d _build/doctrees  . _build/html`
```
The bug is clear now, if I execute `...\_build$ sphinx-build -b html -c . -d ./doctrees  ../ ./html` in Windows all right!

**Comment by yceruto** [comment]
I think both files `make.bat` and `Makefile` should make the same to perform the same procedure in both environments.
