### ISSUE TITLE
Document the new route definition for invokable controller (annotation)

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-docs#7549]
PR: https://github.com/symfony/symfony/pull/21723

I have planned to add it as a separate topic into [Learn more about Routing][1] (to startup), however, I'm not sure if it should be inserted elsewhere as subtopic.

  [1]: http://symfony.com/doc/master/routing.html#learn-more-about-routing

**Comment by TomasVotruba** [comment]
Can be closed as PR is merged
