### ISSUE TITLE
[Form] Missing note about validation and form type tests

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#7566]
Somehow we should add a note to mention the [TypeTestCase](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Tests/Extension/Validator/Type/TypeTestCase.php) from the validator extension.

Ref https://github.com/symfony/symfony/pull/21780.

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because this class was removed (https://github.com/symfony/symfony/pull/21960) and the alternative solution was already documented in #7578.
