### ISSUE TITLE
Fix the current docs of SonataAdminBundle

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7579]
Moved from https://github.com/symfony/symfony-marketing/issues/385

---

Maybe you could help us changing this to the right docs:
http://symfony.com/doc/current/bundles/SonataAdminBundle/index.html

This leads to 2.x instead of 3.x, which is the current version of sonata

**Comment by OskarStark** [comment]
2.x is not supported anymore (same for the other sonata bundles)
3.x is current
and
master is...master and will be the next major

**Comment by javiereguiluz** [comment]
Thanks ... I've made those changes (and aliased "master" to "4.x"). It will be fixed once merged and deployed.

**Comment by Moltchalivyi-Koder** [comment]
https://symfony.com/doc/master/bundles/SonataAdminBundle/getting_started/the_form_view.html#configuring-the-form-mapper

No longer possible to do that :
`$formMapper->add('title', 'text');`
Instead:
`$formMapper->add('title', TextType::class);`
don't forget to add this line above the class : 
`use Symfony\Component\Form\Extension\Core\Type\TextType;`
