### ISSUE TITLE
Update allowed changes on classes in BC promise

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#7597]
I see some points that could be good to update in the document:

- When an element is flagged `@final` or is final, some "no" in the list of allowed changes ("Changing classes") become "yes", such as adding/removing argument, more generally all changes that could break when extending the element
- An argument _can_ be added to a public method (depending on some conditions) using `func_get_args`/`func_num_args`.

WDYT? 
/cc @GuilhemN

**Comment by GuilhemN** [comment]
> When an element is flagged @final or is final, some "no" in the list of allowed changes ("Changing classes") become "yes", such as adding/removing argument, more generally all changes that could break when extending the element

:+1:, same applies for final methods.
I would change that either by add a reference to a note (eg [6]) or reword `No` to `No, unless final` where needed.

> An argument can be added to a public method (depending on some conditions) using func_get_args/func_num_args.

:+1:, in fact it would be great to specify the bc layer we use for each kind of change (removing a class, remove a property, etc).

**Comment by theofidry** [comment]
Careful though, a class that have been flagged as `@final` cannot be changed yet and are still subject to the same BC promises as before. It's simply like for the `@deprecated`, they will change in the future and that will be a BC.

**Comment by GuilhemN** [comment]
see https://github.com/symfony/symfony-docs/issues/7597
