### ISSUE TITLE
"How to Upload Files" is misplaced under the Routing component

### ISSUE THREAD

**Issue by gjuric** [symfony/symfony-docs#7606]
When viewing the [article](http://symfony.com/doc/current/controller/upload_file.html) the breadcrumb shows it is located under:

 `Documentation / The Components / The Routing Component / How to Upload Files`

**Comment by xabbuh** [comment]
@javiereguiluz Can you have a look here?

**Comment by javiereguiluz** [comment]
Closing this in favor of the file uploading meta-issue: #8255.
