### ISSUE TITLE
[3.3][DI] Calls Autowiring with @required

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#7608]
See symfony/symfony#21763

Because there have been so many iterations on the DI component for 3.3, I'm not sure what's documented / has docs issues and what doesn't. So, apologies of this is a duplicate - but I wanted to help make sure that all the different parts of this are not forgotten.

**Comment by metamaker** [comment]
Quoting from https://github.com/symfony/symfony/pull/21763:

> **it tells the reader that this method needs to be called for correct instantiation** - thus lowering one drawback of setter injection (discoverability).

This. Isn't that a design smell? **After constructor call, object must be already good enough to be used.**

Setter injection for optional arguments is amazing thing, but I can live with defaults that are provided during object construction in 99% of cases. However, requiring user of class to always call `setFoo` after instantiation is a good sign of bad design that `@required` enforces (temporal coupling, better explanation http://blog.ploeh.dk/2011/05/24/DesignSmellTemporalCoupling/).

Moreover, I don't feel good about reading some class code from top to bottom, so I could finally find some random `@required` reference in 500 LOC written by someone who worked 2 years before me. Imagine that this person instantiated class somewhere outside container and called `setFoo` somewhere after 100 child method calls, or, surprise!, has forgotten to do so. If something is wrong with instantiation we need to fail fast, and in that hypothetical case we failed in 100 child method calls or day of debugging nightmare (but class still remains victim of bad design -- required dependencies must REALLY be passed in constructor; if you can mutate service, then you can never be sure what you will have as result till you execute a program, which enforces long night debugging sessions -- oh, and I "love" when I happen to deal with code that mutates shared services from service_container and that mutator code is happening somewhere in Doctrine EventSubscriber).

Other thing is that for years it was standard that when we use annotation, we have to write declaration statement `use MyFavouriteAnnotation as Y;` on top of .php file, e.g. we have this pattern in Symfony Routing annotations, Doctrine annotations, JMS Serializer annotations, etc. What will happen if I imported `@required` annotation from somewhere already? As far as I see, I can't make alias to Symfony's `@required`. What if I happened to write `@required` for something completely random in description? I can't disable it when `autowiring: true` :(

**Comment by nicolas-grekas** [comment]
Closing as this is documented already.
