### ISSUE TITLE
Wrong deprecation message for ClassLoader

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7615]
In the 3.2 version (http://symfony.com/doc/current/components/class_loader.html) we can see a warning saying that the component is deprecated in 3.3.

We should remove it and keep it only for 3.3 version (http://symfony.com/doc/master/components/class_loader.html).

**Comment by xabbuh** [comment]
I deliberately merged #7383 into the `2.7` branch as I wanted to make this deprecation as visible as possible. IMO there is no good reason why someone should start a new project based on the ClassLoader component even with Symfony 2.7 or 2.8. So why shouldn't we make everybody aware of the deprecation as soon as possible (this is not like with other deprecations where you would really need newer versions of a component to be able to use the non-deprecated approach for a particular feature)?

**Comment by HeahDude** [comment]
I tend to agree with @xabbuh, this is more about the PHP version used and OPCache being available from 5.5.

Maybe we should either move it in 3.3 only or add a sentence to explain why this deprecation is not like others for consistency?

**Comment by javiereguiluz** [comment]
OK then. Let's close it! Thanks!
