### ISSUE TITLE
[Form] [DX] Collection of form with delete empty is not clear

### ISSUE THREAD

**Issue by murilolobato** [symfony/symfony-docs#7630]
[Instructions about delete_empty](http://symfony.com/doc/current/reference/forms/types/collection.html#delete-empty) are partially ok. It instructs only that allow_delete must be enabled.

If you have a collection of another form type, and you want that empty items are deleted, you have to dig around the web (old issues and wrong workarounds), to discover that you just have to set `entry_options => array('required' => false)` at the collection definition.

I've discovered this searching in the issues. And found https://github.com/symfony/symfony/issues/13940 which points to https://github.com/symfony/Form/blob/master/Tests/Extension/Core/Type/CollectionTypeTest.php#L145-166 

I think, we could update the collection doc, in the section of delete_empty, to warn the developers about this behavior. And, why this `entry_options => array('required' => false)` makes sense? In my opinion, i think it is not legible. I'm available to help!

UPDATE
I have just found, why `required => false` makes sense. http://symfony.com/doc/2.8/reference/forms/types/form.html#empty-data

**Comment by murilolobato** [comment]
Does anyone have a suggestion where to add instructions? I can make it, if you think it's wortwhile.

**Comment by HeahDude** [comment]
Hello @murilolobato thank you for working on this :). I think a caution block under the `delete_empty` option definition should do the trick.

**Comment by murilolobato** [comment]
I've just made the pull request! https://github.com/symfony/symfony-docs/pull/7767 thanks for help! Waiting for your suggestions.
