### ISSUE TITLE
Should we remove the docs versioning?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7644]
I know it sounds like a radical idea, but what if we get rid of the doc versioning? Checking our Google Analytics stats:

* 80% of doc pageviews use `current` as the version.
* The only versions without residual traffic are: 2.0, 2.3, 2.7 and 2.8.

The "pros" of doing that:

* Massive simplification for the doc management
* Minor simplification for doc readers (it's "minor" because 80% of them already don't care about versioning, so they won't notice any difference)
* Some of our docs clearly don't need versioning (contributing, quick tour, etc.)

The "cons" of doing that:

* We should maintain the "versionadded" directives forever, because you only have 1 doc and you may need to know if something was added in 2.6, 3.2, etc.
* In some articles we may need to add a "changelog" section at the end to explain the things that were removed or those which changed a lot.

If our backlog wasn't so long, instead of removing the versioning, we could simplify it using Git tags to create snapshots of the docs. Example: when 3.3 code is released, we create the tag for 3.2 docs.

**Comment by xabbuh** [comment]
I think removing the versions would make some parts barely unreadable as the reading flow would be disturbed by countless `versionadded` blocks or useless information you don't need.

It's true that there are some parts where we in fact do not need any versions at all. For those I suggest to just remove the version switcher on symfony.com instead (in Git we don't have any differences between the maintained branches for these parts anyway).

**Comment by iltar** [comment]
What about 1 per major?

**Comment by HeahDude** [comment]
👎 for one per major for the reason given by @xabbuh. Keeping it this way allow to keep a current version with version added only from it.

We recently updated our policy to explicit the fact that every minor allow to clean them up removing unmaintained branches.

The cons are to big, it is not worth it IMHO.

**Comment by javiereguiluz** [comment]
Closing this as "won't fix" because most doc maintainers are against it. Thanks for the discussion!
