### ISSUE TITLE
Documenting a bundle-less setup as of 3.3

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#7655]
Now that 3.3 is near, it would be a really nice thing to have the documentation explain how to use an application without bundles in your repository (vendor bundles allowed). @wouterj mentioned on slack, this could be a new subguide somewhere. The only "issue" I see at the moment is that it conflicts with the best practices. I would personally like to see this guide written in a way that a new developer can use it, but opens up the road to a stronger setup for the more experienced devs that like decoupling and explicitness.

The following things should probably be explained in this guide:
 - How to register your controllers (with the new DI possibilities)
 - How to do this with explicit service definitions (no auto-wiring as opposed above)
 - How to register your entities if you use this with doctrine
 - How to register commands in your application
 - How to load resources (which is already documented via best practices, via `app/Resources`)
 - How to manipulate the container (via kernel `build()` and such)
 - Did I forget anything?

Closely related to symfony/symfony-standard/pull/1034

/cc @dunglas

**Comment by javiereguiluz** [comment]
Please, don't work on this yet. There are some changes coming for Symfony 3.4/4.0 related to this. Thanks!

**Comment by javiereguiluz** [comment]
I'm closing this because of the same reasons given in #5535. This proposal is no longer optional but absolutely mandatory. We must update ALL docs for bundle-less apps introduced in Symfony 4.0.
