### ISSUE TITLE
Added a new asset versioning strategy that reads a manifest JSON file

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7659]
See https://github.com/symfony/symfony/pull/22046 and https://symfony.com/blog/new-in-symfony-3-3-manifest-based-asset-versioning

**Comment by Ricknox** [comment]
I am picking up this documentation piece.

**Comment by javiereguiluz** [comment]
@Ricknox my guess is that we need to:

* Document the new `json_manifest_path ` option here: https://symfony.com/doc/current/reference/configuration/framework.html#assets
* Add a note at the beginning of this article https://symfony.com/doc/current/frontend/custom_version_strategy.html explaining that in Symfony 3.3 the example explained in the article is now a built-in Symfony feature.

**Comment by javiereguiluz** [comment]
@ricknox just asking: will you have time to contribute this doc before the end of next week? I'd like to have this merged soon because it's very important for the new JavaScript tool that we're going to introduce to manage assets in Symfony apps. If you don't have time, please tell me and I'll write this doc. Thanks!

**Comment by ricknox** [comment]
@javiereguiluz I totally forgot about this piece of documentation. Cannot pick this up at the moment, I am sorry. Will pick up another soon! Thanks.

**Comment by robfrawley** [comment]
@javiereguiluz If you're tight on time with all the other documentation you are writing/reviewing, I'm happy to pick this up and can have something for tomorrow.

**Comment by javiereguiluz** [comment]
Thanks a lot!  I'll wait then for your PR :)
