### ISSUE TITLE
[RFC] [Validator] Suggest to apply `\Locale::canonicalize()` before validating with `Locale` constraint

### ISSUE THREAD

**Issue by phansys** [symfony/symfony-docs#7660]
It would be nice to have a note about [`\Locale::canonicalize()`](http://php.net/manual/en/locale.canonicalize.php) within the `Locale` constraint documentation, since many times locales are expressed using other "uncanonicalized" formats. By instance, a common use case is to infer the locale from javascript, where `navigator.language` returns values like "en-US" instead of "en_US"; making the `Locale` constraint to fail.
The canonicalization process is explained at [ICU project](http://userguide.icu-project.org/locale#TOC-Canonicalization).

**Comment by phansys** [comment]
As a side note, and to add more reasons for this suggestion, the referenced article at Wikipedia for [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes) doesn't mention anything about the separator to use between the language and country codes.

**Comment by fabpot** [comment]
Will be a feature implemented in 4.1 (see referenced PR).
