### ISSUE TITLE
[3.3] Changes to trusted_proxies config

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#7671]
See https://github.com/symfony/symfony/pull/21830

**Comment by javiereguiluz** [comment]
This morning @iltar had some issues about this:

> The Symfony\Component\HttpFoundation\Request::setTrustedProxies() method expects a bit field of Request::HEADER_* as second argument. Defining it is required since version 3.3. See http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html for more info.
> ...
> But I can't find anything about the second argument, I have no clue what I should pass along
