### ISSUE TITLE
Improved flash messages handling in Twig templates

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#7676]
Symfony 3.3 will get a simpler way to deal with flash messages in Twig templates: symfony/symfony#21819

**Comment by Ricknox** [comment]
I'm going to work on this.

**Comment by wouterj** [comment]
@Ricknox if you reference this issue number in the PR body, the PR will be referenced in this issue. Which is quite a nice way to indicate that this issue has a PR.

Even more, if you prefix the number with "close/closed/closes or fix/fixed/fixes" (e.g. `Fixes #7676`) in the commit or PR body, this issue will be closed automatically when the PR is merged.
