### ISSUE TITLE
Improve documentation on importing routes from a directory

### ISSUE THREAD

**Issue by BabakMN** [symfony/symfony-docs#7678]
Ref: Symfony [#22092](https://github.com/symfony/symfony/issues/22092)

Ref: [Documentation](https://github.com/symfony/symfony-docs/blob/de0446828ea77d82cf010261792c6262079b95f5/routing/external_resources.rst)

> When pointing to a directory, all files in that directory are parsed and put into the routing.

It appears that a `type: directory` is required for this feature to work.

**Comment by javiereguiluz** [comment]
Fixed by #9102.
