### ISSUE TITLE
[FrameworkBundle] Multiple services on one Command class

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7703]
Maybe we need to review some description because of this: "Introduced the possibility of using multiple command-services with one command class. This should make Commands much more equal to other services in Symfony."

See https://github.com/symfony/symfony/pull/22120

**Comment by claudioflagbit** [comment]
Is this still a thing? Anything I can help with my introduced PR?

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" because this change just removed some special behaviour about command services ... now it's fixed and it works like any other service, so there's nothing special to document.

**Comment by SenseException** [comment]
I'm glad that I was able to help to introduce an improvement for commands.
