### ISSUE TITLE
[DI] Add "by-id" autowiring: a side-effect free variant of it based on the class<>id convention

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7706]
See https://github.com/symfony/symfony/pull/22060

**Comment by weaverryan** [comment]
Actually, this is more important now - as we're introducing a BC break in 3.3 related to this: https://github.com/symfony/symfony/pull/22295

**Comment by weaverryan** [comment]
The BC break is gone, but it's now the preferred way to explicitly define all services (and not let autowiring automatically create them for you)

**Comment by HeahDude** [comment]
Closing here as fixed by https://github.com/symfony/symfony-docs/pull/7807 which is now merged.
