### ISSUE TITLE
[DI] New container.service_subscriber & ServiceSubscriberInterface

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#7740]
See symfony/symfony#21708

**Comment by weaverryan** [comment]
@chalasr This is pretty closely related to #7458, right? Would it make sense to put them all in the same article?

**Comment by chalasr** [comment]
@weaverryan This is a whole concept (built on top of #7458) allowing to request some entries from the DIC at the PHP level. I think it deserves its own article, the need for this feature should be different that the one for #7458 (right now the class must know which services they want exactly, #7458 is more about collecting tagged services).

@nicolas-grekas pov would be good!

**Comment by nicolas-grekas** [comment]
It's like event listener vs subscribers.
Personally, I'd advocate to promote subscribers over listeners, for events and for services.

**Comment by chalasr** [comment]
I agree, but creating locators by hand remain the way to go for collecting services for a given tag, that is especially useful for third party libs/bundles and the core. Opened https://github.com/symfony/symfony/issues/22649 for a related proposal.

**Comment by codedmonkey** [comment]
I've created a concept page in https://github.com/symfony/symfony-docs/pull/9223. It still needs some improvements though, especially properly describing `getSubscribedServices()`. It's probably also worth mentioning on the page that you're probably already using it through `AbstractController`. Any thoughts?
