### ISSUE TITLE
Give the opportunity to download PDF version of entire (single) bundle documentation.

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-docs#7763]
I would like to have a chance to print entire documentation as a one pdf file of a bundle f.e. http://symfony.com/doc/master/bundles/KnpMenuBundle/index.html with all related topics listed below of this site.

**Comment by javiereguiluz** [comment]
@sruj we appreciate your proposal to improve Symfony. Sadly, we already have lots of problems with the existing PDF docs, so we're not planning to add more PDF docs. We're sorry!
