### ISSUE TITLE
New Method: Kernel::getProjectDir()

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#7768]
See symfony/symfony#22315

**Comment by javiereguiluz** [comment]
Technically the change is minimal, but updating our docs to replace `kernel.root_dir` by `kernel.project_dir` would be too much. I propose this:

* Document the `Kernel::getProjectDir()` method in 3.3 but don't change the rest of the docs.
* For 4.0 docs, only use `kernel.project_dir` and never mention `kernel.root_dir`

**Comment by wouterj** [comment]
I don't agree with your proposal @javiereguiluz. I don't think something can be "too much". E.g. in 2.8, we changed all form types to use the FQCN. I think we should stick with our guide to not recommend usage of deprecated features.

So whenever we use `kernel.root_dir` and it's not a copy/paste example from the SE, I think we should use `kernel.project_dir`.
