### ISSUE TITLE
[Console] Allow to catch CommandNotFoundException

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7781]
See https://github.com/symfony/symfony/pull/22181

Review if we mention that you can't catch CommandNotFoundException. If we do, fix it.

**Comment by xabbuh** [comment]
Closing as we do not mention the `CommandNotFoundException` anywhere.

**Comment by javiereguiluz** [comment]
Have you also checked if we mention this limitation with words? Instead of using `CommandNotFoundException` explicitly maybe we say: *"you can catch all exceptions except when the command itself is not found"*.

**Comment by xabbuh** [comment]
@javiereguiluz Yes, at least if I did not miss any other place in the docs talking about exceptions.
