### ISSUE TITLE
Validation not enabled by default

### ISSUE THREAD

**Issue by Haikuch** [symfony/symfony-docs#7797]
In `validation.rst` is written:

> Configuration
> 
> The Symfony validator is enabled by default, but you must explicitly enable annotations if you're using the annotation method to specify your constraints:

But actually, in my fresh Symfony installations (with installer 1.5.9) the annotation **is** enabled by default like:

    validation:      { enable_annotations: true }

But I have to explicitly enable when I dont want to use annotations (so exactly the opposite to what is documented in validation.rst):

    validation:      { enabled: true }

**Comment by GuilhemN** [comment]
@xabbuh this can be closed :wink:
