### ISSUE TITLE
death URL components/serializer.html#component-serializer-encoders should be components/serializer.html#encoders

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-docs#7799]
`<component-serializer-encoders>` from https://github.com/symfony/symfony-docs/edit/3.2/serializer.rst refers to death URL `/current/components/serializer.html#component-serializer-encoders` should be: `/current/components/serializer.html#encoders`

**Comment by javiereguiluz** [comment]
Well spotted! However, I think the real problem is that the `id` is duplicated and I don't know exactly why:

![repeated-id](https://cloud.githubusercontent.com/assets/73419/25065486/3e34fd3c-2211-11e7-95a5-22d03e22348b.png)
