### ISSUE TITLE
Upgrading docs to Symfony 4.0

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7809]
This meta-issue lists all the big changes needed to upgrade the docs to Symfony 4.0:

* [x] Replace `kernel.root_dir` by `kernel.project_dir` everywhere. Never explain `kernel.root_dir` but maybe add a note mentioning that `project_dir` didn't exist before 4.x and people used `root_dir`.
* [x] The file extension of YAML files is now `.yaml` instead of `.yml`
* [x] ~In YAML files, null values are represented as `null` instead of `~`~ (change was reverted)
* [x] Application code is no longer stored in AppBundle or any other bundle. Bundles for own code are discouraged.
* [x] Lots of components/bundles (e.g. Symfony Console or MonologBundle) are not installed by default. We should add notes telling users to do: `composer req console`, etc.
* [x] We need to decide what to do with Symfony Flex aliases. For example, which command should we use to install the Symfony Console package? `composer req cli`, `composer req console`, `composer require console`, `composer require symfony/console`, etc.
* [x] Most config options are disabled by default. For example, the `session` service is not available by default because `session` config is commented in `framework.yaml`
* [x] See #8538 - make sure we mention all of the debugging commands somewhere
* [x] Commands are now always services, being in a `Command/` directory is not important
* [x] remove references to symfony/framework-standard-edition
* [x] `web/` to `public/` (also see https://github.com/symfony/symfony-docs/pull/8693#issuecomment-345435740)
* [x] `_controller` -> `controller`

-----

Remove deprecated features:

 * removed autowiring services based on the types they implement
 * removed the `DefinitionDecorator` class, replaced by `ChildDefinition`
 * removed the `AutowireServiceResource` class and related `AutowirePass::createResourceForClass()` method
 * removed `LoggingFormatter`, `Compiler::getLoggingFormatter()` and `addLogMessage()` class and methods, use the `ContainerBuilder::log()` method instead
 * removed `FactoryReturnTypePass`
 * removed `ContainerBuilder::addClassResource()`, use the `addObjectResource()` or the `getReflectionClass()` method instead.
 * removed support for top-level anonymous services
 * removed silent behavior for unused attributes and elements
 * Removed the "framework.validation.cache" configuration option. Configure the "cache.validator" service under "framework.cache.pools" instead.
* Support for stacked errors in the `ErrorHandler` is deprecated and will be removed in Symfony 4.0.

**Comment by wouterj** [comment]
Articles that have to be completely checked:

 * [ ] `best_pratices/*`
 * [ ] `bundles/remove`
 * [ ] `bundles`
 * [ ] `configuration`
 * [ ] `configuration/*`

**Comment by javiereguiluz** [comment]
Closing because this is a too broad issue. We're already taking care of all these in multiple separate pull requests.

**Comment by weaverryan** [comment]
@javiereguiluz I'm going to re-open this. This IS indeed broad. But I'd like to either check all the boxes in the description or create separate issues. For example, we have NOT removed all references to `AppBundle` yet on 4.0. We're still working on that :)

**Comment by javiereguiluz** [comment]
We finally checked all boxes of this meta issue ... so closing it as fixed.
