### ISSUE TITLE
Little typo in PHPUnit Bridge component page

### ISSUE THREAD

**Issue by medinae** [symfony/symfony-docs#7811]
> You used the Symfony Stopwatch Component to calculate the duration time of your process, here 10 seconds. However, **depending on the load of the server your the processes running on your local machine**, the $duration could for example be 10.000023s instead of 10s.

Would anyone have an idea to reformulate the sentence ?

👍

**Comment by javiereguiluz** [comment]
"your the processes" should be "or the processes"

**Comment by medinae** [comment]
Thanks. I'll create a PR. Which branch should i target ?

**Comment by javiereguiluz** [comment]
Thanks for spotting this error and for fixing it! The branch should be 2.8, because is the oldest supported branch that contains the bug. Thanks!

**Comment by medinae** [comment]
#7812

**Comment by javiereguiluz** [comment]
Closing it as fixed because the related PR #7812 was merged. Thanks!
