### ISSUE TITLE
Heroku deployment guide lacks instructions for configuring a database

### ISSUE THREAD

**Issue by yhoiseth** [symfony/symfony-docs#7814]
I recently followed the instructions on [Deploying to Heroku Cloud](http://symfony.com/doc/current/deployment/heroku.html) to deploy a MySQL-driven app to Heroku.

Once deployed, the app didn't work as expected because I didn't configure a database. I wrongly assumed that this was done automatically because the instructions didn't mention anything about a database.

I managed to make it work by following [this guide](https://coderwall.com/p/qpitzq/deploing-symfony-project-using-mysql-to-heroku).

To improve the developer experience, I think the deployment instructions should contain an optional section on configuring a database.

As a plan B, they should at least mention that they don't cover database configuration.

Please let me know if you'd like such an expansion of the article covering Heroku deployment. If you do, I can make a pull request.

**Comment by yhoiseth** [comment]
I would also like to see instructions for forcing SSL. I used [this StackOverflow](http://stackoverflow.com/questions/26489519/how-to-redirect-to-https-with-htaccess-on-heroku-cedar-stack) answer to achieve that.

**Comment by HeahDude** [comment]
Would mentioning doctrine commands in http://symfony.com/doc/current/deployment/heroku.html#custom-compile-steps be enough?

**Comment by yhoiseth** [comment]
@HeahDude 

> Would mentioning doctrine commands in http://symfony.com/doc/current/deployment/heroku.html#custom-compile-steps be enough?

I don't think so. As described in the blog post I linked to, there's a lot more to it than doctrine commands.

But I may be misunderstanding what you mean by "mentioning doctrine commands". Why, exactly, do you think that would be enough?

**Comment by HeahDude** [comment]
I suggest that could be enough (I'm not a Heroic user), because the hook I linked could be where `doctrine:database:create --if-not-exist`, `doctrine:schema:update --force` or `doctrine:migrations:migrate` commands could live, I guess this would do the job.

I don't get why a db clearer add-on as mentioned in the blog article you linked is needed in the first place (when creating a project).

**Comment by yhoiseth** [comment]
> I don't get why a db clearer add-on as mentioned in the blog article you linked is needed in the first place (when creating a project).

MySQL isn't included as a core offering in Heroku, so you need an add-on in order to use it.

> I suggest that could be enough (I'm not a Heroku user), because the hook I linked could be where `doctrine:database:create --if-not-exists`, `doctrine:schema:update --force` or `doctrine:migrations:migrate` commands could live, I guess this would do the job.

Unfortunately, I don't think that's enough. For example, you need to get the database credentials from the environment variable `CLEARDB_DATABASE_URL`.

**Comment by javiereguiluz** [comment]
We must close this as "won't fix" because as part of our efforts to simplify things, in #8721 we've removed all deployment articles.
