### ISSUE TITLE
CSRF token validation in Controller is confusing

### ISSUE THREAD

**Issue by enumag** [symfony/symfony-docs#7817]
http://symfony.com/doc/current/controller/csrf_token_validation.html

In the example code the `$submittedToken` variable does not exist. I'd send a pull request but I don't know what the correct code should be here. I assume there are multiple ways - but there should be some example where to create the token, how to pass it to the action and how to get it these.

**Comment by xabbuh** [comment]
I would just add a placeholder comment (`// ...`) before the check. How you read the token from the request (for example, by getting some data from the form or by accessing the request's `$request` parameter bag) does not really matter.

**Comment by javiereguiluz** [comment]
Fixed by #8873.
