### ISSUE TITLE
[cache component] get all keys

### ISSUE THREAD

**Issue by Francesco-Rizzi** [symfony/symfony-docs#7841]
**Get all keys method**

http://symfony.com/blog/new-in-symfony-3-1-cache-component

It would be a very useful method, with the standard component I have not way to retrieve all keys store on redis (or whatever..) (I can only with a third-part library)...

maybe something like:
`$cache->getKeysByPattern('*')`;

I thinks it should be a base func. and I'm surprised that there is not.

**Comment by yashari01** [comment]
i agree
