### ISSUE TITLE
[DependencyInjection] No page to explain services definition attributes

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony-docs#7843]
I just noticed that a service definition can have **a lot** of options:

```
alias
abstract
arguments
autowire
autowiring_types
calls
class
configurator
decorates
decoration_inner_name
decoration_priority
deprecated
factory
file
lazy
parent
properties
public
shared
synthetic
tags
```

There are some pages in the documentation that explain how they work, but there is no page referencing all possible options, like we have for configuration references (for example with [FrameworkBundle configuration reference](https://symfony.com/doc/current/reference/configuration/framework.html)).

I think that we may need a _"centralized"_ page for all these options, this could be a very nice entry point to work with service definitions and have a better knowledge of how all options work.

What do you think?

**Comment by javiereguiluz** [comment]
Thanks for your proposal. However, I'm closing this as "won't fix" because we don't have enough resources to create and maintain this new reference. All attributes are already explained in the related articles.

**Comment by Pierstoval** [comment]
So you mean that if someone intends to work on this, it's okay?
