### ISSUE TITLE
Console command docs refer to obsolete ContainerAwareCommand class

### ISSUE THREAD

**Issue by joachim-n** [symfony/symfony-docs#7874]
The docs at http://symfony.com/doc/current/console.html have a section 'Getting Services from the Service Container'.

This says that to get access to services, a command should inherit from ContainerAwareCommand.

However, AFAICT, ContainerAwareCommand was removed prior to 3.x.

**Comment by xabbuh** [comment]
The [`ContainerAwareCommand` class](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/ContainerAwareCommand.php) from the FrameworkBundle is still a thing in Symfony 3. What was removed was the `ContainerAware` class. Thus, I am closing here, but please feel free to leave comments in case you still have any questions. It's always good to have people questioning what we have in the docs (we miss a lot of things :)).

**Comment by joachim-n** [comment]
Ah right. Problem is I couldn't find it in either console or dependency-injection components. 

Is there a way of getting this without the whole of the framework bundle? Looking at packagist, that requires things such as routing, http, config, cache -- none of which I need for a simple command-line application.

**Comment by xabbuh** [comment]
Not really, but you can create your own base command class that implements the `ContainerAwareInterface`.

**Comment by joachim-n** [comment]
I've done that, using the ContainerAwareTrait that's in 3.x to provide the method.

It doesn't seem to do anything -- $this->container is not set when when the command's execute() method is called.

Are there any docs that cover this?

**Comment by xabbuh** [comment]
Can you show the code that you have implemented?

**Comment by joachim-n** [comment]
I've pushed my work branch here: https://github.com/joachim-n/dorgflow/tree/sandbox-symfony-console

It's a command-line application that up till now was using just the symfony/dependency-injection component, but I think that using symfony/console will improve how input and output are handled -- simplify it, make it prettier, and allow me to add command line options more easily.

The majority of the code can be ignored for the current purposes. It's just the main script file, dorgflow, the Application class, and one test command SymfCommand that do anything on that branch.

It occurs to me now I think about it that the glaring fatal flaw is that the service container I build doesn't get passed to the console application in any way, but I've no idea how to do that.

**Comment by xabbuh** [comment]
Indeed, however this is a bit too much to answer it in the docs repo. I suggest you ask this again on StackOverflow or on IRC/Slack. Thank you for understanding. :)

**Comment by joachim-n** [comment]
Yeah, that's a lot of code, sorry. 

I've made a separate repository with it stripped down to just the main script, one service, and one console command: https://github.com/joachim-n/console-with-di

Does that help?

I do think that the docs need to be updated to say that the 'Getting Services from the Service Container' example requires FrameworkBundle. Beyond that, it would be nice to have an example of how to use console and dependency-injection together without needing FrameworkBundle.
