### ISSUE TITLE
API documentation for JsonResponse

### ISSUE THREAD

**Issue by twify93** [symfony/symfony-docs#7888]
I've just saw that the API documentation for JsonEncode is not valid, the constructor has other parameters
[JsonResponse::__construct](http://api.symfony.com/2.7/Symfony/Component/HttpFoundation/JsonResponse.html#method___construct)
Should be:
`public function __construct($data = null, $status = 200, $headers = array(), $json = false)`
I haven't checked anything else,  there might be other problems as well.

**Comment by xabbuh** [comment]
Well, you are comparing the API doc for Symfony 2.7 with a more recent version of the code. The `$json` argument was added in Symfony 3.1.

**Comment by twify93** [comment]
Ou.. Crap.. Yes, sorry, my bad!
