### ISSUE TITLE
Update Doctrine `AppBundle:Post` syntax to `Post::class`

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#7892]
I believe this is now the preferred syntax and writing it is "easier" a bit more universally (PhpStorm with the Symfony plugin will autocomplete both, but a normal IDE will only autocomplete the second).

This should be updated everywhere in the 3.1 branch (first, currently-maintained version with a high even PHP version to support this).

**Comment by xabbuh** [comment]
A quick note: Symfony 3.1 is not maintained anymore. ;) And I would by the way even make the change in the `2.7` branch as we already switched to the usage of FQCNs with the `class` constant in other places as well (to refer to form types for example).

**Comment by ricknox** [comment]
This seems to be fixed in #7907.
