### ISSUE TITLE
Improving the event subscribers examples

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7908]
With Symfony Flex and Symfony 4, Symfony is moving towards using only subscribers instead of listeners. However, I don't like how most of subscribers are displayed in docs. Example:

```php
class SearchIndexerSubscriber implements EventSubscriberInterface
{
    // the code...

    public static function getSubscribedEvents()
    {
        return array(
            KernelEvents::CONTROLLER => 'onKernelController',
            KernelEvents::RESPONSE => 'onKernelResponse',
        );
    }
}
```

In my opinion, there are two issues:

1. `getSubscribedEvents()` should always be the first method of the class, to clearly see the events you are listening to. I don't know why Symfony insists on putting it at the end of the class.
2. `onKernelController()` and `onKernelResponse()` are the worst method names possible because they mean nothing. I'd like to use meaningful names.

Proposal example:

```php
class SearchIndexerSubscriber implements EventSubscriber
{
    public static function getSubscribedEvents()
    {
        return array(
            KernelEvents::CONTROLLER => 'validateApiToken',
            KernelEvents::RESPONSE => 'checkResponseHeaders',
        );
    }

    // the code...
}
```

**Comment by xabbuh** [comment]
:+1: I agree with both of your suggestions.

**Comment by HeahDude** [comment]
I agree with the second suggestion, method should always have explicit name.
But regarding the first, this is just about following common CS which places static methods after non static ones.

**Comment by javiereguiluz** [comment]
I'm closing this because it's not really a bug or a missing doc. This is just to improve docs a little ... but we don't have resources for this. Let's focus on important things. Thanks!
