### ISSUE TITLE
Update page How to Use PHP's built-in Web Server for Symfony 3.3

### ISSUE THREAD

**Issue by jrysig** [symfony/symfony-docs#7919]
http://symfony.com/doc/master/setup/built_in_web_server.html

Command ```php bin/console server:start --env=test``` doesn't work with Symfony 3.3.0-RC1, following error is displayed:
```
[Symfony\Component\Console\Exception\CommandNotFoundException] 
There are no commands defined in the "server" namespace.
```
The reason is a new version of AppKernel.php in Symfony Standard Edition - WebServerBundle is included only in 'dev' environment.

**Comment by JarJak** [comment]
Also, this page has to be updated:
https://symfony.com/doc/current/setup.html
This is urgent in my opinion because newbies entering this page (one of the first in docs) would get bad feeling when command they copy-paste is not working.

**Comment by xabbuh** [comment]
@JarJak But on that page we only execute the `server:run` command in the `dev` environment.

**Comment by JarJak** [comment]
But server:run command is not available in symfony standard, you need
WebServerBundle for it. This fact needs to be at least mentioned there.

20.06.2017 11:39 AM "Christian Flothmann" <notifications@github.com>
napisał(a):

**Comment by JarJak** [comment]
Nevermind, my bad
