### ISSUE TITLE
[DI] Explain that "class FQCN as service IDs" doesn't always work

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7935]
As explained in https://github.com/symfony/symfony/issues/22851, you can't always use FQCN as service IDs. Specifically, classes that don't use namespaces won't work (e.g. anything related to Twig).

Although the error message is clear, let's make sure that we mention this limitation somewhere.

**Comment by stof** [comment]
Technically, you can still use the FQCN as service id (the id is just a string, and FQCNs are strings). But you will still need to configure the class explicitly for the service. What won't work for classes in the global namespace is the auto-configuration of the class based on the id.

**Comment by weaverryan** [comment]
👍 I didn't realize this limitation - but it makes sense!
