### ISSUE TITLE
Testing suggestion to use PHPUnit phar should be changed from 3.3 on

### ISSUE THREAD

**Issue by YetiCGN** [symfony/symfony-docs#7936]
[The testing page](https://github.com/symfony/symfony-docs/blob/master/testing.rst) mentions "It's recommended to use the latest stable PHPUnit version, installed as PHAR."

However, this causes issues with the new 3.3 Yaml component and PHPUnit's bundled version in the PHAR, effectively failing every test and very weird to debug.

The current recommendation to work around this issue is to ["do a Composer + require-dev + phpunit/phpunit and execute your tests via ./vendor/bin/phpunit"](https://github.com/symfony/symfony/issues/19532#issuecomment-266307266). I think this should somehow be mentioned here to prevent others from searching in vain.

**Comment by xabbuh** [comment]
I think we should explain how to use the `simple-phpunit` script from the PhpUnitBridge instead.

**Comment by YetiCGN** [comment]
Or that.

**Comment by HeahDude** [comment]
Agreed with @xabbuh.

**Comment by javiereguiluz** [comment]
Fixed by #9213.
