### ISSUE TITLE
Better explain MIME type detection issues and solutions

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7953]
From time to time we receive in the code repository issues about this feature. The things to explain (or improve the explanation) are:

* How this MIME type detection works: how does Symfony selects the guesser (file extension based, binary file detection, etc.), how to configure/change that behavior.
* What can I do when the guess has issues; for example for Microsoft Office file types: https://github.com/symfony/symfony/issues/22702
* How can I define my own MIME types; to avoid issues when FileinfoMimeTypeGuesser fails: https://github.com/symfony/symfony/issues/22888

**Comment by xelaris** [comment]
Some of these points are part of my comment in https://github.com/symfony/symfony/issues/22702#issuecomment-304532913. Maybe it can serve as a base for an addition to the docs. @javiereguiluz Do you have an idea where in the doc this could be added? I would open a PR for it then.

**Comment by HeahDude** [comment]
Closing as "duplicate" of #2542 which is actrionnable, thanks!
