### ISSUE TITLE
[symfony.com/doc/../contributing/../standards] Use underscores for option names and parameter name

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-docs#7956]
http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions

> Use underscores for option names and parameter names;

```
//line 95: 
private function reverseBoolean($value = null, $theSwitch = false)
```

So what is the correct rule?

**Comment by javiereguiluz** [comment]
@sruj I'm sorry for the confusion. The underscores are for the config options and params, not for the PHP arguments. In #7957 I'm trying to fix this with a minor reword.

**Comment by javiereguiluz** [comment]
I'm reopening the issue because we close them automatically when the related pull request is merged. Thanks!
