### ISSUE TITLE
Coding standards rule about "Declare public methods first, then protected ones and finally private ones"

### ISSUE THREAD

**Issue by Kwadz** [symfony/symfony-docs#7967]
Keeping dependent methods together improve readability. [This answer ](https://stackoverflow.com/a/1760877/1941316) confirm this point. However the current rule `"Declare public methods first, then protected ones and finally private ones"` does not allow it.

Could we improve the current coding standards to also accept keeping dependent methods together?

**Comment by javiereguiluz** [comment]
@Kwadz thanks for your proposal to improve Symfony. Sadly, this idea didn't gain enough traction ... so we must close it as "won't fix".

Even if what you said is true ... the current standard is also correct for an important reason: public methods are what you can use (and protected sometimes) and you can't use private methods from the outside. So, wen opening a class, you see first what you can use about that class.

This time the proposal didn't make it. but we hope to receive more proposals from you soon. Thanks!
