### ISSUE TITLE
Classnames as service id seems to be in conflict with the Service Naming Conventions

### ISSUE THREAD

**Issue by MetalArend** [symfony/symfony-docs#7968]
The Symfony [Coding Standards](http://symfony.com/doc/current/contributing/code/standards.html#service-naming-conventions) define for the moment that 

> Use lowercase letters for service and parameter names (except when referring to environment variables with the %env(VARIABLE_NAME)% syntax);

Should this be updated for Symfony 3.3, as using classnames will always introduce having uppercase letters when referencing to a service?

**Comment by weaverryan** [comment]
That's true - but that document is meant for contributing to the core code... which should still use the old convention (and then add class/interface aliases to allow autowiring).

**Comment by weaverryan** [comment]
We should add a small spot about adding class aliases for public services.
