### ISSUE TITLE
Documentation for LessThan has some minor errors

### ISSUE THREAD

**Issue by tzfrs** [symfony/symfony-docs#8012]
I found minor errors on the documentation page of the LessThan constraint. http://symfony.com/doc/current/reference/constraints/LessThan.html

Important here are the first two bullet points of the "Basic Usage" chapter, which currently look like this

![image](https://user-images.githubusercontent.com/3509557/26963305-2d3c13fc-4cec-11e7-8791-bc190c86bc8a.png)

* The first bullet point contains information which should be only present in the `LessThanOrEquals` Constraint
* The second bullet point has the number 80, which is not code highlighted, because of a missing space.

I created a PR for this

https://github.com/symfony/symfony-docs/pull/8011

**Comment by tzfrs** [comment]
I did some "research" and find out that this problem occurs on the documentation for the versions:

* 4.0 / master
* 3.4
* 3.3 / current
* 3.2
* 2.8
* 2.7

so basically in every version.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #8011. @tzfrs thanks for reporting this issue and for fixing it!
