### ISSUE TITLE
[Security] Add docs about success handlers for login and logout

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony-docs#802]
Johannes says it's not recommended to use security.interactive_login for redirections and such because they should not apply to all firewalls, and not all auth types. In any case, if you ignore that and do it anyway, there is no event for logout, so you get stuck eventually if you try to cover that as well.

**Comment by WouterJ** [comment]
Closing in favor of #4258, which contains a lot more details on how to fix it
