### ISSUE TITLE
margin is missing

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-docs#8024]
URL: http://symfony.com/doc/current/setup.html

the `edit this page` button is hitting the next info box:
![screenshot 2017-06-12 10 14 43](https://user-images.githubusercontent.com/995707/27024741-1e1c7bdc-4f58-11e7-96ce-6364b4a2a93f.png)

**Comment by javiereguiluz** [comment]
Thanks for reporting. Sadly this issue has been with us forever 😢   It's because the right aligned buttons are floated to the right, and the rest of elements adapt to floats. The only solution I came up was to add a white background to the right buttons. That will hide part of the box below it and it will probably look better. Anyway, I tested it and I didn't like it. I'll test it again.

**Comment by OskarStark** [comment]
What about a transparent background/border?

**Comment by javiereguiluz** [comment]
I'm proposing this fix based on adding a white background + white box-shadow on the version selector:

### Smartphones

| Before | After
| --- |---
| ![smarthpone-before](https://user-images.githubusercontent.com/73419/27263288-43130646-5466-11e7-8cf9-fd94f2304b7b.png) ![smartphone-before-reveal](https://user-images.githubusercontent.com/73419/27263289-447790f6-5466-11e7-80a6-a2ce2bdd428b.png) | ![smartphone-after](https://user-images.githubusercontent.com/73419/27263290-461c843e-5466-11e7-8ee6-6fff59802365.png) ![smartphone-after-reveal](https://user-images.githubusercontent.com/73419/27263291-474bf9fc-5466-11e7-883c-fc211fdb6e14.png)

### Desktops

| Before | After
| --- | ---
|![desktop-before](https://user-images.githubusercontent.com/73419/27263297-714a2fb2-5466-11e7-878f-5f51ae1661c0.png) ![desktop-before-reveal](https://user-images.githubusercontent.com/73419/27263298-72ac7630-5466-11e7-86d0-5f386e153d64.png) | ![desktop-after](https://user-images.githubusercontent.com/73419/27263300-74903af4-5466-11e7-904b-c494898c8c2f.png) ![desktop-after-reveal](https://user-images.githubusercontent.com/73419/27263301-75994b0c-5466-11e7-9788-e5d4f312ac6f.png)

**Comment by xabbuh** [comment]
Looks good to me. I especially like the move of the version switcher for the mobile view. 👍

**Comment by javiereguiluz** [comment]
This has been deployed on production, so you can test it for real and I can close this as "fixed". Thanks!
