### ISSUE TITLE
Groups option missing in the UniqueEntity constraint documentation

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#8036]
Moved from symfony/symfony#23158:

I noticed that the UniqueEntity constraint (form validation) accepts the "groups" option like other common validation constraints. However, this option does not appear in the documentation: https://symfony.com/doc/3.4/reference/constraints/UniqueEntity.html
Very minor thing but I just wanted to let the community know.

**Comment by xabbuh** [comment]
Actually, it seems we don't include the `groups` option in any of the constraints' description, right?

**Comment by rtarnaud** [comment]
I think you are right. I checked some of the usual constraints and no sign of a "groups" option.

**Comment by pbowyer** [comment]
Is this not "Missing Documentation"?

I ran into this today, not realising that I could create constraints with 'groups' via code (rather than annotations). I figured this out because I tried it to see what would happen.

The following works, even though there isn't a `groups` option present in the docs for any validation constraint:
```
      $builder
            ->add('line1', TextType::class, [
                'constraints' => [
                    new NotBlank(['groups' => ['Address']]),
                ]
            ])
```

**Comment by xabbuh** [comment]
> Is this not "Missing Documentation"?

Yes, but nearly every issue in this repo is about missing documentation bits. That's why we recently decided to remove this label.

**Comment by javiereguiluz** [comment]
Closing as fixed. The "groups" option is now explained in https://symfony.com/doc/3.4/reference/constraints/UniqueEntity.html

**Comment by pbowyer** [comment]
Thanks @javiereguiluz!
