### ISSUE TITLE
Frontend - Encore, postcss and browserslist

### ISSUE THREAD

**Issue by fvsch** [symfony/symfony-docs#8038]
Hi. To answer a common use case, I think this page should mention how to define a `"browserslist"` config in `package.json` for Autoprefixer:
http://symfony.com/doc/current/frontend/encore/postcss.html

Maybe something like a note stating:

> Autoprefixer recommends defining your target browsers in `package.json`:
> 
> ```json
> {
>   "browserslist": [ "last 2 versions", "ios >= 8" ]
> }
> ```

**Comment by weaverryan** [comment]
👍 this appears to be the best practice: https://github.com/postcss/autoprefixer#no-prefixes-in-production

There's one other place where a browser list is used:  `babel-preset-env`. But, it looks like reading this prefix is not yet supported: https://github.com/babel/babel-preset-env/pull/161. We should keep an eye on that.

But yes, let's definitely add a spot about this!

**Comment by fvsch** [comment]
There are a number of tools using browserslist too: eslint, stylelint, and other tools have it in the works. https://css-tricks.com/browserlist-good-idea/

**Comment by weaverryan** [comment]
PR opened! #8054
