### ISSUE TITLE
Deprecate (or remove) "Using Bower with Symfony"

### ISSUE THREAD

**Issue by simshaun** [symfony/symfony-docs#8050]
https://symfony.com/doc/current/frontend/bower.html
(linked to from the bottom of https://symfony.com/doc/master/frontend.html)

This follows up #8049 regarding confusion about Symfony's best practices regarding frontend.

With https://bower.io now recommending that new projects use Yarn & Webpack instead of Bower, I feel like the Bower page in the Symfony docs needs to be removed.

It's mostly a *how to use Bower* article anyway. The only Symfony-specific part is referencing your assets with `{{ asset(...) }}`.

**Comment by xabbuh** [comment]
This should be fixed once #8034 is merged.
