### ISSUE TITLE
[Encore] Document exposing global variables

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8071]
In many cases, you may need to do this:

```js
const $ = require('jquery');
window.$ = window.jQuery = $;
```

so that you can use `$`  or `jQuery` outside of a webpack file (e.g. because you have some JS in a template). We need to document this in the "legacy" section.

**Comment by stof** [comment]
I would recommend this instead:

```js
const $ = require('jquery');
global.$ = global.jQuery = $;
```

This would let us add `window.jQuery` again in the autoProvideJquery list, to support bootstrap by default
