### ISSUE TITLE
[Encore] Show example of executable paths for Windows

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8073]
See https://github.com/symfony/webpack-encore/issues/13#issuecomment-309434371

Basically, we should mention what it looks like to run the path in Windows.

**Comment by weaverryan** [comment]
Actually, I'm going to close this until we see if people have issues.

**Comment by WyrdNexus** [comment]
definitely having issues.

Can be tricky to run node commands on windows powershell, but this in `packages.json` makes life easy:
```json
"scripts": {
    "assets:watch": "encore dev --watch",
    "assets:dev": "encore dev",
    "assets:build": "encore production"
  }
```
Then commands are as simple as:
`> yarn run assets:dev`

While this is a yarn/os/node issue, and understanding those components are sufficient to get around running commands, I was very close to going down a rabbit-hole to solve this.  Personally, I'm new enough to yarn, that I never would have guessed at such a clean and simple solution.  (Please add some side-note about this for windows, as finding this issue saved me several hours of going in the wrong direction).
