### ISSUE TITLE
[Encore] Update docs related to HMR

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8074]
Thanks to https://github.com/symfony/webpack-encore/pull/8, Encore supports HMR.

But I've put this on hold, because we don't actually have any loaders yet that support HMR, so turning it on doesn't do anything.

**Comment by javiereguiluz** [comment]
Closing as fixed because HMR is explained here: https://symfony.com/doc/current/frontend/encore/dev-server.html
