### ISSUE TITLE
Symfony\Component\Workflow namespace

### ISSUE THREAD

**Issue by Kwadz** [symfony/symfony-docs#8093]
[The documentation](https://symfony.com/doc/current/components/workflow.html) states we need to install the Workflow component (for example with composer) while it is already available in Symfony v3.2.

**Comment by xabbuh** [comment]
All the `components/*` pages describe how to use a component standalone (i.e. outside the full stack framework). Maybe we could add a note to all these installation instructions that this is not necessary when using `symfony/symfony`.

**Comment by javiereguiluz** [comment]
This will be fixed as part of #9840. I'm closing it as a duplicate of #9357, which asks the same but in a generic way for all components. Thanks!
