### ISSUE TITLE
[Console] Add documentation about the console.command "command" attribute (lazy commands)

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#8147]

**Comment by xabbuh** [comment]
see symfony/symfony#22734 for more information

**Comment by chalasr** [comment]
I'm going to take this in the next week. I think we need a small section in the "Command as services" chapter and a whole new section in the Console component showing how to get commands lazily loaded using the console standalone.

**Comment by xabbuh** [comment]
symfony/symfony#23510 was also merged

**Comment by chalasr** [comment]
https://github.com/symfony/symfony/pull/23805 was merged too

**Comment by chalasr** [comment]
See #8502
