### ISSUE TITLE
[Validator] Remove support of boolean value for the checkDNS option

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8171]
See https://github.com/symfony/symfony/pull/23391.

The way `checkDNS` works has changed. I put this issue "on hold" because there's a proposal to revert this change. See https://github.com/symfony/symfony/issues/23538

**Comment by eXtreme** [comment]
I'm bumping this because 4.0 is out and UrlValidator seems not to accept "true" for checkDNS but docs still say it does.

see: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Constraints/UrlValidator.php#L76-L91

**Comment by javiereguiluz** [comment]
Fixed by #9131.

**Comment by fmonts** [comment]
Introducing a BC break in a minor updated is a very bad practice. Also, it didn't issue any deprecation warning. 
You should have waited for 4.1 and issued a warning instead
