### ISSUE TITLE
[Security] remove support for defining voters that don't implement VoterInterface

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8178]
Support for defining voters that don't implement the `VoterInterface` has been removed.

See https://github.com/symfony/symfony/pull/23324.

**Comment by xabbuh** [comment]
This shouldn't affect the docs I guess. The referenced PR only removed code that was already deprecated and I think we already adapted the docs accordingly.

**Comment by javiereguiluz** [comment]
You are right. I've just checked all the voter examples and they always implement `Symfony\Component\Security\Core\Authorization\Voter\VoterInterface` or extend from `Symfony\Component\Security\Core\Authorization\Voter\Voter`.

Closing as fixed.
