### ISSUE TITLE
[Yaml] remove deprecated unspecific tag behavior

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8179]
The behavior of the non-specific tag `!` is changed and now forces non-evaluating your values.

See https://github.com/symfony/symfony/pull/23286.

**Comment by xabbuh** [comment]
I don't think we mention the non-specific tag anywhere and IMO we should not document it.

**Comment by javiereguiluz** [comment]
Closing as not needed to be documented. Thanks!
