### ISSUE TITLE
[Form] Registering form types

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#8183]
https://symfony.com/doc/current/form/create_custom_field_type.html

the first paragraph mentions `and finally, how you can register it for use in your application` i don't see anything about registering it for use in my application on that page.

usecase:

I'm trying to figure out how to deal with form types in silex which still mentions `You can register form types by extending form.types` https://silex.symfony.com/doc/2.0/providers/form.html

i guess this is then outdated as well?

I like to keep things inline and not create classes right away (since i'm doing small and quick projects). If i HAVE TO create a class can it be an anonymous one?

**Comment by xabbuh** [comment]
Hm indeed, this was true before the introduction of the `autoconfigure` DI option in Symfony 3.3 where you had to manually tag a service for your class with `form.type`. We should reword the first paragraph.

For the Silex related issue you should ask on the [Silex repo](https://github.com/silexphp/Silex) as they maintain their own documentation.
