### ISSUE TITLE
Customize EmailType when used in a Collection 

### ISSUE THREAD

**Issue by partulaj** [symfony/symfony-docs#8229]
Hello,

I  would like to customize the `EmailType` when it's used in a `CollectionType` (not for a specific form but for **ALL** my form), I take a look to the doc and the different topic about customizing an entry of a `CollectionType` but didn't find something like that.

I try to customize it but I don't find the correct name for the block, I tried
_collection_entry_row
_collection_email_entry_row

Is it the correct way to do ?
If it is what should be the correct name of the block?

**Comment by HeahDude** [comment]
Hello @partulaj, the feature you need is not implemented in Symfony core. There is no generic block for collection entries, they can only be overridden per form with `myformname_mycollectionfield_entry_*`.

Note that the convention of block name starting with underscore is to use with form names, not block prefix defined in types.

I don't see any easy way to solve such case for now. What you could do is make a type extension for the CollectionType and use the `finishView` method to do something like:
```php
foreach ($form as $field) {
    $view->vars['entry_type'] = $field->getConfig()->getType()->getInnerType()->getBlockPrefix();
    break;
}
```
And use the `entry_type` value while overriding the `collection_row`.

**Comment by partulaj** [comment]
Thank you, but I think that the easiest way to do it will be to create a `FormType` with a form theme and  replace the `EmailType` by this `FormType`
