### ISSUE TITLE
Add a note to explicit service overriding

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#8242]
Ref https://github.com/symfony/symfony/issues/23308.

Overriding a definition in another config file looses the original `_default` attributes.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix". This issue was probably caused because autowiring was very new at that time. But we've improved our articles since and we repeat *"[...] for any service defined in this file"* once and again when talking about the `_defaults` option.
