### ISSUE TITLE
Clarify "format" option in DateType and DateTimeType

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#8248]
Ref https://github.com/symfony/symfony/issues/23602 and https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/Form/Extension/Core/Type/DateTimeType.php#L36-L57.

We should add a note [here](http://symfony.com/doc/current/reference/forms/types/datetime.html#format) and [here](http://symfony.com/doc/current/reference/forms/types/date.html#format).

**Comment by javiereguiluz** [comment]
I can't find the exact PR, but this was fixed recently. The date articles now include a link to the ICU docs that explain the format to use: http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax

**Comment by xabbuh** [comment]
hm, looks like a really old change: 9016514ad41a516451d9e99e5109a103885c8458
