### ISSUE TITLE
Remove JSRoutingBundle if it is not maintained(?)

### ISSUE THREAD

**Issue by tobias-93** [symfony/symfony-docs#8250]
Hi,

I hate to wreak havoc here, but for the past year I've been waiting for a pull request to be merged in the `FosJSRoutingBundle` (https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/254).
Without the code in this PR, the bundle is not usable for us in Symfony >2.8, meaning that we cannot upgrade to Symfony 3.
However, it seems that no attention is given to this PR, and we're unable to contact any member of the repository.
The bundle is listed in the documentation (https://symfony.com/doc/bundles/, https://symfony.com/doc/master/bundles/FOSJsRoutingBundle/index.html and mentioned on https://github.com/symfony/symfony-docs/blob/master/routing/generate_url_javascript.rst), but I'm seriously worried about the status of this bundle.
I don't think it is fair to list this bundle in the documentation if no effort is made to keep it compatible with the latest version of Symfony.

Do you agree with me that the reference to this bundle should not be part of the official Symfony documentation as long as it is not maintained?

**Comment by GuilhemN** [comment]
If the bundle is no longer maintained then we should ask if people are willing to maintain it.

@stof @willdurand do you still have time to maintain JSRoutingBundle?

**Comment by willdurand** [comment]
So I guess this should be closed now that the bundle has been updated :)

**Comment by tobias-93** [comment]
The question here asked by @GuilhemN still stands. @willdurand Do you still have time to maintain the bundle or do you foresee problems in the future?

**Comment by willdurand** [comment]
You look like a good fit for the maintainer position :)

I haven't done PHP for years now, but this bundle used to work for a long time now. Sure it needed your changes to make it compatible with recent Symfony versions, but it is feature-complete and does not need a lot of maintenance effort. I can give a hand time to time but it would be better to have users as maintainers (like you, again 😉)

**Comment by tobias-93** [comment]
@willdurand you flatter me 😳 
I agree that it's best to have users as maintainers, so they can also test fixes in their own projects.
Although I'm not sure I'm proficient with all the parts of the bundle, I'd like to give it a shot 😄

**Comment by HeahDude** [comment]
So it looks like the bundle is still maintained :). Let's close here then, feel free to reopen to further discuss it if needed.
