### ISSUE TITLE
Doctrine documentation about caches lacks detailed explanation

### ISSUE THREAD

**Issue by NicoHaase** [symfony/symfony-docs#8251]
I am just experimenting with the capabilities of the doctrine cache. According to https://symfony.com/doc/current/reference/configuration/doctrine.html, there should be a caching driver option of "service". If I set the option in my yml, the container cannot be built.

```
doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          driver:   pdo_mysql
          host:     mysql.local
          port:     ~
          dbname:   db
          user:     db
          password: db
          charset:  UTF8
    orm:
      default_entity_manager: default
      auto_generate_proxy_classes: %kernel.debug%
      entity_managers:
        default:
          connection: default
          metadata_cache_driver: service
```

```
[Tue Aug 01 16:33:46 2017] [error] [client 10.13.110.75] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException' with message 'The service "doctrine.orm.default_entity_manager" has a dependency on a non-existent service "".' in /home/niha/projects/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:58
[Tue Aug 01 16:33:46 2017] [error] [client 10.13.110.75] Stack trace:
[Tue Aug 01 16:33:46 2017] [error] [client 10.13.110.75] #0 /home/niha/projects/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(51): Symfony\\Component\\DependencyInjection\\Compiler\\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
[Tue Aug 01 16:33:46 2017] [error] [client 10.13.110.75] #1 /home/niha/projects/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(51): Symfony\\Component\\DependencyInjection\\Compiler\\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
[Tue Aug 01 16:33:46 2017] [error] [client 10.13.110.75] #2 /home/niha/projects/project/vendor/symfony/ in /home/niha/projects/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 58
```

In Symfony 2.8, using doctrine/cache v1.6.2, I can find many implementations of `\Doctrine\Common\Cache\CacheProvider` (including classes like `CouchbaseCache`, `FilesystemCache`, `MongoDBCache`, `PhpFileCache`,....) which are not document, but not a `ServiceCache` or something like that which is documented.

**Comment by xabbuh** [comment]
I think that explanation is misleading. In fact, what you can pass here is the id of a service that provides such a cache implementation. We could make it more clear by not enclosing "service" with backticks and explicitly talk about passing a service id here.

**Comment by NicoHaase** [comment]
This is what I found yesterday, after lots of tries and long after having reported this issue here, too. Even if I learned the hard way how to use these caches, it would be kind if someone with more knowledge about them could provide docs

**Comment by javiereguiluz** [comment]
@NicoHaase thanks for noticing us about this. I'm trying to improve it in #8254. Please let me know if it's better now. Thanks!

**Comment by NicoHaase** [comment]
It's already better, but I think one more example about such a service would be really great. In my project, I added the following lines to the service.yml to write metadata to the disk:

```
  project.doctrine_filesystem_cache:
    parent: doctrine_cache.abstract.file_system
    arguments: ['%kernel.cache_dir%']
```

Probably, also a reference to vendor/doctrine/doctrine-cache-bundle/Resources/config/services.xml could help, as this contains the list of available services which need to be extended like in my example
