### ISSUE TITLE
Minor typo in Service Container page

### ISSUE THREAD

**Issue by kastaneda** [symfony/symfony-docs#8265]
PHP code example in [chapter 'Explicitly Configuring Services'](http://symfony.com/doc/current/service_container.html#explicitly-configuring-services-and-arguments) should have method calls `setAutowired()` instead of non-existed `setAutowire()`.

**Comment by xabbuh** [comment]
@kastaneda good catch, would you like to submit a pull request?

**Comment by kastaneda** [comment]
Yes, surely, here it is: https://github.com/symfony/symfony-docs/pull/8266
