### ISSUE TITLE
[DI] Localbinding (bind) support

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#8276]
see symfony/symfony#22187

**Comment by weaverryan** [comment]
I bootstrapped the section (poorly) in #8559. We just need to fill in that section.

**Comment by javiereguiluz** [comment]
Closing as fixed because this was bootstraped in #8559 but completed later, as you can see in https://symfony.com/doc/current/service_container.html#binding-arguments-by-name-or-type.
