### ISSUE TITLE
Better explain projects installation

### ISSUE THREAD

**Issue by HeahDude** [symfony/symfony-docs#8289]
When reading http://symfony.com/doc/current/setup.html#creating-symfony-applications, if instructions are followed sequentially it may happen that dev install new projects with `symfony new xxx` in a folder that cannot be used with web servers (i.e `c:\projects\my-project`).

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue ... but sadly I don't understand it. Besides, keep in mind that all this is greatly simplified in "master" branch, in preparation for Symfony 4.0. See https://symfony.com/doc/master/setup.html#creating-symfony-applications

**Comment by javiereguiluz** [comment]
Let's close this old issue because we don't have more information and it's probably no longer relevant in Symfony 4 and newer. Thanks!
