### ISSUE TITLE
deprecated choices_as_values in dynamic forms

### ISSUE THREAD

**Issue by tacman** [symfony/symfony-docs#8293]
The code explaining dynamic form building uses choices_as_values as an option:

https://symfony.com/doc/current/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms

                   $form->add('position', EntityType::class, array(
                        'class' => 'AppBundle:Position',
                        'placeholder' => '',
                        'choices' => $positions,
                        'choices_as_values' => true,
                    ));
                }

If that's not used anymore, it can be removed.  If it is, can you update the documentation to reflect how to generate dynamic forms without using choices_as_values?

**Comment by xabbuh** [comment]
Thanks for reporting this @tacman. This option should indeed be removed in the `3.3` branch. Would you like to open a pull request?
