### ISSUE TITLE
[2.8] better document how to work behind AWS ELB

### ISSUE THREAD

**Issue by bruno-ds** [symfony/symfony-docs#8297]
Hello,
while the current (3.3) doc. explain how to deal with AWS ELB : 
http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html

the LTS (2.8) doc. does not explain this (and an internet search will provide contradictory solutions).

I think that it could be great to explain better how to deal wit the very common case of being behind an ELB.
reading from the 3.3 source code's [binary mask in class' constants](https://github.com/symfony/http-foundation/blob/master/Request.php), it seem that ELB provide standard header but no `X-Forwarded-Host` and `X-Forwarded`.

so (if I'm not wrong), for the 2.8, the config should be : 
```
    Request::setTrustedHeaderName(Request::HEADER_CLIENT_HOST, '');// AWS ELB doesn't send X-Forwarded-Host
    Request::setTrustedHeaderName(Request::HEADER_FORWARDED, '');// AWS ELB doesn't use RFC 7239
    Request::setTrustedProxies(
    // trust *all* requests
        array('127.0.0.1', $request->server->get('REMOTE_ADDR'))
    );
```

**Comment by javiereguiluz** [comment]
I don't have enough experience about this, but the fact that the 2.8 docs don't mention this may be because those binary mask constants are not available in 2.8. See:

* 2.8: https://github.com/symfony/http-foundation/blob/2.8/Request.php
* 3.3: https://github.com/symfony/http-foundation/blob/3.3/Request.php
* Master: https://github.com/symfony/http-foundation/blob/master/Request.php

Can you please confirm if this is correct? If that's the case, we'll need to close this as "can't fix". Thanks!

**Comment by bruno-ds** [comment]
Hello,

It is true that the "shortcut" `Request::HEADER_X_FORWARDED_AWS_ELB` do not exist, so I reverse engineered the 3.3 source code in order to conclude how replace it with code compatible with the 2.8 version.

This said, in the 2.8, the `Request::HEADER_CLIENT_HOST` and `Request::HEADER_FORWARDED`  exists, so this code can be executed. 

I'm human and may have written errored code but it runs in the 2.8 version.

**Comment by nicolas-grekas** [comment]
LGTM

**Comment by xabbuh** [comment]
@bruno-ds Would you like to create a pull request with your suggestion? Just note that Symfony 2.7 is still maintained and you can open it PR against the `2.7` branch.

**Comment by bruno-ds** [comment]
@xabbuh this is done here: https://github.com/symfony/symfony-docs/compare/2.7...bruno-ds:patch-1
(it's my first PR, so I hope that it will comply with your quality requirements)

**Comment by wouterj** [comment]
Closing as the related PR was merged! (a long time ago) Still congratz @bruno-ds on your first doc PR!
