### ISSUE TITLE
Add missing trailing commas for all examples

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8325]
As discussed in #8319, there are some code examples where we don't include the trailing comma in the last element of the arrays. For example here:  https://github.com/symfony/symfony-docs/blob/master/service_container.rst.

So let's review all of them 😄

**Comment by ricknox** [comment]
I am going to work on this issue.

**Comment by javiereguiluz** [comment]
@DylanDelobel is going to give a shot at this, so we'll wait for his pull requests 😄

**Comment by javiereguiluz** [comment]
Fixed by #9238.
