### ISSUE TITLE
[2.7+][Component] In HttpFoundation, responses are not returned

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#8348]
On http://symfony.com/doc/2.7/components/http_foundation.html and following versions, `$response` is used as an example but `return $response;` is never called.

I only used code like `$response = new Response(…);` in Symfony where `return $response` was mandatory and it thinks that it's the same when HttpFoundation is used as a component.

Should HttpFoundation examples show calls to `return $response;`?

**Comment by xabbuh** [comment]
I don't think using `return` in these examples makes much sense. The thing is that we don't know how people are using the component. They may not have functions that act as controllers. That's why we use the  `send()` method in these examples. I think that's enough.

**Comment by javiereguiluz** [comment]
I agree with @xabbuh. Here we are explaining the component, so we cannot use the `return ...` as in the framework. However, I think we could improve the `prepare()` method explanation a bit, and I'm doing that in #8356.

**Comment by alexislefebvre** [comment]
Thanks for your answers, I understand that it's a component so the context is different from the other pages about Symfony.

@xabbuh

> That's why we use the `send()` method in these examples. I think that's enough.

But `send()` is never called in the following examples: http://symfony.com/doc/2.7/components/http_foundation.html#serving-files http://symfony.com/doc/2.7/components/http_foundation.html#creating-a-json-response

Should we add `send()` to the end of these examples?

**Comment by javiereguiluz** [comment]
Closing as fixed by #8356.
