### ISSUE TITLE
[Routing] Add the possibility to define a prefix for all routes of a controller

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8358]
See https://github.com/symfony/symfony/pull/24031 and https://symfony.com/blog/new-in-symfony-3-4-prefix-all-controller-route-names

**Comment by ismail1432** [comment]
I make a https://github.com/symfony/symfony-docs/pull/9159

**Comment by javiereguiluz** [comment]
Fixed by #9186.
