### ISSUE TITLE
[DI] Made container parameters case sensitive

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8359]
See https://github.com/symfony/symfony/pull/24052

**Comment by ro0NL** [comment]
Thx :)

**Comment by javiereguiluz** [comment]
Closing as fixed by #8622. The exact change was done here: https://github.com/symfony/symfony-docs/commit/02660464b189383e47e1f5f608ba8a8a44813fbd#diff-122786a4391045b1aa3edea4ab2e676f
