### ISSUE TITLE
[DI] Add ContainerInterface :: IGNORE_ON_UNINITIALIZED_REFERENCE

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8360]
See https://github.com/symfony/symfony/pull/24033

Not sure if this is an internal thing or we should document it too. @nicolas-grekas what do you think? Thanks!

**Comment by nicolas-grekas** [comment]
It's not internal, Could be useful for advanced uses (eg weak refs - or refs to initialized-ony services ;) )
The most important use case is going to be implemented in SF very soon so that directly using this maybe rare thought.
