### ISSUE TITLE
[Form] Add debug:form command

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8361]
See https://github.com/symfony/symfony/pull/23694. We need to mention this new command in the main debugging article.

**Comment by yceruto** [comment]
Is it normal that http://symfony.com/doc/current/debug.html to be empty?

**Comment by javiereguiluz** [comment]
See also: https://github.com/symfony/symfony/pull/24185

**Comment by ogizanagi** [comment]
And https://github.com/symfony/symfony/pull/24208 ;) (but not merged yet)

**Comment by javiereguiluz** [comment]
Fixed by #8517 ... we can create a new issue/PR if we want to improve the mention to this new command. Thanks.
