### ISSUE TITLE
Update %env()% documentation

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-docs#8382]
See https://github.com/symfony/symfony/pull/23901 + https://github.com/symfony/symfony/pull/23888

Just a ticket for reference now :)

**Comment by javiereguiluz** [comment]
See also https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables

**Comment by ro0NL** [comment]
It's getting ready :) i think for most users things will work out-of-the-box / as expected.

Nevertheless if you decide to document more advanced stuff when using env vars, i think these points are worth mentioning related to the Config tier;

- no real env lookup, config is validated with dummy env values based on the prefix (string by default)
  - this happens at normalization, merging and finalizing level (main Processor API)
- env placeholder can be detected with normalization closures upfront, and thus can be normalized
  - if the user normalizes a different value; then either the type changed or the string value changed (the placeholder is concatenated or so). In that case processing continues as usual (it doesnt use dummy value as it's a regular string)
- env vars are not compatible with enum nodes because we expect a know value (envs can be anything)
- env vars are not compatible with array nodes (either being prototyped yes/no) because that's part of the semantic structure, thus needs processing (normalizing, merging, validating)

**Comment by javiereguiluz** [comment]
Fixed by #9507.
