### ISSUE TITLE
Coding standards conflict

### ISSUE THREAD

**Issue by smokarz** [symfony/symfony-docs#8390]
Hi
In Symfony coding standard there is:

> "Use lowercase letters for service and parameter names "

but what now after S3.2 when I should name services using namespaces not ids ? 

for example i have:

`$result = $this->get('ApiBundle\Handler\CompanyHandler')->createCompany();`

and there is code sniffer notification shown before

what should I act now ?

greetings

**Comment by javiereguiluz** [comment]
Fixed by #9215.
