### ISSUE TITLE
Images broken on symfony.com

### ISSUE THREAD

**Issue by GromNaN** [symfony/symfony-docs#8400]
Some images are not available on symfony.com

On these pages, the `src` of `<img>` tag is correct, bu the server redirect to a 404.
https://symfony.com/doc/current/components/console/helpers/progressbar.html
https://symfony.com/doc/current/components/console/helpers/processhelper.html

Image `../../../_images/process-helper-verbose.png` is redirected to https://symfony.com/doc/current/_images/process-helper-verbose.png.html in a 404.

![image](https://user-images.githubusercontent.com/400034/30516108-9401761c-9b35-11e7-8060-df07f6c24606.png)

These images are correctly displayed in GitHub.
https://github.com/symfony/symfony-docs/blob/master/components/console/helpers/progressbar.rst
https://github.com/symfony/symfony-docs/blob/master/components/console/helpers/processhelper.rst

**Comment by xabbuh** [comment]
ping @javiereguiluz

**Comment by javiereguiluz** [comment]
We're investigating the cause. Thanks for the warning!

**Comment by GromNaN** [comment]
Apparently fixed. Thanks.
