### ISSUE TITLE
Documentation for WDT auto-reload

### ISSUE THREAD

**Issue by jeffreymb** [symfony/symfony-docs#8409]
See: https://github.com/symfony/symfony/pull/26655

I'm not sure where or how the above new functionality should be documented. https://symfony.com/doc/current/reference/configuration/web_profiler.html seems like the closest thing I could found but it doesn't quite fit. Suggestions?

The basic functionality is that a developer can add a `Symfony-Debug-Toolbar-Replace` with a value of "1" to an ajax response and the debug toolbar will automatically reload showing the info from the ajax request.

**Comment by gharlan** [comment]
Or maybe a new chapter here?
https://symfony.com/doc/current/profiler.html

**Comment by javiereguiluz** [comment]
Fixed by #9692.
