### ISSUE TITLE
Wrong default value for "framework.form.enabled" config node

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#8412]
As of Symfony 3.3 the `framework.form.enabled` config option is default ~`true`~  `false` [if you are requiring `symfony/symfony`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L120), but documentation says it is always false by default (https://symfony.com/doc/current/reference/configuration/framework.html#reference-form-enabled).

Originally reported on https://github.com/symfony/symfony/issues/24269
Also applies to assets, validation, translation, serialization and csrf

**Comment by stof** [comment]
The issue description is wrong. It defaults to true when you are **not** using `symfony/symfony` and `symfony/form` is installed (i.e. a Flex-like project using forms)

**Comment by chalasr** [comment]
Indeed, mistake. PR body updated.

**Comment by javiereguiluz** [comment]
Fixed by #8468.
