### ISSUE TITLE
New argon2i password encoder

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#8441]
See https://github.com/symfony/symfony/pull/21604 (3.4)
Can be documented around https://symfony.com/doc/current/reference/configuration/security.html#using-the-pbkdf2-encoder-security-and-speed

**Comment by chalasr** [comment]
The fact it won the password hashing competition and is the recommended algorithm for hashing passwords should probably be mentioned (per https://password-hashing.net).

**Comment by javiereguiluz** [comment]
See also https://symfony.com/blog/new-in-symfony-3-4-argon2i-password-hasher

It should also be mentioned that Bcrypt is a perfectly valid choice and that there's no need to update your existing applications to rehash passwords.

**Comment by xabbuh** [comment]
see #8481

**Comment by javiereguiluz** [comment]
Fixed by #8481.
