### ISSUE TITLE
Added a minimalist default PSR-3 logger

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8448]
A simple alternative when you don't want or have access to Monolog.

See https://github.com/symfony/symfony/pull/24300

**Comment by javiereguiluz** [comment]
I don't know what to do about this. We have at least two alternatives:

1) Document this at the beginning of the main `logging.rst` article and move the current contents below: *"if you need a more powerful logger, then use Monolog, blah blah"*.
2) Document this in a dedicated article and explain it as "an oddity" for edge cases ... and keep recommending to always use Monolog in "real apps".

Ping @weaverryan @xabbuh @wouterj. Thanks!

**Comment by weaverryan** [comment]
Option 1! But this almost an internal detail. We just need to say “there is technically a logger always, but it doesn’t do much. Install monolog”

**Comment by xabbuh** [comment]
I agree with Ryan.

**Comment by javiereguiluz** [comment]
Fixed by #10321.
