### ISSUE TITLE
[DependencyInjection] Adding Definition::addError() and a compiler pass to throw errors as exceptions

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8458]
See https://github.com/symfony/symfony/pull/24290.

**Comment by nicolas-grekas** [comment]
Looks internal to me. It's used by autowiring pass to postpone errors, but I'm not sure how this can be of interest to userland.

**Comment by HeahDude** [comment]
Agreed, closing then. Feel free to reopen if there a legit use case. Thanks!
