### ISSUE TITLE
Added new fluent PHP config formats for services and routes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8462]
* Services: https://github.com/symfony/symfony/pull/23834
* Routes: https://github.com/symfony/symfony/pull/24180

We must make a decision about this:

1) Publish a new article mentioning this new notation ...
2) ... or adding this new format to EVERY example of the docs (this would be a huge task!)

**Comment by afurculita** [comment]
+1 for adding this new format to EVERY example of the docs

**Comment by HeahDude** [comment]
This feels needed somehow https://github.com/symfony/symfony-docs/pull/11085/files#diff-7b2545dd61a3817c08117d17725de110L63.

**Comment by afilina** [comment]
@javiereguiluz @HeahDude Do you guys need help on that?

**Comment by xabbuh** [comment]
#10824 does the DI part

**Comment by HeahDude** [comment]
And #11085 did the routing part. Closing here, thanks!
