### ISSUE TITLE
Improve the styles of some codes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8490]
Example: https://symfony.com/doc/current/components/var_dumper.html

![code-issue](https://user-images.githubusercontent.com/73419/31309973-ae967742-ab8f-11e7-94a1-8aa900eecd47.png)

Wouter recommends changing `word-break: break-all;` to `word-break: break-word;` for the `code` element. I agree, but I need to double check if this doesn't interfere with anything else (`<code>` can be in headlines, the sidebar TOC, etc.)

**Comment by javiereguiluz** [comment]
I've tested this change and it works OK most of the time, so I'm proposing it for symfony.com. If accepted, it will be deployed online soon.

My only minor concern is that we use underscores a lot and they are not considered word breaks, so depending on the width of your browser, you can see some ugly gaps:

![new-code](https://user-images.githubusercontent.com/73419/31327607-bf27fd50-acd0-11e7-9394-dfbf799c533d.png)

In the future, if we decide that this is a problem, we can always rever to the previous situation. Thanks!

**Comment by xabbuh** [comment]
I agree that this doesn't look very nice. But to me that's better than having `stream_get_meta_data()` split.
