### ISSUE TITLE
The realpath_cache_size setting in modern PHP versions is correct

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8512]
In https://symfony.com/doc/current/performance.html#configure-the-php-realpath-cache we say:

> By default, PHP sets a realpath_cache_size of 16K which is too low for Symfony. Consider updating this value at least to 4096K.

Today I read this: https://tideways.io/profiler/blog/how-does-the-php-realpath-cache-work-and-how-to-configure-it

> PHP 7.2 sets realpath_cache_size to 4096K by default ... This change was also backported to PHP 7.0 and PHP 7.1 patch releases in January.

**Comment by xabbuh** [comment]
This seems to be true: https://3v4l.org/H0B6i

**Comment by xabbuh** [comment]
But, I am not sure if it's worth it to update the docs now given that we still have supported Symfony versions that have to work with PHP 5.x.

**Comment by weaverryan** [comment]
We can at least remove the recommendation from master (so, Symfony 4)

**Comment by javiereguiluz** [comment]
In #9216 a reword is proposed to not mention if this is a default PHP value or not ... just that you need to use at least those values.

**Comment by javiereguiluz** [comment]
Fixed by #9216.
