### ISSUE TITLE
Symfony 3.3 documentation is incomplete

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony-docs#8536]
Repost from https://github.com/symfony/symfony/issues/24654

For example i want to insert some content in a database based on the logged in user ( user_id )
i was only able to do that after paying for tutorials because symfony documentation is incomplete !

i also found that symfony does integrate forms with bootstrap template ( which is awesome !!! )
( http://symfony.com/doc/current/form/form_themes.html )
however, that i didn't found on documentation ... also paid for this !

Don't get me wrong, Symfony is awesome ! It has a lot of potential, but not very documented if not at all

This may not be a bug, but it should be definitely treated like one ...

I'm trying to open a debate here ( not a fight ! )

**Comment by cybernet** [comment]
Doctrine documentation show me how to insert a row in a table ... but a simple thing like inserting the current user that is using the form ... how ?

for instance it took me a few hours just to figure out how to pass an argument to a form ( not even [stackoverflow](https://stackoverflow.com/questions/46870572/passing-data-to-buildform-in-symfony-3-3) didn't help ... ) finally i decided to search for a demo app and i find your [blog](https://github.com/symfony/demo/blob/master/src/Controller/BlogController.php#L92) 

now i'm searching again on how to get 2 values in one query from 2 table ( without DQL ) because ... we have entities...

also symfony doesn't have a default Slug component
it's not like symfony is used for websites that publish stuff ... and well they need urls
i found a [Slug bundle](https://github.com/cocur/slugify) but i have to figure out a way to make unique urls ... and many more.. i started a week ago with symfony, if i wasn't using phpstorm i would smash my laptop with a fire extinguisher ( it's nearby )

i know that making a good documentation takes time, but at least publish the basic and more examples on github, like a forum, using Users and registration and stuff ( these are the basic stuff that any n00b needs when learning new stuff )

my login and registration part i got it from [auth0](https://auth0.com/blog/creating-your-first-symfony-app-and-adding-authentication/) ...

it's the small things that matter

and once again, this issue should be reopened ...

**Comment by weaverryan** [comment]
Hi there!

Yes, we definitely need to make some improvements to the docs - so thanks for the specific examples! To make this actionable, could you open an individual issue for each suggestion? I hope we can improve things greatly, with help from the community of course :).

**Comment by wjbLabs** [comment]
@cybernet 

> if i wasn't using phpstorm i would smash my laptop with a fire extinguisher 

Man... I started using Symfony in 2012 when documentation was far smaller than now, stackoverflow was useless because it was new FW and phpstorm plugin had < 5% of functionalities than it is having now.

Trust me, you don't know what being frustrated really means :smile: 

Anyway, about slug: you should install [doctrine extensions bundle ](https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html) as it gives you more tools you will need.

**Comment by cybernet** [comment]
in your opinion. what are the basic stuff that any developer would try to do for a website ? except user registration and login ( we got that covered by symfony ( thank god ) )

**Comment by wjbLabs** [comment]
If you want to learn Symfony, I would suggest starting with something small. Try building a blog where you only have categories, posts and tags. Make admin, do not use existing solution.

This might sound simple but you should try it anyway. The real fun starts when you want to use DataTransformers for tags so you don't duplicate them. You will see when you start, they are insanely good! IMO, I thing they are the most powerful thing I have seen so far.

About security; good luck with that. I tried it, I failed and I stick to FosUserBundle for that. I don't think it is worth the time to deal with all that, at least when learning.

**Comment by javiereguiluz** [comment]
We need to close here because Symfony 3.3 is now unmaintained and its docs are no longer updated. At the moment we update 2.7, 2.8, 3.4, 4.0 and master (4.1) branches.

In any case, as Ryan said, we'd need to open an issue for each specific problem that you face when reading Symfony Docs or working with Symfony apps. That's the best way to tackle them. Thank you!
