### ISSUE TITLE
Update parameters.yml documentation to talk about .env

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8546]
Changes to be made for 4.0.

**Comment by javiereguiluz** [comment]
I created a meta-issue for the changes needed for 4.0 (https://github.com/symfony/symfony-docs/issues/7809) but maybe it's better to create smaller issues like this one? My fear with meta-issues is that they can end up being never-ending and too big.

**Comment by weaverryan** [comment]
Ok, that’s great! I don’t mind having the meta issue - it’s nice. So let’s not automatically create issues for everything. But if some items do have their own issue, we can just link. Until we have done more work and are closer to ready, I don’t think we should worry too much about perfectly organizing things.

**Comment by weaverryan** [comment]
After #8779 and once #8754 is done (specifically, the quick intro), this will be done. So, I'm going to close it.
