### ISSUE TITLE
Document the container.autowiring.strict_mode option

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8561]
It's useful to disable the hybrid 2.8/3.3 autowiring mode ... so it should be `true` in 3.4+ applications.

See https://github.com/symfony/symfony/pull/24671 and https://github.com/symfony/recipes/pull/221

**Comment by yceruto** [comment]
Note: this parameter is useful only for 3.4, in 4.0 it's useless as strict mode behavior is enabled by default.

**Comment by althaus** [comment]
Any news on this? I just stumbled upon the deprecation and needed to google for a fix. Nothing mentioned in the docs or the UPGRADE file.

**Comment by nicolas-grekas** [comment]
Fixed by https://github.com/symfony/symfony/pull/26278 ?

**Comment by HeahDude** [comment]
And https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/src/Kernel.php#L42. Closing, thanks!
