### ISSUE TITLE
How to Use multiple User Providers

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony-docs#8582]
On my symfony project i have setup 2 multiple user providers
i need to know how the user logged in ? trough what provider so i can  use it in a controller
for instance, i have a single login page, depending on what provider is used i wanted to redirect him to a different route

i didn't find anything in the documentation on how to achieve this ( https://symfony.com/doc/current/security/multiple_user_providers.html )

**Comment by xabbuh** [comment]
Basically, you will do that by checking which `UserInterface` implementation is stored in the token. As each provider must have a way to detect whether or not it supports the currently logged in user you can use the same approach to check which provider was loading the user.

Is it needed to add this information to the existing article?

**Comment by cybernet** [comment]
look, i'm a beginner, for me, of course is needed, but for others ... i don't know

that depends on what kind of programmers symfony is addressed to ...

**Comment by javiereguiluz** [comment]
Fixed by #9726.
