### ISSUE TITLE
[Filesystem] Improve the documentation of the mirror method

### ISSUE THREAD

**Issue by naitsirch** [symfony/symfony-docs#8591]
In the [current doc](http://symfony.com/doc/current/components/filesystem.html#mirror) only the first two parameters (`$originDir` and `$targetDir`) are mentioned.

It would be nice if the other parameters (`$iterator` and `$options`) are explained, too (see [here](http://api.symfony.com/3.3/Symfony/Component/Filesystem/Filesystem.html#method_mirror)).

**Comment by javiereguiluz** [comment]
This one is tricky ... because we usually don't document all the method/function parameters, only the essential params needed to use something. And even when we document them, we don't mention all their features. But we can make exceptions for important things. It's just a tricky balance.

**Comment by naitsirch** [comment]
Maybe I can create a PR next month when I have a little bit more time ;-)
Am 12.11.2017 12:01 nachm. schrieb Javier Eguiluz <notifications@github.com>:This one is tricky ... because we usually don't document all the method/function parameters, only the essential params needed to use something. And even when we document them, we don't mention all their features. But we can make exceptions for important things. It's just a tricky balance.

**Comment by javiereguiluz** [comment]
After having thought more about this, I propose to close as "won't fix". To me this falls into the *"extra options/arguments that are not mandatory to use "this thing" and which we don't document to not make the docs harder to maintain"*. Thanks for understanding it.

**Comment by naitsirch** [comment]
My thought was to add a hint telling that there are more options and link to api.symfony.com
Am 03.01.2018 15:28 schrieb Javier Eguiluz <notifications@github.com>:After having thought more about this, I propose to close as "won't fix". To me this falls into the "extra options/arguments that are not mandatory to use "this thing" and which we don't document to not make the docs harder to maintain". Thanks for understanding it.
