### ISSUE TITLE
The BC policy table needs to be updated to cover return types

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#8609]
Our BC policy table listing everything contributors can and cannot do due to BC currently explains when you can add or remove typehints for arguments.
We need to update this table to explain what we can do for return types as well, given that Symfony 4 will be able to use them (and will use them when possible)

**Comment by alcaeus** [comment]
There are `Change return type` in the tables at https://symfony.com/doc/current/contributing/code/bc.html#working-on-symfony-code - shouldn't that be sufficient?

**Comment by javiereguiluz** [comment]
Closing as "not needed to be fixed" because most people on Symfony Slack thought that we don't need to do anything else here. Thanks!

**Comment by stof** [comment]
We need rules about adding or removing a PHP return type, similar to what we have for typehints. (removing an explicit return type, even without changing the contract in the documented return type, is a BC break in PHP)

**Comment by javiereguiluz** [comment]
Closing as fixed by #9717.
