### ISSUE TITLE
Images are broken in documentation.

### ISSUE THREAD

**Issue by hackzilla** [symfony/symfony-docs#8677]
There images in these pages are referencing 404s.

* https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
* https://symfony.com/doc/current/contributing/documentation/overview.html
* https://symfony.com/doc/current/setup.html

e.g. https://symfony.com/doc/current/_images/anonymous_wdt.png

I can see that image in the repo.
https://github.com/symfony/symfony-docs/tree/master/_images/security

**Comment by xabbuh** [comment]
ping @javiereguiluz

**Comment by javiereguiluz** [comment]
I'm closing this one as "fixed" because all the images of the given URLs now work as expected. Thanks!

**Comment by zain-saqer** [comment]
this image link is broken:
https://symfony.com/doc/current/_images/anonymous_wdt.png

**Comment by hackzilla** [comment]
It is also redirecting to https://symfony.com/doc/current/_images/anonymous_wdt.png.html

I believe this issue is now #9349
