### ISSUE TITLE
A chapter for maintenance and maintainability

### ISSUE THREAD

**Issue by linaori** [symfony/symfony-docs#8695]
After meeting and talking with @weaverryan, @nicolas-grekas and @stof at the hackday, I would like to propose a few additions regarding maintenance and maintainability for reusable bundles.

During the hackday, I've seen a lot of bundles (including my own), that already spewed errors and deprecations running the tests. It's doesn't mean that the bundle is unstable, but could for example be because a dependency has an issue. A second issue, is lack of knowledge or experience regarding Travis and how to properly build a matrix. 

As package maintainer, you can use Cron jobs in Travis to run the tests daily and this would alert, additionally there's a tool: Nightli.es to do this for you (perhaps even others), as it requires no clicking for each repository.

I would like to see at least the Cron job feature described in the docs, to run their builds daily, so the maintainer can easily find out when something breaks due to a new dependency. In addition to this, I would like to see a Travis yml file that contains a few builds that will work for the majority of bundles ready for copy paste if needed. It should probably test the current, latest, minimum and optionally with the phpnightly and possibly Dev dependencies. This would make issues such as symfony/monolog-bundle#223 spotted in a far earlier stage of development and releases of dependencies. In addition to that, it might find accidental BC breaks or bugs in Symfony a lot faster.

In theory this can be expanded upon and automate things, but having people aware of this, would be an awesome start!

**Comment by iltar** [comment]
Small addition, which is slightly unrelated to this particular issue, but it would be really cool to have some sort of a bundle health check. A lot of bundles do not have tests, are deprecated or no longer actively maintained. It would be awesome to have some sort of check people can run on bundles (or packages in general).

**Comment by javiereguiluz** [comment]
I'm closing this as fixed because we already display a recommended Travis config for bundles: https://symfony.com/doc/current/setup/bundles.html#update-the-travis-ci-configuration Thanks.
