### ISSUE TITLE
Image are not rendered on form reference

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony-docs#8707]
Hello.

On the following page https://symfony.com/doc/current/reference/forms/types/choice.html 
all images are not rendered. It works well on <3.3

I tried to fix it, but I did not find the error.
For exemple, this file https://github.com/symfony/symfony-docs/blob/master/reference/forms/types/options/group_by.rst.inc contains `.. image:: /_images/reference/form/choice-example5.png` and the image do exist.

I don't know why it does not work :/

**Comment by xabbuh** [comment]
Unfortunately that's true. But I think we already cover that in #8677. Thank you Greg anyway. :)
