### ISSUE TITLE
Update Apache server configuration for Flex

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8724]
See #8693. Basically, Symfony 4 won't ship with a `.htaccess` file anymore. But see https://github.com/symfony/recipes/issues/190#issuecomment-336173408 - we *may* have a recipe for it soon. So, this is kind of blocked until we figure that out.

**Comment by xabbuh** [comment]
Now that we have a pack, should we do anything here?

**Comment by weaverryan** [comment]
We need to wait for the recipe to be created, then we can document that you need to install it for Apache (or put the rewrite rules into your vhost if you prefer)

**Comment by ricknox** [comment]
The recipe has been created by @fabpot in [symfony/apache-pack](https://github.com/symfony/apache-pack). However, this recipe is empty.

As for the article in the documentation; I think we can add this as an x within [setup/flex.rst](https://github.com/symfony/symfony-docs/blob/master/setup/flex.rst):

```
Using Flex With The Apache Webserver
------------------------------------
```

Or we make a new node at [setup/web_server_configuration.rst](https://github.com/symfony/symfony-docs/blob/master/setup/web_server_configuration.rst) about configure Apache for Flex by using the recipe.

@fabpot: What is the status of the [symfony/apache-pack](https://github.com/symfony/apache-pack)?
@weaverryan: In what doc page are we going to put this?

**Comment by fabpot** [comment]
See symfony/recipes#190
