### ISSUE TITLE
Fix validation YAML paths

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8727]
In #8593, one of the automated changes changed the `validation.yml` paths like this:

```diff
- src/AppBundle/Resources/config/validation.yml
+ src/Resources/config/validation.yml
```

But, that's not correct, right? Is there a correct path for the validation YAML files? Or does the user need to add a `framework.validation.mapping.paths` config? I believe this is the case.

@yceruto could you update the paths? If I'm correct about needing the config, then I guess the path should be `config/validation.yaml`, and we will need a note near the top that mentions the config that's needed (probably can just link to the reference section). I don't want to make a huge thing out of this, as it's not the recommended config, but it should be accurate and mentioned.

Thanks!

**Comment by yceruto** [comment]
Yeah, it was merged before https://github.com/symfony/symfony/pull/24856 :) so need to be updated again, same for https://github.com/symfony/symfony/pull/24833 and `config/serializer.yaml`.

**Comment by weaverryan** [comment]
@yceruto how are things now in the 4.0 branch. Do we need more changes? Or can this be closed? Thx :)

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony-docs/pull/8782 ;)
