### ISSUE TITLE
Make Upgrade to Flex dir structure docs clear & easy to find

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8746]
Currently, there *is* some docs about upgrading to Flex - it's in the Flex chapter. But, we need to make sure this is very easy to find - probably in its own, titled article "How to upgrade to using Symfony Flex".

Also, as I've discussed with Javier, I'm not sure if the instructions can be easier. I haven't had time yet to play with things and see.

**Comment by jzawadzki** [comment]
I was just *literally* making an issue on symfony/flex on that - so I though I just put my question here if I may:

Background:
I was doing an upgrade of my app written in 3.4 to 4.0 but I wanted to use new directory structure and flex on new version.  So i created whole new 4.0 project, copied code into and, what took some time, find out which symfony components/bundles I use in my application. App was pretty small so it wasn't big deal but still wasn't straightforward. 

Question:
So my question is - is there a way I can find which symfony components I use in my codebase? That way we could help developers with adopting flex?

That could be some doc on symfony upgrade with e.g. list of components included earlier in symfony/symfony and that those may need to be added but I was thinking also if we could write some script that could list all imports from `Symfony\` namespace on every php file in my `src/` and make a list of components that I'm missing?
WDYT? Is there easier way to do that?

**Comment by weaverryan** [comment]
Hey @jzawadzki! We are thinking alike then :)

> So my question is - is there a way I can find which symfony components I use in my codebase? That way we could help developers with adopting flex?

I don't think this is possible.

> That could be some doc on symfony upgrade with e.g. list of components included earlier in symfony/symfony

But this IS possible, and it's a great idea. We can create a list of all of the Symfony components/bundles that are a part of `symfony/symfony` that you do *not* get automatically with a new Flex project. Then the user will have a somewhat-easy-to-navigate list to check out.

> but I was thinking also if we could write some script that could list all imports from Symfony\ namespace on every php file in my src/ and make a list of components that I'm missing?

Yes, this is probably possible. In fact, I would *love* to see a tool created to help automate some of the more tedious changes. I won't have time to do that. But if we get the process documented clearly, maybe creating a tool to help would not be too difficult.

**Comment by weaverryan** [comment]
We also need to document the `container.autowiring.strict_mode: true` parameter. Users should set it when ready to upgrade on 3.4, as there is one type of autowiring deprecation that is a false positive. See symfony/symfony#25265

**Comment by javiereguiluz** [comment]
I'm closing this old issue because we haven't received any bug reports (here or on Slack, etc.) about this, so the current instructions may be clear enough. If we receive reports in the future, we can make the needed changes. Thanks.
