### ISSUE TITLE
Navigation issue on symfony.com website

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8749]
Moved from https://github.com/symfony/symfony/issues/25156

-----

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

This isn't a bug report not for Symfony itself, but for the documentation website (symfony.com)
When browsing it from a tablet (iPad 2) and focusing on the main content, there's an annoying bug with the navbar. See the screenshot:
![fullsizeoutput_655](https://user-images.githubusercontent.com/6420099/33231814-33c09322-d204-11e7-9748-6b7cc283a11d.jpeg)

**Comment by javiereguiluz** [comment]
I reproduced this issue as follows.

If you load any page on iPad, it works as expected:

![screenshot1](https://user-images.githubusercontent.com/73419/33231994-11231b46-d1ff-11e7-9bdf-0e299303ce7d.png)

But if you double-tap on the main area of the page, the applied zoom breaks the navigation:

![screenshot2](https://user-images.githubusercontent.com/73419/33231998-250eb3f4-d1ff-11e7-85a3-bb80445f5acf.png)

I don't know how to fix this. Has any of you experienced this problem in your own applications? Thanks for your help!

**Comment by cordoval** [comment]
I have noticed that it depends on the locatoin where you tap, on my macpro i tap on the header sticky and it enlarges differently, so i assume it is a matter of scope, and for the html css that loads for ipad has probably a different ration you see it out of whack. So that is plausible explanation.

**Comment by javiereguiluz** [comment]
We've fixed this issue adding these new styles:

```css
.header__nav ul { /* ... */, flex-wrap: wrap; font-size: $font-size-small; height: 40px; overflow: hidden; }
```

Now, when double tapping the content area, the "Download" button disappears and the rest of menu elements are displayed correctly.

I'm closing as fixed because the related pull request is in a private repo and this fix will be available after the merging and redeploying. Thanks!
