### ISSUE TITLE
Updating docs to Symfony 4 and Symfony Flex

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8754]
This meta-issue keeps track of the docs upgrade to Symfony 4 and Flex:

| Directory | Pull Request
| --------- | ------------
| assetic/ | ~#8750~
| best_practices/ | ~#8599~
| bundles/ | ~#8613~, ~#8617~, ~#8620~
| components/ | ~#8747~
| configuration/ | ~#8732~
| console/ | ~#8748~
| contributing/ | 
| controller/ | ~#8664~
| cookbook/ | *(update not necessary)*
| create_framework/ | 
| deployment/ | ~#8721~
| doctrine/ | ~#8729~
| email/ | ~#8667~, ~#8745~
| event_dispatcher/ | ~#8670~
| form/ | ~#8755~
| frontend/ | ~#8750~
| http_cache/ | ~#8682~
| introduction/ | *(update not necessary)*
| logging/ | ~#8683~
| profiler/ |  ~#8685~
| quick_tour/ | (partially) #8781 
| reference/ | ~#8643~
| routing/ | ~#8657~
| security/ | ~#8735~
| serializer/ | ~#8687~
| service_container/ | ~#8751~
| session/ | ~#8689~
| setup/ | ~#8544~
| templating/ | ~#8734~
| testing/ | ~#8705~
| translation/ | ~#8733~
| validation/ | ~#8756~
| workflow/ | ~#8654~

**Comment by javiereguiluz** [comment]
Things to do:

* `/contributing/code/reproducer.rst` needs a heavy reword. It still talks about Symfony standard edition.
* ...

**Comment by weaverryan** [comment]
See #8798.

Other than the quick tour, do we need to do anything else in this issue? If not, we should close it and open a separate issue for the quick tour.

**Comment by javiereguiluz** [comment]
Closing as fixed. The rest of things to update are #8884 and #8885.
