### ISSUE TITLE
DataTransformer missing image in current docs

### ISSUE THREAD

**Issue by DonCallisto** [symfony/symfony-docs#8757]
At this link [https://symfony.com/doc/current/form/data_transformers.html#about-model-and-view-transformers](https://symfony.com/doc/current/form/data_transformers.html#about-model-and-view-transformers) data transformer image is missing.

I suppose that it is not copied in the right dir (looking at the broken link).

**Comment by xabbuh** [comment]
Yes, we have some issues with images in the generated documentation. Thanks for reporting it. However, we can close here as we already have #8677 to keep track of it.

**Comment by DonCallisto** [comment]
Sorry, didn't noticed #8677.
