### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by Oppodelldog** [symfony/symfony-docs#8771]
The documentation of the BrowserKit Client is someway misleading.
I wanted to use the BrowserKit Client to make a real call to a public webseite, but that does not work out of the box. Always my application is triggered.

There is a comment in the documentation of the "History" feature which let me assume how external calls would have been possible. But the request related code does not differ from some code abouve that does not state to "make a real request to an external site".

So I would suggest to remove that comment. The code is better readable without it.

https://github.com/symfony/symfony-docs/blame/4.0/components/browser_kit.rst#L202

**Comment by weaverryan** [comment]
Yea... the Client isn't really meant to make requests to external sites. Is it even possible? Does the code that @Oppodelldog linked to even work? I agree that something should probably be removed.

**Comment by javiereguiluz** [comment]
I think this is a bug. We're trying to fix it in #8823. Thanks for reporting.
