### ISSUE TITLE
Re-organize reference sections by their package/feature

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8774]
Currently, we organize the reference section by bundle - e.g. `framework`, `twig`, etc. I'd like to propose 2 changes:

1) Link to the reference section at the bottom of the related article. For example, at the bottom of the main `logging` article, we should link to the logging reference section. Heck, we should maybe even move the logging reference under `logging/`.

2) Things under the `framework` key are actually modified in Flex by several different files - `framework.yaml`, `workflow.yaml`, `translation.yaml`, etc. I think it makes more sense to split the `framework` reference section into smaller sections and include the reference *where* you need it. for example, we would talk about the `framework.workflow` configuration in the Workflow docs.

**Comment by javiereguiluz** [comment]
I tried to do this in #10097 ... but I didn't like the idea at all 😞  The current docs (which separate config by package: framework, twig, doctrine, monolog, etc.) feels better. Separating by sub-package (framework.asset, framework.workflow, etc.) create lots of tiny files that will complicate our maintenance and could be more confusing for readers too. Let's close this as "won't fix" ... and let's reevaluate this decision in the future, when our backlog and the ending features to be merged will be smaller. Thanks!
