### ISSUE TITLE
No more welcome page in 4.0?

### ISSUE THREAD

**Issue by viion** [symfony/symfony-docs#8783]
Following: http://symfony.com/doc/4.0/setup.html

- `composer create-project symfony/skeleton my-project`
- `cd my-project`
- `composer require server`
- `php bin/console server:run`

Quote:

> Open your browser and navigate to http://localhost:8000/. If everything is working, you'll see a welcome page.

Instead get:

```
Sorry, the page you are looking for could not be found.

(2/2) NotFoundHttpException
No route found for "GET /"
```

In 3.3 there used to be a welcome. The 4.0 skeleton doesn't create any kind of controller or template at all, so you have to do that yourself.

**Comment by yceruto** [comment]
This experience was improved since 3.4, use `-s rc` to create a new 4.0-RC project and the welcome page will be there at `GET /`.

**Comment by javiereguiluz** [comment]
@viion thanks for reporting, but as @yceruto said, we changed this recently and now Symfony shows a Welcome Page again. If you are curious, in #24403 you can see the clever trick used by @yceruto to show the Welcome Page.
