### ISSUE TITLE
please add about creating Symfony 3.4 project that support Symfony Flex

### ISSUE THREAD

**Issue by erlangp** [symfony/symfony-docs#8807]
for creating Symfony 3.4 project that support Symfony Flex, use: 
`composer create-project symfony/skeleton proj_name "3.4"`

for creating Symfony 3.4 project that not (planning to) support Symfony Flex, use: 
`php symfony.phar new proj_name "3.4"`

because both commands create different directory structure (example: location for registering bundles)
Thanks..

**Comment by erlangp** [comment]
https://github.com/symfony/symfony-docs/issues/8746

**Comment by weaverryan** [comment]
Hmm. So we really don't recommend creating *new* projects with Symfony 3.4. Symfony 3.4 is just meant to be a "helper" version for *upgrading* projects. Does that help?
