### ISSUE TITLE
There are no app/AppKernel.php file in fresh 3.4 version but docs says otherwise.

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-docs#8812]
Hi, I just installed Symfony 3.4 `composer create-project symfony/skeleton my_project 3.4` and there are no `app/` directory nor `src/AppBundle`.  Documentation for 3.4 https://symfony.com/doc/3.4/page_creation.html#bundles-configuration saying:

> Bundles are registered in your app/AppKernel.php file

But this file not exists in fresh Symfony. What is going on? Did I install Symfony 4.0 or documentation is wrong? Console command `--version` saying I have 3.4 version.

edit: ok, I think I got it, I should read documentation for 4.0 as 3.4 structure became 4.0

**Comment by john-arcus** [comment]
I am building a console applications and that seems to run without any AppKernel.php script. So, I agree with sruj. The docs are misleading because they assume an AppKernel class is actually being used but does not explain how the AppKernel script gets created and used.
