### ISSUE TITLE
Unknown Twig function csrf_token

### ISSUE THREAD

**Issue by Guibzs** [symfony/symfony-docs#8816]
See [symfony-docs/security/csrf_in_login_form.rst](https://github.com/symfony/symfony-docs/blob/4.0/security/csrf_in_login_form.rst)

There's no more csrf_token function included in twig since Symfony 4.0.
Or is there a missing **_composer require_** ?

**Comment by xabbuh** [comment]
You are right. This becomes a bit tricky when using Symfony 4. The "easy" solution is to install the Form component for the function to be available. If you want to solve this in a cleaner way, you may want to implement the function yourself. You can take a look at symfony/symfony#25197 to see how easy this is in fact.

**Comment by javiereguiluz** [comment]
@Guibzs good catch. The good solution will come in Symfony 4.1 thanks to the change made by @xabbuh, but meanwhile we can improve this article as proposed in #8821.

**Comment by curry684** [comment]
Ran into same issue just now, so we can at least mark this confirmed  ;)

Status: reviewed

**Comment by javiereguiluz** [comment]
Fixed by #8873.
