### ISSUE TITLE
/templating/overriding.rst should update in version 4

### ISSUE THREAD

**Issue by TangMonk** [symfony/symfony-docs#8835]
the bundle path should be update

**Comment by javiereguiluz** [comment]
@TangMonk I guess you are referring to this article --> https://symfony.com/doc/current/templating/overriding.html  Which is the bundle path that should be updated? Thanks!

**Comment by TangMonk** [comment]
![image](https://user-images.githubusercontent.com/3498786/33702069-d7e2223e-db5c-11e7-8eb4-b1e34be46492.png)

the `Resources/views/Blog/index.html.twig` path is unclear, it should be `vendor/acme_bundle/Resources/views/Blog/index.html.twig`

**Comment by yceruto** [comment]
The paragraph begins by saying `Inside the bundle` which means it's relative to the bundle directory:
* from app point of view: `vendor/acme/bundle-name/`
* [from bundle point of view](https://github.com/symfony/maker-bundle/tree/master/src): `src/`

IMHO it's clear enough.

**Comment by javiereguiluz** [comment]
I think I agree with @yceruto here. The phrase is short and starts with "Inside the bundle..." so it's probably clear enough. But thanks for reporting this problem. We'll be on alert in case we receive more issue reports about this. Thank you!
