### ISSUE TITLE
doctrine.rst should be update in Version 4

### ISSUE THREAD

**Issue by TangMonk** [symfony/symfony-docs#8838]
![image](https://user-images.githubusercontent.com/3498786/33649855-7c255c4e-da9a-11e7-932e-bcc4b2f6d05c.png)

migration sub command not works in doctrine in Symfony 4

**Comment by ricknox** [comment]
Thanks for reporting this problem @TangMonk. I will pick up this problem and make an improved article.

**Comment by xabbuh** [comment]
What do you mean with "it does not work"?

**Comment by TangMonk** [comment]
`bin/console doctrine:migrations:migrate` and `bin/console doctrine:migrations:diff` not works

![image](https://user-images.githubusercontent.com/3498786/33706565-7a87b974-db6f-11e7-9ac4-d9873dfaa186.png)

**Comment by xabbuh** [comment]
Did you install the DoctrineMigrationsBundle?

**Comment by javiereguiluz** [comment]
The problem can be that migrations weren't included in the "ORM pack" used by Flex. They were added on October 30th (see https://github.com/symfony/orm-pack/commit/44d915006a20c36c380f13f0c5c64e43b4268a1d#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) so maybe you installed this in the past and migrations weren't included then. You can solve it reinstalling the "ORM pack" or more easily, running this in your project: "composer require doctrine/doctrine-migrations-bundle"

**Comment by TangMonk** [comment]
@javiereguiluz thanks for you tips, but I think it should be documented for avoid new users

**Comment by TangMonk** [comment]
thanks, I understand

**Comment by javiereguiluz** [comment]
> @javiereguiluz thanks for you tips, but I think it should be documented for avoid new users

yes ... the things is that anyone who created a Symfony 4 project or run "composer require orm" after October 30th (1 month before the final release of Symfony 4) should have migrations installed. This error should only happen to early beta testers of Symfony, but that's OK.

The question is: was your application created before October 30th or did you install the "orm" dependency before October 30th? If you didn't, then there's some issue here that we must investigate. Thanks!

**Comment by TangMonk** [comment]
@javiereguiluz I am using the latest Symfony 4, And after I install DoctrineMigrationsBundle , it works fine, thanks, it's my problem, I miss the doc

**Comment by javiereguiluz** [comment]
OK. Thanks for your help here trying to understand the problem. We appreciate it a lot. I'm closing this issue as "fixed" then. Thank you!
