### ISSUE TITLE
Missing guideline when explaining how to get services from the service container in a Command

### ISSUE THREAD

**Issue by netsuo** [symfony/symfony-docs#8841]
In the current documentation, in the paragraph where it explains how to inject services in a command, the documentation doesn't state that you should call `parent::__construct`.

https://symfony.com/doc/current/console.html#getting-services-from-the-service-container

However, it is explained in the documentation about defining Commands as services.

https://symfony.com/doc/current/console/commands_as_services.html

I think we should add this information in the first link to avoid user having unusable Commands.

**Comment by javiereguiluz** [comment]
@netsuo well spotted! Thanks for reporting. We're trying to fix this in #8854.

**Comment by javiereguiluz** [comment]
Finally fixed by #8849.
