### ISSUE TITLE
Document 4.0 upgrade path regarding SensioDistributionBundle

### ISSUE THREAD

**Issue by Majkl578** [symfony/symfony-docs#8842]
Based on sensiolabs/SensioDistributionBundle#334, it should be documented how to properly handle this dependency during upgrade from 3.x to 4.0.
Since the bundle is replaced by Flex entirely and no support to SF4 will ever exist, it causes a dependency hell during upgrade to SF4.

**Comment by javiereguiluz** [comment]
I'm closing this old issue as "won't fix" because sadly we couldn't make the proposed changes on time. Luckily we haven't receive many support questions about this ... but if suddenly we start receiving them (on Symfony's Slack for example) we'll reopen. Thanks!
