### ISSUE TITLE
[Console] Always use lazy commands?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8843]
This issue was reported in the Symfony Slack.

1) A user was reading https://symfony.com/doc/current/console.html
2) Then he run `make:command`
3) He didn't see `->setName('...')` in the generated command, so he added `->setName('app:mycommand')` himself.
4) Then he saw this error: *">>>There are no commands defined in the "app:mycommand" namespace"*

The problem is:

1) MakerBundle generates lazy commands by default (https://github.com/symfony/maker-bundle/blob/bf97703ddb68c6b37bd6bab5f5ebd5c7542ca1ef/src/Resources/skeleton/command/Command.tpl.php#L14), as explained in https://symfony.com/doc/3.4/console/commands_as_services.html#lazy-loading
2) But most of the console docs don't use lazy commands.

What should we do here? Should we change all console docs to always use lazy commands?

**Comment by viion** [comment]
I've just encountered this exact issue, following the docs everythings works up until you require services, unsure if this is a similar issue and the error is not clear. For example:

**This works fine**
```php
<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestCommand extends Command
{
    // ...
    protected function configure()
    {
        $this
            ->setName('app:test')
            ->setDescription('Test command');
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
    }
}
```

**This errors with message: There are no commands defined in the "app" namespace.**
```php
<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use App\Service\Test;

class TestCommand extends Command
{
    private $test;

    public function __construct(Test $test)
    {
        $this->test = $test;
    }

    protected function configure()
    {
        $this
            ->setName('app:test')
            ->setDescription('Test command');
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
    }
}
```

This should work according to: https://symfony.com/doc/current/console.html#getting-services-from-the-service-container "Getting Services from the Service Container"

PHPStorm notices error: *Missing parent constructor call*, there is a `__construct()` in `Command` which is extended.

You can change your constructor to:

```
public function __construct(Test $test)
{
    parent::__construct('app:test');
    $this->test = $test;
}
```

Which works... Don't really like the parent call.

The main frustrations I ran into it:

- Following the docs will lead you to this problem
- The error message is not obvious, if I didn't have a good IDE I would be confused..

**Comment by nicolas-grekas** [comment]
Yes please, lazy commands all the time!
