### ISSUE TITLE
Missing PHP start tag in the examples given in the getting_started 4.0 documentation

### ISSUE THREAD

**Issue by mohib0306** [symfony/symfony-docs#8848]
The php code start tag `<?php` is missing from the examples in Getting Started 4.0 documentation. Normally a php developer will notice it instantly and add it by him/herself, but it would be nice to have it in the documentation to make the documentation clean and complete.

**Comment by javiereguiluz** [comment]
@mohib0306 you are right! However, we did this on purpose. We never include the opening/closing PHP tags in code examples to make them easier to read.

We've discussed about this a lot in the past (for example in https://github.com/symfony/symfony-docs/pull/4686 and https://github.com/symfony/symfony-docs/pull/8324) and we finally decided to keep doing this (to not include the opening/closing tags).

The good news is that we've improved Symfony code to display better error messages when someone forgets the opening PHP tag. So, I'm closing this issue as "can't fix" but we hope you understand the reasons. Thank you!
