### ISSUE TITLE
compiler passes doc bug report

### ISSUE THREAD

**Issue by eb22fbb4** [symfony/symfony-docs#8852]
https://symfony.com/doc/current/service_container/compiler_passes.html

The code for example ``Kernel::build`` is not in ``Symfony/Component/DependencyInjection/Compiler/CompilerPassInterface``.

http://api.symfony.com/4.0/Symfony/Component/DependencyInjection/Compiler/CompilerPassInterface.html

**Comment by xabbuh** [comment]
good catch, see #8853

**Comment by xabbuh** [comment]
fixed in #8814
