### ISSUE TITLE
[Console] points to missing API method interact

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#8869]
This page https://symfony.com/doc/current/console.html
`interact() (optional)
    This method is executed after initialize() and before execute()`
points to http://api.symfony.com/4.0/Symfony/Component/Console/Command/Command.html#method_interact but there is no interact method

I think something has gone wrong with the API because execute() is also missing but i do see it in the code on master branch. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Command/Command.php#L171

**Comment by xabbuh** [comment]
This is an issue with how the API docs are generated (see #7138). Thank you for reporting, but I am going to close here nonetheless as having one issue to track this problem is enough. :)
