### ISSUE TITLE
"Consider creating multiple small applications" needs some clarification

### ISSUE THREAD

**Issue by Kwadz** [symfony/symfony-docs#8877]
The [Symfony 4 documentation](https://symfony.com/doc/current/configuration/multiple_kernels.html) states:

> Creating applications with multiple kernels is no longer recommended by Symfony. Consider creating multiple small applications instead.

However, in [this comment](https://github.com/symfony/symfony-standard/issues/584#issuecomment-23148928), at the "Application vs Project" section, Fabien Potencier told:
> So, instead of creating several application in one project, it's often much easier and sensible to just create several projects.

So, here are we talking about multiple small applications or multiple small projects? I think some clarifications are needed. 

The article [Symfony 4: Monolith vs Micro](http://fabien.potencier.org/symfony4-monolith-vs-micro.html) gives some clue but it's still not clear...

**Comment by javiereguiluz** [comment]
The Fabien comment you linked is from 2013, so I'd say we can ignore it because too many things changed since then.

Here you have a more recent comment from Fabien about this: https://github.com/symfony/flex/issues/110#issuecomment-309833181

Flex doesn't support or care about multi-kernels ... so we should recommend to create full featured and independent applications, which by the way in Symfony 4 is great because apps are so small by default!

So, do you think this caution note needs more clarification? Thanks

**Comment by Kwadz** [comment]
The problem is that apparently in the past we used to use the term project which can contain one application or more:

> I envisioned a Symfony2 world where a project would have more than one application. So, app/ would
just be the default and first application of your project.

So, we could understand that a project can contain multiple applications, and as we know an application can contains multiple kernels.

However, if I am not wrong, it seems that now we use the term application to mean the project.
So, can you confirm that now an application = a project?

To be honest I never appreciated the term project to define an IT application, even if it's so widely used, because the real definition of a project in the common language is something that is not existing yet.

Anyway, in the caution note, if we mean an application as a project, no I don't think it needs more clarification.

**Comment by javiereguiluz** [comment]
@Kwadz I can confirm that throughout the docs we use "project" and "app" indifferently.
