### ISSUE TITLE
The Quick Tour Version: 4.0. Missing Information

### ISSUE THREAD

**Issue by stevespages** [symfony/symfony-docs#8889]
Early in this document it sais "Open the src/Controller/DefaultController.php file". The document does not have any information prior to this about which app should be used for this. I created two Symfony apps: composer create-project symfony/symfony-demo and  composer create-project symfony/skeleton my_project. Neither symfony-demo or my_project appear to have the file: src/Controller/DefaultController.php.

Unless I have misunderstood the situation it seems that you are assuming that we have downloaded a particular Symfony app which has this file in it but you have not advised us as to what this app is and where we can get it.

Sorry if I have misunderstood this, Steve

**Comment by weaverryan** [comment]
Hey @stevespages! You're absolutely right. The quick tour is the last section we haven't updated yet for 4.0. I'm actually working on it right now - and we have another issue that's tracking it :).

Thanks!

**Comment by stevespages** [comment]
Thanks for your reply. I am totally new to frameworks and have spent the
last couple of weeks trying to learn Symfony. I can see that keeping the
documentation up to date with the latest version is a major challenge.

**Comment by javiereguiluz** [comment]
@stevespages we're really sorry that this Quick Tour doc is still pending to be updated. However, you don't really need it to start with Symfony. You can read these six quick introductory chapters to get up and running with Symfony:

![symfony-getting-started](https://user-images.githubusercontent.com/73419/34069772-18f3fde0-e258-11e7-90b1-5f5d6ba0d3b3.png)

**Comment by stevespages** [comment]
Thanks for that, Steve
