### ISSUE TITLE
Update authentication-guard-methods.png

### ISSUE THREAD

**Issue by jonag** [symfony/symfony-docs#8903]
I think the diagram displayed on [this page](https://symfony.com/doc/current/security/guard_authentication.html#the-guard-authenticator-methods) should be updated to display the call to the method `supports` [introduced in Symfony 3.4](https://symfony.com/blog/new-in-symfony-3-4-guard-authentication-improvements).

**Comment by javiereguiluz** [comment]
Fixed by #9244.
