### ISSUE TITLE
Complete the "How to Work with multiple Entity Managers and Connections" documentation to warn about impossibility of relationship between entities of different entity managers

### ISSUE THREAD

**Issue by Levure** [symfony/symfony-docs#8904]
Hello !

Having searched a long time about this problem, I would like to suggest to add a warning block, or at least a sentence in the "**How to Work with multiple Entity Managers and Connections**" page  (https://symfony.com/doc/3.4/doctrine/multiple_entity_managers.html).

Shouldn't we add a sentence to warn that Doctrine is unable to do "entities relationship" if the entities are managed by different entity-managers, and (_if another solution exist_) another sentence and a link to redirect the reader to a workaround solution to manage such situation ?

As a beginner (sorry), I feel uncomfortable in altering the documentation, in order to avoid misguiding other users.

**Comment by javiereguiluz** [comment]
@Levure thanks for reporting this. It's true that it needs some clarification. Apparently, associations across entity managers don't work ... but there are some alternative solutions. See #8907.
