### ISSUE TITLE
Where to put acl-bundle documentation

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#8906]
In #8433 we removed the acl part of the security bundle documentation, which makes acl fully undocumented. 
Could we add an `acl` reference alongside the `security` one, as for monolog-bundle and others?

**Comment by javiereguiluz** [comment]
Given that Symfony has made a strong statement against ACL ... even "kicking them out" of the main code and repository, I don't think we should add the docs on symfony.com. If other people agree, the docs could be created inside the ACL repository and using Markdown, so they are perfectly rendered on GitHub.

**Comment by javiereguiluz** [comment]
I'm closing this in favor of https://github.com/symfony/acl-bundle/pull/8 which moves the ACL docs to the ACL bundle.
