### ISSUE TITLE
Having issues autowiring CsrfTokenManagerInterface into AbstractFormLoginAuthenticator

### ISSUE THREAD

**Issue by jonasarts** [symfony/symfony-docs#8911]
I'm implementing the form login example with csrf token from

https://symfony.com/doc/current/security/guard_authentication.html#guard-csrf-protection

See the chapter Adding CSRF Protection

But I can not make the constructor working with symfony autowiring

    __construct(CsrfTokenManagerInterface $csrfTokenManager)

Cannot autowire service "App\Security\FormLoginAuthenticator": argument "$csrfTokenManager" of method "__construct()" references interface "Symfony\Component\Security\Csrf\CsrfTokenManagerInterface" but no such service exists. It cannot be auto-registered because it is from a different root namespace.

Do I need to use manual wiring or is there an autowiring way for the CsrfTokenManagerInterface?

Either way, the following documentation probably will need an update:

> Then, type-hint CsrfTokenManagerInterface in your __construct() method (or manually configure the Symfony\Component\Security\Csrf\CsrfTokenManagerInterface service to be passed) and add the following logic

As I get it to work with symfony, I'm glad to propose a documentation pull request.

**Comment by javiereguiluz** [comment]
I just checked `debug:autowiring` and I found this, so I guess your code should work:

![debug-autowiring](https://user-images.githubusercontent.com/73419/34223579-284b0a34-e5c0-11e7-932c-9bbfa693d51c.png)

**Comment by xabbuh** [comment]
Did you install the `symfony/security-csrf` (or `symfony/security`) package?

**Comment by jonasarts** [comment]
I did install the `symfony/security` package. (And just now tested to add the `symfony/security-csrf` one.)
The `composer.json` shows me both in the require section

    "symfony/security-bundle": "^4.0",
    "symfony/security-csrf": "^4.0",

But i only get the error

    [ERROR] No autowirable classes or interfaces found matching "csrf"

on running `bin/console debug:autowire csrf`. So I probably have an issue with the `symfony/security` package recepie? A quick test on an empty fresh symfony 4 installation with a quick `composer require symfony/security` did also show me the above error.

**Comment by jonasarts** [comment]
I found the solution in `config/packages/framework.yaml`. There you need to enable csrf_protection!

    framework:
        csrf_protection: ~

After that, `bin/console debug:autowire csrf` works and the CsrfTokenManagerInterface is present as a service.
This is probably worth to mention in the docs?
