### ISSUE TITLE
In Symfony 3.4 is deprecated to not implement reset() in data collectors

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8935]
In Sf 3.4 is deprecated to not implement `reset()` in data collectors. In 4.0 is mandatory to do that.

In https://symfony.com/doc/4.0/profiler/data_collector.html we document `reset()` but in https://symfony.com/doc/3.4/profiler/data_collector.html we don't even mention it.

Should we:

* Mention in 3.4 that you must implement `reset()`?
* Update 3.4 fully as 4.0 to explain the `reset()` method?

**Comment by xabbuh** [comment]
For 4.0, this was done in #8882. Should we do some changes for 3.4?

**Comment by javiereguiluz** [comment]
Fixed by #8969.
