### ISSUE TITLE
Consider if we should mention the Symfony console autocomplete utility

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8936]
This is the project: https://github.com/bamarni/symfony-console-autocomplete

Caveats: autocomplete is not easy to setup and it doesn't work on some OS or shells.

**Comment by lockland** [comment]
Would you do something about this?

**Comment by javiereguiluz** [comment]
Let's close this to wait until Symfony makes a decision about autocompleting in general. See https://github.com/symfony/symfony/issues/38275
