### ISSUE TITLE
Composer version required

### ISSUE THREAD

**Issue by jzawadzki** [symfony/symfony-docs#8938]
Hi,

I've noticed that nowhere on symfony docs is stated that installation on flex requires composer version `>=1.1` (because of `composer-plugin-api >1.1` requirement).
This is how installation looks like on 1.0.0 (beside note on `symfony/thanks` there is no other info on update needed):

![composer](https://user-images.githubusercontent.com/1220891/34413868-5fb9a0ee-ebe6-11e7-8e5e-2539c4f68dfc.png)

This wouldn't be an issue normally, however ubuntu's `apt-get install composer` still installs `1.0.0-beta2` by default and looks like some people use that option of composer installation.

I would recommend adding information about that somewhere (not sure where tho).

**Comment by javiereguiluz** [comment]
Composer 1.0.0-beta2 was released on 2016-03-27 and the required 1.1.0 version on 2016-05-10. I'd say that we could ignore this error because developers need to update their Composer regularly ... but some people may consider this unacceptable. Let's wait to read more opinions!

**Comment by xabbuh** [comment]
If that's not an issue that pops up too often, I am against mentioning this in the docs. By the way, the error message you get is quite self-explanatory to me.

**Comment by javiereguiluz** [comment]
OK, let's close it for now and we'll reconsider this decision as soon as we receive more issue reports like this. Thanks!
