### ISSUE TITLE
In "How to Unit Test your Forms", where does `fromArray()` come from?

### ISSUE THREAD

**Issue by Kwadz** [symfony/symfony-docs#8970]
In [this example](https://symfony.com/doc/master/form/unit_testing.html#the-basics) we can notice the `fromArray()` method to hydrate `$object`. However this method exists only for a Propel entity.

If I am not wrong we should mention that this method has to be manually created for Doctrine entities if the user want to test forms like this.

What do you think?

**Comment by javiereguiluz** [comment]
Thanks for reporting this error. I'm trying to fix this in #8971.
