### ISSUE TITLE
"How to Unit Test your Forms" page needs improvement

### ISSUE THREAD

**Issue by Kwadz** [symfony/symfony-docs#8972]
The title of [this page](https://symfony.com/doc/master/form/unit_testing.html) suggests that we explain how to do a unit test for a form while the given example is not a unit test. A real unit test should only contain one SUT (Subject Under Test) and everything else should be a mock.

**Comment by javiereguiluz** [comment]
Also, commented by @wouterj in #8971:

> It's quite complex if you don't understand forms well and I think it's not a good example of writing tests (and btw, it's not a Unit test at all if written like this)

**Comment by javiereguiluz** [comment]
Just asking: does it make any sense at all to unit test a Symfony Form? The basic internal working of the form is guaranteed to work (because we test it in Symfony repo) so shouldn't you just test forms in functional or integration tests only?

**Comment by Kwadz** [comment]
> just test forms in functional or integration tests only
Totally agree
