### ISSUE TITLE
[DX] Showing cross component features

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-docs#8975]
Currently on [the components page](https://symfony.com/components), we have a very clear overview of what Symfony has to offer. However, I'm currently missing the cross component features. I was working on removing `symfony/symfony` from my application, wrote a bash one-liner to fetch all references I could find and run the application, ofc I was missing the Yaml dependency, because _I_ don't refer to it, but the DI does with the `YamlLoader`.

Once I got everything to work, I noticed `N/A` in my WDT where usually the request time is displayed. Clicking on it would cause a 500 error. Turns out, I was missing the Stopwatch component for this feature to work.

There are a lot of features that work once another package is installed (which is really awesome). However, there's no overview on which features work this way and what packages they require. Now that we have Flex, I think it's really important to document this and save developers a lot of time figuring out how or what.

One step further than docs, possible the packages should somehow define this, so that exception messages could get hints about this (I think we already have something similar to this in the error handler).

**Comment by ostrolucky** [comment]
Just for reference, stopwatch issue fix has been done in https://github.com/symfony/symfony/pull/25526

**Comment by iltar** [comment]
It won't tell me how to get the timings though, it's not clear that you need the Stopwatch component for that (I'm glad this is fixed though).

**Comment by javiereguiluz** [comment]
@iltar yes, we're going to reword some docs to better separate the contents for using a stand-alone component and using them inside a Symfony apps alongside other components. This will be a long-term goal and will spread across multiple PRs, so I'm closing this issue because it's too generic and not actionable. Cheers!
