### ISSUE TITLE
PSR-1 incorrectly cited as recommending CamelCase properties

### ISSUE THREAD

**Issue by aweddleton** [symfony/symfony-docs#8991]
In the Serializer documentation [here](https://symfony.com/doc/master/components/serializer.html) it says

> However, PSR-1 specifies that the preferred style for PHP properties and methods is CamelCase.

Regarding properties this seem to not match [PSR-1](http://www.php-fig.org/psr/psr-1/), though, which says

> 4.2. Properties
> This guide intentionally avoids any recommendation regarding the use of $StudlyCaps, $camelCase, or $under_score property names.

**Comment by javiereguiluz** [comment]
Fixed by #8995.
