### ISSUE TITLE
Need for introductory information about parameters

### ISSUE THREAD

**Issue by voltel** [symfony/symfony-docs#8996]
I couldn't figure out what parameters are concerned in ["Accessing the Container Directly" section](https://symfony.com/doc/current/controller.html#accessing-the-container-directly): from `.env` file, `services.yaml` file, or somewhere else. I raise this issue by @weaverryan recommendation.  

As far as I understand, this is an introductory article, so some basic information about parameters would be of help. My suggestion is to include the `services.yaml` file with some parameters set, and then demonstrate how it's possible to reach them from within a controller. 
It'd would be super cool, if it were explained with a real-life example, when this feature might be useful. I often find it confusing when there's a tool you have no clear idea where to use, or what it's for.

Related to this, [in a section just above, "Fetching Services"](https://symfony.com/doc/current/controller.html#fetching-services), at the end of a section, there's a Note block (with red explanation mark). As a person who learned English as a second language, I find it obscure and hard to understand. 
So, my suggestion is to find another way to convey the idea (re-phrase it) and provide examples: one how it's supposed to work, and another – the "wrong" way. And again, it'd be cool to see the case where reaching some parameter (`'kernel.debug'` in this case) would be of benefit.
 
On a side note, I suggest styling code blocks with "wrong" approaches (with "this won't work" comment) somewhat differently (e.g. grayish background), since when browsing the pages for clues (when for example, I want to find a way to do something in a page I read some time ago), somehow I read wrong solutions in haste. It's not a big problem, but why not make browsing the topics visually simpler.

**Comment by weaverryan** [comment]
Thanks for opening this! I agree with your conclusions :). So:

1) I believe we’re actually going to remove the accessing the container directly section. So this will remove the reference to parameters

2) instead of the warning below that you mentioned, yes, we should show an example. But I think we should show getParameter() being used (which only works with Controller in 4.0, but I think will Work for AbstractController in 4.1).
