### ISSUE TITLE
[FrameworkBundle][Routing] Use a PSR-11 container in FrameworkBundle Router

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9006]
This is probably irrelevant for Docs, but let's review the examples related to this change. See https://github.com/symfony/symfony/pull/24738

Maybe @ogizanagi can confirm if this is an internal thing and "irrelevant" for Symfony Docs. Thanks!

**Comment by ogizanagi** [comment]
Hey! Sorry I missed this issue.
This is mainly internal indeed. It actually opens the base Router class to be used with any PSR-11 container for lazy-loading the `routing.loader` service and fetching parameters, but it's still part of the FrameworkBundle and people probably won't have many use-cases for this. Until we get a request about it and decide to move it to the Router component, I think this is indeed irrelevant for Symfony Docs.

**Comment by javiereguiluz** [comment]
Thanks for the detailed explanation Maxime! Closing then as "won't fix". Thanks!
