### ISSUE TITLE
[FrameworkBundle] Add atom editor to IDE config

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9009]
**This issue is reserved for first-time contributors**. If you send a pull request and you aren't a first-time contributor to Symfony Docs, we'll need to close your pull request. Thanks for understanding it!

-----

See https://github.com/symfony/symfony/pull/25415

To fix this issue, you need to update this file: `reference/configuration/framework.rst` in the `master` branch. To do so, you can simply browse https://symfony.com/doc/master/reference/configuration/framework.html and click on `Edit this page`.

Then, add `atom` to the list of editors displayed in the `ide` option: https://symfony.com/doc/master/reference/configuration/framework.html#ide

**Comment by alcaeus** [comment]
Linking #9043 and #9044 for the sake of completeness.

**Comment by javiereguiluz** [comment]
Closing as fixed by #9043.
