### ISSUE TITLE
[DI][FrameworkBundle] Add PSR-11 "ContainerBag" to access parameters as-a-service

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9010]
Added PSR-11 `ContainerBagInterface` and its `ContainerBag` implementation to access parameters as-a-service. See https://github.com/symfony/symfony/pull/25288

**Comment by weaverryan** [comment]
Might be a dup of #8999 :)

Btw, I think we should mention `ParameterBagInterface`, not `ContainerBagInterface`. I believe they both can be used to access this service, but `ParameterBagInterface` is a better name.

**Comment by javiereguiluz** [comment]
Closing as duplicate and I'm going to update the PR to use `ParameterBagInterface`. Thanks!
