### ISSUE TITLE
Document the Workflow deprecations

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9017]
https://github.com/symfony/symfony/pull/24751:

* Deprecated the `add` method in favor of the `addWorkflow` method in `Workflow\Registry`.
* Deprecated `SupportStrategyInterface` in favor of `WorkflowSupportStrategyInterface`.
* Deprecated the class `ClassInstanceSupportStrategy` in favor of the class `InstanceOfSupportStrategy`.

@Simperfit do you think you could update the Workflow examples in the `master` branch of the docs to update for these deprecations? In addition to updating the example contents, we'd need to add cautions like this:

```rst
.. versionadded:: 4.1
    The ``addWorkflow()`` method was introduced in Symfony 4.1. In previous
    Symfony versions it was called ``add()``.
```

Thanks!

**Comment by Simperfit** [comment]
Yes, I'm going to do it tomorrow, could you please assign this issue to me ?

**Comment by javiereguiluz** [comment]
@Simperfit thanks! ... and sorry because GitHub doesn't let me assign it to you :(

**Comment by Simperfit** [comment]
@javiereguiluz this one can be close I think, there are no usage of SupportStrategyInterface or ClassInstanceSupportStrategy in the docs. but we need to take care of https://github.com/symfony/symfony-docs/issues/7439

**Comment by javiereguiluz** [comment]
You are right. Closing then. Thanks!
