### ISSUE TITLE
[VarDumper] add a GMP caster in order to cast GMP resources into string or integer

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9021]
https://github.com/symfony/symfony/pull/25237

Not sure if it needs to be mentioned explicitly in the docs.

**Comment by Simperfit** [comment]
If we need to do it, please ping me, ill do it ;).

**Comment by javiereguiluz** [comment]
After reviewing the docs, the only place where we link to VarDumper/Caster/* classes is this section: https://symfony.com/doc/current/components/var_dumper/advanced.html#adding-semantics-with-metadata  But my guess is that this GMP Caster doesn't fit that section contents. If that's the case, we should close this as "won't fix". Thanks!

**Comment by javiereguiluz** [comment]
I've rechecked this and we don't document the built-in casters anywhere in the docs, so let's close this as "won't fix". Thanks!
