### ISSUE TITLE
[RFC] Should we remove the default values of config options in references?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9065]
Problems with default values:

* Sometimes Symfony applies some logic to set the default value (if you have this and that component, then this is `true`; otherwise it's `false`). It's complex to document that and it will be outdated the moment Symfony code changes.
* Sometimes default values are completely different according to the environment (e.g. https://github.com/symfony/symfony-docs/pull/9064/files)

What if we remove all default values and we just leave the data type (and the possible values if they are restricted).

**Comment by xabbuh** [comment]
I would not drop the default values entirely. IMO it helps to not configure useless options in your application (because you just need the default values).

**Comment by javiereguiluz** [comment]
@xabbuh and what about this change -> https://github.com/symfony/symfony-docs/pull/9064/files  That default value is correct in some cases (prod) but not in others (dev). Given that the reference is about Symfony framework, not components, the default values are hard to explain: it depend on environment and other dynamic conditions.

**Comment by xabbuh** [comment]
I think using the `kernel.debug` parameter as the default value in the documentation could be an option.

**Comment by javiereguiluz** [comment]
OK, let's close this then. Thanks.
