### ISSUE TITLE
[FrameworkBundle] add cache.app.simple psr simple cache

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9097]
See https://github.com/symfony/symfony/pull/25710.

@dmaicher asked in the original PR if he should update the docs. If you can't do this, we'd need at least some explanation about what this change does exactly for end users and, if needed, a quick example. Thank you!

**Comment by dmaicher** [comment]
I can look into it :blush: 

Where should it go though? I cannot find anything in the docs for the `cache.app`?

https://symfony.com/doc/current/components/cache.html

**Comment by nicolas-grekas** [comment]
This issue is deeper: we need a new page to document the framework bundle integration in the cache component actually.

**Comment by nicolas-grekas** [comment]
We're going to fade out PSR16 actually, so no need to add any doc for it.
See https://github.com/symfony/symfony/issues/28918
