### ISSUE TITLE
[Cache] New array adapter cache

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#9110]
See symfony/symfony#25892

Also, our reference.rst section about the different cache adapters isn't great :).

> The cache adapter used by the ``cache.app`` service. The FrameworkBundle
ships with multiple adapters: ``apcu``, ``doctrine``, ``system``, ``filesystem``,
``psr6``, ``redis`` and ``memcached``.

It's not clear what values you would *actually* use, like `cache.adapter.redis`. It's also not very clear how you would configure, for example, the memcached connection details.

**Comment by javiereguiluz** [comment]
Fixed by #9202 and #9203.
