### ISSUE TITLE
NelmioApiDocBundle Link for documentation 2.x is broken

### ISSUE THREAD

**Issue by Sydney-o9** [symfony/symfony-docs#9113]
Hi Team,

The Documentation link for NelmioApiDocBundle 2.x is broken.

See https://symfony.com/doc/2.8/bundles/NelmioApiDocBundle/index.html

Issue was reported in https://github.com/nelmio/NelmioApiDocBundle/issues/1195

**Comment by xabbuh** [comment]
It looks like https://symfony.com/doc/2.x/bundles/NelmioApiDocBundle/index.html mistakenly redirects to https://symfony.com/doc/2.8/bundles/NelmioApiDocBundle/index.html.

**Comment by javiereguiluz** [comment]
Thanks for reporting. We fixed this yesterday. Closing then.
