### ISSUE TITLE
DBAL 3.x removes PDO dependency

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9128]
Main deprecations:

* The support of `PDO::PARAM_*`, `PDO::FETCH_*`, `PDO::CASE_*` and `PDO::PARAM_INPUT_OUTPUT` constants in the DBAL API is removed.
* `\Doctrine\DBAL\Driver\PDOStatement` does not extend `\PDOStatement` anymore.

See https://github.com/doctrine/dbal/pull/2958

**Comment by stof** [comment]
Even the part meant to be shipped in the next 2.x are not there yet, so it is too early to rewrite the doc to use the new PARAM and FETCH constants rather than the PDO ones (we might even want to wait until these constants are part of a *released* 2.x version)

**Comment by javiereguiluz** [comment]
Closing in favor of the meta-issue #9401.
