### ISSUE TITLE
IvoryCKEditorBundle not compatible with symfony 4

### ISSUE THREAD

**Issue by cybernet** [symfony/symfony-docs#9133]
[IvoryCKEditorBundle](https://symfony.com/doc/current/bundles/IvoryCKEditorBundle/index.html) not compatible with symfony 4 due to `symfony/form` and yet it still has a dedicated page

in my opinion it should pe stated that it is not compatible on docs page :)

**Comment by javiereguiluz** [comment]
Closing this as fixed because this bundle was adopted by other community (https://symfony.com/blog/finding-a-new-home-for-ivoryckeditorbundle) and we've updated the docs and all the links on symfony.com. Thanks!
