### ISSUE TITLE
Warn of environmental variable inclusion in phpinfo/super globals dump

### ISSUE THREAD

**Issue by michaelcullum** [symfony/symfony-docs#9237]
We should warn in the docs that dumping `$_SERVER`, `$_ENV`, or outputting `phpinfo()` would disclose contents of environmental variables which, as of Symfony 4 best practices, would include database credentials.

Originally commented upon: https://twitter.com/mdekrijger/status/958688583858212865

**Comment by javiereguiluz** [comment]
Fixed by #9245.
