### ISSUE TITLE
An "s" is missing in a attribute data-list="#email-field-list"

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony-docs#9272]
An "s" is missing in a attribute `data-list="#email-field-list"`
In this case, in order for it to work properly, it must have the same ID that it has in UL.

### Collection template
https://symfony.com/doc/current/reference/forms/types/collection.html#prototype
https://prnt.sc/if8q7f

Thanks

**Comment by javiereguiluz** [comment]
Fixed by #9276.
