### ISSUE TITLE
Add info about about skeleton and website-skeleton?

### ISSUE THREAD

**Issue by uikolas** [symfony/symfony-docs#9284]
What about adding some info in: https://symfony.com/doc/master/setup.html about  differences `symfony/website-skeleton` and `symfony/skeleton` ?
It's only mentioned in blog whats the difference between them: https://symfony.com/blog/the-end-of-the-symfony-standard-edition
Maybe it will be usefull for new users to choose what they really need?

**Comment by javiereguiluz** [comment]
Fixed by #9444. We now use the `website-skeleton` by default, but also mention the `skeleton` alternative in the main installation article.
