### ISSUE TITLE
[TwigBundle] Deprecating "false" in favor of "kernel.debug" as default value of "strict_variable"

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9291]
See https://github.com/symfony/symfony/pull/25780. We should probably update the config reference of TwigBundle.

**Comment by yceruto** [comment]
For now, I think there are no changes up to 5.0:
* https://github.com/symfony/symfony/pull/25780/files#diff-78ce19fd8437c9c93513086cad6d9d10R53

**Comment by javiereguiluz** [comment]
You are right. We'll need to make this change for Symfony 5.0 (to be released on November 2019). Closing.
