### ISSUE TITLE
Add clearer examples of images (and other non-CSS/JS assets) handling

### ISSUE THREAD

**Issue by rgembalik** [symfony/symfony-docs#9332]
Currently, there is not much on images in the documentation, especially from "Getting Started" pages. Right now googling for "Symfony 4 assets" or "Symfony 4 images" points you to https://github.com/symfony/symfony-docs/blob/4.0/best_practices/web-assets.rst which talks about images being web asset and that web assets should be kept in `/assets` directory. 

This is a bit confusing because usually images won't be moved into `/public`.  Even if they will (due to reference in `js` or `scss`), it won't be clear for less webpack-experienced programmers when it happens and when it don't. `assets:install` command won't look in `/assets` directory either to copy them into `/public` which is even more confusing. 

Either I am missing some bits of docs, or there is a gap in Symfony 4 docs when it comes to using images with Encore and/or Symfony Flex. From experience, I think that a lot of people will avoid putting anything from `/public` to a repo, so if it's indeed a recommended solution for handling non-CSS/js assets then I think it should be directly pointed out in the docs whenever assets directory is being mentioned. 

I also think there should be built in solution for handling image assets which will truly allow keeping all assets in one directory - be it support in `assets:install` command, or rebuilt webpack configs (e.g. something like `.addStaticEntry('static', './assets/static').enableStaticFilesCopying()` ).

**Comment by javiereguiluz** [comment]
Closing as fixed for the reasons given in https://github.com/symfony/symfony-docs/issues/9565#issuecomment-460166842. Thanks.
