### ISSUE TITLE
Explain how to rehash passwords from Bcrypt to Argon2i

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9356]
As requested in https://symfony.com/blog/new-in-symfony-4-1-argon2i-configuration#comment-22135 it'd be great to have some docs about how to update an existing app to use Argon2i hasher instead of Bcrypt.

This is a very serious security topic, so we need help from people who has done this with success in a non-trivial real-world app. Thanks!

**Comment by alterphp** [comment]
This blog post shows a way to change password hash encoding : http://blog.michaelperrin.fr/2017/01/17/migrating-users-to-a-secure-hashing-algorithm-in-symfony/

It's simple and well explained.

**Comment by mssimi** [comment]
@alterphp This is not good solution. If you want secure your passwords you want that now not when someone logs in, that is too late, besides majority of users may not log in ever again.

Correct me if I am wrong, but the only secure way to migrate your passwords to new hashing algorithm without user's interaction is chaining hashing algorithms, this means hash your md5 to bcrypt or whatever is your before/after script. And on login hash password with same chain of hashing algorithms.

**Comment by alterphp** [comment]
From a non secure hashing, you're right : secure ASAP (your method seems good !). But to move to another hash, I think chaining hashing iterations may not be sustainable. Maybe using both methods is a good practice, change ASAP by chaining and move to new hashing method as described in the tutorial.

+1 for hash algorithm chains in security config !

**Comment by dkarlovi** [comment]
See also https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2788 for a deep dive by @stof.

**Comment by dkarlovi** [comment]
Implemented into Sylius by @pamil, maybe some part of the feature can be pulled into Symfony?
https://github.com/Sylius/Sylius/pull/10084

**Comment by OskarStark** [comment]
Or better the proposal by @nicolas-grekas:
https://github.com/symfony/symfony/issues/31139

**Comment by OskarStark** [comment]
Or better the proposal by @nicolas-grekas:
https://github.com/symfony/symfony/issues/31139

**Comment by javiereguiluz** [comment]
I'm closing this in favor of #11656, which will document the new `needsRehash()` feature introduced by Symfony.
