### ISSUE TITLE
[Form] "Component" doc does not link to "Framework" doc

### ISSUE THREAD

**Issue by Alsciende** [symfony/symfony-docs#9357]
The Form component documentation at http://symfony.com/doc/current/components/form.html does not explain how and why users can define their forms as PHP classes. 

The main article explains how to build and use a form right inside the controller code, with no mention of Form classes or the `$formFactory->createForm()` method.

The "Learn more" links don't mention "Forms as classes".

The first "Learn more" article (http://symfony.com/doc/2.8/form/action_method.html) mentions "When using a form type class...", but at that point, the reader hasn't been presented with that option and, likely, does not understand the mention.

None of the "Learn more" articles, as far as I can say, explain how to build and use a form as a PHP class.

Nevertheless, the "Best Practices - Forms" article (https://symfony.com/doc/current/best_practices/forms.html) recommends "defining forms as PHP classes." (and explains how to do that in a few lines and an example).

I think there's an article missing here, right at the top of the "Learn more" section of the Form component, which explains "How to define your forms as PHP classes".

**Comment by yceruto** [comment]
> The main article explains how to build and use a form right inside the controller code, with no mention of Form classes 

This is the main article: https://symfony.com/doc/current/forms.html:
> This example shows you how to build your form directly in the controller. Later, in the "Creating Form Classes" section, you'll learn how to build your form in a standalone class, which is recommended as your form becomes reusable.

**Comment by Alsciende** [comment]
Ok. Is there a reason why the "main" article talks about Form Classes, but the "component" article does not talk about them? In the end, the "Learn more" section is more or less the same for both articles. Wouldn't it be good to have a "Creating Form Classes" section at the end of the "component" article?

**Comment by Alsciende** [comment]
@yceruto the title of the issue is "Form **component** documentation does not describe Form classes". I believe the "component" main article is at http://symfony.com/doc/current/components/form.html.

**Comment by javiereguiluz** [comment]
In the components articles we try to explain how to use the component out of a Symfony app. But we don't explain the component itself (except sometimes where the component is a utility equally used inside and outside of an app: Console, Yaml, Filesystem, Finder, etc.)  So the rest of component articles should be super concise and explain almost nothing. That may be the reason.

**Comment by codedmonkey** [comment]
I have to agree, the seperation between the component pages and framework pages is understandable, but not always clear.

**Comment by javiereguiluz** [comment]
Fixed by #9840.
