### ISSUE TITLE
[Serializer] Add a MaxDepth handler

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9380]
There's a new `max_depth_handler` config option, but as usual the pull request description is very poor and doesn't include any example: https://github.com/symfony/symfony/pull/26108

**Comment by dunglas** [comment]
I'll handle this @javiereguiluz.
There is an usage example here anyway: https://github.com/symfony/symfony/pull/26108/files#diff-383be450d98e45fa294e0527b2e44640R635

**Comment by javiereguiluz** [comment]
Fixed by #9427.
