### ISSUE TITLE
[BrowserKit] add a way to switch to ajax for one request

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9381]
Let's wait a bit before documenting this because someone (🙄) has asked to rethink the proposed implementation: https://github.com/symfony/symfony/pull/24778#issuecomment-369879079

https://github.com/symfony/symfony/pull/24778

**Comment by Simperfit** [comment]
I'll document it when the new PR is merged.

**Comment by javiereguiluz** [comment]
This is now ready and the new implementation is https://github.com/symfony/symfony/pull/26381
