### ISSUE TITLE
[PropertyInfo] Added support for extracting type from constructor

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9382]
The pull request has no description and no examples 😢 

https://github.com/symfony/symfony/pull/25605

**Comment by javiereguiluz** [comment]
We are looking for volunteers to contribute these docs. Thanks!

**Comment by LS05** [comment]
This line [https://github.com/lyrixx/symfony/blob/adcb25ec01a0e164e269ef2d8903afa70181d05d/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L233](ReflectionExtractor.php#L233) has a call to `getName` on the `\ReflectionType` class.
But I cannot find it here in the official documentation http://php.net/manual/en/class.reflectiontype.php
Am I wrong? Am I looking at the wrong class? :)

**Comment by kunicmarko20** [comment]
If I recall correctly the method is there, it is just not documented.

**Comment by kunicmarko20** [comment]
@LS05 https://github.com/phpstan/phpstan/issues/1133
