### ISSUE TITLE
dead link to doctrine documentation

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#9400]
https://github.com/symfony/symfony-docs/blob/master/doctrine/reverse_engineering.rst#how-to-generate-entities-from-an-existing-database

`Doctrine tools documentation` points to http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/tools.html#reverse-engineering

The page is there but the reverse engineering section is gone. Also the commands that are used like `doctrine:mapping:convert` are nowhere to be found.

Possibly this functionality is removed from doctrine (i didn't investigate) and this whole documentation page is no longer valid.

**Comment by javiereguiluz** [comment]
Yes, this feature was removed from Doctrine. We'll need to rethink all this.

**Comment by flip111** [comment]
Do you know a link to where this removal was discussed ?

**Comment by javiereguiluz** [comment]
This is the commit: https://github.com/doctrine/doctrine2/commit/e4ce75a8dc775f9b7414668b1fac2759d661992f I cannot find any public discussion.

**Comment by javiereguiluz** [comment]
We've created a meta-issue to list all the things removed by Doctrine ... so I'm closing this in favor of that meta-issue: #9401. Thanks!
