### ISSUE TITLE
Update docs for latest Doctrine removals

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9401]
Latest Doctrine versions are removing features that we use on Symfony Docs. We should double check everything, remove no longer relevant docs and provide alternatives when possible:

### Changes already included in Doctrine 2.x

*(we can already make these changes in Symfony Docs)*

* [x] Removed support for entity namespace aliases: `App:User` no longer works, use `User::class`  or `App\Entity\User`: https://github.com/doctrine/doctrine2/commit/63cb8018dd1a889be4e08a31fad1e76f4cc876d0
* [x] Removed support for same-namespace class resolution. Now you must use `::class` in annotations: https://github.com/doctrine/doctrine2/commit/cd590f2f3309d15c680079076838a55ecd30dab1
  ```diff
  /**
  -    @ORM\ManyToOne(targetEntity="NotifyChangedEntity", inversedBy="items") */
  +    @ORM\ManyToOne(targetEntity=NotifyChangedEntity::class, inversedBy="items") 
  */
  ```
* [x] Removed support for named queries: https://github.com/doctrine/doctrine2/commit/e6557cbee3c318090c7993944c8aa5b56fa17c82
* [x] Removed `EntityManager::copy`: https://github.com/doctrine/doctrine2/commit/c4eb2b016d7beb5ec5ede2bfa1971752a4a3f35b
* [x] Removed reverse engineering (`convert:mapping`) and entity generation (`generate:entity`): https://github.com/doctrine/doctrine2/commit/e4ce75a8dc775f9b7414668b1fac2759d661992f

### Changes planned for the upcoming Doctrine 3.x

*(please don't make any of these changes until Doctrine 3 is released)*

* [ ] Removed the YAML metadata driver: you can no longer define the entity using YAML. Only XML and annotations. https://github.com/doctrine/doctrine2/commit/bc0c0986c5e8b250a40f601f3e404d5abd4dd34c
* [ ] Removed `EntityManager::detach`: https://github.com/doctrine/doctrine2/commit/df397e1d685b22aa11942a7f55ba18cd16abd9f0
* [ ] Removed PDO dependency: the support of `PDO::PARAM_*`, `PDO::FETCH_*`, `PDO::CASE_*` and `PDO::PARAM_INPUT_OUTPUT` constants in the DBAL API is removed. \Doctrine\DBAL\Driver\PDOStatement does not extend \PDOStatement anymore: https://github.com/doctrine/dbal/pull/2958

**Comment by flip111** [comment]
Some explanation about the entity code generator removal can be found here https://github.com/doctrine/doctrine2/issues/6418

**Comment by stof** [comment]
Part of these updates can be done already (for instance, using `::class` in annotation works in Doctrine 2.x already). But some of these are related to BC breaks in the future Doctrine 3, which has no ETA yet (and so working on the update right now is not worth it)

**Comment by stof** [comment]
btw, I'm quite sure some of these changes won't impact the Symfony doc:

- `EntityManager::copy` was *never* implemented in Doctrine, so it is probably not documented anywhere in Symfony (and should be removed immediately if it is)
- named queries are a very advanced feature of Doctrine (for which I never found a use case btw), and I don't think we document it either.

**Comment by stof** [comment]
`EntityManager::copy` is doable now. It is removed from 3.x, but it **never** worked in 2.x (see the removed implementation: `throw new \BadMethodCallException("Not implemented.");`). But I don't think we have any doc using it, because of that (so probably nothing to do).

regarding the mapping conversion and the entity generation, I think we should already work today on removing them from the Symfony documentation. The Doctrine team discourages their usage since years, so we should not push for it.

**Comment by javiereguiluz** [comment]
Here's a list of everything removed in DBAL 3.0: https://github.com/doctrine/dbal/pull/3518

**Comment by javiereguiluz** [comment]
I'm closing this one as fixed because I've verified that we no longer use features removed in 2.x. For the future 3.x, we'll take care of that when it's released. Thanks!
