### ISSUE TITLE
Document that console.command tag doesn’t support command aliases

### ISSUE THREAD

**Issue by hacfi** [symfony/symfony-docs#9421]
I just noticed that using the `console.command` tag command aliases set via `setAliases` in `configure` are not taken into account. This should be documented on the `console/commands_as_services.rst` / http://symfony.com/doc/current/console/commands_as_services.html page. Or do you think that’s a bug of Symfony? If so [Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/DependencyInjection/AddConsoleCommandPass.php) needs to call `getAliases` of each command instance.

cc @bcremer @chalasr @nicolas-grekas

**Comment by javiereguiluz** [comment]
I'd say this is a bug. I've opened https://github.com/symfony/symfony/issues/26495 so the community can verify or reject this. I'm closing here, but if this is not considered a bug but a thing to document, we'll reopen. Thanks!

**Comment by chalasr** [comment]
Should be reopened

**Comment by javiereguiluz** [comment]
Fixed by #9971.
