### ISSUE TITLE
SQL error following doc steps: can't create "not null" column with null default value

### ISSUE THREAD

**Issue by liarco** [symfony/symfony-docs#9424]
Dear Sirs,
I was reading the documentation, following the steps one-by-one, then I got stuck with a SQL error.
I'm a very newbie with Symfony, but I think that there's something missing in the annotation here: https://github.com/symfony/symfony-docs/blame/master/doctrine.rst#L244

I was using SQLite, the error complains about the impossibility to create a new "NOT NULL" column with NULL default value.

Changing my code to the following solved the issue, but I'm not sure that's what was intended:
```
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;
```

Thank you for your time.

**Comment by javiereguiluz** [comment]
@liarco thanks for reporting this. Sadly this is a bit confusing to me. In the `current` version docs, we show this:

```rst
.. code-block:: terminal

    $ php bin/console make:migration

This time, the SQL in the generated file will look like this:

.. code-block:: sql

    ALTER TABLE product ADD description LONGTEXT NOT NULL
```

So this field is a `NOT NULL` (and in the later examples we always add a value for this column). That's why adding `nullable=true` is confusing to me because it's not compatible with the rest of the article.

If you execute the migration commands, does it still fail when using SQLite? Thanks!

**Comment by liarco** [comment]
Hi @javiereguiluz, thank you for your reply.
I tried again with my current system (i formatted my computer recently with an update version: macOS 10.13.4) and followed the steps again on a freshly installed workspace (just followed https://symfony.com/doc/current/setup.html) before going straight to docrtine.

It's the same as before, I attach a screenshot of my terminal so that you can see exactly what it tells me:
![symfony-doctrine-error](https://user-images.githubusercontent.com/1532277/40607971-4819998a-626a-11e8-80a7-993da13fda08.jpg)

It seems like a "text" field cannot be "NOT NULL" if you don't specify a default value (at least in SQLite)... am I wrong?

**Comment by javiereguiluz** [comment]
Thanks for debugging this! Sadly this looks like a SQLite bug/limitation: https://laracasts.com/discuss/channels/general-discussion/migrations-sqlite-general-error-1-cannot-add-a-not-null-column-with-default-value-null  So maybe we can add a note about that, but I'm not sure we can fix it for real.

**Comment by liarco** [comment]
That's what I was afraid of, but I pointed it out because this error might discourage a newbie trying to follow the documentation and not understanding the given error.

I think that a little side-note would be helpful (and absolutely enough) in this case. :)

Thank you for your time!
