### ISSUE TITLE
Coding standards: Importing PHP built-in classes

### ISSUE THREAD

**Issue by umulmrum** [symfony/symfony-docs#9426]
Concerning the coding standards (https://symfony.com/doc/current/contributing/code/standards.html).

The example shows that built-in PHP classes are not imported but preceded with a backslash on every use, but the rules do not mention this in any way unless I didn't miss it. PSR-1 and PSR-2 also seem to not handle this.

So my question is, what is the rule on imports? Always import classes but never import built-in classes?

Thanks for a clarification. I can submit a PR if required and requested.

**Comment by xabbuh** [comment]
Our rule is indeed not to add `use` statements for classes from the global namespace.

**Comment by javiereguiluz** [comment]
@umulmrum what @xabbuh said is correct. Do you think we should change something in the contribution guide? If yes, could you please create a pull request? That's be awesome! Thanks.
