### ISSUE TITLE
[Validator] Deprecate use of `Locale` validation constraint without setting "canonicalize" option to `true`

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9453]
We recently documented this feature, so we just need to add that not using it is deprecated. See https://github.com/symfony/symfony/pull/26075.

**Comment by snoek09** [comment]
Wasn't this fixed in https://github.com/symfony/symfony-docs/pull/9248/files#diff-08df604c59d5284048fac6277839ca0dR104?

**Comment by xabbuh** [comment]
fixed by #9248
