### ISSUE TITLE
[Routing] i18n routing

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9458]
Lots of config examples here: https://github.com/symfony/symfony/pull/26143

Instead of adding this to normal routing docs, it may be better to create a separate article for this feature? Maybe not ... the explanation can be really concise. Let's think about this.

**Comment by dominikhajduk** [comment]
proposal: https://github.com/symfony/symfony-docs/pull/9510

**Comment by javiereguiluz** [comment]
Fixed by #9515.
