### ISSUE TITLE
[Config] Introduce BuilderAwareInterface

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9460]
See https://github.com/symfony/symfony/pull/26308

**Comment by javiereguiluz** [comment]
@ro0NL I'm a bit confused about your work in https://github.com/symfony/symfony/pull/26308  Do you think we should make any change in the Symfony Docs about that change ... or is it an internal Symfony change? Thanks!

**Comment by ro0NL** [comment]
@javiereguiluz i dont think it needs any real attention. We dont explain custom node types at https://symfony.com/doc/current/components/config/definition.html so nothing new there.

I mentioned the PR in my blog about custom node types https://medium.com/@ro0NL/creating-a-custom-configuration-node-type-with-symfony-config-376e471b8053 though. Perhaps it can serve as a base for new docs :)

**Comment by javiereguiluz** [comment]
Thanks for the comments Roland! Closing it as "won't fix" then. Cheers!
