### ISSUE TITLE
[Workflow] Transition blockers support

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#9465]
Transition blockers allow to fetch the reason why applying a transition was blocked (see symfony/symfony#26076).

**Comment by noniagriconomie** [comment]
there is https://symfony.com/doc/master/workflow/usage.html#transition-blockers
is this issue still relevant?

**Comment by xabbuh** [comment]
Thank you for checking. Let's close here then as this seems to be solved.
