### ISSUE TITLE
[VarDumper] Document the Server Dumper feature

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony-docs#9474]
https://github.com/symfony/symfony/pull/23831 was merged :)

The PR description should be up-to-date but If I can be of any help, don't hesitate to ping me if you need more info!

(In case nobody is up to take it, I may give it a try but I'm far from being an expert at writing documentation 😅 )

**Comment by javiereguiluz** [comment]
Fixed by #9783.
