### ISSUE TITLE
[Serializer] Added a ConstraintViolationListNormalizer

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9480]
https://github.com/symfony/symfony/pull/22150

It normalizes ConstraintViolationListInterface instances according to RFC7807.

**Comment by javiereguiluz** [comment]
We need a volunteer to contribute these docs. Someone expert in the Serializer component: @dunglas, @lyrixx, @Simperfit? Thanks!

**Comment by javiereguiluz** [comment]
I think you are right. In the future we may add some brief mention somewhere if we think it's necessary. Thanks!

**Comment by dunglas** [comment]
We should at least add it to the list of available normalizer. People using directly the component have no way to discover this feature.

**Comment by javiereguiluz** [comment]
Let's reopen then. But we'll need a volunteer to do this. Thanks!

**Comment by javiereguiluz** [comment]
Fixed by #9855.

**Comment by dunglas** [comment]
Thank you very much @javiereguiluz
