### ISSUE TITLE
Codes examples colors

### ISSUE THREAD

**Issue by Krazitchek** [symfony/symfony-docs#9524]
Why changing what was good ?... new theme for codes samples rendering in documentation is less readable than "before" because of some dark font colors (dark blue) on black background...

**Comment by javiereguiluz** [comment]
We haven't made any recent change about that (at least on purpose!). Could you please share a screenshot of the problematic code listings? Thanks!

**Comment by Krazitchek** [comment]
In commit 8c84bb1 we read that JS and CSS was added.

What i did:

- Download last 2.7 documentation archive from github
- Build (make html) documentation with python-sphinx using fabpot/sphinx-php.git
- Copy assets directory in generated html directory to get css and js
- Launch index.html

In browser console i see this error: TypeError: $.getQueryParameters is not a function

Screenshot before:
![sf-before](https://user-images.githubusercontent.com/11500208/38144229-33cbc8a8-3444-11e8-8732-b3c82909df8c.png)

Same screenshot wow:
![sf-now](https://user-images.githubusercontent.com/11500208/38144246-3a2c3002-3444-11e8-9ac3-3bf6507de770.png)

**Comment by javiereguiluz** [comment]
I honestly don't understand what's going on here. I literally took the same CSS and JS files used on symfony.com and added to the repo. Could you please use the browser's inspector on the code which shows a wrong highlight and see if it's because of some missing style or some missing CSS, etc. Thanks!

**Comment by javiereguiluz** [comment]
@Krazitchek in #9972 we've switched the default theme used to build docs locally. Now it doesn't look like symfony.com at all ... but at least everything works and the generated docs are fully usable. That's why I'm closing this issue. Thanks!
