### ISSUE TITLE
caution in dev mode passwords exposed

### ISSUE THREAD

**Issue by biji** [symfony/symfony-docs#9540]
Please add caution for new users that in dev mode, passwords are exposed by symfony profiler

http://symfony.com/doc/current/configuration/external_parameters.html

And there is no other way to hide it except go to production mode

**Comment by EarthSchlange** [comment]
A little warning about database ENV variable being exposed in profiler would be nice to add for new users who are not aware of it. There is already a caution for [Environment Variables in Production](http://symfony.com/doc/current/configuration/external_parameters.html#configuring-environment-variables-in-production) for a similar issue, so I don't see any harm in adding a warning explaining that their database variable will be exposed in profiler when working in dev mode.

**Comment by javiereguiluz** [comment]
We're trying to fix this in #9793. What do you think? Thanks!

**Comment by javiereguiluz** [comment]
Fixed by #9793.
