### ISSUE TITLE
[Website] FosUserBundle navigation broken

### ISSUE THREAD

**Issue by codedmonkey** [symfony/symfony-docs#9555]
It seems that the navigation between FosUserBundle versions is broken. The docs sent me to the following url: https://symfony.com/doc/current/bundles/FOSUserBundle/index.html which shows documentation for version 1.3, but the navigation says it version 2.0. For some reason both version 2.0 and 1.3 are set as "current" versions in some way.

The 2.0 documentation is still available as master branch at https://symfony.com/doc/master/bundles/FOSUserBundle/index.html but visiting either the 1.3 or 2.0 urls redirect to the faulty "current" version.

**Comment by javiereguiluz** [comment]
We updated the config for this bundle a while ago and I think it's now working as expected. Please, reopen if it isn't. Thanks!
