### ISSUE TITLE
ChoiceType has BC Breaks

### ISSUE THREAD

**Issue by marcel-burkhard** [symfony/symfony-docs#9573]
the values array was flipped in symfony 3

shouldn't it be mentioned here:
https://github.com/symfony/symfony-docs/blob/3.4/setup/upgrade_major.rst ?

**Comment by xabbuh** [comment]
We do not document all the BC breaks in that document. It is just a generic document that describes what you need to take into account. All the BC breaks themselves are documented in the `UPGRADE-*.md` files in the Symfony code which you will basically follow by making your application/code deprecation free.
