### ISSUE TITLE
Bootstrap Validator component documentation

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#958]
Recommended sections:

* Introduction
* Installation
* Usage

**Comment by weaverryan** [comment]
This was started at #3710, but Wouter didn't have time to finish. BUT, he's invited anyone to continue by building off of his work.

**Comment by stof** [comment]
Anyone willing to work on it ? It is important to have doc for all components IMO.

**Comment by weaverryan** [comment]
I agree - Validator strikes me as a component that is quite usable standalone anyways - I would also like this.

**Comment by xabbuh** [comment]
The docs finally made it into the repo thanks to the work of many people (see the result in #6798).
