### ISSUE TITLE
Duplicate SymfonyMakerBundle bundle

### ISSUE THREAD

**Issue by lex111** [symfony/symfony-docs#9584]
On page https://symfony.com/doc/bundles/ twice displayed SymfonyMakerBundle bundle

![image](https://user-images.githubusercontent.com/4408379/38638513-2691d758-3dd7-11e8-8ea6-f2df352c15f9.png)

![image](https://user-images.githubusercontent.com/4408379/38638479-0a2f4cd0-3dd7-11e8-8ada-cd647a17d9c0.png)

If you remove it from the section "Popular Bundles from the Symfony Community" then in each column will be displayed exactly 5 bundles.

**Comment by javiereguiluz** [comment]
We like the Maker bundle so much that we needed to list it twice! ... just kidding! 😄  Thanks for reporting this issue. Although the fix is simple, it will take me some time because these days I'm busy and out of my regular office. Cheers!

**Comment by javiereguiluz** [comment]
I almost forgot about this error ... but it's been finally fixed and the merged fix will be deployed soon to symfony.com. Thanks again for alerting us about this. Cheers!
