### ISSUE TITLE
[symfony.com] Blog post content accidentally replaced?

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony-docs#9588]
https://symfony.com/blog/symfony-3-3-0-curated-new-features

The content of the blog post is actually about Symfony 3.4.0 (released in November 2017), but the title, slug, date, and comments are all about Symfony 3.3.0 (released in May 2017).

Edit: Found the blog post about Symfony 3.4: https://symfony.com/blog/symfony-3-4-curated-new-features

**Comment by javiereguiluz** [comment]
Thanks for reporting this problem. I don't know what could have happened here. At the end, I recovered the original blog post content using the "Wayback Machine": https://web.archive.org/web/20170529223455/https://symfony.com/blog/symfony-3-3-0-curated-new-features
