### ISSUE TITLE
Fos userbundle always mention to configure in `app/config/config.yml

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony-docs#9590]
fos userbundle always mention to configure in `app/config/config.yml` that doesn’t exists in [Sf4](https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle) and people are confuse see [here](https://stackoverflow.com/questions/49799385/symfony4-app-config-config-yml-is-missing)

**Comment by xabbuh** [comment]
[Sorry](https://github.com/symfony/symfony-docs/issues/9589#issuecomment-380903699) :)
