### ISSUE TITLE
[Configuration] Missing info about %env(resolve:MYVAR)% const: int: base64: file: json:

### ISSUE THREAD

**Issue by msheakoski** [symfony/symfony-docs#9601]
The section [How to Set external Parameters in the Service Container](https://symfony.com/doc/current/configuration/external_parameters.html) is missing some very useful documentation about `%env(MYVAR)%` operators such as `resolve:`, `int:`, `base64:` covered in the blog post [New in Symfony 3.4: Advanced environment variables](https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables). I couldn't find any other mention of it aside from that blog post and seeing it in the Doctrine bundle recipe.

**Comment by xabbuh** [comment]
You are absolutely right. I am just going to close here though as we already have #8382 to keep track of it. :)
