### ISSUE TITLE
flex loading files in routes and the route definition without prefix wins over the route definition with a prefix.

### ISSUE THREAD

**Issue by mackou** [symfony/symfony-docs#9608]
Hello : 
As you can see in this issue : https://github.com/symfony/symfony/issues/26949
It seems that all routing files in config/routes are loaded automatically and it will ignore the prefix.
So you should group routing files by prefix in different folders :

> This is working
>----------------
>```yaml
>app_security:
>    resource: 'security/security.yaml'
>    prefix: /security
>```
>![image](https://user-images.githubusercontent.com/38428205/38820338-ec6332e6-419d-11e8-8064-e6aa93d5ef6f.png)

>This is not working
>-----------------
>```yaml
>app_security:
>    resource: 'security.yaml'
>    prefix: /security
>```
>![image](https://user-images.githubusercontent.com/38428205/38812044-7d1c46fa-418b-11e8-93bf-86ff6791c409.png)
------------------
Quoting @stof : 
> Well, the Flex kernel is indeed loading all files in routes itself. and this means that the loading of the file done in the kernel might happen after the loading of the file done by your own file (which is likely here, as security.yml comes after routes.yml and so the route definition without prefix wins over the route definition with a prefix.
>
>If you want to split the routes into separate files loaded with a prefix, putting them in a subfolder is indeed a solution.
>
>I suggest adding a warning in the doc about it.

**Comment by HeahDude** [comment]
Closing here as fixed by #9523 (also reported in #9609). Thanks
