### ISSUE TITLE
[Messenger] Added a AMQP adapter

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9633]
See https://github.com/symfony/symfony/pull/26632 (note: this PR triggers a GitHub unicorn error to me ... use private navigation in your browser to fix it):

> In order to give a great DX for simple needs such as sending messages through an AMQP broker such as RabbitMq, we should ship an AMQP adapter for the Messenger component within Symfony Core. It should be as simple as this proposal. We don't need to handle more specific use-cases nor brokers as other adapters such as the enqueue adapter can also be used.

**Comment by PReimers** [comment]
As far as I can see this is already implemented.

https://symfony.com/doc/4.1/messenger.html#transports
