### ISSUE TITLE
[PhpUnitBridge] Search for other SYMFONY_* env vars

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9637]
See https://github.com/symfony/symfony/pull/26800 and https://github.com/symfony/symfony/pull/26811

Hi @lyrixx! Your original pull request at https://github.com/symfony/symfony/pull/26811 didn't contain any description, so it's hard for us to document it. Could you please tell us which changes or improvements does this PR introduce for end-users apps? Thank you!

**Comment by lyrixx** [comment]
Hello.

Actually, when one install the phpunit bridge and if she/he wants to use phrophecy also, she/he needs to set the `SYMFONY_PHPUNIT_REMOVE` env var to `symfony/yaml`. And this, *each** time she/he runs the Test Suite. And to me it's really annoying.

With my PR, we could put this env var in the `phpunit.xml(.dist)`. 

ref https://symfony.com/doc/current/components/phpunit_bridge.html#modified-phpunit-script

**Comment by javiereguiluz** [comment]
Fixed by #9643.
