### ISSUE TITLE
[Messenger] Remove the Doctrine middleware configuration from the FrameworkBundle

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9638]
See https://github.com/symfony/symfony/pull/26684. Should we make any change in the just merged Messenger docs? Maybe @sroze can help us answer that question. Thanks!

**Comment by sroze** [comment]
I'd wait for this one to be merged first (your review is welcome by the way): https://github.com/symfony/symfony/pull/26864.

**Comment by sroze** [comment]
No change needed to the document, this can be closed.
