### ISSUE TITLE
[Messenger] Add a `MessageHandlerInterface` (multiple messages + auto-configuration)

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9639]
Another PR that we must review to check if current Messenger docs include it: https://github.com/symfony/symfony/pull/26685

**Comment by tomtomau** [comment]
There's still some discussion going on here that I'll keep an eye on. 

In the meantime I'm going to pick this up and add information about the MessageHandlerInterface as I don't feel the [documentation about Registering Handlers](https://github.com/symfony/symfony-docs/blob/master/messenger.rst#registering-handlers) adequately explains the[ logic around registering based on Message type logic](https://github.com/symfony/symfony/blob/fe199317dade04b561ed358315fe0b6eba6c7cf8/src/Symfony/Component/Messenger/DependencyInjection/MessengerPass.php#L117)
