### ISSUE TITLE
[Messenger] Added a middleware that validates messages

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9641]
See https://github.com/symfony/symfony/pull/26648

@Nyholm I know you are busy with lots of contributions to open source projects ... but I hope you can take some time before the end of May to document this in time for Symfony 4.1 release. Thank you!

**Comment by Nyholm** [comment]
Oh, I forgot about this. I just came back from vacation. 

Thank you @sroze

**Comment by sroze** [comment]
Hope you enjoyed :)
