### ISSUE TITLE
[HttpFoundation] introduced detailed exceptions to replace the generic FileException

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9642]
See https://github.com/symfony/symfony/pull/26475

> added `CannotWriteFileException`, `ExtensionFileException`, `FormSizeFileException`, `IniSizeFileException`, `NoFileException`, `NoTmpDirFileException`, `PartialFileException` to handle failed `UploadedFile`.

We may need to update some file upload code sample.

**Comment by LS05** [comment]
Is it possible for me to work on this? :)

**Comment by LS05** [comment]
@xabbuh I'll do it :) I really want to contribute to Symfony!

**Comment by xabbuh** [comment]
Don't hesitate to ask if you have any questions. You can also join us on the [Symfony Slack](https://symfony.com/slack-invite) in in the `#documentation` channel.
