### ISSUE TITLE
Allow to not to set a response to private automatically

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9647]
https://github.com/symfony/symfony/pull/26681

@Toflar changes related to HTTP Cache are always a bit tricky for us ... could you please help us making the required changes in docs or helping us know what to change? Thanks!

**Comment by Toflar** [comment]
Sure! Will submit a PR!

**Comment by Toflar** [comment]
Done 😃

**Comment by javiereguiluz** [comment]
Fixed by #9667.
