### ISSUE TITLE
[Form] Add choice_translation_locale option for Intl choice types

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9657]
https://github.com/symfony/symfony/pull/26825

> This PR adds possibility to show the list of elements for a custom locale different to the current one and proposes also deprecate the ChoiceLoaderInterface implementation from all of them, moving it to a separate class.

@yceruto will you have some time before Symfony 4.1 is released at the end of May to work on a PR to document this feature? Thanks!

**Comment by yceruto** [comment]
Sure, I'll do it soon.
