### ISSUE TITLE
[Doctrine] price property is an integer and a float

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#9677]
On [4.0+ documentation](https://symfony.com/doc/4.0/doctrine.html), an entity is created and its `price` property is an integer:

```php
    /**
     * @ORM\Column(type="integer")
     */
    private $price;
```

A note explain this:

> Confused why the price is an integer? Don't worry: this is just an example. But, storing prices as integers (e.g. 100 = $1 USD) can avoid rounding issues.

But when the [entity is persisted](https://symfony.com/doc/4.0/doctrine.html#persisting-objects-to-the-database) a float number is provided:

```php
        $product->setPrice(19.99);
```

I think that this is inconsistent.

---

It's related to #9487.

I can provide a PR.

**Comment by javiereguiluz** [comment]
Fixed by #9680.
