### ISSUE TITLE
[PhpUnitBridge] Usage inconsistent between flex & symfony.com

### ISSUE THREAD

**Issue by kiler129** [symfony/symfony-docs#9679]
Installing `phpunit-bridge` calls for running `bin/phpunit`:
![image](https://user-images.githubusercontent.com/1227834/39206619-8ed6f654-47c3-11e8-9509-99c3dfd982df.png)

This is inconsistent with https://symfony.com/doc/current/components/phpunit_bridge.html, since it mentions only `./vendor/bin/simple-phpunit`:
![image](https://user-images.githubusercontent.com/1227834/39206687-b3df0b1c-47c3-11e8-9c35-ebae8e4db2ad.png)

The worst of this issue is `bin/phpunit` is incompatible with e.g. PhpStorm due to duplicated shebang line (but this is a separate issue reported as https://github.com/symfony/symfony/issues/27035).

**Comment by javiereguiluz** [comment]
@kiler129 that's correct! We're partially fixing this in #9452 ... but we'll need another pull request to fix the other occurrences.

**Comment by javiereguiluz** [comment]
After checking this agin, I think now this is correct. The error was using ./bin/phpunit in Flex and ./vendor/bin/simple-phpunit in the docs. But now we display ./bin/phpunit in the docs about the framework (https://symfony.com/doc/current/testing.html).

However, in the component docs (https://symfony.com/doc/current/components/phpunit_bridge.html) we must keep using ./vendor/bin/simple-phpunit beucase thre's no Flex, no framework, nothing ... just the component. So let's close this as fixed and we'll reopen if you disagree. Thanks!
