### ISSUE TITLE
Should we use full Composer package names or Symfony Flex shortcuts?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9693]
Related to https://github.com/symfony/symfony-docs/pull/9691 and other similar PRs we've received. Our idea was to always assume that the reader of 3.4+ docs was using Flex, so we use shortcuts everywhere. Should we keep doing that?

My vote is to keep using shortcuts, but let's ask to doc maintainers: @weaverryan @xabbuh @wouterj @HeahDude. Thanks!

**Comment by weaverryan** [comment]
I lean slightly towards the longer versions... it avoids issues for some users, and I think people copy-and-paste most of the time anyways. So, that's my vote, but I DO like how cool the aliases look :p

**Comment by liviubalan** [comment]
I think that a good idea is to use Composer format for Symfony versions <4.0 and the Flex format for Symfony versions >=4.0. According to [Flex documentation](https://symfony.com/doc/3.4/setup/flex.html):

> The only caveat is that Symfony Flex requires that applications use the following directory structure, which is the same used by default in Symfony 4

I vote for:
-Composer format for Symfony <4.0
-Flex format for Symfony 4.0+

**Comment by javiereguiluz** [comment]
Yesterday we discussed about this on Symfony Slack. Most people (all of them in fact) were against Flex shortcuts. The analogy I used was that these shortcuts are like a lottery: when using it you don't know which package will be installed. I'm now more and more convinced of not using these shortcuts anywhere in the docs.

**Comment by javiereguiluz** [comment]
Ryan, Wouter and I seem to agree on doing this ... so let's do it! I'm going to prepare the PR right now.

**Comment by javiereguiluz** [comment]
Fixed by #9742.
