### ISSUE TITLE
Missing value in versionadded directive

### ISSUE THREAD

**Issue by lex111** [symfony/symfony-docs#9699]
```
.. versionadded::
    The interactive behavior of the ``make:entity`` command was introduced
    in MakerBundle 1.3.
```

The result is displayed like this:

![image](https://user-images.githubusercontent.com/4408379/39382288-ab5f8b86-4a6d-11e8-87f8-d9be18cae8e9.png)

Source - https://symfony.com/doc/current/doctrine.html#doctrine-adding-mapping

**Comment by javiereguiluz** [comment]
@lex111 thanks for reporting this problem! We're fixing it in #9707.
