### ISSUE TITLE
json-login issues

### ISSUE THREAD

**Issue by josephzhao** [symfony/symfony-docs#9731]
Hello All:

I need help, I have logged in as following code, but the profile still shows the logged in user is anon.

and in twig file app.user is empty.  I am using symfony 4.0.8

( yaml file format in my file is ok, but here display has problem , I am not able to fix it)

Thanks

Joseph

my security.yaml

security:
    encoders:
        App\Entity\Map2u\Core\User: 
            algorithm: bcrypt
            cost: 12
    providers:
        database_users:
            entity: { class: App\Entity\Map2u\Core\User, property: username }

    firewalls:

        main:
            pattern: ^/
            http_basic: ~
            provider: database_users
            anonymous: ~
            json-login:
                # The route name that the login form submits to
                check_path: security_login
                username_path: security.credentials.username
                password_path: security.credentials.password
            logout:
                invalidate_session: true
                # The route name the user can go to in order to logout
                path: security_logout
                # The name of the route to redirect to after logging out
                target: /
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }                
    access_control:
        - { path: '^/(%app_locales%)/admin', roles: ROLE_ADMIN }
        - { path: '^/admin', roles: ROLE_ADMIN }

my controller 

    /**
     * @Route("/login", name="security_login", methods={"POST"})
     */
    public function login(Request $request, UserPasswordEncoderInterface $passwordEncoder): JsonResponse {
      

        if ($request->isMethod('POST')) {
            if (0 === strpos($request->headers->get('Content-Type'), 'application/json')) {

                $data = json_decode($request->getContent(), true);
                $request->request->replace(is_array($data) ? $data : array());
            }

            $security=$request->get("security");
            $credentials=$security['credentials'];
            $_username = $credentials["username"];
            $_password = $credentials["password"];
           
            $user_repository = $this->getDoctrine()->getRepository(User::class); 
            $user = $user_repository->findOneByUsernameOrEmail(array('username' => $_username));
                                
            if (!$user) {
                return new JsonResponse(array(
                    'Username doesnt exists', Response::HTTP_UNAUTHORIZED, array('Content-type' => 'application/json')
                ));
            }

            /// Start verification

            if (!$passwordEncoder->isPasswordValid($user, $_password)) {
                return new JsonResponse(
                        'Username or Password not valid.', Response::HTTP_UNAUTHORIZED, array('Content-type' => 'application/json')
                );
            }
             

            $token = new UsernamePasswordToken($user, null, 'main', $user->getRoles());
         
         
                 $this->get('security.token_storage')->setToken($token);

            $this->get('session')->set('_security_main', serialize($token));
          
            // Fire the login event manually
            $event = new InteractiveLoginEvent($request, $token);
            $dispatcher = new EventDispatcher();
      
       
            try {
                //   $dispatcher->addListener('foo.action', function ($event);
                    $this->loginManager->logInUser('main', $user);
             
                $dispatcher->dispatch(
                        AuthenticationEvents::AUTHENTICATION_SUCCESS, new AuthenticationEvent($token)
                );
                   $dispatcher->addListener(FOSUserEvents::SECURITY_IMPLICIT_LOGIN, new UserEvent($user, $request));
                //    $dispatcher->dispatch(FOSUserEvents::SECURITY_IMPLICIT_LOGIN, $event);
                $dispatcher->dispatch('fos_user.security.implicit_login', new UserEvent($user, $request));
                $dispatcher->dispatch(SecurityEvents::INTERACTIVE_LOGIN, $event);
                        $dispatcher->dispatch('security.authentication.success', $event);
                  
                  
            } catch (AccountStatusException $ex) {
                // We simply do not authenticate users which do not pass the user
                // checker (not enabled, expired, etc.).
            }

            /*
             * Now the user is authenticated !!!! 
             * Do what you need to do now, like render a view, redirect to route etc.
             */
            return new JsonResponse(
                    'Welcome ' . $user->getUsername(), Response::HTTP_OK, array('Content-type' => 'application/json')
            );
        } else {
            return new JsonResponse(
                    'Welcome edf ', Response::HTTP_OK, array('Content-type' => 'application/json')
            );
        }
    }

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
