### ISSUE TITLE
[DI] Add select specific key from an array resolved env var documentation

### ISSUE THREAD

**Issue by bobvandevijver** [symfony/symfony-docs#9734]
In https://github.com/symfony/symfony/pull/27157, the `key` processor is added. This should also be documented, but currently there is no documentation yet (see #8382, with #9507 as work-in-progress MR). 

When the initial documentation is merged, the new `key` processor should also be added

**Comment by xabbuh** [comment]
Did you mean symfony/symfony#27157?

**Comment by bobvandevijver** [comment]
I did indeed, good catch!

**Comment by nicolas-grekas** [comment]
@bobvandevijver would you mind sending a PR now that this is merged?

**Comment by bobvandevijver** [comment]
@nicolas-grekas I wouldn't, if put it on my list to do this soon!
