### ISSUE TITLE
[PropertyAccessor] Behavior of getValue

### ISSUE THREAD

**Issue by nicolaspetitjean** [symfony/symfony-docs#9747]
Hey !
I was reading [that doc](https://symfony.com/doc/current/components/property_access.html), and it says:

> As you can see, the method will return null if the index does not exists.

I think the doc could mention that the behavior of `PropertyAccessor::getValue` can be configured, meaning if an index is missing, an exception can be thrown (see [27187](https://github.com/symfony/symfony/issues/27187)).
```php
$accessor = new PropertyAccessor(false, true, null);
```

**Comment by ismail1432** [comment]
good point @nicolaspetitjean could you updta edocumentation in this way ?

**Comment by javiereguiluz** [comment]
Fixed by #10095.
