### ISSUE TITLE
render_hinclude problems when activating PHP templating engine

### ISSUE THREAD

**Issue by liviubalan** [symfony/symfony-docs#9790]
When the PHP templating engine is activated (value` framework.templating.engines: ['twig', 'php']` in `config.yml`) when using the code sample

> {{ render_hinclude(controller('...'), {'default': 'Loading...'}) }}

the following errror occures:

> An exception has been thrown during the rendering of a template ("Template name "Loading..." contains invalid characters.").

Maybe a good idea is to show an info/warning when dealing with PHP templating.

See: [How to Embed Asynchronous Content with hinclude.js](https://symfony.com/doc/3.4/templating/hinclude.html)

**Comment by javiereguiluz** [comment]
I've never used `render_hinclude()` or the PHP templating engine ... but isn't this a Symfony bug instead of a code issue?

**Comment by javiereguiluz** [comment]
I've looked into the code of the hinclude renderer and this is what I found:

```php
        $template = isset($options['default']) ? $options['default'] : $this->globalDefaultTemplate;
        if (null !== $this->templating && $template && $this->templateExists($template)) {
            $content = $this->templating->render($template);
        } else {
            $content = $template;
        }
```

Looking at the code it looks like the things explained in the docs should work. So, I'm opening an issue on symfony/symfony to report this as a bug (https://github.com/symfony/symfony/issues/28001). If it's not, we'll reopen here. Thanks!
