### ISSUE TITLE
[Security] Typo in Security Main Page

### ISSUE THREAD

**Issue by intco** [symfony/symfony-docs#9798]
Under the section

Always Check if the User is Logged In

the code:

`use Symfony\Component\Security\Core\User\UserInterface\UserInterface;`

should be

`use Symfony\Component\Security\Core\User\UserInterface;`

**Comment by javiereguiluz** [comment]
@intco good catch! I can confirm that this is a bug. Would you like to fix it yourself to contribute to Symfony? It will only take you 30 seconds. You just need to:

1) Browse this page: https://symfony.com/doc/3.4/security.html  (3.4 is the oldest maintained version that contains the bug)
2) Click on the blue "Edit this page" button at the top right of the page.
3) Fix the `UserInterface` path using GitHub's web interface.
4) Click on the Create Pull Request button and select `3.4` as the branch for it.

Thanks!

**Comment by javiereguiluz** [comment]
Fixed by #9800.
