### ISSUE TITLE
Please add a basic example of running a heavy-duty background task

### ISSUE THREAD

**Issue by arechsteiner** [symfony/symfony-docs#9806]
I've been trying to figure this out for a while now and I've only figured out how *not* to do it.

I believe that the accepted answer on StackOverflow is downright wrong and misleading as it suggests running processes asynchronously. However in the documentation (that is linked in the SO answer it says):

> If a Response is sent before a child process had a chance to complete, the server process will be killed (depending on your OS). It means that your task will be stopped right away. Running an asynchronous process is not the same as running a process that survives its parent process.

Here's the Q/A: https://stackoverflow.com/questions/37733820/running-a-background-task-using-symfony-process-without-having-to-wait-for-the-p

The documentation further states that:

> If you want your process to survive the request/response cycle, you can take advantage of the kernel.terminate event, and run your command synchronously inside this event. Be aware that kernel.terminate is called only if you use PHP-FPM.

However, there isn't really any good example on how to actually do this.

In my case I have a Symfony console command that takes 5 to 300 minutes and I can't for the life of me figure out how to do it *correctly*.

I believe this is a common problem and the information I found was conflicting and incomplete, so it would be a great addition to the docs.

**Comment by javiereguiluz** [comment]
I have a question about this:

> In my case I have a Symfony console command that takes 5 to 300 minutes and I can't for the life of me figure out how to do it correctly.

Do you call that command from your web application (e.g. from a controller or service)? By the way, now that we have the Messenger component, the best solution is probably to use messaging and queues.

**Comment by arechsteiner** [comment]
Yes exactly. The user takes an action and I would like this to trigger a console command that can take seconds to hours. I think this is a common requirement so an example page in the documentation would help newer Symfony developers like myself.

**Comment by xabbuh** [comment]
That's not something that should be triggered synchronously, but you should use some asynchronous queue for it. Using the `kernel.terminate` event for this task, would mean that your PHP FPM pool would be run out of workers really soon as they will soon be busy by performing the background task and thus couldn't serve the requests.

**Comment by theofidry** [comment]
Starting a new process to run it asynchronously as done in the SO answer is indeed not desirable. But that's a case where you use a queue system.

I agree that the doc should be a bit more clear about it, I remember struggling a bit with this the first time I used Symfony as well.

**Comment by arechsteiner** [comment]
Right, as it says in the docs

>That is why it's generally way better not to do any fancy things even after the request is sent, but to use a job queue instead.

So what I'm essentially really missing is that the words "use a job queue instead" become a link to a best-practices article on how to use a job queue with Symfony to perform heavy-duty background tasks. 

Ideally that article would then outrank any Google results that provide hacky solutions such as using an ampersand and redirecting the output to dev/null.

**Comment by javiereguiluz** [comment]
Now that Symfony is pushing the Messenger component and the use of queues, I'm going to close this as "won't fix". Instead of doing things in kernel.terminate, let's use proper queues to delay heavy tasks. This is for example how the new Symfony Mailer will work. Thanks!
