### ISSUE TITLE
Link to an example code line

### ISSUE THREAD

**Issue by roberto910907** [symfony/symfony-docs#9833]
It's possible to implement a way to create a link directly to an example code line inside symfony docs? I'm thinking in something like github does that you can point directly to a specific line and this way it's easier when you want to point what line inside de docs you're talking about.

Ex: `http://symfony.com/doc/current/bundles.html#code-example-create-bundle-L2`

**Comment by javiereguiluz** [comment]
I'm afraid it's not possible to do that. Also, the tooling we use to generate docs is quite complex, so we're not planning to add this feature ourselves.

However, we can add any link to any part of the doc using references:

```rst
Some text here ...

.. _the-reference-id:

More text here ...
```

Now you can link to that section with `/doc/{version}/{slug}.html#the-reference-id`  So we can do that if some section or example is very important, but let's not abuse this and let's not create too many IDs. Cheers!
