### ISSUE TITLE
File permission requirements

### ISSUE THREAD

**Issue by magnetik** [symfony/symfony-docs#9866]
In https://symfony.com/doc/current/setup/file_permissions.html the documentation states:

> If you decide to store log files on disk, you will need to make sure your logs directory

I disagree with the "If", [in the http kernel](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L608), in the `containerBuild` function will try to create this folder even if I do not do anything in the log directory.

I'm not quite sure if this should also be a bug in Symfony side as it does feels quite right to me that the build container function tries to create a log related folder when it might not be used at all.

Thanks

**Comment by javiereguiluz** [comment]
@nicolas-grekas could you please review this issue? It's true that `buildContainer()` tries to create the logs dir in:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L623-L633

I haven't used Symfony without a physical log directory. Is it possible to do that? Thanks!

**Comment by javiereguiluz** [comment]
OK. But is the log dir created even when using the minimalist logger? The docs say that:

> Symfony comes with a minimalist PSR-3 logger: Logger. In conformance with the twelve-factor app methodology, it sends messages starting from the WARNING level to stderr.

https://symfony.com/doc/current/logging.html

**Comment by nicolas-grekas** [comment]
yes, these are two unrelated feature, code wise
