### ISSUE TITLE
[Twig/Templating] Unable to find template "FooBarBundle::template.html.twig"

### ISSUE THREAD

**Issue by mykiwi** [symfony/symfony-docs#9867]
Hi

I created a new Symfony project and added Twig. I also added an external Bundle that use the syntax `FooBarBundle::template.html.twig` and I got this exception:

> Unable to find template "FooBarBundle::template.html.twig" (looked into: /srv/templates, /srv/templates).

To fix this I had to require `symfony/templating` and add this config:

```
framework:
    templating:
        engines: ['twig']
```

Maybe we should document this, and improve the DX with a recipe.

**Comment by javiereguiluz** [comment]
Thanks for reporting this. I don't know if it's just a doc issue or also something to be improved in Symfony. I've created https://github.com/symfony/symfony/issues/27468 to ask the community about it.

**Comment by nicolas-grekas** [comment]
Closing in favor of symfony/symfony#27468, thanks for the report @mykiwi
