### ISSUE TITLE
label_attr on SubmitType

### ISSUE THREAD

**Issue by QuentinCurtet** [symfony/symfony-docs#9894]
Hello,

This doc : https://symfony.com/doc/current/reference/forms/types/submit.html said that it's actually possible to use "label_attr" option on a SubmitType but when we use it, we have the following error : 
`The option "label_attr" does not exist. Defined options are: "attr", "auto_initialize", "block_name", "disabled", "label", "label_format", "translation_domain", "validation_groups".`

Am i using it wrong or is the doc wrong ?

**Comment by xabbuh** [comment]
That's indeed a bug in the documentation. The `label_attr` option (as well as many other options) is provided by the `FormType` class which is the parent type by default for all form types that extend the `AbstractType` class. However, this is not true for the `SubmitType` and `ButtonType` which both do not extend the `FormType`.

**Comment by QuentinCurtet** [comment]
@xabbuh Ok thanks ^^
AFAIK, this option for SubmitType is in the doc since symfony 2.8

**Comment by QuentinCurtet** [comment]
Ok nice :)
