### ISSUE TITLE
What is the best practice for services declaration in Symfony4?

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony-docs#9915]
Hello,

the docs of official [Best Practices](https://symfony.com/doc/current/best_practices/business-logic.html#service-format-yaml) says we should use YAML to declare services, but I have the feeling we should mention autowiring first, and on a very specific use cases, rely on YAML only: am I wrong?

**Comment by javiereguiluz** [comment]
I agree with you that this needs a bit updating. Earlier in the same article we say "use autowiring for services" (https://symfony.com/doc/current/best_practices/business-logic.html#services-naming-and-configuration) so we must change a bit this section to say: "you are using autowiring, so the service config will be minimal or non-existent. However, if you config services manually, use YAML" (or XML, if you prefer it).

**Comment by mickaelandrieu** [comment]
Ok for me, thanks for your answer. I'm working on a course about sf4 and I want to provide code following the Best practices :+1:

**Comment by javiereguiluz** [comment]
Fixed by #9937.
