### ISSUE TITLE
Better doc about overriding third-party translations

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#9923]
Translations are not tied to a bundle, but to a translation domain. So overriding translation is done by putting translations in the same domain (with the same key) in `translations/`.

This needs to be documented explicitly, as even some core team members were thinking that it was more complex than that.

**Comment by yceruto** [comment]
I think that's already clear in this section http://symfony.com/doc/3.4/bundles/override.html#translations

**Comment by stof** [comment]
Well, as you can see from the issue reported by @javiereguiluz in the code repo, the existing doc might not be clear enough.

**Comment by javiereguiluz** [comment]
Fixed by #9935.
