### ISSUE TITLE
How to Build a Traditional Login Form refers viewers to FOSUserBundle

### ISSUE THREAD

**Issue by truckee** [symfony/symfony-docs#9946]
The current 4.1 documentation page [How to Build a Traditional Login Form](http://symfony.com/doc/current/security/form_login_setup.html) includes the text "...you should consider using FOSUserBundle..." with a link to github. My understanding (and experience) is that FOSUserBundle is not (yet?) compatible with Symfony 4.1. I'm not sufficiently competent to fork and rewrite the page so I mention it here.

**Comment by HeahDude** [comment]
I can confirm 2.0 works great, we use the bundle with some Symfony 4 projects. I've pushed [a bug fix when using old controller notation](https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2807) needed in the 2.1 version, but to be tagged though.

Closing here, thanks!

**Comment by XWB** [comment]
@javiereguiluz Indeed, FOSUsrBundle comes with Symfony 4 support since version 2.1 (which was released in February  2018).

**Comment by truckee** [comment]
Please forgive my ignorance, but if FOSUserBundle is compatible with Symfony 4.1, why then does ` composer require friendsofsymfony/user-bundle "~2.1"` in a fresh 4.1 installation result in 
````
 [KO]
Script cache:clear returned with error code 1
!!
!!  In ArrayNode.php line 230:
!!
!!    The child node "db_driver" at path "fos_user" must be configured.
!!
!!
!!

Installation failed, reverting ./composer.json to its original content.
````
Following up on the error message only seems to end up in a rabbit hole. Is there documentation somewhere on a different installation method?

**Comment by stof** [comment]
We are compatible with Symfony 4.1. But as we have some mandatory configuration, registering the bundle automatically with Flex fails (because it gets registered without this mandatory configuration).

**Comment by Nyholm** [comment]
There as been about 4-5 attempts. The most successful one fails cause of requirements on a mailer service. 

https://github.com/symfony/recipes-contrib/pull/270

**Comment by javiereguiluz** [comment]
Let's close this because it looks like a config issue ... that should be solved manually like a traditional Symfony bundle until the Symfony Flex recipe for FOSUserBundle is ready. Thanks!
