### ISSUE TITLE
PHPUnit testing and database isolation

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony-docs#9954]
I'm wondering if it would be ok to update the documentation and mention my bundle as a reference to ease having isolated tests when it comes to database contents.

It could be mentioned on this page: https://symfony.com/doc/current/testing/database.html

This is the bundle: 
https://github.com/dmaicher/doctrine-test-bundle
https://packagist.org/packages/dama/doctrine-test-bundle

It now has over 200.000 installs and seems to be working quite well :blush: 

Its also used on the symfony demo project since a while: https://github.com/symfony/demo/blob/master/composer.json#L32

WDYT? I believe it can be quite useful for many people.

**Comment by javiereguiluz** [comment]
I'm 👍 for mentioning this bundle. It solves a useful problem, it works great, we've tested it ourselves (in the Demo app), it's not too recent (it's tested enough), it's getting popular (lots of downloads), etc.

**Comment by javiereguiluz** [comment]
Fixed by #10026.

**Comment by dmaicher** [comment]
Thanks for fixing this so fast @javiereguiluz :+1: Did not get to it yet myself.
