### ISSUE TITLE
[FrameworkBundle] "messenger" is missing from the framework configuration

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-docs#9963]
In https://github.com/symfony/symfony-docs/blob/master/reference/configuration/framework.rst

**Comment by javiereguiluz** [comment]
I can't do this ... but I can help polish/tweak/fix the docs provided by someone else. Any volunteer? Thanks!

**Comment by javiereguiluz** [comment]
I'm closing this one in favor of #10197 which lists all missing options in Framework reference. Thanks.
